Repository openshift/assisted-service, pull requests merged in 2020-11, with the labels that each got.

#632 OCPBUGSM-19651: fix installation's event message
  internal/bminventory/inventory.go
Labels: approved, lgtm

#629 MGMT-2659 DHCP server changes the VIPs addresses after installation has started - code changes
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/mock_cluster_api.go
  internal/common/db.go
  internal/host/dhcpallocatecmd.go
  internal/host/dhcpallocatecmd_test.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/network/lease_utils.go
  internal/network/lease_utils_test.go
Labels: approved, lgtm

#614 MGMT-2450 Add email domain label to cluster and host metrics
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/transition_test.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_netricsManager_api.go
  models/cluster.go
  pkg/auth/authz_handler.go
  pkg/auth/authz_handler_test.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#525 mgmt-2320 expose logs deleted clusters
  client/installer/get_cluster_parameters.go
  client/installer/list_clusters_parameters.go
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/mock_cluster_api.go
  internal/common/common_unitest_db.go
  internal/host/host.go
  internal/host/mock_host_api.go
  models/cluster.go
  models/host.go
  restapi/embedded_spec.go
  restapi/operations/installer/get_cluster_parameters.go
  restapi/operations/installer/list_clusters_parameters.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#636 Raz/mgmt 2746 unregistered cluster fixes
  internal/cluster/cluster.go
  subsystem/cluster_test.go
Labels: approved, lgtm

#633 Validate user is not installing on OpenStack
  internal/host/host_test.go
  internal/host/refresh_status_preprocessor.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/host/validator.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#631 NO-ISSUE Update Makefile for onprem
  Makefile
Labels: approved, lgtm

#609 MGMT-2137,MGMT-2134 Verify that pull secret includes required registries
  Makefile
  cmd/main.go
  deploy/assisted-service-configmap.yaml
  go.mod
  go.sum
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/validations/mock_validations.go
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
  openshift/template.yaml
  tools/deploy_assisted_installer_configmap.py
  tools/update_bm_cm.py
Labels: approved, lgtm

#634 MGMT-2575 - create installed hosts during day OCP cluster registratio…
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/mock_cluster_api.go
  internal/cluster/registrar.go
  internal/cluster/validations/mock_validations.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/host.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/host/statemachine.go
  internal/host/transition.go
  internal/host/transition_test.go
  internal/metrics/mock_netricsManager_api.go
  pkg/generator/mock_install_config.go
  pkg/k8sclient/k8s_utils.go
  pkg/k8sclient/k8sclient.go
  pkg/k8sclient/mock_k8sclient.go
  pkg/leader/mock_leader_elector.go
  pkg/ocm/mock_authorization.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3wrapper.go
Labels: approved, lgtm

#466 MGMT-2221 Host-specific ignition files
  client/installer/download_host_ignition_parameters.go
  client/installer/download_host_ignition_responses.go
  client/installer/get_host_ignition_parameters.go
  client/installer/get_host_ignition_responses.go
  client/installer/installer_client.go
  go.mod
  go.sum
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/mock_cluster_api.go
  internal/hostutil/host_utils.go
  internal/ignition/dummy.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  mocks/mock_assisted_service.go
  models/host_ignition_params.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/download_host_ignition.go
  restapi/operations/installer/download_host_ignition_parameters.go
  restapi/operations/installer/download_host_ignition_responses.go
  restapi/operations/installer/download_host_ignition_urlbuilder.go
  restapi/operations/installer/get_host_ignition.go
  restapi/operations/installer/get_host_ignition_parameters.go
  restapi/operations/installer/get_host_ignition_responses.go
  restapi/operations/installer/get_host_ignition_urlbuilder.go
  swagger.yaml
Labels: api-review, approved, lgtm

#640 MGMT-2137 Exclude quay.io from pull secret validation by default
  Makefile
Labels: approved, lgtm

#639 MGMT-2770 add inventory to installing-in-progress
  internal/host/host.go
  internal/host/host_test.go
  internal/host/instructionmanager.go
  internal/host/instructionmanager_test.go
Labels: approved, lgtm

#568 MGMT-2331 Host ignition customization
  client/installer/installer_client.go
  client/installer/update_host_ignition_parameters.go
  client/installer/update_host_ignition_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  mocks/mock_assisted_service.go
  models/host.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/update_host_ignition.go
  restapi/operations/installer/update_host_ignition_parameters.go
  restapi/operations/installer/update_host_ignition_responses.go
  restapi/operations/installer/update_host_ignition_urlbuilder.go
  swagger.yaml
Labels: api-review, approved, lgtm

#627 MGMT-2592: enable HW detection of host via new root path
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/inventorycmd.go
  internal/host/inventorycmd_test.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/metrics/mock_netricsManager_api.go
  pkg/generator/mock_install_config.go
  pkg/k8sclient/mock_k8sclient.go
  pkg/leader/mock_leader_elector.go
  pkg/ocm/mock_authorization.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3wrapper.go
Labels: approved, lgtm

#646 MGMT-2704: added nodes to ocp clusterole
  deploy/roles/ocp_role.yaml
Labels: approved, lgtm

#647 MGMT-2657 Fix StartLimitInterval in agent service config
  internal/bminventory/inventory.go
Labels: approved, lgtm

#641 MGMT-2788 - fix installing hosts on day2 cloud cluster, when there is…
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/mock_cluster_api.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/host/statemachine.go
  internal/host/transition.go
  internal/host/transition_test.go
  internal/metrics/mock_netricsManager_api.go
  pkg/generator/mock_install_config.go
  pkg/k8sclient/mock_k8sclient.go
  pkg/leader/mock_leader_elector.go
  pkg/ocm/mock_authorization.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3wrapper.go
Labels: approved, lgtm

#644 MGMT-2462: deploy on ocp - copy livecd
  tools/deploy_assisted_installer.py
Labels: approved, lgtm

#649 MGMT-2821 - day2 on OCP should use pull secret extracted from OCP
  deploy/roles/ocp_role.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  pkg/k8sclient/k8s_utils.go
  pkg/k8sclient/k8sclient.go
  pkg/k8sclient/mock_k8sclient.go
Labels: approved, lgtm

#650 MGMT-2611 - Event on failing validation specify the validation
  internal/host/common.go
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, lgtm

#652 MGMT-2322 Add NTP API to swagger.yaml
  internal/cluster/mock_cluster_api.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/metrics/mock_netricsManager_api.go
  models/ntp_source.go
  models/ntp_synchronization_request.go
  models/ntp_synchronization_response.go
  models/source_state.go
  models/step_type.go
  pkg/generator/mock_install_config.go
  pkg/k8sclient/mock_k8sclient.go
  pkg/leader/mock_leader_elector.go
  pkg/ocm/mock_authorization.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3wrapper.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#654 MGMT-2821 - fix the getting secret k8s implementation
  pkg/k8sclient/k8sclient.go
Labels: approved, lgtm

#653 MGMT-2629 Added secretdump package
  pkg/secretdump/secretdump_test.go
  pkg/secretdump/struct.go
Labels: approved, lgtm

#655 OCPBUGSM-20065 require pull secret in swagger
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validation_test.go
  models/cluster_create_params.go
  pkg/auth/authz_handler_test.go
  restapi/embedded_spec.go
  subsystem/authz_test.go
  subsystem/cluster_test.go
  subsystem/host_test.go
  subsystem/image_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#658 MGMT-2137 Exclude quay.io from pull secret validation in onprem
  onprem-environment
Labels: approved, lgtm

#657 MGMT-2831 adding failed validations in events while statusInfoInsufficientHardware and statusInfoPendingForInput
  internal/host/common.go
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, lgtm

#659 Yevgeny/mgmt 2846
  internal/bminventory/inventory.go
  internal/cluster/mock_cluster_api.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/metrics/mock_netricsManager_api.go
  pkg/generator/mock_install_config.go
  pkg/k8sclient/mock_k8sclient.go
  pkg/leader/mock_leader_elector.go
  pkg/ocm/mock_authorization.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3wrapper.go
Labels: approved, lgtm

#594 NO-ISSUE: Generate and verify onprem configs in sync
  Makefile
  README.md
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  docs/installer-live-iso.md
  hack/verify-latest-onprem-config.sh
  onprem-environment
Labels: approved, lgtm

#660 MGMT-2857: Fix image expiration
  pkg/s3wrapper/client.go
  pkg/s3wrapper/client_test.go
Labels: approved, lgtm

#651 MGMT-2456: new cluster installing-pending-user-action state
  docs/ClusterStatus.dot
  docs/ClusterStatus.png
  internal/cluster/common.go
  internal/cluster/statemachine.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/host/host.go
  internal/host/transition.go
  internal/host/transition_test.go
  models/cluster.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#666 MGMT-2868: refresh stage_updated_at if cluster is pending-user-action
  internal/host/common.go
  internal/host/statemachine.go
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, lgtm

#664 MGMT-2088 Add downstream-change-needed label to Dockerfile changes
  OWNERS
Labels: approved, lgtm

#667 NO-ISSUE Clear created images after Jenkins job
  Jenkinsfile
  Makefile
Labels: approved, lgtm

#668 MGMT-2871 Revert "MGMT-2472 Format bootable disks on Install command …
  internal/host/installcmd.go
  internal/host/installcmd_test.go
Labels: approved, lgtm

#665 MGMT-2464 - update state machine and instruction for day2 OCP
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/common.go
  internal/host/host.go
  internal/host/instructionmanager.go
  internal/host/statemachine.go
  internal/host/transition.go
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, lgtm

#656 MGMT-2624 removed proxy URL print when proxy URL is empty
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  subsystem/image_test.go
Labels: approved, lgtm

#670 MGMT-2633 Stop sending the hostname to the installer
  internal/host/installcmd.go
  internal/host/installcmd_test.go
Labels: approved, lgtm

#671 MGMT-2889 Allow registration of host in error state
  internal/host/statemachine.go
  internal/host/transition_test.go
Labels: approved, lgtm

#599 MGMT-2208 download live ISO for running AI on-prem
  Dockerfile.assisted-service
  client/assisted_install_client.go
  client/assisted_service_iso/assisted_service_iso_client.go
  client/assisted_service_iso/create_i_s_o_and_upload_to_s3_parameters.go
  client/assisted_service_iso/create_i_s_o_and_upload_to_s3_responses.go
  client/assisted_service_iso/download_i_s_o_parameters.go
  client/assisted_service_iso/download_i_s_o_responses.go
  client/assisted_service_iso/get_presigned_for_assisted_service_i_s_o_parameters.go
  client/assisted_service_iso/get_presigned_for_assisted_service_i_s_o_responses.go
  cmd/main.go
  internal/assistedserviceiso/assistedserviceiso_api.go
  internal/assistedserviceiso/assistedserviceiso_api_test.go
  internal/imgexpirer/imgexpirer.go
  models/assisted_service_iso_create_params.go
  pkg/auth/auth_assisted_service_mock_test.go
  pkg/auth/auth_handler_test.go
  pkg/auth/authz_handler_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/assisted_service_iso/create_i_s_o_and_upload_to_s3.go
  restapi/operations/assisted_service_iso/create_i_s_o_and_upload_to_s3_parameters.go
  restapi/operations/assisted_service_iso/create_i_s_o_and_upload_to_s3_responses.go
  restapi/operations/assisted_service_iso/create_i_s_o_and_upload_to_s3_urlbuilder.go
  restapi/operations/assisted_service_iso/download_i_s_o.go
  restapi/operations/assisted_service_iso/download_i_s_o_parameters.go
  restapi/operations/assisted_service_iso/download_i_s_o_responses.go
  restapi/operations/assisted_service_iso/download_i_s_o_urlbuilder.go
  restapi/operations/assisted_service_iso/get_presigned_for_assisted_service_i_s_o.go
  restapi/operations/assisted_service_iso/get_presigned_for_assisted_service_i_s_o_parameters.go
  restapi/operations/assisted_service_iso/get_presigned_for_assisted_service_i_s_o_responses.go
  restapi/operations/assisted_service_iso/get_presigned_for_assisted_service_i_s_o_urlbuilder.go
  subsystem/image_test.go
  swagger.yaml
Labels: api-review, approved, kind/dependency-change, lgtm

#676 OCPBUGSM-20495 ignition generation should skip upload files of disabled hosts
  internal/ignition/dummy.go
  internal/ignition/ignition.go
Labels: approved, lgtm

#677 OCPBUGSM-18132: Added AddForUpdateQueryOption to cancel/reset
  internal/bminventory/inventory.go
Labels: approved, lgtm

#663 MGMT-2384: Add OCP cluster ID to AI cluster entity
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster_test.go
  internal/cluster/mock_cluster_api.go
  internal/cluster/transition.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/ignition/dummy.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/metrics/mock_netricsManager_api.go
  models/cluster.go
  pkg/generator/mock_install_config.go
  pkg/k8sclient/mock_k8sclient.go
  pkg/leader/mock_leader_elector.go
  pkg/ocm/mock_authorization.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3wrapper.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#672 MGMT-2888 Add marker file to bootstrap ignition
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
Labels: approved, lgtm

#683 NO-ISSUE Add unit tests to ignition generation upload to s3
  internal/ignition/ignition_test.go
Labels: approved, lgtm

#626 MGMT-2694: Allow additional installer args per host
  client/installer/installer_client.go
  client/installer/update_host_installer_args_parameters.go
  client/installer/update_host_installer_args_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/installcmd.go
  internal/hostutil/host_utils.go
  internal/hostutil/host_utils_test.go
  mocks/mock_assisted_service.go
  models/host.go
  models/installer_args_params.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/update_host_installer_args.go
  restapi/operations/installer/update_host_installer_args_parameters.go
  restapi/operations/installer/update_host_installer_args_responses.go
  restapi/operations/installer/update_host_installer_args_urlbuilder.go
  swagger.yaml
Labels: api-review, approved, lgtm

#680 MGMT-2652 Inform there was a disconnectio when stage is timed out + test
  internal/host/common.go
  internal/host/host.go
  internal/host/transition.go
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, lgtm

#684 NO-ISSUE Handle ISO generation cancellation
  pkg/s3wrapper/client_test.go
  pkg/s3wrapper/upload_iso.go
Labels: approved, lgtm

#682 MGMT-2936 - extract machineCIDR and baseDoman for day2 on OCP, fix ap…
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/apivipconnectivitycheckcmd.go
  internal/network/machine_network_cidr.go
  pkg/k8sclient/k8s_utils.go
Labels: approved, lgtm

#685 OCPBUGSM-20532: Allow register deleted hosts
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/mock_host_api.go
  internal/host/monitor_test.go
  internal/host/transition.go
  internal/host/transition_test.go
  subsystem/cluster_test.go
Labels: approved, lgtm

#688 MGMT-792 - Swagger - added virtual field to system_vendor
  models/system_vendor.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#689 Ocpbugsm-20532/for release v1.0.11
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/mock_host_api.go
  internal/host/monitor_test.go
  internal/host/transition.go
  internal/host/transition_test.go
  subsystem/cluster_test.go
Labels: approved, lgtm

#694 OCPBUGSM-20563: Allow registering an unregistered cluster
  internal/cluster/registrar.go
  internal/cluster/registrar_test.go
  subsystem/cluster_test.go
Labels: approved, lgtm

#695 OCPBUGSM-20496 Add hostname to host enable/disable events
  internal/bminventory/inventory.go
Labels: approved, lgtm

#696 OCPBUGSM-20563: Allow registering an unregistered cluster (#694)
  internal/cluster/registrar.go
  internal/cluster/registrar_test.go
  subsystem/cluster_test.go
Labels: approved, lgtm

#690 MGMT-2947 - move day2 ignition from general to per node ignition
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/ignition/ignition.go
Labels: approved, lgtm

#674 MGMT-2752 - Add user-managed-networking to cluster (none-platform)
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/installcfg/installcfg.go
  internal/installcfg/installcfg_test.go
  models/cluster.go
  models/cluster_create_params.go
  models/cluster_update_params.go
  swagger.yaml
Labels: api-review, approved, lgtm

#698 MGMT-2947 - move day2 ignition from general to per node ignition (#690)
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/ignition/ignition.go
Labels: approved, lgtm

#700 MGMT-2465: day2 - single replica for ocp
  tools/deploy_assisted_installer.py
Labels: approved, lgtm

#692 MGMT-2765 Run a subet of subsystem tests for onprem in Jenkins
  Jenkinsfile
  Makefile
  subsystem/cluster_test.go
  subsystem/image_test.go
Labels: approved, lgtm

#702 MGMT-2982 Fix image build race condition
  build_deploy.sh
  build_images.sh
Labels: approved, lgtm

#701 MGMT-2965 Reset fields when enabling host
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, lgtm

#686 MGMT-2393: enable filtering clusters by Openshift cluster ID
  client/installer/list_clusters_parameters.go
  internal/bminventory/inventory.go
  internal/cluster/transition.go
  restapi/embedded_spec.go
  restapi/operations/installer/list_clusters_parameters.go
  restapi/operations/installer/list_clusters_urlbuilder.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#642 OCPBUGSM-17327: allow "*" as a valid NoProxyFormat
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
  swagger.yaml
Labels: api-review, approved, lgtm

#705 MGMT-2403 increase upload log capacity
  swagger.yaml
Labels: api-review, approved, lgtm

#699 OCPBUGSM-20497 limit cluster name to 54 characters
  models/cluster_create_params.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#707 NO-ISSUE Regenerate files after swagger changes
  models/cluster_create_params.go
  models/cluster_update_params.go
  restapi/embedded_spec.go
  restapi/operations/installer/upload_logs_parameters.go
Labels: approved, lgtm

#713 OCPBUGSM-17591 [1879103] Failed validations on the cluster after inst…
  internal/cluster/cluster_test.go
  internal/cluster/transition_test.go
  internal/cluster/validator.go
Labels: approved, lgtm

#711 MGTM-2834 assisted-service on-prem reset doesn't clean old cluster st…
  internal/cluster/cluster.go
  pkg/s3wrapper/client.go
Labels: approved, lgtm

#704 MGMT-2678: Adding list of IPs to logs cmd.
  internal/host/common.go
  internal/host/instructionmanager.go
  internal/host/logscmd.go
  internal/host/logscmd_test.go
  internal/network/machine_network_cidr.go
Labels: approved, lgtm

#719 OCPBUGSM-20425 - failed day2 host should be able to be reset and to r…
  client/installer/installer_client.go
  client/installer/reset_host_parameters.go
  client/installer/reset_host_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/mock_cluster_api.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/common.go
  internal/host/host.go
  internal/host/instructionmanager.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/host/statemachine.go
  internal/host/transition.go
  internal/host/transition_test.go
  internal/host/validator.go
  internal/metrics/mock_netricsManager_api.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  pkg/generator/mock_install_config.go
  pkg/k8sclient/mock_k8sclient.go
  pkg/leader/mock_leader_elector.go
  pkg/ocm/mock_authorization.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3wrapper.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/reset_host.go
  restapi/operations/installer/reset_host_parameters.go
  restapi/operations/installer/reset_host_responses.go
  restapi/operations/installer/reset_host_urlbuilder.go
  subsystem/day2_cluster_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#720 MGMT-2678: Adding list of IPs to logs cmd. (#704)
  internal/host/common.go
  internal/host/instructionmanager.go
  internal/host/logscmd.go
  internal/host/logscmd_test.go
  internal/network/machine_network_cidr.go
Labels: approved, lgtm

#722 OCPBUGSM-20151 - in case day2 cloud cluster already exists for the UU…
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/common.go
Labels: approved, lgtm

#718 MGMT-2989 increase timeout of writing to disk from 10 minutes to 30 m…
  internal/host/host.go
Labels: approved, lgtm

#725 MGMT-3013 - fix the IP format in BMH annotations, fixes the link betw…
  internal/ignition/ignition.go
Labels: approved, lgtm

#721 MGMT-2411: Added error_utils.go
  pkg/error/error_utils.go
  pkg/error/error_utils_test.go
Labels: approved, lgtm

#723 OCPBUGSM-20820: Removing workers IPs from logs cmd.
  internal/host/logscmd.go
Labels: approved, lgtm

#727 MGMT-3033 - Add S.M.A.R.T. field to inventory host disks
  models/disk.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#729 NO-ISSUE Merge RUNs of curl and chmod for assisted-iso-create
  Dockerfile.assisted-iso-create
Labels: approved, kind/dependency-change, lgtm

#724 OCPBUGSM-20820: Removing workers IPs from logs cmd.
  internal/host/logscmd.go
Labels: approved, lgtm

#732 NO-ISSUE Remove docker objects cleanup
  Jenkinsfile
Labels: approved, lgtm

#691 MGMT-2943 Expose discovery ignition separately from iso
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/common/error_utils.go
  restapi/embedded_spec.go
  restapi/operations/installer/download_cluster_files_parameters.go
  swagger.yaml
Labels: api-review, approved, lgtm

#735 OCPBUGSM-20425 - failed day2 host should be able to be reset and to r…
  client/installer/installer_client.go
  client/installer/reset_host_parameters.go
  client/installer/reset_host_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/common.go
  internal/host/host.go
  internal/host/instructionmanager.go
  internal/host/mock_host_api.go
  internal/host/statemachine.go
  internal/host/transition.go
  internal/host/transition_test.go
  internal/host/validator.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/reset_host.go
  restapi/operations/installer/reset_host_parameters.go
  restapi/operations/installer/reset_host_responses.go
  restapi/operations/installer/reset_host_urlbuilder.go
  subsystem/day2_cluster_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#739 NO-ISSUE - Added missing env forwarding in deploy configmap
  tools/deploy_assisted_installer_configmap.py
Labels: approved, lgtm

#675 MGMT-2322 add ntp step
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/mock_cluster_api.go
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/instructionmanager.go
  internal/host/instructionmanager_test.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/host/ntp_synchronizer_cmd.go
  internal/host/refresh_status_preprocessor.go
  internal/host/transition.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/host/validator.go
  internal/metrics/mock_netricsManager_api.go
  models/cluster.go
  models/cluster_create_params.go
  models/cluster_update_params.go
  models/host.go
  models/host_validation_id.go
  onprem-environment
  openshift/template.yaml
  pkg/generator/mock_install_config.go
  pkg/k8sclient/mock_k8sclient.go
  pkg/leader/mock_leader_elector.go
  pkg/ocm/mock_authorization.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3wrapper.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  subsystem/day2_cluster_test.go
  subsystem/utils_test.go
  swagger.yaml
  tools/deploy_assisted_installer_configmap.py
Labels: api-review, approved, lgtm

#741 NO-ISSUE - Remove masayag from OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, lgtm

#742 MGMT-2955 add retry to live.iso curl download in deploy-onprem
  Makefile
Labels: approved, lgtm

#740 MGMT-3078 - Add an unfiltered_disks list entry to the inventory API
  models/inventory.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#745 Revert "MGMT-3078 - Add a unfiltered_disks list entry to the inventory API (#740)"
  models/inventory.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#743 MGMT-2370 Add chrony manifest
  cmd/main.go
  go.mod
  go.sum
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/network/mock_ntp_utils.go
  internal/network/ntp_utils.go
  internal/network/ntp_utils_test.go
  mocks/generate.go
  mocks/mock_manifests.go
Labels: approved, lgtm

#749 OCPBUGSM-20963 MGMT-2370 Bugfix create chrony manifest with no ntp sources
  internal/network/ntp_utils.go
  internal/network/ntp_utils_test.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#751 MGMT-2322 Bugfix Default NTP value
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#726 MGMT-3024 Update OCP release to ocp-release:4.6.4-x86_64
  Makefile
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  onprem-environment
Labels: approved, lgtm

#752 MGMT-3103: reduce image expiration time and interval for local e2e tests
  Makefile
  skipper.yaml
  tools/deploy_assisted_installer_configmap.py
Labels: approved, lgtm

#750 OCPBUGSM-20944 Clear kubectl objects with force
  Makefile
  tools/clear_deployment.py
Labels: approved, lgtm

#754 OCPBUGSM-20982 Bugfix List manifests onprem
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
  pkg/job/local_job.go
  subsystem/manifests_test.go
Labels: approved, lgtm
