Repository openshift/assisted-service, pull requests merged in 2020-12, with the labels that each got.

#753 MGMT-3027 Wrong event when timeout on writing to disk
  internal/host/common.go
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, lgtm

#757 MGMT-3128 - extract ssh public key from OCP cluster
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  pkg/k8sclient/k8s_utils.go
Labels: approved, lgtm

#758 MGMT-2892 Add openapi endpoint to return api spec
  cmd/main.go
  internal/spec/spec.go
  internal/spec/spec_test.go
  subsystem/spec_test.go
  subsystem/utils_test.go
Labels: approved, lgtm

#733 MGMT-2963 Skip VIP and Machine Network CIDR validations with user-managed-networking
  internal/bminventory/inventory.go
  internal/cluster/transition_test.go
  internal/cluster/validator.go
  internal/host/transition_test.go
  internal/host/validator.go
  internal/network/cidr_validations.go
  internal/network/dhcp_param_file.go
Labels: approved, lgtm

#759 NO-ISSUE - Remove romfreiman from OWNERS_ALIASES
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm

#756 MGMT-2780 - Changes for IPv6, Phase 2
  internal/host/common.go
  internal/host/validator.go
  internal/installcfg/installcfg.go
  internal/network/cidr_validations.go
  internal/network/family_utils.go
  internal/network/machine_network_cidr.go
  models/cluster.go
  models/cluster_create_params.go
  models/cluster_update_params.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#761 MGMT-2738: installcmd.go remove MBR sector from bootable disks
  cmd/main.go
  internal/host/installcmd.go
  internal/host/installcmd_test.go
  internal/host/instructionmanager.go
  internal/host/instructionmanager_test.go
Labels: approved, lgtm

#760 MGMT-3054 Add host machine config pool
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/common.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/mock_host_api.go
  models/cluster_update_params.go
  models/host.go
  restapi/embedded_spec.go
  subsystem/day2_cluster_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#763 OCPBUGSM-20856 Remove ssh-public-key length limitation and migrate DB
  internal/migrations/20201019194303_change_overrides_to_text_test.go
  internal/migrations/20201202140700_change_image_ssh_key_text.go
  internal/migrations/20201202140700_change_image_ssh_key_text_test.go
  internal/migrations/migrations.go
  internal/migrations/migrations_suite_test.go
  models/cluster.go
  models/image_info.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#648 MGMT-2573 Extract and use MCO image from release image
  cmd/main.go
  go.mod
  go.sum
  internal/cluster/validations/validations.go
  internal/host/installcmd.go
  internal/host/installcmd_test.go
  internal/host/instructionmanager.go
  internal/host/instructionmanager_test.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/installercache/installercache.go
  internal/oc/mock_release.go
  internal/oc/release.go
  internal/oc/release_test.go
  pkg/job/job.go
  pkg/job/local_job.go
  subsystem/day2_cluster_test.go
Labels: approved, lgtm

#766 NO-ISSUE add helper method to updateClusterData
  internal/bminventory/inventory.go
Labels: approved, lgtm

#747 MGMT-2277 - remove references to the unused ignition-generate-image
  internal/versions/versions.go
  models/cluster.go
  openshift/template.yaml
  restapi/embedded_spec.go
  subsystem/versions_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#767 MGMT-3086 - implement InstallHost per specific day2 host
  client/installer/install_host_parameters.go
  client/installer/install_host_responses.go
  client/installer/installer_client.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  pkg/k8sclient/k8s_utils.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/install_host.go
  restapi/operations/installer/install_host_parameters.go
  restapi/operations/installer/install_host_responses.go
  restapi/operations/installer/install_host_urlbuilder.go
  subsystem/day2_cluster_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#768 MGMT-3130: Change unit tests to use httptest server instead of http server
  pkg/auth/auth_handler_test.go
  pkg/auth/auth_suite_test.go
  pkg/auth/authz_handler_test.go
  pkg/log/logcontext_test.go
Labels: approved, lgtm

#769 OPCBUGSM-20841: Wrong boot order hosts will be set to error when cluster status is error
  internal/host/monitor.go
  internal/host/statemachine.go
  internal/host/transition_test.go
Labels: approved, lgtm

#770 MGMT-3182: remove duplicated refresh status on cluster error
  internal/host/statemachine.go
Labels: approved, lgtm

#764 MGMT-3153 - Disable password login for discovery ISO core user
  internal/bminventory/inventory.go
Labels: approved, lgtm

#776 NO-ISSUE add cloud README
  README.md
  docs/cloud.md
Labels: approved, lgtm

#775 MGMT-2254 Migrate Grafana dashboards to assisted-service codebase
  dashboards/grafana-dashboard-assisted-installer-general-overview.configmap.yaml
Labels: approved, lgtm

#748 MGMT-3061 Add cluster install progress
  client/installer/installer_client.go
  client/installer/update_cluster_install_progress_parameters.go
  client/installer/update_cluster_install_progress_responses.go
  internal/bminventory/inventory.go
  internal/cluster/cluster.go
  internal/cluster/common.go
  internal/cluster/mock_cluster_api.go
  internal/cluster/statemachine.go
  internal/cluster/transition.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/metrics/mock_netricsManager_api.go
  internal/network/mock_ntp_utils.go
  internal/oc/mock_release.go
  mocks/mock_assisted_service.go
  models/cluster.go
  models/cluster_progress_info.go
  pkg/auth/auth_assisted_service_mock_test.go
  pkg/generator/mock_install_config.go
  pkg/k8sclient/mock_k8sclient.go
  pkg/leader/mock_leader_elector.go
  pkg/ocm/mock_authorization.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3wrapper.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/update_cluster_install_progress.go
  restapi/operations/installer/update_cluster_install_progress_parameters.go
  restapi/operations/installer/update_cluster_install_progress_responses.go
  restapi/operations/installer/update_cluster_install_progress_urlbuilder.go
  subsystem/cluster_test.go
  subsystem/utils_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#778 MGMT-2254 Migrate Grafana additional dashboards to assisted-service
  dashboards/grafana-dashboard-assisted-installer-agent-api.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-basic-cluster-operation.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-cluster-overview.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-general-overview.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-ocm-operations.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-resource-utilization.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-rnd-overview.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-weekly-overview.configmap.yaml
Labels: approved, lgtm

#779 MGMT-3061 progress_info should not be a mandatory field
  models/cluster_progress_info.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#781 NO-ISSUE Adding Richard Su and Sudarshan Acharya
  OWNERS_ALIASES
Labels: approved, lgtm

#780 NO-ISSUE Fix + update weekly overview dashboard
  dashboards/grafana-dashboard-assisted-installer-weekly-overview.configmap.yaml
Labels: approved, lgtm

#783 MGMT-3220 - Add documentation for setting discovery ISO password
  README.md
  docs/set_discovery_password.md
Labels: approved, lgtm

#784 NO-ISSUE Added Omer Tuchfeld (omertuc) to code-reviewers
  OWNERS_ALIASES
Labels: approved, lgtm

#785 MGMT-3220 - Modified documentation wording to be more clear
  README.md
  docs/set-discovery-password.md
Labels: approved, lgtm

#788 NO-ISSUE Add 4.7 support on swagger
  models/cluster.go
  models/cluster_create_params.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#786 MGMT-3064 User Managed Networking cluster params conflicts
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#791 fix podman pod create format
  Makefile
Labels: approved, lgtm

#790 MGMT-2765 More robust curl retry via shell script
  Makefile
  hack/retry.sh
Labels: approved, lgtm

#765 MGMT-2758 Remove image from s3 when editing the discovery ignition
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
  pkg/s3wrapper/client.go
  pkg/s3wrapper/filesystem.go
  pkg/s3wrapper/filesystem_test.go
  pkg/s3wrapper/mock_s3wrapper.go
  subsystem/image_test.go
Labels: approved, lgtm

#793 Osher/ocpbugsm 20497
  restapi/embedded_spec.go
  restapi/operations/installer/update_cluster_parameters.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#794 MGMT-3261 Add ISO Generated metrics to weekly and general overview
  dashboards/grafana-dashboard-assisted-installer-general-overview.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-weekly-overview.configmap.yaml
Labels: approved, lgtm

#772 MGMT-3078 - Add disk filtering reasons to the API
  go.mod
  go.sum
  internal/hardware/mock_validator.go
  internal/hardware/validator.go
  internal/hardware/validator_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/validator.go
  models/cluster_update_params.go
  models/disk.go
  restapi/embedded_spec.go
  restapi/operations/installer/update_cluster_parameters.go
  subsystem/host_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#762 MGMT-2424: Support for LSO(Local Storage Operator) installation
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/operators/lso/utils.go
  models/cluster.go
  models/cluster_create_params.go
  models/cluster_update_params.go
  models/lso.go
  models/operators.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#796 OCPBUGSM-21552 Add workers chrony manifest
  internal/network/ntp_utils.go
  internal/network/ntp_utils_test.go
Labels: approved, lgtm

#800 MGMT-3078 - Reverted #772
  go.mod
  go.sum
  internal/hardware/mock_validator.go
  internal/hardware/validator.go
  internal/hardware/validator_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/validator.go
  models/disk.go
  restapi/embedded_spec.go
  subsystem/host_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#797 OCPBUGSM-21583 Remove RHEL default NTP source
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#802 OCPBUGSM-21552 Bugfix trailing parenthesis
  internal/network/ntp_utils.go
Labels: approved, lgtm

#795 MGMT-3262 Remove app-sre images
  Dockerfile.assisted-iso-create
  Dockerfile.assisted-service
  Dockerfile.assisted-service-build
  Dockerfile.test
  Makefile
  hack/wait_for_postgres.sh
  internal/common/error_utils.go
  openshift/template-post-deploy-job.yaml
Labels: approved, kind/dependency-change, lgtm

#801 OCPBUGSM-21366 Support comma-separated NTP sources list
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/mock_cluster_api.go
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
  internal/common/common.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/metrics/mock_netricsManager_api.go
  internal/network/mock_ntp_utils.go
  internal/oc/mock_release.go
  models/cluster.go
  models/cluster_create_params.go
  models/cluster_update_params.go
  models/ntp_synchronization_request.go
  pkg/generator/mock_install_config.go
  pkg/k8sclient/mock_k8sclient.go
  pkg/leader/mock_leader_elector.go
  pkg/ocm/mock_authorization.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3wrapper.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#777 OCPBUGSM-21213 Failed NTP validations on the cluster after installati…
  internal/cluster/refresh_status_preprocessor.go
  internal/cluster/transition_test.go
  internal/cluster/validator.go
Labels: approved, lgtm

#773 MGMT-3120 IPv6 connectivity check
  internal/cluster/cluster_test.go
  internal/host/connectivitycheckconvertor.go
  internal/host/connectivitycheckconvertor_test.go
  internal/host/validator.go
  internal/network/connectivity_groups.go
  internal/network/connectivity_groups_test.go
  internal/network/machine_network_cidr.go
  internal/network/machine_network_cidr_test.go
  subsystem/cluster_test.go
Labels: approved, lgtm

#787 MGMT-3117 Add API for selecting boot disk
  models/cluster_update_params.go
  models/disk_config_params.go
  models/disk_role.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#792 MGMT-2991 None-Platform logs commands IPs
  internal/host/logscmd.go
  internal/host/logscmd_test.go
Labels: approved, lgtm

#798 OCPBUGSM-21433 Enable NTP validation as sufficient for installation
  internal/host/statemachine.go
  internal/host/transition_test.go
  subsystem/cluster_test.go
Labels: approved, lgtm

#808 MGMT-3287 Add none-platform label to startInstall metric
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_netricsManager_api.go
Labels: approved, lgtm

#774 OCPBUGSM-21144 Document stand-alone mode
  docs/installer-stand-alone.md
  onprem-environment
Labels: approved, lgtm

#810 NO-ISSUE hardcode SERVICE_API_PORT in onprem-environment
  docs/installer-stand-alone.md
  onprem-environment
Labels: approved, lgtm

#807 NO-ISSUE Default of a single service replica
  Makefile
Labels: approved, lgtm

#813 NO-ISSUE format mocks
  internal/cluster/mock_cluster_api.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/metrics/mock_netricsManager_api.go
  internal/network/mock_ntp_utils.go
  internal/oc/mock_release.go
  pkg/generator/mock_install_config.go
  pkg/k8sclient/mock_k8sclient.go
  pkg/leader/mock_leader_elector.go
  pkg/ocm/mock_authorization.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3wrapper.go
Labels: approved, lgtm

#809 MGMT-3062 Allow cluster install progress updates for cluster installing and finalizing state
  client/installer/update_cluster_install_progress_responses.go
  internal/cluster/statemachine.go
  restapi/embedded_spec.go
  restapi/operations/installer/update_cluster_install_progress_responses.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#693 MGMT-1263 Allow the overriding of the rhcos image
  internal/hostutil/host_utils.go
  internal/hostutil/host_utils_test.go
Labels: approved, lgtm

#812 MGMT-3296 support static ip provisioning for discovery ISO
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/mock_cluster_api.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/metrics/mock_netricsManager_api.go
  internal/network/mock_ntp_utils.go
  internal/oc/mock_release.go
  models/image_create_params.go
  models/image_info.go
  models/static_ip_config.go
  pkg/generator/mock_install_config.go
  pkg/k8sclient/mock_k8sclient.go
  pkg/leader/mock_leader_elector.go
  pkg/ocm/mock_authorization.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3wrapper.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#814 MGMT-3117 select boot disk
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/hardware/validator.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/installcmd.go
  internal/host/mock_host_api.go
  internal/hostutil/host_utils.go
Labels: approved, lgtm

#817 Revert "OCPBUGSM-21433 Enable NTP validation as sufficient for instal…
  internal/host/statemachine.go
  internal/host/transition_test.go
  subsystem/cluster_test.go
Labels: approved, lgtm

#805 MGMT-2245 Support OCP multiversion
  Makefile
  client/versions/list_supported_openshift_versions_parameters.go
  client/versions/list_supported_openshift_versions_responses.go
  client/versions/versions_client.go
  cmd/main.go
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  deploy/assisted-service-configmap.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/common_unitest_db.go
  internal/host/installcmd.go
  internal/host/installcmd_test.go
  internal/host/instructionmanager.go
  internal/host/instructionmanager_test.go
  internal/installcfg/installcfg_test.go
  internal/oc/release.go
  internal/versions/mock_versions.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  models/add_hosts_cluster_create_params.go
  models/cluster.go
  models/cluster_create_params.go
  models/openshift_version.go
  models/openshift_versions.go
  onprem-environment
  openshift/template.yaml
  pkg/auth/auth_assisted_service_mock_test.go
  pkg/auth/authz_handler_test.go
  pkg/generator/generator.go
  pkg/generator/mock_install_config.go
  pkg/job/job.go
  pkg/job/local_job.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/versions/list_supported_openshift_versions.go
  restapi/operations/versions/list_supported_openshift_versions_parameters.go
  restapi/operations/versions/list_supported_openshift_versions_responses.go
  restapi/operations/versions/list_supported_openshift_versions_urlbuilder.go
  skipper.yaml
  subsystem/authz_test.go
  subsystem/cluster_test.go
  subsystem/day2_cluster_test.go
  subsystem/host_test.go
  subsystem/image_test.go
  subsystem/manifests_test.go
  subsystem/versions_test.go
  swagger.yaml
  tools/deploy_assisted_installer_configmap.py
  tools/update_bm_cm.py
Labels: api-review, approved, lgtm

#645 MGMT-2636 Remove uploadBaseISO job
  .gitignore
  Dockerfile.assisted-iso-create
  Makefile
  README.md
  assisted-iso-create/main.go
  build_images.sh
  cmd/main.go
  docs/installer-live-iso.md
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  models/image_info.go
  pkg/generator/generator.go
  pkg/job/job.go
  pkg/job/local_job.go
  pkg/s3wrapper/client.go
  subsystem/versions_test.go
  tools/deploy_assisted_installer.py
  tools/deploy_assisted_installer_configmap.py
Labels: approved, kind/dependency-change, lgtm

#799 Add host count to InstallationStart metric
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_netricsManager_api.go
Labels: approved, lgtm

#819 MGMT-2245 Bugfix add default 4.7 and create default_ocp_versions.json
  Makefile
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  onprem-environment
  subsystem/versions_test.go
Labels: approved, lgtm

#815 MGMT-3303 - update OCP release to 4.6.8 & RCHOS_VERSION to 46.82.2020…
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  onprem-environment
Labels: approved, lgtm

#821 MGMT-3295: On installation delete old cluster logs
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster_test.go
  internal/cluster/transition.go
  internal/host/host_test.go
  internal/host/transition.go
Labels: approved, lgtm

#804 MGMT-3078 - Add disk filtering reasons to the API
  go.mod
  go.sum
  internal/cluster/mock_cluster_api.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/hardware/validator.go
  internal/hardware/validator_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/host/monitor_test.go
  internal/host/refresh_status_preprocessor.go
  internal/host/transition_test.go
  internal/host/validator.go
  internal/metrics/mock_netricsManager_api.go
  internal/network/mock_ntp_utils.go
  internal/oc/mock_release.go
  internal/versions/mock_versions.go
  models/disk.go
  models/image_info.go
  pkg/generator/mock_install_config.go
  pkg/k8sclient/mock_k8sclient.go
  pkg/leader/mock_leader_elector.go
  pkg/ocm/mock_authorization.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3wrapper.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#822 NO-ISSUE Extend wait for assisted-service timeout to 30 minutes
  tools/wait_for_assisted_service.py
Labels: approved, lgtm

#828 MGMT-2245 Bugfix OCP override image
  Makefile
  deploy/assisted-service-configmap.yaml
  tools/deploy_assisted_installer_configmap.py
Labels: approved, lgtm

#824 MGMT-2256: placeholder makefile targets for openshift ci
  Makefile
Labels: approved, lgtm

#830 NO-ISSUE reduce main cyclomatic complexity
  cmd/main.go
  pkg/s3wrapper/client.go
Labels: approved, lgtm

#806 MGMT-3026 - invoke fio from installcmd
  internal/bminventory/inventory.go
  internal/host/fioperfcheckcmd.go
  internal/host/host.go
  internal/host/installcmd.go
  internal/host/installcmd_test.go
  internal/host/instructionmanager.go
  internal/host/mock_host_api.go
  models/disk.go
  models/fio_perf_check_request.go
  models/fio_perf_check_response.go
  models/io_perf.go
  models/step_type.go
  openshift/template.yaml
  restapi/embedded_spec.go
  subsystem/host_test.go
  swagger.yaml
  tools/deploy_assisted_installer_configmap.py
Labels: api-review, approved, lgtm

#728 MGMT-2470 silently fail if free addresses container already running
  go.mod
  go.sum
  internal/host/freeaddressescmd.go
Labels: approved, lgtm

#818 MGMT-2782 - IPv6 Phase 3 changes
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster_test.go
  internal/cluster/transition_test.go
  internal/host/host_test.go
  internal/host/instructionmanager.go
  internal/host/transition_test.go
  internal/installcfg/installcfg.go
  internal/installcfg/installcfg_test.go
  internal/network/cidr_validations.go
  internal/network/cidr_validations_test.go
  internal/network/machine_network_cidr_test.go
  subsystem/cluster_test.go
  subsystem/ipv6_test.go
Labels: approved, lgtm

#829 MGMT-3355 Run controllers along side rest-api
  Dockerfile.assisted-service-build
  Makefile
  cmd/main.go
  go.mod
  go.sum
  internal/controller/api/v1alpha1/cluster_types.go
  internal/controller/api/v1alpha1/groupversion_info.go
  internal/controller/api/v1alpha1/host_types.go
  internal/controller/api/v1alpha1/image_types.go
  internal/controller/api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/config/crd/bases/adi.io.my.domain_clusters.yaml
  internal/controller/config/crd/bases/adi.io.my.domain_hosts.yaml
  internal/controller/config/crd/bases/adi.io.my.domain_images.yaml
  internal/controller/config/crd/kustomization.yaml
  internal/controller/config/crd/kustomizeconfig.yaml
  internal/controller/config/rbac/kube_api_roles.yaml
  internal/controller/config/rbac/role.yaml
  internal/controller/controllers/cluster_controller.go
  internal/controller/controllers/host_controller.go
  internal/controller/controllers/image_controller.go
  tools/deploy_assisted_installer.py
  tools/deploy_crd.py
  tools/deploy_role.py
  tools/deployment_options.py
Labels: approved, kind/dependency-change, lgtm

#715 MGMT-2966: add a single node mode for installing SNO clusters
  internal/cluster/mock_cluster_api.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/mock_instruction_api.go
  internal/metrics/mock_netricsManager_api.go
  internal/network/mock_ntp_utils.go
  internal/oc/mock_release.go
  internal/versions/mock_versions.go
  models/cluster.go
  models/cluster_update_params.go
  pkg/generator/mock_install_config.go
  pkg/k8sclient/mock_k8sclient.go
  pkg/leader/mock_leader_elector.go
  pkg/ocm/mock_authorization.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3wrapper.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#833 NO-ISSUE log OCP & mco version
  internal/host/installcmd.go
Labels: approved, do-not-merge/hold, lgtm

#831 MGMT-2256: openshift ci build and deploy
  Makefile
  tools/deploy_assisted_installer.py
  tools/utils.py
Labels: approved, lgtm

#834 MGMT-3419 Verify OCP versions on CI and on deployment
  Dockerfile.assisted-service-build
  Makefile
  tools/deploy_assisted_installer_configmap.py
  tools/handle_ocp_versions.py
Labels: approved, kind/dependency-change, lgtm

#820 MGMT-2245 Extract OCP version from OCP images
  cmd/main.go
  go.mod
  go.sum
  internal/host/instructionmanager.go
  internal/installercache/installercache.go
  internal/oc/mock_release.go
  internal/oc/release.go
  internal/oc/release_test.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  pkg/executer/executer.go
  pkg/executer/mock_executer.go
  pkg/job/job.go
Labels: approved, lgtm

#832 MGMT-2256: openshift ci test
  Makefile
  subsystem/leader_test.go
  tools/deploy_assisted_installer.py
Labels: approved, lgtm

#835 MGMT-3410 Add HA mode to install command
  internal/host/installcmd.go
  internal/host/installcmd_test.go
Labels: approved, lgtm

#836 MGMT-3330 remove requirement for OPENSHIFT_INSTALL_RELEASE_IMAGE & OP…
  openshift/template.yaml
Labels: approved, lgtm

#838 NO-ISSUE Change log to log format
  internal/host/installcmd.go
Labels: approved, lgtm

#839 Revert "MGMT-3410 Add HA mode to install command (#835)"
  internal/host/installcmd.go
  internal/host/installcmd_test.go
Labels: approved, lgtm

#837 MGMT-3355 Add controller generation call to controller manifests gene…
  Makefile
  hack/boilerplate.go.txt
Labels: approved, lgtm

#840 Revert "MGMT-2245 Extract OCP version from OCP images"
  cmd/main.go
  go.mod
  go.sum
  internal/host/instructionmanager.go
  internal/installercache/installercache.go
  internal/oc/mock_release.go
  internal/oc/release.go
  internal/oc/release_test.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  pkg/executer/executer.go
  pkg/executer/mock_executer.go
  pkg/job/job.go
Labels: approved, lgtm

#841 NO-ISSUE Add userAuth to DownloadHostIgnition
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#842 MGMT-3410 Add HA mode to install command
  internal/host/installcmd.go
  internal/host/installcmd_test.go
Labels: approved, lgtm

#843 MGMT-3356 Create cluster CRD
  Makefile
  internal/controller/api/v1alpha1/cluster_types.go
  internal/controller/api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/config/crd/bases/adi.io.my.domain_clusters.yaml
  internal/controller/config/rbac/role.yaml
  internal/controller/config/rbac/secret_patch.yaml
Labels: approved, lgtm

#848 MGMT-3026 increase FIO check threshold
  internal/host/fioperfcheckcmd.go
  internal/host/installcmd_test.go
Labels: approved, lgtm

#755 MGMT-3100 Upload/download PXE artifacts
  Dockerfile.assisted-service-build
  client/assisted_install_client.go
  client/bootfiles/bootfiles_client.go
  client/bootfiles/download_boot_files_parameters.go
  client/bootfiles/download_boot_files_responses.go
  cmd/main.go
  deploy/assisted-service.yaml
  deploy/s3/scality-deployment.yaml
  deploy/s3/scality-public-secret.yaml
  go.mod
  go.sum
  internal/bootfiles/bootfiles.go
  internal/bootfiles/bootfiles_test.go
  internal/cluster/mock_cluster_api.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/isoutil/isoutil.go
  internal/isoutil/isoutil_test.go
  internal/isoutil/mock_isoutil.go
  internal/metrics/mock_netricsManager_api.go
  internal/network/mock_ntp_utils.go
  internal/oc/mock_release.go
  internal/versions/mock_versions.go
  openshift/template.yaml
  pkg/executer/mock_executer.go
  pkg/generator/mock_install_config.go
  pkg/k8sclient/mock_k8sclient.go
  pkg/leader/mock_leader_elector.go
  pkg/ocm/mock_authorization.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/client.go
  pkg/s3wrapper/client_test.go
  pkg/s3wrapper/filesystem.go
  pkg/s3wrapper/filesystem_test.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3manageriface.go
  pkg/s3wrapper/mock_s3wrapper.go
  pkg/s3wrapper/upload_iso.go
  pkg/s3wrapper/util.go
  pkg/s3wrapper/util_test.go
  restapi/configure_assisted_install.go
  restapi/operations/assisted_install_api.go
  restapi/operations/bootfiles/download_boot_files.go
  restapi/operations/bootfiles/download_boot_files_parameters.go
  restapi/operations/bootfiles/download_boot_files_responses.go
  restapi/operations/bootfiles/download_boot_files_urlbuilder.go
  swagger.yaml
  tools/deploy_scality_configmap.py
Labels: api-review, approved, kind/dependency-change, lgtm
