Repository openshift/assisted-service, pull requests merged in 2020-08, with the labels that each got.

#27 Fix APP SRE changes
  Dockerfile.test
  build_deploy.sh
  openshift/template.yaml
Labels: lgtm

#30 update pushed image assisted-service
  Jenkinsfile
Labels: approved, lgtm

#37 Fixing DB password's env variable in openshift/template.yaml.
  openshift/template.yaml
Labels: approved, lgtm

#32 Remove OBJEXP from jenkins file
  Jenkinsfile
Labels: approved, lgtm

#38 fix quay login
  Jenkinsfile
Labels: approved, lgtm

#29 Removed s3-object-expirer from openshift/template.yaml.
  openshift/template.yaml
Labels: approved, lgtm

#31 Changing deploy-test SERVICE image to an unknown one
  Makefile
Labels: approved, lgtm

#39 MGMT-1681: Use only official AWS SDK for S3 operations
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  pkg/s3Client/mock_s3client.go
  pkg/s3Client/s3Client.go
  pkg/s3wrapper/client.go
  pkg/s3wrapper/mock_s3wrapper.go
Labels: approved, lgtm

#47 MGMT-1626 - allow openshift version 4.6 to be passed as parameter dur…
  client/events/mock_API.go
  client/installer/mock_API.go
  client/managed_domains/mock_API.go
  client/versions/mock_API.go
  models/cluster.go
  models/cluster_create_params.go
  restapi/embedded_spec.go
  restapi/mock_EventsAPI.go
  restapi/mock_InstallerAPI.go
  restapi/mock_ManagedDomainsAPI.go
  restapi/mock_VersionsAPI.go
  swagger.yaml
Labels: approved, lgtm

#53 MGMT-773 - Auth disabled by default
  .drone.yml
  Makefile
  pkg/auth/auth_handler.go
Labels: approved, lgtm

#49 MGMT-1715 Replace host and port with URL
  deploy/assisted-service-configmap.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/installcmd.go
  internal/host/installcmd_test.go
  internal/host/instructionmanager.go
  tools/deploy_assisted_installer_configmap.py
Labels: approved, lgtm

#51 MGMT-1649 Add host installation disk path property
  internal/host/host_test.go
  internal/host/installcmd.go
  internal/host/installcmd_test.go
  internal/host/transition.go
  internal/host/transition_test.go
  models/host.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: approved, lgtm

#55 MGMT-773 auth handler should not use populateKeyMap when auth disabled
  pkg/auth/auth_handler.go
Labels: approved, lgtm

#56 Refactor Jenkinsfile and fix OCPBUGSM-1866481
  Jenkinsfile
  Makefile
Labels: approved, lgtm

#60 Change Jenkinsfile to use env variable for the image name
  Jenkinsfile
Labels: approved, lgtm

#58 MGMT-1661: Ensure aws xvd disks are discovered
  internal/hardware/validator_test.go
Labels: approved, lgtm

#44 Use official swagger codegen docker image for client generation
  Makefile
Labels: approved, lgtm

#62 MGTM-1173 fixes for https://github.com/openshift/assisted-service/pull/46
  .drone.yml
  Dockerfile.assisted-service-onprem
  Jenkinsfile
  Makefile
  README.md
  cmd/main.go
  deploy/ui/nginx.conf
  go.mod
  go.sum
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  onprem-environment
  pkg/generator/generator.go
  pkg/job/job.go
  pkg/job/local_job.go
  pkg/job/local_job_test.go
  pkg/job/mock_job.go
  pkg/job/mock_local_job.go
Labels: approved, lgtm

#63 Set only approvers on OWNERS
  OWNERS
Labels: approved, lgtm

#67 Fix Jenkins push to master
  Jenkinsfile
Labels: approved, lgtm

#68 Fixed indentation and removed usage of 'scripts' inside the steps
  Jenkinsfile
Labels: approved

#43 MGMT-1717 Swagger changes for DHCP allocation
  models/cluster.go
  models/cluster_create_params.go
  models/cluster_update_params.go
  models/dhcp_allocation_request.go
  models/dhcp_allocation_response.go
  models/step_type.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, lgtm

#65 Igal/enable cors
  cmd/main.go
  go.mod
  go.sum
  pkg/app/middleware.go
  pkg/auth/auth_handler.go
Labels: approved, lgtm

#77 Pass the current namespace as the NAMESPACE env var to assisted-service
  deploy/assisted-service.yaml
  openshift/template.yaml
Labels: approved, lgtm

#76 Fix README formatting for onprem build commands
  README.md
Labels: approved, lgtm

#50 Raz/ocpbugsm 13597
  internal/host/statemachine.go
  internal/host/transition_test.go
Labels: approved, lgtm

#69 MGMT-1661: Fix unit test according to new AWS output
  internal/hardware/validator_test.go
Labels: approved, lgtm

#79 MGMT-1757 Fix upload ISO generation UpdateObjectTag error log
  internal/bminventory/inventory.go
Labels: approved, lgtm

#61 Add Agent Auth to Hosts list API
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  subsystem/host_test.go
  swagger.yaml
Labels: approved, lgtm

#83 MGMT-1178 - Change image pull policy to Always
  pkg/job/job.go
Labels: approved, lgtm

#85 Update state diagrams with missing states
  docs/ClusterState.png
  docs/ClusterStatus.dot
  docs/ClusterStatus.png
  docs/HostStatus.dot
  docs/HostStatus.png
  docs/NodeState.dot
  docs/NodeState.png
Labels: approved, lgtm

#52 MGMT-1669 / MGMT-1637: Add image presigned URL, size, and expire time
  client/installer/download_cluster_i_s_o_responses.go
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  models/image_info.go
  pkg/s3wrapper/client.go
  pkg/s3wrapper/mock_s3wrapper.go
  restapi/embedded_spec.go
  restapi/operations/installer/download_cluster_i_s_o_responses.go
  subsystem/image_test.go
  swagger.yaml
Labels: approved, lgtm

#88 MGMT-1762 Remove old images pre test
  Jenkinsfile
Labels: approved, lgtm

#87 Updated env variable name for route53-creds secret.
  openshift/template.yaml
Labels: approved, lgtm

#91 MGMT-1770 Verify assisted-service is healthy in deploy
  Dockerfile.assisted-service-build
  Makefile
  tools/deploy_assisted_installer_configmap.py
  tools/utils.py
  tools/wait_for_assisted_service.py
  tools/wait_for_pod.py
Labels: approved, lgtm

#92 Set Auth disabled log to debug mode
  pkg/auth/auth_handler.go
Labels: approved, lgtm

#93 Fix requests timeout
  tools/wait_for_assisted_service.py
Labels: approved

#90 MGMT-1767 Move git repo ori-amizur/introspector to opnshift/assisted-installer-agent
  internal/bminventory/inventory.go
  internal/host/instructionmanager.go
Labels: approved, lgtm

#94 Hotfix catch requests timeout exception on deploy assisted-service
  Jenkinsfile
  tools/wait_for_assisted_service.py
Labels: approved

#74 Run assisted-service on-prem as non-root
  Dockerfile.assisted-service-onprem
  Makefile
Labels: approved, lgtm

#84 Igal/upload logs
  client/installer/installer_client.go
  client/installer/upload_host_logs_parameters.go
  client/installer/upload_host_logs_responses.go
  deploy/assisted-service.yaml
  go.sum
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  openshift/template.yaml
  pkg/auth/auth_handler_test.go
  pkg/s3wrapper/client.go
  pkg/s3wrapper/mock_s3wrapper.go
  restapi/configure_assisted_install.go
  restapi/doc.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/upload_host_logs.go
  restapi/operations/installer/upload_host_logs_parameters.go
  restapi/operations/installer/upload_host_logs_responses.go
  restapi/operations/installer/upload_host_logs_urlbuilder.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: approved, lgtm

#96 Adding ConfigMap to openshift/template.yaml
  openshift/template.yaml
Labels: approved, lgtm

#86 MGMT-1733 Make multistage production image to support Prow
  Dockerfile.assisted-service
  Makefile
  skipper.yaml
  tools/generate_python_client.sh
Labels: approved, lgtm

#99 Removing `namespace` field from all resources in openshift/template.yaml
  openshift/template.yaml
Labels: approved, lgtm

#106 MGMT-1791 remove disable ssl from s3 client
  pkg/s3wrapper/client.go
Labels: approved, lgtm

#89 MGMT-1764 - move ignition generation to assisted-ignition-generator
  Dockerfile.assisted-service-onprem
  Makefile
  internal/bminventory/inventory.go
  internal/cluster/mock_cluster_api.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/imgexpirer/mock_s3iface.go
  internal/metrics/mock_netricsManager_api.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  pkg/job/job.go
  pkg/job/local_job.go
  tools/deploy_assisted_installer_configmap.py
  tools/update_bm_cm.py
Labels: approved, lgtm

#110 MGMT-1797 fix get credentials
  internal/bminventory/inventory.go
Labels: approved, lgtm

#108 Set Jenkinsfile with timeout 1 hour and cron job triggers hourly
  Jenkinsfile
Labels: approved, lgtm

#71 MGMT-1718 Add new command in the bm-inventory to invoke dhcp lease allocation
  go.mod
  go.sum
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/mock_cluster_api.go
  internal/host/dhcpallocatecmd.go
  internal/host/dhcpallocatecmd_test.go
  internal/host/freeaddressescmd_test.go
  internal/host/instructionmanager.go
  internal/host/instructionmanager_test.go
  internal/network/mac_utils.go
  internal/network/machine_network_cidr.go
  pkg/job/mock_job.go
Labels: approved, lgtm

#111 Setting assisted-installer-agent as default image in assisted-service…
  tools/deploy_assisted_installer_configmap.py
Labels: approved, lgtm

#117 OCPBUGSM-15610 fix makefile to set domain when waiting for service to…
  Makefile
Labels: approved, lgtm

#109 MGMT-1788 - move coreos_installation_iso to assisted-service repo and…
  Dockerfile.assisted-iso-create
  Makefile
  assisted-iso-create/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  pkg/job/job.go
  pkg/s3wrapper/client.go
  pkg/s3wrapper/mock_s3wrapper.go
Labels: approved, lgtm

#118 OCPBUGSM-15610 fix wait for service in oc-ingress target
  tools/utils.py
Labels: approved, lgtm

#123 MGMT-1788 - change the iso creation image to ocpmetal
  Makefile
Labels: approved, lgtm

#122 Removed ConfigMap from openshift/template.yaml.
  openshift/template.yaml
Labels: approved, lgtm

#125 MGMT-1819 add --network=host to docker build to solve network issues
  Makefile
Labels: approved, lgtm

#115 MGMT-1721 Pass mode of operation by bm-inventory to cause creation of flag file to Openshift
  go.mod
  internal/network/dhcp_param_file.go
  internal/network/dhcp_param_file_test.go
  pkg/job/job.go
  pkg/job/local_job.go
Labels: approved, lgtm

#100 Added masayag to OWNERS
  OWNERS
Labels: approved, lgtm

#41 [MGMT-766][MGMT-1108] Provide HTTP/S Proxy for OCP cluster installation
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/installcfg/installcfg.go
  internal/installcfg/installcfg_test.go
  models/cluster.go
  models/cluster_create_params.go
  models/cluster_update_params.go
  models/image_create_params.go
  models/image_info.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, lgtm

#95 MGMT-1772 Use an env var to set the s3 url scheme if not present
  cmd/main.go
  deploy/assisted-service.yaml
  openshift/template.yaml
  pkg/s3wrapper/util.go
  pkg/s3wrapper/util_test.go
Labels: approved, lgtm

#78 MGMT-1388 add validation data to cluster model
  go.mod
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/common.go
  internal/cluster/error.go
  internal/cluster/finalizing.go
  internal/cluster/installed.go
  internal/cluster/installer.go
  internal/cluster/installer_test.go
  internal/cluster/installing.go
  internal/cluster/insufficient.go
  internal/cluster/insufficient_test.go
  internal/cluster/mock_cluster_api.go
  internal/cluster/ready.go
  internal/cluster/ready_test.go
  internal/cluster/refresh_status_preprocessor.go
  internal/cluster/statemachine.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/cluster/validation_id.go
  internal/cluster/validator.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/host/transition.go
  internal/imgexpirer/mock_s3iface.go
  internal/metrics/mock_netricsManager_api.go
  internal/network/machine_network_cidr.go
  models/cluster.go
  models/cluster_validation_id.go
  pkg/job/mock_local_job.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: approved, lgtm

#126 Adding ServiceMonitor template
  openshift/template-monitoring.yaml
Labels: approved, lgtm

#121 Update local job to use assisted-iso-create
  Dockerfile.assisted-service-onprem
  pkg/job/local_job.go
Labels: approved, lgtm

#131 Added assisted-iso-create to the build pipeline
  Jenkinsfile
Labels: approved, lgtm

#130 fix subsystem test - cancel installation with a disabled host
  subsystem/cluster_test.go
Labels: approved, lgtm

#133 Fixed assisted-iso-create build pipeline
  Jenkinsfile
Labels: approved, lgtm

#135 Use the latest ignition generator image
  pkg/job/job.go
Labels: approved, lgtm

#134 The working directory needs group write permissions
  Dockerfile.assisted-iso-create
Labels: approved, lgtm

#132 Update image assisted-ignition-generator name
  Dockerfile.assisted-service-onprem
  README.md
  tools/deploy_assisted_installer_configmap.py
Labels: approved, lgtm

#136 fix dump yaml
  tools/update_bm_cm.py
Labels: approved, lgtm

#127 MGMT-1821: Store image with .iso prefix
  internal/bminventory/inventory.go
Labels: approved, lgtm

#140 MGMT-1836 increase subsystem timeout to 30 minutes
  Makefile
Labels: approved, lgtm

#138 MGMT-1835 - change iso creation image name
  Jenkinsfile
  Makefile
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/mock_cluster_api.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/imgexpirer/mock_s3iface.go
  internal/metrics/mock_netricsManager_api.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  pkg/job/job.go
  tools/deploy_assisted_installer_configmap.py
Labels: approved, lgtm

#129 MGMT-1720 Modify UpdateCluster to handle DHCP mode and machine network cidr change
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/network/machine_network_cidr.go
  models/cluster_update_params.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, lgtm

#142 MGMT-1839 fix adding query_option to db pointer
  internal/bminventory/inventory.go
  pkg/transaction/transaction.go
Labels: approved, lgtm

#139 MGMT-1677 move preparing for installation to cluster state machine
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/prepare.go
  internal/cluster/prepare_test.go
  internal/cluster/statemachine.go
  internal/cluster/transition.go
Labels: approved, lgtm

#145 MGMT-1841 Increase wait for service timeout
  tools/wait_for_assisted_service.py
Labels: approved, lgtm

#146 fix subsytem test install cluster requirement
  subsystem/cluster_test.go
Labels: approved, lgtm

#147 Igal/upload logs intaller
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/installcmd.go
  internal/host/installcmd_test.go
Labels: approved, lgtm

#149 MGMT-1759 add notification when master test branch fails on jenkins
  Jenkinsfile
Labels: approved, lgtm

#124 Avishay/ocpbugsm 13596
  client/events/events_client.go
  client/events/list_events_parameters.go
  client/events/list_events_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/events/event.go
  internal/events/event_test.go
  internal/events/events_api.go
  internal/events/mock_event.go
  internal/host/common.go
  internal/host/common_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/instructionmanager_test.go
  internal/host/transition_test.go
  internal/imgexpirer/imgexpirer.go
  internal/imgexpirer/imgexpirer_test.go
  models/event.go
  pkg/job/job.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/events/list_events.go
  restapi/operations/events/list_events_parameters.go
  restapi/operations/events/list_events_responses.go
  restapi/operations/events/list_events_urlbuilder.go
  subsystem/image_test.go
  swagger.yaml
Labels: approved, lgtm

#144 MGMT-1833 Change cluster and host state machines to adapt to DHCP mode
  internal/cluster/conditions.go
  internal/cluster/refresh_status_preprocessor.go
  internal/cluster/statemachine.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/cluster/validator.go
  internal/host/validator.go
Labels: approved, lgtm

#152 OCPBUGSM-14226 fix subsystem-clean to remove correct pods
  Makefile
Labels: approved, lgtm

#73 MGMT-1430 - Authorization support with AMS
  Makefile
  cmd/main.go
  deploy/assisted-installer-sso.yaml
  deploy/assisted-service-configmap.yaml
  deploy/assisted-service.yaml
  go.mod
  go.sum
  internal/bminventory/inventory.go
  internal/identity/identity.go
  internal/identity/identity_test.go
  models/cluster.go
  models/host.go
  openshift/template.yaml
  pkg/auth/auth.go
  pkg/auth/auth_handler.go
  pkg/auth/auth_handler_test.go
  pkg/auth/authz_handler.go
  pkg/auth/authz_handler_test.go
  pkg/ocm/authorization.go
  pkg/ocm/client.go
  pkg/ocm/pullsecret_auth.go
  restapi/embedded_spec.go
  skipper.yaml
  swagger.yaml
  tools/deploy_assisted_installer.py
  tools/deploy_assisted_installer_configmap.py
  tools/deploy_sso_secret.py
Labels: approved, lgtm

#153 OCPBUGSM-13634 fix clear-deployment to delete configmaps as well
  tools/clear_deployment.py
Labels: approved, lgtm

#137 MGMT-1667: added minikube profile flag
  Makefile
  skipper.yaml
  tools/clear_deployment.py
  tools/debug/minikube_postgres.sh
  tools/deploy_assisted_installer.py
  tools/deploy_assisted_installer_configmap.py
  tools/deploy_grafana.py
  tools/deploy_inventory_service.py
  tools/deploy_mariadb.py
  tools/deploy_namespace.py
  tools/deploy_olm.py
  tools/deploy_postgres.py
  tools/deploy_prometheus.py
  tools/deploy_role.py
  tools/deploy_route53.py
  tools/deploy_s3.py
  tools/deploy_scality_configmap.py
  tools/deploy_tls_secret.py
  tools/deploy_ui.py
  tools/deployment_options.py
  tools/utils.py
  tools/wait_for_assisted_service.py
Labels: approved, lgtm

#154 MGMT-1858 - subsystem should use dummy ignition image and not a real one
  Dockerfile.ignition-dummy
  Makefile
  dummy-ignition/main.go
  pkg/job/job.go
  pkg/job/mock_job.go
  pkg/job/mock_local_job.go
  pkg/s3wrapper/mock_s3wrapper.go
  tools/deploy_assisted_installer.py
  tools/deploy_assisted_installer_configmap.py
Labels: approved, lgtm

#158 MGMT-1834 Subsystem tests for DHCP, and some bug fixes
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  subsystem/cluster_test.go
  subsystem/host_test.go
Labels: approved, lgtm

#150 Igal/download logs
  client/installer/download_host_logs_parameters.go
  client/installer/download_host_logs_responses.go
  client/installer/installer_client.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/mock_cluster_api.go
  internal/connectivity/mock_connectivity_validator.go
  internal/hardware/mock_validator.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/imgexpirer/mock_s3iface.go
  internal/metrics/mock_netricsManager_api.go
  pkg/auth/auth_handler_test.go
  pkg/s3wrapper/client.go
  pkg/s3wrapper/errors.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/download_host_logs.go
  restapi/operations/installer/download_host_logs_parameters.go
  restapi/operations/installer/download_host_logs_responses.go
  restapi/operations/installer/download_host_logs_urlbuilder.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: approved, lgtm

#141 [MGMT-1828] Generate new ISO after proxy was changed
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/db.go
  subsystem/image_test.go
Labels: approved, lgtm

#104 MGMT-1577 auto assign host role
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/common.go
  internal/cluster/installer.go
  internal/cluster/installing.go
  internal/cluster/mock_cluster_api.go
  internal/cluster/refresh_status_preprocessor.go
  internal/cluster/statemachine.go
  internal/cluster/transition_test.go
  internal/cluster/validation_id.go
  internal/cluster/validator.go
  internal/common/common.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/common.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/host/refresh_status_preprocessor.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/host/validator.go
  internal/imgexpirer/mock_s3iface.go
  internal/metrics/mock_netricsManager_api.go
  models/cluster_validation_id.go
  models/host.go
  models/host_role.go
  models/host_role_update_params.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: approved, lgtm

#162 MGMT-1855 - Logs spammed from UpdateCluster
  internal/cluster/common.go
Labels: approved, lgtm

#163 Let the DB time to die before restarting for the unitest
  Makefile
Labels: approved, lgtm

#143 MGMT-882 Enable deploy with HTTPS without cert verification
  deploy/assisted-service-configmap.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/installcmd.go
  internal/host/installcmd_test.go
  internal/host/instructionmanager.go
  pkg/job/job.go
  pkg/job/local_job.go
  swagger.yaml
  tools/deploy_assisted_installer_configmap.py
  tools/deploy_inventory_service.py
  tools/deployment_options.py
  tools/utils.py
  tools/wait_for_assisted_service.py
Labels: approved, lgtm

#156 Adding 'assisted-iso-generator' to app-interface.
  build_deploy.sh
Labels: approved, lgtm

#107 deployment: change aws mountPath
  deploy/assisted-service.yaml
Labels: approved, lgtm

#169 MGMT-1877 Wrong image for dhcp allocation containerized application
  internal/host/instructionmanager.go
Labels: approved, lgtm

#167 MGMT-1863 Get preassigned url to download logs
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#171 Validate Proxy settings
  go.mod
  internal/bminventory/inventory.go
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
Labels: approved, lgtm

#157 MGMT-1859: use CapabilityReview via SDK
  go.mod
  go.sum
  pkg/ocm/authorization.go
Labels: approved, lgtm

#151 MGMT 1768: Create and use local filesystem implementation
  Dockerfile.assisted-service-onprem
  Makefile
  assisted-iso-create/main.go
  cmd/main.go
  discovery-image-a55d012f-fed7-4b3e-87cb-53e3dccccdd4.iso?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA52ZYGBOVE6BP6R6V%2F20200818%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200818T132452Z&X-Amz-Expires=3600&X-Amz-SignedHeader
  go.mod
  go.sum
  internal/bminventory/inventory.go
  internal/imgexpirer/imgexpirer.go
  onprem-environment
  pkg/job/local_job.go
  pkg/s3wrapper/client.go
  pkg/s3wrapper/client_test.go
  pkg/s3wrapper/filesystem.go
  pkg/s3wrapper/filesystem_test.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3wrapper.go
Labels: approved, lgtm

#176 OCPBUGSM-16010 Add UT coverage to cluster refresh
  internal/cluster/transition_test.go
Labels: approved, lgtm

#170 Revert "Adding 'assisted-iso-generator' to app-interface."
  build_deploy.sh
Labels: approved, lgtm

#172 Raz/mgmt 1245
  tools/deploy_postgres.py
  tools/deploy_s3.py
  tools/pvc_size_utils.py
  tools/utils.py
Labels: approved, lgtm

#175 MGMT-1450: Create assisted installer artifact to run on-prem
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  docs/README.md
  docs/installer-live-iso.md
Labels: lgtm

#180 Hotfix remove mistakenly discovery image iso
  discovery-image-a55d012f-fed7-4b3e-87cb-53e3dccccdd4.iso?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIA52ZYGBOVE6BP6R6V%2F20200818%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20200818T132452Z&X-Amz-Expires=3600&X-Amz-SignedHeader
Labels: approved, lgtm

#181 MGMT-1450: remove s3 from live ISO
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  docs/installer-live-iso.md
Labels: approved, lgtm

#183 fixes error when re-generating an ISO for the same cluster on-prem
  Makefile
  assisted-iso-create/main.go
  pkg/job/local_job.go
  subsystem/image_test.go
Labels: approved, lgtm

#196 Revert "MGMT-1849: Delete PVCs on clear-deplyment by flag (#161)"
  Makefile
  tools/clear_deployment.py
Labels: approved, lgtm

#174 Mgmt-1768 Cleanup remaining s3-volume
  Makefile
Labels: approved, lgtm

#178 OCPBUGSM-15906 - Cluster has Ready status although DNS domain is not set
  client/assisted_install_client.go
  client/events/events_client.go
  client/installer/installer_client.go
  client/managed_domains/managed_domains_client.go
  client/versions/versions_client.go
  internal/cluster/cluster_test.go
  internal/cluster/refresh_status_preprocessor.go
  internal/cluster/statemachine.go
  internal/cluster/transition_test.go
  internal/cluster/validation_id.go
  internal/cluster/validator.go
  models/cluster_validation_id.go
  restapi/doc.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, lgtm

#159 MGMT-1867: set user_name as 'admin' when auth is disabled
  internal/identity/identity.go
  pkg/auth/auth_handler.go
  pkg/auth/authz_handler.go
  pkg/ocm/pullsecret_auth.go
Labels: approved, lgtm

#199 MGMT-1723 Run UI yaml generation directly
  Dockerfile.assisted-service-build
  tools/deploy_ui.py
  tools/utils.py
Labels: approved, lgtm

#195 Osher/jenkins file notification
  Jenkinsfile
Labels: approved

#200 Replace print with log in UI deployment
  tools/deploy_ui.py
Labels: approved, lgtm

#201 Add slack notification
  Jenkinsfile
Labels: approved

#197 Adding 'assisted-iso-generator' to app-interface.
  Makefile
  build_deploy.sh
  openshift/template.yaml
  skipper.yaml
Labels: approved, lgtm

#204 Add debugging info to update tag failure
  pkg/s3wrapper/client.go
Labels: approved, lgtm

#205 Fix docker installation in build image
  Dockerfile.assisted-service-build
Labels: approved, lgtm

#206 Revert "add link to notification"
  Jenkinsfile
Labels: approved, lgtm

#184 MGMT-1450: Fix auth.json path in live ISO and FCC
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  docs/installer-live-iso.md
Labels: approved, lgtm

#210 Add -r option to xargs
  Jenkinsfile
  Makefile
  tools/clear_deployment.py
Labels: approved, lgtm

#212 Adding missing parameters to openshift/template.yaml.
  openshift/template.yaml
Labels: approved, lgtm

#101 Wrap JWKS and OCM URLs with quotation marks in configMap
  tools/deploy_assisted_installer_configmap.py
Labels: approved, lgtm

#207 Igal/upload logs
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/events/mock_event.go
  internal/host/host.go
  internal/host/mock_host_api.go
  models/host.go
  pkg/job/mock_job.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: approved, lgtm

#211 notify and fail job if minikube is not running
  Jenkinsfile
Labels: approved, lgtm

#213 MGMT-1924 Remove severity of logging message when a host does not belong to machine cidr when checking free_addresses
  internal/network/machine_network_cidr.go
Labels: approved, lgtm

#209 OCPBUGSM-16347 delete ingress configuration on cleanup
  tools/clear_deployment.py
Labels: approved, lgtm

#194 MGMT-1864 - Validate advanced networking fields
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster_test.go
  internal/cluster/refresh_status_preprocessor.go
  internal/cluster/statemachine.go
  internal/cluster/transition_test.go
  internal/cluster/validation_id.go
  internal/cluster/validator.go
  internal/network/cidr_validations.go
  models/cluster_validation_id.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, lgtm

#217 Updating the value of SELF_VERSION parameter in openshift/template.yaml.
  openshift/template.yaml
Labels: approved, lgtm

#219 Changed the TAG of IMAGE_BUILDER in openshift/template.yaml.
  openshift/template.yaml
Labels: approved, lgtm

#208 MGMT-1865: Add 'force' flag to job Deletion
  pkg/job/job.go
  pkg/job/job_test.go
Labels: approved, lgtm

#220 MGMT-1644: pvc_size_utils.py current size check fix
  Makefile
  tools/clear_deployment.py
Labels: approved, lgtm

#218 MGMT-1792 add ready api to assisted-service
  cmd/main.go
  tools/wait_for_assisted_service.py
Labels: approved, lgtm

#222 Added image building to pr_check.sh.
  build_deploy.sh
  build_images.sh
  pr_check.sh
Labels: approved, lgtm

#165 Adding 'liveness' and readiness probs to the deployments.
  deploy/assisted-service.yaml
  openshift/template.yaml
Labels: approved, lgtm

#224 OCPBUGSM-16477 [Advanced networking] Illegal CIDRS not verified
  internal/bminventory/inventory_test.go
  internal/cluster/refresh_status_preprocessor.go
  internal/cluster/validator.go
  internal/network/cidr_validations.go
  pkg/job/mock_job.go
Labels: approved, lgtm

#229 Fixing build_deploy.sh and pr_check.sh.
  build_deploy.sh
  pr_check.sh
Labels: approved, lgtm

#232 OCPBUGSM-16205: Remove empty parenthesis from event info
  internal/host/common.go
Labels: approved, lgtm

#198 MGMT-1506: Return minimum host requirements
  client/installer/get_host_requirements_parameters.go
  client/installer/get_host_requirements_responses.go
  client/installer/installer_client.go
  internal/bminventory/inventory.go
  internal/hardware/mock_validator.go
  internal/hardware/validator.go
  internal/host/host.go
  internal/host/mock_host_api.go
  models/host_requirements.go
  models/host_requirements_role.go
  pkg/auth/auth_handler_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/get_host_requirements.go
  restapi/operations/installer/get_host_requirements_parameters.go
  restapi/operations/installer/get_host_requirements_responses.go
  restapi/operations/installer/get_host_requirements_urlbuilder.go
  swagger.yaml
Labels: approved, lgtm

#148 OCPBUGSM-15827: Severity for host insufficient status event should be…
  internal/common/host_utils.go
  internal/host/transition_test.go
Labels: approved, lgtm

#233 OCPBUGSM-13814: Added SSH public key validation
  internal/bminventory/inventory.go
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
  subsystem/cluster_test.go
Labels: approved, lgtm

#226 MGMT-1950 Bugfix race-condition in waitFor subsystem functions
  subsystem/cluster_test.go
Labels: approved, lgtm

#231 Raz/ocpbugsm 16238
  internal/host/host.go
  internal/host/host_test.go
Labels: approved, lgtm

#166 OCPBUGSM-15826: Rewrite status infos
  internal/host/common.go
  internal/host/host_test.go
  internal/host/statemachine.go
  internal/host/transition_test.go
Labels: approved, lgtm, ok-to-test

#168 Raz/mgmt 1685
  Makefile
  deploy/assisted-service-configmap.yaml
  internal/host/installcmd.go
  internal/host/installcmd_test.go
  internal/host/instructionmanager.go
  tools/deploy_assisted_installer_configmap.py
Labels: approved, lgtm

#187 Raz/mgmt 1644
  Dockerfile.assisted-iso-create
  Dockerfile.ignition-dummy
  Makefile
  tools/clear_deployment.py
  tools/deploy_assisted_installer.py
  tools/deploy_assisted_installer_configmap.py
  tools/deploy_grafana.py
  tools/deploy_inventory_service.py
  tools/deploy_mariadb.py
  tools/deploy_namespace.py
  tools/deploy_olm.py
  tools/deploy_postgres.py
  tools/deploy_prometheus.py
  tools/deploy_role.py
  tools/deploy_route53.py
  tools/deploy_s3.py
  tools/deploy_scality_configmap.py
  tools/deploy_sso_secret.py
  tools/deploy_tls_secret.py
  tools/deploy_ui.py
  tools/pvc_size_utils.py
  tools/utils.py
  tools/wait_for_assisted_service.py
Labels: approved, lgtm

#241 Multiple issues
  internal/bminventory/inventory.go
Labels: approved, lgtm

#243 Fix installation timeout deployment in makefile
  Makefile
Labels: approved, lgtm

#245 [MGMT-1984] No Proxy does not support '*' as value
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
Labels: approved, lgtm
