Repository openshift/assisted-service, pull requests merged in 2020-10, with the labels that each got.

#452 Eran/bug 1883887
  internal/host/host.go
Labels: approved, lgtm

#440 MGMT-2073 - implement host/cluster state machine for day2 flow
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/mock_cluster_api.go
  internal/cluster/statemachine.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/instructionmanager.go
  internal/host/instructionmanager_test.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/host/statemachine.go
  internal/host/transition.go
  internal/host/transition_test.go
  internal/host/validator.go
  internal/metrics/mock_netricsManager_api.go
  pkg/job/mock_job.go
  pkg/job/mock_local_job.go
  pkg/leader/mock_leader_elector.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3wrapper.go
Labels: approved, lgtm

#458 NO-JIRA add kni-projects team to reviewers
  OWNERS
Labels: approved, lgtm

#454 Refactor ignition generation
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
Labels: approved, lgtm

#445 MGMT-2292 cache payload in UserAuth flow
  pkg/auth/auth_handler.go
Labels: approved, lgtm

#461 OCPBUGSM-18341 added upload of install-config.yaml to s3 to ignition …
  internal/ignition/ignition.go
  subsystem/cluster_test.go
Labels: approved, lgtm

#443 MGMT-2052 - Patching OPENSHIFT_RELEASE_IMAGE variable to make that customizable on the Assisted Service
  Makefile
  README.md
  deploy/assisted-service-configmap.yaml
  tools/deploy_assisted_installer_configmap.py
  tools/update_bm_cm.py
Labels: approved, lgtm

#464 MGMT-2252: Don't log secrets from the ignitionConfig
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#462 MGMT-2038: Make for-update transaction in enable/disable
  internal/bminventory/inventory.go
Labels: approved, lgtm

#465 MGMT-2148 - InstallHosts imeplementation
  client/installer/install_hosts_parameters.go
  client/installer/install_hosts_responses.go
  client/installer/installer_client.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/registrar.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_handler_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/install_hosts.go
  restapi/operations/installer/install_hosts_parameters.go
  restapi/operations/installer/install_hosts_responses.go
  restapi/operations/installer/install_hosts_urlbuilder.go
  swagger.yaml
Labels: approved, lgtm

#425 MGMT-2075 swagger: API connectivity check request and step
  models/connectivity_check_api_request.go
  models/step_type.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, lgtm

#416 MGMT-2240 adding time calculation to auth, register and update cluster
  cmd/main.go
  go.mod
  internal/bminventory/inventory_test.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_netricsManager_api.go
  pkg/commonutils/common_utils.go
  pkg/ocm/authorization.go
  pkg/ocm/client.go
  pkg/ocm/pullsecret_auth.go
Labels: approved, lgtm

#472 MGMT-2337 Remove create, delete and monitor from job API
  internal/bminventory/inventory_test.go
  pkg/generator/generator.go
  pkg/generator/mock_install_config.go
  pkg/job/job.go
  pkg/job/job_test.go
  pkg/job/local_job.go
  pkg/job/mock_job.go
  pkg/job/mock_local_job.go
Labels: approved, lgtm

#460 MGMT-2328: always require user reboot by default
  internal/host/host.go
  internal/host/host_test.go
  internal/host/statemachine.go
  internal/host/transition.go
  subsystem/cluster_test.go
Labels: approved, lgtm

#418 NO-ISSUE: grammar fix in log messages
  internal/cluster/common.go
  internal/host/common.go
Labels: approved, lgtm

#474 BUG-1885001 Register Error event will show internal error
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#446 OCPBUGSM-17732 Add timeout trensition to host installing status
  internal/host/common.go
  internal/host/host.go
  internal/host/statemachine.go
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, lgtm

#455 NO-ISSUE cleaning vm pre build
  Jenkinsfile
Labels: approved, lgtm

#470 MGMT-2279 Pull Secret validation - Auth disabled
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#475 MGMT-2297 Cluster monitor should filter our installed and clusters in…
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
Labels: approved, lgtm

#456 NO-ISSUE Use gotestsum tool for testing and publish junit on Jenkins
  .gitignore
  Dockerfile.assisted-service-build
  Jenkinsfile
  Makefile
  pkg/log/logcontext_test.go
  pkg/requestid/requestid_test.go
  pkg/thread/example_test.go
Labels: approved, lgtm

#479 NO-ISSUE Update Owners file
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm

#481 NO-ISSUE Use errors pkg instead of fmt.Errorf
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validations.go
  internal/connectivity/validator.go
  internal/hardware/validator.go
  internal/host/freeaddressescmd.go
  internal/host/host.go
  internal/host/installcmd.go
  internal/ignition/ignition.go
  internal/network/machine_network_cidr.go
  pkg/auth/auth_handler.go
  pkg/auth/auth_handler_test.go
  pkg/auth/auth_handler_utils.go
  pkg/auth/authz_handler.go
  pkg/log/logcontext_test.go
  pkg/ocm/authorization.go
  pkg/ocm/pullsecret_auth.go
Labels: approved, lgtm

#482 Igal/time skew validation
  internal/bminventory/inventory.go
  internal/cluster/mock_cluster_api.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/hardware/validator.go
  internal/host/host_test.go
  internal/host/instructionmanager.go
  internal/host/instructionmanager_test.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/host/refresh_status_preprocessor.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/host/validator.go
  internal/metrics/mock_netricsManager_api.go
  models/host_validation_id.go
  models/inventory.go
  pkg/generator/mock_install_config.go
  pkg/leader/mock_leader_elector.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3wrapper.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  subsystem/host_test.go
  swagger.yaml
Labels: approved, lgtm

#483 MGMT-2182 Add event on successful cluster registration
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#484 NO-ISSUE Verify minikube before Makefile targets deploying to minikube
  Makefile
Labels: approved, lgtm

#487 MGMT-2356: Update livecd name in S3
  pkg/s3wrapper/client.go
Labels: approved, lgtm

#255 MGMT-1755 Setup TLS trust on-prem
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  go.mod
  go.sum
  internal/bminventory/inventory.go
  internal/common/common.go
  internal/host/installcmd.go
  internal/host/instructionmanager.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  pkg/job/job.go
  pkg/job/local_job.go
Labels: approved, lgtm

#486 MGMT-2138 Added asisted-iso-create rhcos image download back
  Dockerfile.assisted-iso-create
  Makefile
  README.md
Labels: approved, kind/dependency-change, lgtm

#450 MGMT-2271 API VIP connectivity check
  internal/bminventory/inventory.go
  internal/host/apivipconnectivitycheckcmd.go
  internal/host/apivipconnectivitycheckcmd_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/instructionmanager.go
  internal/host/mock_host_api.go
  internal/host/refresh_status_preprocessor.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/host/validator.go
  models/api_vip_connectivity_request.go
  models/api_vip_connectivity_response.go
  models/cluster.go
  models/cluster_update_params.go
  models/host.go
  models/host_validation_id.go
  openshift/template.yaml
  restapi/embedded_spec.go
  swagger.yaml
  tools/deploy_assisted_installer_configmap.py
Labels: api-review, approved, lgtm

#473 MGMT-2314 Add cluster_id label to cluster related metrics
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/mock_cluster_api.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_netricsManager_api.go
  pkg/generator/mock_install_config.go
  pkg/leader/mock_leader_elector.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3wrapper.go
Labels: approved, lgtm

#489 MGMT-2329 - update OCP release image for 4.6 to fc.9
  Makefile
Labels: approved, lgtm

#488 MGMT-2342 move ntp validation from host to cluster validator
  internal/cluster/cluster_test.go
  internal/cluster/refresh_status_preprocessor.go
  internal/cluster/statemachine.go
  internal/cluster/transition_test.go
  internal/cluster/validation_id.go
  internal/cluster/validator.go
  internal/host/host_test.go
  internal/host/refresh_status_preprocessor.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/host/validator.go
  models/cluster_validation_id.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#468 MGMT-2288: For image generation, call copy parts concurrently
  pkg/s3wrapper/client_test.go
  pkg/s3wrapper/upload_iso.go
Labels: approved, lgtm

#410 MGMT-2128: Change log filenames, including for presigned S3 urls
  go.mod
  go.sum
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/common/common.go
  pkg/s3wrapper/client.go
  pkg/s3wrapper/filesystem.go
  pkg/s3wrapper/mock_s3wrapper.go
Labels: approved, lgtm

#463 MGMT-2357: Return an error when the cluster is not found for upload logs
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#335 Use infra_error for all 401 and 403 responses
  client/installer/get_cluster_install_config_responses.go
  client/installer/get_host_requirements_responses.go
  client/installer/update_cluster_install_config_responses.go
  restapi/embedded_spec.go
  restapi/operations/installer/get_cluster_install_config_responses.go
  restapi/operations/installer/get_host_requirements_responses.go
  restapi/operations/installer/update_cluster_install_config_responses.go
  swagger.yaml
Labels: approved, lgtm

#485 NO-ISSUE Add build-all Makefile target using ASSISTED_ORG and ASSISTE…
  Dockerfile.assisted-service
  Dockerfile.assisted-service-onprem
  Jenkinsfile
  Makefile
  skipper.yaml
Labels: approved, kind/dependency-change, lgtm

#490 MGMT-2359: Event log spam fix
  internal/bminventory/inventory.go
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, lgtm

#495 MGMT-2372 on-prem subsystem tests broke after livecd.iso was renamed
  Dockerfile.assisted-service-onprem
  Makefile
  pkg/job/job.go
  pkg/s3wrapper/client.go
  skipper.yaml
Labels: approved, kind/dependency-change, lgtm

#497 MGMT-1710: trimspace around provided pull secrets
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validations.go
Labels: approved, lgtm

#477 Increase unitest timeout to 30 min
  Makefile
Labels: approved, lgtm

#498 OCPBUGSM-17571 Block creating a cluster without a pull secret
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  subsystem/authz_test.go
  subsystem/cluster_test.go
  subsystem/host_test.go
  subsystem/image_test.go
  subsystem/wiremock_stubs.go
Labels: approved, lgtm

#491 host: removed redundant debug log
  internal/host/host.go
Labels: approved, lgtm

#500 BUG-1885920 failure in host logs download with presigned url
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#502 NO-ISSUE Remove prefix commit message checking to a substring check
  tools/check-commit-message.sh
Labels: approved, lgtm

#503 MGMT-2363 Add clusterId label to host related metrics
  internal/host/host.go
  internal/host/host_test.go
  internal/host/transition_test.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_netricsManager_api.go
Labels: approved, lgtm

#504 NO-ISSUE add merge back to commit check regex
  tools/check-commit-message.sh
Labels: approved, lgtm

#505 NO-JIRA Increase CPU limits
  deploy/assisted-service.yaml
  openshift/template.yaml
Labels: approved, lgtm

#493 MGMT-2077 - create subsystem test for day2 flow
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  subsystem/cluster_test.go
  subsystem/day2_cluster_test.go
  subsystem/utils_test.go
Labels: approved, lgtm

#501 Raz/mgmt 1659 cluster cancel status
  docs/ClusterStatus.dot
  docs/ClusterStatus.png
  docs/HostStatus.dot
  docs/HostStatus.png
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/statemachine.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/host/host_test.go
  internal/host/instructionmanager.go
  internal/host/instructionmanager_test.go
  internal/host/statemachine.go
  internal/host/transition.go
  internal/host/transition_test.go
  models/cluster.go
  models/host.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#506 APPSRE-2377 Use a random ID instead of the commit hash
  openshift/template-post-deploy-job.yaml
Labels: approved, lgtm

#508 BUG-1886087 adding HostStatusResettingPendingUserAction and HostStatu…
  internal/cluster/transition_test.go
  internal/cluster/validator.go
Labels: approved, lgtm

#494 MGMT-2341 Add host hw type to host metrics
  internal/host/host.go
  internal/host/host_test.go
  internal/host/transition_test.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_netricsManager_api.go
  subsystem/host_test.go
Labels: approved, lgtm

#511 MGMT-2381 Missed image expiration events upon leader change
  internal/imgexpirer/imgexpirer.go
  internal/imgexpirer/imgexpirer_test.go
Labels: approved, lgtm

#351 Wording fixes and tweaks
  client/installer/update_host_install_progress_parameters.go
  internal/bminventory/inventory.go
  internal/cluster/transition_test.go
  internal/cluster/validator.go
  internal/host/transition_test.go
  internal/host/validator.go
  models/cluster.go
  models/cluster_update_params.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/installer/download_cluster_i_s_o.go
  restapi/operations/installer/generate_cluster_i_s_o.go
  restapi/operations/installer/get_cluster_install_config.go
  restapi/operations/installer/get_credentials.go
  restapi/operations/installer/get_presigned_for_cluster_files.go
  restapi/operations/installer/update_cluster_install_config.go
  restapi/operations/installer/update_host_install_progress.go
  restapi/operations/installer/update_host_install_progress_parameters.go
  swagger.yaml
Labels: api-review, approved, lgtm

#514 NO-ISSUE fix cluster unit tests
  internal/cluster/transition_test.go
Labels: approved

#512 Revert "MGMT-2283 change unit-tests db into quay.io/ocpmetal/postgres…
  Makefile
  internal/common/common_unitest_db.go
Labels: approved, lgtm

#424 MGMT-2238: Deployment files: Store namespace within quotes
  tools/deploy_assisted_installer.py
  tools/deploy_assisted_installer_configmap.py
  tools/deploy_grafana.py
  tools/deploy_inventory_service.py
  tools/deploy_mariadb.py
  tools/deploy_namespace.py
  tools/deploy_prometheus.py
  tools/deploy_role.py
  tools/deploy_route53.py
  tools/deploy_scality_configmap.py
  tools/deploy_sso_secret.py
  tools/deploy_ui.py
Labels: approved, lgtm

#518 BZ-1886431 - Remove ignition-generator leftovers
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  openshift/template.yaml
  pkg/job/job.go
  tools/deploy_assisted_installer_configmap.py
  tools/update_bm_cm.py
Labels: approved, lgtm

#310 MGMT-1793 - Allow discovery ignition customization
  client/installer/get_discovery_ignition_parameters.go
  client/installer/get_discovery_ignition_responses.go
  client/installer/get_free_addresses_responses.go
  client/installer/installer_client.go
  client/installer/update_discovery_ignition_parameters.go
  client/installer/update_discovery_ignition_responses.go
  client/installer/update_host_install_progress_parameters.go
  client/installer/update_host_install_progress_responses.go
  client/versions/versions_client.go
  go.sum
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/ignition/ignition.go
  mocks/mock_assisted_service.go
  models/cluster.go
  models/cluster_create_params.go
  models/cluster_update_params.go
  models/dhcp_allocation_request.go
  models/dhcp_allocation_response.go
  models/discovery_ignition_params.go
  models/error.go
  models/event.go
  models/host.go
  models/host_progress_info.go
  models/host_stage.go
  models/image_info.go
  models/infra_error.go
  pkg/auth/auth_handler_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/events/list_events.go
  restapi/operations/installer/download_cluster_logs.go
  restapi/operations/installer/download_host_logs.go
  restapi/operations/installer/get_discovery_ignition.go
  restapi/operations/installer/get_discovery_ignition_parameters.go
  restapi/operations/installer/get_discovery_ignition_responses.go
  restapi/operations/installer/get_discovery_ignition_urlbuilder.go
  restapi/operations/installer/get_free_addresses_responses.go
  restapi/operations/installer/get_host_requirements.go
  restapi/operations/installer/update_discovery_ignition.go
  restapi/operations/installer/update_discovery_ignition_parameters.go
  restapi/operations/installer/update_discovery_ignition_responses.go
  restapi/operations/installer/update_discovery_ignition_urlbuilder.go
  restapi/operations/installer/update_host_install_progress_parameters.go
  restapi/operations/installer/update_host_install_progress_responses.go
  restapi/operations/managed_domains/list_managed_domains.go
  restapi/operations/versions/list_component_versions.go
  swagger.yaml
Labels: api-review, approved, lgtm

#492 Refresh installation timeout in case there is a progress
  internal/host/host.go
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, lgtm

#507 MGMT-2318 pass verify CIDR flag to APIVIPConnectivityCheckCmd
  internal/host/apivipconnectivitycheckcmd.go
  internal/host/apivipconnectivitycheckcmd_test.go
  internal/host/instructionmanager.go
  models/api_vip_connectivity_request.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#510 MGMT-2296 Host and cluster monitor iterate in baches
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/transition_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/monitor.go
  internal/host/monitor_test.go
Labels: approved, lgtm

#523 MGMT-2392 - allow updating api vip dnsname/ip in day2 cluster
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#509 MGMT-2211 Host registration returns command for starting next-step agent
  client/installer/register_host_responses.go
  internal/bminventory/inventory.go
  models/host_registration_response.go
  restapi/embedded_spec.go
  restapi/operations/installer/register_host_responses.go
  subsystem/utils_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#376 MGMT-2195 Add CONTRIBUTING file
  CONTRIBUTING.md
Labels: approved, lgtm

#520 NO-ISSUE adding gitattributes declaring generated files
  .gitattributes
Labels: approved, lgtm

#528 MGMT-2367 Fix multiple events unit test
  internal/events/event_test.go
Labels: approved, lgtm

#276 [BZ1874632] Fixing Monitoring deployment
  tools/deploy_olm.py
  tools/utils.py
Labels: approved, lgtm

#530 OCPBUGSM-18587: updated stop installation cmd
  internal/host/stopinstallation.go
Labels: approved, lgtm

#532 NO-ISSUE Set local ut run db to alpine
  internal/common/common_unitest_db.go
Labels: approved, lgtm

#536 MGMT-2364 API to signal next step runner to exit
  models/steps.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#527 MGMT-2385 move upload logs from install step to stopAll step, to uplo…
  internal/host/installcmd.go
  internal/host/installcmd_test.go
  internal/host/instructionmanager.go
  internal/host/stopinstallation.go
  internal/host/stopinstallation_test.go
Labels: approved, lgtm

#542 MGMT-2427 use SUPPORT_L2 env var
  internal/host/instructionmanager.go
Labels: approved, lgtm

#538 NO-ISSUE Jenkins print kubernetes snapshot
  Jenkinsfile
Labels: approved, lgtm

#535 OCPBUGSM-17572 misleading suggestions when saving invalid CIDR
  internal/network/cidr_validations.go
Labels: approved, lgtm

#480 MGMT-2326: Added controller_logs_collected_at to 'cluster' relation in DB.
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/mock_cluster_api.go
  internal/cluster/transition.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/metrics/mock_netricsManager_api.go
  models/cluster.go
  pkg/generator/mock_install_config.go
  pkg/leader/mock_leader_elector.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3wrapper.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#531 NO-ISSUE Remove sleep from unit test
  internal/events/event_test.go
Labels: approved, lgtm

#534 OCPBUGSM-18826 wrong validation error return when using out of range prefix
  internal/cluster/transition_test.go
  internal/network/cidr_validations.go
Labels: approved, lgtm

#526 MGMT-2427 openshift template: added SUPPORT_L2
  openshift/template.yaml
Labels: approved, lgtm

#471 Publish images per versions
  Jenkinsfile
Labels: approved, lgtm

#499 MGMT-2301 expecting completion times on both success and error to be updated
  Makefile
  internal/cluster/cluster_test.go
  internal/cluster/common.go
  internal/cluster/transition.go
  subsystem/cluster_test.go
Labels: approved, lgtm

#539 MGMT-2289 For image generation, only leader should upload base ISO
  cmd/main.go
  deploy/roles/default_role.yaml
Labels: approved, lgtm

#541 MGMT-2211 Move next step runner command to host package
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/nextsteprunnercmd.go
  internal/host/nextsteprunnercmd_test.go
  subsystem/cluster_test.go
  subsystem/day2_cluster_test.go
  subsystem/host_test.go
  subsystem/utils_test.go
Labels: approved, lgtm

#544 Revert "Publish images per versions"
  Jenkinsfile
Labels: approved, lgtm

#467 OCPBUGSM-18082 - Worker number should not be 1
  internal/cluster/transition_test.go
  internal/cluster/validator.go
  internal/common/common.go
  subsystem/cluster_test.go
Labels: approved, lgtm

#519 MGMT-1843 Publish onprem image
  Dockerfile.assisted-iso-create
  Dockerfile.assisted-service
  Jenkinsfile
  Makefile
Labels: approved, kind/dependency-change, lgtm

#551 MGMT-2037 Avoid dockerhub base images
  Dockerfile.assisted-service
  Dockerfile.assisted-service-build
  Dockerfile.assisted-service-onprem
  Dockerfile.test
  Makefile
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  deploy/postgres/postgres-deployment.yaml
  onprem-environment
Labels: approved, kind/dependency-change, lgtm

#549 MGMT-2420 Collect additional bootable information on disks
  models/disk.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#553 OCPBUGSM-18082 - Increase defaultWaitForClusterStateTimeout
  subsystem/cluster_test.go
  subsystem/utils_test.go
Labels: approved, lgtm

#550 MGMT-2448 Add installer image caching to host discovery
  internal/host/downloadinstallercmd.go
  internal/host/downloadinstallercmd_test.go
  internal/host/instructionmanager.go
  internal/host/instructionmanager_test.go
Labels: approved, lgtm

#448 Mgmt 2230 added authorization scopes (with read only admin)
  ADMINS
  client/installer/register_add_hosts_cluster_responses.go
  internal/identity/identity.go
  internal/identity/identity_test.go
  pkg/auth/auth_assisted_service_mock_test.go
  pkg/auth/auth_handler.go
  pkg/auth/auth_handler_test.go
  pkg/auth/auth_utils.go
  pkg/auth/authz_handler.go
  pkg/auth/authz_handler_test.go
  pkg/ocm/authorization.go
  pkg/ocm/client.go
  pkg/ocm/mock_authorization.go
  restapi/embedded_spec.go
  restapi/operations/installer/register_add_hosts_cluster_responses.go
  subsystem/authz_test.go
  subsystem/subsystem_suite_test.go
  swagger.yaml
  tools/deploy_assisted_installer_configmap.py
Labels: api-review, approved, lgtm

#522 MGMT-2313: Send an event when a host is chosen for bootstrap
  internal/host/host.go
  internal/host/host_test.go
Labels: approved, lgtm

#559 NO-ISSUE Fix installcfg logs with right format
  internal/installcfg/installcfg.go
Labels: approved, lgtm

#560 NO-ISSUE Using centos postgres except for UT
  Makefile
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  deploy/postgres/postgres-deployment.yaml
  onprem-environment
Labels: approved, lgtm

#558 OCPBUGSM-18082 - Fix install command failed test
  subsystem/cluster_test.go
Labels: approved, lgtm

#529 Ori/mgmt 2401 Support connectivity majority groups
  go.mod
  go.sum
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/mock_cluster_api.go
  internal/host/refresh_status_preprocessor.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/host/validator.go
  internal/network/connectivity_groups.go
  internal/network/connectivity_groups_test.go
  internal/network/machine_network_cidr.go
  models/cluster.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#543 MGMT-2069: make server return 409 code (conflict) when host tries to …
  client/installer/register_host_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  pkg/ocm/mock_authorization.go
  restapi/embedded_spec.go
  restapi/operations/installer/register_host_responses.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#555 NO-ISSUE Use the centos image from app-sre
  Dockerfile.assisted-service
  Dockerfile.assisted-service-onprem
Labels: approved, kind/dependency-change, lgtm

#554 makefile: added update-service rule
  Makefile
  README.md
Labels: approved, lgtm

#579 MGMT-2415 change id label name for HTTP metrics to clusterId
  internal/metrics/recorder.go
Labels: approved, lgtm

#567 OCPBUGSM-19280 adding api int to noproxy param of assited-installer
  internal/host/installcmd.go
  internal/host/installcmd_test.go
Labels: approved, lgtm

#566 MGMT-2069: fix conflict code returned by host registration to be an i…
  client/installer/register_host_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  restapi/embedded_spec.go
  restapi/operations/installer/register_host_responses.go
  swagger.yaml
Labels: api-review, approved, lgtm

#572 MGMT-2407 Run all jobs periodically at night
  Jenkinsfile
Labels: approved, lgtm

#563 MGMT-2307 Publish release images
  Jenkinsfile
  Makefile
Labels: approved, lgtm

#573 MGMT-2444 Update OCP release to OCP 4.6 RC.4
  Makefile
Labels: approved, lgtm

#580 NO-ISSUE increase CI timeout
  Jenkinsfile
Labels: approved, lgtm

#581 MGMT-2364 Return post_step_action enum in next step API
  internal/host/instructionmanager.go
  internal/host/instructionmanager_test.go
  models/steps.go
  restapi/embedded_spec.go
  subsystem/host_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#577 MGMT-2473 Enable command to return multiple steps
  internal/host/apivipconnectivitycheckcmd.go
  internal/host/apivipconnectivitycheckcmd_test.go
  internal/host/cmdcommon.go
  internal/host/connectivitycheckcmd.go
  internal/host/connectivitycheckcmd_test.go
  internal/host/dhcpallocatecmd.go
  internal/host/dhcpallocatecmd_test.go
  internal/host/downloadinstallercmd.go
  internal/host/downloadinstallercmd_test.go
  internal/host/freeaddressescmd.go
  internal/host/freeaddressescmd_test.go
  internal/host/installcmd.go
  internal/host/installcmd_test.go
  internal/host/instructionmanager.go
  internal/host/inventorycmd.go
  internal/host/inventorycmd_test.go
  internal/host/resetinstallationcmd.go
  internal/host/resetinstallationcmd_test.go
  internal/host/stopinstallation.go
  internal/host/stopinstallation_test.go
Labels: approved, lgtm

#547 MGMT-2237 - PostStepReply API will return BadRequest in case the requ…
  internal/bminventory/inventory.go
  subsystem/cluster_test.go
  subsystem/host_test.go
Labels: approved, lgtm

#447 MGMT-2036 - Agent APIs have User Identity filter
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validation_test.go
  pkg/auth/auth_handler.go
  pkg/auth/auth_handler_test.go
Labels: approved, lgtm

#583 MGMT-2480: Fixed flaky authz test
  pkg/auth/authz_handler_test.go
Labels: approved, lgtm

#585 MGMT-2488 We are automigrating db twice - remove automigrate from main
  cmd/main.go
Labels: approved, lgtm

#586 Update assisted-service-on-local.md
  docs/user-guide/assisted-service-on-local.md
Labels: approved, lgtm

#587 MGMT-2389 - Missing cluster_id in some logs
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#589 git Osher/mgmt 2416
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, lgtm

#591 MGMT-2480: change authz test server port
  pkg/auth/authz_handler_test.go
  pkg/log/logcontext_test.go
Labels: approved, lgtm

#597 MGMT-2295 Give the test cluster a unique name
  openshift/template-post-deploy-job.yaml
Labels: approved, lgtm

#576 MGMT-2431: Copy 'logs_sender' binary file to host.
  internal/host/common.go
  internal/host/stopinstallation.go
Labels: approved, lgtm

#603 MGMT-2625 Add HW info to assisted_installer_cluster_hosts metric
  internal/cluster/mock_cluster_api.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_netricsManager_api.go
  pkg/generator/mock_install_config.go
  pkg/leader/mock_leader_elector.go
  pkg/ocm/mock_authorization.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3wrapper.go
Labels: approved, lgtm

#604 MGMT-2635 Bugfix: GenerateClusterISO failing in subsystem tests
  Dockerfile.assisted-iso-create
Labels: approved, kind/dependency-change, lgtm

#605 MGMT-2586 - fixing updating hostname for day2 host, when there is ano…
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#537 OCPBUGSM-18248 wrong validation message when host has 4G RAM
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, lgtm

#600 MGMT-2480: Wait until server is ready
  pkg/auth/authz_handler_test.go
Labels: approved, lgtm

#607 OCPBUGSM-19585 Register disabled host
  internal/host/statemachine.go
  internal/host/transition_test.go
Labels: approved, lgtm

#598 MGMT-2463 - implement OCP Register day2 cluster
  cmd/main.go
  go.mod
  go.sum
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  models/cluster.go
  models/host.go
  pkg/k8sclient/k8sclient.go
  pkg/k8sclient/mock_k8sclient.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#593 MGMT-2472 Format bootable disks on Install command
  internal/host/installcmd.go
  internal/host/installcmd_test.go
Labels: approved, lgtm

#606 MGMT-2598: Added finalizing to cancel/reset transitions
  internal/cluster/statemachine.go
  internal/cluster/transition_test.go
  subsystem/cluster_test.go
Labels: approved, lgtm

#595 MGMT-2479 Cancellation stops only installer container
  internal/host/stopinstallation.go
Labels: approved, lgtm

#610 MGMT-2674 VIPs DHCP leases are not renewed in OCP
  go.mod
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
Labels: approved, lgtm

#608 OCPBUGSM-19651: sending event about cluster installation started
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/mock_cluster_api.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_netricsManager_api.go
  pkg/generator/mock_install_config.go
  pkg/k8sclient/mock_k8sclient.go
  pkg/leader/mock_leader_elector.go
  pkg/ocm/mock_authorization.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3wrapper.go
Labels: approved, lgtm

#592 MGMT-2227: Use running livecd when running on prem
  Dockerfile.assisted-service-onprem
  Makefile
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  docs/installer-live-iso.md
  pkg/s3wrapper/filesystem.go
  skipper.yaml
Labels: approved, kind/dependency-change, lgtm

#618 MGMT-2692: Fixed waiting for server in authz test
  pkg/auth/authz_handler_test.go
Labels: approved, lgtm

#619 MGMT-2444 - Update OCP release to ocp-release:4.6.1-x86_64
  Makefile
Labels: approved, lgtm

#564 NO-JIRA Bugfix: regenerate ignition from fcc
  config/onprem-iso-config.ign
Labels: approved, lgtm

#620 NO-ISSUE Fix README issues, Add Go Report Card, remove github workflows
  .github/workflows/image-push.yml
  .github/workflows/release.yml
  .github/workflows/unit-test.yml
  README.md
Labels: approved, lgtm

#569 MGMT-2466 Make the override columns text and add migrations
  cmd/main.go
  go.mod
  go.sum
  internal/common/common_unitest_db.go
  internal/migrations/20201019194303_change_overrides_to_text.go
  internal/migrations/20201019194303_change_overrides_to_text_test.go
  internal/migrations/migrations.go
  internal/migrations/migrations_suite_test.go
  internal/migrations/migrations_test.go
  models/cluster.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#621 MGMT-2704 - adjust role deployment for assisted-service day2 on ocp
  cmd/main.go
  deploy/roles/ocp_role.yaml
  tools/deploy_role.py
Labels: approved, lgtm

#615 OCPBUGSM-19500 - enforce worker count with auto-assign
  internal/cluster/cluster_test.go
  internal/cluster/transition_test.go
  internal/cluster/validator.go
Labels: approved, lgtm

#622 NO-ISSUE fixing logscmd test db issue
  internal/host/logscmd_test.go
Labels: approved, lgtm

#623 MGMT-2320: added ADMIN_USERS env to openshift template.yaml
  openshift/template.yaml
Labels: approved, lgtm

#602 MGMT-2462 AI on OCP cluster
  Makefile
  deploy/postgres/postgres-deployment-ephemeral.yaml
  tools/deploy_assisted_installer.py
  tools/deploy_postgres.py
  tools/deployment_options.py
  tools/utils.py
Labels: approved, lgtm

#624 MGMT-2320: added ADMIN_USERS definition env to openshift template.yaml
  openshift/template.yaml
Labels: approved, lgtm

#625 MGMT-2612 Fixed 'base domain undefined' validation message
  internal/cluster/transition_test.go
  internal/cluster/validator.go
Labels: approved, lgtm

#402 MGMT-1992 - User guide added for iPXE use case
  docs/user-guide/deploy-on-bare-metal.md
  docs/user-guide/img/ai_all_nodes.png
  docs/user-guide/img/ai_node_appear.gif
  docs/user-guide/img/ai_vips.png
  docs/user-guide/img/boot_from_ipxe.gif
  docs/user-guide/img/dhcp_ipxe_image.png
  docs/user-guide/img/discovery_iso_generated.png
  docs/user-guide/img/download_disc_iso_first.png
  docs/user-guide/img/entry_base_domain.png
  docs/user-guide/img/entry_ssh_download_discovery.png
  docs/user-guide/img/entry_ssh_pub_key.png
  docs/user-guide/img/iPXE_boot.png
  docs/user-guide/img/ipxe_boot.png
  docs/user-guide/img/ipxe_reached_booting.png
  docs/user-guide/img/new_cluster.png
  docs/user-guide/img/node_on_assisted.png
  docs/user-guide/img/vm_base_OS.png
  docs/user-guide/img/vm_boot_iPXE_first.png
  docs/user-guide/img/vm_mem.png
  docs/user-guide/img/vm_storage.png
  site/ClusterStatus.dot
  site/ClusterStatus.png
  site/HostStatus.dot
  site/HostStatus.png
  site/index.html
  site/search/search_index.json
  site/sitemap.xml
  site/sitemap.xml.gz
  site/user-guide/deploy-on-bare-metal/index.html
  site/user-guide/img/ai_all_nodes.png
  site/user-guide/img/ai_node_appear.gif
  site/user-guide/img/ai_vips.png
  site/user-guide/img/boot_from_ipxe.gif
  site/user-guide/img/dhcp_ipxe_image.png
  site/user-guide/img/discovery_iso_generated.png
  site/user-guide/img/download_disc_iso_first.png
  site/user-guide/img/entry_base_domain.png
  site/user-guide/img/entry_ssh_download_discovery.png
  site/user-guide/img/entry_ssh_pub_key.png
  site/user-guide/img/iPXE_boot.png
  site/user-guide/img/ipxe_boot.png
  site/user-guide/img/ipxe_reached_booting.png
  site/user-guide/img/new_cluster.png
  site/user-guide/img/node_on_assisted.png
  site/user-guide/img/vm_base_OS.png
  site/user-guide/img/vm_boot_iPXE_first.png
  site/user-guide/img/vm_mem.png
  site/user-guide/img/vm_storage.png
Labels: approved, lgtm

#284 [BZ1872302] Exposing grafana and prometheus as NodePort instead of clusterIP on Minikube
  deploy/monitoring/grafana/assisted-installer-k8s-grafana.yaml
  deploy/monitoring/prometheus/assisted-installer-k8s-prometheus-svc.yaml
Labels: approved, lgtm

#611 MGMT-2659 DHCP server changes the VIPs addresses after installation has started - Swagger changes
  models/dhcp_allocation_request.go
  models/dhcp_allocation_response.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#630 MGMT-2734 - fixing error with go get command
  docs/user-guide/deploy-on-bare-metal.md
  docs/user-guide/img/manual_ipxe_boot.png
  site/index.html
  site/installer-live-iso/index.html
  site/search/search_index.json
  site/sitemap.xml
  site/sitemap.xml.gz
  site/user-guide/assisted-service-on-local/index.html
  site/user-guide/deploy-on-bare-metal/index.html
  site/user-guide/img/manual_ipxe_boot.png
Labels: approved, lgtm
