Repository openshift/assisted-service, pull requests merged in 2021-03, with the labels that each got.

#1148 MGMT-3854 log info API
  client/installer/installer_client.go
  client/installer/update_logs_progress_parameters.go
  client/installer/update_logs_progress_responses.go
  internal/bminventory/inventory.go
  mocks/mock_assisted_service.go
  models/cluster.go
  models/host.go
  models/logs_state.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/update_logs_progress.go
  restapi/operations/installer/update_logs_progress_parameters.go
  restapi/operations/installer/update_logs_progress_responses.go
  restapi/operations/installer/update_logs_progress_urlbuilder.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1160 MGMT-4281, Bump OCP versions
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#1150 MGMT-3976: Embed ramdisk placeholder in template
  internal/isoeditor/rhcos.go
  internal/isoeditor/rhcos_test.go
Labels: approved, lgtm

#1116 NO-ISSUE add skipper mac file
  skipper-mac.yaml
Labels: approved, lgtm

#1152 MGMT-3865 Block VIP DHCP allocation with IPv6 machine network
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
  subsystem/ipv6_test.go
Labels: approved, lgtm

#1188 NO-ISSUE Add docker ignore
  .dockerignore
Labels: approved, lgtm

#1185 MGMT-4347 Fix pull secret format to dockerconfigjson
  internal/controller/controllers/common.go
  internal/controller/controllers/controllers_suite_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1171 MGMT-3982 Store initrd metadata in system area
  internal/isoeditor/rhcos.go
  internal/isoeditor/rhcos_test.go
  internal/isoutil/isoutil.go
  pkg/s3wrapper/client_test.go
  pkg/s3wrapper/filesystem_test.go
Labels: approved, lgtm

#1184 MGMT-3854 API convert log info on cluster to ref
  models/cluster.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1190 MGMT-4343 Document how to set static network config with curl
  docs/user-guide/restful-api-guide.md
  docs/user-guide/user-guide.md
Labels: approved, lgtm

#1186 MGMT-4052 - Add disk by-id info to inventory - Adding by-id field
  models/disk.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1193 MGMT-4361 Postgres init container should not hardcode namespace
  config/default/postgres-patch-init-container.yaml
Labels: approved, lgtm

#1195 OCPBUGSM-25000 Unclear error message when saving wrong service CIDR
  internal/bminventory/inventory.go
  internal/network/cidr_validations.go
Labels: approved, lgtm

#1194 MGMT-4345 Removed setOperatorStatus from OCS validations code
  internal/operators/ocs/validations.go
Labels: approved, lgtm

#1199 MGMT-3854 log progress new API
  client/installer/installer_client.go
  client/installer/update_cluster_logs_progress_parameters.go
  client/installer/update_cluster_logs_progress_responses.go
  client/installer/update_host_logs_progress_parameters.go
  client/installer/update_host_logs_progress_responses.go
  client/installer/update_logs_progress_parameters.go
  client/installer/update_logs_progress_responses.go
  internal/bminventory/inventory.go
  mocks/mock_assisted_service.go
  models/logs_progress_params.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/update_cluster_logs_progress.go
  restapi/operations/installer/update_cluster_logs_progress_parameters.go
  restapi/operations/installer/update_cluster_logs_progress_responses.go
  restapi/operations/installer/update_cluster_logs_progress_urlbuilder.go
  restapi/operations/installer/update_host_logs_progress.go
  restapi/operations/installer/update_host_logs_progress_parameters.go
  restapi/operations/installer/update_host_logs_progress_responses.go
  restapi/operations/installer/update_host_logs_progress_urlbuilder.go
  restapi/operations/installer/update_logs_progress.go
  restapi/operations/installer/update_logs_progress_parameters.go
  restapi/operations/installer/update_logs_progress_responses.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1200 NO-ISSUE Organize common db functions
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/registrar.go
  internal/cluster/transition_test.go
  internal/common/common_unitest_db.go
  internal/common/db.go
  internal/events/event.go
  internal/events/event_test.go
  internal/events/mock_event.go
  internal/host/host_test.go
  internal/host/monitor_test.go
  internal/host/transition_test.go
  internal/migrations/migrations_test.go
  internal/network/manifests_generator_test.go
Labels: approved, lgtm

#1178 MGMT-4095 - update minimal iso flow to work with nmstate static netwo…
  cmd/main.go
  go.mod
  go.sum
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/constants/scripts.go
  internal/isoeditor/factory.go
  internal/isoeditor/rhcos.go
  internal/isoeditor/rhcos_test.go
  pkg/s3wrapper/client_test.go
  pkg/s3wrapper/filesystem_test.go
  pkg/staticnetworkconfig/generator.go
  pkg/staticnetworkconfig/mock_generator.go
Labels: approved, lgtm

#1172 MGMT-4315 Api changes and code generation for additional state for checking disk performance
  models/disk_info.go
  models/disk_speed.go
  models/disk_speed_check_request.go
  models/disk_speed_check_response.go
  models/host.go
  models/host_requirements_role.go
  models/host_validation_id.go
  models/step_type.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1204 MGMT-4372: Comment events/metrics generation on host validations changes.
  internal/host/host.go
  subsystem/metrics_test.go
Labels: approved, lgtm

#1183 MGMT-4259 Add Approved field to host/agent
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/common/db.go
  internal/controller/api/v1alpha1/agent_types.go
  internal/controller/config/crd/bases/adi.io.my.domain_agents.yaml
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/crd_utils.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1205 MGMT-3371 Documentation on adding support for a new OLM operator
  docs/README.md
  docs/dev/olm-operator-plugins.md
Labels: approved, lgtm

#1210 NO-ISSUE Delete assisted-service pod before deploy-test
  Makefile
Labels: approved, lgtm

#1207 NO-ISSUE Performance grafana dashboard
  dashboards/grafana-dashboard-assisted-resource-dashboard.yaml
Labels: approved, lgtm

#1211 NO-ISSUE update hive version to master
  cmd/main.go
  go.mod
  go.sum
  internal/controller/config/crd/bases/hive.openshift.io_clusterdeployments.yaml
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/controllers_suite_test.go
  internal/controller/controllers/installenv_controller.go
  subsystem/kubeapi_test.go
  subsystem/subsystem_suite_test.go
Labels: approved, lgtm

#1218 MGMT-4406 change OCP 4.6 version from 4.6.18 to 4.6.16
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#1212 OCPBUGSM-25682 - set image type to full-iso during cluster ISO genera…
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  restapi/embedded_spec.go
  subsystem/image_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1168 MGMT-4170 - Create assisted service python client as a library
  Dockerfile.assisted-service-build
  Jenkinsfile
  Makefile
  hack/generate.sh
  skipper.yaml
  tools/client_package_initializer.py
Labels: api-review, approved, kind/dependency-change, lgtm

#1196 NO-ISSUE - Support make build without the skipper on MAC
  hack/get_ocp_versions_for_testing.sh
Labels: approved, lgtm

#1197 MGMT-4065 supported-operators handler
  client/operators/list_operator_properties_parameters.go
  client/operators/list_operator_properties_responses.go
  client/operators/list_supported_operators_responses.go
  client/operators/operators_client.go
  cmd/main.go
  internal/operators/api/api.go
  internal/operators/builder.go
  internal/operators/handler.go
  internal/operators/lso/ls_operator.go
  internal/operators/manager.go
  internal/operators/manager_test.go
  internal/operators/mock_operators_api.go
  internal/operators/ocs/ocs_operator.go
  models/operator_properties.go
  models/operator_property.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/operators/list_operator_properties.go
  restapi/operations/operators/list_operator_properties_parameters.go
  restapi/operations/operators/list_operator_properties_responses.go
  restapi/operations/operators/list_operator_properties_urlbuilder.go
  restapi/operations/operators/list_supported_operators_responses.go
  subsystem/operators_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1206 MGMT-4339 Add indication for discovery image generation
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/db.go
Labels: approved, lgtm

#1182 Dns manifests for single node
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/mock_cluster_api.go
  internal/cluster/transition.go
  internal/manifests/manifests.go
  internal/network/machine_network_cidr_test.go
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
  internal/network/mock_manifests_generator.go
Labels: approved, lgtm

#1221 NO-ISSUE the build failed on MAC by a weird networking behavior
  skipper-mac.yaml
Labels: approved, lgtm

#1201 MGMT-4274 Allow for additional authenticator types
  Makefile
  cmd/main.go
  deploy/assisted-service-configmap.yaml
  internal/assistedserviceiso/assistedserviceiso_api.go
  internal/assistedserviceiso/assistedserviceiso_api_test.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/validations/mock_validations.go
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
  openshift/template.yaml
  pkg/auth/authenticator.go
  pkg/auth/authenticator_test.go
  pkg/auth/authz_handler.go
  pkg/auth/authz_handler_test.go
  pkg/auth/jwk.go
  pkg/auth/none_authenticator.go
  pkg/auth/rhsso_authenticator.go
  pkg/auth/rhsso_authenticator_test.go
  pkg/ocm/utils.go
  skipper.yaml
  subsystem/ams_subscriptions_test.go
  subsystem/authz_test.go
  subsystem/host_test.go
  subsystem/subsystem_suite_test.go
  tools/deploy_assisted_installer_configmap.py
Labels: approved, lgtm

#1220 NO-ISSUE Remove unneeded fields from Agent CRD
  internal/controller/api/v1alpha1/agent_types.go
  internal/controller/api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/config/crd/bases/adi.io.my.domain_agents.yaml
Labels: approved, lgtm

#1208 MGMT-4165 handle minimal iso templates update
  cmd/main.go
  pkg/s3wrapper/client.go
  pkg/s3wrapper/client_test.go
  pkg/s3wrapper/filesystem.go
  pkg/s3wrapper/filesystem_test.go
  pkg/s3wrapper/mock_s3wrapper.go
  pkg/s3wrapper/util.go
  pkg/s3wrapper/util_test.go
Labels: approved, lgtm

#1217 MGMT-4348 move cluster-deployment crd from internal
  hack/crds/hive.openshift.io_clusterdeployments.yaml
  internal/controller/config/crd/kustomization.yaml
  tools/deploy_crd.py
Labels: approved, lgtm

#1224 Hotfix - MGMT-4170 - Add --skip-existing flag
  Makefile
  tools/client_package_initializer.py
Labels: approved, lgtm

#1226 MGMT-4274 Make AUTH_TYPE optional
  openshift/template.yaml
Labels: approved, lgtm

#1151 MGMT-3979: Embed ignition and ramdisk into cluster iso
  internal/isoeditor/rhcos.go
  internal/isoeditor/rhcos_test.go
  internal/isoutil/isoutil.go
  internal/isoutil/mock_isoutil.go
Labels: approved, lgtm

#1176 MGMT-4079 Deploy cnv
  internal/cluster/cluster_test.go
  internal/cluster/statemachine.go
  internal/cluster/transition_test.go
  internal/cluster/validation_id.go
  internal/hardware/validator.go
  internal/host/host_test.go
  internal/host/hostutil/test_utils.go
  internal/host/monitor_test.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/operators/builder.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/cnv/utils.go
  internal/operators/manager_test.go
  models/cluster_validation_id.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  subsystem/operators_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1233 MGMT-4424 - vaidate the interface name parameter format in case of st…
  pkg/staticnetworkconfig/generator.go
  pkg/staticnetworkconfig/generator_test.go
Labels: approved, lgtm

#1121 MGMT-4123 Allow the user to provide the machine cider of the cluster API IP
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/common.go
  internal/installcfg/installcfg.go
  internal/installcfg/installcfg_test.go
  internal/network/machine_network_cidr.go
  internal/network/machine_network_cidr_test.go
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
Labels: approved, lgtm

#1225 MGMT-4049 Add id information to the inventory disk - The id field identify the disk to the UI instead of computing it from the by-path and by-id field
  models/disk.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1180 Log info implementation
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/common.go
  internal/cluster/mock_cluster_api.go
  internal/cluster/statemachine.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostutil/update_host.go
  internal/host/mock_host_api.go
  internal/host/monitor.go
  internal/host/statemachine.go
  internal/host/transition.go
  subsystem/cluster_test.go
  subsystem/utils_test.go
Labels: api-review, approved, lgtm

#1229 MGMT-4079 CNV update
  docs/dev/olm-operator-plugins.md
  internal/operators/builder.go
Labels: approved, lgtm

#1238 MGMT-4415 Remove cluster_ID from validations metrics
  internal/host/host.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_metrics_manager_api.go
  subsystem/metrics_test.go
Labels: approved, lgtm

#1170 MGMT-3998 Get installEnv params when creating or updating cluster
  cmd/main.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/common.go
  internal/controller/controllers/crd_events_handler.go
  internal/controller/controllers/installenv_controller.go
  internal/controller/controllers/mock_crd_events_handler.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1244 OCPBUGSM-1934722 Included the size unit in validation message
  internal/cluster/transition_test.go
  internal/operators/ocs/validations.go
Labels: approved, lgtm

#1247 MGMT-4415 Remove cluster_ID from validations metrics (#1238)
  internal/host/host.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_metrics_manager_api.go
  subsystem/metrics_test.go
Labels: approved, lgtm

#1249 MGMT-4414: Adding DB update for each change in validations status.
  internal/host/host.go
  internal/host/host_test.go
  internal/host/refresh_status_preprocessor.go
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, lgtm

#1219 Update OLM plugin dev documentation; simplify monitored operators init
  docs/dev/olm-operator-plugins.md
  internal/operators/api/api.go
  internal/operators/api/mock_operator_api.go
  internal/operators/builder.go
  internal/operators/builder_test.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/lso/ls_operator.go
  internal/operators/ocs/ocs_operator.go
Labels: approved, lgtm

#1234 MGMT-4414: Adding DB update for each change in validations status.
  internal/host/host.go
  internal/host/host_test.go
  internal/host/refresh_status_preprocessor.go
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, lgtm

#1243 OCPBUGSM-1934562 Added the validation to consider OCS disk of size >=5 GB
  internal/cluster/cluster_test.go
  internal/cluster/transition_test.go
  internal/operators/ocs/consts.go
  internal/operators/ocs/validations.go
Labels: approved, lgtm

#1235 MGMT-4385 ClusterDeployment controller start install only if hosts are approved
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1209 MGMT-3697 Fix typo in the role verb /patc/patch
  internal/controller/config/rbac/kube_api_roles.yaml
Labels: approved, lgtm

#1246 MGMT-4447 SNO - if machine cidr was not set, route53 fails
  internal/bminventory/inventory.go
  internal/network/machine_network_cidr.go
  internal/network/manifests_generator.go
Labels: approved, lgtm

#1251 MGMT-4365 validation for custom ramdisk size
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/isoeditor/rhcos.go
  internal/isoeditor/rhcos_test.go
Labels: approved, lgtm

#1245 MGMT-4430 ListOfClusterOperators and ReportMonitoredOperatorStatus operations
  client/operators/report_monitored_operator_status_responses.go
  cmd/main.go
  internal/operators/handler.go
  internal/operators/handler/handler.go
  internal/operators/handler/handler_suite_test.go
  internal/operators/handler/handler_test.go
  restapi/embedded_spec.go
  restapi/operations/operators/report_monitored_operator_status_responses.go
  subsystem/operators_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1253 MGMT-4468 update cluster from installenv
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/installenv_controller.go
  internal/controller/controllers/installenv_controller_test.go
Labels: approved, lgtm

#1255 NO-ISSUE set MinWorkersNeededForInstallation to 2
  internal/cluster/transition.go
Labels: approved, lgtm

#1259 OCPBUGSM-1936338 Fixed the total disks to be used while generating OCS manifests.
  internal/operators/ocs/ocs_operator.go
Labels: approved, lgtm

#1261 OCPBUGSM-1936338 Fixed the total disks to be used while generating OCS manifests.
  internal/operators/ocs/ocs_operator.go
Labels: approved, lgtm

#1260 MGMT-4366 compress custom ramdisk archive
  internal/isoeditor/rhcos.go
  internal/isoeditor/rhcos_test.go
Labels: approved, lgtm

#1257 MGMT-4430 Fix for flaky subsystem tests
  subsystem/operators_test.go
Labels: approved, lgtm

#1258 OCPBUGSM-25057 added image type to events
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#1272 MGMT-4423 Add Host inventory to Agent Status
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1266 MGMT-4204 Rename prefix_name to subscription_name
  models/monitored_operator.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1275 MGMT-4483 Add InstallationDiskPath to Agent CRD
  internal/controller/api/v1alpha1/agent_types.go
  internal/controller/config/crd/bases/adi.io.my.domain_agents.yaml
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1264 MGMT-4188 Use manifest API to manage operator ignition files
  cmd/main.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/transition_test.go
  internal/host/transition_test.go
  internal/ignition/ignition.go
  internal/network/manifests_generator.go
  internal/operators/api/api.go
  internal/operators/api/mock_operator_api.go
  internal/operators/builder.go
  internal/operators/builder_test.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/cnv/cnv_suite_test.go
  internal/operators/cnv/manifest.go
  internal/operators/cnv/manifests_test.go
  internal/operators/lso/ls_operator.go
  internal/operators/lso/lso_suite_test.go
  internal/operators/lso/manifest.go
  internal/operators/lso/manifests_test.go
  internal/operators/manager.go
  internal/operators/manager_test.go
  internal/operators/mock_operators_api.go
  internal/operators/ocs/manifest.go
  internal/operators/ocs/manifests_test.go
  internal/operators/ocs/ocs_operator.go
  internal/operators/ocs/ocs_suite_test.go
  subsystem/cluster_test.go
Labels: approved, lgtm

#1228 MGMT-4275 Add local JWT authentication
  pkg/auth/auth_handler_test_utils.go
  pkg/auth/auth_suite_test.go
  pkg/auth/authenticator.go
  pkg/auth/authenticator_test.go
  pkg/auth/local_authenticator.go
  pkg/auth/local_authenticator_test.go
  pkg/auth/none_authenticator.go
  pkg/auth/rhsso_authenticator.go
Labels: approved, lgtm

#1230 MGMT-4428 Create Dockerfile to build bundle image in prow
  Dockerfile.assisted-service-build
  Dockerfile.bundle
  Makefile
  docs/operator.md
Labels: approved, kind/dependency-change, lgtm

#1273 MGMT-4442: Added cluster name to OCM subscription.
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  pkg/ocm/accounts_mgmt.go
  pkg/ocm/mock_accounts_mgmt.go
  subsystem/ams_subscriptions_test.go
  subsystem/wiremock_stubs.go
Labels: approved, lgtm

#1281 NO-ISSUE: remove bundle from publish
  Makefile
Labels: approved, lgtm

#1285 MGMT-4428 Adds operator-bundle to build-all and publish
  Makefile
Labels: approved, lgtm

#1167 MGMT-4066 Add enabled operator CPU and memory requirements to host validation
  internal/cluster/cluster.go
  internal/cluster/refresh_status_preprocessor.go
  internal/cluster/validator.go
  internal/hardware/validator_test.go
  internal/host/host_test.go
  internal/host/hostutil/test_utils.go
  internal/host/monitor_test.go
  internal/host/refresh_status_preprocessor.go
  internal/host/transition_test.go
  internal/host/validator.go
  internal/operators/api/api.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/lso/ls_operator.go
  internal/operators/manager.go
  internal/operators/mock_operators_api.go
  internal/operators/ocs/ocs_operator.go
  subsystem/cluster_test.go
  subsystem/host_test.go
  subsystem/ipv6_test.go
  subsystem/metrics_test.go
Labels: api-review, approved, lgtm

#1267 MGMT-4460 - update REST API to support new format for static network …
  internal/bminventory/inventory_test.go
  models/host_static_network_config.go
  models/image_create_params.go
  models/mac_interface_map.go
  pkg/staticnetworkconfig/generator.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1162 MGMT-4219: update cluster: skip cidr validations
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/validator.go
  internal/network/machine_network_cidr.go
  internal/network/machine_network_cidr_test.go
  subsystem/cluster_test.go
  subsystem/metrics_test.go
  subsystem/utils_test.go
Labels: approved, lgtm

#1269 MGMT-4471 Generate an agent auth token for local auth
  internal/bminventory/inventory.go
  internal/cluster/auth.go
  internal/cluster/auth_test.go
  pkg/auth/local_authenticator.go
Labels: approved, lgtm

#1274 MGMT-4461 Use mac-interface mapping alongside the nmstate yamls
  internal/constants/scripts.go
Labels: approved, lgtm

#1291 MGMT-4518 - add mac address format validation for static network conf…
  models/mac_interface_map.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1252 NO-ISSUE: Document the need for an extra PVC
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#1283 MGMT-4204 Return subscription data in monitor operators
  internal/bminventory/inventory_test.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/cnv/manifest.go
  internal/operators/lso/ls_operator.go
  internal/operators/lso/manifest.go
  internal/operators/manager.go
  internal/operators/ocs/manifest.go
  internal/operators/ocs/ocs_operator.go
Labels: approved, lgtm

#1271 MGMT-4450 Operator bundle should not include experimental ISOs
  Makefile
Labels: approved, lgtm

#1293 MGMT-4448: Updating host validations metrics test.
  subsystem/metrics_test.go
Labels: approved, lgtm

#1263 MGMT-4274 Remove ENABLE_AUTH
  cmd/main.go
  openshift/template.yaml
  pkg/auth/authenticator.go
  pkg/auth/authenticator_test.go
  pkg/auth/authz_handler.go
  pkg/auth/authz_handler_test.go
  skipper-mac.yaml
  skipper.yaml
Labels: approved, lgtm

#1287 OCPBUGSM-25828 Use ubi for assisted-service init container
  config/default/assisted-service-patch-init-containers.yaml
Labels: approved, lgtm

#1277 MGMT-4382 Sets minimal-iso as the default for operator and updates docs
  config/default/assisted-service-patch-iso-image-type.yaml
  config/default/kustomization.yaml
  docs/operator.md
Labels: approved, lgtm

#1268 NO-ISSUE Add customizations doc
  docs/user-guide/install-customization.md
Labels: approved, lgtm

#1290 NO-ISSUE Revert PR#1285 adding operator-bundle to build-all and publish
  Makefile
Labels: approved, lgtm

#1298 MGMT-4502 - Improve unit test performance by putting DB data in RAM rather than disk
  Makefile
Labels: approved, lgtm

#1289 MGMT-4413, Bump OCP versions
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#1284 MGMT-4501 - Remove unnecessary steps from Dockerfile
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, lgtm

#1304 NO-ISSUE: use swagger-codegen-cli from quay.io instead of docker hub
  hack/generate.sh
Labels: approved, lgtm

#1256 MGMT-3811 KubeAPI Minimal ISO support
  cmd/main.go
  internal/controller/controllers/installenv_controller.go
  internal/controller/controllers/installenv_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1305 OCPBUGSM-25786: Fixed pull secret validation message
  internal/bminventory/inventory.go
Labels: approved, lgtm

#1296 NOISSUE: Move tests for ocs into ocs package
  internal/cluster/cluster_test.go
  internal/cluster/common.go
  internal/cluster/refresh_status_preprocessor.go
  internal/cluster/registrar.go
  internal/cluster/statemachine.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/cluster/validation_id.go
  internal/cluster/validator.go
  internal/operators/ocs/manifests_test.go
  internal/operators/ocs/ocs_suite_test.go
  internal/operators/ocs/validation_test.go
Labels: approved, lgtm

#1299 NO-ISSUE - Remove erezalster from OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm

#1307 MGMT-3109 increase timeout for cluster logs when logs requested
  internal/cluster/transition.go
Labels: approved, lgtm

#1250 MGMT-3550 Add flag to disable IPv6
  Makefile
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  deploy/assisted-service-configmap.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  onprem-environment
  openshift/template.yaml
  subsystem/ipv6_test.go
  tools/deploy_assisted_installer_configmap.py
  tools/update_bm_cm.py
Labels: approved, lgtm

#1278 MGMT-4490 Cluster-dependent host requirements API definition
  client/installer/get_cluster_host_requirements_parameters.go
  client/installer/get_cluster_host_requirements_responses.go
  client/installer/installer_client.go
  internal/bminventory/inventory.go
  mocks/mock_assisted_service.go
  models/cluster_host_requirements.go
  models/cluster_host_requirements_details.go
  models/cluster_host_requirements_list.go
  models/operator_host_requirements.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/get_cluster_host_requirements.go
  restapi/operations/installer/get_cluster_host_requirements_parameters.go
  restapi/operations/installer/get_cluster_host_requirements_responses.go
  restapi/operations/installer/get_cluster_host_requirements_urlbuilder.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1310 NO-ISSUE - attempt to logout from problematic registries before running CI
  Jenkinsfile
Labels: approved, lgtm

#1276 MGMT-4205 Cluster completes on monitored operators status
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/mock_cluster_api.go
  internal/cluster/statemachine.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/constants/files.go
  internal/host/hostcommands/instruction_manager.go
  internal/host/transition_test.go
  internal/operators/builder.go
  internal/operators/builder_test.go
  internal/operators/manager_test.go
  internal/operators/ocs/validation_test.go
  pkg/ocm/client.go
  subsystem/ams_subscriptions_test.go
  subsystem/cluster_test.go
  subsystem/ipv6_test.go
  subsystem/operators_test.go
Labels: approved, lgtm

#1311 OCPBUGSM-26398 Fix OCS and CNV manifests indentation issue
  go.mod
  internal/operators/cnv/manifest.go
  internal/operators/cnv/manifests_test.go
  internal/operators/lso/manifests_test.go
  internal/operators/manager_test.go
  internal/operators/ocs/manifest.go
  internal/operators/ocs/manifests_test.go
Labels: approved, lgtm

#1297 Moving conversion helpers to separate package
  internal/hardware/validator.go
  internal/hardware/validator_test.go
  internal/host/host_test.go
  internal/host/hostutil/test_utils.go
  internal/host/transition_test.go
  internal/host/validator.go
  internal/operators/cnv/cnv_operator.go
  pkg/conversions/conversions.go
Labels: approved, lgtm

#1306 NO-ISSUE: AUTH_TYPE missing in onprem and liveiso configurations
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  onprem-environment
Labels: approved, lgtm

#1301 MGMT-4079 Check whether inventory available
  internal/operators/cnv/cnv_operator.go
Labels: approved, lgtm

#1302 MGMT-4513: Don't do anything if we update host with unchanged info.
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#1317 NO-ISSUE - Operator SDK should have a pinned version to make sure the environment is consistent across dev machines
  Dockerfile.assisted-service-build
Labels: approved, kind/dependency-change, lgtm

#1312 NO-ISSUE Download specific version of operator-sdk, turn on publish
  Dockerfile.bundle
  Makefile
Labels: approved, kind/dependency-change, lgtm

#1295 MGMT-4446 Verify CPU virtualization flag for CNV operator
  internal/hardware/validator.go
  internal/host/hostutil/test_utils.go
  internal/host/transition_test.go
  internal/operators/cnv/cnv_operator.go
Labels: approved, lgtm

#1323 OCPBUGSM-26476 Set portable to false for StorageCluster CR
  internal/operators/ocs/manifest.go
Labels: approved, lgtm

#1315 MGMT-4531 change ram_mib to ram_gib in cluster-host-requirements-details
  models/cluster_host_requirements_details.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1326 NO-ISSUE Add icon, additional metadata and annotations to operator CSV
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm

#1322 MGMT-4480 Get must-gather image from release
  internal/host/hostcommands/container_image_availability_cmd.go
  internal/host/hostcommands/container_image_availability_cmd_test.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/oc/mock_release.go
  internal/oc/release.go
  internal/oc/release_test.go
Labels: approved, lgtm

#1321 NO-ISSUE Update ocp-metal-ui proxy-pass URI with service route URI in operator
  config/default/kustomization.yaml
  config/default/ui-patch-init-containers.yaml
Labels: approved, lgtm

#1325 MGMT-4517 Update static network config in RESTful API user guide
  docs/user-guide/restful-api-guide.md
Labels: approved, lgtm

#1237 MGMT-4420 Make dnsmasq manifest for sno optional by os env
  Makefile
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  onprem-environment
  openshift/template.yaml
  tools/deploy_assisted_installer_configmap.py
Labels: approved, lgtm

#1242 MGMT-4210 Refactor ignition code
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/test_configuration.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/ignition/mock_ignition.go
Labels: approved, lgtm

#1270 MGMT-4312 Remove scality from operator deployment
  config/assisted-service/kustomization.yaml
  config/assisted-service/scality.yaml
  config/default/assisted-service-patch-deploy-target.yaml
  config/default/assisted-service-patch-volume-bucket-filesystem.yaml
  config/default/kustomization.yaml
  tools/deploy_assisted_installer.py
Labels: approved, kind/dependency-change, lgtm

#1303 MGMT-4234 Update ClusterDeployment CR MetaData
  go.mod
  internal/bminventory/inventory.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/crd_utils.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1327 MGMT-4205 Add degraded cluster status info
  internal/bminventory/inventory_test.go
  internal/cluster/common.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  subsystem/ams_subscriptions_test.go
  subsystem/cluster_test.go
  subsystem/operators_test.go
Labels: approved, lgtm

#1333 NO-ISSUE Agent Reconcile should not update if installation disk is empty
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, lgtm

#1191 MGMT-4217: Run subsystem test for kube-api after rest-api tests
  Makefile
  tools/deploy_assisted_installer.py
Labels: approved, lgtm

#1335 MGMT-4628 InstallEnv ignitionConfigOverride should be optional
  internal/controller/api/v1alpha1/installenv_types.go
  internal/controller/config/crd/bases/adi.io.my.domain_installenvs.yaml
Labels: approved, lgtm

#1342 NO-ISSUE Fix Secret create role
  internal/controller/config/rbac/role.yaml
  internal/controller/controllers/clusterdeployments_controller.go
Labels: approved, lgtm

#1345 NO-ISSUE Agent Reconcile need to create empty array for inventory
  internal/controller/controllers/agent_controller.go
Labels: approved, lgtm

#1337 MGMT-4205 Wait for OLM operators to finish cluster installation
  internal/cluster/transition.go
  internal/cluster/transition_test.go
Labels: approved, lgtm

#1248 MGMT-4300 Deregister inactive cluster
  cmd/main.go
  internal/bminventory/inventory.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/mock_cluster_api.go
  internal/garbagecollector/garbageCollector.go
  internal/garbagecollector/mock_garbageCollector.go
  internal/host/host.go
  openshift/template.yaml
Labels: approved, lgtm

#1352 NO-ISSUE Add retry to update agent in kube-api subsystem test
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1356 NO-ISSUE Add flaper87 to OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, lgtm

#1346 MGMT-4558 adding joined state for workers and bootstrap
  internal/host/host.go
Labels: approved, lgtm

#1351 NO-ISSUE: Fix typo in the documentation
  docs/operator.md
Labels: approved, lgtm

#1331 No issue enable kube api for ci
  Makefile
  hack/generate.sh
  internal/controller/config/crd/resources.yaml
  skipper.yaml
  tools/utils.py
Labels: approved, lgtm

#1344 NO-ISSUE Update create manifests example
  docs/user-guide/install-customization.md
Labels: api-review, approved, lgtm

#1308 MGMT-4583: Refactor ocs code
  internal/operators/manager_test.go
  internal/operators/ocs/consts.go
  internal/operators/ocs/manifest.go
  internal/operators/ocs/mock_validations.go
  internal/operators/ocs/ocs_operator.go
  internal/operators/ocs/validation_test.go
  internal/operators/ocs/validations.go
Labels: approved, lgtm

#1328 MGMT-4576 Check manifests content on creation
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
  models/create_manifest_params.go
  restapi/embedded_spec.go
  subsystem/manifests_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1350 MGMT-4644 Enable IPv6 support by default
  Makefile
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  internal/bminventory/inventory.go
  onprem-environment
  openshift/template.yaml
  tools/deploy_assisted_installer_configmap.py
Labels: approved, lgtm

#1362 NO-ISSUE: Add retries to Agent Update in kube-api
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1338 MGMT-4386: Use latest available rhcos for onprem
  Makefile
Labels: approved, lgtm

#1339 MGMT-4627 Match version key to image repository
  internal/versions/versions.go
  internal/versions/versions_test.go
Labels: approved, lgtm

#1349 change single-node ocp release
  Makefile
  hack/get_ocp_versions_for_testing.sh
  tools/handle_ocp_versions.py
Labels: approved, lgtm

#1353 NO-ISSUE Transfer assisted-installer-deployment repo under openshift-assisted org
  tools/deployment_options.py
Labels: approved, lgtm

#1354 MGMT-4398 Handle post step reply changes for new tool in assisted service
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/disks_info.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/mock_host_api.go
Labels: approved, lgtm

#1334 MGMT-4568 Block IPv6 input when not supported
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
Labels: approved, lgtm

#1198 MGMT-3659,MGMT-3483: Generate metrics/event on cluster validations failure/changes.
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/refresh_status_preprocessor.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/host/host.go
  internal/host/transition_test.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_metrics_manager_api.go
  subsystem/cluster_test.go
  subsystem/kubeapi_test.go
  subsystem/metrics_test.go
  subsystem/utils_test.go
Labels: approved, lgtm

#1365 OCPBUGSM-26541 Verify file name does not include folder
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
  models/create_manifest_params.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1369 MGMT-3431 Bugfix pass CHECK_CLUSTER_VERSION value to other components
  cmd/main.go
Labels: approved, lgtm

#1329 MGMT-4531 cluster host requirements handler
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/hardware/mock_validator.go
  internal/hardware/validator.go
  internal/hardware/validator_test.go
  internal/hardware/virt/virt.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/monitor_test.go
  internal/host/transition_test.go
  internal/host/validator.go
  internal/operators/api/api.go
  internal/operators/api/mock_operator_api.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/lso/ls_operator.go
  internal/operators/manager.go
  internal/operators/manager_test.go
  internal/operators/mock_operators_api.go
  internal/operators/ocs/ocs_operator.go
  pkg/conversions/conversions.go
  subsystem/cluster_test.go
Labels: approved, lgtm

#1368 NO-ISSUE Fixes in kubeAPI subsystem tests
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1359 OCPBUGSM-25994 Fix for unbalanced disks on OCS StorageCluster
  internal/operators/ocs/manifest.go
Labels: approved, lgtm
