Repository openshift/assisted-service, pull requests merged in 2021-04, with the labels that each got.

#1348 MGMT-4623 Publish index image for assisted service operator bundle
  Dockerfile.assisted-service-build
  Jenkinsfile
  Makefile
  skipper.env
Labels: approved, kind/dependency-change, lgtm

#1425 NO-ISSUE Remove subsystem steps from Jenkins as they run on OpenShift CI instead
  Jenkinsfile
  Makefile
Labels: approved, lgtm

#1404 MGMT-4715 Auto install Day 2 hosts in kube-api
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1428 NO-ISSUE: Index build needs to use the publish tag of bundle image
  Jenkinsfile
  Makefile
Labels: approved, lgtm

#1426 NO-ISSUE Remove APIVipDnsname handling from CRD
  internal/controller/controllers/clusterdeployments_controller.go
Labels: approved, lgtm

#1413 MGMT-4640 Versioned OCP requirements
  internal/hardware/validator.go
  internal/hardware/validator_test.go
  internal/hardware/versioned-requirements.go
  internal/hardware/versioned-requirements_test.go
  models/versioned_host_requirements.go
  openshift/template.yaml
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1279 MGMT-3697: BareMetal Agent controller …
  cmd/main.go
  docs/baremetal-agent-controller.md
  go.mod
  go.sum
  hack/crds/metal3.io_baremetalhosts.yaml
  internal/controller/config/rbac/role.yaml
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  internal/controller/controllers/controllers_suite_test.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  tools/deploy_crd.py
Labels: api-review, approved, lgtm

#1429 NO-ISSUE Extend Hive integration doc
  docs/Kube-API-examples.md
Labels: approved, lgtm

#1437 OCPBUGSM-27182 Backward-compatible IsOperatorAvailable function
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
Labels: approved, lgtm

#1417 MGMT-4587 Allow install-config overrides using annotations
  docs/Kube-API-examples.md
  docs/user-guide/install-customization.md
  go.sum
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1440 MGMT-4647 Remove HTTP409 event for `GenerateClusterISOInternal`
  internal/bminventory/inventory.go
Labels: approved, lgtm

#1441 OCPBUGSM-27173 Set operator status_updated_at field on operator status report
  internal/operators/handler/handler.go
  internal/operators/handler/handler_test.go
Labels: approved, lgtm

#1436 MGMT-4543 Updating ocp versions to latest releases 4.6.16 -> 4.6.23 & 4.7.2 -> 4.7.5
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#1439 Retry extracting the installer from the release image
  cmd/main.go
  go.mod
  go.sum
  internal/bminventory/inventory.go
  internal/installercache/installercache.go
  internal/oc/release.go
  internal/oc/release_test.go
Labels: approved, lgtm

#1434 NO-ISSUE Add an "about" section to the README
  README.md
Labels: approved, lgtm

#1435 NO-ISSUE - Jenkins slack message distinction between failure and user abort
  Jenkinsfile
Labels: approved, lgtm

#1336 NO-ISSUE Remove minikube code and PROFILE variable
  Dockerfile.assisted-service-build
  Makefile
  hack/update_local_image.sh
  pkg/job/job.go
  skipper.yaml
  tools/clear_deployment.py
  tools/debug/minikube_postgres.sh
  tools/deploy_assisted_installer.py
  tools/deploy_assisted_installer_configmap.py
  tools/deploy_crd.py
  tools/deploy_grafana.py
  tools/deploy_inventory_service.py
  tools/deploy_local_auth_secret.py
  tools/deploy_mariadb.py
  tools/deploy_namespace.py
  tools/deploy_olm.py
  tools/deploy_postgres.py
  tools/deploy_prometheus.py
  tools/deploy_role.py
  tools/deploy_route53.py
  tools/deploy_s3.py
  tools/deploy_scality_configmap.py
  tools/deploy_sso_secret.py
  tools/deploy_ui.py
  tools/deploy_wiremock.py
  tools/deployment_options.py
  tools/pvc_size_utils.py
  tools/utils.py
  tools/wait_for_assisted_service.py
Labels: approved, kind/dependency-change, lgtm

#1447 MGMT-4543 Updating versions to latest releases (#1436)
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#1448 OCPBUGSM-27182 Backward-compatible IsOperatorAvailable function (#1437)
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
Labels: approved, lgtm

#1449 OCPBUGSM-27173 Set operator status_updated_at field on operator statu…
  internal/operators/handler/handler.go
  internal/operators/handler/handler_test.go
Labels: approved, lgtm

#1358 MGMT-4443: Adding console-url to AMS subscription.
  go.mod
  go.sum
  internal/cluster/cluster.go
  internal/cluster/statemachine.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/common/db.go
  pkg/ocm/accounts_mgmt.go
  pkg/ocm/mock_accounts_mgmt.go
  subsystem/ams_subscriptions_test.go
  subsystem/cluster_test.go
  subsystem/metrics_test.go
  subsystem/operators_test.go
  subsystem/subsystem_suite_test.go
  subsystem/utils_test.go
  subsystem/wiremock_stubs.go
Labels: approved, lgtm

#1446 MGMT-4866 - remove code related to local day2 cluster flow
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/hostutil/host_utils.go
  internal/host/transition_test.go
  models/cluster.go
  models/host.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1444 NO-ISSUE Architecture document
  docs/architecture.md
Labels: approved, lgtm

#1423 MGMT-4822 Skip un-needed cluster status update
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/transition.go
  subsystem/cluster_test.go
Labels: approved, lgtm

#1452 Fixed markdown Heading in Kube-API-examples.md
  docs/Kube-API-examples.md
Labels: approved, lgtm

#1454 NO-ISSUE Remove skipper dependency from build_images.sh AppSRE script
  Makefile
  build_images.sh
Labels: approved, lgtm

#1453 Mgmt 4801 - Use common GetHostFromDB in the server
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/db.go
  internal/host/common.go
  internal/host/host.go
  internal/host/hostutil/update_host.go
  internal/host/hostutil/update_host_test.go
  internal/host/transition.go
Labels: approved, lgtm

#1438 MGMT-4580 InstallEnv should only accept a single optional SSH key
  docs/crds/clusterDeployment-SNO.yaml
  docs/crds/installEnv.yaml
  internal/controller/api/v1alpha1/installenv_types.go
  internal/controller/api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/config/crd/bases/adi.io.my.domain_installenvs.yaml
  internal/controller/config/crd/resources.yaml
  internal/controller/controllers/installenv_controller.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1459 MGMT-4822 Skip un-needed cluster status update (#1423)
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/transition.go
  subsystem/cluster_test.go
Labels: approved, lgtm

#1455 MGMT-4891 Validate hostNMConnections is not empty
  pkg/staticnetworkconfig/generator.go
Labels: approved, lgtm

#1451 MGMT-4523: Exposing ams_subscription_id field in API cluster model.
  internal/common/db.go
  models/cluster.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1461 MGMT-4850 set InstallationDiskID based on RootDeviceHints
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, lgtm

#1465 NO-ISSUE fix kubeAPI doc syntax highlighting
  docs/Kube-API-examples.md
Labels: approved, lgtm

#1418 MGMT-4733 Take supported GPUs memory overhead into account
  internal/host/hostutil/test_utils.go
  internal/host/transition_test.go
  internal/operators/builder.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/cnv/cnv_operator_test.go
  internal/operators/cnv/config.go
  internal/operators/cnv/config_test.go
  internal/operators/cnv/manifests_test.go
Labels: approved, lgtm

#1466 MGMT-4922 remove flaky call of updateAt while static
  subsystem/cluster_test.go
Labels: approved, lgtm

#1468 NO-ISSUE Allow @pkliczewski's team to lgtm PRs
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm

#1422 MGMT 4737: Add AgentServiceConfig controller
  Dockerfile.assisted-service
  Makefile
  cmd/operator/main.go
  config/assisted-service/kustomization.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/manager/manager.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  config/prometheus/monitor.yaml
  config/rbac/auth_proxy_service.yaml
  docs/operator.md
  go.mod
  go.sum
  internal/controller/api/v1alpha1/agentserviceconfig_types.go
  internal/controller/config/crd/bases/adi.io.my.domain_agentserviceconfigs.yaml
  internal/controller/config/crd/resources.yaml
  internal/controller/config/rbac/role.yaml
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/common.go
  internal/controller/controllers/images.go
Labels: approved, kind/dependency-change, lgtm

#1462 MGMT-4909 - add hosts' hyperthreading configuration to create/update …
  models/cluster.go
  models/cluster_create_params.go
  models/cluster_update_params.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1445 MGMT-4834 Reconcile on backend events
  Makefile
  cmd/main.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/controller_event_wrapper.go
  internal/controller/controllers/controller_event_wrapper_test.go
  internal/controller/controllers/crd_events_handler.go
  internal/controller/controllers/mock_crd_events_handler.go
Labels: approved, lgtm

#1470 MGMT-4910 - set hyperthreading configuration to install-config based on cluster configuration. User can set the following options: all (default), none, masters(only masters have hyperthreading enabled), workers(only workers have hyperthreading enabled)
  internal/bminventory/inventory.go
  internal/installcfg/installcfg.go
  internal/installcfg/installcfg_test.go
Labels: approved, lgtm

#1473 NO-ISSUE Increase operator resource limit/requests
  config/manager/manager.yaml
Labels: approved, lgtm

#1430 MGMT-4762 support head for iso download
  client/installer/download_cluster_i_s_o_headers_parameters.go
  client/installer/download_cluster_i_s_o_headers_responses.go
  client/installer/installer_client.go
  internal/bminventory/inventory.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  pkg/auth/authz_handler_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/download_cluster_i_s_o_headers.go
  restapi/operations/installer/download_cluster_i_s_o_headers_parameters.go
  restapi/operations/installer/download_cluster_i_s_o_headers_responses.go
  restapi/operations/installer/download_cluster_i_s_o_headers_urlbuilder.go
  subsystem/image_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1400 NO-ISSUE Replace envconfig prefix in-line string with a const
  cmd/main.go
  internal/cluster/cluster_test.go
  internal/common/common.go
  internal/hardware/validator_test.go
  internal/host/monitor_test.go
  internal/operators/ocs/ocs_operator.go
  internal/operators/ocs/validation_test.go
Labels: approved, lgtm

#1460 NO-ISSUE: Fixing update of console URL in OCM.
  internal/cluster/statemachine.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  subsystem/ams_subscriptions_test.go
  subsystem/wiremock_stubs.go
Labels: approved, lgtm

#517 NO-ISSUE Publish susbsystem reports
  Dockerfile.assisted-service-build
  Jenkinsfile
  Makefile
  dev-requirements.txt
  hack/setup_env.sh
Labels: approved, kind/dependency-change, lgtm, lifecycle/rotten

#1472 MGMT-4929 Add Agent Approval event
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/controller/controllers/controller_event_wrapper.go
  internal/controller/controllers/controller_event_wrapper_test.go
Labels: approved, lgtm

#1482 NO-ISSUE Pin k8s.io/api to v0.20.0
  go.mod
Labels: approved, lgtm

#1471 MGMT-4848 Return the newest agent in findAgent
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, lgtm

#1316 MGMT-4314 KubeAPI: InstallEnv support for nmstate config
  docs/crds/installEnv.yaml
  docs/crds/nmstate.yaml
  internal/controller/api/v1alpha1/nmstate_config_types.go
  internal/controller/api/v1alpha1/nmstate_util.go
  internal/controller/api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/config/crd/bases/adi.io.my.domain_nmstateconfigs.yaml
  internal/controller/config/crd/kustomization.yaml
  internal/controller/config/crd/resources.yaml
  internal/controller/config/rbac/role.yaml
  internal/controller/controllers/installenv_controller.go
  internal/controller/controllers/installenv_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1474 MGMT-4734 Adjust GPU data model
  models/gpu.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1427 MGMT-4363 mark the default ocp version
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  internal/versions/versions_test.go
  models/openshift_version.go
  onprem-environment
  openshift/template.yaml
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1433 MGMT-4704 - add CA and mirror registry to install-config.Allows to configure user provided mirror registries( via registries.conf) and certificate for the mirrors
  internal/bminventory/inventory.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/installcfg/installcfg.go
  internal/installcfg/installcfg_test.go
  models/mirror_registry.go
  pkg/mirrorregistries/generator.go
  pkg/mirrorregistries/generator_test.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1477 NO-ISSUE Updated Minimal Deployment RAM Requirements to 57GB
  internal/operators/ocs/validation_test.go
  internal/operators/ocs/validations.go
Labels: approved, lgtm

#1475 MGMT-4739: AgentServiceConfig controller cleanup
  cmd/operator/main.go
  config/manager/manager.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  docs/operator.md
  internal/controller/api/v1alpha1/agentserviceconfig_types.go
  internal/controller/config/crd/bases/adi.io.my.domain_agentserviceconfigs.yaml
  internal/controller/config/crd/resources.yaml
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/common.go
  internal/controller/controllers/images.go
Labels: approved, lgtm

#1483 MGMT-4955 Update OCP default version 4.7.5 -> 4.7.6
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#1484 MGMT-4937 Events doc
  docs/events.md
Labels: approved, lgtm

#1489 OCPBUGSM-27559 - fix pip install of the pycairo package. previously i…
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, lgtm

#1363 MGMT-4638 Rename `Group/Version` to `agent-install.openshift.io/v1beta1`
  cmd/main.go
  cmd/operator/main.go
  config/crd/bases/assistedservice.openshift.io.openshift.io_assistedservices.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  docs/Kube-API-examples.md
  docs/baremetal-agent-controller.md
  docs/crds/installEnv.yaml
  docs/crds/nmstate.yaml
  docs/operator.md
  internal/controller/api/v1beta1/agent_types.go
  internal/controller/api/v1beta1/agentserviceconfig_types.go
  internal/controller/api/v1beta1/groupversion_info.go
  internal/controller/api/v1beta1/installenv_types.go
  internal/controller/api/v1beta1/nmstate_config_types.go
  internal/controller/api/v1beta1/nmstate_util.go
  internal/controller/api/v1beta1/zz_generated.deepcopy.go
  internal/controller/config/crd/bases/agent-install.openshift.io_agents.yaml
  internal/controller/config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
  internal/controller/config/crd/bases/agent-install.openshift.io_installenvs.yaml
  internal/controller/config/crd/bases/agent-install.openshift.io_nmstateconfigs.yaml
  internal/controller/config/crd/kustomization.yaml
  internal/controller/config/crd/resources.yaml
  internal/controller/config/rbac/agentserviceconfig_editor_role.yaml
  internal/controller/config/rbac/agentserviceconfig_viewer_role.yaml
  internal/controller/config/rbac/role.yaml
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/common.go
  internal/controller/controllers/controllers_suite_test.go
  internal/controller/controllers/crd_utils.go
  internal/controller/controllers/crd_utils_test.go
  internal/controller/controllers/installenv_controller.go
  internal/controller/controllers/installenv_controller_test.go
  subsystem/kubeapi_test.go
  subsystem/subsystem_suite_test.go
Labels: approved, lgtm

#1490 OCPBUGSM-27561 Updating the host get to wrong boot order event to con…
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, lgtm

#1494 Igal/support installer args
  docs/Kube-API-examples.md
  go.mod
  go.sum
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/api/v1beta1/agent_types.go
  internal/controller/config/crd/bases/agent-install.openshift.io_agents.yaml
  internal/controller/config/crd/resources.yaml
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  subsystem/kubeapi_test.go
  subsystem/subsystem_suite_test.go
Labels: approved, lgtm

#1503 NO-ISSUE improving doc for installer args override with crd flow
  docs/Kube-API-examples.md
Labels: approved, lgtm

#1487 OCPBUGSM-26455 - Change misleading message indicates we can support more than 3 masters
  internal/cluster/transition_test.go
  internal/cluster/validator.go
  internal/operators/ocs/validation_test.go
Labels: approved, lgtm

#1497 NO-ISSUE Remove error log when iso template versions is missing
  pkg/s3wrapper/util.go
Labels: approved, lgtm

#1501 OCPBUGSM-27612 - Fix typo in dnsmasq description
  internal/network/machine_network_cidr.go
  internal/network/manifests_generator.go
Labels: approved, lgtm

#1504 NO-ISSUE documents how to configure baremetal-operator to watch all namespaces
  docs/user-guide/assisted-service-on-openshift.md
Labels: approved, lgtm

#1495 MGMT-4991 Allow the service to serve https traffic
  cmd/main.go
Labels: approved, lgtm

#1457 MGMT-4467 Add conditions to Agent CRD
  internal/controller/api/v1beta1/agent_types.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/refresh_status_preprocessor.go
  internal/host/transition.go
  internal/host/transition_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1464 MGMT-4711 Move to new installation initiation flow
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/common.go
  internal/cluster/conditions.go
  internal/cluster/mock_cluster_api.go
  internal/cluster/refresh_status_preprocessor.go
  internal/cluster/statemachine.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/common/disks_info.go
  internal/dns/dns.go
  internal/dns/dns_test.go
  internal/hardware/boot_device.go
  internal/hardware/mock_validator.go
  internal/hardware/validator.go
  internal/host/common.go
  internal/host/conditions.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostcommands/disk_performance_cmd.go
  internal/host/hostcommands/disk_performance_cmd_test.go
  internal/host/hostcommands/fio_perf_check_cmd.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/instruction_manager.go
  internal/host/mock_host_api.go
  internal/host/monitor.go
  internal/host/monitor_test.go
  internal/host/refresh_status_preprocessor.go
  internal/host/statemachine.go
  internal/host/transition.go
  internal/host/transition_test.go
  internal/operators/ocs/validation_test.go
  subsystem/cluster_test.go
  subsystem/host_test.go
  subsystem/kubeapi_test.go
  subsystem/utils_test.go
Labels: approved, lgtm

#1499 NO-ISSUE making subsystem for ignition override less flaky
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1498 MGMT-4996 Bugfix Wrap REST error StatusNotFound when gorm record isn't found
  Makefile
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/error_utils.go
Labels: approved, lgtm

#1395 NO-ISSUE Use logging instead of print in tools scripts
  tools/deploy_assisted_installer.py
  tools/deploy_namespace.py
  tools/deploy_role.py
Labels: approved, lgtm

#1424 MGMT-4494: Create bmh in spoke cluster
  go.mod
  go.sum
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/spoke_cluster.go
Labels: approved, lgtm

#1485 MGMT-4921 Rename InstallEnv --> InfraEnv
  cmd/main.go
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  docs/Kube-API-examples.md
  docs/baremetal-agent-controller.md
  docs/crds/infraEnv.yaml
  internal/controller/api/v1beta1/infraenv_types.go
  internal/controller/api/v1beta1/zz_generated.deepcopy.go
  internal/controller/config/crd/bases/agent-install.openshift.io_infraenvs.yaml
  internal/controller/config/crd/kustomization.yaml
  internal/controller/config/crd/resources.yaml
  internal/controller/config/rbac/role.yaml
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/common.go
  internal/controller/controllers/controller_event_wrapper.go
  internal/controller/controllers/crd_events_handler.go
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  internal/controller/controllers/mock_crd_events_handler.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1513 NO-ISSUE: Update docs for BMAC deployment
  docs/baremetal-agent-controller.md
Labels: approved, lgtm

#1505 OCPBUGSM-27640: localjob when storage=filesystem
  Makefile
  cmd/main.go
  skipper.env
  tools/deploy_assisted_installer_configmap.py
  tools/deploy_s3.py
  tools/deployment_options.py
Labels: approved, lgtm

#1517 MGMT-5237 Update ocp version 4.7.6 -> 4.7.7
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#1492 MGMT-4981: crds and dependencies for custom version support
  cmd/main.go
  docs/crds/clusterImageSet.yaml
  hack/crds/hive.openshift.io_clusterimagesets.yaml
  internal/controller/config/rbac/role.yaml
  internal/controller/controllers/clusterdeployments_controller.go
  models/cluster.go
  models/cluster_create_params.go
  models/openshift_version.go
  restapi/embedded_spec.go
  swagger.yaml
  tools/handle_ocp_versions.py
Labels: api-review, approved, lgtm

#1500 MGMT-5176 - Fix support for disabling hyperthrreading
  internal/installcfg/installcfg.go
  internal/installcfg/installcfg_test.go
Labels: approved, lgtm

#1518 MGMT-5240 - Add recently released 4.8.0-fc.0 to the default versions JSON
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  hack/get_ocp_versions_for_testing.sh
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#1519 NO-ISSUE: Fix ClusterDeployment example
  docs/crds/clusterDeployment-SNO.yaml
  docs/crds/clusterDeployment.yaml
Labels: approved, lgtm

#1511 OCPBUGSM-1948449: Update Standard Deployment RAM and CPU requirements
  internal/operators/ocs/validation_test.go
  internal/operators/ocs/validations.go
Labels: approved, lgtm

#1516 OCPBUGSM-26430 - fix dns resolution for bootstrap node configured wit…
  internal/common/common.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
Labels: approved, lgtm

#1520 MGMT-5249 AI controller will install only OCP 4.8
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1507 NO-ISSUE: Update doc: nmstate and agent conditions
  docs/Kube-API.md
Labels: approved, lgtm

#1361 MGMT-4143 usage table and API
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/usage/consts.go
  internal/usage/manager.go
  internal/usage/manager_test.go
  internal/usage/mock_usage_manager.go
  models/cluster.go
  models/usage.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  subsystem/operators_test.go
  subsystem/utils_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1488 OCPBUGSM-24075 - Correct the spelling of 'canceled' on "canceled by user" event
  internal/bminventory/inventory.go
Labels: api-review, approved, lgtm

#1521 NO-ISSUE Replace gorm.IsRecordNotFoundError with errors.Is
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster_test.go
  internal/cluster/common.go
  internal/cluster/registrar.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/infraenv_controller.go
  internal/host/host.go
  internal/operators/handler/handler.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1523 Multiple issues
  internal/cluster/validator.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1496 MGMT-3443: Adding Grafana dashboards for validations metrics.
  dashboards/grafana-dashboard-assisted-installer-validations.configmap.yaml
Labels: approved, lgtm

#1509 MGMT-5188 Deprecate UpdateClusterInstallProgress API
  client/installer/installer_client.go
  client/installer/update_cluster_install_progress_parameters.go
  client/installer/update_cluster_install_progress_responses.go
  cmd/main.go
  internal/bminventory/inventory.go
  internal/cluster/cluster.go
  internal/cluster/common.go
  internal/cluster/mock_cluster_api.go
  internal/cluster/statemachine.go
  internal/cluster/transition.go
  internal/operators/handler/handler.go
  internal/operators/handler/handler_test.go
  mocks/mock_assisted_service.go
  models/cluster.go
  models/cluster_progress_info.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/update_cluster_install_progress.go
  restapi/operations/installer/update_cluster_install_progress_parameters.go
  restapi/operations/installer/update_cluster_install_progress_responses.go
  restapi/operations/installer/update_cluster_install_progress_urlbuilder.go
  subsystem/cluster_test.go
  subsystem/utils_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1508 MGMT-4477 Pre-flight host requirements API
  client/installer/get_preflight_requirements_parameters.go
  client/installer/get_preflight_requirements_responses.go
  client/installer/installer_client.go
  internal/bminventory/inventory.go
  mocks/mock_assisted_service.go
  models/host_type_hardware_requirements.go
  models/host_type_hardware_requirements_wrapper.go
  models/operator_hardware_requirements.go
  models/preflight_hardware_requirements.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/get_preflight_requirements.go
  restapi/operations/installer/get_preflight_requirements_parameters.go
  restapi/operations/installer/get_preflight_requirements_responses.go
  restapi/operations/installer/get_preflight_requirements_urlbuilder.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1528 MGMT-5265 Add the ability to disable host validations via configuration
  cmd/main.go
  go.mod
  go.sum
  internal/host/host.go
  internal/host/host_test.go
  internal/host/monitor_test.go
  internal/host/refresh_status_preprocessor.go
  internal/host/refresh_status_preprocessor_test.go
  internal/host/statemachine.go
  internal/host/statemachine_test.go
  internal/host/transition_test.go
Labels: approved, lgtm

#1531 NO-ISSUE: Fixing validations dashboards name.
  dashboards/grafana-dashboard-assisted-installer-validations.configmap.yaml
Labels: approved, lgtm

#1525 OCPBUGSM-25356 Handle net prefix for single node
  internal/network/cidr_validations.go
  internal/network/cidr_validations_test.go
Labels: approved, lgtm

#1533 MGMT-4965: Fixing OCM-Operations Grafana dashboard.
  dashboards/grafana-dashboard-assisted-installer-ocm-operations.configmap.yaml
Labels: approved, lgtm

#1530 MGMT-5266 Add API endpoint for resetting failed host validation
  client/installer/installer_client.go
  client/installer/reset_host_validation_parameters.go
  client/installer/reset_host_validation_responses.go
  internal/bminventory/inventory.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/reset_host_validation.go
  restapi/operations/installer/reset_host_validation_parameters.go
  restapi/operations/installer/reset_host_validation_responses.go
  restapi/operations/installer/reset_host_validation_urlbuilder.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1534 MGMT-5280 move installcfg package to use interface as an external API
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/installcfg/installcfg.go
  internal/installcfg/installcfg_test.go
  internal/installcfg/mock_installcfg.go
Labels: approved, lgtm

#1476 MGMT-4914: BMAC sets IgnitionConfigOverride to agent
  internal/controller/api/v1beta1/agent_types.go
  internal/controller/config/crd/bases/agent-install.openshift.io_agents.yaml
  internal/controller/config/crd/resources.yaml
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, lgtm

#1529 MGMT-5268 SetStatusCondition causes controllers reconcile endless loop
  go.mod
  go.sum
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/infraenv_controller.go
Labels: approved, lgtm

#1535 MGMT-5288 Handle NOOP transition for host "preparation-successful" state
  internal/host/statemachine.go
  internal/host/transition_test.go
Labels: approved, lgtm

#1512 NO-ISSUE Set `online: true` and disable autoamted cleaning in the BMH resource
  go.mod
  go.sum
  internal/controller/config/rbac/kube_api_roles.yaml
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/crd_events_handler.go
  internal/controller/controllers/crd_utils_test.go
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
Labels: approved, lgtm

#1409 OCPBUGSM-17327 Handle asterisk in NoProxy values
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/ignition/ignition_test.go
  internal/installcfg/installcfg.go
  internal/installcfg/installcfg_test.go
Labels: approved, lgtm

#1491 MGMT-3512 Report FS usage metrics
  cmd/main.go
  go.mod
  internal/metrics/metricsManager.go
  internal/metrics/mock_metrics_manager_api.go
  pkg/s3wrapper/filesystem.go
  pkg/s3wrapper/filesystem_test.go
Labels: approved, lgtm

#1515 MGMT-4477 Preflight hardware requirements handler
  internal/bminventory/inventory.go
  internal/hardware/mock_validator.go
  internal/hardware/validator.go
  internal/hardware/validator_test.go
  internal/host/host.go
  internal/host/mock_host_api.go
  internal/host/transition_test.go
  internal/operators/api/api.go
  internal/operators/api/mock_operator_api.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/cnv/cnv_operator_test.go
  internal/operators/lso/ls_operator.go
  internal/operators/manager.go
  internal/operators/manager_test.go
  internal/operators/mock_operators_api.go
  internal/operators/ocs/ocs_operator.go
  subsystem/cluster_test.go
Labels: api-review, approved, lgtm

#1443 MGMT-3512 Reduce disk space taken by assisted service
  cmd/main.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/garbagecollector/garbageCollector.go
  internal/imgexpirer/imgexpirer.go
  internal/imgexpirer/imgexpirer_test.go
Labels: approved, lgtm

#1536 Mgmt 5282 kubeapi info log on reconcile entering
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/infraenv_controller.go
Labels: approved, lgtm

#1539 NO-ISSUE - add kubectl to the build image
  hack/setup_env.sh
  skipper-mac.yaml
  skipper.yaml
Labels: approved, kind/dependency-change, lgtm

#1456 MGMT-4557: Add Host Validation for OCS
  internal/operators/ocs/consts.go
  internal/operators/ocs/ocs_operator.go
  internal/operators/ocs/ocs_operator_test.go
  internal/operators/ocs/test_utils.go
  internal/operators/ocs/validation_test.go
  internal/operators/ocs/validations.go
  pkg/conversions/conversions.go
Labels: approved, lgtm

#1532 MGMT-4526 - Extended Event API
  internal/controller/controllers/controller_event_wrapper.go
  internal/events/event.go
  internal/events/event_test.go
  internal/events/mock_event.go
  models/event.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1239 MGMT-4444 Enable machine cidr validators for single node
  internal/cluster/validator.go
  internal/host/validator.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1544 MGMT-5324 Skip flaky subsystem kube-api test invalid namestate
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1551 OCPBUGSM-28144 fix reconcile error of installed SNO cluster
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, lgtm

#1420 OCPBUGSM-26846 Fix DHCP failing silently on reboot
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, lgtm

#1467 MGMT-4273 Create secret key to enable local AUTH_TYPE in operator
  config/assisted-service/kustomization.yaml
  internal/controller/api/v1beta1/agentserviceconfig_types.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
Labels: approved, kind/dependency-change, lgtm

#1506 MGMT-4740 Encrypt traffic to assisted service
  internal/controller/controllers/agentserviceconfig_controller.go
Labels: approved, lgtm

#1546 NO-ISSUE set feature-usage to nil in old clusters
  internal/usage/manager.go
  models/cluster.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1541 MGMT-4494 Unit tests for reconciling day2 worker
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, lgtm

#1502 MGMT-4463 Support IgnitionConfigOverrides in the Agent
  docs/Kube-API.md
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/api/v1beta1/agent_types.go
  internal/controller/config/crd/bases/agent-install.openshift.io_agents.yaml
  internal/controller/config/crd/resources.yaml
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1562 MGMT-4444 Update SNO CRD example with machinenetwork
  docs/crds/clusterDeployment-SNO.yaml
Labels: approved, lgtm

#1553 MGMT-3879 Enhance kube api conditions docs
  docs/Kube-API.md
  docs/kube-api-conditions.md
Labels: approved, lgtm

#1493 MGMT-4563 Skip host connection validation when host is installed or p…
  internal/host/host.go
  internal/host/refresh_status_preprocessor.go
  internal/host/transition_test.go
  internal/host/validator.go
  subsystem/metrics_test.go
Labels: approved, lgtm

#1559 NO-ISSUE remove dependency of common in s3wrapper
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/common/common.go
  internal/common/error_utils.go
  pkg/s3wrapper/client.go
  pkg/s3wrapper/errors.go
  pkg/s3wrapper/filesystem.go
  pkg/s3wrapper/util.go
Labels: approved, lgtm

#1524 MGMT-3879 Add ClusterDeployment Conditions
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/refresh_status_preprocessor.go
  internal/cluster/transition_test.go
  internal/controller/api/v1beta1/agent_types.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/conditions.go
  subsystem/cluster_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1564 MGMT-5306 Handle dhcp karg in case of SNO
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, lgtm

#1566 NO-ISSUE fix some typos
  docs/baremetal-agent-controller.md
Labels: approved, lgtm

#1570 NO-ISSUE Refactor kubeapi sub test InfraEnv condition
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1548 Mgmt 4967
  Dockerfile.assisted-service-debug
  Makefile
  hack/update_local_image.sh
  skipper-mac.yaml
  skipper.env
  skipper.yaml
Labels: approved, kind/dependency-change, lgtm

#1565 Mgmt 4843 clusterdeployment api and console urls
  internal/bminventory/inventory.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/common/common.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/cluster_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1571 NO-ISSUE Updated logging in release.go to reflect cases that `oc extr…
  internal/oc/release.go
Labels: approved, lgtm

#1572 MGMT-5274 Allow override SERVICE_BASE_URL for test-infra port-forwarding
  internal/controller/controllers/agentserviceconfig_controller.go
Labels: approved, lgtm

#1578 OCP version update 4.7.7 -> 4.7.8 & rhcos update 4.7.0 -> 4.7.7
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#1573 MGMT-5359 High CPU usage of Assisted-Service with 500 clusters and not hosts
  internal/cluster/cluster.go
  internal/cluster/transition.go
  internal/cluster/validator.go
Labels: approved, lgtm

#1319 MGMT-4554 API for supporting a custom OCP version
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/common/test_configuration.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/common.go
  internal/controller/controllers/controllers_suite_test.go
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  internal/oc/release.go
  internal/versions/mock_versions.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  subsystem/kubeapi_test.go
Labels: api-review, approved, lgtm

#1577 MGMT-4185 add release_version to default_ocp_versions
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#1550 MGMT-4930 Add notifications from ClusterDeployment to InfravEnv
  internal/controller/controllers/infraenv_controller.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1554 BZ-1937293: Disable container-image-availability host validation
  cmd/main.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/monitor_test.go
  internal/host/refresh_status_preprocessor.go
  internal/host/refresh_status_preprocessor_test.go
  internal/host/statemachine.go
  internal/host/statemachine_test.go
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, lgtm

#1540 NO-ISSUE: Adds BMH detached annotation if Agent installation has started
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, lgtm

#1575 NO-ISSUE: Docs update
  docs/Kube-API.md
Labels: approved, lgtm

#1582 MGMT-3512 Skip garbage collection jobs in operator deployment
  cmd/main.go
Labels: approved, lgtm

#1583 MGMT-5386: Fixing OCM-Operations Grafana dashboard.
  dashboards/grafana-dashboard-assisted-installer-ocm-operations.configmap.yaml
Labels: approved, lgtm

#1580 OCPBUGSM-28006 Fix vxlan vmware incorrect checksum in assisted installer
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/common/test_configuration.go
  internal/network/manifests_generator.go
  internal/network/mock_manifests_generator.go
Labels: approved, lgtm

#1588 MGMT-4183 use z-stream version for ClusterRegistered metric
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#1561 MGMT-5295 - Use AI configuration to configure DiscoveryISO and RHCOS …
  cmd/main.go
  internal/bminventory/inventory.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/installcfg/installcfg.go
  internal/installcfg/installcfg_test.go
  models/image_create_params.go
  models/image_info.go
  models/mirror_registries_ca_config.go
  models/mirror_registries_config.go
  models/mirror_registry.go
  pkg/mirrorregistries/generator.go
  pkg/mirrorregistries/generator_test.go
  pkg/mirrorregistries/mock_generator.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1526 MGMT-5174 Subsystem tests for epic MGMT-3563
  subsystem/cluster_test.go
  subsystem/kubeapi_test.go
  subsystem/utils_test.go
Labels: approved, lgtm

#1590 OCPBUGSM-27380 Fix confusing host registration error
  internal/bminventory/inventory.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
Labels: approved, lgtm

#1568 MGMT-5372 added scripts for operator installation
  deploy/operator/deploy.sh
  deploy/operator/gather.sh
  deploy/operator/setup_assisted_operator.sh
  deploy/operator/setup_hive.sh
  deploy/operator/setup_lso.sh
  deploy/operator/utils.sh
Labels: approved, lgtm

#1574 MGMT-5362: Add CapabilityReview to OCM's cache.
  pkg/auth/rhsso_authenticator.go
Labels: approved, lgtm

#1576 Mgmt 4967 Create a standard way to run a debugger on the service
  Dockerfile.assisted-service-debug
  Makefile
  debug.md
  deploy/assisted-service.yaml
  skipper-mac.yaml
  tools/deploy_assisted_installer.py
  tools/deploy_inventory_service.py
  tools/deployment_options.py
  tools/wait_for_assisted_service.py
Labels: approved, kind/dependency-change, lgtm

#1597 OCPBUGSM-28353 Modified LSO Subscription manifest to use default channel
  internal/operators/lso/ls_operator.go
  internal/operators/lso/manifest.go
Labels: approved, lgtm

#1605 NO-ISSUE: Adding debug info for failing validations subsystem tests.
  subsystem/metrics_test.go
Labels: approved, lgtm
