Repository openshift/assisted-service, pull requests merged in 2021-01, with the labels that each got.

#854 MGMT-3407 Add host and image controller unit tests
  internal/controller/controllers/controllers_suite_test.go
  internal/controller/controllers/host_controller_test.go
  internal/controller/controllers/image_controller_test.go
Labels: approved, lgtm

#851 MGMT-3452 Collect logs from onprem on AI CI
  Jenkinsfile
Labels: approved, lgtm

#852 OCPBUGSM-22592 Clarify disk format event
  internal/host/installcmd.go
  internal/host/installcmd_test.go
Labels: approved, lgtm

#855 MGMT-3437 Shell escape for installCmd
  go.mod
  go.sum
  internal/host/installcmd.go
  internal/host/installcmd_test.go
Labels: approved, lgtm

#853 NO-ISSUE - Makefile cleanup target used pipes instead of conditions
  Makefile
Labels: approved, lgtm

#845 MGMT-3405 - block role and user network mode update in sno case
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/transition_test.go
  internal/cluster/validator.go
  internal/common/common.go
Labels: api-review, approved, lgtm

#844 MGMT-3358 Image CRD
  internal/controller/api/v1alpha1/image_types.go
  internal/controller/api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/config/crd/bases/adi.io.my.domain_images.yaml
Labels: approved, lgtm

#849 MGMT-3407: Add cluster controller test infra
  internal/controller/controllers/cluster_controller_test.go
Labels: approved, lgtm

#858 MGMT-3100 - Add missing generated files from #755
  restapi/embedded_spec.go
Labels: approved, lgtm

#856 MGMT-2245 Extract OCP version from OCP images
  cmd/main.go
  go.mod
  go.sum
  internal/cluster/mock_cluster_api.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/instructionmanager.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/installercache/installercache.go
  internal/isoutil/mock_isoutil.go
  internal/metrics/mock_netricsManager_api.go
  internal/network/mock_ntp_utils.go
  internal/oc/mock_release.go
  internal/oc/release.go
  internal/oc/release_test.go
  internal/versions/mock_versions.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  pkg/executer/executer.go
  pkg/executer/mock_executer.go
  pkg/generator/mock_install_config.go
  pkg/job/job.go
  pkg/k8sclient/mock_k8sclient.go
  pkg/leader/mock_leader_elector.go
  pkg/ocm/mock_authorization.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3manageriface.go
  pkg/s3wrapper/mock_s3wrapper.go
Labels: approved, lgtm

#857 MGMT-3433 Create cluster with CRD
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/controllers/cluster_controller.go
  internal/controller/controllers/cluster_controller_test.go
  internal/controller/controllers/controllers_suite_test.go
Labels: approved, lgtm

#863 MGMT-3488 Move cluster_mode set to register cluster
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  models/cluster_create_params.go
  models/cluster_update_params.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#862 MGMT-3456 - Will not attempt to format bootable disks that look like installation media
  internal/bminventory/mock_installer_internal.go
  internal/cluster/mock_cluster_api.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/installcmd.go
  internal/host/installcmd_test.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/isoutil/mock_isoutil.go
  internal/metrics/mock_netricsManager_api.go
  internal/network/mock_ntp_utils.go
  internal/oc/mock_release.go
  internal/versions/mock_versions.go
  models/disk.go
  pkg/executer/mock_executer.go
  pkg/generator/mock_install_config.go
  pkg/k8sclient/mock_k8sclient.go
  pkg/leader/mock_leader_elector.go
  pkg/ocm/mock_authorization.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3manageriface.go
  pkg/s3wrapper/mock_s3wrapper.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#867 MGMT-3489 Update create ignition-configs in case HighAvailabilityMode is None
  internal/ignition/ignition.go
Labels: approved, lgtm

#871 NO-ISSUE Stop trying to push the iso create image
  build_deploy.sh
Labels: approved, lgtm

#873 MGMT-3511 Wait for service in onprem deployment
  Makefile
  tools/deployment_options.py
  tools/utils.py
Labels: approved, lgtm

#866 NO-ISSUE: Fixed typo in spec.channel in lsoSubscription manifest
  internal/operators/lso/utils.go
Labels: approved, lgtm

#874 MGMT-3358 Minor fixes to Image CRD
  internal/controller/api/v1alpha1/image_types.go
  internal/controller/api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/config/crd/bases/adi.io.my.domain_images.yaml
Labels: approved, lgtm

#877 MGMT-3489 Update create ignition-configs in case HighAvailabilityMode…
  internal/ignition/ignition.go
Labels: approved, lgtm

#878 MGMT-3356 Rename Pull Secret in Cluster CRD
  internal/controller/api/v1alpha1/cluster_types.go
  internal/controller/api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/config/crd/bases/adi.io.my.domain_clusters.yaml
  internal/controller/controllers/cluster_controller.go
  internal/controller/controllers/cluster_controller_test.go
Labels: approved, lgtm

#876 NO-ISSUE - make format target shouldn't format anything the linter doesn't check
  Makefile
  internal/bminventory/mock_installer_internal.go
  internal/cluster/mock_cluster_api.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/isoutil/mock_isoutil.go
  internal/metrics/mock_netricsManager_api.go
  internal/network/mock_ntp_utils.go
  internal/oc/mock_release.go
  internal/versions/mock_versions.go
  pkg/executer/mock_executer.go
  pkg/generator/mock_install_config.go
  pkg/k8sclient/mock_k8sclient.go
  pkg/leader/mock_leader_elector.go
  pkg/ocm/mock_authorization.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3manageriface.go
  pkg/s3wrapper/mock_s3wrapper.go
Labels: approved, lgtm

#847 MGMT-3330 default OPENSHIFT_VERSION
  Makefile
  openshift/template.yaml
Labels: approved, kind/dependency-change, lgtm

#872 MGMT-3297 - support static ips when rebooting nodes woth RHCOS image
  internal/bminventory/inventory.go
  internal/bminventory/mock_installer_internal.go
  internal/cluster/mock_cluster_api.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/installcmd.go
  internal/host/installcmd_test.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/isoutil/mock_isoutil.go
  internal/metrics/mock_netricsManager_api.go
  internal/network/mock_ntp_utils.go
  internal/oc/mock_release.go
  internal/versions/mock_versions.go
  pkg/executer/mock_executer.go
  pkg/generator/mock_install_config.go
  pkg/k8sclient/mock_k8sclient.go
  pkg/leader/mock_leader_elector.go
  pkg/ocm/mock_authorization.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3manageriface.go
  pkg/s3wrapper/mock_s3wrapper.go
Labels: approved, lgtm

#864 MGMT-3476 - Service will now set hosts installation disks field to the default installation disk
  internal/host/host.go
  internal/host/host_test.go
  internal/host/installcmd.go
Labels: approved, lgtm

#881 NO-ISSUE add goimports to fix auto generated controllers code
  Makefile
Labels: approved, lgtm

#869 MGMT-3353 RHCOS per version
  client/bootfiles/download_boot_files_parameters.go
  cmd/main.go
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  internal/assistedserviceiso/assistedserviceiso_api.go
  internal/assistedserviceiso/assistedserviceiso_api_test.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/bootfiles/bootfiles.go
  internal/bootfiles/bootfiles_test.go
  internal/cluster/mock_cluster_api.go
  internal/connectivity/mock_connectivity_validator.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/mock_host_api.go
  internal/host/mock_instruction_api.go
  internal/imgexpirer/imgexpirer_test.go
  internal/isoutil/mock_isoutil.go
  internal/metrics/mock_netricsManager_api.go
  internal/network/mock_ntp_utils.go
  internal/oc/mock_release.go
  internal/versions/mock_versions.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  models/assisted_service_iso_create_params.go
  models/openshift_version.go
  onprem-environment
  pkg/executer/mock_executer.go
  pkg/generator/mock_install_config.go
  pkg/job/local_job.go
  pkg/k8sclient/mock_k8sclient.go
  pkg/leader/mock_leader_elector.go
  pkg/ocm/mock_authorization.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/client.go
  pkg/s3wrapper/client_test.go
  pkg/s3wrapper/filesystem.go
  pkg/s3wrapper/filesystem_test.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3manageriface.go
  pkg/s3wrapper/mock_s3wrapper.go
  pkg/s3wrapper/upload_iso.go
  pkg/s3wrapper/util_test.go
  restapi/embedded_spec.go
  restapi/operations/bootfiles/download_boot_files_parameters.go
  restapi/operations/bootfiles/download_boot_files_urlbuilder.go
  subsystem/image_test.go
  subsystem/ipv6_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#883 MGMT-3489 Support None HighAvailabilityMode
  internal/cluster/transition.go
  internal/ignition/ignition.go
Labels: approved, lgtm

#803 MGMT-3514 Add extract and create methods to the iso handler
  go.mod
  go.sum
  internal/isoutil/isoutil.go
  internal/isoutil/isoutil_test.go
  internal/isoutil/mock_isoutil.go
Labels: approved, lgtm

#662 MGMT-2712 Validate cert in install config overrides
  internal/bminventory/inventory.go
  internal/installcfg/installcfg.go
  internal/installcfg/installcfg_test.go
Labels: approved, lgtm

#884 Avishay/fix onprem wait
  Makefile
  tools/deployment_options.py
  tools/utils.py
Labels: approved, lgtm

#860 MGMT-3458 Pass REST API params to FIO cmd
  internal/bminventory/inventory.go
  internal/host/fioperfcheckcmd.go
  internal/host/installcmd.go
  internal/host/installcmd_test.go
  models/fio_perf_check_request.go
  models/fio_perf_check_response.go
  subsystem/host_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#886 NO-ISSUE Enforce description format in swagger lint
  .spectral.yml
  swagger.yaml
Labels: api-review, approved, lgtm

#890 MGMT-3353 Update ocp template
  openshift/template.yaml
Labels: approved, lgtm

#888 MGMT-3459 added metrics for disk sync duration
  internal/bminventory/inventory.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_netricsManager_api.go
Labels: api-review, approved, lgtm

#893 Revert "OCPBUGSM-21433 Enable NTP validation as sufficient for installation"
  internal/host/statemachine.go
  internal/host/transition_test.go
  subsystem/cluster_test.go
Labels: approved, lgtm

#889 OCPBUGSM-22671, OCPBUGSM-22656 Remove IPv6 networks from host networks.
  go.sum
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  subsystem/ipv6_test.go
Labels: approved, lgtm

#895 MGMT-3026 update openshift template for FIO check
  openshift/template.yaml
Labels: approved, lgtm

#870 MGMT-3507 Openshift version is sent to relevant metrics
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_netricsManager_api.go
Labels: approved, lgtm

#897 MGMT-3551 add name to FIO check container
  internal/host/fioperfcheckcmd.go
  internal/host/installcmd_test.go
Labels: approved, lgtm

#894 NO-ISSUE missed run of make generate-from-swagger
  client/bootfiles/download_boot_files_parameters.go
  restapi/embedded_spec.go
  restapi/operations/bootfiles/download_boot_files_parameters.go
Labels: approved, lgtm

#896 NO-ISSUE Add Cluster NTP metric on PrepareForInstallation
  go.sum
  internal/bminventory/mock_installer_internal.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/transition.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_netricsManager_api.go
Labels: approved, lgtm

#865 MGMT-3361: Image Controller - Create
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/api/v1alpha1/image_types.go
  internal/controller/api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/config/crd/bases/adi.io.my.domain_images.yaml
  internal/controller/controllers/cluster_controller_test.go
  internal/controller/controllers/error_utils.go
  internal/controller/controllers/image_controller.go
  internal/controller/controllers/image_controller_test.go
Labels: approved, lgtm

#850 MGMT-3200 Add IPv6 static IP
  internal/bminventory/inventory.go
  internal/ignition/ignition.go
  models/static_ip_config.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#900 MGMT-2977 Add a cache for downloading files from S3
  pkg/s3wrapper/file_cache.go
  pkg/s3wrapper/file_cache_test.go
Labels: approved, lgtm

#901 MGMT-2977 Enhancements to isoutil
  internal/isoutil/isoutil.go
  internal/isoutil/isoutil_test.go
  internal/isoutil/mock_isoutil.go
Labels: approved, lgtm

#879 MGMT-3508 Adjust Grafana dashboards to filter data by openshift version
  dashboards/grafana-dashboard-assisted-installer-general-overview.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-weekly-overview.configmap.yaml
Labels: approved, lgtm

#887 MGMT-3356 Cluster CRD - align with K8s API name conventions
  internal/controller/api/v1alpha1/cluster_types.go
  internal/controller/api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/config/crd/bases/adi.io.my.domain_clusters.yaml
  internal/controller/controllers/cluster_controller.go
Labels: approved, lgtm

#899 MGTM-3552 Remove default for user-managed-networking in cluster updat…
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#907 Mgmt 3539 get clutster by k8s key
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/mock_cluster_api.go
  internal/common/db.go
  internal/controller/controllers/cluster_controller.go
  internal/controller/controllers/cluster_controller_test.go
Labels: approved, lgtm

#908 MGMT-3572 Modify image_test to run against the supported OCP versions
  subsystem/cluster_test.go
  subsystem/image_test.go
  subsystem/ipv6_test.go
  subsystem/manifests_test.go
Labels: approved, lgtm

#909 NO-ISSUE Remove [only-k8s] tests references
  subsystem/cluster_test.go
  subsystem/image_test.go
Labels: approved, lgtm

#904 MGMT-3568 - fix formatting of boolean input arguments in Install command
  internal/host/fioperfcheckcmd.go
  internal/host/installcmd.go
  internal/host/installcmd_test.go
Labels: approved, lgtm

#910 OCPBUGSM-22643 Replace NTP pending with failure
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, lgtm

#912 MGMT-3583 user-managed-networking must be renamed to user_managed_net…
  models/cluster.go
  models/cluster_create_params.go
  models/cluster_update_params.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#914 Bump RHCOS 4.7 image to use 4.7.0-fc.0 instead of 4.6.8
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#915 NO-ISSUE fixing leader test on aws
  subsystem/leader_test.go
Labels: approved, lgtm

#916 NO-ISSUE add Elior Erez to code reviewers
  OWNERS_ALIASES
Labels: approved, lgtm

#891 MGMT-3434 Support cluster update with k8s API
  Makefile
  cmd/main.go
  internal/controller/api/v1alpha1/cluster_types.go
  internal/controller/config/crd/bases/adi.io.my.domain_images.yaml
  internal/controller/config/rbac/role.yaml
  internal/controller/config/rbac/secret_patch.yaml
  internal/controller/controllers/cluster_controller.go
  internal/controller/controllers/cluster_controller_test.go
  internal/controller/controllers/controllers_suite_test.go
Labels: approved, lgtm

#917 MGMT-3431 add CVO check flag
  internal/host/installcmd.go
  internal/host/installcmd_test.go
  internal/host/instructionmanager.go
  openshift/template.yaml
Labels: approved, lgtm

#920 MGMT-3615 Set machine network CIDR as a pointer in cluster CRD
  internal/controller/api/v1alpha1/cluster_types.go
  internal/controller/api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/controllers/cluster_controller.go
Labels: approved, lgtm

#921 MGMT-3622 Bump RHCOS 4.7 image to use 4.7.0-fc.2 instead of 4.7.0.-fc-0
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#922 MGMT-3618 Add progress info to event
  internal/cluster/cluster.go
Labels: approved, lgtm

#919 MGMT-3327 - Remove backwards compatibility code for listing ineligible disks
  internal/hardware/validator.go
  internal/hardware/validator_test.go
Labels: approved, lgtm

#911 MGMT-2976 create and upload minimal iso template
  cmd/main.go
  internal/isoeditor/rhcos.go
  internal/isoeditor/rhcos_test.go
  internal/isoutil/isoutil.go
  internal/isoutil/mock_isoutil.go
  pkg/s3wrapper/client.go
  pkg/s3wrapper/client_test.go
  pkg/s3wrapper/filesystem.go
  pkg/s3wrapper/filesystem_test.go
  pkg/s3wrapper/mock_s3wrapper.go
  pkg/s3wrapper/util.go
Labels: approved, lgtm

#924 MGMT-3620 Add RHCOS version as build id to be part of the S3 object name
  cmd/main.go
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  internal/assistedserviceiso/assistedserviceiso_api.go
  internal/assistedserviceiso/assistedserviceiso_api_test.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bootfiles/bootfiles.go
  internal/bootfiles/bootfiles_test.go
  internal/versions/mock_versions.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  models/openshift_version.go
  onprem-environment
  openshift/template.yaml
  pkg/s3wrapper/client.go
  pkg/s3wrapper/client_test.go
  pkg/s3wrapper/filesystem.go
  pkg/s3wrapper/filesystem_test.go
  pkg/s3wrapper/mock_s3wrapper.go
  pkg/s3wrapper/util_test.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#931 MGMT-2977 Allow downloading and caching from the public S3 bucket
  pkg/s3wrapper/client.go
  pkg/s3wrapper/file_cache.go
  pkg/s3wrapper/file_cache_test.go
  pkg/s3wrapper/filesystem.go
  pkg/s3wrapper/mock_s3wrapper.go
Labels: approved, lgtm

#929 NO-ISSUE Add format-check to Makefile
  Makefile
Labels: approved, lgtm

#933 NO-ISSUE Removes some extra whitespace and contexts from tests
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#930 MGMT-2977 Remove coreos.liveiso kernel param for the template minimal iso
  internal/isoeditor/rhcos.go
  internal/isoeditor/rhcos_test.go
Labels: approved, lgtm

#925 MGMT-3630 - Fix missing validation for minimum host valid disks
  internal/hardware/validator.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/installcmd.go
Labels: approved, lgtm

#935 NO-ISSUE Set get spec endpoint test as minimal set
  subsystem/spec_test.go
Labels: approved, lgtm

#934 Remove cluster name from event
  internal/cluster/cluster.go
Labels: approved, lgtm

#936 MGMT-3491 add swagger changes for additional OLM based services - fix
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  models/cluster.go
  models/operators.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#927 Changes for IPv6 single node
  cmd/main.go
  internal/bminventory/inventory.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/transition.go
  internal/common/common.go
  internal/installcfg/installcfg.go
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
  internal/network/mock_manifests_generator.go
  internal/network/mock_ntp_utils.go
  internal/network/utils.go
Labels: approved, lgtm

#885 MGMT-3442: Report metrics for host validation errors.
  go.mod
  go.sum
  internal/bminventory/inventory.go
  internal/cluster/cluster.go
  internal/host/host.go
  internal/host/mock_host_api.go
  internal/metrics/metricsManager.go
  internal/metrics/metricsManager_test.go
  internal/metrics/mock_metrics_manager_api.go
  subsystem/metrics_test.go
Labels: approved, lgtm

#937 MGMT-3446 Update Waiting for ignition timeout to 24 hours
  internal/host/host.go
  internal/host/transition_test.go
Labels: approved, lgtm

#940 MGMT-3680 Make IPv6 configuration be sent by ignition and not by manifest when not in single node
  internal/cluster/transition.go
  internal/common/common.go
  internal/ignition/ignition.go
  internal/network/manifests_generator.go
Labels: approved, lgtm

#941 NO-ISSUE: Removing metrics unit-tests.
  internal/metrics/metricsManager_test.go
Labels: approved, lgtm

#944 MGMT-3431 Support update CVO flag from env param
  Makefile
  deploy/assisted-service-configmap.yaml
  skipper.yaml
  tools/deploy_assisted_installer_configmap.py
Labels: approved, lgtm

#942 OCPBUGSM-23132 - Allow read-only-admin to call openshift_versions call
  pkg/auth/authz_handler_test.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#947 NO-ISSUE Add info logs to install and update progress apis
  internal/bminventory/inventory.go
Labels: approved, lgtm

#928 MGMT-3526 Add image_availability request and response objects
  models/container_image_availability.go
  models/container_image_availability_request.go
  models/container_image_availability_response.go
  models/container_image_availability_result.go
  models/step_type.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#943 MGMT-3691 Move IPv6 single IP configuration after pivot to use ignition instead of manifest
  internal/cluster/cluster_test.go
  internal/cluster/transition.go
  internal/ignition/ignition.go
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
  internal/network/mock_manifests_generator.go
Labels: approved, lgtm

#951 MGMT-3701 Update AI to use latest release image that support SNO
  internal/ignition/ignition.go
Labels: approved, lgtm

#949 MGMT-3714 Adds emailDomain pannel to cluster overview dashboard
  dashboards/grafana-dashboard-assisted-installer-cluster-overview.configmap.yaml
Labels: approved, lgtm

#953 MGMT-3717 support IPv6 config for DHCP in static ip scenario
  internal/ignition/ignition.go
Labels: approved, lgtm

#956 NO-ISSUE Extend on-prem installer startup timeout from 1m to 3m
  Makefile
Labels: approved, lgtm

#945 MGMT-3690 - Fix tests that never ran, add lint to prevent
  .golangci.yml
  internal/bminventory/inventory.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/transition_test.go
  internal/cluster/validations/validation_test.go
  internal/common/test_configuration.go
  internal/host/host_test.go
  internal/host/hostutil/test_utils.go
  internal/host/transition_test.go
  pkg/auth/auth_handler_test.go
  pkg/auth/authz_handler_test.go
  pkg/log/context_test.go
  pkg/requestid/requestid_test.go
  subsystem/image_test.go
Labels: approved, lgtm

#955 MGMT-3538 support cluster installation with kube-api
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/mock_installer_internal.go
  internal/cluster/cluster.go
  internal/controller/api/v1alpha1/cluster_types.go
  internal/controller/api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/config/crd/bases/adi.io.my.domain_clusters.yaml
  internal/controller/controllers/cluster_controller.go
  internal/controller/controllers/cluster_controller_test.go
Labels: approved, lgtm

#861 MGMT-3357 Host CRD
  internal/controller/api/v1alpha1/cluster_types.go
  internal/controller/api/v1alpha1/host_types.go
  internal/controller/api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/config/crd/bases/adi.io.my.domain_hosts.yaml
  internal/host/refresh_status_preprocessor.go
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, lgtm

#962 OCPBUGSM-23568 Generate default no proxy in install-config to avoid passing internal cluster communication through the proxy
  internal/installcfg/installcfg.go
  internal/installcfg/installcfg_test.go
Labels: approved, lgtm

#932 MGMT-2977 Cluster specific minimal iso
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/isoeditor/factory.go
  internal/isoeditor/mock_editor.go
  internal/isoeditor/mock_factory.go
  internal/isoeditor/rhcos.go
  internal/isoeditor/rhcos_test.go
  models/image_create_params.go
  models/image_info.go
  models/image_type.go
  pkg/s3wrapper/upload_iso.go
  pkg/s3wrapper/util.go
  subsystem/image_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#964 OCPBUGSM-23568 Generate default no proxy in install-config to avoid passing internal cluster communication through the proxy
  internal/installcfg/installcfg.go
  internal/installcfg/installcfg_test.go
Labels: approved, lgtm

#709 MGMT-2662 re-enable the baremetalProvisioningConfig
  internal/bminventory/inventory_test.go
  internal/common/version.go
  internal/ignition/ignition.go
  internal/installcfg/installcfg.go
Labels: approved, lgtm

#960 MGMT-3747 Filter ISO Generated data by openshift version
  dashboards/grafana-dashboard-assisted-installer-weekly-overview.configmap.yaml
Labels: approved, lgtm

#961 MGMT-3526 Add timeout, time, size and rate for the pull operation
  models/container_image_availability.go
  models/container_image_availability_request.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#958 MGMT-3510 Alter the static ip config script to work during boot
  internal/ignition/ignition.go
Labels: approved, lgtm

#970 Revert "MGMT-2662 re-enable the baremetalProvisioningConfig"
  internal/bminventory/inventory_test.go
  internal/common/version.go
  internal/ignition/ignition.go
  internal/installcfg/installcfg.go
Labels: approved, lgtm

#950 NO-ISSUE Fix format issues found by gosec, update format-check
  Makefile
  internal/cluster/cluster.go
  internal/isoeditor/rhcos.go
  internal/isoeditor/rhcos_test.go
  internal/isoutil/isoutil_test.go
  pkg/s3wrapper/client_test.go
  pkg/s3wrapper/filesystem_test.go
Labels: approved, lgtm

#971 MGMT-3763 - Fix misleading host progress error when cluster enters error state
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, lgtm

#952 MGMT-3658: Generate event/metric in case an host validation is changing.
  internal/host/host.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_metrics_manager_api.go
  subsystem/metrics_test.go
Labels: approved, lgtm

#972 MGMT-2622 - Add disk and user to event when booted into the ISO instead of into the installed OCP on disk
  internal/bminventory/inventory.go
  internal/host/transition.go
Labels: approved, lgtm

#974 NO-ISSUE Merge all agent sub-images into one
  cmd/main.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/instruction_manager.go
  internal/host/hostcommands/logs_cmd.go
  openshift/template.yaml
  tools/deploy_assisted_installer_configmap.py
Labels: approved, lgtm

#975 NO-ISSUE Update go-diskfs to include temp dir leak fix
  go.mod
  go.sum
Labels: approved, lgtm

#967 MGMT-3684 None-platform set machine network CIDR from bootstrap
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/installcfg/installcfg.go
  internal/installcfg/installcfg_test.go
Labels: approved, lgtm

#939 MGMT-3523 Reconcile Image when pull secret updated
  cmd/main.go
  go.sum
  internal/controller/controllers/cluster_controller.go
  internal/controller/controllers/error_utils.go
  internal/controller/controllers/image_controller.go
Labels: approved, lgtm

#984 Revert "MGMT-3658: Generate event/metric in case an host validation is changing."
  internal/host/host.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_metrics_manager_api.go
  subsystem/metrics_test.go
Labels: approved, lgtm

#977 MGMT-3608: Added cluster deregister when CRD is deleted
  internal/bminventory/inventory.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/controllers/cluster_controller.go
  internal/controller/controllers/cluster_controller_test.go
Labels: approved, lgtm

#989 NO-ISSUE: removing 'role-defined' validation-id.
  models/host_validation_id.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#990 MGMT-3837 Add cluster deployment controller
  cmd/main.go
  go.mod
  go.sum
  internal/controller/config/crd/bases/hive.openshift.io_clusterdeployments.yaml
  internal/controller/config/crd/kustomization.yaml
  internal/controller/config/rbac/role.yaml
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/controllers_suite_test.go
Labels: approved, lgtm

#968 MGMT-3362: Subsystem for kube api with basic installation test
  subsystem/kubeapi_test.go
  subsystem/subsystem_suite_test.go
Labels: approved, lgtm

#976 MGMT-3797, Bump OCP version from 4.6.8 to 4.6.12 (auto created)
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#986 MGMT-3510 Set static IP during boot in minimal iso
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/constants/scripts.go
  internal/ignition/ignition.go
  internal/isoeditor/mock_editor.go
  internal/isoeditor/rhcos.go
  internal/isoeditor/rhcos_test.go
  subsystem/image_test.go
Labels: approved, lgtm

#993 MGMT-3842 Substitute OPENSHIFT_VERSIONS parameter
  Makefile
Labels: approved, lgtm

#992 MGMT-3721 ClusterDeployments support delete
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, lgtm

#985 MGMT-3802 + MGMT-3299 Cluster fail if host is not responsive
  internal/host/common.go
  internal/host/statemachine.go
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, lgtm

#997 NO-ISSUE Add cache of dependencies before compilation in Dockerfile
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, lgtm
