Repository openshift/assisted-service, pull requests merged in 2021-07, with the labels that each got.

#2135 OCPBUGSM-31522: Bug 1976776: Change agent's ReadyForInstallation condition into RequirementsMet
  docs/hive-integration/README.md
  docs/hive-integration/kube-api-conditions.md
  internal/controller/api/v1beta1/agent_types.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#2042 MGMT-6908: Adding enhancement for installation-progress-bar.
  docs/enhancements/installation-progress-bar.md
Labels: approved, lgtm

#2131 OCPBUGSM-31584: added columns to Agent CRD
  config/crd/bases/agent-install.openshift.io_agents.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
  internal/controller/api/v1beta1/agent_types.go
Labels: approved, lgtm

#2140 NO-ISSUE: Add common module for operator deployment scripts
  deploy/operator/common.sh
  deploy/operator/deploy.sh
  deploy/operator/destroy.sh
  deploy/operator/gather.sh
  deploy/operator/setup_assisted_operator.sh
  deploy/operator/setup_hive.sh
  deploy/operator/utils.sh
  deploy/operator/ztp/deploy_spoke_cluster.sh
Labels: approved, lgtm

#2139 NO-ISSUE: Show full command on release.go execture error
  internal/oc/release.go
Labels: approved, lgtm

#2150 NO-ISSUE: Move live iso test out of image type loop
  subsystem/image_test.go
Labels: approved, lgtm

#2081 BUG 1970063: Don't force ca-bundle.crt when mirroring
  docs/operator.md
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/common.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2141 Bug 1975452: Fix spoke BMH provisioned registration error
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2132 Bug 1975491: Added network latency and packet loss to /host-requirements
  internal/bminventory/inventory.go
  models/host_requirements_role.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2146 Bug 1976983: Add docs explaining automatedCleaningMode overrides
  docs/hive-integration/baremetal-agent-controller.md
  docs/hive-integration/kube-api-getting-started.md
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2145 Bug 1977354: Move agent to different cluster same NS
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_crd_utils.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/crd_utils.go
  internal/controller/controllers/crd_utils_test.go
  internal/host/host.go
  internal/host/mock_host_api.go
  subsystem/kubeapi_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2154 OCPBUGSM-31176: Fail the installation if there is only 1 installed workers.
  docs/ClusterStatus.dot
  docs/ClusterStatus.png
  internal/cluster/cluster_test.go
  internal/cluster/common.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  subsystem/cluster_test.go
Labels: approved, lgtm

#2148 MGMT-5171: Disconnected IPv6 full worfklow
  deploy/operator/common.sh
  deploy/operator/deploy.sh
  deploy/operator/mirror_utils.sh
  deploy/operator/set_ca_bundle.py
  deploy/operator/setup_assisted_operator.sh
  deploy/operator/utils.sh
  deploy/operator/ztp/baremetalHost.j2
  deploy/operator/ztp/deploy_spoke_cluster.sh
Labels: approved, lgtm

#2152 Bug 1978744: Add docs explaining automatedCleaningMode overrides
  docs/hive-integration/baremetal-agent-controller.md
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2161 MGMT-5171: Call set_ca_bundle.py script from the correct path
  deploy/operator/common.sh
  deploy/operator/setup_assisted_operator.sh
Labels: approved, lgtm

#2164 MGMT-7144: Add verbose flag for tests
  Jenkinsfile
  Makefile
  README.md
  skipper.env
Labels: approved, lgtm

#2163 MGMT-7152: Adding verbose printing for ginkgo.
  Makefile
  subsystem/metrics_test.go
Labels: approved, lgtm

#2157 Bug 1975529: Remove unmet requirement message from log
  internal/operators/cnv/cnv_operator.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#2153 MGMT-7142: Bump OCP versions 4.7.16 -> 4.7.18, 4.8.0-rc.1 -> 4.8.0-rc.2
  config/manager/manager.yaml
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_ocp_versions.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#2137 Bug 1965117: Keep assisted-service configmap mount updated
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/common.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1879 MGMT-6663: Make an event for any operator status change
  internal/operators/handler/handler.go
  internal/operators/handler/handler_test.go
Labels: approved, lgtm

#1992 Bug 1937696: Use hostname for BMH resource name
  internal/installcfg/installcfg.go
  internal/installcfg/installcfg_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#2165 MGMT-5171: Fix quotes on setup_assisted_operator.sh
  deploy/operator/setup_assisted_operator.sh
Labels: approved, lgtm

#2166 MGMT-7163: Bump OCP versions 4.8.0-rc.2 -> 4.8.0-rc.3
  config/manager/manager.yaml
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_ocp_versions.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#2091 MGMT-7083: Add additional timestamp to trigger monitoring and replace updated-at field with this timestamp for selective monitoring
  internal/bminventory/inventory.go
  internal/cluster/cluster_test.go
  internal/cluster/common.go
  internal/common/db.go
  internal/common/monitor_query_generator.go
  internal/host/common.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostutil/update_host.go
  internal/host/transition.go
Labels: approved, lgtm

#2159 NO-ISSUE: Enable Day 2 cluster in kube api
  Makefile
  docs/hive-integration/README.md
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#2169 NO-ISSUE: kubeAPI subsystem tests: decouple ACI and ClusterImageSet Creation
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#2173 Bug 1978739: Fix requeue logic inside mapInfraEnvToBMH
  internal/controller/controllers/bmh_agent_controller.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, kind/dependency-change, lgtm, size/S

#2182 MGMT-7054: Mark iso download tests as pending
  subsystem/image_test.go
Labels: approved, lgtm, size/XS

#2179 Bug 1979906: Fix requeue logic inside mapInfraEnvToBMH
  internal/controller/controllers/bmh_agent_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, size/S

#2178 MGMT-7189: Bump OCP versions rchos 4.8.0-fc.3 -> 4.8.0-rc.3
  config/manager/manager.yaml
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_ocp_versions.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm, size/M

#2162 Bug 1979169: Clarify documenation about automatedCleaningMode
  docs/hive-integration/baremetal-agent-controller.md
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2115 OCPBUGSM-29517: use UsableBytes instead of PhysicalBytes
  internal/host/hostutil/test_utils.go
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, lgtm, size/S

#2185 MGMT-5171: Mirror all available ICSP on script
  deploy/operator/setup_assisted_operator.sh
Labels: approved, lgtm, size/XS

#2160 MGMT-6961: optional argument to cluster_list REST API
  client/installer/list_clusters_parameters.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  restapi/embedded_spec.go
  restapi/operations/installer/list_clusters_parameters.go
  restapi/operations/installer/list_clusters_urlbuilder.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: api-review, approved, lgtm, size/L

#2170 OCPBUGSM-30766: Removing "Unauthorized access to cluster *" log.
  pkg/auth/rhsso_authenticator.go
Labels: approved, lgtm, size/XS

#2124 MGMT-7121: Add vsphere platform support to install-config.yaml
  internal/installcfg/installcfg.go
Labels: approved, lgtm, size/S

#2184 Bug 1978691: Fix osImages reference passing
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm, size/M

#2186 MGMT-4179: Move KubeAPI types to under the top-level directory
  PROJECT
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  api/hiveextension/v1beta1/groupversion_info.go
  api/hiveextension/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/agent_types.go
  api/v1beta1/agentserviceconfig_types.go
  api/v1beta1/groupversion_info.go
  api/v1beta1/infraenv_types.go
  api/v1beta1/nmstate_config_types.go
  api/v1beta1/nmstate_util.go
  api/v1beta1/zz_generated.deepcopy.go
  cmd/operator/main.go
  docs/hive-integration/README.md
  hack/generate.sh
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/agentclusterinstall_controller.go
  internal/controller/controllers/agentclusterinstall_controller_test.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/common.go
  internal/controller/controllers/controllers_suite_test.go
  internal/controller/controllers/crd_utils.go
  internal/controller/controllers/crd_utils_test.go
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  subsystem/kubeapi_test.go
  subsystem/subsystem_suite_test.go
Labels: approved, lgtm, size/M

#2190 NO-ISSUE: Don't lint swagger for now to make tests green
  hack/generate.sh
  hack/setup_env.sh
Labels: approved, lgtm, size/XS

#2192 NO-ISSUE: Use spectral image directly when needed
  hack/generate.sh
  hack/setup_env.sh
Labels: approved, lgtm, size/S

#2171 OCPBUGSM-31691: Add Machine net CIDR to ACI status
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  api/hiveextension/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  internal/controller/controllers/clusterdeployments_controller.go
Labels: approved, lgtm, size/M

#2189 OCPBUGSM-31903: Match 4.7 rootfs with iso version
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_ocp_versions.json
  onprem-environment
  openshift/template.yaml
  pkg/s3wrapper/util.go
Labels: approved, lgtm, size/S

#2112 Bug 1966586: 200 OK returned when setting invalid BaseDNSdomain via API
  internal/dns/dns.go
  subsystem/cluster_test.go
Labels: api-review, approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, size/M

#2193 MGMT-7170: Adapt connectivity groups to support L3 connectivity
  internal/cluster/cluster.go
  internal/network/connectivity_groups.go
  internal/network/connectivity_groups_test.go
Labels: approved, lgtm, size/XL

#2183 MGMT-7136: Add metric report to all installation complete scenarios
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_metrics_manager_api.go
Labels: approved, lgtm, size/M

#2198 NO-ISSUE: Fix spectral linter
  hack/generate.sh
  hack/setup_env.sh
Labels: approved, lgtm, size/XS

#2194 OCPBUGSM-30272: Clear ACI LogsURL and EventsURL in ClusterConditionsUnknown
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, lgtm, size/M

#2201 NO-ISSUE: Remove deprecated IMAGE_BUILDER var
  openshift/template.yaml
Labels: approved, lgtm, size/XS

#2197 MGMT-5171: Mirror only assisted index image
  deploy/operator/mirror_utils.sh
  deploy/operator/setup_assisted_operator.sh
  deploy/operator/setup_lso.sh
Labels: approved, lgtm, size/M

#2202 NO-ISSUE: Fix CI issues
  Dockerfile.bundle
  Dockerfile.test
  config/crd/bases/agent-install.openshift.io_agents.yaml
  config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
  config/crd/bases/agent-install.openshift.io_infraenvs.yaml
  config/crd/bases/agent-install.openshift.io_nmstateconfigs.yaml
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  hack/generate.sh
  hack/setup_env.sh
Labels: approved, kind/dependency-change, lgtm, size/XL

#2205 MGMT-5171: Mirror OCP release repositories instead of namespaces
  deploy/operator/setup_assisted_operator.sh
Labels: approved, lgtm, size/XS

#2211 NO-ISSUE: Add dependabot.yml file
  .github/dependabot.yml
Labels: approved, lgtm, size/M

#2206 MGMT-7212: Fix crash in PostRefreshCluster
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  subsystem/metrics_test.go
Labels: approved, lgtm, size/S

#2200 MGMT-7136: Add metric report to all installation complete scenarios …
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_metrics_manager_api.go
  subsystem/metrics_test.go
Labels: approved, lgtm, size/M

#2196 Multiple issues: MGMT-7195, MGMT-7208
  internal/cluster/cluster.go
  internal/host/transition_test.go
  internal/host/validator.go
  internal/network/utils.go
Labels: approved, lgtm, size/L

#2210 MGMT-7111: DISABLED_STEPS environment variable
  Makefile
  deploy/assisted-service-configmap.yaml
  internal/host/hostcommands/instruction_manager.go
  internal/host/hostcommands/instruction_manager_test.go
  openshift/template.yaml
  skipper.env
  tools/deploy_assisted_installer_configmap.py
Labels: approved, lgtm, size/L

#2219 NO-ISSUE: Make dependabot commits prefixed with NO-ISSUE
  .github/dependabot.yml
Labels: approved, lgtm, size/XS

#2220 MGMT-7228: Add AgentClusterInstall shortName aci
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
Labels: approved, lgtm, size/XS

#2225 NO-ISSUE: Update document
  docs/operator.md
Labels: approved, lgtm, size/XS

#2227 MGMT-7154: Flaky test: Host tests next step - DHCP
  subsystem/host_test.go
Labels: approved, lgtm, size/S

#2209 OCPBUGSM-25122: Unexpected host api-vip validation before setting network parameters
  internal/host/refresh_status_preprocessor.go
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, lgtm, size/M

#2230 NO-ISSUE: Force minimal iso template update
  pkg/s3wrapper/util.go
Labels: approved, lgtm, size/XS

#2207 MGMT-7214: Add InfraEnv model
  client/installer/installer_client.go
  client/installer/v2_register_infra_env_parameters.go
  client/installer/v2_register_infra_env_responses.go
  internal/bminventory/inventory.go
  internal/common/db.go
  mocks/mock_assisted_service.go
  models/host.go
  models/infra_env.go
  models/infra_env_list.go
  models/infraenv_create_params.go
  models/proxy.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_register_infra_env.go
  restapi/operations/installer/v2_register_infra_env_parameters.go
  restapi/operations/installer/v2_register_infra_env_responses.go
  restapi/operations/installer/v2_register_infra_env_urlbuilder.go
  swagger.yaml
Labels: api-review, approved, lgtm, size/XXL

#2098 Bug 1974085: fixes network&latency host validations
  internal/host/common.go
  internal/host/hostutil/test_utils.go
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, size/L

#2223 Bug 1980901: Gateway is '<nil>' in route
  internal/host/validator.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, size/XS

#2226 MGMT-7054: Use a network LB to avoid download issue
  deploy/assisted-service-service.yaml
  subsystem/image_test.go
Labels: approved, lgtm, size/XS

#2228 NO-ISSUE: Removing Install() method from cluster's API.
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/installer.go
  internal/cluster/installer_test.go
  internal/cluster/mock_cluster_api.go
Labels: approved, lgtm, size/L

#2229 MGMT-7086 Migrate existing cluster to InfraEnv
  cmd/main.go
  internal/common/db.go
  internal/migrations/20201019194303_change_overrides_to_text_test.go
  internal/migrations/20201202140700_change_image_ssh_key_text_test.go
  internal/migrations/20210218160100_validations_info_to_text_test.go
  internal/migrations/20210223090000_host_validations_info_to_text_test.go
  internal/migrations/20210713123129_populate_infra_env.go
  internal/migrations/20210713123129_populate_infra_env_test.go
  internal/migrations/migrations.go
  internal/migrations/migrations_suite_test.go
  internal/migrations/migrations_test.go
Labels: api-review, approved, lgtm, size/L

#2203 MGMT-7210 Upgrade Go version to 1.16
  Dockerfile.assisted-service
  Dockerfile.assisted-service-build
  Dockerfile.assisted-service-debug
  Dockerfile.bundle
  Dockerfile.test
  go.mod
Labels: approved, kind/dependency-change, lgtm, size/S

#2237 MGMT-7286: Bump OCP versions 4.7.18 -> 4.7.19
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_ocp_versions.json
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm, size/S

#2221 MGMT-6977: Make sure that preparing for installation timeout is more than the tools timeouts
  cmd/main.go
  internal/host/hostcommands/container_image_availability_cmd.go
  internal/host/hostcommands/container_image_availability_cmd_test.go
  internal/host/hostcommands/instruction_manager.go
Labels: approved, lgtm, size/M

#2113 MGMT-6768: Allow users to choose between SDN or OVN network types
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster_test.go
  internal/cluster/refresh_status_preprocessor.go
  internal/cluster/statemachine.go
  internal/cluster/transition_test.go
  internal/cluster/validation_id.go
  internal/cluster/validator.go
  internal/installcfg/installcfg.go
  internal/installcfg/installcfg_test.go
  internal/operators/ocs/validation_test.go
  models/cluster.go
  models/cluster_create_params.go
  models/cluster_update_params.go
  models/cluster_validation_id.go
  restapi/embedded_spec.go
  subsystem/ipv6_test.go
  swagger.yaml
Labels: api-review, approved, lgtm, size/XL

#2231 NO-ISSUE: Remove unused srcStatus from updateLogsProgress func
  internal/cluster/cluster.go
  internal/cluster/common.go
  internal/cluster/transition.go
Labels: approved, lgtm, size/XS

#2240 MGMT-7288 Add degraded cluster event for failed OLM operators
  internal/cluster/transition.go
Labels: approved, lgtm, size/XS

#2244 MGMT-7086: Migrate data from Cluster to IngraEnv
  internal/migrations/20210713123129_populate_infra_env.go
  internal/migrations/20210713123129_populate_infra_env_test.go
Labels: approved, lgtm, size/XS

#2243 MGMT-7287: Monitor user selection of networkType by setting usage whe…
  internal/bminventory/inventory.go
  internal/usage/consts.go
Labels: approved, lgtm, size/XS

#2075 MGMT-4540: Support schedulable masters cluster property
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/common/common.go
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
  internal/network/mock_manifests_generator.go
  models/cluster.go
  models/cluster_create_params.go
  models/cluster_update_params.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: api-review, approved, lgtm, ok-to-test, size/L

#2235 MGMT-5302: Removing deprecated /host_requirements endpoint and related…
  client/installer/get_host_requirements_parameters.go
  client/installer/get_host_requirements_responses.go
  client/installer/installer_client.go
  internal/bminventory/inventory.go
  internal/hardware/mock_validator.go
  internal/hardware/validator.go
  mocks/mock_assisted_service.go
  models/host_requirements.go
  models/host_requirements_role.go
  pkg/auth/auth_assisted_service_mock_test.go
  pkg/auth/authz_handler_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/get_host_requirements.go
  restapi/operations/installer/get_host_requirements_parameters.go
  restapi/operations/installer/get_host_requirements_responses.go
  restapi/operations/installer/get_host_requirements_urlbuilder.go
  swagger.yaml
Labels: api-review, approved, lgtm, size/XXL

#2175 MGMT-7104: Add new API for updating VMWare credentials in the assisted service
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/installcfg/installcfg.go
  internal/installcfg/installcfg_test.go
  models/cluster.go
  models/cluster_update_params.go
  models/platform.go
  models/platform_type.go
  models/vsphere_platform.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm, size/XL

#2246 MGMT-7297: Add view agent logs command to the agent message of the day
  internal/ignition/ignition.go
Labels: approved, lgtm, size/XS

#2253 MGMT-7306: Use local CI image for spectral if it is available
  hack/generate.sh
Labels: approved, lgtm, size/XS

#2252 NO-ISSUE: Filter out Clusterdeployments from non-relevant namespaces
  internal/controller/controllers/clusterdeployments_controller.go
Labels: approved, lgtm, size/XS

#2254 MGMT-7308: Increase timeout for agents in ZTP flow
  deploy/operator/ztp/deploy_spoke_cluster.sh
Labels: approved, lgtm, size/XS

#2232 MGMT-7235 - change AI implementation to use InfraEnv instead of Image…
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/auth.go
  internal/cluster/auth_test.go
  internal/cluster/cluster_test.go
  internal/cluster/common_test.go
  internal/cluster/installer_test.go
  internal/cluster/transition_test.go
  internal/common/common.go
  internal/common/db.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/controller_event_wrapper_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostutil/test_utils.go
  internal/host/transition_test.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/ignition/mock_ignition.go
  internal/migrations/20210223090000_host_validations_info_to_text_test.go
  internal/migrations/20210713123129_populate_infra_env.go
  internal/migrations/20210713123129_populate_infra_env_test.go
  internal/network/manifests_generator_test.go
  internal/operators/ocs/validation_test.go
  models/host.go
  pkg/mirrorregistries/generator_test.go
  restapi/embedded_spec.go
  subsystem/ams_subscriptions_test.go
  subsystem/cluster_test.go
  subsystem/day2_cluster_test.go
  subsystem/host_test.go
  subsystem/ipv6_test.go
  subsystem/kubeapi_test.go
  subsystem/metrics_test.go
  subsystem/operators_test.go
  subsystem/utils_test.go
  swagger.yaml
Labels: api-review, approved, lgtm, size/XXL

#1838 NO-ISSUE Enhancement for late binding
  docs/enhancements/agent-late-binding.md
Labels: approved, lgtm, size/L

#2256 NO-ISSUE: download binaries instead of using docker-hub
  hack/generate.sh
  hack/setup_env.sh
Labels: approved, do-not-merge/hold, lgtm, size/S

#1679 OCPBUGSM-28683: Enable pprof when running in debug mode
  .golangci.yml
  Dockerfile.assisted-service
  cmd/main.go
Labels: approved, kind/dependency-change, lgtm, size/S

#2259 MGMT-5171: Mirror OCP release image to a single repository
  deploy/operator/deploy.sh
  deploy/operator/mirror_utils.sh
  deploy/operator/setup_assisted_operator.sh
Labels: approved, lgtm, size/S

#2241 OCPBUGSM-31406: Validate log collection before displaying LogsURL
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm, size/L

#2248 Bug 1974077: Missing source hostname in validation error
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, size/S

#2251 Bug 1983412: Wrong validation status for network&packet loss
  internal/host/validator.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, size/S

#2261 OCPBUGSM-31996: Preparing for Installation failed with message: Failed to prepare the installation due to an unexpected error. Please retry later
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
Labels: approved, lgtm, size/M

#2257 MGMT-7141: Add VMWare to feature_usage
  internal/bminventory/inventory.go
  internal/usage/consts.go
Labels: approved, lgtm, size/S

#2264 NO-ISSUE update ginko version and add logs to kube-api subsystem tests
  go.mod
  go.sum
  subsystem/kubeapi_test.go
Labels: approved, lgtm, size/M

#2187 MGMT-7085: Add metrics network latency packet loss
  internal/host/common_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/validator.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_metrics_manager_api.go
  subsystem/cluster_test.go
  subsystem/day2_cluster_test.go
  subsystem/ipv6_test.go
  subsystem/kubeapi_test.go
  subsystem/metrics_test.go
  subsystem/utils_test.go
Labels: approved, lgtm, size/XL

#2262 NO-ISSUE: Fix validations package mocking
  hack/generate.sh
  hack/setup_env.sh
  internal/cluster/validations/mock_validations.go
  internal/cluster/validations/validations.go
  internal/garbagecollector/mock_garbageCollector.go
  pkg/externalmocks/mock_kube_client.go
Labels: approved, lgtm, size/XL

#2234 MGMT-7262: Create a ServiceMonitor when deploying Assisted Service
  cmd/operator/main.go
  config/rbac/role.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/common.go
Labels: approved, lgtm, size/L

#2144 NO-ISSUE: enhancement proposal to avoid agent reboots
  docs/enhancements/bmac-reboot-hosts-on-iso-change.md
Labels: approved, lgtm, size/L

#2208 MGMT-7197: Implementing cluster's installation progress bar in BE.
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/mock_cluster_api.go
  internal/cluster/progress_test.go
  internal/cluster/transition.go
  internal/common/db.go
  internal/host/common.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/mock_host_api.go
  internal/operators/handler/handler.go
  internal/operators/handler/handler_test.go
  models/cluster.go
  models/cluster_progress_info.go
  models/host_progress_info.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: api-review, approved, lgtm, size/XL

#2271 MGMT-7319 remove ntp validation from kube-api test
  subsystem/kubeapi_test.go
Labels: approved, lgtm, size/S

#2273 OCPBUGSM-32244: Bugfix ListClusters for admin role
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm, size/L

#2265 MGMT-7219: Add internal API to transform a cluster from day1 to day2
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/mock_cluster_api.go
Labels: approved, lgtm, size/L

#2269 Multiple issues for late binding agent APIs:
  client/installer/installer_client.go
  client/installer/v2_get_host_parameters.go
  client/installer/v2_get_host_responses.go
  client/installer/v2_get_next_steps_parameters.go
  client/installer/v2_get_next_steps_responses.go
  client/installer/v2_post_step_reply_parameters.go
  client/installer/v2_post_step_reply_responses.go
  client/installer/v2_register_host_parameters.go
  client/installer/v2_register_host_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/db.go
  internal/host/hostcommands/v2_next_step_runner_cmd.go
  internal/migrations/20210713123129_populate_infra_env_test.go.disable
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_get_host.go
  restapi/operations/installer/v2_get_host_parameters.go
  restapi/operations/installer/v2_get_host_responses.go
  restapi/operations/installer/v2_get_host_urlbuilder.go
  restapi/operations/installer/v2_get_next_steps.go
  restapi/operations/installer/v2_get_next_steps_parameters.go
  restapi/operations/installer/v2_get_next_steps_responses.go
  restapi/operations/installer/v2_get_next_steps_urlbuilder.go
  restapi/operations/installer/v2_post_step_reply.go
  restapi/operations/installer/v2_post_step_reply_parameters.go
  restapi/operations/installer/v2_post_step_reply_responses.go
  restapi/operations/installer/v2_post_step_reply_urlbuilder.go
  restapi/operations/installer/v2_register_host.go
  restapi/operations/installer/v2_register_host_parameters.go
  restapi/operations/installer/v2_register_host_responses.go
  restapi/operations/installer/v2_register_host_urlbuilder.go
  swagger.yaml
Labels: api-review, approved, lgtm, size/XXL

#2275 MGMT-7358: change host validation to support infra env
  internal/hardware/mock_validator.go
  internal/hardware/validator.go
  internal/host/conditions.go
  internal/host/hostutil/test_utils.go
  internal/host/refresh_status_preprocessor.go
  internal/host/validator.go
Labels: approved, lgtm, size/L

#2283 NO-ISSUE fix panic in host reference
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, lgtm, size/S

#2278 MGMT-7343: Increase s3 pod volume size
  deploy/s3/pvc.yaml
Labels: approved, lgtm, size/XS

#2285 NO-ISSUE: remove unused params from cd controller functions
  internal/controller/controllers/clusterdeployments_controller.go
Labels: approved, lgtm, size/S

#2268 MGMT-7356: Bump OCP versions 4.8.0-rc.3 -> 4.8.2
  config/manager/manager.yaml
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_ocp_versions.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm, size/M

#2281 MGMT-6897: Add install_config_network field to cluster
  models/cluster.go
  models/cluster_create_params.go
  models/cluster_network.go
  models/cluster_update_params.go
  models/machine_network.go
  models/network_configuration.go
  models/service_network.go
  models/subnet.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm, size/XL

#2277 MGMT-7374: Issue a single cluster log collection event
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm, size/S

#1661 MGMT-4561 Add MCS certificate to worker's pointer ignition on installation start
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, lgtm, size/L

#2276 MGMT-7268: Remove SupportFreeAddresses
  cmd/main.go
  internal/host/hostcommands/free_addresses_cmd.go
  internal/host/hostcommands/free_addresses_cmd_test.go
  internal/host/hostcommands/instruction_manager.go
  internal/host/hostcommands/instruction_manager_test.go
Labels: approved, lgtm, ok-to-test, size/L

#2287 NO-ISSUE: Deploy MinIO as a LoadBalancer
  deploy/s3/deployment.yaml
Labels: approved, lgtm, size/XS

#2255 MGMT-6750: Automate community-operator updates
  Makefile
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  hack/generate.sh
  hack/operator-release.sh
Labels: approved, lgtm, size/L

#1884 MGMT-6425 Add validation for API DNS name resolution
  internal/bminventory/inventory.go
  internal/common/test_configuration.go
  internal/constants/files.go
  internal/host/host.go
  internal/host/hostcommands/domain_name_resolution_cmd.go
  internal/host/hostcommands/domain_name_resolution_cmd_test.go
  internal/host/hostcommands/instruction_manager.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/host/mock_host_api.go
  internal/host/refresh_status_preprocessor.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/host/validator.go
  models/host.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm, ok-to-test, size/L

#2284 MGMT-7377: Remove auto-assign param and set default to SDN for network…
  internal/bminventory/inventory_test.go
  internal/cluster/validator.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/installcfg/installcfg.go
  internal/installcfg/installcfg_test.go
  models/cluster.go
  models/cluster_create_params.go
  models/cluster_update_params.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm, size/L

#2270 NO-ISSUE: Adding BE progress for day2 hosts.
  internal/bminventory/inventory.go
  internal/host/host.go
  internal/host/host_test.go
  subsystem/day2_cluster_test.go
Labels: approved, lgtm, size/L

#2288 MGMT-7382: Delete clusters using REST API on subsystem tests
  subsystem/kubeapi_test.go
  subsystem/metrics_test.go
  subsystem/utils_test.go
Labels: approved, lgtm, size/M

#2236 MGMT-7280: Add API for getting the hosts supported platforms
  client/installer/get_cluster_supported_platforms_parameters.go
  client/installer/get_cluster_supported_platforms_responses.go
  client/installer/installer_client.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/common/platforms.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/get_cluster_supported_platforms.go
  restapi/operations/installer/get_cluster_supported_platforms_parameters.go
  restapi/operations/installer/get_cluster_supported_platforms_responses.go
  restapi/operations/installer/get_cluster_supported_platforms_urlbuilder.go
  swagger.yaml
Labels: api-review, approved, lgtm, size/XXL

#2295 Bug 1975383: Update the defaultChronyConf
  internal/network/manifests_generator.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm, ok-to-test, size/XS

#2286 OCPBUGSM-32293: Cache only required secrets
  cmd/main.go
  config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agentserviceconfigs.yaml
  go.mod
  go.sum
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/common.go
Labels: approved, lgtm, size/XL

#2289 NO-ISSUE: Move 4.8 support_level from beta to production
  config/manager/manager.yaml
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_ocp_versions.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  internal/versions/versions_test.go
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm, size/S

#2294 MGMT-4492: Removing WITH_AMS_SUBSCRIPTIONS env variable.
  Makefile
  deploy/assisted-service-configmap.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/controller/controllers/agentserviceconfig_controller.go
  openshift/template.yaml
  pkg/ocm/client.go
  skipper.env
  subsystem/ams_subscriptions_test.go
  subsystem/cluster_test.go
  subsystem/subsystem_suite_test.go
  tools/deploy_assisted_installer_configmap.py
Labels: approved, lgtm, size/M

#2293 MGMT-7333 Add a HoldInstallation flag to AgentClusterInstall
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  docs/hive-integration/kube-api-conditions.md
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, lgtm, size/L

#2304 Revert "MGMT-7280: Add API for getting the hosts supported platforms"
  client/installer/get_cluster_supported_platforms_parameters.go
  client/installer/get_cluster_supported_platforms_responses.go
  client/installer/installer_client.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/common/platforms.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/get_cluster_supported_platforms.go
  restapi/operations/installer/get_cluster_supported_platforms_parameters.go
  restapi/operations/installer/get_cluster_supported_platforms_responses.go
  restapi/operations/installer/get_cluster_supported_platforms_urlbuilder.go
  swagger.yaml
Labels: api-review, approved, lgtm, size/XXL

#2296 MGMT-7093: implement pool image state machine and instruction manager
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster_test.go
  internal/cluster/common_test.go
  internal/cluster/installer_test.go
  internal/cluster/progress_test.go
  internal/cluster/transition_test.go
  internal/common/db.go
  internal/connectivity/validator_test.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/controller_event_wrapper_test.go
  internal/controller/controllers/crd_utils.go
  internal/controller/controllers/crd_utils_test.go
  internal/hardware/validator_test.go
  internal/host/common.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostcommands/api_vip_connectivity_check_cmd_test.go
  internal/host/hostcommands/connectivity_check_cmd_test.go
  internal/host/hostcommands/connectivity_check_convertor_test.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/instruction_manager.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/host/hostcommands/logs_cmd.go
  internal/host/hostutil/host_utils.go
  internal/host/hostutil/test_utils.go
  internal/host/hostutil/update_host.go
  internal/host/hostutil/update_host_test.go
  internal/host/monitor_test.go
  internal/host/pool_host_statemachine.go
  internal/host/statemachine.go
  internal/host/transition.go
  internal/host/transition_test.go
  internal/host/validator.go
  internal/installcfg/installcfg_test.go
  internal/migrations/20210223090000_host_validations_info_to_text_test.go
  internal/migrations/20210713123129_populate_infra_env_test.go.disable
  internal/network/manifests_generator_test.go
  internal/operators/ocs/validation_test.go
  models/host.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  subsystem/utils_test.go
  swagger.yaml
Labels: api-review, approved, lgtm, size/XXL

#2290 MGMT-6735: Add configurations for multi node spoke in ZTP
  deploy/operator/utils.sh
  deploy/operator/ztp/agentClusterInstall.j2
  deploy/operator/ztp/assisted-installer-crds-playbook.yaml
  deploy/operator/ztp/deploy_spoke_cluster.sh
Labels: approved, lgtm, size/M

#2311 NO-ISSUE: fix operator image version
  config/manager/manager.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/XS

#2263 MGMT-4893: MUST_GATHER_IMAGES env var
  Makefile
  data/default_must_gather_versions.json
  deploy/assisted-service-configmap.yaml
  hack/generate.sh
  openshift/template.yaml
  tools/deploy_assisted_installer_configmap.py
Labels: approved, lgtm, size/S

#2310 MGMT-7362: Change to infa env id from cluster id in discovery ignition
  internal/ignition/ignition.go
Labels: approved, lgtm, size/XS

#2303 MGMT-7398: Bump OCP versions 4.7.19 -> 4.7.21
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_ocp_versions.json
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm, size/S

#2267 MGMT-7250: Generate discovery ignition on demand
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
Labels: approved, lgtm, size/M

#2312 Fix gathering of operator after operator rename
  deploy/operator/gather.sh
Labels: approved, lgtm, size/XS
