Repository openshift/assisted-service, pull requests merged in 2021-08, with the labels that each got.

#2301 [ocm-2.3] Bug 1986081: Cache only required secrets (#2286)
  cmd/main.go
  config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agentserviceconfigs.yaml
  go.mod
  go.sum
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/common.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm, size/XL

#2308 Bug 1987250: Remove diskEligible check for OCS
  internal/operators/manager_test.go
  internal/operators/ocs/ocs_operator_test.go
  internal/operators/ocs/validation_test.go
  internal/operators/ocs/validations.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, ok-to-test, size/L

#2297 MGMT-7389: Create cluster with a platform
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  models/cluster_create_params.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm, size/L

#2306 MGMT-7280: add API for getting the hosts supported platforms
  client/installer/get_cluster_supported_platforms_parameters.go
  client/installer/get_cluster_supported_platforms_responses.go
  client/installer/installer_client.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/common/inventory.go
  internal/common/platforms.go
  internal/host/common.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostutil/host_utils.go
  internal/host/transition_test.go
  internal/host/validator.go
  internal/network/connectivity_groups.go
  internal/network/utils.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/cnv/cnv_operator_test.go
  internal/operators/manager_test.go
  internal/operators/ocs/ocs_operator.go
  internal/operators/ocs/validations.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/get_cluster_supported_platforms.go
  restapi/operations/installer/get_cluster_supported_platforms_parameters.go
  restapi/operations/installer/get_cluster_supported_platforms_responses.go
  restapi/operations/installer/get_cluster_supported_platforms_urlbuilder.go
  subsystem/host_test.go
  swagger.yaml
Labels: api-review, approved, lgtm, size/XXL

#2247 MGMT-4893: Add Must Gather Image map
  cmd/main.go
  internal/host/hostcommands/container_image_availability_cmd.go
  internal/host/hostcommands/container_image_availability_cmd_test.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/versions/mock_versions.go
  internal/versions/versions.go
  internal/versions/versions_test.go
Labels: approved, lgtm, size/L

#2314 MGMT-7321: Move the AI code to address the host using its IfraEnvID i…
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/db.go
  internal/hardware/validator_test.go
  internal/host/common.go
  internal/host/common_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostcommands/api_vip_connectivity_check_cmd_test.go
  internal/host/hostcommands/connectivity_check_cmd_test.go
  internal/host/hostcommands/connectivity_check_convertor_test.go
  internal/host/hostcommands/container_image_availability_cmd_test.go
  internal/host/hostcommands/dhcp_allocate_cmd_test.go
  internal/host/hostcommands/disk_performance_cmd_test.go
  internal/host/hostcommands/domain_name_resolution_cmd_test.go
  internal/host/hostcommands/free_addresses_cmd_test.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/host/hostcommands/inventory_cmd_test.go
  internal/host/hostcommands/logs_cmd_test.go
  internal/host/hostcommands/reset_installation_cmd_test.go
  internal/host/hostcommands/stop_installation_cmd_test.go
  internal/host/hostutil/test_utils.go
  internal/host/hostutil/update_host.go
  internal/host/hostutil/update_host_test.go
  internal/host/monitor_test.go
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, lgtm, size/XXL

#2307 Organize update network params
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm, size/XL

#2282 Bug 1985449: Use report variable for unmarshaling
  internal/host/host.go
  internal/metrics/metricsManager.go
  subsystem/metrics_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm, size/M

#2322 MGMT-7424: Remove undeeded network validations for day2 hosts
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/validator.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm, size/M

#2313 OCPBUGSM-32618: Create worker's spoke machines in the "openshift-machine-api" namespace
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, lgtm, size/S

#2327 NO-ISSUE: Making agent discovered message more informative.
  deploy/operator/ztp/deploy_spoke_cluster.sh
Labels: approved, lgtm, size/XS

#2274 MGMT-7331: Validate host platform
  internal/bminventory/inventory_test.go
  internal/common/platform.go
  internal/host/host_test.go
  internal/host/hostutil/test_utils.go
  internal/host/refresh_status_preprocessor.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/host/validator.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm, size/XL

#2329 wait 1.5 hours for installation
  deploy/operator/ztp/deploy_spoke_cluster.sh
Labels: approved, lgtm, size/XS

#2330 Wait for the 'stopped' condition to save time on early failure
  deploy/operator/ztp/deploy_spoke_cluster.sh
Labels: approved, lgtm, size/XS

#2332 NO-ISSUE: KubeAPI subsystem cleanUpCRs to assert via Eventually
  subsystem/kubeapi_test.go
Labels: approved, lgtm, size/S

#2334 MGMT-7445: During update-cluster CIDRs are checked for overlap even if they were not provided as part of the update
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm, size/M

#2323 MGMT-7426: Allow installing on OpenStack in case of userManagedNetwor…
  internal/host/hostutil/test_utils.go
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, lgtm, size/M

#2336 MGMT-6735: Update ZTP script to allow for multiple baremetal hosts
  deploy/operator/ztp/assisted-installer-crds-playbook.yaml
  deploy/operator/ztp/baremetalHost.j2
  deploy/operator/ztp/deploy_spoke_cluster.sh
Labels: approved, size/M, lgtm

#2338 MGMT-4893: Support must gather images in kube-api
  api/v1beta1/agentserviceconfig_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
  config/crd/resources.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agentserviceconfigs.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/images.go
Labels: approved, size/L, lgtm

#2318 MGMT-6768: Add NetworkType to KubeAPI
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, lgtm

#2347 MGMT-7466: add V2 update host progress API
  client/installer/installer_client.go
  client/installer/v2_update_host_install_progress_parameters.go
  client/installer/v2_update_host_install_progress_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_update_host_install_progress.go
  restapi/operations/installer/v2_update_host_install_progress_parameters.go
  restapi/operations/installer/v2_update_host_install_progress_responses.go
  restapi/operations/installer/v2_update_host_install_progress_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2331 MGMT-7427: Add support for hosts that do not belong to cluster in host monitoring
  internal/cluster/cluster.go
  internal/common/db.go
  internal/common/monitor_query_generator.go
  internal/host/host.go
  internal/host/hostutil/test_utils.go
  internal/host/monitor.go
  internal/host/monitor_test.go
  internal/host/validator.go
Labels: approved, size/L, lgtm

#2233 MGMT-6537: Fetch operator version from index image
  Dockerfile.assisted-service
  Makefile
  cmd/main.go
  go.mod
  go.sum
  internal/cluster/transition_test.go
  internal/host/transition_test.go
  internal/oc/extract.go
  internal/oc/extract_test.go
  internal/oc/release.go
  internal/operators/builder.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/cnv/cnv_operator_test.go
  internal/operators/cnv/manifests_test.go
  internal/operators/manager_test.go
  internal/operators/ocs/manifests_test.go
  internal/operators/ocs/ocs_operator.go
  internal/operators/ocs/ocs_operator_test.go
  internal/operators/ocs/validation_test.go
  internal/sqllite/mock_query.go
  internal/sqllite/query.go
  internal/sqllite/query_test.go
  subsystem/operators_test.go
Labels: approved, kind/dependency-change, size/L, lgtm

#2343 MGMT-5443 Set host status to pending-user-input in case of reboot tim…
  internal/host/common.go
  internal/host/statemachine.go
  internal/host/transition_test.go
Labels: approved, size/M, lgtm

#2344 Adapt service to use only V2 APIs for agent Register, GetNextSteps, PostStepReply
  client/installer/get_next_steps_parameters.go
  client/installer/get_next_steps_responses.go
  client/installer/installer_client.go
  client/installer/post_step_reply_parameters.go
  client/installer/post_step_reply_responses.go
  client/installer/register_host_parameters.go
  client/installer/register_host_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  pkg/auth/authz_handler_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/get_next_steps.go
  restapi/operations/installer/get_next_steps_parameters.go
  restapi/operations/installer/get_next_steps_responses.go
  restapi/operations/installer/get_next_steps_urlbuilder.go
  restapi/operations/installer/post_step_reply.go
  restapi/operations/installer/post_step_reply_parameters.go
  restapi/operations/installer/post_step_reply_responses.go
  restapi/operations/installer/post_step_reply_urlbuilder.go
  restapi/operations/installer/register_host.go
  restapi/operations/installer/register_host_parameters.go
  restapi/operations/installer/register_host_responses.go
  restapi/operations/installer/register_host_urlbuilder.go
  subsystem/cluster_test.go
  subsystem/day2_cluster_test.go
  subsystem/host_test.go
  subsystem/utils_test.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2348 MGMT-4893: Add default values and doc to MUST_GATHER_IMAGES in kube-api
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  docs/operator.md
  internal/controller/controllers/agentserviceconfig_controller.go
Labels: approved, size/M, lgtm

#2339 MGMT-6897: Swagger support multiple networks
  internal/common/db.go
  models/cluster.go
  models/cluster_create_params.go
  models/cluster_network.go
  models/cluster_update_params.go
  models/machine_network.go
  models/network_configuration.go
  models/service_network.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/XL, api-review, lgtm

#2346 MGMT-7089: Add binding host API
  client/installer/bind_host_parameters.go
  client/installer/bind_host_responses.go
  client/installer/installer_client.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostutil/update_host.go
  internal/host/mock_host_api.go
  internal/host/transition.go
  mocks/mock_assisted_service.go
  models/bind_host_params.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/bind_host.go
  restapi/operations/installer/bind_host_parameters.go
  restapi/operations/installer/bind_host_responses.go
  restapi/operations/installer/bind_host_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2335 OCPBUGSM-32941: Cache secrets for spoke cluster
  cmd/main.go
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/common.go
Labels: approved, size/L, lgtm

#2350 MGMT-5444: Set 24 hours timeout for installation to complete
  cmd/main.go
  internal/cluster/cluster.go
  internal/cluster/common.go
  internal/cluster/statemachine.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
Labels: approved, size/L, lgtm

#2326 MGMT-7437: Add infra-env-id to the install command per host
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/S, lgtm

#2351 NO-ISSUE: Remove host ID from upload logs log
  internal/bminventory/inventory.go
Labels: approved, size/XS, lgtm

#2353 MGMT-7091: Add unbind API
  client/installer/installer_client.go
  client/installer/unbind_host_parameters.go
  client/installer/unbind_host_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/common.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostcommands/instruction_manager.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/host/mock_host_api.go
  internal/host/pool_host_statemachine.go
  internal/host/statemachine.go
  internal/host/transition.go
  internal/host/transition_test.go
  mocks/mock_assisted_service.go
  models/host.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/unbind_host.go
  restapi/operations/installer/unbind_host_parameters.go
  restapi/operations/installer/unbind_host_responses.go
  restapi/operations/installer/unbind_host_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2352 MGMT-7468: Bump OCP versions 4.7.21 -> 4.7.22, 4.8.2 -> 4.8.3
  config/manager/manager.yaml
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_ocp_versions.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  onprem-environment
  openshift/template.yaml
Labels: approved, size/S, lgtm

#2305 MGMT-7309: enhancement proposal for ARM64 CPU architecture support
  docs/enhancements/arm64-cpu-architecture.md
Labels: approved, size/L, lgtm

#2361 MGMT-7487: Add list infra-env hosts
  client/installer/installer_client.go
  client/installer/v2_list_hosts_parameters.go
  client/installer/v2_list_hosts_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/db.go
  internal/oc/mock_extract.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_list_hosts.go
  restapi/operations/installer/v2_list_hosts_parameters.go
  restapi/operations/installer/v2_list_hosts_responses.go
  restapi/operations/installer/v2_list_hosts_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2362 MGMT-7069: Adding latency metric to cluster to assisted-installer-bas…
  dashboards/grafana-dashboard-assisted-installer-basic-cluster-operation.configmap.yaml
Labels: approved, size/L, lgtm

#2364 NO-ISSUE: Add default test values for IPv4 and IPv6 networking
  internal/bminventory/inventory_test.go
  internal/cluster/cluster_test.go
  internal/cluster/transition_test.go
  internal/common/test_configuration.go
  internal/host/hostutil/test_utils.go
  internal/host/transition_test.go
  internal/operators/ocs/validation_test.go
Labels: approved, lgtm, size/XXL

#2359 MGMT-7470: add Internal interface V2 API
  client/installer/installer_client.go
  client/installer/v2_deregister_host_parameters.go
  client/installer/v2_deregister_host_responses.go
  client/installer/v2_update_host_ignition_parameters.go
  client/installer/v2_update_host_ignition_responses.go
  client/installer/v2_update_host_installer_args_parameters.go
  client/installer/v2_update_host_installer_args_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/common/db.go
  internal/controller/controllers/agent_controller.go
  internal/host/host.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_deregister_host.go
  restapi/operations/installer/v2_deregister_host_parameters.go
  restapi/operations/installer/v2_deregister_host_responses.go
  restapi/operations/installer/v2_deregister_host_urlbuilder.go
  restapi/operations/installer/v2_update_host_ignition.go
  restapi/operations/installer/v2_update_host_ignition_parameters.go
  restapi/operations/installer/v2_update_host_ignition_responses.go
  restapi/operations/installer/v2_update_host_ignition_urlbuilder.go
  restapi/operations/installer/v2_update_host_installer_args.go
  restapi/operations/installer/v2_update_host_installer_args_parameters.go
  restapi/operations/installer/v2_update_host_installer_args_responses.go
  restapi/operations/installer/v2_update_host_installer_args_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2266 MGMT-7292: Split custom manifest in custom_manifest file
  internal/cluster/cluster.go
  internal/operators/api/api.go
  internal/operators/api/mock_operator_api.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/cnv/manifest.go
  internal/operators/cnv/manifests_test.go
  internal/operators/lso/ls_operator.go
  internal/operators/lso/manifest.go
  internal/operators/lso/manifests_test.go
  internal/operators/manager.go
  internal/operators/manager_test.go
  internal/operators/ocs/manifest.go
  internal/operators/ocs/manifests_test.go
  internal/operators/ocs/ocs_operator.go
  restapi/embedded_spec.go
  restapi/operations/installer/download_cluster_files_parameters.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#2375 NO-ISSUE: Add CRD update in README
  docs/hive-integration/README.md
Labels: approved, size/S, lgtm

#2365 MGMT-7472: Create Agent CR without Cluster
  api/v1beta1/agent_types.go
  config/crd/bases/agent-install.openshift.io_agents.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_crd_utils.go
  internal/controller/controllers/crd_utils.go
  internal/controller/controllers/crd_utils_test.go
Labels: approved, size/L, lgtm

#2380 MGMT-7520: Update ignition as part of infraEnv update
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/M, lgtm

#2384 MGMT-7475: allow only cluster owners to download sensitive files.
  internal/bminventory/inventory.go
  internal/cluster/cluster.go
  pkg/auth/authz_handler_test.go
  restapi/embedded_spec.go
  subsystem/authz_test.go
  swagger.yaml
Labels: approved, size/M, api-review, lgtm, ok-to-test

#2385 NO-ISSUE: Use variables from env if set
  deploy/operator/ztp/deploy_spoke_cluster.sh
Labels: approved, size/XS, lgtm

#2381 MGMT-7513: Add GET method to v2 host ignition endpoint
  client/installer/installer_client.go
  client/installer/v2_get_host_ignition_parameters.go
  client/installer/v2_get_host_ignition_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_get_host_ignition.go
  restapi/operations/installer/v2_get_host_ignition_parameters.go
  restapi/operations/installer/v2_get_host_ignition_responses.go
  restapi/operations/installer/v2_get_host_ignition_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2368 Bug 1974077: Improve validation message for network latency and packe…
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, size/M, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#2387 MGMT-7534: Bump OCP versions 4.8.3 -> 4.8.4, 4.7.22 -> 4.7.23
  config/manager/manager.yaml
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_ocp_versions.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  onprem-environment
  openshift/template.yaml
Labels: approved, size/S, lgtm

#2291 MGMT-7220: CD controller to transform day1 cluster to day2
  internal/bminventory/inventory.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, lgtm

#2378 MGMT-7443: skip removable disks format
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  models/disk.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#2383 MGMT-7502: implement V2 API download infraEnv discovery ignition file
  client/installer/installer_client.go
  client/installer/v2_download_infra_env_files_parameters.go
  client/installer/v2_download_infra_env_files_responses.go
  internal/bminventory/inventory.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_download_infra_env_files.go
  restapi/operations/installer/v2_download_infra_env_files_parameters.go
  restapi/operations/installer/v2_download_infra_env_files_responses.go
  restapi/operations/installer/v2_download_infra_env_files_urlbuilder.go
  subsystem/infra_env_test.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2382 OCPBUGSM-31544: Set the BMH's hostname to the desired value
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/XS, lgtm

#2390 NO-ISSUE: Deploy multiple versions on CI only
  Makefile
  subsystem/image_test.go
Labels: approved, size/S, lgtm

#2358 Bug 1994060: Change IP version to golang's unix constant
  internal/network/connectivity_groups.go
Labels: approved, size/XS, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#2392 MGMT-7567 Check cluster owner for file downloads only with rhsso auth
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/M, lgtm

#1854 MGMT-4872: Initial events generation
  data/events.yaml
  hack/generate.sh
  internal/bminventory/inventory.go
  internal/common/events/events.go
  internal/controller/controllers/controller_event_wrapper.go
  internal/events/event.go
  internal/events/mock_event.go
  tools/generate_events.py
Labels: approved, lgtm, size/XXL

#2357 MGMT-5443: Reduced reboot timeout to 40 minutes
  internal/host/host.go
  internal/host/hostutil/host_utils.go
  internal/host/transition.go
Labels: approved, size/M, lgtm

#2325 OCPBUGSM-31544: Spoke worker BMH does not join cluster because CSR was not auto approved
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/L, lgtm

#2355 NO-ISSUE: Removed obsolete installation-timeout from the install command
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/instruction_manager.go
Labels: approved, size/S, lgtm

#2369 MGMT-7444: Support OS images listing in OS_IMAGES variable
  Makefile
  cmd/main.go
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_os_images.json
  deploy/assisted-service-configmap.yaml
  hack/generate.sh
  internal/versions/mock_versions.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  models/os_image.go
  models/os_images.go
  onprem-environment
  openshift/template.yaml
  pkg/s3wrapper/client.go
  pkg/s3wrapper/client_test.go
  pkg/s3wrapper/filesystem.go
  pkg/s3wrapper/filesystem_test.go
  pkg/s3wrapper/util_test.go
  restapi/embedded_spec.go
  swagger.yaml
  tools/deploy_assisted_installer_configmap.py
Labels: approved, size/XL, api-review, lgtm

#2389 MGMT-7512: Add V2 API for reset host validation
  client/installer/installer_client.go
  client/installer/v2_reset_host_validation_parameters.go
  client/installer/v2_reset_host_validation_responses.go
  internal/bminventory/inventory.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostutil/test_utils.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_reset_host_validation.go
  restapi/operations/installer/v2_reset_host_validation_parameters.go
  restapi/operations/installer/v2_reset_host_validation_responses.go
  restapi/operations/installer/v2_reset_host_validation_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2396 NO-ISSUE: Run subsystem waitForHostState in parallel when possible
  subsystem/cluster_test.go
  subsystem/day2_cluster_test.go
  subsystem/metrics_test.go
Labels: approved, size/L, lgtm

#2399 MGMT-7178: Adding new worker status, waiting-for-control-plane
  go.sum
  internal/host/host.go
  internal/host/host_test.go
  subsystem/day2_cluster_test.go
Labels: approved, size/S, lgtm

#2401 MGMT-7528: implement V2 download cluster files API
  client/installer/installer_client.go
  client/installer/v2_download_cluster_files_parameters.go
  client/installer/v2_download_cluster_files_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/mock_installer_internal.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_download_cluster_files.go
  restapi/operations/installer/v2_download_cluster_files_parameters.go
  restapi/operations/installer/v2_download_cluster_files_responses.go
  restapi/operations/installer/v2_download_cluster_files_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2398 Move the ocp version script from assisted-installer-deployment to this repo
  dev-requirements.txt
  hack/setup_env.sh
  tools/ocp_version_update/Jenkinsfile.default_release_update
  tools/ocp_version_update/update_default_release_versions_to_latest.py
Labels: approved, size/XL, lgtm

#2400 MGMT-7505: Implement V2 HostLogsProgress API
  client/installer/installer_client.go
  client/installer/v2_update_host_logs_progress_parameters.go
  client/installer/v2_update_host_logs_progress_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_update_host_logs_progress.go
  restapi/operations/installer/v2_update_host_logs_progress_parameters.go
  restapi/operations/installer/v2_update_host_logs_progress_responses.go
  restapi/operations/installer/v2_update_host_logs_progress_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2404 MGMT-7564: cluster credentials only for cluster owner
  pkg/auth/authz_handler_test.go
  restapi/embedded_spec.go
  subsystem/authz_test.go
  swagger.yaml
Labels: approved, size/M, api-review, lgtm, ok-to-test

#2342 MGMT-7251: Add minimal-initrd endpoint
  client/installer/download_minimal_initrd_parameters.go
  client/installer/download_minimal_initrd_responses.go
  client/installer/installer_client.go
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/isoeditor/factory.go
  internal/isoeditor/mock_editor.go
  internal/isoeditor/rhcos.go
  internal/isoeditor/rhcos_test.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  pkg/s3wrapper/client_test.go
  pkg/s3wrapper/filesystem_test.go
  pkg/s3wrapper/util_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/download_minimal_initrd.go
  restapi/operations/installer/download_minimal_initrd_parameters.go
  restapi/operations/installer/download_minimal_initrd_responses.go
  restapi/operations/installer/download_minimal_initrd_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2391 MGMT-7511: V2 Infra Env Reset Day2 Host API
  client/installer/installer_client.go
  client/installer/v2_reset_host_parameters.go
  client/installer/v2_reset_host_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_reset_host.go
  restapi/operations/installer/v2_reset_host_parameters.go
  restapi/operations/installer/v2_reset_host_responses.go
  restapi/operations/installer/v2_reset_host_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2413 NO-ISSUE: Add MINIKUBE_HOME to skipper.env
  skipper.env
Labels: approved, size/XS, lgtm

#2408 MGMT-7569: remove release getters from Versions
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/hostcommands/container_image_availability_cmd.go
  internal/host/hostcommands/container_image_availability_cmd_test.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/versions/mock_versions.go
  internal/versions/versions.go
  internal/versions/versions_test.go
Labels: approved, size/L, lgtm

#2411 MGMT-7583: AddEvent function should be used with InfraEnvID
  internal/bminventory/inventory.go
  internal/host/host.go
  internal/host/host_test.go
Labels: approved, size/M, lgtm

#2340 MGMT-4321: Service support multiple networks
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/common.go
  internal/cluster/refresh_status_preprocessor.go
  internal/cluster/transition_test.go
  internal/cluster/validations/validations.go
  internal/cluster/validator.go
  internal/common/common.go
  internal/common/db.go
  internal/common/test_configuration.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/common.go
  internal/dns/dns_test.go
  internal/hardware/validator_test.go
  internal/host/host_test.go
  internal/host/hostcommands/dhcp_allocate_cmd.go
  internal/host/hostcommands/dhcp_allocate_cmd_test.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/host/hostcommands/logs_cmd.go
  internal/host/hostutil/test_utils.go
  internal/host/monitor.go
  internal/host/monitor_test.go
  internal/host/transition_test.go
  internal/host/validator.go
  internal/installcfg/installcfg.go
  internal/installcfg/installcfg_test.go
  internal/network/machine_network_cidr.go
  internal/network/machine_network_cidr_test.go
  internal/network/utils.go
  internal/operators/ocs/validation_test.go
  subsystem/cluster_test.go
  subsystem/host_test.go
  subsystem/ipv6_test.go
Labels: approved, api-review, lgtm, size/XXL, ok-to-test

#2360 MGMT-7315: Make ACI CR accept multiple subnets
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
Labels: approved, size/S, lgtm

#2422 MGMT-7509: Implement V2 infra env download image API
  client/installer/download_infra_env_discovery_image_headers_responses.go
  client/installer/download_infra_env_discovery_image_responses.go
  client/installer/installer_client.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/download_infra_env_discovery_image.go
  restapi/operations/installer/download_infra_env_discovery_image_headers.go
  restapi/operations/installer/download_infra_env_discovery_image_headers_urlbuilder.go
  restapi/operations/installer/download_infra_env_discovery_image_urlbuilder.go
  swagger.yaml
Labels: approved, size/XL, api-review, lgtm

#2374 NO-ISSUE: clearing logs timestamp when node re-register
  internal/host/transition.go
Labels: approved, size/XS, lgtm

#2403 MGMT-6670: Extend validator for host in machineNetwork
  internal/network/machine_network_cidr.go
Labels: approved, size/S, lgtm

#2417 MGMT-7510: Implement V2 Infra Install Day2 host API
  client/installer/installer_client.go
  client/installer/v2_install_host_parameters.go
  client/installer/v2_install_host_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_install_host.go
  restapi/operations/installer/v2_install_host_parameters.go
  restapi/operations/installer/v2_install_host_responses.go
  restapi/operations/installer/v2_install_host_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2407 MGMT-7497: Remove KubeAPI EnableDay2Cluster flag
  Makefile
  cmd/main.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  tools/deploy_assisted_installer_configmap.py
Labels: approved, size/L, lgtm

#2426 MGMT-7600 log ignition generator user request id from the api
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
Labels: approved, size/M, lgtm

#2423 MGMT 4321: delete networks records on deletion
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/common.go
  internal/cluster/registrar.go
  internal/cluster/registrar_test.go
  internal/common/db.go
  subsystem/utils_test.go
Labels: approved, size/L, lgtm

#2424 MGMT-6670: Create sample ACI manifests for dual-stack OCP
  docs/hive-integration/crds/agentClusterInstall-dualstack-SNO.yaml
  docs/hive-integration/crds/agentClusterInstall-dualstack.yaml
Labels: approved, size/M, lgtm

#2416 MGMT-6670: Create a getter for Machine Network CIDR
  internal/bminventory/inventory.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/common.go
  internal/cluster/validator.go
  internal/host/validator.go
  internal/installcfg/installcfg_test.go
  internal/network/machine_network_cidr.go
  internal/network/machine_network_cidr_test.go
  internal/network/utils.go
Labels: approved, size/M, lgtm

#2370 NO-ISSUE: Update ztp readme file
  deploy/operator/README.md
Labels: approved, size/XS, lgtm

#2349 NO-ISSUE: Bump build tools to latest released version
  config/crd/bases/agent-install.openshift.io_agents.yaml
  config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
  config/crd/bases/agent-install.openshift.io_infraenvs.yaml
  config/crd/bases/agent-install.openshift.io_nmstateconfigs.yaml
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agentserviceconfigs.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_nmstateconfigs.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  deploy/olm-catalog/metadata/annotations.yaml
  hack/generate.sh
  hack/setup_env.sh
  internal/bminventory/mock_crd_utils.go
  internal/bminventory/mock_installer_internal.go
  internal/cluster/mock_cluster_api.go
  internal/cluster/validations/mock_validations.go
  internal/connectivity/mock_connectivity_validator.go
  internal/controller/controllers/mock_crd_events_handler.go
  internal/dns/mock_dns.go
  internal/dns/mock_dns_vendor.go
  internal/events/mock_event.go
  internal/hardware/mock_validator.go
  internal/host/hostcommands/mock_instruction_api.go
  internal/host/mock_host_api.go
  internal/ignition/mock_ignition.go
  internal/installcfg/mock_installcfg.go
  internal/isoeditor/mock_editor.go
  internal/isoeditor/mock_factory.go
  internal/isoutil/mock_isoutil.go
  internal/manifests/mock_manifests_internal.go
  internal/metrics/mock_metrics_manager_api.go
  internal/network/mock_manifests_generator.go
  internal/oc/mock_extract.go
  internal/oc/mock_release.go
  internal/operators/api/mock_operator_api.go
  internal/operators/mock_operators_api.go
  internal/sqllite/mock_query.go
  internal/usage/mock_usage_manager.go
  internal/versions/mock_versions.go
  mocks/mock_assisted_service.go
  mocks/mock_manifests.go
  pkg/executer/mock_executer.go
  pkg/generator/mock_install_config.go
  pkg/k8sclient/mock_k8sclient.go
  pkg/leader/mock_leader_elector.go
  pkg/mirrorregistries/mock_generator.go
  pkg/ocm/mock_accounts_mgmt.go
  pkg/ocm/mock_authorization.go
  pkg/ocm/mock_pullsecret_auth.go
  pkg/s3wrapper/mock_s3iface.go
  pkg/s3wrapper/mock_s3manageriface.go
  pkg/s3wrapper/mock_s3wrapper.go
  pkg/staticnetworkconfig/mock_generator.go
Labels: approved, lgtm, size/XXL

#2412 MGMT-7588: Fix event wrapper to notify kube-api
  data/events.yaml
  internal/common/events/events.go
  internal/controller/controllers/controller_event_wrapper.go
  internal/controller/controllers/controller_event_wrapper_test.go
Labels: approved, size/L, lgtm, ok-to-test

#2386 NO-ISSUE: Set machine network only in case of SNO. Remove unused VIPs from cluster deployment.
  deploy/operator/ztp/agentClusterInstall.j2
  deploy/operator/ztp/clusterDeployment.j2
Labels: approved, size/XS, lgtm

#2433 NO-ISSUE: fix typo in overriding OVNKubernetes via install-config
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/XS, api-review, lgtm

#2430 NO-ISSUE: Create a direct link to user guide in the main readme
  README.md
  docs/user-guide/README.md
Labels: approved, size/S, lgtm

#2437 NO-ISSUE: Mount k3d binary in skipper conf
  skipper.yaml
Labels: approved, size/XS, lgtm

#2436 MGMT-7597: Remove ronniel1, razregev, and sacharya from OWNERS
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#2420 MGMT-7206: add RELEASE_IMAGES env var for listing release images
  Makefile
  cmd/main.go
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_release_images.json
  deploy/assisted-service-configmap.yaml
  hack/generate.sh
  internal/versions/versions.go
  internal/versions/versions_test.go
  models/release_image.go
  models/release_images.go
  onprem-environment
  openshift/template.yaml
  restapi/embedded_spec.go
  swagger.yaml
  tools/deploy_assisted_installer_configmap.py
Labels: approved, size/L, api-review, lgtm

#2434 MGMT-7595: add UserName, OrgID, EmailDomain to the InfraEnv model
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  models/infra_env.go
  restapi/embedded_spec.go
  subsystem/infra_env_test.go
  subsystem/utils_test.go
  swagger.yaml
Labels: approved, size/M, api-review, lgtm

#2438 MGMT-7588: Replace the type of the generated clusterID and hostID
  internal/common/events/events.go
  internal/controller/controllers/controller_event_wrapper.go
  internal/events/event.go
  internal/events/mock_event.go
  tools/generate_events.py
Labels: approved, size/M, lgtm, ok-to-test

#2441 NO-ISSUE: OCP update only to github
  tools/ocp_version_update/update_default_release_versions_to_latest.py
Labels: approved, size/M, lgtm

#2409 MGMT-7582: Fix hasMemoryForRole validation message
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, size/S, lgtm

#2442 MGMT-7620: Change download URL in InfraEnv to contain V2 URL
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/M, lgtm

#2432 MGMT-7464: Pass multiple machine networks to install-config.yaml
  internal/installcfg/installcfg.go
  internal/installcfg/installcfg_test.go
  internal/network/machine_network_cidr.go
Labels: approved, size/L, lgtm

#2449 MGMT-7637: Bump OCP versions 4.8.4 -> 4.8.5, 4.7.23 -> 4.7.24
  config/manager/manager.yaml
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_ocp_versions.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  onprem-environment
  openshift/template.yaml
Labels: approved, size/S, lgtm

#2450 MGMT-7638: implement V2 Get Host API
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/M, lgtm

#2440 MGMT-7566: Fix day2 printBelongsToMachineCidr validation message
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, size/L, lgtm

#2455 MGMT-7498: Add backwards compatibility for network configuration
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster_test.go
  internal/cluster/common.go
Labels: approved, size/M, lgtm

#2446 MGMT-7529 Migrate local auth to use InfraEnv
  internal/bminventory/inventory.go
  internal/cluster/auth.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/gencrypto/token.go
  internal/gencrypto/token_test.go
  pkg/auth/local_authenticator.go
  pkg/auth/local_authenticator_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, lgtm

#2298 MGMT-6911: Validate that DNS wildcard entry is not configured.
  internal/common/test_configuration.go
  internal/constants/files.go
  internal/host/hostcommands/domain_name_resolution_cmd.go
  internal/host/refresh_status_preprocessor.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/host/validator.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  subsystem/ams_subscriptions_test.go
  subsystem/authz_test.go
  subsystem/cluster_test.go
  subsystem/day2_cluster_test.go
  subsystem/kubeapi_test.go
  subsystem/manifests_test.go
  subsystem/metrics_test.go
  subsystem/operators_test.go
  subsystem/utils_test.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm, ok-to-test

#2421 NO-ISSUE: Refactor agentserviceconfig controller
  api/v1beta1/agentserviceconfig_types.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
Labels: approved, size/XL, lgtm

#2463 MGMT-7649: Update inventory should not try to get cluster if host is unbound
  internal/host/host.go
  internal/host/host_test.go
Labels: approved, size/M, lgtm

#2415 NO-ISSUE - expose the assisted debug port and remove the liveness por…
  Makefile
Labels: approved, size/XS, lgtm

#2443 MGMT-7114: support CPUArchitecture in Cluster
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/common.go
  internal/common/db.go
  internal/common/test_configuration.go
  internal/host/hostcommands/container_image_availability_cmd.go
  internal/host/hostcommands/container_image_availability_cmd_test.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/versions/mock_versions.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  models/cluster.go
  models/cluster_create_params.go
  models/infra_env.go
  models/infra_env_create_params.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/XL, api-review, lgtm

#2445 MGMT-7498: Migrate multiple networks
  internal/migrations/20210713123129_populate_infra_env.go
  internal/migrations/20210822134659_multiple_networks.go
  internal/migrations/20210822134659_multiple_networks_test.go
  internal/migrations/migrations.go
  tools/migration_generator/migration_generator.go
Labels: approved, size/L, lgtm

#2468 MGMT-4321: Bugfix flaky auto assign DHCP machine cidr
  internal/cluster/common.go
Labels: approved, size/S, lgtm

#2462 MGMT-7648: Notification on event for binded Host
  internal/controller/controllers/controller_event_wrapper.go
  internal/controller/controllers/controller_event_wrapper_test.go
Labels: approved, size/M, lgtm

#2333 MGMT-7420 - Introducing disk encryption to cluster properties.
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/validations/validations.go
  internal/common/tang_server.go
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
  internal/network/mock_manifests_generator.go
  models/cluster.go
  models/cluster_create_params.go
  models/cluster_update_params.go
  models/disk_encryption.go
  restapi/embedded_spec.go
  subsystem/manifests_test.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2472 MGMT-7675: Update StaticNetwork in infraEnv update
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/M, lgtm

#2418 MGMT-7574: Add V2 endpoint to download cluster credentials
  client/installer/installer_client.go
  client/installer/v2_download_cluster_credentials_parameters.go
  client/installer/v2_download_cluster_credentials_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_download_cluster_credentials.go
  restapi/operations/installer/v2_download_cluster_credentials_parameters.go
  restapi/operations/installer/v2_download_cluster_credentials_responses.go
  restapi/operations/installer/v2_download_cluster_credentials_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2453 Bug 1996531: Reduce singleNodeRebootTimeout from 120 minutes to 80 minutes
  internal/cluster/common.go
  internal/host/common.go
  internal/host/hostutil/test_utils.go
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, size/L, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#2460 MGMT-7642: Select latest version in InfraEnv create
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/versions/mock_versions.go
  internal/versions/versions.go
  internal/versions/versions_test.go
Labels: approved, size/L, lgtm

#2465 MGMT-7650: Align GenerateIso error handling
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/M, lgtm

#2470 MGMT-7661: Add property called physical_bytes_method to memory
  models/memory.go
  models/memory_method.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#2475 MGMT-4321: Bugfix flaky auto assign machine cidr deadlock
  internal/cluster/common.go
  internal/cluster/common_test.go
Labels: approved, size/L, lgtm

#2478 NO-ISSUE: Deprecating /v1/clusters/{cluster_id}/host-requirements API.
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/XS, api-review, lgtm

#2456 MGMT-7549: extract openshift-install for none platform
  Dockerfile.assisted-service
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/ignition/dummy.go
  internal/ignition/ignition.go
  internal/ignition/mock_ignition.go
  internal/installercache/installercache.go
  internal/oc/mock_release.go
  internal/oc/release.go
  internal/oc/release_test.go
  models/platform_type.go
  pkg/generator/generator.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, kind/dependency-change, size/L, api-review, lgtm

#2454 MGMT-7187: support multiple architectures in uploadISOs
  cmd/main.go
  internal/assistedserviceiso/assistedserviceiso_api.go
  internal/assistedserviceiso/assistedserviceiso_api_test.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/versions/mock_versions.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  pkg/s3wrapper/client.go
  pkg/s3wrapper/client_test.go
  pkg/s3wrapper/filesystem.go
  pkg/s3wrapper/filesystem_test.go
  pkg/s3wrapper/mock_s3wrapper.go
  pkg/s3wrapper/util_test.go
Labels: approved, size/L, api-review, lgtm

#2494 MGMT-7692: add subsystem test for infra env V2 scenarios
  subsystem/cluster_test.go
  subsystem/infra_env_test.go
  subsystem/utils_test.go
Labels: approved, size/L, lgtm

#2495 MGMT-7695: remove a ClusterID option from InfraEnvUpdateParams
  models/infra_env_update_params.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/M, api-review, lgtm

#2379 MGMT-7234: InfraEnv Controller migrate to v2
  api/v1beta1/infraenv_types.go
  cmd/main.go
  config/crd/bases/agent-install.openshift.io_infraenvs.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/common/db.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/common.go
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  subsystem/cluster_test.go
  subsystem/kubeapi_test.go
  subsystem/utils_test.go
Labels: approved, lgtm, size/XXL

#2467 MGMT-4872: Generate cluster update events
  data/events.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/common.go
  internal/cluster/progress_test.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/common/events/events.go
  internal/operators/ocs/validation_test.go
  tools/generate_events.py
Labels: approved, api-review, lgtm, size/XXL, ok-to-test

#2501 MGMT-7642: Use GetOpenshiftVersion in GetLatestVersion
  internal/versions/versions.go
  internal/versions/versions_test.go
Labels: approved, size/S, lgtm

#2502 MGMT-7484: validate UserManagedNetworking for non-default arch cluster
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/oc/release.go
  pkg/generator/generator.go
Labels: approved, size/M, lgtm

#2498 NO-ISSUE: Remove manual sleep in Makefile & Extend sleep interval when waiting to the service
  Makefile
  tools/wait_for_assisted_service.py
Labels: approved, size/XS, lgtm

#2499 MGMT-7592 - implement Register/List Cluster/s for V2 API
  client/installer/installer_client.go
  client/installer/v2_list_clusters_parameters.go
  client/installer/v2_list_clusters_responses.go
  client/installer/v2_register_cluster_parameters.go
  client/installer/v2_register_cluster_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_list_clusters.go
  restapi/operations/installer/v2_list_clusters_parameters.go
  restapi/operations/installer/v2_list_clusters_responses.go
  restapi/operations/installer/v2_list_clusters_urlbuilder.go
  restapi/operations/installer/v2_register_cluster.go
  restapi/operations/installer/v2_register_cluster_parameters.go
  restapi/operations/installer/v2_register_cluster_responses.go
  restapi/operations/installer/v2_register_cluster_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2507 MGMT-6898: Fix MachineNetworks validation for multi-network setup
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/M, lgtm

#2511 MGMT-6670: Fix BelongsToMachineCidr validator message
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, size/L, lgtm

#2503 MGMT-7479: support OS_IMAGES in AgentServiceConfig
  api/v1beta1/agentserviceconfig_types.go
  config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
  config/crd/resources.yaml
  config/manager/manager.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agentserviceconfigs.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  hack/generate.sh
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/images.go
Labels: approved, size/L, lgtm

#2493 NO-ISSUE: Fixing disk-encryption definition in swagger.yaml.
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validations.go
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
  models/disk_encryption.go
  restapi/embedded_spec.go
  subsystem/manifests_test.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#2505 Update swagger-codgen-cli to its latest version
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, size/XS, lgtm

#2510 MGMT-7690: BMAC agent reference to CD is optional
  internal/controller/controllers/bmh_agent_controller.go
Labels: approved, size/XS, lgtm

#2500 MGMT-7606: implement Get/Deregister cluster for V2 API
  client/installer/installer_client.go
  client/installer/v2_deregister_cluster_parameters.go
  client/installer/v2_deregister_cluster_responses.go
  client/installer/v2_get_cluster_parameters.go
  client/installer/v2_get_cluster_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_v2_handlers.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/controllers/clusterdeployments_controller.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_deregister_cluster.go
  restapi/operations/installer/v2_deregister_cluster_parameters.go
  restapi/operations/installer/v2_deregister_cluster_responses.go
  restapi/operations/installer/v2_deregister_cluster_urlbuilder.go
  restapi/operations/installer/v2_get_cluster.go
  restapi/operations/installer/v2_get_cluster_parameters.go
  restapi/operations/installer/v2_get_cluster_responses.go
  restapi/operations/installer/v2_get_cluster_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2520 MGMT-7292: Revert Add custom_manifest.yaml to not break tests
  internal/operators/manager.go
  internal/operators/manager_test.go
  restapi/embedded_spec.go
  restapi/operations/installer/download_cluster_files_parameters.go
  swagger.yaml
Labels: approved, size/M, api-review, lgtm

#2428 NO-ISSUE: Create initial docs about network configuration
  docs/user-guide/README.md
  docs/user-guide/network-configuration.md
Labels: approved, size/L, lgtm
