Repository openshift/assisted-service, pull requests merged in 2021-09, with the labels that each got.

#2521 MGMT-7714: Allow downloading kubeconfig-noingress while cluster is "Installing pending user action"
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
Labels: approved, size/M, lgtm

#2523 NO-ISSUE: downloading kustomize release directly to handle rate-limiters
  hack/setup_env.sh
Labels: approved, size/XS, lgtm

#2512 MGMT-6670: Fix handling of empty network in various network params
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/common_test.go
  internal/cluster/validator.go
  internal/common/common.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/network/utils.go
Labels: approved, size/L, lgtm

#2508 MGMT-4475: add suggested-role
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/common.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/mock_host_api.go
  internal/usage/consts.go
  models/host.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#2526 OCPBUGSM-34182: skip IsDNSWildcardNotConfigured validation in day2
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, size/S, lgtm

#2519 MGMT-7609: implement cluster get/update install config for V2
  client/installer/installer_client.go
  client/installer/v2_get_cluster_install_config_parameters.go
  client/installer/v2_get_cluster_install_config_responses.go
  client/installer/v2_update_cluster_install_config_parameters.go
  client/installer/v2_update_cluster_install_config_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_get_cluster_install_config.go
  restapi/operations/installer/v2_get_cluster_install_config_parameters.go
  restapi/operations/installer/v2_get_cluster_install_config_responses.go
  restapi/operations/installer/v2_get_cluster_install_config_urlbuilder.go
  restapi/operations/installer/v2_update_cluster_install_config.go
  restapi/operations/installer/v2_update_cluster_install_config_parameters.go
  restapi/operations/installer/v2_update_cluster_install_config_responses.go
  restapi/operations/installer/v2_update_cluster_install_config_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2528 Update cloud.md how to get JWT_TOKEN without ocm client
  docs/cloud.md
Labels: approved, size/S, lgtm

#2525 MGMT-7568: ocp_version_update - support os/release images
  tools/ocp_version_update/update_default_release_versions_to_latest.py
Labels: approved, size/L, lgtm

#2497 MGMT-4872: Update events requirements
  data/events.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/events/events.go
  internal/controller/controllers/controller_event_wrapper.go
  internal/controller/controllers/controller_event_wrapper_test.go
  internal/events/event.go
  internal/events/mock_event.go
  tools/generate_events.py
Labels: approved, size/XL, lgtm, ok-to-test

#2517 MGMT-7704: Fix disk validation for infra-env host
  internal/hardware/mock_validator.go
  internal/hardware/validator.go
  internal/hardware/validator_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/monitor_test.go
  internal/host/transition_test.go
  internal/host/validator.go
  subsystem/host_v2_test.go
Labels: approved, size/L, lgtm

#2534 NO-ISSUE: Move events.yaml to docs
  docs/events.yaml
  hack/generate.sh
Labels: approved, size/XS, lgtm

#2540 MGMT-7643: Add support for OCP 4.9.0-fc.0 version
  config/manager/manager.yaml
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_must_gather_versions.json
  data/default_ocp_versions.json
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  onprem-environment
  openshift/template.yaml
Labels: approved, size/M, lgtm

#2545 NO-ISSUE: Trigger VIP reallocation only when the primary machine CIDR changes
  internal/bminventory/inventory.go
Labels: approved, size/S, lgtm

#2476 OCPBUGSM-34158: Transition day2 hosts to Done
  internal/host/host.go
  internal/host/statemachine.go
  internal/host/transition.go
Labels: approved, size/S, lgtm

#2532 MGMT-7724: Remove notification CD to InfraEnv
  internal/controller/controllers/clusterdeployments_controller.go
Labels: approved, size/S, lgtm

#2547 NO-ISSUE: Fix typo in log
  internal/bminventory/inventory.go
Labels: approved, size/XS, lgtm

#2549 MGMT-4505 Fixes RWN creation when no hostname annotation is passed
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/bmh_agent_controller.go
Labels: approved, size/S, lgtm

#2542 MGMT-7568: ocp_version_update - clone repo before updates
  tools/ocp_version_update/update_default_release_versions_to_latest.py
Labels: approved, size/S, lgtm

#2552 MGMT-7749: Bump OCP versions 4.8.4 -> 4.8.5, 4.7.23 -> 4.7.24
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_ocp_versions.json
  data/default_os_images.json
  data/default_release_images.json
  onprem-environment
  openshift/template.yaml
Labels: approved, size/S, lgtm

#2485 MGMT-7498: Add missing backwards compatibility for network configuration
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/L, lgtm

#2536 MGMT-7736: Do not blindly load the whole database in InfraEnv migration
  docs/dev/migrations.md
  internal/migrations/20210713123129_populate_infra_env.go
  internal/migrations/20210713123129_populate_infra_env_test.go
Labels: approved, size/S, lgtm

#2530 MGMT-7610: Implement install cluster V2 API
  client/installer/installer_client.go
  client/installer/v2_install_cluster_parameters.go
  client/installer/v2_install_cluster_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/controllers/clusterdeployments_controller.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_install_cluster.go
  restapi/operations/installer/v2_install_cluster_parameters.go
  restapi/operations/installer/v2_install_cluster_responses.go
  restapi/operations/installer/v2_install_cluster_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2548 MGMT-7472: Fix log to print infraenv ID
  internal/controller/controllers/crd_utils.go
Labels: approved, size/XS, lgtm

#2560 MGMT-7753: KubeAPI Docs - Update Diagram
  docs/hive-integration/kubeAPI4.9_controllers.jpg
Labels: approved, size/XS, lgtm

#2482 MGMT-7457: Adding validations for disk-encryption.
  internal/common/test_configuration.go
  internal/host/refresh_status_preprocessor.go
  internal/host/statemachine.go
  internal/host/validation_id.go
  internal/host/validations_test.go
  internal/host/validator.go
  models/host_validation_id.go
  models/inventory.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: approved, size/XL, api-review, lgtm

#2557 NO-ISSUE: report OVN and SDN nw types separately
  internal/bminventory/inventory.go
  internal/usage/consts.go
  subsystem/cluster_test.go
Labels: approved, size/M, lgtm

#2531 MGMT-7725: BMAC add test for agent without cluster
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/XS, lgtm

#2561 MGMT-7742: Fixing host getting stuck in "binding" state
  internal/host/hostcommands/instruction_manager.go
  internal/host/hostcommands/instruction_manager_test.go
  restapi/embedded_spec.go
  subsystem/host_v2_test.go
  subsystem/utils_test.go
  swagger.yaml
Labels: approved, size/M, api-review, lgtm

#2522 MGMT-7686: Support unbound status in conditions
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, size/L, lgtm

#2568 MGMT-7751: fix unbound host not reaching discovering-unbound state
  internal/host/pool_host_statemachine.go
  internal/host/statemachine.go
  internal/host/transition_test.go
Labels: approved, size/S, lgtm

#2564 Backwards backport of backward compatibility work
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/common.go
  internal/cluster/common_test.go
  internal/cluster/validator.go
  internal/common/common.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/network/utils.go
Labels: approved, size/L, lgtm

#2554 NO-ISSUE: Change wording for the preMigration section in docs
  docs/dev/migrations.md
Labels: approved, size/XS, lgtm

#2558 MGMT-7752: Bump OCP versions 4.8.5 -> 4.8.9, 4.7.24 -> 4.7.28
  config/manager/manager.yaml
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_ocp_versions.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  onprem-environment
  openshift/template.yaml
Labels: approved, size/M, lgtm

#2566 MGMT-7643: update ocp to 4.9 in operator/common
  deploy/operator/common.sh
Labels: approved, size/XS, lgtm

#2504 MGMT-7593: Added custom manifest feature usage
  cmd/main.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/manifests/api/interface.go
  internal/manifests/api/mock_manifests_api.go
  internal/manifests/api/mock_manifests_internal.go
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
  internal/operators/builder.go
  internal/operators/manager_test.go
  internal/usage/consts.go
  subsystem/manifests_test.go
Labels: approved, size/L, lgtm

#2550 Bug 1979950: Fix minimal requirements for cnv
  internal/operators/cnv/cnv_operator.go
  internal/operators/cnv/cnv_operator_test.go
Labels: approved, size/M, bugzilla/severity-urgent, lgtm, bugzilla/valid-bug

#2477 MGMT-7090: Bind and Unbind Agent
  internal/bminventory/inventory.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/XL, lgtm

#2480 MGMT-7253: Add assisted-image-service to AgentServiceconfig
  api/v1beta1/agentserviceconfig_types.go
  config/manager/manager.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/images.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#2464 MGMT-7601: V2 cluster update API
  client/installer/installer_client.go
  client/installer/v2_update_cluster_parameters.go
  client/installer/v2_update_cluster_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  mocks/mock_assisted_service.go
  models/v2_cluster_update_params.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_update_cluster.go
  restapi/operations/installer/v2_update_cluster_parameters.go
  restapi/operations/installer/v2_update_cluster_responses.go
  restapi/operations/installer/v2_update_cluster_urlbuilder.go
  subsystem/ams_subscriptions_test.go
  subsystem/cluster_test.go
  subsystem/day2_cluster_test.go
  subsystem/host_test.go
  subsystem/image_test.go
  subsystem/metrics_test.go
  subsystem/operators_test.go
  subsystem/utils_test.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2541 MGMT-4475: suggested role in monitor
  internal/host/common.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostrole_test.go
  internal/host/hostutil/test_utils.go
  internal/host/validations_test.go
Labels: approved, size/L, lgtm

#2563 MGMT-7754: Support iso creation with EFI boot only
  internal/isoutil/isoutil.go
Labels: approved, size/S, lgtm

#2573 Bug 2001973: Add more validations for Disk Encryption settings
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validations.go
Labels: approved, size/L, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#2574 Release 0.1.0
  Makefile
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/metadata/annotations.yaml
  hack/operator-release.sh
Labels: approved, size/S, lgtm

#2578 MGMT-7768: Handle Host's Kind field during bind/unbind/register
  internal/host/host.go
  internal/host/host_test.go
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, size/S, lgtm

#2565 MGMT-7730: Add Bound condition to Agent CRD
  api/v1beta1/agent_types.go
  docs/hive-integration/kube-api-conditions.md
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, lgtm

#2496 MGMT-7395: Improve error messages for DNS validations
  internal/host/validator.go
Labels: approved, size/S, lgtm, ok-to-test

#2567 MGMT-7633: Update CD controller to use V2 API
  internal/bminventory/inventory.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, size/M, lgtm

#2559 MGMT-7643: support pre-releases in update_versions
  tools/ocp_version_update/update_default_release_versions_to_latest.py
Labels: approved, size/L, lgtm

#2575 MGMT-4475: add operators host criteria to canBeMaster
  internal/host/host.go
Labels: approved, size/XS, lgtm

#2533 MGMT-7611: Implement V2 Cancel Cluster Installation API
  client/installer/installer_client.go
  client/installer/v2_cancel_installation_parameters.go
  client/installer/v2_cancel_installation_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/controllers/clusterdeployments_controller.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_cancel_installation.go
  restapi/operations/installer/v2_cancel_installation_parameters.go
  restapi/operations/installer/v2_cancel_installation_responses.go
  restapi/operations/installer/v2_cancel_installation_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2582 MGMT-7775: IsDNSWildcardNotConfigured should not be part of unbound h…
  internal/host/validator.go
Labels: approved, size/XS, lgtm

#2583 Bug 2001029: presigned files access
  internal/bminventory/inventory.go
  subsystem/authz_test.go
Labels: approved, size/M, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#2451 MGMT-7639: Support using podman in the assisted-service
  Dockerfile.assisted-service-build
  Jenkinsfile
  Makefile
  hack/generate.sh
  hack/setup_env.sh
  hack/update_local_image.sh
  hack/utils.sh
  skipper.yaml
Labels: approved, kind/dependency-change, size/L, lgtm

#2452 MGMT-4321: Extend network validators for dual-stack support
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
Labels: approved, size/L, lgtm

#2588 Revert "MGMT-7639: Support using podman in the assisted-service"
  Dockerfile.assisted-service-build
  Jenkinsfile
  Makefile
  hack/generate.sh
  hack/setup_env.sh
  hack/update_local_image.sh
  hack/utils.sh
  skipper.yaml
Labels: approved, kind/dependency-change, size/L

#2581 MGMT-7777: Bump OCP versions rchos 4.9.0-fc.0 -> 4.9.0-rc.0, 4.8.9 -> 4.8.10, 4.9.0-fc.0 -> 4.9.0-rc.0
  config/manager/manager.yaml
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_ocp_versions.json
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  onprem-environment
  openshift/template.yaml
Labels: approved, size/M, lgtm

#2590 NO-ISSUE: Skip cluster progress update on day2 clusters.
  internal/cluster/cluster.go
  internal/cluster/progress_test.go
  subsystem/cluster_test.go
  subsystem/day2_cluster_test.go
Labels: approved, size/M, lgtm

#2591 MGMT-7639: Support using podman in the deploy-test make target (#2451)
  Dockerfile.assisted-service-build
  Jenkinsfile
  Makefile
  hack/generate.sh
  hack/setup_env.sh
  hack/update_local_image.sh
  hack/utils.sh
  skipper.yaml
  tools/utils.py
Labels: approved, kind/dependency-change, size/L, lgtm

#2569 MGMT-7726: Handle non existing cluster in Agent controller
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, lgtm

#2596 NO-ISSUE: adding podman to the skipper builder image unless the opm i…
  hack/setup_env.sh
Labels: approved, size/XS

#2589 MGMT-7774: convert V1 APIs to V2 APIs
  client/installer/installer_client.go
  client/installer/v2_complete_installation_parameters.go
  client/installer/v2_complete_installation_responses.go
  client/installer/v2_get_preflight_requirements_parameters.go
  client/installer/v2_get_preflight_requirements_responses.go
  client/installer/v2_reset_cluster_parameters.go
  client/installer/v2_reset_cluster_responses.go
  client/installer/v2_update_cluster_logs_progress_parameters.go
  client/installer/v2_update_cluster_logs_progress_responses.go
  client/installer/v2_upload_cluster_ingress_cert_parameters.go
  client/installer/v2_upload_cluster_ingress_cert_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_complete_installation.go
  restapi/operations/installer/v2_complete_installation_parameters.go
  restapi/operations/installer/v2_complete_installation_responses.go
  restapi/operations/installer/v2_complete_installation_urlbuilder.go
  restapi/operations/installer/v2_get_preflight_requirements.go
  restapi/operations/installer/v2_get_preflight_requirements_parameters.go
  restapi/operations/installer/v2_get_preflight_requirements_responses.go
  restapi/operations/installer/v2_get_preflight_requirements_urlbuilder.go
  restapi/operations/installer/v2_reset_cluster.go
  restapi/operations/installer/v2_reset_cluster_parameters.go
  restapi/operations/installer/v2_reset_cluster_responses.go
  restapi/operations/installer/v2_reset_cluster_urlbuilder.go
  restapi/operations/installer/v2_update_cluster_logs_progress.go
  restapi/operations/installer/v2_update_cluster_logs_progress_parameters.go
  restapi/operations/installer/v2_update_cluster_logs_progress_responses.go
  restapi/operations/installer/v2_update_cluster_logs_progress_urlbuilder.go
  restapi/operations/installer/v2_upload_cluster_ingress_cert.go
  restapi/operations/installer/v2_upload_cluster_ingress_cert_parameters.go
  restapi/operations/installer/v2_upload_cluster_ingress_cert_responses.go
  restapi/operations/installer/v2_upload_cluster_ingress_cert_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2592 Bug 2002495: Deploying OCP on RHOS with assisted-installer Failing validation blocks deployment
  internal/host/pool_host_statemachine.go
  internal/host/refresh_status_preprocessor.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/host/validator.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  subsystem/metrics_test.go
  swagger.yaml
Labels: approved, bugzilla/severity-urgent, size/XL, api-review, lgtm, bugzilla/valid-bug

#2594 NO-ISSUE: Fixed a flaky subystem-test related to disk-encryption.
  subsystem/cluster_test.go
Labels: approved, size/S, lgtm

#2529 MGMT-4872: Generate host package events
  docs/events.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/events/events.go
  internal/events/eventstest/events_test_utils.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/host/hostrole_test.go
  internal/host/hostutil/update_host.go
  internal/host/hostutil/update_host_test.go
  internal/host/monitor_test.go
  internal/host/transition_test.go
  internal/host/validations_test.go
Labels: approved, lgtm, size/XXL, ok-to-test

#2537 MGMT-7667: Move list managed domains V1 API to V2
  client/managed_domains/managed_domains_client.go
  client/managed_domains/v2_list_managed_domains_parameters.go
  client/managed_domains/v2_list_managed_domains_responses.go
  internal/domains/managed_domains.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/managed_domains/v2_list_managed_domains.go
  restapi/operations/managed_domains/v2_list_managed_domains_parameters.go
  restapi/operations/managed_domains/v2_list_managed_domains_responses.go
  restapi/operations/managed_domains/v2_list_managed_domains_urlbuilder.go
  swagger.yaml
Labels: approved, size/XL, api-review, lgtm

#2429 MGMT-7576: Implement V2 DownloadClusterFile presigned
  client/installer/installer_client.go
  client/installer/v2_get_presigned_for_cluster_files_parameters.go
  client/installer/v2_get_presigned_for_cluster_files_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_get_presigned_for_cluster_files.go
  restapi/operations/installer/v2_get_presigned_for_cluster_files_parameters.go
  restapi/operations/installer/v2_get_presigned_for_cluster_files_responses.go
  restapi/operations/installer/v2_get_presigned_for_cluster_files_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2609 MGMT-7799: Adds infra_env_id to event properties
  models/event.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/M, api-review, lgtm

#2598 MGMT-7785: support AddReleaseImage in Versions
  Makefile
  cmd/main.go
  go.mod
  go.sum
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/common/test_configuration.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/host/hostcommands/container_image_availability_cmd.go
  internal/host/hostcommands/container_image_availability_cmd_test.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/oc/mock_release.go
  internal/oc/release.go
  internal/oc/release_test.go
  internal/versions/mock_versions.go
  internal/versions/versions.go
  internal/versions/versions_test.go
Labels: approved, lgtm, size/XXL

#2604 NO-ISSUE: install epel for centos8 stream
  Dockerfile.assisted-service-build
Labels: approved, kind/dependency-change, size/XS, lgtm

#2606 MGMT-7798: KubeAPI: Adds InfraEnv debugInfo.eventsURL
  api/v1beta1/infraenv_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/agent-install.openshift.io_infraenvs.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
Labels: approved, size/M, lgtm

#2611 NO-ISSUE: added OS_IMAGES/RELEASE_IMAGES to template
  openshift/template.yaml
Labels: approved, size/XS, lgtm

#2600 Update operator-index-build to use podman fixing broken Jenkins builds
  Makefile
Labels: approved, size/XS, lgtm

#2597 MGMT-7796: reset host data, set by the cluster on unbind operation
  internal/host/statemachine.go
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, size/L, lgtm

#2616 OCPBUGSM-34901: Add register successfully event
  docs/events.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/events/events.go
Labels: approved, size/M, lgtm

#2619 MGMT-7804: Create healthchecks for monitoring routines
  cmd/main.go
  internal/cluster/cluster.go
  openshift/template.yaml
  pkg/app/middleware.go
  pkg/commonutils/common_utils.go
  pkg/thread/thread.go
Labels: approved, size/M, lgtm

#2595 MGMT-7728: Add NTP configuration to ISO
  internal/bminventory/inventory.go
  internal/common/common.go
  internal/host/host.go
  internal/host/hostcommands/instruction_manager.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/host/hostcommands/ntp_synchronizer_cmd.go
  internal/host/pool_host_statemachine.go
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, size/L, lgtm

#2509 MGMT-7608: Move cluster default-config to V2 API
  client/installer/installer_client.go
  client/installer/v2_get_cluster_default_config_parameters.go
  client/installer/v2_get_cluster_default_config_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_v2_handlers.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_get_cluster_default_config.go
  restapi/operations/installer/v2_get_cluster_default_config_parameters.go
  restapi/operations/installer/v2_get_cluster_default_config_responses.go
  restapi/operations/installer/v2_get_cluster_default_config_urlbuilder.go
  swagger.yaml
Labels: approved, size/XL, api-review, lgtm

#2607 MGMT-7772: move specific V1 APIs to V2
  client/manifests/manifests_client.go
  client/manifests/v2_download_cluster_manifest_parameters.go
  client/manifests/v2_download_cluster_manifest_responses.go
  client/operators/operators_client.go
  client/operators/v2_report_monitored_operator_status_parameters.go
  client/operators/v2_report_monitored_operator_status_responses.go
  client/versions/v2_list_component_versions_parameters.go
  client/versions/v2_list_component_versions_responses.go
  client/versions/v2_list_supported_openshift_versions_parameters.go
  client/versions/v2_list_supported_openshift_versions_responses.go
  client/versions/versions_client.go
  internal/manifests/api/mock_manifests_api.go
  internal/manifests/manifests.go
  internal/operators/handler/handler.go
  internal/versions/mock_versions.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  mocks/mock_manifests.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/manifests/v2_download_cluster_manifest.go
  restapi/operations/manifests/v2_download_cluster_manifest_parameters.go
  restapi/operations/manifests/v2_download_cluster_manifest_responses.go
  restapi/operations/manifests/v2_download_cluster_manifest_urlbuilder.go
  restapi/operations/operators/v2_report_monitored_operator_status.go
  restapi/operations/operators/v2_report_monitored_operator_status_parameters.go
  restapi/operations/operators/v2_report_monitored_operator_status_responses.go
  restapi/operations/operators/v2_report_monitored_operator_status_urlbuilder.go
  restapi/operations/versions/v2_list_component_versions.go
  restapi/operations/versions/v2_list_component_versions_parameters.go
  restapi/operations/versions/v2_list_component_versions_responses.go
  restapi/operations/versions/v2_list_component_versions_urlbuilder.go
  restapi/operations/versions/v2_list_supported_openshift_versions.go
  restapi/operations/versions/v2_list_supported_openshift_versions_parameters.go
  restapi/operations/versions/v2_list_supported_openshift_versions_responses.go
  restapi/operations/versions/v2_list_supported_openshift_versions_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2621 Revert MGMT 7639 podman transition
  Dockerfile.assisted-service-build
  Jenkinsfile
  Makefile
  hack/generate.sh
  hack/setup_env.sh
  hack/update_local_image.sh
  hack/utils.sh
  skipper.yaml
  tools/utils.py
Labels: approved, kind/dependency-change, size/L, lgtm

#2586 OCPBUGSM-34323: Use the hostname in the Spec if present
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/M, lgtm

#2577 MGMT-7282: Operator upgrade CI job
  deploy/operator/after_upgrade.sh
  deploy/operator/before_upgrade.sh
  deploy/operator/common.sh
  deploy/operator/upgrade.sh
  deploy/operator/ztp/deploy_spoke_cluster.sh
Labels: approved, size/M, lgtm

#2627 MGMT-7282: Rename env var and move upgrade scripts into its own repo
  deploy/operator/upgrade/after_upgrade.sh
  deploy/operator/upgrade/before_upgrade.sh
  deploy/operator/upgrade/upgrade.sh
Labels: approved, size/XS, lgtm

#2626 OCPBUGSM-35037: Fix osImages refenrece passing
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
Labels: approved, size/M, lgtm

#2535 MGMT-7666: Move list monitored operators V1 API to V2
  client/operators/operators_client.go
  client/operators/v2_list_of_cluster_operators_parameters.go
  client/operators/v2_list_of_cluster_operators_responses.go
  internal/operators/handler/handler_v2.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/operators/v2_list_of_cluster_operators.go
  restapi/operations/operators/v2_list_of_cluster_operators_parameters.go
  restapi/operations/operators/v2_list_of_cluster_operators_responses.go
  restapi/operations/operators/v2_list_of_cluster_operators_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2603 MGMT-7613: Move get cluster logs V1 API to V2
  client/installer/installer_client.go
  client/installer/v2_download_cluster_logs_parameters.go
  client/installer/v2_download_cluster_logs_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_download_cluster_logs.go
  restapi/operations/installer/v2_download_cluster_logs_parameters.go
  restapi/operations/installer/v2_download_cluster_logs_responses.go
  restapi/operations/installer/v2_download_cluster_logs_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2631 MGMT-6763: Add support for dual-stack CI jobs
  deploy/operator/ztp/agentClusterInstall.j2
  deploy/operator/ztp/assisted-installer-crds-playbook.yaml
  deploy/operator/ztp/deploy_spoke_cluster.sh
Labels: approved, size/S, lgtm

#2585 MGMT-7790: Set SUPPORT_L2 to False from the operator
  internal/controller/controllers/agentserviceconfig_controller.go
Labels: approved, size/XS, lgtm

#2622 NO-ISSUE: fixing the name and the message of the status info for Unbo…
  internal/host/common.go
  internal/host/pool_host_statemachine.go
  internal/host/transition_test.go
Labels: approved, size/S, lgtm

#2620 MGMT-7806: Change host events API in order to solve segmentation fault
  docs/events.yaml
  internal/bminventory/inventory.go
  internal/common/events/events.go
  internal/events/event.go
  internal/host/host.go
  internal/host/host_test.go
  tools/generate_events.py
Labels: approved, size/L, lgtm

#2644 MGMT-7780: Late Binding Kube API documentation
  docs/hive-integration/README.md
  docs/hive-integration/crds/infraEnvLateBinding.yaml
  docs/hive-integration/late-binding.md
Labels: approved, size/M, lgtm

#2645 MGMT-7840: Document events usage
  docs/dev/events.md
Labels: approved, size/M, lgtm

#2647 Monitor logs
  cmd/main.go
  internal/cluster/cluster.go
  openshift/template.yaml
  pkg/app/middleware.go
  pkg/app/middleware_test.go
  pkg/commonutils/common_utils.go
  pkg/thread/thread.go
Labels: approved, size/L, lgtm

#2643 NO-ISSUE: Fixing default values for disk-encryption on cluster creation.
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validations.go
Labels: approved, size/M, lgtm

#2648 MGMT-7698: KubeAPI subsystem - restore upload logs tests
  subsystem/kubeapi_test.go
Labels: approved, size/L, lgtm

#2651 NO-ISSUE: Fix olm skip range
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
Labels: approved, size/XS, lgtm

#2634 OCPBUGSM-35242: Set x86_64 as the default architecture for OsImages and ReleaseImages
  models/os_image.go
  models/release_image.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/S, api-review, lgtm

#2636 NO-ISSUE: Print resources for easy debugging of operator installation
  deploy/operator/gather.sh
Labels: approved, size/XS, lgtm

#2632 MGMT-7282: Operator upgrade readme
  deploy/operator/upgrade/README.md
Labels: approved, size/M, lgtm

#2641 MGMT-7421: Adding feature usage for disk-encryption.
  internal/bminventory/inventory.go
  internal/usage/consts.go
  subsystem/cluster_test.go
Labels: approved, size/S, lgtm

#2650 MGMT-7847: Remove SUPPORT_L2 env var
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/host/hostcommands/api_vip_connectivity_check_cmd.go
  internal/host/hostcommands/api_vip_connectivity_check_cmd_test.go
  internal/host/hostcommands/instruction_manager.go
  models/api_vip_connectivity_request.go
  openshift/template.yaml
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/S, api-review, lgtm

#2628 MGMT-7258: Use image service in assisted service
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
Labels: approved, size/L, lgtm

#2635 MGMT-7315: Allow providing machine networks for multi-node non-DHCP
  deploy/operator/ztp/assisted-installer-crds-playbook.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/network/cidr_validations.go
Labels: approved, size/L, lgtm

#2649 MGMT-7223: Changes for adding remote worker node jobs
  deploy/operator/ztp/add-remote-nodes-playbook.yaml
  deploy/operator/ztp/add_day2_remote_nodes.sh
  deploy/operator/ztp/assisted-installer-crds-playbook.yaml
  deploy/operator/ztp/baremetalHost.j2
Labels: approved, size/M, lgtm

#2640 MGMT-7687: Propagate Infrastructure Operator node selection and tolerations to its workloads
  cmd/operator/main.go
  config/manager/manager.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  internal/controller/controllers/agentserviceconfig_controller.go
Labels: approved, size/M, lgtm

#2657 MGMT-7282: Use community operators to install AI operator for ocm-2.3
  deploy/operator/setup_assisted_operator.sh
  deploy/operator/upgrade/before_upgrade.sh
  deploy/operator/upgrade/upgrade.sh
Labels: approved, size/S, lgtm

#2656 Bug 2006549: Pass CA certificate to the UploadLogsCmd
  internal/host/hostcommands/logs_cmd.go
Labels: approved, bugzilla/severity-unspecified, size/XS, lgtm, bugzilla/valid-bug

#2637 MGMT-4872: Generate Image Expirer Event
  docs/events.yaml
  internal/common/events/events.go
  internal/imgexpirer/imgexpirer.go
  internal/imgexpirer/imgexpirer_test.go
Labels: approved, size/M, lgtm

#2599 MGMT-7732: Late binding - support move agent
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, lgtm

#2639 MGMT-4872: Generate event for disk quick format
  docs/events.yaml
  internal/common/events/events.go
  internal/events/eventstest/events_test_utils.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/L, lgtm

#2659 MGMT-7282: Update operator using subscription channel
  deploy/operator/upgrade/after_upgrade.sh
  deploy/operator/upgrade/before_upgrade.sh
  deploy/operator/upgrade/upgrade.sh
Labels: approved, size/M, lgtm

#2638 MGMT-4872: Generate event for operator status
  docs/events.yaml
  internal/common/events/events.go
  internal/operators/handler/handler.go
  internal/operators/handler/handler_test.go
Labels: approved, size/L, lgtm

#2662 Bug 2007515: Pass copy-network when infraEnv.StaticNetworkConfig is set
  internal/common/db.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/instruction_manager_test.go
Labels: approved, size/L, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#2667 Bug 2007515: Fix regression introduced by copy-network bugfix
  internal/common/db.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/instruction_manager_test.go
Labels: approved, size/S, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#2668 MGMT-7867: Use default ImagePullPolicy behaviour from OCP
  internal/controller/controllers/agentserviceconfig_controller.go
Labels: approved, size/S, lgtm

#2663 Bug 2007539: Pass copy-network when infraEnv.StaticNetworkConfig is set
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/instruction_manager_test.go
Labels: approved, size/L, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#2669 NO-ISSUE - Increase operator deployment wait-for-service-pod-ready timeout
  deploy/operator/utils.sh
Labels: approved, size/XS, lgtm

#2670 Fix OCP bump job by updating assigned user
  tools/ocp_version_update/Jenkinsfile.default_release_update
  tools/ocp_version_update/update_default_release_versions_to_latest.py
Labels: approved, size/S, lgtm

#2584 MGMT-7599: Add documentation on the repository CI
  CONTRIBUTING.md
  README.md
  docs/dev/running-test.md
  docs/dev/testing.md
Labels: approved, size/L, lgtm

#2671 MGMT-7871: added default arm64 OS/Release images
  config/manager/manager.yaml
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  onprem-environment
  openshift/template.yaml
Labels: approved, size/M, lgtm

#2546 Add Providers Support - enhancement implementation
  cmd/main.go
  go.sum
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/platform.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostrole_test.go
  internal/host/monitor_test.go
  internal/host/refresh_status_preprocessor.go
  internal/host/transition_test.go
  internal/host/validations_test.go
  internal/host/validator.go
  internal/installcfg/builder/builder.go
  internal/installcfg/builder/builder_test.go
  internal/installcfg/builder/mock_installcfg.go
  internal/installcfg/installcfg.go
  internal/provider/baremetal/base.go
  internal/provider/baremetal/consts.go
  internal/provider/baremetal/installConfig.go
  internal/provider/baremetal/inventory.go
  internal/provider/base.go
  internal/provider/mock_base_provider.go
  internal/provider/registry/mock_providerregistry.go
  internal/provider/registry/mock_registry.go
  internal/provider/registry/registry.go
  internal/provider/registry/registry_test.go
  internal/provider/vsphere/base.go
  internal/provider/vsphere/consts.go
  internal/provider/vsphere/installConfig.go
  internal/provider/vsphere/inventory.go
Labels: approved, lgtm, size/XXL

#2676 use /cc command to set reviewers for ocp bump PRs
  tools/ocp_version_update/update_default_release_versions_to_latest.py
Labels: approved, size/S, lgtm

#2610 Bug 2009349: Adds InfraEnv Register Deregister events
  docs/events.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/events/events.go
  internal/events/eventstest/events_test_utils.go
Labels: approved, size/L, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#2675 Bug 2009204: Add error msg to InfraEnv condition
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/XS, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#2680 NO-ISSUE: changed creds used in ocp bump job
  tools/ocp_version_update/Jenkinsfile.default_release_update
Labels: approved, size/XS, lgtm

#2681 MGMT-2391: Deprecate host stage_started_at and stage_updated_at fields
  internal/host/host_test.go
  internal/host/transition_test.go
  models/host.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/M, api-review, lgtm
