Repository openshift/assisted-service, pull requests merged in 2021-06, with the labels that each got.

#1836 Bug 1964591: Remove AI Agent image in case of service failure
  internal/ignition/ignition.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1860 NO-ISSUE Periodic GC log to debug
  internal/garbagecollector/garbageCollector.go
Labels: approved, lgtm

#1818 MGMT-6550 Move SNO requiremets to versioned host requiremens configuration
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_hw_requirements.json
  docs/dev/hardware-requirements.md
  internal/bminventory/inventory.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/hardware/mock_validator.go
  internal/hardware/validator.go
  internal/hardware/validator_test.go
  internal/hardware/versioned-requirements.go
  internal/hardware/versioned-requirements_test.go
  internal/host/transition_test.go
  models/versioned_host_requirements.go
  onprem-environment
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1819 MGMT-6605 Create disks with WWN
  deploy/operator/libvirt_disks.sh
  deploy/operator/setup_lso.sh
  deploy/operator/utils.sh
Labels: approved, lgtm

#1855 Bug 1947154: Kubeapi cancel install before delete
  internal/bminventory/inventory.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1882 OCPBUGSM-29832 Add HostStageWaitingForBootkube ad HostStageWaitingForContro…
  internal/host/host.go
Labels: approved, lgtm

#1861 BUG 1965990: Keep Image URL for existing image with auth=local + S3
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/controller/controllers/infraenv_controller.go
  subsystem/kubeapi_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1863 NO-ISSUE Check commit for bugzilla prefix
  tools/check-commit-message.sh
Labels: approved, lgtm

#1866 MGMT-4189 - block in update cluster setting API VIP DHCP allocation when user_managed_network is set
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#1871 OCPBUGSM-29621 Unify client Scheme registration
  cmd/main.go
  internal/controller/controllers/bmh_agent_controller_test.go
  internal/controller/controllers/common.go
  internal/controller/controllers/spoke_cluster.go
Labels: approved, lgtm

#1874 enable defining public registries that should not be validated against PS
  deploy/operator/setup_assisted_operator.sh
Labels: approved, lgtm

#1883 NO-ISSUE Fix host metrics stage label on ELK
  internal/metrics/metricsManager.go
  subsystem/metrics_test.go
Labels: approved, lgtm

#1875 migrating gathering logic to assisted-service
  deploy/operator/gather.sh
Labels: approved, lgtm

#1811 MGMT-6014: Missing VIP values in SNO cluster
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, lgtm

#1886 Bug 1965356 - Add `name: master` to the InstallConfig override example
  docs/Kube-API.md
Labels: approved, lgtm

#1870 Bug 1966268 - remove default.nmconnection as a WA for NM priority issue
  internal/constants/scripts.go
  internal/ignition/ignition.go
Labels: approved, lgtm

#1878 Bug 1966485: [operator] Wait for CVO to be ready before marking as done
  internal/controller/controllers/agentserviceconfig_controller.go
  openshift/template.yaml
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1887 NO-ISSUE Enhance subsystem waitForState functions
  subsystem/cluster_test.go
Labels: approved, lgtm

#1864 Bug 1965026: Configure IPv6 DHCP in dual-stack
  internal/host/hostcommands/install_cmd.go
  internal/host/hostutil/host_utils.go
  internal/host/hostutil/host_utils_test.go
  internal/ignition/ignition.go
  internal/network/utils.go
  internal/network/utils_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1880 MGMT-6765 document how to run ZTP workflow
  deploy/operator/README.md
Labels: approved, lgtm

#1889 Bug 1966697: Periodic GC log to debug level
  internal/cluster/cluster.go
  internal/garbagecollector/garbageCollector.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1897 NO-ISSUE: Fixing typo in stage telemeter URL.
  internal/network/manifests_generator.go
Labels: approved, lgtm

#1898 Bug 1967121: Docs should clarify that the pullSecretRef is currently ignored
  docs/Kube-API.md
  docs/crds/infraEnv.yaml
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1907 NO-ISSUE: Extend waiting for pod to 20 minutes
  deploy/operator/utils.sh
Labels: approved, lgtm

#1895 MGMT-6286 install AI operator on disconnected env
  deploy/operator/deploy.sh
  deploy/operator/libvirt_disks.sh
  deploy/operator/mirror_utils.sh
  deploy/operator/setup_assisted_operator.sh
  deploy/operator/setup_hive.sh
  deploy/operator/setup_lso.sh
Labels: approved, lgtm

#1909 Bug 1965356: Change install config override example to OVNKubernetes
  docs/Kube-API.md
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1901 OCPBUGSM-29871 SNO node cannot transition into "Writing image to disk…
  go.mod
  go.sum
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostutil/test_utils.go
Labels: approved, lgtm

#1872 Bug 1963684: Return zero for DiskSize for OCS GetHostRequirements
  internal/operators/ocs/ocs_operator.go
  internal/operators/ocs/ocs_operator_test.go
  subsystem/cluster_test.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1899 OCPBUGSM-29957: InfraEnv should log the amount of NMstate Configs baked into the image
  internal/controller/controllers/infraenv_controller.go
Labels: approved, lgtm

#1873 MGMT-6607: (OCS) remove resource checks in ValidateHost
  internal/operators/ocs/ocs_operator.go
  internal/operators/ocs/ocs_operator_test.go
Labels: approved, lgtm

#1906 OCPBUGSM-29525 Assisted installer chrony manifests missing index numbering
  internal/network/manifests_generator.go
Labels: approved, lgtm

#1846 MGMT-6533: Skip "Token used before issued" validation in jwt-go.
  internal/cluster/validations/validation_test.go
  pkg/auth/auth_handler_test_utils.go
  pkg/auth/authenticator_test.go
  pkg/auth/authz_handler_test.go
  pkg/auth/local_authenticator_test.go
  pkg/auth/rhsso_authenticator.go
  pkg/auth/rhsso_authenticator_test.go
Labels: approved, lgtm

#1915 Fix docs to make use of 'EXTRA_WORKER_<X>' configurations
  deploy/operator/README.md
Labels: approved, lgtm

#1908 NO-ISSUE: Fixing metrics subsystem-test's spamming.
  Makefile
  subsystem/metrics_test.go
Labels: approved, lgtm

#1920 Bug 1967842: Removed log messages from OCS cluster validation to prevent spamming of logs.
  internal/operators/ocs/ocs_operator.go
  internal/operators/ocs/validations.go
Labels: approved, bugzilla/severity-urgent, bugzilla/valid-bug, lgtm

#1923 NO-ISSUE: ztp flow output log to file
  deploy/operator/gather.sh
Labels: approved, lgtm

#1919 NO-ISSUE Add mkowalski to OWNERS/code-reviewers
  OWNERS_ALIASES
Labels: approved, lgtm

#1924 NO-ISSUE: ztp flow download log as insecure
  deploy/operator/gather.sh
Labels: approved, lgtm

#1910 NO-ISSUE Fix spelling in the PR template
  docs/pull_request_template.md
Labels: approved, lgtm

#1914 NO-ISSUE Add mkowalski to OWNERS/code-reviewers
  OWNERS_ALIASES
Labels: approved, lgtm

#1926 Bug 1968067: KubeAPI add all none-success validations to conditions
  docs/kube-api-conditions.md
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/conditions.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1890 MGMT-6775 Bump OCP versions 4.7.11 -> 4.7.12, 4.8.0-fc.3 -> 4.8.0-fc.7
  config/manager/manager.yaml
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_ocp_versions.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#1900 Bug 1966546: KubeAPI keep day1 cluster after install
  Makefile
  docs/Kube-API.md
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/kubeapi_test.go
  tools/deploy_assisted_installer_configmap.py
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1912 Bug 1967423: CD ctrl reqeueue after 1m when failing with AddOpenshiftVersion
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1928 MGMT-6832, Bump OCP versions 4.7.12 -> 4.7.13
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_ocp_versions.json
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#1936 NO-ISSUE: Add to deployment status dashboard installation status
  dashboards/grafana-dashboard-assisted-installer-deployment-overview.configmap.yaml
Labels: approved, lgtm

#1938 OCPBUGSM-30068: Revert "Docs should clarify that the pullSecretRef is currently ignored (#1898)"
  docs/Kube-API.md
  docs/crds/infraEnv.yaml
Labels: approved, lgtm

#1940 NO-ISSUE: Fix grafana dashboard annotation
  dashboards/grafana-dashboard-assisted-installer-deployment-overview.configmap.yaml
Labels: approved, lgtm

#1921 NO-ISSUE: Add djzager to ci-reviewers
  OWNERS_ALIASES
Labels: approved, lgtm

#1918 MGMT-6749: Automate ocm-2.3 tag for quay.io/ocpmetal
  Jenkinsfile
Labels: approved, lgtm

#1935 NO-ISSUE Add CI to the list of environments for the PR template
  docs/pull_request_template.md
Labels: approved, lgtm

#1944 [ocm-2.3] Bug 1966947: Unify client Scheme registration
  cmd/main.go
  internal/controller/controllers/bmh_agent_controller_test.go
  internal/controller/controllers/common.go
  internal/controller/controllers/spoke_cluster.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1930 move provisioning configuration for watching all namespaces to hub deployment
  deploy/operator/README.md
  deploy/operator/setup_assisted_operator.sh
  deploy/operator/ztp/deploy_spoke_cluster.sh
Labels: approved, lgtm

#1934 [ocm-2.3] Bug 1967633: SNO node cannot transition into "Writing image to disk" …
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostutil/test_utils.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1937 OCPBUGSM-29808: Wait for REST api before starting controllers
  cmd/main.go
Labels: approved, lgtm

#1947 Enable AlphaAgentInstallStrategy feature of hive in CI
  deploy/operator/setup_hive.sh
Labels: approved, lgtm

#1948 OCPBUGSM-30084: Always disable inspection and cleaning for BMH
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, lgtm

#1953 NO-ISSUE: Fix bug in the date for ocm tag
  Jenkinsfile
Labels: approved, lgtm

#1946 [ocm-2.3] Bug 1966989: asc controller log line
  internal/controller/controllers/agentserviceconfig_controller.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1959 OCPBUGSM-30087: Fix doc for installconfig on ACI
  docs/Kube-API.md
Labels: approved, lgtm

#1956 NO-ISSUE Doc update: add example to print ACI conditions
  docs/Kube-API.md
Labels: approved, lgtm

#1965 Update ocm-2.3 branch with limited approvers
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm

#1963 NO-ISSUE: ZTP flow gather agents CRDs data
  deploy/operator/gather.sh
Labels: approved, lgtm

#1967 NO-ISSUE Use `annotate` instead of `apply` for AgentServiceConfig annotation
  docs/operator.md
Labels: approved, lgtm

#1902 assisted-service-operator: bundle versions
  Makefile
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/metadata/annotations.yaml
Labels: approved, lgtm

#1961 OCPBUGSM-30145: Missing request ID field on image uploading logs
  cmd/main.go
Labels: approved, lgtm

#1955 MGMT-6849: Remove vmware vxlan tunnel offloading patch because it is done by OCP
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/network/manifests_generator.go
  internal/network/mock_manifests_generator.go
Labels: approved, lgtm

#1954 MGMT-6848, Bump OCP versions 4.8.0-fc.7 -> 4.8.0-fc.8
  config/manager/manager.yaml
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_ocp_versions.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#1964 OCPBUGSM-29819: Installation fails after cancel and reset of installation before node reboot
  pkg/generator/generator.go
Labels: approved, lgtm

#1969 MGMT-6707: Move cluster status update to central function
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/common.go
  internal/cluster/installer.go
  internal/cluster/installer_test.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
Labels: approved, lgtm

#1973 NO-ISSUE move check-commit from tools to hack directory
  CONTRIBUTING.md
  Makefile
  hack/check-commit-message.sh
  hack/check-commits.sh
Labels: approved, lgtm

#1958 OCPBUGSM-29458: Check the response status code from http.Get
  pkg/s3wrapper/util.go
  pkg/s3wrapper/util_test.go
Labels: approved, lgtm

#1807 MGMT-6607: Fix OCS Validations to conform with the expected behavior
  internal/operators/ocs/consts.go
  internal/operators/ocs/manifest.go
  internal/operators/ocs/manifests_test.go
  internal/operators/ocs/ocs_operator.go
  internal/operators/ocs/ocs_operator_test.go
  internal/operators/ocs/validation_test.go
  internal/operators/ocs/validations.go
  subsystem/cluster_test.go
Labels: approved, lgtm

#1862 Bug 1969304: Don't queue BMH reconcile if the InfraEnv URL hasn't changed
  internal/controller/controllers/bmh_agent_controller.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1943 OCPBUGSM-30082: Don't reconcile BMH in a detached state
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, lgtm

#1980 OCPBUGSM-30278: disable metrics event when deploying via operator
  internal/controller/controllers/controller_event_wrapper.go
Labels: approved, lgtm

#1972 OCPBUGSM-30346: Populate State and StateInfo and move to DebugInfo in CRDs
  config/crd/bases/agent-install.openshift.io_agents.yaml
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  internal/controller/api/hiveextension/v1beta1/agentclusterinstall_types.go
  internal/controller/api/v1beta1/agent_types.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1941 OCPBUGSM-30056: host namespace on agent update notification
  cmd/main.go
  internal/common/db.go
  internal/controller/controllers/controller_event_wrapper.go
  internal/controller/controllers/controller_event_wrapper_test.go
  internal/controller/controllers/controllers_suite_test.go
  internal/controller/controllers/crd_utils.go
  internal/controller/controllers/crd_utils_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/host/hostutil/test_utils.go
  internal/host/mock_host_api.go
  subsystem/kubeapi_test.go
Labels: api-review, approved, lgtm

#1983 ZTP CI gather more CRDs
  deploy/operator/gather.sh
Labels: approved, lgtm

#1867 MGMT-6747 Media disconnection: Mark host as failed and show an Indicative error
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#1982 OCPBUGSM-30179: Remove unused fields in CRDs
  config/crd/bases/agent-install.openshift.io_agents.yaml
  config/crd/bases/agent-install.openshift.io_infraenvs.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
  internal/controller/api/v1beta1/agent_types.go
  internal/controller/api/v1beta1/infraenv_types.go
  internal/controller/api/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm

#1971 OCPBUGSM-30146 - Fixing the issue with missing data in /etc/resolv.conf after reboot of SNO host
  internal/network/manifests_generator.go
Labels: approved, lgtm

#1976 Bug 1970494: asc controller log line (#1946)
  internal/controller/controllers/agentserviceconfig_controller.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1957 MGMT-6647: Allow wildcard NoProxy with OCP 4.8+
  go.mod
  internal/bminventory/inventory.go
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
Labels: approved, lgtm

#1978 Bug 1969315: Don't queue BMH reconcile if the InfraEnv URL hasn't changed
  internal/controller/controllers/bmh_agent_controller.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#1788 Revert "Revert "MGMT-5430 Move assisted service image to stream8""
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, lgtm

#1932 OCPBUGSM-30014: Cluster folder should be cleared from FS
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
Labels: approved, lgtm

#1988 OCPBUGSM-30853: Change default telemeter server of installed clusters to prod.
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
  subsystem/manifests_test.go
Labels: approved, lgtm

#1974 NO-ISSUE: Change default value for BMH_DETACHED_ANNOTATION
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, lgtm

#2008 NO-ISSUE: Use /cc instead of /assign to link PRs to users
  docs/pull_request_template.md
Labels: approved, lgtm

#1865 MGMT-6024 Merge setupNewHost subsystem utility with registerNode
  subsystem/cluster_test.go
  subsystem/kubeapi_test.go
  subsystem/utils_test.go
Labels: approved, lgtm

#1996 Bug 1969796: Fix logline containing ConfigMap for AgentServiceConfig
  internal/controller/controllers/agentserviceconfig_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1994 OCPBUGSM-30076: Add role, bootstrap and ntp sources to Agent CR
  config/crd/bases/agent-install.openshift.io_agents.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
  internal/controller/api/v1beta1/agent_types.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#2000 OCPBUGSM-29737 - disable /etc/resolve.conf handling by NM during boot…
  internal/common/common.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
Labels: approved, lgtm

#2006 Gather hive logs on CI
  deploy/operator/gather.sh
  deploy/operator/setup_hive.sh
Labels: approved, lgtm

#2014 NO-ISSUE: Make operator deploy.sh exit in case of error
  deploy/operator/deploy.sh
Labels: approved, lgtm

#2017 Fix hive installation to create namespace and OperatorGroup
  deploy/operator/setup_hive.sh
Labels: approved, lgtm

#1990 UpdateCluster changes for REST API
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  internal/network/machine_network_cidr.go
  subsystem/cluster_test.go
Labels: approved, lgtm

#2002 OCPBUGSM-30063: Bug 1968125: AgentServiceConfig examples in operator.md doc should each contain databaseStorage + filesystemStorage
  docs/operator.md
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1950 MGMT-6286: add image mirroring in service installation automation for CI
  deploy/operator/deploy.sh
  deploy/operator/mirror_utils.sh
  deploy/operator/setup_assisted_operator.sh
Labels: approved, lgtm

#2003 Bug 1971589: Change default telemeter server of installed clusters to prod. (#1988)
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
  subsystem/manifests_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1995 MGMT-6628: Exposing the deregistration time on cluster API.
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  models/cluster_default_config.go
  restapi/embedded_spec.go
  subsystem/cluster_default_config_test.go
  subsystem/subsystem_suite_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#2024 NO-ISSUE: Add lranjbar to OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, lgtm

#1997 OCPBUGSM-30211: cache image fetched from release
  internal/oc/release.go
  internal/oc/release_test.go
Labels: approved, lgtm

#1999 Bug 1971162: OCS check if the disks are Installation eligible
  internal/operators/manager_test.go
  internal/operators/ocs/ocs_operator_test.go
  internal/operators/ocs/validation_test.go
  internal/operators/ocs/validations.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2004 OCPBUGSM-30350: Add Progress info to Agent Status
  config/crd/bases/agent-install.openshift.io_agents.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
  internal/controller/api/v1beta1/agent_types.go
  internal/controller/api/v1beta1/zz_generated.deepcopy.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#2012 MGMT-6942: Bump OCP versions 4.8.0-fc.8 -> 4.8.0-fc.9
  config/manager/manager.yaml
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_ocp_versions.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#2019 MGMT-6806 Rename DEBUG and DEBUG_PORT flags to DEBUG_SERVICE and DEBU…
  Dockerfile.assisted-service-debug
  Makefile
  docs/dev/debug.md
  hack/update_local_image.sh
  skipper.env
Labels: approved, kind/dependency-change, lgtm

#2028 NO-ISSUE Add results to cluster.installation.results internal event
  internal/metrics/metricsManager.go
Labels: approved, lgtm

#2026 Bug 1967956: Propagate proxy config to service
  internal/controller/controllers/agentserviceconfig_controller.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2021 Bug 1968124: Clarify "Mirror Registry Configuration" doc
  docs/operator.md
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#1993 Bug 1972096: Use .invalid domain instead of dummy.com
  internal/bminventory/inventory_test.go
  internal/cluster/cluster_test.go
  internal/common/test_configuration.go
  internal/host/host_test.go
  internal/network/manifests_generator.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1853 MGMT-6712: Enable host validations for network latency and packet loss
  Makefile
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_hw_requirements.json
  deploy/assisted-service-configmap.yaml
  docs/dev/hardware-requirements.md
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/hardware/validator_test.go
  internal/host/host.go
  internal/host/hostutil/test_utils.go
  internal/host/transition_test.go
  onprem-environment
  openshift/template.yaml
  skipper.env
  subsystem/cluster_test.go
  subsystem/day2_cluster_test.go
  subsystem/utils_test.go
  tools/deploy_assisted_installer_configmap.py
Labels: approved, lgtm

#2005 MGMT-4585: Enable flexible scaling for OCS
  internal/operators/ocs/manifest.go
  internal/operators/ocs/validation_test.go
  internal/operators/ocs/validations.go
Labels: approved, lgtm

#1975 OCPBUGSM-30121: Add Image CreatedAt to InfraEnv status
  config/crd/bases/agent-install.openshift.io_infraenvs.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
  internal/controller/api/v1beta1/infraenv_types.go
  internal/controller/api/v1beta1/zz_generated.deepcopy.go
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1998 Bug 1968425: Apply labels from infraenv to Agents
  config/crd/bases/agent-install.openshift.io_infraenvs.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
  docs/crds/infraEnv.yaml
  internal/controller/api/v1beta1/infraenv_types.go
  internal/controller/api/v1beta1/zz_generated.deepcopy.go
  internal/controller/controllers/crd_utils.go
  internal/controller/controllers/crd_utils_test.go
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2040 OCPBUGSM-30258: Fix empty cluster name after applying InfraEnv.yaml
  internal/controller/controllers/infraenv_controller.go
Labels: approved, lgtm

#2022 OCPBUGSM-30887: InfraEnv should always requeue on HTTP 409 backend response
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
Labels: approved, lgtm

#2020 OCPBUGSM-30089 parsing error indication for config override
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, lgtm

#1885 MGMT-6764 Apply timeouts for waiting for amount of agents and waiting for agentclusterinstall to be completed
  deploy/operator/setup_hive.sh
  deploy/operator/utils.sh
  deploy/operator/ztp/deploy_spoke_cluster.sh
Labels: approved, lgtm

#2023 OCPBUGSM-30324: AI KubeAPI AgentClusterInstall confusing "Validated" condition about VIP not matching machine network
  internal/cluster/transition_test.go
  internal/cluster/validator.go
Labels: approved, lgtm

#2036 MGMT-7045: Bump OCP versions 4.7.13 -> 4.7.16, 4.8.0-fc.9 -> 4.8.0-rc.0, rchos 4.7.7 -> 4.7.13
  config/manager/manager.yaml
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_ocp_versions.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#2039 MGMT-6806 - Enable remote debugging on Beaker hosts
  Makefile
  hack/setup_env.sh
  skipper.env
Labels: approved, lgtm

#2009 OCPBUGSM-29588: ACM/ZTP with Wan emulation, several clusters fail to step past discovery
  cmd/main.go
  internal/host/hostcommands/free_addresses_cmd.go
  internal/host/hostcommands/free_addresses_cmd_test.go
  internal/host/hostcommands/instruction_manager.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/host/hostcommands/noop_cmd.go
Labels: approved, lgtm

#2051 OCPBUGSM-30844 NTP status is Unreachable after disable - enable host
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, lgtm

#1888 Bug 1964623: Tune FS disk usage log messages
  pkg/s3wrapper/filesystem.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2046 Bug 1972525: CD controller to notify InfraEnv for backend cluster registration
  internal/controller/controllers/clusterdeployments_controller.go
  subsystem/kubeapi_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2018 OCPBUGSM-30296: Delete unregistered hosts agents by namespace
  internal/bminventory/inventory.go
  internal/bminventory/mock_installer_internal.go
  internal/common/db.go
  internal/controller/controllers/agent_controller.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/mock_host_api.go
Labels: approved, lgtm

#2041 Bug 1969547: Create KubeConfig Secret when install starts
  internal/bminventory/inventory.go
  internal/bminventory/mock_installer_internal.go
  internal/constants/files.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2045 OCPBUGSM-30203: remove cluster_id from prometheus metrics + update tests
  go.mod
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_metrics_manager_api.go
Labels: approved, lgtm

#2062 NO-ISSUE Adding sagidayan as a code-reviewer
  OWNERS_ALIASES
Labels: approved, lgtm

#2069 NO-ISSUE: Update BMAC documentation
  docs/baremetal-agent-controller.md
Labels: approved, lgtm

#2011 Bug 1972262: Change default value for BMH_DETACHED_ANNOTATION
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2044 NO-ISSUE: increase timeout of waiting for pod for disconnected flow
  deploy/operator/utils.sh
Labels: approved, lgtm

#2047 NO-ISSUE: Fix a PR template typo
  docs/pull_request_template.md
Labels: approved, lgtm

#2053 Bz1974085 wrong ip network latency validation
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, lgtm

#2052 MGMT-5171: Deploy assisted operator in disconnected ipv6 env
  deploy/operator/deploy.sh
  deploy/operator/libvirt_disks.sh
  deploy/operator/mirror_utils.sh
  deploy/operator/setup_assisted_operator.sh
  deploy/operator/setup_hive.sh
  deploy/operator/setup_lso.sh
Labels: approved, lgtm

#2074 Bug 1968423: Document kube api teardown process
  docs/Kube-API.md
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#2064 BUG 1971311: remove cluster_id from prometheus metrics + update te…
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_metrics_manager_api.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2072 Bug 1970395: Create KubeConfig Secret when install starts (#2041)
  internal/bminventory/inventory.go
  internal/bminventory/mock_installer_internal.go
  internal/constants/files.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#2085 NO-ISSUE: Elaborate assisted-service tests documentation
  README.md
Labels: approved, lgtm

#2077 OCPBUGSM-31316: decrease poll interval for check NTP source
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#2070 Bug 1974501: infrastructure operator rename
  config/manager/manager.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  docs/operator.md
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#2079 NO-ISSUE: Remove duplicated transition tests
  internal/cluster/transition_test.go
Labels: approved, lgtm, ok-to-test

#2032 Bug 1968552: Wait for ISO for 1 minute before using it
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#2034 NO-ISSUE: Add pawanpinjarkar to code-reviewers
  OWNERS_ALIASES
Labels: approved, lgtm

#2061 OCPBUGSM-30767: AI Pods throws errors cannot access the media (ISO) - me…
  internal/bminventory/inventory.go
Labels: approved, lgtm

#2071 MGMT-7054: Use Minio over scality
  .golangci.yml
  Makefile
  README.md
  deploy/s3/deployment.yaml
  deploy/s3/public-secret.yaml
  deploy/s3/pvc.yaml
  deploy/s3/scality-deployment.yaml
  deploy/s3/secret.yaml
  pkg/s3wrapper/client.go
  pkg/s3wrapper/client_test.go
  tools/deploy_s3.py
  tools/deploy_s3_secrets.py
Labels: approved, lgtm

#2078 Bug 1975218: Move conditions const to CRDs
  internal/controller/api/hiveextension/v1beta1/agentclusterinstall_types.go
  internal/controller/api/v1beta1/agent_types.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/conditions.go
  subsystem/kubeapi_test.go
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#2082 MGMT-7074: Update OCM sdk version
  go.mod
  go.sum
Labels: approved, lgtm
