Repository openshift/assisted-service, pull requests merged in 2021-02, with the labels that each got.

#998 OCPBUGSM-23927 - correct openshift version recieved for day2 cluster …
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/versions/mock_versions.go
  internal/versions/versions.go
  internal/versions/versions_test.go
Labels: approved, lgtm

#996 MGMT-3721 ClusterDeployments support creation
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/common.go
Labels: approved, lgtm

#980 MGMT-2662 re-enable the baremetalProvisioningConfig
  internal/bminventory/inventory_test.go
  internal/common/version.go
  internal/ignition/ignition.go
  internal/installcfg/installcfg.go
Labels: approved, lgtm

#978 MGMT-3358 Image CRD to use ClusterReference instead of ObjectReference
  internal/controller/api/v1alpha1/image_types.go
  internal/controller/api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/config/crd/bases/adi.io.my.domain_images.yaml
  internal/controller/controllers/image_controller.go
  internal/controller/controllers/image_controller_test.go
Labels: approved, lgtm

#1001 OCPBUGSM-23927 - correct openshift version recieved for day2 cluster …
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/versions/mock_versions.go
  internal/versions/versions.go
  internal/versions/versions_test.go
Labels: approved, lgtm

#1005 MGMT-3872 Fix s3 url for boot files
  pkg/s3wrapper/client.go
  pkg/s3wrapper/client_test.go
Labels: approved, lgtm

#999 MGMT-3862 update KubeAPI Image with recent StaticIPConfig changes
  internal/controller/api/v1alpha1/image_types.go
  internal/controller/api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/config/crd/bases/adi.io.my.domain_images.yaml
  internal/controller/controllers/image_controller.go
Labels: approved, lgtm

#991 MGMT-3658: Generate event/metric in case an host validation is changing. (#952)
  internal/host/host.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_metrics_manager_api.go
  subsystem/cluster_test.go
  subsystem/day2_cluster_test.go
  subsystem/metrics_test.go
  subsystem/utils_test.go
Labels: approved, lgtm

#1004 NO-ISSUE Add generateEssentialHostStep function for subsystem tests
  internal/bminventory/inventory_test.go
  internal/common/test_configuration.go
  internal/host/host_test.go
  internal/host/transition_test.go
  internal/network/manifests_generator_test.go
  subsystem/cluster_test.go
  subsystem/day2_cluster_test.go
  subsystem/ipv6_test.go
  subsystem/kubeapi_test.go
  subsystem/metrics_test.go
  subsystem/utils_test.go
Labels: approved, lgtm

#1007 OCPBUGSM-19591 Host connectivity validation fails when only 2 nodes booted
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, lgtm

#637 MGMT-2424, MGMT-2275 OCS validations
  cmd/main.go
  go.mod
  go.sum
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/refresh_status_preprocessor.go
  internal/cluster/statemachine.go
  internal/cluster/transition_test.go
  internal/cluster/validation_id.go
  internal/cluster/validator.go
  internal/host/host.go
  internal/host/mock_host_api.go
  internal/ignition/dummy.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/operators/ocs/mock_validations.go
  internal/operators/ocs/utils.go
  internal/operators/ocs/validations.go
  pkg/job/job.go
  pkg/job/local_job.go
Labels: api-review, approved, lgtm

#1000 MGMT-3721 ClusterDeployments support update
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/error_utils.go
Labels: approved, lgtm

#1002 MGMT-3856 - Add API for domain resolution step
  models/domain_resolution_request.go
  models/domain_resolution_response.go
  models/step_type.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1008 MGMT-3576 Add timeout to log sender
  internal/host/hostcommands/logs_cmd.go
Labels: approved, lgtm

#1014 MGMT-3721 ClusterDeployments support cluster installation
  go.mod
  go.sum
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, lgtm

#1016 MGMT-3576 Fix logs_cmd timeout test
  internal/host/hostcommands/instruction_manager_test.go
  internal/host/hostcommands/logs_cmd_test.go
Labels: approved, lgtm

#1015 MGMT-3826 - Versions JSON validation exception for specific single-node version
  tools/handle_ocp_versions.py
Labels: approved, lgtm

#1017 OCPBUGSM-23207 - Overwrite the default value of host_networks
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#1018 NO-ISSUE: Temporarily removing a flaky test until the reason is deter…
  subsystem/metrics_test.go
Labels: approved, lgtm

#1020 MGMT-3910 update OCP release from 4.7-fc.2 to 4.7-fc.4
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#1019 MGMT-3908 Port mapSecretToCluster to clusterDeployment controller
  internal/controller/controllers/clusterdeployments_controller.go
Labels: approved, lgtm

#588 NO-ISSUE add swagger changes validation to the build
  Makefile
Labels: api-review, approved, lgtm

#969 MGMT-3719 First pass of InstallationEnvironment
  internal/controller/api/v1alpha1/installenv_types.go
  internal/controller/api/v1alpha1/nmstate_config_types.go
  internal/controller/api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/config/crd/bases/adi.io.my.domain_installenvs.yaml
  internal/controller/config/crd/bases/adi.io.my.domain_nmstateconfigs.yaml
Labels: approved, lgtm

#1023 MGMT-3920 Rename Host CRD to Agent CRD
  cmd/main.go
  internal/controller/api/v1alpha1/agent_types.go
  internal/controller/api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/config/crd/bases/adi.io.my.domain_agents.yaml
  internal/controller/config/rbac/role.yaml
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, lgtm

#983 MGMT-3526 Add container image availability step
  Dockerfile.assisted-service-build
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/test_configuration.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostcommands/container_image_availability_cmd.go
  internal/host/hostcommands/container_image_availability_cmd_test.go
  internal/host/hostcommands/download_installer_cmd.go
  internal/host/hostcommands/download_installer_cmd_test.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/instruction_manager.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/host/mock_host_api.go
  internal/host/refresh_status_preprocessor.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/host/validator.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_metrics_manager_api.go
  models/host.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  subsystem/utils_test.go
  swagger.yaml
Labels: api-review, approved, kind/dependency-change, lgtm

#1028 Revert "NO-ISSUE adding gitattributes declaring generated files"
  .gitattributes
Labels: approved, lgtm

#1010 NO-ISSUE Don't recreate the s3 client for local ignition generator
  cmd/main.go
  internal/ignition/ignition_test.go
  pkg/job/local_job.go
  pkg/s3wrapper/filesystem.go
  pkg/s3wrapper/filesystem_test.go
Labels: approved, lgtm

#1033 MGMT-3920 rename host crds to agents in kustomization.yaml
  internal/controller/config/crd/kustomization.yaml
Labels: approved, lgtm

#1012 MGMT-3884: Modified OCS validations to use all disks
  internal/cluster/transition_test.go
  internal/ignition/ignition.go
  internal/operators/ocs/utils.go
  internal/operators/ocs/validations.go
Labels: approved, lgtm

#1034 MGMT-3959 Support overriding newer release images
  cmd/main.go
  deploy/assisted-service-configmap.yaml
  internal/versions/versions.go
  internal/versions/versions_test.go
  onprem-environment
  openshift/template.yaml
  tools/handle_ocp_versions.py
Labels: approved, lgtm

#1036 MGMT-3432 set high_availability_mode on cluster creation by Provision…
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, lgtm

#1037 MGMT-3370: add ENABLE_KUBE_API to skipper and configmap deployment
  Makefile
  skipper.yaml
  tools/deploy_assisted_installer_configmap.py
Labels: approved, lgtm

#1038 MGMT-3857 subsystem test for stopping installation when host disconne…
  subsystem/host_test.go
Labels: approved, lgtm

#1041 MGMT-3959 Remove OCP override flag references
  Makefile
  tools/deploy_assisted_installer_configmap.py
Labels: approved, lgtm

#1040 Get cluster server and verify cluster instead of specific minikube
  Makefile
  tools/utils.py
Labels: approved, lgtm

#1032 MGMT-3844 Limit concurrent minimal iso generations
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/isoeditor/factory.go
  internal/isoeditor/mock_factory.go
  internal/isoeditor/rhcos_test.go
  pkg/s3wrapper/client.go
  pkg/s3wrapper/client_test.go
  pkg/s3wrapper/filesystem.go
  pkg/s3wrapper/filesystem_test.go
  pkg/s3wrapper/util.go
Labels: approved, lgtm

#1057 MGMT-4033 update OCP release to 4.7-rc.0
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#1058 NO-ISSUE remove ENABLE_KUBE_API from skipper.yaml
  Makefile
  skipper.yaml
Labels: approved, lgtm

#1003 NO-ISSUE generate-from-swagger should regenerate KUBE_API manifests
  Makefile
Labels: approved, lgtm

#1060 NO-ISSUE Added michaellevy101 to code-reviewers
  OWNERS_ALIASES
Labels: approved, lgtm

#1061 MGMT-3911: Fixing 'belongs-to-majority-group' validation test.
  subsystem/metrics_test.go
Labels: approved, lgtm

#1050 NO-ISSUE Update ClusterDeplpyment CRD
  Dockerfile.test
  cmd/main.go
  go.mod
  go.sum
  internal/controller/config/crd/bases/hive.openshift.io_clusterdeployments.yaml
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, kind/dependency-change, lgtm

#1047 MGMT-3980 Update go-diskfs to expose file offset in iso
  go.mod
  go.sum
Labels: approved, lgtm

#1067 MGMT-4061: using the PULL_SECRET env-var to access the OCP image
  tools/handle_ocp_versions.py
Labels: approved, lgtm

#1062 MGMT-4013 Add generate-all Makefile target
  Makefile
  hack/generate.sh
  hack/verify-latest-onprem-config.sh
  internal/metrics/mock_metrics_manager_api.go
  skipper.yaml
Labels: approved, lgtm

#1069 MGMT-3990 Single Node integration environment invalid IP address DNS …
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/common.go
Labels: approved, lgtm

#1068 Update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: approved, lgtm

#1021 MGMT-3890 - Add default-configuration GET API call
  client/installer/get_cluster_default_config_parameters.go
  client/installer/get_cluster_default_config_responses.go
  client/installer/installer_client.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  mocks/mock_assisted_service.go
  models/cluster_default_config.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/get_cluster_default_config.go
  restapi/operations/installer/get_cluster_default_config_parameters.go
  restapi/operations/installer/get_cluster_default_config_responses.go
  restapi/operations/installer/get_cluster_default_config_urlbuilder.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1052 NO-ISSUE support macos see https://github.com/ory/dockertest/issues/212
  go.mod
  go.sum
Labels: approved, lgtm, ok-to-test

#1079 OCPBUGSM-22823 Disk formatting event is missing host name
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, lgtm

#1078 OCPBUGSM-25002 Start image availability event with hostname
  internal/host/host.go
  internal/host/host_test.go
Labels: approved, lgtm

#1053 OCPBUGSM-24603 Remove the cluster-id from http request/response metrics
  internal/metrics/recorder.go
Labels: approved, lgtm

#1059 NO-ISSUE standalone build performance improvements
  Jenkinsfile
  Makefile
  skipper.yaml
Labels: approved, lgtm, ok-to-test

#1066 MGMT-4059, Bump OCP version from 4.6.12 to 4.6.16 (auto created)
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#1064 MGMT-3966 - create system-connections-merged using overlayFS and add …
  internal/constants/scripts.go
  internal/ignition/ignition.go
Labels: approved, lgtm

#1083 NO-ISSUE add profile name to the minikube update-context command
  Makefile
Labels: approved, lgtm

#1081 Eran/mgmt 4111
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#1085 NO-ISSUE add the profile name to the minikube status command as well
  Makefile
Labels: approved, lgtm

#1080 NO-ISSUE log the params UpdateClusterInternal
  internal/bminventory/inventory.go
Labels: approved, lgtm

#1087 MGMT-4092 Update AI to set bootStrapInPlace option in the install con…
  internal/common/common.go
  internal/installcfg/installcfg.go
  internal/installcfg/installcfg_test.go
Labels: approved, lgtm

#1075 MGMT-3999 http proxy support for minimal-iso
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/isoeditor/mock_editor.go
  internal/isoeditor/rhcos.go
  internal/isoeditor/rhcos_test.go
Labels: approved, lgtm

#1088 use 'safe_load' instead of 'load' to remove deprecation warning
  tools/deploy_assisted_installer_configmap.py
  tools/update_bm_cm.py
  tools/utils.py
Labels: approved, lgtm

#1089 OCPBUGSM-25004 Avoid printing empty image status measurements
  internal/host/host.go
  internal/host/host_test.go
Labels: approved, lgtm

#1084 MGMT-4114 Refactor KubeAPI subsystem and use clusterDeployment
  subsystem/kubeapi_test.go
  subsystem/subsystem_suite_test.go
Labels: approved, lgtm

#1086 OCPBUGSM-25012 Check download rate only for an image with a positive size
  internal/host/host.go
  internal/host/host_test.go
  internal/host/validator.go
  subsystem/host_test.go
Labels: approved, lgtm

#1082 OCPBUGSM-23207 - Fix GenerateClusterISO sometimes return null
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#1092 NO-ISSUE: checking hosts' status before checking status of the cluster
  subsystem/cluster_test.go
Labels: approved, lgtm

#1090 MGMT-3999 minimal-iso proxy - capital env vars
  internal/isoeditor/rhcos.go
  internal/isoeditor/rhcos_test.go
Labels: approved, lgtm

#771 MGMT-3137 OCM Cluster list - Integration
  Makefile
  cmd/main.go
  deploy/assisted-service-configmap.yaml
  go.mod
  go.sum
  internal/assistedserviceiso/assistedserviceiso_api.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/mock_cluster_api.go
  internal/common/db.go
  internal/identity/identity.go
  pkg/auth/auth_handler.go
  pkg/auth/authz_handler.go
  pkg/auth/authz_handler_test.go
  pkg/ocm/accounts_mgmt.go
  pkg/ocm/client.go
  pkg/ocm/mock_accounts_mgmt.go
  pkg/ocm/utils.go
  skipper.yaml
  subsystem/ams_subscriptions_test.go
  subsystem/authz_test.go
  subsystem/cluster_test.go
  subsystem/subsystem_suite_test.go
  subsystem/utils_test.go
  subsystem/wiremock_stubs.go
  tools/deploy_assisted_installer_configmap.py
Labels: approved, lgtm

#1104 NO-ISSUE Switch registry.svc.ci.openshift.org registry to public registry.ci.openshift.org
  Dockerfile.assisted-service
  Dockerfile.assisted-service-build
  Dockerfile.test
Labels: approved, kind/dependency-change, lgtm

#1107 OCPBUGSM-25012 Fixing bad bandwidth subsystem test
  internal/host/validator.go
  subsystem/host_test.go
Labels: approved, lgtm

#1095 OCPBUGSM-25012 Check download rate only for an image with a positive …
  internal/host/host.go
  internal/host/host_test.go
  internal/host/validator.go
  subsystem/host_test.go
Labels: approved, lgtm

#1106 MGMT-4155: Fixing integration with AMS when auth is disabled.
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#1108 NO-ISSUE Switch registry.svc.ci.openshift.org registry to public regi…
  Dockerfile.assisted-service
  Dockerfile.assisted-service-build
  Dockerfile.test
Labels: approved, kind/dependency-change, lgtm

#1099 MGMT-3370: fixed typo in AgentPlatformStateInfo value
  internal/controller/controllers/clusterdeployments_controller.go
Labels: approved, lgtm

#1103 NO-ISSUE: validate PULL_SECRET value before using it
  tools/handle_ocp_versions.py
Labels: approved, lgtm

#1109 MGMT-4167 Support both 3.1 and 3.2 ignition versions
  go.mod
  go.sum
  internal/bminventory/inventory.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
Labels: approved, lgtm

#1113 MGMT-3370: Added error logs to RegisterClusterInternal
  internal/bminventory/inventory.go
Labels: approved, lgtm

#1115 NO-ISSUE Remove onprem step from Jenkinsfile
  Jenkinsfile
Labels: approved, lgtm

#1114 OCPBUGSM-24964 Change sufficient masters validation to include insufficient, pending-for-input an known statuses
  internal/cluster/transition_test.go
  internal/cluster/validator.go
Labels: approved, lgtm

#1117 NO-ISSUE - add HostStageStartWaitingForControlPlane to dissconnection…
  internal/host/host.go
  internal/host/statemachine.go
  internal/host/transition_test.go
Labels: approved, lgtm

#1111 MGMT-4181 Generate service image URL for non S3 enabled deployments
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#1123 MGMT-4190 Fix bootstrap in place master ignition version to match the…
  internal/ignition/ignition.go
Labels: approved, lgtm

#1125 NO-ISSUE Log format fixes
  internal/bminventory/inventory.go
  pkg/auth/auth_handler.go
  pkg/s3wrapper/client.go
  pkg/s3wrapper/filesystem.go
Labels: approved, lgtm

#1074 MGMT-3371 Move all additional operator-related code to dedicated package
  cmd/main.go
  go.sum
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/refresh_status_preprocessor.go
  internal/cluster/transition_test.go
  internal/cluster/validator.go
  internal/ignition/dummy.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/operators/manager.go
  internal/operators/manager_test.go
  internal/operators/mock_operators_api.go
  internal/operators/ocs/mock_validations.go
  internal/operators/ocs/validations.go
  internal/operators/operators_suite_test.go
  pkg/job/job.go
  pkg/job/local_job.go
Labels: approved, lgtm

#1127 MGMT-4168 SNO cluster will be created automatically with OCP 4.8
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, lgtm

#1096 MGMT-4087 - add REST API for static network configuration
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/controller/api/v1alpha1/image_types.go
  internal/controller/api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/config/crd/bases/adi.io.my.domain_images.yaml
  internal/controller/controllers/image_controller.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/ignition/ignition.go
  models/image_create_params.go
  models/image_info.go
  models/static_ip_config.go
  models/static_ip_v4_config.go
  models/static_ip_v6_config.go
  models/vlan_config.go
  restapi/embedded_spec.go
  subsystem/image_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1130 NO-ISSUE add target to deploy-resources
  Makefile
Labels: approved, lgtm

#1105 OCPBUGSM-1928474 Fix for memory validation, when using additional disks
  go.mod
  go.sum
  internal/cluster/transition_test.go
  internal/operators/ocs/validations.go
Labels: approved, lgtm

#1065 MGMT-4017 Create agent CR on Register Host
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_crd_utils.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/cluster_controller_test.go
  internal/controller/controllers/crd_utils.go
  internal/controller/controllers/crd_utils_test.go
  internal/controller/controllers/image_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1029 MGMT-3918 InstallEnv controller
  cmd/main.go
  go.mod
  go.sum
  internal/controller/api/v1alpha1/cluster_types.go
  internal/controller/api/v1alpha1/image_types.go
  internal/controller/api/v1alpha1/installenv_types.go
  internal/controller/api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/config/crd/bases/adi.io.my.domain_installenvs.yaml
  internal/controller/config/crd/kustomization.yaml
  internal/controller/config/rbac/role.yaml
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/installenv_controller.go
  internal/controller/controllers/installenv_controller_test.go
Labels: approved, lgtm

#1110 MGMT-4161, Bump OCP version from 4.7.0-fc.4 to 4.7.0-rc.2 (auto created)
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#1133 MGMT-4211 - Single node clusters will now use default master role for hosts
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/transition_test.go
  internal/cluster/validator.go
Labels: approved, lgtm

#1134 NO-ISSUE Organize bminventory test mocks
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#1136 OCPBUGSM-22593 Validate SSH key when generating cluster ISO
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#1118 OCPBUGSM-1927459 Added ValidationPending Status when host inventory is empty
  internal/cluster/cluster_test.go
  internal/cluster/transition_test.go
  internal/cluster/validator.go
  internal/operators/manager.go
  internal/operators/manager_test.go
  internal/operators/mock_operators_api.go
  internal/operators/ocs/mock_validations.go
  internal/operators/ocs/validations.go
Labels: approved, lgtm

#1097 MGMT-4088 add nmstate package to the AssistedService image
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, lgtm

#1141 MGMT-3137 Fix bminventory unit test with AMS mock
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#1124 MGMT-4191 Clean up ignition package naming
  internal/bminventory/inventory.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
Labels: approved, lgtm

#1063 MGMT-3970 Make the iso editor scratch space base dir configurable
  go.mod
  go.sum
  internal/isoeditor/factory.go
  internal/isoeditor/rhcos.go
  internal/isoeditor/rhcos_test.go
  internal/isoutil/isoutil.go
  internal/isoutil/isoutil_test.go
  internal/isoutil/mock_isoutil.go
Labels: approved, lgtm

#1145 NO-ISSUE: Adding WITH_AMS_SUBSCRIPTIONS to deployment template.
  openshift/template.yaml
Labels: approved, lgtm

#1120 MGMT-4182 - Add 4.8 sno to OPENSHIFT_VERSIONS in test deployments
  Makefile
  default_public_container_registries.txt
  hack/generate.sh
  hack/get_ocp_versions_for_testing.sh
  subsystem/versions_test.go
  tools/handle_ocp_versions.py
Labels: approved, lgtm

#1128 OCPBUGSM-1927631 Modified the ocs validations to use all HDD or SSD driveType disks except installation disk
  cmd/main.go
  internal/cluster/cluster_test.go
  internal/cluster/transition_test.go
  internal/cluster/validator.go
  internal/ignition/ignition_test.go
  internal/operators/manager.go
  internal/operators/manager_test.go
  internal/operators/ocs/consts.go
  internal/operators/ocs/validations.go
Labels: approved, lgtm

#1144 NO-ISSUE: Fixing a typo in OCM Delete subscription logs.
  pkg/ocm/accounts_mgmt.go
Labels: approved, lgtm

#1119 NO-ISSUE Fix typos
  client/installer/complete_installation_parameters.go
  client/installer/get_cluster_parameters.go
  client/installer/get_host_parameters.go
  client/installer/get_next_steps_parameters.go
  internal/ignition/ignition.go
  models/api_vip_connectivity_response.go
  models/cluster.go
  models/dhcp_allocation_response.go
  models/disk.go
  restapi/embedded_spec.go
  restapi/operations/installer/complete_installation_parameters.go
  restapi/operations/installer/get_cluster_parameters.go
  restapi/operations/installer/get_host_parameters.go
  restapi/operations/installer/get_next_steps_parameters.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1153 MGMT-4242 Install Config edit fails for single node clusters
  internal/installcfg/installcfg.go
  internal/installcfg/installcfg_test.go
Labels: approved, lgtm

#1154 OCPBUGSM-25360 Create of SNO Cluster will set vip_dhcp_allocation to …
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#1156 NO-ISSUE Log each time uploading a new file using S3
  pkg/s3wrapper/client.go
Labels: approved, lgtm

#1155 NO-ISSUE Call build-minimal when using deploy-test
  Makefile
Labels: approved, lgtm

#1137 MGMT-3667 Print git_revision label for every image on deployment
  tools/deploy_assisted_installer_configmap.py
Labels: approved, lgtm

#1158 NO-ISSUE Organize DB preloads with common functions
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/common.go
  internal/cluster/installer_test.go
  internal/cluster/registrar.go
  internal/cluster/registrar_test.go
  internal/cluster/transition_test.go
  internal/cluster/validator.go
  internal/common/db.go
  internal/host/hostcommands/logs_cmd.go
  internal/host/validator.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1163 OCPBUGSM-25447 Disable image availability
  internal/host/hostcommands/instruction_manager.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/host/statemachine.go
  subsystem/host_test.go
Labels: approved, lgtm

#1143 MGMT-4089 - create nm connection file in discovery ISO using nmstatectl
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  pkg/staticnetworkconfig/generator.go
Labels: approved, lgtm

#1165 MGMT-4295 Verify that a host is valid to be master not only if it is in known state
  internal/host/host.go
  internal/host/host_test.go
Labels: approved, lgtm

#1073 KNIDEPLOY-4151 Operator deploys the assisted installer
  .gitignore
  Dockerfile.assisted-service-build
  Makefile
  PROJECT
  config/assisted-service/kustomization.yaml
  config/assisted-service/scality.yaml
  config/crd/bases/assistedservice.openshift.io.openshift.io_assistedservices.yaml
  config/crd/kustomization.yaml
  config/crd/kustomizeconfig.yaml
  config/crd/patches/cainjection_in_assistedservices.yaml
  config/crd/patches/webhook_in_assistedservices.yaml
  config/default/assisted-service-configmap-patch-hw-validator-min-disk-size.yaml
  config/default/assisted-service-patch-deploy-target.yaml
  config/default/assisted-service-patch-image.yaml
  config/default/assisted-service-patch-init-containers.yaml
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/default/manager_config_patch.yaml
  config/default/postgres-patch-init-container.yaml
  config/manager/controller_manager_config.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  config/manifests/kustomization.yaml
  config/prometheus/kustomization.yaml
  config/prometheus/monitor.yaml
  config/rbac/assistedservice_editor_role.yaml
  config/rbac/assistedservice_viewer_role.yaml
  config/rbac/auth_proxy_client_clusterrole.yaml
  config/rbac/auth_proxy_role.yaml
  config/rbac/auth_proxy_role_binding.yaml
  config/rbac/auth_proxy_service.yaml
  config/rbac/kustomization.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/scorecard/bases/config.yaml
  config/scorecard/kustomization.yaml
  config/scorecard/patches/basic.config.yaml
  config/scorecard/patches/olm.config.yaml
  deploy/postgres/postgres-deployment.yaml
  deploy/roles/ocp_role.yaml
  docs/operator.md
  hack/generate.sh
  internal/controller/config/rbac/kube_api_roles.yaml
  internal/controller/config/rbac/role.yaml
  tools/deploy_assisted_installer.py
  tools/deploy_assisted_installer_configmap.py
  tools/deploy_crd.py
  tools/deploy_inventory_service.py
  tools/deploy_postgres.py
  tools/deploy_role.py
  tools/deploy_scality_configmap.py
  tools/deploy_sso_secret.py
  tools/deploy_ui.py
  tools/deployment_options.py
  tools/wait_for_assisted_service.py
Labels: approved, kind/dependency-change, lgtm

#1112 MGMT-4297 Nuke Image and Cluster CRDs and Controllers
  cmd/main.go
  internal/controller/api/v1alpha1/cluster_types.go
  internal/controller/api/v1alpha1/image_types.go
  internal/controller/api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/config/crd/bases/adi.io.my.domain_clusters.yaml
  internal/controller/config/crd/bases/adi.io.my.domain_images.yaml
  internal/controller/config/crd/kustomization.yaml
  internal/controller/config/rbac/role.yaml
  internal/controller/controllers/cluster_controller.go
  internal/controller/controllers/cluster_controller_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/image_controller.go
  internal/controller/controllers/image_controller_test.go
  internal/controller/controllers/installenv_controller.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1139 OCPBUGSM-1928868 : Add validation for Auto-assign role
  internal/cluster/transition_test.go
  internal/operators/ocs/validations.go
Labels: approved, lgtm

#1157 MGMT-3856 - Fix weird domain resolution auto-generated swagger name
  models/domain_resolution_request.go
  models/domain_resolution_response.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1166 OCPBUGSM-1931840 Removed channel from Subscription manifest to allow OCS to install latest version
  internal/operators/manager.go
  internal/operators/ocs/utils.go
Labels: approved, lgtm

#1161 MGMT-4282 InstallEnv controller should attempt to update installEnv Status in all error cases
  internal/controller/controllers/installenv_controller.go
  internal/controller/controllers/installenv_controller_test.go
Labels: approved, lgtm

#1174 MGMT-4323 - fix the nmstate lib installation in Assisted-Service cont…
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, lgtm

#1140 MGMT-3371 Introducing generic OLM operator API and migrating OLM+LSO.
  cmd/main.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/refresh_status_preprocessor.go
  internal/cluster/statemachine.go
  internal/cluster/transition_test.go
  internal/cluster/validation_id.go
  internal/cluster/validator.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/monitor_test.go
  internal/host/refresh_status_preprocessor.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/ignition/ignition.go
  internal/migrations/20210218160100_validations_info_to_text.go
  internal/migrations/20210218160100_validations_info_to_text_test.go
  internal/migrations/20210223090000_host_validations_info_to_text.go
  internal/migrations/20210223090000_host_validations_info_to_text_test.go
  internal/migrations/migrations.go
  internal/operators/api/api.go
  internal/operators/builder.go
  internal/operators/lso/ls_operator.go
  internal/operators/manager.go
  internal/operators/manager_test.go
  internal/operators/mock_operators_api.go
  internal/operators/ocs/consts.go
  internal/operators/ocs/mock_validations.go
  internal/operators/ocs/ocs_operator.go
  internal/operators/ocs/validations.go
  models/cluster.go
  models/host.go
  models/host_validation_id.go
  pkg/job/job.go
  pkg/job/local_job.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1164 MGMT-3360 Agent controller spec reconcile
  cmd/main.go
  internal/controller/api/v1alpha1/agent_types.go
  internal/controller/api/v1alpha1/zz_generated.deepcopy.go
  internal/controller/config/crd/bases/adi.io.my.domain_agents.yaml
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/crd_utils_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1175 Igal/mgmt 4325
  internal/installcfg/installcfg.go
  internal/installcfg/installcfg_test.go
Labels: approved, lgtm

#1138 MGMT-4090 Use nmconnection settings relevant to current host
  internal/bminventory/inventory.go
  internal/constants/scripts.go
  internal/host/hostcommands/install_cmd.go
Labels: approved, lgtm

#1169 MGMT-3598: clusterdeployments_controller.go: Update host prefix only if > 0
  internal/controller/controllers/clusterdeployments_controller.go
Labels: approved, lgtm
