Repository openshift/assisted-service, pull requests merged in 2021-05, with the labels that each got.

#1563 MGMT-5248 - add configuration of mirror registry and its CA to AI dep…
  Makefile
  deploy/assisted-service-configmap-registry-ca.yaml
  deploy/assisted-service.yaml
  tools/deploy_assisted_installer_configmap_registry_ca.py
Labels: approved, lgtm

#1622 MGMT-5420 Always return 401 for local auth errors
  pkg/auth/local_authenticator.go
  pkg/auth/local_authenticator_test.go
Labels: approved, lgtm

#1589 MGMT-3512 Decrease verbosity of filesystem logs
  cmd/main.go
  pkg/s3wrapper/filesystem.go
Labels: approved, lgtm

#1629 Revert "MGMT-5441 assisted-service should use oc client with ICSP support"
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, lgtm

#1627 NO-ISSUE: Fixing OCM-Operations and Validations Grafana dashboard.
  dashboards/grafana-dashboard-assisted-installer-ocm-operations.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-validations.configmap.yaml
Labels: approved, lgtm

#1628 NO-ISSUE Adding monitoring logs for monitors
  internal/cluster/auth_test.go_disable
  internal/cluster/cluster.go
  internal/cluster/cluster_suite_test.go_disable
  internal/cluster/cluster_test.go
  internal/cluster/cluster_test.go_disable
  internal/cluster/common_test.go_disable
  internal/cluster/installer_test.go_disable
  internal/cluster/registrar_test.go_disable
  internal/cluster/transition_test.go_disable
  internal/host/host.go
  internal/host/host_test.go_disable
  internal/host/hosts_suite_test.go_disable
  internal/host/monitor_test.go_disable
  internal/host/refresh_status_preprocessor.go
  internal/host/transition_test.go_disable
  internal/operators/ocs/validation_test.go_disable
  pkg/commonutils/common_utils.go
Labels: approved, lgtm

#1626 NO-ISSUE remove redundant call to upload files
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#1630 OCPBUGSM-28168 update the ignition config run our service after the N…
  internal/ignition/ignition.go
Labels: approved, lgtm

#1637 NO-ISSUE Adding monitoring logs for monitors
  internal/cluster/cluster.go
  internal/host/host.go
  internal/host/monitor.go
Labels: approved, lgtm

#1412 MGMT-4356: Deploy only single openshift version
  hack/get_ocp_versions_for_testing.sh
  subsystem/cluster_test.go
  subsystem/day2_cluster_test.go
  subsystem/host_test.go
  subsystem/image_test.go
  subsystem/ipv6_test.go
  subsystem/manifests_test.go
  subsystem/metrics_test.go
  subsystem/operators_test.go
  subsystem/subsystem_suite_test.go
  subsystem/utils_test.go
  subsystem/versions_test.go
  tools/handle_ocp_versions.py
Labels: approved, lgtm

#1620 MGMT-5419 Move disks creation code to assisted-service repo
  deploy/operator/deploy.sh
  deploy/operator/libvirt_disks.sh
  deploy/operator/setup_lso.sh
  deploy/operator/utils.sh
Labels: approved, lgtm

#1638 NO-ISSUE Adding monitoring logs for monitors
  internal/cluster/cluster.go
  internal/host/monitor.go
  internal/operators/manager.go
Labels: approved, lgtm

#1639 MGMT-5390 Improve host monitoring performance (to release 1.0.19)
  internal/cluster/cluster_test.go
  internal/cluster/transition_test.go_disable
  internal/cluster/validator.go
  internal/host/host.go
  internal/host/host_test.go_disable
  internal/host/mock_host_api.go
  internal/host/monitor.go
  internal/host/monitor_test.go_disable
  internal/host/transition.go
  internal/host/validator.go
  internal/operators/ocs/validation_test.go_disable
Labels: approved, lgtm

#1641 NO-ISSUE remove skipping on clusters without hosts
  internal/cluster/cluster.go
Labels: approved, lgtm

#1640 MGMT-5390 Improve host monitoring performance (to master)
  internal/cluster/cluster_test.go
  internal/cluster/transition_test.go
  internal/cluster/validator.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/mock_host_api.go
  internal/host/monitor.go
  internal/host/monitor_test.go
  internal/host/transition.go
  internal/host/validator.go
  internal/operators/ocs/validation_test.go
Labels: approved, lgtm

#1593 OCPBUGSM-28382: Accept cm annotation on ASC
  docs/operator.md
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/controllers_suite_test.go
Labels: approved, lgtm

#1635 MGMT-6000, Bump OCP versions
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#1643 MGMT-5274 Adjust operator scripts for test-infra usage
  deploy/operator/deploy.sh
  deploy/operator/destroy.sh
  deploy/operator/libvirt_disks.sh
  deploy/operator/setup_assisted_operator.sh
  deploy/operator/setup_hive.sh
  deploy/operator/setup_lso.sh
  deploy/operator/utils.sh
Labels: approved, lgtm

#1646 MGMT-6011 Add monitoring for duration and number of clusters/hosts fr host/cluster monitors
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/host/monitor.go
  internal/host/monitor_test.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_metrics_manager_api.go
  pkg/commonutils/common_utils.go
Labels: approved, lgtm

#1586 MGMT-4849 Watch the InfraEnv resource for BMH reconcile
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1595 MGMT-4795 - operator should configure Assisted Service deployment to …
  docs/operator.md
  internal/common/common.go
  internal/controller/api/v1beta1/agentserviceconfig_types.go
  internal/controller/api/v1beta1/zz_generated.deepcopy.go
  internal/controller/config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
  internal/controller/config/crd/resources.yaml
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/common.go
  pkg/mirrorregistries/generator.go
Labels: approved, lgtm

#1653 NO-ISSUE Verify release version as part of handle_ocp_versions.py script
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  onprem-environment
  openshift/template.yaml
  tools/handle_ocp_versions.py
Labels: approved, lgtm

#1656 OCPBUGSM-27596 Update KubeAPI docs for nmstate
  docs/Kube-API.md
Labels: approved, lgtm

#1655 MGMT-5441 assisted-service should use oc client with ICSP support
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, lgtm

#1657 NO-ISSUE Set release_version when overriding ocp image
  tools/handle_ocp_versions.py
Labels: approved, lgtm

#1538 OCPBUGSM-27416 Handle AAAA DNS records in Route53
  internal/bminventory/inventory.go
  internal/cluster/transition.go
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
  internal/dns/dns.go
  internal/dns/dns_test.go
  internal/dns/mock_dns.go
  internal/dns/mock_dns_vendor.go
  internal/dns/mocks.go
Labels: approved, lgtm

#1611 NO-ISSUE support using a local registry
  Makefile
  README.md
  deploy/assisted-service.yaml
  docs/dev/debug.md
  hack/update_local_image.sh
  skipper.env
  tools/deploy_assisted_installer.py
  tools/deployment_options.py
Labels: approved, lgtm

#1623 NO-ISSUE Use correct validation ID for CNV host validation
  internal/operators/cnv/cnv_operator.go
Labels: approved, lgtm

#1654 MGMT-6027 - update documentation for deploying Assisted Service v ia …
  docs/operator.md
Labels: approved, lgtm

#1658 MGMT-5390 Additional improvements to host monitoring
  internal/host/conditions.go
  internal/host/refresh_status_preprocessor.go
  internal/host/statemachine.go
  internal/host/transition.go
Labels: approved, lgtm

#1527 MGMT-4736 Calculate SR-IOV NICs-related memory overhead
  internal/operators/cnv/cnv_operator.go
  internal/operators/cnv/cnv_operator_test.go
  internal/operators/cnv/config.go
  internal/operators/cnv/config_test.go
Labels: approved, lgtm

#1660 MGMT-5274 Order alphabetically operator env vars
  deploy/operator/setup_assisted_operator.sh
Labels: approved, lgtm

#1625 MGMT-5456 docs: hive integ - z-stream support
  docs/Kube-API.md
  docs/kube-api-select-ocp-versions.md
Labels: approved, lgtm

#1663 Update default OCP version 4.8.0-fc.0 -> 4.8.0-fc.2
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#1560 MGMT-4529 convert host and cluster metrics to ELK
  cmd/main.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/host/host.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_metrics_manager_api.go
Labels: approved, lgtm

#1601 NO-ISSUE: Change the memory unit from GB to GiB for OCS
  internal/operators/ocs/consts.go
  internal/operators/ocs/ocs_operator.go
  internal/operators/ocs/ocs_operator_test.go
  internal/operators/ocs/validation_test.go
  internal/operators/ocs/validations.go
Labels: approved, lgtm

#1652 MGMT-6023 kubeAPI subsystem test - wait for URLs
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1619 NO-ISSUE: Tests for agentserviceconfig_controller reconcile and
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
Labels: approved, lgtm

#1645 MGMT-4292 Re-enable image availability
  internal/bminventory/inventory.go
  internal/common/image_status.go
  internal/host/conditions.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostcommands/container_image_availability_cmd.go
  internal/host/hostcommands/instruction_manager.go
  internal/host/refresh_status_preprocessor.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/host/validator.go
  subsystem/cluster_test.go
  subsystem/host_test.go
  subsystem/kubeapi_test.go
  subsystem/utils_test.go
Labels: approved, lgtm

#1662 MGMT-6034 fix enabling mirror registry certificate in Assisted Service…
  internal/common/common.go
  internal/installcfg/installcfg.go
  internal/installcfg/installcfg_test.go
Labels: approved, lgtm

#1666 MGMT-5274 Make deploy operator scripts executable
  deploy/operator/deploy.sh
  deploy/operator/gather.sh
  deploy/operator/libvirt_disks.sh
  deploy/operator/setup_assisted_operator.sh
  deploy/operator/setup_hive.sh
  deploy/operator/setup_lso.sh
Labels: approved, lgtm

#1659 MGMT-5331 Subsystem test for filesystem usage metrics
  subsystem/metrics_test.go
Labels: approved, lgtm

#1665 MGMT-5449 Provide Minimum HW requirements for SNO
  client/installer/get_host_requirements_parameters.go
  internal/bminventory/inventory.go
  internal/hardware/mock_validator.go
  internal/hardware/validator.go
  internal/hardware/validator_test.go
  internal/host/validator.go
  restapi/embedded_spec.go
  restapi/operations/installer/get_host_requirements_parameters.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1555 MGMT-5348 cluster specific disk eligibility check
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/hardware/mock_validator.go
  internal/hardware/validator.go
  internal/hardware/validator_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/mock_host_api.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validator.go
  subsystem/cluster_test.go
Labels: approved, lgtm

#1647 MGMT-6010 kubeAPI subsystem tests should cleanup the pull-secret
  subsystem/cluster_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1673 OCPBUGSM-26820 Add database connection retry
  cmd/main.go
Labels: approved, lgtm

#1669 MGMT-4942 Download rootfs from mirror.openshift.com
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/isoeditor/factory.go
  internal/isoeditor/mock_factory.go
  internal/isoeditor/rhcos.go
  internal/isoeditor/rhcos_test.go
  internal/versions/mock_versions.go
  internal/versions/versions.go
  models/openshift_version.go
  onprem-environment
  openshift/template.yaml
  pkg/s3wrapper/client.go
  pkg/s3wrapper/client_test.go
  pkg/s3wrapper/filesystem.go
  pkg/s3wrapper/filesystem_test.go
  pkg/s3wrapper/util.go
  pkg/s3wrapper/util_test.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1686 Revert "MGMT-4942 Download rootfs from mirror.openshift.com"
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/isoeditor/factory.go
  internal/isoeditor/mock_factory.go
  internal/isoeditor/rhcos.go
  internal/isoeditor/rhcos_test.go
  internal/versions/mock_versions.go
  internal/versions/versions.go
  models/openshift_version.go
  onprem-environment
  openshift/template.yaml
  pkg/s3wrapper/client.go
  pkg/s3wrapper/client_test.go
  pkg/s3wrapper/filesystem.go
  pkg/s3wrapper/filesystem_test.go
  pkg/s3wrapper/util.go
  pkg/s3wrapper/util_test.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1687 NO-ISSUE allow GitHub-created reverts to be used
  tools/check-commit-message.sh
Labels: approved, lgtm

#1674 OCPBUGSM-28762 cd controller: trim ssh key before update
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1682 MGMT-6090 - fix erroneous mirror CA is set in the master ignition
  internal/installcfg/installcfg.go
  internal/installcfg/installcfg_test.go
Labels: approved, lgtm

#1683 MGMT-6067 Add a cache for the local authenticator
  pkg/auth/local_authenticator.go
  pkg/auth/local_authenticator_test.go
Labels: approved, lgtm

#1685 MGMT-4966 Map the /run/media/iso directory to the next_step agent com…
  internal/host/hostcommands/next_step_runner_cmd.go
Labels: approved, lgtm

#1543 MGMT-4477 adjust OCS preflight requirements
  internal/operators/ocs/ocs_operator.go
  subsystem/cluster_test.go
Labels: approved, lgtm

#1690 NO-ISSUE Fix incomplete Hive installation manifest
  docs/operator.md
Labels: approved, lgtm

#1692 NO-ISSUE Fix apiVersion for AgentServiceConfig
  docs/operator.md
Labels: approved, lgtm

#1691 NO_ISSUE Revert "MGMT-4966 Map the /run/media/iso directory to the next_step a…
  internal/host/hostcommands/next_step_runner_cmd.go
Labels: approved, lgtm

#1684 MGMT-6281 mirror LSO packages to local registry
  deploy/operator/libvirt_disks.sh
  deploy/operator/mirror_utils.sh
  deploy/operator/setup_lso.sh
  deploy/operator/utils.sh
Labels: approved, lgtm

#1608 NO-ISSUE Update and expand BMAC's documentation
  docs/baremetal-agent-controller.md
Labels: approved, lgtm

#1617 MGMT-4943 Watch the ClusterDeployment resource for BMH reconcile
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, lgtm

#1694 MGMT-4134 Fixes to usage dashboard
  internal/bminventory/inventory.go
  subsystem/cluster_test.go
  subsystem/operators_test.go
  subsystem/subsystem_suite_test.go
  subsystem/utils_test.go
Labels: approved, lgtm

#1458 MGMT-4640 set default OCP requirements
  Makefile
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_hw_requirements.json
  deploy/assisted-service-configmap.yaml
  hack/generate.sh
  onprem-environment
  tools/deploy_assisted_installer_configmap.py
  tools/update_bm_cm.py
Labels: approved, lgtm

#1700 MGMT-5270 handle_ocp_versions: ignore default key
  tools/handle_ocp_versions.py
Labels: approved, lgtm

#1667 OCPBUGSM-28705: replace MiB unit to GiB when ocs host requirement fails
  internal/operators/ocs/ocs_operator.go
  internal/operators/ocs/ocs_operator_test.go
Labels: approved, lgtm

#1708 MGMT-5274 Destroy test assisted-service test catalogsource
  deploy/operator/destroy.sh
Labels: approved, lgtm

#1549 MGMT-5302 Removing deprecated /host_requirements endpoint and related model
  client/installer/get_host_requirements_parameters.go
  client/installer/get_host_requirements_responses.go
  client/installer/installer_client.go
  internal/bminventory/inventory.go
  mocks/mock_assisted_service.go
  models/host_requirements.go
  models/host_requirements_role.go
  pkg/auth/auth_assisted_service_mock_test.go
  pkg/auth/authz_handler_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/get_host_requirements.go
  restapi/operations/installer/get_host_requirements_parameters.go
  restapi/operations/installer/get_host_requirements_responses.go
  restapi/operations/installer/get_host_requirements_urlbuilder.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1636 MGMT-5398 Update kubeapi docs for AgentClusterInstall
  docs/Kube-API.md
  docs/crds/agentClusterInstall-SNO.yaml
  docs/crds/agentClusterInstall.yaml
  docs/crds/clusterDeployment-SNO.yaml
  docs/crds/clusterDeployment.yaml
  docs/kube-api-conditions.md
Labels: approved, lgtm

#1712 NO-ISSUE add /etc/pki/tls/certs/ca-bundle.crt volume mount to skipper…
  skipper.yaml
Labels: approved, lgtm

#1642 MGMT-4261 Deregister Host on agent CR deletion
  config/rbac/role.yaml
  internal/bminventory/inventory.go
  internal/bminventory/mock_installer_internal.go
  internal/common/db.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1714 MGMT-6451 Skip flaky subsystem kubeapi test deploy clusterDeployment with agent
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1702 OCPBUGSM-28332 - Fix enable/disable host operations returns cluster resource with only enabled hosts list
  internal/bminventory/inventory.go
Labels: approved, lgtm

#1705 MGMT-5415: Adding filter to GET /clusters API.
  client/installer/list_clusters_parameters.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/db.go
  restapi/embedded_spec.go
  restapi/operations/installer/list_clusters_parameters.go
  restapi/operations/installer/list_clusters_urlbuilder.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1706 MGMT-6001 Misleading status after prepare-for-install error
  internal/cluster/cluster.go
  internal/host/common.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/host/validator.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1710 NO-ISSUE Add retry for any curl command
  Dockerfile.assisted-service
  Dockerfile.bundle
  Jenkinsfile
  deploy/operator/mirror_utils.sh
  hack/setup_env.sh
  hack/update_local_image.sh
Labels: approved, kind/dependency-change, lgtm

#1716 MGMT-5396 Remove unneeded yaml - rebase leftovers
  internal/controller/config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  internal/controller/config/crd/kustomization.yaml
Labels: approved, lgtm

#1697 MGMT-4942 Download rootfs from mirror.openshift.com (take 2)
  config/manager/manager.yaml
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  default_ocp_versions.json
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/isoeditor/factory.go
  internal/isoeditor/mock_factory.go
  internal/isoeditor/rhcos.go
  internal/isoeditor/rhcos_test.go
  internal/versions/mock_versions.go
  internal/versions/versions.go
  models/openshift_version.go
  onprem-environment
  openshift/template.yaml
  pkg/s3wrapper/client.go
  pkg/s3wrapper/client_test.go
  pkg/s3wrapper/filesystem.go
  pkg/s3wrapper/filesystem_test.go
  pkg/s3wrapper/util.go
  pkg/s3wrapper/util_test.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1724 MGMT-6458 - Don't override hw master requirements with sno one
  internal/hardware/validator.go
Labels: approved, lgtm

#1715 MGMT-6438 Removed deprecated requirements env variables.
  hack/generate.sh
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/hardware/mock_validator.go
  internal/hardware/validator.go
  internal/hardware/validator_test.go
  internal/hardware/versioned-requirements.go
  internal/hardware/versioned-requirements_test.go
  internal/host/transition_test.go
Labels: approved, lgtm

#1728 NO-ISSUE Add documentation for overriding hardware requirements
  docs/dev/hardware-requirements.md
Labels: approved, lgtm

#1592 MGMT-5412: Add OSImages to AgentServiceConfig API
  config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
  config/crd/resources.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agentserviceconfigs.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  docs/operator.md
  internal/controller/api/v1beta1/agentserviceconfig_types.go
  internal/controller/api/v1beta1/zz_generated.deepcopy.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
Labels: api-review, approved, lgtm

#1644 Mgmt 5399 Add support for conditions Failed Stopped
  docs/kube-api-conditions.md
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/conditions.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1648 MGMT-5847 Move InstallConfig annotation to AgentClusterInstall CRD
  docs/Kube-API.md
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1730 MGMT-6451 fixing flaky subsystem tests with bmh deployments
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1699 Bug 1957227: Allow overriding defaults via provided ConfigMap
  config/rbac/role.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/metadata/annotations.yaml
  docs/operator.md
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm

#1732 MGMT-5302 Restoring /host_requirements for e2e tests
  client/installer/get_host_requirements_parameters.go
  client/installer/get_host_requirements_responses.go
  client/installer/installer_client.go
  internal/bminventory/inventory.go
  internal/hardware/mock_validator.go
  internal/hardware/validator.go
  mocks/mock_assisted_service.go
  models/host_requirements.go
  models/host_requirements_role.go
  pkg/auth/auth_assisted_service_mock_test.go
  pkg/auth/authz_handler_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/get_host_requirements.go
  restapi/operations/installer/get_host_requirements_parameters.go
  restapi/operations/installer/get_host_requirements_responses.go
  restapi/operations/installer/get_host_requirements_urlbuilder.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1734 OCPBUGSM-28708, OCPBUGSM-28573 Disable OCS installation on OCP 4.8
  internal/operators/ocs/validation_test.go
  internal/operators/ocs/validations.go
Labels: approved, lgtm

#1736 NO-ISSUE Fix HW_VALIDATOR_REQUIREMENTS value for the operator deployment
  internal/controller/controllers/agentserviceconfig_controller.go
Labels: approved, lgtm

#1707 NO-ISSUE Add Elastic APM agent
  cmd/main.go
  go.mod
  go.sum
Labels: approved, lgtm

#1719 MGMT-6456 fetch OpenshiftVersion from cache by ReleaseImage
  internal/versions/versions.go
  internal/versions/versions_test.go
Labels: approved, lgtm

#1735 NO-ISSUE: Bump operator to 0.0.4
  Makefile
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/metadata/annotations.yaml
  hack/generate.sh
Labels: approved, lgtm

#1713 MGMT-6465 Move default_ocp_versions.json and default_public_container_registries.txt to data directory
  Makefile
  data/default_ocp_versions.json
  data/default_public_container_registries.txt
  default_ocp_versions.json
  hack/generate.sh
  hack/get_ocp_versions_for_testing.sh
  internal/versions/versions_test.go
  tools/handle_ocp_versions.py
Labels: approved, lgtm

#1711 NO-ISSUE Add examples to the contributor guide
  CONTRIBUTING.md
Labels: approved, lgtm

#1729 MGMT-6413 Add current deployment state dashboard
  dashboards/grafana-dashboard-assisted-installer-deployment-overview.configmap.yaml
Labels: approved, lgtm

#1751 MGMT-5302 Restoring /host_requirements for e2e tests (#1732)
  client/installer/get_host_requirements_parameters.go
  client/installer/get_host_requirements_responses.go
  client/installer/installer_client.go
  internal/bminventory/inventory.go
  mocks/mock_assisted_service.go
  models/host_requirements.go
  models/host_requirements_role.go
  pkg/auth/auth_assisted_service_mock_test.go
  pkg/auth/authz_handler_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/get_host_requirements.go
  restapi/operations/installer/get_host_requirements_parameters.go
  restapi/operations/installer/get_host_requirements_responses.go
  restapi/operations/installer/get_host_requirements_urlbuilder.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1750 NO- ISSUE Revert "MGMT-6451 Skip flaky subsystem kubeapi test deploy clusterDeployment with agent
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1432 MGMT-4878 Add host validation for network latency
  internal/cluster/cluster_test.go
  internal/common/test_configuration.go
  internal/hardware/validator.go
  internal/hardware/validator_test.go
  internal/hardware/versioned-requirements.go
  internal/host/common.go
  internal/host/host.go
  internal/host/hostutil/host_utils.go
  internal/host/hostutil/test_utils.go
  internal/host/refresh_status_preprocessor.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/host/validator.go
  models/cluster_host_requirements_details.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  subsystem/day2_cluster_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1585 MGMT-5430 - use the nmstate RPM
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, lgtm

#1701 MGMT-4327 Remove old FIO tool from service after the new tool is in use
  models/fio_perf_check_request.go
  models/fio_perf_check_response.go
  models/step_type.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1748 OCPBUGSM-29306 Allow creating SNO cluster with version 4.8.0-fc.X
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#1675 OCPBUGSM-26546 Validate length of base DNS domain
  internal/bminventory/inventory.go
  internal/dns/dns.go
  internal/dns/dns_test.go
  internal/dns/mock_dns.go
Labels: approved, lgtm

#1718 MGMT-6282: Split openshift_cluster_id and status 'Active' update in AMS.
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/transition_test.go
  pkg/ocm/accounts_mgmt.go
  pkg/ocm/mock_accounts_mgmt.go
  subsystem/ams_subscriptions_test.go
  subsystem/cluster_test.go
  subsystem/wiremock_stubs.go
Labels: approved, lgtm

#1737 NO-ISSUE Remove kube job references and combine job types
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  pkg/generator/generator.go
  pkg/generator/mock_install_config.go
  pkg/job/job.go
  pkg/job/local_job.go
Labels: approved, lgtm

#1746 MGMT-6438 Remove references to unused env variables for hardware requiremets
  openshift/template.yaml
Labels: approved, lgtm

#1757 MGMT-6413 Move dashboard under assisted-installer folder in Grafana
  dashboards/grafana-dashboard-assisted-installer-deployment-overview.configmap.yaml
Labels: approved, lgtm

#1704 MGMT-6420 add owner reference to AgentClusterInstall
  go.sum
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1731 MGMT-4658 Remove contents of Hosts field from payload
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  subsystem/cluster_test.go
Labels: approved, lgtm

#1753 MGMT-6469 Delete Day1 only after the state is updated in CRD
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, lgtm

#1744 OCPBUGSM-28663 Create an iso download endpoint with .iso at the end - bz-1956421
  client/installer/download_cluster_i_s_o_clone_parameters.go
  client/installer/download_cluster_i_s_o_clone_responses.go
  client/installer/download_cluster_i_s_o_headers_clone_parameters.go
  client/installer/download_cluster_i_s_o_headers_clone_responses.go
  client/installer/installer_client.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/download_cluster_i_s_o_clone.go
  restapi/operations/installer/download_cluster_i_s_o_clone_parameters.go
  restapi/operations/installer/download_cluster_i_s_o_clone_responses.go
  restapi/operations/installer/download_cluster_i_s_o_clone_urlbuilder.go
  restapi/operations/installer/download_cluster_i_s_o_headers_clone.go
  restapi/operations/installer/download_cluster_i_s_o_headers_clone_parameters.go
  restapi/operations/installer/download_cluster_i_s_o_headers_clone_responses.go
  restapi/operations/installer/download_cluster_i_s_o_headers_clone_urlbuilder.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1755 OCPBUGSM-29303: fix crash on undefined pull-secret
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/common.go
  internal/controller/controllers/error_utils.go
Labels: approved, lgtm

#1227 NO-ISSUE: Add docs/enhancements directory
  docs/enhancements/README.md
  docs/enhancements/template.md
Labels: approved, lgtm

#1749 MGMT-6063 Minor improvements to DHCP kernel arg
  internal/host/hostcommands/install_cmd.go
Labels: approved, lgtm

#1421 NO-ISSUE configure hco subscription
  internal/operators/cnv/cnv_operator.go
  internal/operators/cnv/config.go
  internal/operators/cnv/manifest.go
  internal/operators/cnv/manifests_test.go
Labels: approved, lgtm

#1742 OCPBUGSM-23667 - add validation for mac/nic uniqueness for static net…
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/ignition/ignition_test.go
  pkg/staticnetworkconfig/generator.go
  pkg/staticnetworkconfig/generator_test.go
  pkg/staticnetworkconfig/mock_generator.go
  subsystem/image_test.go
Labels: approved, lgtm

#1759 MGMT-6473 - adding mirror registry documentation
  docs/Kube-API.md
Labels: approved, lgtm

#1760 NO-ISSUE kube-api: full format for release version
  internal/versions/versions.go
  internal/versions/versions_test.go
Labels: approved, lgtm

#1764 MGMT-6282: Split openshift_cluster_id and status 'Active' update in A…
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/transition_test.go
  pkg/ocm/accounts_mgmt.go
  pkg/ocm/mock_accounts_mgmt.go
  subsystem/ams_subscriptions_test.go
  subsystem/cluster_test.go
  subsystem/wiremock_stubs.go
Labels: approved, lgtm

#1763 MGMT-5430 Move assisted service image to stream8
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, lgtm

#1774 Revert "MGMT-5430 Move assisted service image to stream8"
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, lgtm

#1766 NO-ISSUE: don't overwrite bundle metadata
  hack/generate.sh
Labels: approved, kind/failing-test, lgtm, priority/critical-urgent

#1698 MGMT-6284 install hive without OLM
  Dockerfile.assisted-service-build
  Makefile
  deploy/operator/deploy.sh
  deploy/operator/setup_hive.sh
  hack/setup_env.sh
Labels: approved, kind/dependency-change, lgtm

#1762 OCPBUGSM-29119 Can't change Installation disk
  internal/bminventory/inventory.go
  internal/hardware/validator.go
  internal/hardware/validator_test.go
Labels: approved, lgtm

#1761 NO-ISSUE fix case of AgentCluster
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1777 MGMT-5274 Check nodes disks before attach/detach script
  deploy/operator/libvirt_disks.sh
Labels: approved, lgtm

#1770 Ocpbugsm 29306
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, lgtm

#1720 MGMT-6411 Discovery image deleted on cluster removal
  subsystem/cluster_test.go
Labels: approved, lgtm

#1768 NO-ISSUE Add note about Skipper to the operator build docs
  docs/operator.md
Labels: approved, lgtm

#1780 MGMT-4966 Mapping /run/media directory to the next_step agent
  internal/host/hostcommands/next_step_runner_cmd.go
Labels: approved, lgtm

#1772 NO-ISSUE Extend BMAC documentation
  docs/baremetal-agent-controller.md
Labels: approved, lgtm

#1784 NO-ISSUE: Fixing doc typos
  README.md
  docs/installer-stand-alone.md
Labels: approved, lgtm

#1609 MGMT-4668: Generate OLM opeartor manifest to custom file
  cmd/main.go
  internal/cluster/cluster.go
  internal/cluster/transition_test.go
  internal/host/transition_test.go
  internal/ignition/ignition_test.go
  internal/operators/api/api.go
  internal/operators/api/mock_operator_api.go
  internal/operators/builder.go
  internal/operators/builder_test.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/cnv/manifest.go
  internal/operators/cnv/manifests_test.go
  internal/operators/lso/ls_operator.go
  internal/operators/lso/manifest.go
  internal/operators/lso/manifests_test.go
  internal/operators/manager.go
  internal/operators/manager_test.go
  internal/operators/ocs/manifest.go
  internal/operators/ocs/manifests_test.go
  internal/operators/ocs/ocs_operator.go
  internal/operators/ocs/validation_test.go
  restapi/embedded_spec.go
  restapi/operations/installer/download_cluster_files_parameters.go
  subsystem/operators_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1791 MGMT-6576 - Bump 4.8 OCP to fc.5
  config/manager/manager.yaml
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_ocp_versions.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#1799 NO-ISSUE perf test - setting db max connectio
  cmd/main.go
  pkg/commonutils/common_utils.go
Labels: approved, lgtm

#1776 MGMT-5255 Add events URL to CRD
  cmd/main.go
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  docs/Kube-API.md
  internal/controller/api/hiveextension/v1beta1/agentclusterinstall_types.go
  internal/controller/api/hiveextension/v1beta1/zz_generated.deepcopy.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  restapi/embedded_spec.go
  subsystem/kubeapi_test.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1783 MGMT-6022 - Hyperthreading support in AgentClusterInstall
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1771 MGMT-6413 fix installer-deployment-overview configmap, (indentation issue)
  dashboards/grafana-dashboard-assisted-installer-deployment-overview.configmap.yaml
Labels: approved, lgtm

#1781 MGMT-5274 Setup assisted operator ConfigMap
  deploy/operator/setup_assisted_operator.sh
Labels: approved, lgtm

#1790 NO-ISSUE: upgrade operator-sdk binary
  .gitignore
  Dockerfile.bundle
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/metadata/annotations.yaml
  hack/generate.sh
  hack/setup_env.sh
Labels: approved, kind/dependency-change, lgtm

#1795 MGMT-6410: Adding documentation for OCM integration.
  docs/ocm-integration.md
Labels: approved, lgtm

#1800 MGMT-6025 Enable day2 subsystem for kubeapi
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1796 MGMT-6577 Production logs are spammed on "Failed to determine install…
  internal/hardware/boot_device.go
  internal/host/host.go
  internal/host/hostcommands/disk_performance_cmd.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/instruction_manager.go
  internal/host/validator.go
Labels: approved, lgtm

#1797 MGMT-6584 Add host progress stages while waiting for control plane
  internal/host/host.go
  internal/host/transition_test.go
  models/host_stage.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: api-review, approved, lgtm

#1805 Revert "MGMT-6576 - Bump 4.8 OCP to fc.5"
  config/manager/manager.yaml
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_ocp_versions.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  onprem-environment
  openshift/template.yaml
Labels: approved, lgtm

#1804 MGMT-5255 KubeAPI Update event URL only once
  internal/controller/controllers/clusterdeployments_controller.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1606 MGMT-4261 Agent CR and ACI cleanup when deleting CD
  config/rbac/role.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1786 MGMT-6562 Agent CRD Validated fails on pending-for-input
  docs/kube-api-conditions.md
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, lgtm

#1809 MGMT-6531 agent conditions: check if approved
  docs/kube-api-conditions.md
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/conditions.go
Labels: approved, lgtm

#1670 MGMT-4758 use InfraEnv namespace to create the Agent
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/common.go
  internal/controller/controllers/crd_utils.go
  internal/controller/controllers/crd_utils_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm

#1773 MGMT-6437: Redirecting cluster metrics to the correct Telemeter server.
  cmd/main.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
  internal/network/mock_manifests_generator.go
Labels: approved, lgtm

#1802 OCPBUGSM-28872 Requirement Conditions for stopped state
  docs/kube-api-conditions.md
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/conditions.go
Labels: approved, lgtm

#1812 MGMT-5255 Disable check for clearing events URL
  subsystem/kubeapi_test.go
Labels: approved, lgtm
