Repository openshift/assisted-service, pull requests merged in 2021-12, with the labels that each got.

#3005 OCPBUGSM-36598: reset progress on re-discovery
  internal/host/transition.go
Labels: approved, size/XS, lgtm

#2998 MGMT-8302 Ignition endpoint token should not be returned
  internal/bminventory/inventory.go
  internal/common/db.go
  internal/controller/controllers/agent_controller.go
  internal/host/host.go
  internal/host/host_test.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/ignition/mock_ignition.go
  models/host.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/M, api-review, lgtm

#3003 MGMT-7943: changing message for image availability validation failure
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, size/S, lgtm

#3007 MGMT-8203: DHCP server failed to allocated VIPs when VIPs are manually cleared
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/S, lgtm

#2911 OCPRHV-635: add tests for ovirt provider
  internal/bminventory/inventory_test.go
  subsystem/cluster_test.go
Labels: approved, size/L, lgtm, ok-to-test

#3002 MGMT-8180: day2 - fallback to default ocp version
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/versions/mock_versions.go
  internal/versions/versions.go
  internal/versions/versions_test.go
Labels: approved, size/L, lgtm

#3012 Allow setting HTTP routes with DISABLE_TLS parameter
  Makefile
  README.md
  skipper.env
Labels: approved, size/S, lgtm

#3011 MGMT-8355: Fix flaky subsystem test - host next step
  subsystem/host_test.go
Labels: approved, size/XS, lgtm

#3000 Update assisted-ui repo location
  tools/deploy_ui.py
Labels: approved, size/XS, lgtm

#3014 MGMT-8299: Subsystem refactor: Implement a global AfterEach func
  subsystem/ams_subscriptions_test.go
  subsystem/authz_test.go
  subsystem/cluster_test.go
  subsystem/cluster_v2_test.go
  subsystem/day2_cluster_test.go
  subsystem/events_test.go
  subsystem/host_test.go
  subsystem/host_v2_test.go
  subsystem/image_test.go
  subsystem/infra_env_test.go
  subsystem/ipv6_test.go
  subsystem/kubeapi_test.go
  subsystem/manifests_test.go
  subsystem/metrics_test.go
  subsystem/operators_test.go
  subsystem/subsystem_suite_test.go
  subsystem/utils_test.go
Labels: approved, size/L, lgtm

#3013 MGMT-7901: Kube-API import cluster doc
  docs/hive-integration/README.md
  docs/hive-integration/import-installed-cluster.md
Labels: approved, size/M, lgtm

#3009 MGMT-7925: Remove a redundant cluster registration event
  docs/events.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/common/events/events.go
  internal/events/eventstest/events_test_utils.go
  subsystem/image_test.go
Labels: approved, size/L, lgtm

#3006 MGMT-8370 - Replace the client on the service with the new generated one
  Dockerfile.assisted-service
  hack/generate.sh
  tools/client_package_initializer.py
Labels: approved, kind/dependency-change, size/M, lgtm

#3019 NO-ISSUE: Fix upload to pypi as it failed while uploading the tar.gz artifact
  Makefile
Labels: approved, size/XS, lgtm

#2994 MGMT-8178: InfraEnv garbage collector
  cmd/main.go
  internal/garbagecollector/garbageCollector.go
  internal/infraenv/infraenv.go
  internal/infraenv/infraenv_test.go
  internal/infraenv/mock_infraenv_api.go
  subsystem/cluster_v2_test.go
  tools/deploy_assisted_installer.py
Labels: approved, size/L, lgtm

#3024 MGMT-8451: Setting VIPs support level to dev-preview on all versions
  internal/featuresupport/support_levels_list.go
Labels: approved, size/S, lgtm

#3026 NO-ISSUE: Allow setting MINIKUBE_HOME
  skipper.env
  skipper.yaml
Labels: approved, size/XS, lgtm

#3028 MGMT-8461: Avoid panic in case nil is passed to GenerateError
  internal/bminventory/inventory.go
  internal/common/error_utils.go
Labels: approved, size/S, lgtm

#2884 MGMT-7254: Deploy and use image service for subsystem
  Makefile
  cmd/main.go
  deploy/assisted-image-service.yaml
  deploy/assisted-installer-ingress-tls.yaml
  deploy/assisted-installer-ingress.yaml
  deploy/assisted-service-configmap.yaml
  docs/events.yaml
  internal/assistedserviceiso/assistedserviceiso_api.go
  internal/assistedserviceiso/assistedserviceiso_api_test.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/events/events.go
  pkg/staticnetworkconfig/generator.go
  subsystem/cluster_test.go
  subsystem/image_test.go
  subsystem/infra_env_test.go
  subsystem/kubeapi_test.go
  tools/deploy_assisted_installer_configmap.py
  tools/deploy_image_service.py
  tools/utils.py
  tools/wait_for_assisted_service.py
Labels: approved, size/XL, api-review, lgtm

#3008 MGMT-7330: Copy files for CI to run the unit tests
  Dockerfile.assisted-service-build
Labels: approved, kind/dependency-change, size/XS, lgtm

#3032 NO-ISSUE Add api-review label to k8s API changes
  OWNERS
Labels: approved, size/XS, lgtm

#2989 MGMT-8308: Fix vsphere provider db fields.
  internal/provider/vsphere/consts.go
Labels: approved, size/XS, lgtm

#3023 MGMT-8448: Use the image service when deploying with podman
  Makefile
  client/installer/download_cluster_i_s_o_responses.go
  docs/installer-stand-alone.md
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  onprem-environment
  restapi/embedded_spec.go
  restapi/operations/installer/download_cluster_i_s_o_responses.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#3016 MGMT-8415: Remove the infra-env image download endpoint
  client/installer/download_infra_env_discovery_image_headers_parameters.go
  client/installer/download_infra_env_discovery_image_headers_responses.go
  client/installer/download_infra_env_discovery_image_parameters.go
  client/installer/download_infra_env_discovery_image_responses.go
  client/installer/installer_client.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/download_infra_env_discovery_image.go
  restapi/operations/installer/download_infra_env_discovery_image_headers.go
  restapi/operations/installer/download_infra_env_discovery_image_headers_parameters.go
  restapi/operations/installer/download_infra_env_discovery_image_headers_responses.go
  restapi/operations/installer/download_infra_env_discovery_image_headers_urlbuilder.go
  restapi/operations/installer/download_infra_env_discovery_image_parameters.go
  restapi/operations/installer/download_infra_env_discovery_image_responses.go
  restapi/operations/installer/download_infra_env_discovery_image_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#3017 MGMT-8313: Update event on Add Host to Installed Cluster
  cmd/main.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/progress_test.go
  internal/cluster/transition_test.go
  internal/operators/ocs/validation_test.go
Labels: approved, size/L, lgtm

#3027 Mgmt-8424: Day 2 ignition endpoint check customization
  internal/host/hostcommands/api_vip_connectivity_check_cmd.go
  internal/host/hostcommands/api_vip_connectivity_check_cmd_test.go
  models/api_vip_connectivity_request.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#3036 MGMT-8482: Add channel for ocs operator
  internal/operators/ocs/manifest.go
Labels: approved, size/XS, lgtm

#3031 MGMT-8413: Add new condition on AgentServiceConfig Agent object
  api/v1beta1/agentserviceconfig_types.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
Labels: approved, size/L, api-review, lgtm

#3041 NO-ISSUE: Use .Equal to compare time objects
  internal/cluster/common_test.go
Labels: approved, size/XS, lgtm

#3044 MGMT-8472: Fix flacky test infraenv GC
  internal/infraenv/infraenv_test.go
Labels: approved, size/XS, lgtm

#3018 MGMT-8315: use values cached in cluster for AddReleaseImage
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/versions/mock_versions.go
  internal/versions/versions.go
  internal/versions/versions_test.go
Labels: approved, size/L, lgtm

#3045 MGMT-8505: Fix logger for NotifyKubeApiInfraEnvEvent
  internal/controller/controllers/controller_event_wrapper.go
Labels: approved, size/XS, lgtm

#3042 MGMT-8300: Improve behaviour of dual-stack via REST API
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/common.go
Labels: approved, size/L, lgtm

#3049 MGMT-8504: Fix InfraEnv image updated event loop
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/S, lgtm

#3038 MGMT-7330: Make `ROOT_DIR`, `COVER_PROFILE` and `GINKGO_REPORTFILE` overridable for running unit tests in CI
  Dockerfile.assisted-service-build
  Makefile
Labels: approved, kind/dependency-change, size/S, lgtm

#3053 NO-ISSUE: Allow short or fqdn for image in manifest
  tools/deployment_options.py
Labels: approved, size/XS, lgtm

#3058 MGMT-8178: Add InfraEnv GC to OpenShift template
  openshift/template.yaml
Labels: approved, size/S, lgtm

#3056 MGMT-8564: Rename the UI deployment template
  Makefile
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  deploy/ui/ui_ingress.yaml
  docs/installer-stand-alone.md
  site/installer-stand-alone/index.html
  site/search/search_index.json
  tools/deploy_assisted_installer_configmap.py
  tools/deploy_ui.py
  tools/deployment_options.py
Labels: approved, size/M, lgtm

#3057 MGMT-7507: Add feature usage for dual-stack
  internal/bminventory/inventory.go
  internal/network/dual_stack_validations.go
  internal/usage/consts.go
  subsystem/cluster_test.go
Labels: approved, size/L, lgtm

#3066 MGMT-8564: Rename the UI deployment template
  Makefile
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  deploy/ui/ui_ingress.yaml
  docs/installer-stand-alone.md
  site/installer-stand-alone/index.html
  site/search/search_index.json
  tools/deploy_assisted_installer_configmap.py
  tools/deploy_ui.py
  tools/deployment_options.py
Labels: approved, size/M, lgtm

#3063 [release-ocm-2.4] Bug 2033463: Rename the UI deployment template (#3056)
  Makefile
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  deploy/ui/ui_ingress.yaml
  docs/installer-stand-alone.md
  site/installer-stand-alone/index.html
  site/search/search_index.json
  tools/deploy_assisted_installer_configmap.py
  tools/deploy_ui.py
  tools/deployment_options.py
Labels: approved, size/L, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#3075 MGMT-8423: Rename api-vip-connected validation
  internal/host/host_test.go
  internal/host/refresh_status_preprocessor.go
  internal/host/statemachine.go
  internal/host/validation_id.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  subsystem/metrics_test.go
  swagger.yaml
Labels: approved, size/M, api-review, lgtm

#3073 MGMT-7428: added ignition to apivip check response in swagger
  models/api_vip_connectivity_response.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/S, api-review, lgtm

#3080 MGMT-8623: Updated ignition-endpoint ca_certificate description to say that the content should be base64 encoded
  models/ignition_endpoint.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/XS, api-review, lgtm

#3079 MGMT-8532: Backport infra-env event handling for image service
  docs/events.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/events/events.go
Labels: approved, size/L, lgtm

#3085 NO-ISSUE: changing sno dnsmasq name from 99.. to 50..
  internal/network/manifests_generator.go
Labels: approved, size/XS, lgtm

#3086 MGMT-7330: remove unit-test logic from Jenkins
  Jenkinsfile
  Makefile
Labels: approved, size/XS, lgtm

#2972 MGMT-8280: changing ignition fields in aci and agent from value to secret reference
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  api/hiveextension/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/agent_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/agent-install.openshift.io_agents.yaml
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  docs/hive-integration/crds/agentClusterInstall-with-ignitionEndpoint.yaml
  docs/hive-integration/late-binding.md
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, size/L, api-review, lgtm

#3070 MGMT-8456: REST-API V2 getting started guide
  docs/user-guide/img/rest-api-v1-v2.jpg
  docs/user-guide/rest-api-getting-started.md
  docs/user-guide/rest-api-v1-v2-transition-guide.md
  docs/user-guide/samples/cluster.json
  docs/user-guide/samples/hosts.json
  docs/user-guide/samples/infra_env.json
Labels: approved, size/XL, lgtm

#3091 NO-ISSUE: Added example for tang_server JSON-formatted string to swagger.
  models/disk_encryption.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/XS, api-review, lgtm

#3081 OCPBUGSM-31072: progress bar alignment for day2
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/progress_test.go
  internal/host/host.go
  internal/host/matchers.go
  internal/host/mock_host_api.go
  subsystem/day2_cluster_test.go
  subsystem/host_test.go
Labels: approved, size/L, lgtm

#3087 Allow /30 machine cidr in SNO
  internal/bminventory/inventory.go
  internal/network/cidr_validations.go
  internal/network/cidr_validations_test.go
Labels: approved, size/S, lgtm

#3095 MGMT-8516: Allow filtering infra-env list by cluster id
  client/installer/list_infra_envs_parameters.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  models/infra_env.go
  restapi/embedded_spec.go
  restapi/operations/installer/list_infra_envs_parameters.go
  restapi/operations/installer/list_infra_envs_urlbuilder.go
  subsystem/infra_env_test.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#3094 Added doc on how to boot discovery image on AWS EC2
  docs/user-guide/boot-discovery-image-on-aws-ec2.md
Labels: approved, size/M, lgtm

#3082 MGMT-8477: invoke cluster validations when updating host
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  subsystem/cluster_v2_test.go
Labels: approved, size/M, lgtm

#3090 MGMT-8677: use "edge-infrastructure" organization for all images
  tools/deploy_ui.py
  tools/deployment_options.py
Labels: approved, size/S, lgtm

#3076 MGMT-8095: Change 'ignition_config_image_generated' event type to infra-env
  docs/events.yaml
  internal/bminventory/inventory_test.go
  internal/common/events/events.go
Labels: approved, size/M, lgtm

#3097 NO-ISSUE - Add pyyaml to python requirements
  dev-requirements.txt
Labels: approved, size/XS, lgtm

#3098 MGMT-8671: Fix V2ListHosts response when InfraEnv does not exist
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/S, lgtm

#3100 MGMT-8709: Allow to override IMAGE_SERVICE and ASSISTED_UI images
  Makefile
Labels: approved, size/S, lgtm

#3099 MGMT-8710: Assisted-service fail to get the agent ignition token
  cmd/main.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, size/S, lgtm

#3092 MGMT-8228: Fixed the error message when a host fails to reboot
  internal/host/common.go
Labels: approved, size/XS, lgtm

#3102 MGMT-7385: feature usage doc
  docs/dev/feature-usage.md
Labels: approved, size/M, lgtm

#3107 MGMT-8448: Redirect v1 image downloads to the image service
  client/installer/download_cluster_i_s_o_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  restapi/embedded_spec.go
  restapi/operations/installer/download_cluster_i_s_o_responses.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#3083 MGMT-8663: Support none platform in kube-api for day1
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/cluster_test.go
  subsystem/kubeapi_test.go
  subsystem/utils_test.go
Labels: approved, size/L, api-review, lgtm

#3104 MGMT-8721: Allow host updates when unbound or binding
  internal/host/common.go
  internal/host/host.go
  internal/host/host_test.go
Labels: approved, size/L, lgtm

#3065 MGMT-8498: Adding mounting /etc/pki to next_step,installer and logs commands to allow providing additional certificate bundle
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/logs_cmd.go
  internal/host/hostcommands/next_step_runner_cmd.go
  internal/host/hostcommands/next_step_runner_cmd_test.go
Labels: approved, size/S, lgtm

#3069 Bug 2029876: auto-assign node fails SpecSync
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, size/M, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#3108 NO-ISSUE: update golang-jwt package to v4.2.0
  go.mod
  go.sum
  internal/bminventory/inventory_v2_handlers.go
  internal/gencrypto/token.go
  internal/gencrypto/token_test.go
  pkg/auth/auth_handler_test_utils.go
  pkg/auth/authz_handler.go
  pkg/auth/authz_handler_test.go
  pkg/auth/jwk.go
  pkg/auth/local_authenticator.go
  pkg/auth/rhsso_authenticator.go
  pkg/auth/rhsso_authenticator_test.go
  tools/auth_keys_generator.go
Labels: approved, size/S, lgtm

#3109 NO-ISSUE: upgrade moby to v20.10.12
  go.mod
  go.sum
Labels: approved, size/XS, lgtm

#3110 MGMT-8724: use upstream postgres image for podman
  Makefile
Labels: approved, size/XS, lgtm

#3113 MGMT-8603: Add doc to install operator via OLM
  docs/user-guide/README.md
  docs/user-guide/img/AgentServiceConfig.png
  docs/user-guide/img/InstallOperator.png
  docs/user-guide/img/InstalledOperator.png
  docs/user-guide/img/OperatorDetails.png
  docs/user-guide/img/OperatorHub.png
  docs/user-guide/infrastructure-operator-olm.md
Labels: approved, size/M, lgtm

#3114 NO-ISSUE: Update to dev docs regarding feature-usage
  docs/dev/feature-usage.md
Labels: approved, size/S, lgtm

#3112 MGMT-8364: use LabelSelectorAsSelector for nmstate
  internal/controller/controllers/infraenv_controller.go
Labels: approved, size/M, lgtm

#3111 MGMT-8727: KubeAPI Controllers to use V2 Events endpoint
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/controller_event_wrapper.go
  internal/controller/controllers/controller_event_wrapper_test.go
  internal/events/events_api.go
  subsystem/kubeapi_test.go
Labels: approved, size/M, lgtm

#3115 MGMT-8096: Remove all VSphere platform properties
  internal/bminventory/inventory_test.go
  internal/provider/registry/registry_test.go
  internal/provider/vsphere/installConfig.go
  internal/provider/vsphere/inventory.go
  models/platform.go
  models/vsphere_platform.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/XL, api-review, lgtm

#3116 MGMT-8713: fix ovrit and vshere platform check
  internal/provider/ovirt/base.go
  internal/provider/ovirt/base_test.go
  internal/provider/ovirt/ovirt_suite_test.go
  internal/provider/vsphere/base.go
  internal/provider/vsphere/base_test.go
  internal/provider/vsphere/vshpere_suite_test.go
Labels: approved, size/L, lgtm

#3125 MGMT-8606: Add api-review label to Events API changes
  OWNERS
Labels: approved, size/XS, lgtm

#3121 NO-ISSUE: fix 'yaml' has no attribute 'FullLoader'
  hack/generate.sh
Labels: approved, size/XS, lgtm

#3124 MGMT-7307: Improve the disconnected media message to explain what is …
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/S, lgtm

#3128 NO-ISSUE: minor cleanup to the events generator
  tools/generate_events.py
Labels: approved, size/XS, lgtm

#3122 MGMT-8722: Populate EventsURL in InfraEnv
  cmd/main.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/common.go
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  internal/gencrypto/token.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, lgtm

#3133 MGMT-8698: update status_info, progress when extra workers fails to install
  internal/cluster/cluster.go
  internal/cluster/common.go
  internal/cluster/common_test.go
  internal/cluster/progress_test.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
Labels: approved, size/L, lgtm

#3135 MGMT-8301: Add a V1 API deprecation warning in swagger
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#3129 MGMT-8703: Document adding additional trust bundle
  docs/user-guide/install-customization.md
Labels: approved, size/M, lgtm

#3137 MGMT-8513: V2 link in cluster's Href field
  internal/bminventory/inventory.go
Labels: approved, size/XS, lgtm

#3140 NO-ISSUE: downgrade 4.7 version to test auto bump new mechanism
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_release_images.json
  onprem-environment
  openshift/template.yaml
Labels: approved, size/S, lgtm

#3138 NO-ISSUE: Check events in kubeapi subsystem
  subsystem/kubeapi_test.go
Labels: approved, size/M, lgtm

#3130 Bug 1994696: Clarify not eligible disk error message
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, size/S, bugzilla/severity-urgent, lgtm, bugzilla/valid-bug

#3141 MGMT-8741: Use full name when logging agent update
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/M, lgtm

#3127 MGMT-8607: Store event names in the DB
  internal/common/events/events.go
  internal/controller/controllers/controller_event_wrapper.go
  internal/controller/controllers/controller_event_wrapper_test.go
  internal/events/api/event.go
  internal/events/api/mock_event.go
  internal/events/event.go
  internal/events/event_test.go
  internal/events/events_api.go
  models/event.go
  restapi/embedded_spec.go
  subsystem/events_test.go
  swagger.yaml
  tools/generate_events.py
Labels: approved, size/L, api-review, lgtm
