Repository openshift/assisted-service, pull requests merged in 2021-11, with the labels that each got.

#2798 Bug 2014081: Add user filter for /v2/events
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/common.go
  internal/cluster/installer.go
  internal/cluster/installer_test.go
  internal/cluster/progress_test.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/common/db.go
  internal/common/events/events.go
  internal/controller/controllers/controller_event_wrapper.go
  internal/controller/controllers/controller_event_wrapper_test.go
  internal/events/api/event.go
  internal/events/api/mock_event.go
  internal/events/event.go
  internal/events/event_test.go
  internal/events/events_api.go
  internal/events/eventstest/events_test_utils.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/instruction_manager.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/host/hostrole_test.go
  internal/host/hostutil/update_host.go
  internal/host/hostutil/update_host_test.go
  internal/host/monitor_test.go
  internal/host/transition.go
  internal/host/transition_test.go
  internal/host/validations_test.go
  internal/imgexpirer/imgexpirer.go
  internal/imgexpirer/imgexpirer_test.go
  internal/metrics/metricsManager.go
  internal/operators/handler/handler.go
  internal/operators/handler/handler_test.go
  internal/operators/ocs/validation_test.go
  subsystem/events_test.go
  subsystem/kubeapi_test.go
  tools/generate_events.py
Labels: approved, lgtm, size/XXL, bugzilla/severity-high, bugzilla/valid-bug

#2846 Bug 2017866: Populate requested_hostname in V2ListHosts
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/S, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#2848 Bug 2005259: Progress bar out of order in SNO
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/cluster/cluster.go
  internal/cluster/progress_test.go
  internal/host/host.go
  internal/host/mock_host_api.go
Labels: approved, size/L, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#2860 MGMT-8120: Change Events subsystem tests assertion
  subsystem/events_test.go
Labels: approved, size/XS, lgtm

#2820 NO-ISSUE: Renamed events to a uniform format
  docs/events.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/common/events/events.go
  internal/controller/controllers/controller_event_wrapper_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostrole_test.go
  internal/host/validations_test.go
  internal/imgexpirer/imgexpirer.go
  internal/imgexpirer/imgexpirer_test.go
Labels: approved, lgtm, size/XXL

#2858 MGMT-8113: Update the postgresql image in the operator CSV to the new org in Quay.io
  config/manager/manager.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
Labels: approved, size/XS, lgtm

#2813 MGMT-7915 - create V2 API for Importing (Creating) Day2 Cluster
  client/installer/installer_client.go
  client/installer/v2_import_cluster_parameters.go
  client/installer/v2_import_cluster_responses.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/bminventory/mock_installer_internal.go
  internal/cluster/cluster.go
  internal/cluster/mock_cluster_api.go
  internal/cluster/registrar.go
  internal/common/common.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  mocks/mock_assisted_service.go
  models/import_cluster_params.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_import_cluster.go
  restapi/operations/installer/v2_import_cluster_parameters.go
  restapi/operations/installer/v2_import_cluster_responses.go
  restapi/operations/installer/v2_import_cluster_urlbuilder.go
  subsystem/day2_cluster_test.go
  subsystem/utils_test.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2862 Bug 2016178: Add ClusterOSImage to Baremetal platform
  internal/installcfg/installcfg.go
Labels: approved, size/XS, bugzilla/severity-urgent, lgtm, bugzilla/valid-bug

#2855 MGMT-8108: Clear Progress in Agent status
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, size/S, lgtm

#2863 NO-ISSUE: Add event name documentation
  docs/dev/events.md
Labels: approved, size/S, lgtm

#2864 NO-ISSUE: Add event severity documentation
  docs/dev/events.md
Labels: approved, size/XS, lgtm

#2857 NO-ISSUE: remove '/test all' that just breaks all jobs
  tools/ocp_version_update/update_default_release_versions_to_latest.py
Labels: approved, size/XS, lgtm

#2843 MGMT-8098: Bump OCP versions release 4.7.34 -> 4.7.36, release 4.8.15 -> 4.8.17, release 4.9.0 -> 4.9.4
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_release_images.json
  onprem-environment
  openshift/template.yaml
Labels: approved, size/S, lgtm

#2870 NO-ISSUE: fix usage report on SDN/OVN
  internal/bminventory/inventory.go
  subsystem/cluster_test.go
Labels: approved, size/XS, lgtm

#2778 MGMT-8058: Update Operator CSV for OCM 2.4
  Makefile
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_ocp_versions.json
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/metadata/annotations.yaml
  deploy/operator/setup_assisted_operator.sh
  onprem-environment
  openshift/template.yaml
Labels: approved, size/L, lgtm

#2867 MGMT-8128 - Fix wait_for_assisted_service failing on multiple tests
  dev-requirements.txt
  tools/utils.py
  tools/wait_for_assisted_service.py
Labels: approved, size/S, lgtm

#2821 MGMT-8070: Adds V2 API: V2GetPresignedForClusterCredentials
  client/installer/installer_client.go
  client/installer/v2_get_presigned_for_cluster_credentials_parameters.go
  client/installer/v2_get_presigned_for_cluster_credentials_responses.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_get_presigned_for_cluster_credentials.go
  restapi/operations/installer/v2_get_presigned_for_cluster_credentials_parameters.go
  restapi/operations/installer/v2_get_presigned_for_cluster_credentials_responses.go
  restapi/operations/installer/v2_get_presigned_for_cluster_credentials_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2873 NO-ISSUE: Expand operator CSV description
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
Labels: approved, size/S, lgtm

#2869 MGMT-8062: Update doc for agents-back-to-infraenv
  docs/enhancements/agents-back-to-infraenv.md
Labels: approved, size/M, lgtm

#2844 MGMT-8090: Add state unbinding-requires-user-action
  internal/host/host_test.go
  internal/host/hostcommands/instruction_manager.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/host/pool_host_statemachine.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  models/host.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/M, api-review, lgtm

#2877 MGMT-8149: Add OPENSHIFT_VERSIONS template parameter back
  openshift/template.yaml
Labels: approved, size/XS, lgtm

#2878 MGMT-8149: Add OPENSHIFT_VERSIONS template parameter back (#2877)
  openshift/template.yaml
Labels: approved, size/XS, lgtm

#2822 MGMT-8074: Make the assisted-service more dry run friendly
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/inventory_cmd.go
  internal/host/hostcommands/inventory_cmd_test.go
  internal/host/hostcommands/next_step_runner_cmd.go
Labels: approved, size/M, lgtm

#2849 MGMT-6893: Support custom Ignition Endpoint URL and Ignition token
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  api/v1beta1/agent_types.go
  config/crd/bases/agent-install.openshift.io_agents.yaml
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validations.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/ignition/mock_ignition.go
  models/cluster.go
  models/cluster_create_params.go
  models/cluster_update_params.go
  models/host.go
  models/host_update_params.go
  models/v2_cluster_update_params.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#2876 MGMT-8126: Exposing feature_id in swagger
  models/feature_support_level.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#2880 MGMT-8129: Remove required attribute from current_stage in both host_progress and host_progress_info
  models/host_progress.go
  models/host_progress_info.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/M, api-review, lgtm

#2879 Bug 2011745: Document ignition versions
  docs/user-guide/install-customization.md
Labels: approved, size/S, lgtm

#2859 MGMT 8078: Agent conditions for unbinding-pending-user-action
  api/v1beta1/agent_types.go
  docs/hive-integration/kube-api-conditions.md
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, size/M, api-review, lgtm

#2887 Bug 2020928: Changing the condition that check if disk-encryption is enabled.
  internal/bminventory/inventory.go
  internal/host/hostutil/test_utils.go
  internal/host/validator.go
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
Labels: approved, size/S, bugzilla/severity-urgent, lgtm, bugzilla/valid-bug

#2889 NO-ISSUE: changing the condition that check if disk-encryption is enabled
  internal/bminventory/inventory.go
  internal/host/hostutil/test_utils.go
  internal/host/validator.go
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
Labels: approved, size/S, lgtm

#2745 OCPRHV-589: Initial oVirt provider support
  cmd/main.go
  go.mod
  go.sum
  internal/common/common.go
  internal/common/common_test.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/installcfg/builder/builder.go
  internal/installcfg/installcfg.go
  internal/provider/baremetal/ignition.go
  internal/provider/base.go
  internal/provider/mock_base_provider.go
  internal/provider/ovirt/base.go
  internal/provider/ovirt/consts.go
  internal/provider/ovirt/ignition.go
  internal/provider/ovirt/installConfig.go
  internal/provider/ovirt/inventory.go
  internal/provider/registry/mock_providerregistry.go
  internal/provider/registry/registry.go
  internal/provider/registry/registry_test.go
  internal/provider/vsphere/ignition.go
  models/ovirt_platform.go
  models/platform.go
  models/platform_type.go
  pkg/generator/generator.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2891 MGMT-8166: updateClusterData should handle updates for Tang servers
  internal/bminventory/inventory.go
  subsystem/manifests_test.go
Labels: approved, size/XS, lgtm

#2854 OCPBUGSM-36598: clean progress on reset
  internal/cluster/transition.go
  internal/host/hostutil/update_host.go
  internal/host/transition.go
  subsystem/cluster_test.go
Labels: approved, size/M, lgtm

#2868 Bug 2019415: Cluster installation stages missing from cluster event logs
  docs/events.yaml
  internal/bminventory/inventory.go
  internal/common/events/events.go
  internal/controller/controllers/controller_event_wrapper_test.go
Labels: approved, size/M, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#2871 MGMT-8130: Unbind hosts on cluster delete
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/registrar.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/infraenv_controller.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, lgtm

#2883 MGMT-8131: k8s user can specify CA cert for ignition endpoint
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  api/hiveextension/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/ignition/mock_ignition.go
  models/cluster.go
  models/cluster_create_params.go
  models/cluster_update_params.go
  models/ignition_endpoint.go
  models/v2_cluster_update_params.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/XL, api-review, lgtm

#2888 MGMT-8165: Enhance message when hosts' clocks are not in sync and have more than 4 min gap
  internal/cluster/validator.go
Labels: approved, size/XS, lgtm

#2851 MGMT-7834: webhook infraenv update
  cmd/webadmission/main.go
  internal/controller/controllers/agentserviceconfig_controller.go
  pkg/validating-webhooks/agentinstall/v1beta1/infraenv_admission_hook.go
  pkg/validating-webhooks/agentinstall/v1beta1/infraenv_admission_hook_test.go
  pkg/validating-webhooks/hiveextension/v1beta1/agentclusterinstall_admission_hook.go
Labels: approved, size/XL, lgtm

#2856 NO-ISSUE: Graduate hive CRDs to apiextensions.k8s.io/v1
  hack/crds/hive.openshift.io_clusterdeployments.yaml
  hack/crds/hive.openshift.io_clusterimagesets.yaml
Labels: approved, lgtm, size/XXL

#2874 MGMT-8144: Bump OCP versions release 4.8.17 -> 4.8.18, release 4.9.4 -> 4.9.5
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_release_images.json
  onprem-environment
  openshift/template.yaml
Labels: approved, size/S, lgtm

#2890 MGMT-7423: KubeAPI support for disk encryption
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  api/hiveextension/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, lgtm

#2901 OCPBUGSM-36974: Skipping disk-encryption validation on day2 hosts.
  internal/host/validator.go
Labels: approved, size/XS, lgtm

#2900 MGMT-8188: Update properties order of host events
  docs/events.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_v2_handlers.go
  internal/common/events/events.go
  internal/host/host.go
  internal/host/hostcommands/install_cmd.go
Labels: approved, size/L, lgtm

#2902 MGMT-8192: Logs_cmd command fails if insecure flag is set to true
  internal/host/hostcommands/logs_cmd.go
  internal/host/hostcommands/logs_cmd_test.go
Labels: approved, size/M, lgtm

#2906 NO-ISSUE: Update webhook doc
  docs/dev/kube-api-webhook.md
Labels: approved, size/S, lgtm

#2905 MGMT-8099: Late binding doc update
  docs/hive-integration/README.md
  docs/hive-integration/late-binding.md
Labels: approved, size/S, lgtm

#2824 MGMT-7897: Add Image-Token authentication
  client/installer/installer_client.go
  client/installer/regenerate_infra_env_signing_key_parameters.go
  client/installer/regenerate_infra_env_signing_key_responses.go
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/common/db.go
  internal/gencrypto/keys.go
  internal/gencrypto/token.go
  internal/gencrypto/token_test.go
  internal/migrations/20211108163809_create_infra_env_image_token_key.go
  internal/migrations/20211108163809_create_infra_env_image_token_key_test.go
  internal/migrations/migrations.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  pkg/auth/authenticator.go
  pkg/auth/authz_handler.go
  pkg/auth/authz_handler_test.go
  pkg/auth/local_authenticator.go
  pkg/auth/none_authenticator.go
  pkg/auth/rhsso_authenticator.go
  pkg/auth/rhsso_authenticator_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/regenerate_infra_env_signing_key.go
  restapi/operations/installer/regenerate_infra_env_signing_key_parameters.go
  restapi/operations/installer/regenerate_infra_env_signing_key_responses.go
  restapi/operations/installer/regenerate_infra_env_signing_key_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2904 MGMT-8196: Use postgresql-12-centos7:latest image
  Makefile
  docs/dev/testing.md
  hack/wait_for_postgres.sh
  internal/common/common_unitest_db.go
Labels: approved, size/S, lgtm

#2913 MGMT-8198: Rename host_cluster_registered to host_registration_succeeded
  docs/events.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/events/events.go
Labels: approved, size/M, lgtm

#2914 MGMT-8207: Worker logs does not collected while cluster in status error
  internal/host/hostcommands/logs_cmd.go
  internal/host/hostcommands/logs_cmd_test.go
Labels: approved, size/XS, lgtm

#2910 MGMT-8206: Bump OCP versions release 4.9.5 -> 4.9.6
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_release_images.json
  onprem-environment
  openshift/template.yaml
Labels: approved, size/S, lgtm

#2921 MGMT-8200: Fix controller crash when import installed cluster
  internal/bminventory/inventory.go
  internal/common/conversions.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, lgtm

#2886 MGMT-7693: More V2 subsystem tests
  client/installer/unbind_host_responses.go
  restapi/embedded_spec.go
  restapi/operations/installer/unbind_host_responses.go
  subsystem/cluster_v2_test.go
  subsystem/day2_cluster_test.go
  subsystem/host_v2_test.go
  subsystem/infra_env_test.go
  subsystem/utils_test.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#2920 Bug 2014262: No cache no client cause hub gotta speak to spoke when retrying
  internal/controller/controllers/bmh_agent_controller.go
Labels: approved, size/S, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#2925 MGMT-8229: All host registration events to include optional cluster_id
  docs/events.yaml
  internal/bminventory/inventory.go
  internal/common/events/events.go
Labels: approved, size/S, lgtm

#2875 NO-ISSUE: remove openshift_versions support
  Makefile
  cmd/main.go
  deploy/assisted-service-configmap.yaml
  internal/versions/versions.go
  internal/versions/versions_test.go
  openshift/template.yaml
Labels: approved, size/L, lgtm

#2923 MGMT-8101: Add subsystem for return host to InfraEnv
  subsystem/cluster_v2_test.go
Labels: approved, size/L, lgtm

#2912 MGMT-8079: reboot BMH on unbind-pending-user-action
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/M, lgtm

#2933 NO-ISSUE: set PlatformType on ImportCluster
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/XS, lgtm

#2937 NO-ISSUE: fix commit message validator to allow [<tag>] at start
  hack/check-commit-message.sh
Labels: approved, size/XS

#2936 MGMT-8237: incorrect api responses for cluster managed networking with VMs
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/featuresupport/support_levels_list.go
  internal/usage/consts.go
  models/feature_support_level.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#2938 OCPBUGSM-36861: progress bar goes to 10% after pending user action on reboot
  internal/cluster/progress_test.go
  internal/cluster/transition.go
Labels: approved, size/L, lgtm

#2915 MGMT-8067: Adds disk encryption feature flag
  Makefile
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validations.go
  onprem-environment
  openshift/template.yaml
  tools/deploy_assisted_installer_configmap.py
Labels: approved, size/L, lgtm

#2919 MGMT-8205: Add endpoint to regenerate infraEnv download URL
  client/installer/get_infra_env_download_url_parameters.go
  client/installer/get_infra_env_download_url_responses.go
  client/installer/installer_client.go
  docs/enhancements/image-service-cloud-authentication.md
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  mocks/mock_assisted_service.go
  models/infra_env_image_url.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/get_infra_env_download_url.go
  restapi/operations/installer/get_infra_env_download_url_parameters.go
  restapi/operations/installer/get_infra_env_download_url_responses.go
  restapi/operations/installer/get_infra_env_download_url_urlbuilder.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#2945 MGMT-7231: ODF docs
  docs/dev/olm-operator-plugins.md
Labels: approved, size/S, lgtm

#2939 Bug 2023616: Add LivenessProbe to Image Service (#2751)
  internal/controller/controllers/agentserviceconfig_controller.go
Labels: approved, size/S, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#2941 NO-ISSUE: remove default_ocp_versions.json
  data/default_ocp_versions.json
Labels: approved, size/M, lgtm

#2909 MGMT-6893: Fix ignition endpoint URL validation
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
Labels: approved, size/M, lgtm

#2942 MGMT-8127: Webhook block unbind if Agent is installing
  cmd/webadmission/main.go
  internal/controller/controllers/agentserviceconfig_controller.go
  pkg/validating-webhooks/agentinstall/v1beta1/agent_admission_hook.go
  pkg/validating-webhooks/agentinstall/v1beta1/agent_admission_hook_test.go
Labels: approved, size/L, lgtm

#2947 MGMT-8276: Add Day2 state in Agent conditions
  docs/hive-integration/kube-api-conditions.md
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, size/M, lgtm

#2922 MGMT-8225: Bump OCP versions release 4.8.18 -> 4.8.19
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_release_images.json
  onprem-environment
  openshift/template.yaml
Labels: approved, size/S, lgtm

#2949 NO-ISSUE: there is no need to base encode an already base64 encoded CA cert
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
Labels: approved, size/S, lgtm

#2950 MGMT-8243: remove log msg about user issues with tokens
  pkg/auth/rhsso_authenticator.go
Labels: approved, size/XS, lgtm

#2940 MGMT-7401: Add cluster progress to ACI
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  api/hiveextension/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/agent_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/agent-install.openshift.io_agents.yaml
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  internal/bminventory/inventory.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/clusterdeployments_controller.go
  subsystem/cluster_test.go
  subsystem/kubeapi_test.go
  subsystem/utils_test.go
Labels: approved, size/L, lgtm

#2962 MGMT-8295: reconcile fail in case agent spec.IgnitionEndpointToken isn't empty due to null pointer dereference
  internal/controller/controllers/agent_controller.go
Labels: approved, size/XS, lgtm

#2963 Bug 2025280: Add ClusterOSImage to Baremetal platform (#2862)
  internal/installcfg/installcfg.go
Labels: approved, size/XS, bugzilla/severity-urgent, lgtm, bugzilla/valid-bug

#2951 MGMT-8278: Allow updating agent properties before binding
  internal/bminventory/inventory.go
  subsystem/host_v2_test.go
Labels: approved, size/S, lgtm

#2955 Bump OCP versions release 4.7.36 -> 4.7.37, release 4.8.19 -> 4.8.20, release 4.9.6 -> 4.9.7
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_release_images.json
  onprem-environment
  openshift/template.yaml
Labels: approved, size/S, lgtm

#2964 Make openshift-edge-bot author for OCP version bump
  tools/ocp_version_update/Jenkinsfile.default_release_update
Labels: approved, size/XS, lgtm

#2435 NO-ISSUE: clear host's log timestamp when deleting the logs
  internal/host/transition.go
  subsystem/cluster_test.go
Labels: approved, size/S, lgtm

#2956 Skip tickets creation when bumping OCP versions
  dev-requirements.txt
  tools/ocp_version_update/Jenkinsfile.default_release_update
  tools/ocp_version_update/update_default_release_versions_to_latest.py
Labels: approved, size/L, lgtm

#2965 Only inspect netrc file in case file exists
  tools/ocp_version_update/update_default_release_versions_to_latest.py
Labels: approved, size/XS, lgtm

#2966 MGMT-8298: MCP can’t be set until the host is day2
  internal/host/host.go
  internal/host/host_test.go
Labels: approved, size/XS, lgtm

#2969 MGMT-8305: Ignition token passes extra colon
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
Labels: approved, size/XS, lgtm

#2967 MGMT-8296: Ignition token is not updated in UpdateHost API
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/mock_host_api.go
Labels: approved, size/L, lgtm

#2958 MGMT-8281: subsystem print resources when subsystem tests fail
  subsystem/kubeapi_test.go
  subsystem/utils_test.go
Labels: approved, size/M, lgtm

#2971 MGMT-8307: fix flaky reset log test
  subsystem/cluster_test.go
Labels: approved, size/M, lgtm

#2970 MGMT-8279: kube-api - ensure release images exists upon install
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/common.go
Labels: approved, size/L, lgtm

#2948 MGMT-8222: Fix flaky subsystem test register_same_host_id
  subsystem/host_test.go
Labels: approved, size/S, lgtm

#2976 MGMT-7817: Rename env var for operator upgrade
  deploy/operator/upgrade/after_upgrade.sh
Labels: approved, size/S, lgtm

#2974 MGMT-8237: incorrect api responses for cluster managed networking with vms (#2936)
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/featuresupport/support_levels_list.go
  internal/usage/consts.go
  models/feature_support_level.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#2978 NO-ISSUE: AgentController move log to debug
  internal/controller/controllers/agent_controller.go
Labels: approved, size/XS, lgtm

#2946 MGMT-8088 validate hostname before transition to known-unbound
  internal/host/pool_host_statemachine.go
  internal/host/transition_test.go
Labels: approved, size/S, lgtm

#2983 MGMT-7716: Add IMAGE_SERVICE_BASE_URL to template
  openshift/template.yaml
Labels: approved, size/XS, lgtm

#2986 MGMT-4502: Put unit-test pgsql data on tmpfs again - the path changed
  Makefile
Labels: approved, size/XS, lgtm

#2980 MGMT-7929: Host status update events to include optional cluster ID
  docs/events.yaml
  internal/bminventory/inventory_test.go
  internal/common/events/events.go
  internal/events/eventstest/events_test_utils.go
  internal/host/host_test.go
  internal/host/hostutil/update_host.go
  internal/host/hostutil/update_host_test.go
  internal/host/monitor_test.go
  internal/host/transition_test.go
  internal/host/validations_test.go
Labels: approved, size/M, lgtm

#2987 MGMT-8346: fix iso url when using image service
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
Labels: approved, size/S, lgtm

#2982 MGMT-8333: Cluster failed to update console operator status
  internal/bminventory/inventory_v2_handlers.go
  internal/cluster/cluster.go
  internal/cluster/common.go
Labels: approved, size/S, lgtm

#2981 MGMT-8178: Add InfraEnv package
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/infraenv/infraenv.go
  internal/infraenv/infraenv_suite_test.go
  internal/infraenv/infraenv_test.go
  internal/infraenv/mock_infraenv_api.go
Labels: approved, size/L, lgtm

#2991 NO-ISSUE: Fix typo in error message
  internal/bminventory/inventory.go
Labels: approved, size/XS, lgtm

#2992 MGMT-8351: Hosts table primary key has to be migrated from (cluster_id, id) to (infra_env_id, id)
  internal/migrations/20211125182200_change_hosts_pkey.go
  internal/migrations/20211125182200_change_hosts_pkey_test.go
  internal/migrations/migrations.go
Labels: approved, size/L, lgtm

#2988 MGMT-8337: Remove unsused hostname from Agent CRD
  api/v1beta1/agent_types.go
  config/crd/bases/agent-install.openshift.io_agents.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
Labels: approved, size/XS, lgtm

#2916 MGMT-7330: Create a job in prow CI to run assisted-service unit tests
  Dockerfile.assisted-service-build
  Makefile
  hack/setup_env.sh
  hack/start_db.sh
  internal/common/common_unitest_db.go
Labels: approved, kind/dependency-change, size/M, lgtm

#2997 MGMT-8372: Removing data from "Custom manifests" usage
  internal/manifests/manifests.go
  subsystem/manifests_test.go
Labels: approved, size/S, lgtm

#3001 Upgrade git on build image
  Dockerfile.assisted-service-build
Labels: approved, kind/dependency-change, size/XS, lgtm
