Repository openshift/assisted-service, pull requests merged in 2022-03, with the labels that each got.

#3267 MGMT-9108: Remove V1 GetPresignedForClusterFiles (GET)
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  subsystem/authz_test.go
Labels: approved, size/L, lgtm

#3408 MGMT-9424: Add to swagger api to transform cluster from day1 to day2
  client/installer/installer_client.go
  client/installer/transform_cluster_to_day2_parameters.go
  client/installer/transform_cluster_to_day2_responses.go
  internal/bminventory/inventory_v2_handlers.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/transform_cluster_to_day2.go
  restapi/operations/installer/transform_cluster_to_day2_parameters.go
  restapi/operations/installer/transform_cluster_to_day2_responses.go
  restapi/operations/installer/transform_cluster_to_day2_urlbuilder.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#3345 MGMT-9206: Allow arm baremetal platform installation
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  pkg/generator/generator.go
  pkg/generator/mock_install_config.go
Labels: approved, size/L, lgtm

#3388 MGMT-9192: Unify spoke client to be a single client in assisted service
  cmd/main.go
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/mock_spoke_k8s_client.go
  internal/controller/controllers/spoke_cluster.go
  internal/controller/controllers/spoke_k8s_client.go
Labels: approved, size/L, lgtm

#3417 MGMT-9115: Remove V1 GetDiscoveryIgnition UpdateDiscoveryIgnition
  docs/events.yaml
  docs/user-guide/rest-api-v1-v2-transition-guide.md
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/events/events.go
  pkg/filemiddleware/middleware.go
Labels: approved, size/L, api-review, lgtm

#3409 MGMT-8879: Add ZTP None platform day2 flow
  deploy/operator/README.md
  deploy/operator/utils.sh
  deploy/operator/ztp/add-remote-nodes-playbook.yaml
  deploy/operator/ztp/add_day2_remote_nodes.sh
  deploy/operator/ztp/assisted-installer-crds-playbook.yaml
  deploy/operator/ztp/baremetalHost.j2
  deploy/operator/ztp/deploy_spoke_cluster.sh
  deploy/operator/ztp/none_platform_utils.sh
Labels: approved, size/L, lgtm

#3389 MGMT-9383: Add enhancement doc for iPXE boot
  docs/enhancements/ipxe-host-boot.md
Labels: approved, size/L, lgtm

#3428 NO-ISSUE: update day2 API doc
  docs/user-guide/rest-api-day2.md
Labels: approved, size/XS, lgtm

#3323 MGMT-9014: Fix OpenShift Virtualization disk validation message for HPP disk
  internal/operators/cnv/cnv_operator.go
  internal/operators/cnv/cnv_operator_test.go
  pkg/conversions/conversions.go
Labels: approved, size/S, lgtm, ok-to-test

#3427 MGMT-9110: remove v1 UpdateCluster
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  pkg/auth/auth_assisted_service_mock_test.go
  pkg/auth/authz_handler_test.go
  subsystem/ams_subscriptions_test.go
  subsystem/cluster_test.go
  subsystem/day2_cluster_test.go
  subsystem/host_test.go
  subsystem/ipv6_test.go
  subsystem/manifests_test.go
  subsystem/metrics_test.go
  subsystem/operators_test.go
  subsystem/utils_test.go
Labels: approved, lgtm, size/XXL

#3406 MGMT-9357 split api dir into a sub module
  Dockerfile.assisted-service
  Dockerfile.assisted-service-build
  Dockerfile.assisted-service-debug
  Dockerfile.bundle
  api/common/zz_generated.deepcopy.go
  api/go.mod
  api/go.sum
  api/hiveextension/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  go.mod
  go.sum
  hack/crds/hive.openshift.io_clusterdeployments.yaml
  hack/crds/metal3.io_baremetalhosts.yaml
  hack/generate.sh
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/clusterdeployments_controller.go
  models/go.mod
Labels: approved, kind/dependency-change, api-review, lgtm, size/XXL

#3435 NO-ISSUE: Remove mocks missed in previous PRs
  internal/bminventory/mock_installer_internal.go
Labels: approved, size/M, lgtm

#3429 MGMT-9485: validate manifests names uniqueness specified in configmaps
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/M, lgtm

#3436 MGMT-9527 fix generate-bundle after moving api to sub modules
  deploy/olm-catalog/manifests/agent-install.openshift.io_agentserviceconfigs.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  hack/generate.sh
Labels: approved, size/L, lgtm

#3424 MGMT-8794: refresh hosts on cluster update
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  subsystem/operators_test.go
Labels: approved, size/L, lgtm

#3449 MGMT-9541: Fix mismatch swagger-codgen versions. Set both versions to v2.4.18
  Dockerfile.assisted-service
  hack/generate.sh
Labels: approved, kind/dependency-change, size/XS, lgtm

#3421 MGMT-9467: Port authz_handler unit-tests to use V2 APIs
  pkg/auth/auth_assisted_service_mock_test.go
  pkg/auth/authz_handler_test.go
Labels: approved, size/L, lgtm

#3426 MGMT-9221 Automatic user-defined agent labels enhancement
  docs/enhancements/automatic-agent-classification-labels.md
Labels: approved, size/L, lgtm

#3326 improve docs: mention minikube tunnel
  README.md
Labels: approved, size/XS, lgtm, ok-to-test

#3454 MGMT-9540: Add iPXE URLs to InfraEnv CRD
  api/v1beta1/infraenv_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/agent-install.openshift.io_infraenvs.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
  docs/hive-integration/README.md
  docs/hive-integration/kube-api-getting-started.md
Labels: approved, size/L, api-review, lgtm

#3456 MGMT-9556: ZTP CI fix: increase the timeout clusterDeployment installed status
  deploy/operator/utils.sh
Labels: approved, size/XS, lgtm

#3446 MGMT-9334: Add an endpoint to download an ipxe-boot script
  client/installer/v2_download_infra_env_files_responses.go
  docs/enhancements/ipxe-host-boot.md
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  restapi/embedded_spec.go
  restapi/operations/installer/v2_download_infra_env_files_parameters.go
  restapi/operations/installer/v2_download_infra_env_files_responses.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#3450 MGMT-9546: update OKD configuration to 4.10
  data/default_okd_os_images.json
  data/default_okd_release_images.json
  deploy/podman/okd-configmap.yml
Labels: approved, size/S, lgtm

#3441 MGMT-8824: Copy additional NTP sources to chrony manifests
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
Labels: approved, size/S, lgtm

#3452 MGMT-9550: Fix automatic agent inventory labels
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, lgtm

#3419 MGMT-9177: OVNKubernetes as network type with SNO
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  docs/user-guide/network-configuration.md
  internal/cluster/transition_test.go
  internal/cluster/validator.go
  internal/cluster/validator_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/installcfg/builder/builder.go
  internal/installcfg/builder/builder_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, api-review, lgtm

#3445 MGMT-8809: Fix e2e-metal-assisted-operator-disconnected CI job
  deploy/operator/mirror_utils.sh
  deploy/operator/setup_assisted_operator.sh
Labels: approved, size/M, lgtm

#3468 MGMT-9470 - Add a pin-latest.py script that pins catalog dependencies
  deploy/olm-catalog/pin-latest.py
  deploy/olm-catalog/requirements.txt
Labels: approved, size/L, lgtm

#3465 MGMT-9577: Upgrade gorm to v1.23.2 (latest)
  go.mod
  go.sum
  internal/cluster/cluster.go
  internal/migrations/20201019194303_change_overrides_to_text_test.go
  internal/migrations/20201202140700_change_image_ssh_key_text_test.go
  internal/migrations/20210218160100_validations_info_to_text_test.go
  internal/migrations/20210223090000_host_validations_info_to_text_test.go
  internal/migrations/20211115162400_modify_events_id_test.go
  internal/migrations/20220113152127_change_cluster_ssh_key_to_text_test.go
  internal/migrations/migrations_suite_test.go
  subsystem/cluster_test.go
Labels: approved, size/M, lgtm

#3469 NO-ISSUE: sporadic ci failure to get epel metadata
  hack/setup_env.sh
Labels: approved, size/XS, lgtm

#3463 MGMT-9277: Optimize connectivity check post step reply to improve load for large multi-node clusters
  internal/host/host.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_metrics_manager_api.go
  subsystem/metrics_test.go
Labels: approved, size/L, lgtm

#3474 NO-ISSUE: generate support rootless podman
  Makefile
  hack/generate.sh
Labels: approved, size/S, lgtm

#3470 MGMT-9584: Remove V1 middleware
  cmd/main.go
  openshift/template.yaml
  pkg/app/middleware.go
  pkg/app/middleware_test.go
Labels: approved, size/M, lgtm

#2932 MGMT-7231: Deploy ODF operator
  config/crd/bases/agent-install.openshift.io_agents.yaml
  config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
  config/crd/bases/agent-install.openshift.io_infraenvs.yaml
  config/crd/bases/agent-install.openshift.io_nmstateconfigs.yaml
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agentserviceconfigs.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_nmstateconfigs.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  docs/dev/olm-operator-plugins.md
  internal/bminventory/inventory.go
  internal/cluster/cluster_test.go
  internal/cluster/progress_test.go
  internal/cluster/statemachine.go
  internal/cluster/validation_id.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/monitor_test.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/host/validations_test.go
  internal/migrations/20210223090000_host_validations_info_to_text_test.go
  internal/operators/builder.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/manager_test.go
  internal/operators/ocs/consts.go
  internal/operators/ocs/manifests_test.go
  internal/operators/ocs/validations.go
  internal/operators/odf/consts.go
  internal/operators/odf/manifest.go
  internal/operators/odf/manifests_test.go
  internal/operators/odf/odf_operator.go
  internal/operators/odf/odf_operator_test.go
  internal/operators/odf/odf_suite_test.go
  internal/operators/odf/test_utils.go
  internal/operators/odf/validation_test.go
  internal/operators/odf/validations.go
  internal/versions/versions_test.go
  models/cluster_validation_id.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  subsystem/operators_test.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL, ok-to-test

#3425 MGMTBUGSM-112: validate ImageSetRef in ACI webhook
  pkg/validating-webhooks/hiveextension/v1beta1/agentclusterinstall_admission_hook.go
  pkg/validating-webhooks/hiveextension/v1beta1/agentclusterinstall_admission_hook_test.go
Labels: approved, size/M, lgtm

#3479 MGMT-9470: Make script to pin catalog compatible with python 3.6
  deploy/olm-catalog/pin-latest.py
Labels: approved, size/XS, lgtm

#3462 MGMT-9314: Reduce the amount of agent updates in agent and BMH reconcilers by updating only agents that actually changed
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  internal/controller/controllers/common.go
  internal/controller/controllers/mock_k8s_client.go
Labels: approved, size/L, lgtm

#3355 MGMT-9279: Remove assisted-service database timeout
  cmd/main.go
Labels: approved, size/XS, lgtm

#3488 MGMT-9468: Add dashboards for events scraper and elasticsearch
  dashboards/grafana-dashboard-assisted-elasticsearch.configmap.yaml
  dashboards/grafana-dashboard-assisted-events-scrape.configmap.yaml
Labels: approved, lgtm, size/XXL

#3476 MGMT-9609: Remove V1 discovery-ignition-params
  models/discovery_ignition_params.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/M, api-review, lgtm

#3464 MGMT-9566: Improve UpdateInstallProgress performance calculating cluster progress
  internal/bminventory/inventory.go
  internal/cluster/cluster.go
  internal/cluster/progress_test.go
  internal/host/common.go
  internal/host/host.go
Labels: approved, size/L, lgtm

#3494 MGMT-9629: change the ODF feature key to ODF only
  internal/featuresupport/support_levels_list.go
  models/feature_support_level.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/S, api-review, lgtm

#3460 MGMT-9539: Add presigned iPXE script URL endpoint
  client/installer/get_infra_env_download_url_responses.go
  client/installer/get_infra_env_presigned_file_url_parameters.go
  client/installer/get_infra_env_presigned_file_url_responses.go
  client/installer/installer_client.go
  client/installer/v2_get_presigned_for_cluster_credentials_responses.go
  client/installer/v2_get_presigned_for_cluster_files_responses.go
  cmd/main.go
  docs/enhancements/ipxe-host-boot.md
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  mocks/mock_assisted_service.go
  models/presigned.go
  models/presigned_url.go
  pkg/auth/auth_assisted_service_mock_test.go
  pkg/auth/authz_handler.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/get_infra_env_download_url_responses.go
  restapi/operations/installer/get_infra_env_presigned_file_url.go
  restapi/operations/installer/get_infra_env_presigned_file_url_parameters.go
  restapi/operations/installer/get_infra_env_presigned_file_url_responses.go
  restapi/operations/installer/get_infra_env_presigned_file_url_urlbuilder.go
  restapi/operations/installer/v2_get_presigned_for_cluster_credentials_responses.go
  restapi/operations/installer/v2_get_presigned_for_cluster_files_responses.go
  subsystem/infra_env_test.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#3490 MGMT-9528: remove dependency on docker invocation for code generation
  Dockerfile.assisted-service-build
  config/crd/bases/agent-install.openshift.io_agents.yaml
  config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
  config/crd/bases/agent-install.openshift.io_infraenvs.yaml
  config/crd/bases/agent-install.openshift.io_nmstateconfigs.yaml
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agentserviceconfigs.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_nmstateconfigs.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  hack/generate.sh
  tools/generate_python_client.sh
Labels: approved, kind/dependency-change, size/M, lgtm

#3489 MGMTBUGSM-191: Race between agent and clusterDeployment reconciler causes day2 host installation to ignore requested hostname
  internal/controller/controllers/agent_controller.go
Labels: approved, size/M, lgtm

#3499 NO-ISSUE: generate CRDs in root and api dir
  hack/generate.sh
Labels: approved, size/S, lgtm

#3507 Bug 2065661: `pin-latest.py` should allow a custom tag to be set
  deploy/olm-catalog/pin-latest.py
Labels: approved, size/S, lgtm, bugzilla/severity-low, bugzilla/valid-bug

#3501 Bug 2063570: ipv6 spoke cluster installation would fail when unchecking 'use advanced network', due to ipv4 defaults cidrs
  internal/cluster/refresh_status_preprocessor.go
  internal/cluster/statemachine.go
  internal/cluster/transition_test.go
  internal/cluster/validation_id.go
  internal/cluster/validator.go
  internal/common/common.go
  internal/network/utils.go
  models/cluster_validation_id.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#3500 NO-ISSUE: optimize build image size
  .dockerignore
  Dockerfile.assisted-service-build
  hack/setup_env.sh
Labels: approved, kind/dependency-change, size/S, lgtm

#3486 MGMT-9403: cluster editor wiremock stubs
  subsystem/wiremock_stubs.go
Labels: approved, size/M, lgtm

#3473 MGMT-9443: tenancy enhancement doc
  docs/enhancements/auth_flow.png
  docs/enhancements/tenancy-based-auth.md
Labels: approved, size/L, lgtm

#3482 MGMT-9443: tenancy based auth
  Makefile
  internal/cluster/validations/validation_test.go
  pkg/auth/auth_utils.go
  pkg/auth/authz_handler.go
  pkg/auth/authz_handler_test.go
  pkg/ocm/authorization.go
  pkg/ocm/mock_authorization.go
  pkg/ocm/utils.go
  subsystem/authz_test.go
  subsystem/subsystem_suite_test.go
  tools/auth_keys_generator.go
Labels: approved, size/L, lgtm

#3228 Bug 2035638: Stop BMH reconcile if InfraEnv label is missing
  deploy/assisted-service.yaml
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#3496 MGMT-9653: Update Assisted Grafana dashboards V2
  dashboards/grafana-dashboard-assisted-installer-agent-api.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-basic-cluster-operation.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-general-overview.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-weekly-overview.configmap.yaml
Labels: approved, lgtm, size/XXL

#3527 NO-ISSUE: Reduce build image size with yum clean all
  Dockerfile.assisted-service-build
Labels: approved, kind/dependency-change, size/XS, lgtm

#3506 Bug 2065649: Fix image tags in operator's CSV
  Makefile
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/operator/setup_assisted_operator.sh
Labels: approved, size/M, lgtm, bugzilla/severity-low, bugzilla/valid-bug

#3434 MGMT-9511: Removing reset cmd as it is not used
  internal/host/hostcommands/instruction_manager.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/host/hostcommands/reset_installation_cmd.go
  internal/host/hostcommands/reset_installation_cmd_test.go
  models/step_type.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  subsystem/host_test.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#3517 MGMT-9683: don't mark vsphere installation with Cluster-managed-netwo…
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/M, lgtm

#3480 Bug 2066917: Set boot artifact URLs in infra-env
  cmd/main.go
  internal/bminventory/inventory_v2_handlers.go
  internal/controller/controllers/common.go
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  internal/imageservice/url_test.go
  internal/imageservice/urls.go
Labels: approved, size/L, api-review, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#3531 Bug 2066786: Set the correct stopping state for a day2 cluster.
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, bugzilla/severity-unspecified, size/XS, lgtm, bugzilla/valid-bug

#3258 MGMT-8300: Allow API VIP on cluster creation
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validations.go
  models/cluster_create_params.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: approved, size/XL, api-review, lgtm

#3512 MGMT-9371: added owner query param to clusters/infraenvs requests
  client/installer/list_infra_envs_parameters.go
  client/installer/v2_list_clusters_parameters.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/identity/identity.go
  internal/identity/identity_test.go
  restapi/embedded_spec.go
  restapi/operations/installer/list_infra_envs_parameters.go
  restapi/operations/installer/list_infra_envs_urlbuilder.go
  restapi/operations/installer/v2_list_clusters_parameters.go
  restapi/operations/installer/v2_list_clusters_urlbuilder.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#3532 Bug 2055333: gc api server when controller is done
  internal/controller/controllers/agentserviceconfig_controller.go
Labels: approved, size/XS, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#3524 Bug 2065288: Add support for Ignition overrides for day2 worker
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/ignition/mock_ignition.go
Labels: approved, bugzilla/severity-unspecified, size/L, lgtm, bugzilla/valid-bug

#3547 MGMT-9404: remove user filter from UpdateHostApproved
  internal/bminventory/inventory.go
Labels: approved, size/XS, lgtm

#3543 MGMT-9478: expose enable_org_tenancy feature flag
  Makefile
  openshift/template.yaml
  skipper.env
  tools/deploy_assisted_installer_configmap.py
Labels: approved, size/S, lgtm

#3548 MGMT-9734: Fix networking issue while trying to get cluster's current release
  tools/handle_ocp_versions.py
Labels: approved, size/S, lgtm

#3493 Bug 2066196: ensure secrets have backup labels
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/common.go
Labels: approved, size/M, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#3530 MGMT-9559: Using vSphere integration creates extraneous machines and …
  internal/ignition/ignition.go
  internal/provider/vsphere/ignition.go
Labels: approved, size/M, lgtm

#3545 NO-ISSUE: Change default release image to 4.10
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm

#3564 MGMT-9451: Move cmd commands from service to agent
  models/install_cmd_request.go
  models/logs_gather_cmd_request.go
  models/next_step_cmd_request.go
  models/step_type.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#3569 MGMT-9451: Move cmd commands from service to agent
  models/install_cmd_request.go
  models/logs_gather_cmd_request.go
  models/next_step_cmd_request.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/M, api-review, lgtm

#3549 NO-ISSUE: bump github.com/moby version
  go.mod
  go.sum
Labels: approved, size/XS, lgtm

#3552 MGMT-9034: Allow all domains for CORS when deploying locally
  deploy/assisted-image-service.yaml
Labels: approved, size/XS, lgtm

#3491 NO-ISSUE: Better documentation for subsystem tests
  Makefile
  docs/dev/running-test.md
  hack/k8s_service_host_port.jq
  skipper.env
Labels: approved, size/L, lgtm

#3553 MGMT-9742: Populate API VIP and Machine Networks in cluster creation via KubeAPI
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validations.go
  internal/controller/controllers/clusterdeployments_controller.go
Labels: approved, size/S, lgtm

#3574 MGMT-9776: [Assisted-4.10] [Staging] multi cluster - installation failing
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/XS, api-review, lgtm

#3560 MGMT-7365: Deprecate single network configuration fields
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster_test.go
  internal/cluster/common.go
  internal/cluster/common_test.go
  internal/host/transition_test.go
  internal/installcfg/builder/builder_test.go
  internal/migrations/20220325125504_multiple_networks_cleanup.go
  internal/migrations/20220325125504_multiple_networks_cleanup_test.go
  internal/migrations/migrations.go
  models/cluster_network.go
  models/machine_network.go
  models/service_network.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  subsystem/cluster_v2_test.go
  subsystem/infra_env_test.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#3572 MGMT-9779: CI - Retry cluster-info readiness
  Makefile
  tools/wait_for_cluster_info.py
Labels: approved, size/M, lgtm

#3555 NO-ISSUE: Clean up remaining references to onprem-iso
  Dockerfile.assisted-service
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  hack/generate.sh
Labels: approved, kind/dependency-change, size/L, lgtm

#3561 MGMT-9532: Don't set openshift version in upgrade files
  deploy/operator/upgrade/after_upgrade.sh
  deploy/operator/upgrade/before_upgrade.sh
Labels: approved, size/XS, lgtm

#3575 MGMT-9776: [Assisted-4.10] [Staging] multi cluster - installation failing
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/XS, api-review, lgtm

#3559 MGMT-9532: Remove remaining references to ocpmetal quay org
  Dockerfile.assisted-service-debug
  deploy/operator/setup_assisted_operator.sh
  deploy/postgres/postgres-deployment-ephemeral.yaml
  deploy/postgres/postgres-deployment.yaml
  docs/dev/testing.md
  docs/hive-integration/kube-api-getting-started.md
  docs/operator.md
  docs/user-guide/samples/hosts.json
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validation_test.go
  internal/controller/controllers/images.go
  internal/host/hostcommands/api_vip_connectivity_check_cmd_test.go
  internal/host/hostcommands/connectivity_check_cmd_test.go
  internal/host/hostcommands/dhcp_allocate_cmd_test.go
  internal/host/hostcommands/disk_performance_cmd_test.go
  internal/host/hostcommands/domain_name_resolution_cmd_test.go
  internal/host/hostcommands/free_addresses_cmd_test.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/instruction_manager.go
  internal/host/hostcommands/inventory_cmd_test.go
  internal/ignition/ignition.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  tools/deploy_assisted_installer_configmap.py
Labels: approved, kind/dependency-change, size/L, lgtm

#3588 NO-ISSUE: tenancy authz - added PATCH cluster test
  subsystem/authz_test.go
Labels: approved, size/S, lgtm

#3594 Revert "MGMT-9272 Automatic agent classification labels (#3516)"
  api/v1beta1/agentclassification_types.go
  api/v1beta1/zz_generated.deepcopy.go
  cmd/main.go
  cmd/webadmission/main.go
  config/crd/bases/agent-install.openshift.io_agentclassifications.yaml
  config/crd/kustomization.yaml
  config/crd/resources.yaml
  config/rbac/role.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agentclassifications.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  docs/enhancements/automatic-agent-classification-labels.md
  docs/hive-integration/agent-labels.md
  docs/hive-integration/crds/agentClassification.yaml
  go.mod
  go.sum
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agentclassification_controller.go
  internal/controller/controllers/agentclassification_controller_test.go
  internal/controller/controllers/agentlabel_controller.go
  internal/controller/controllers/agentlabel_controller_test.go
  pkg/validating-webhooks/agentinstall/v1beta1/agent_classification_admission_hook.go
  pkg/validating-webhooks/agentinstall/v1beta1/agent_classification_admission_hook_test.go
  subsystem/cluster_test.go
  subsystem/kubeapi_test.go
Labels: approved, api-review, lgtm, size/XXL

#3566 NO-ISSUE: added arm64 images for ocp 4.10
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
  subsystem/kubeapi_test.go
Labels: approved, size/M, lgtm

#3590 MGMT-9172: Misleading "No networks found for host" errors reported for hosts which don't have any IPv4 addresses
  internal/common/test_configuration.go
  internal/host/hostcommands/free_addresses_cmd.go
  internal/host/hostcommands/free_addresses_cmd_test.go
Labels: approved, size/M, lgtm

#3562 Bug 2065034: Correct ignition validation message for day 2 host
  internal/host/validations_test.go
  internal/host/validator.go
Labels: approved, bugzilla/severity-unspecified, size/L, lgtm, bugzilla/valid-bug

#3587 MGMT-9793: Include an optional cluster_id for image_info_updated event
  docs/events.yaml
  internal/bminventory/inventory.go
  internal/common/events/events.go
Labels: approved, size/S, api-review, lgtm

#3597 MGMT-9726: Wait for assisted-image-service when deploying the operator
  deploy/operator/setup_assisted_operator.sh
Labels: approved, size/XS, lgtm

#3596 [release-ocm-2.5] Bug 2069974: Host status change to insufficient when binding a host to a cluster
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/common.go
  internal/cluster/validator.go
  internal/common/test_configuration.go
  internal/network/machine_network_cidr.go
  internal/network/utils.go
Labels: approved, size/L, bugzilla/severity-urgent, lgtm, bugzilla/valid-bug

#3599 MGMT-9453: moving part of validation logic to pkg to use in agent
  internal/bminventory/inventory.go
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
  internal/dns/dns.go
  internal/host/hostutil/host_utils.go
  internal/host/hostutil/host_utils_test.go
  pkg/validations/validations.go
  pkg/validations/validations_test.go
Labels: approved, size/XL, lgtm

#3585 MGMT-9779: Call cluster-info with a namespace
  Makefile
  tools/wait_for_cluster_info.py
Labels: approved, size/XS, lgtm

#3571 Bug 2066069: improve ClusterImageSet sync error message
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, size/S, lgtm, bugzilla/severity-low, bugzilla/valid-bug
