Repository openshift/assisted-service, pull requests merged in 2022-11, with the labels that each got.

#4559 MGMT-12402: Add url auth for getting a single infra-env
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/XS, api-review, lgtm

#4560 MGMT-11805: Don't go through the API for setting a discovery password
  docs/set-discovery-password.md
Labels: approved, size/L, lgtm

#4514 MGMT-9023: Add hyperthreading feature usage
  internal/bminventory/inventory.go
  internal/usage/consts.go
  subsystem/cluster_test.go
Labels: approved, size/S, lgtm

#4325 MGMT-11752: enhancement doc: ai on zero worker hypershift
  docs/enhancements/ai-on-hypershift.png
  docs/enhancements/ai-on-zero-worker-hypershift.md
Labels: approved, size/L, lgtm

#4520 MGMT-10819: Ensure the preprovisioningimage arch matches the infraenv
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
Labels: approved, size/M, lgtm

#4548 MGMT-12353: Add dual-stack VIP fields to the Rest API
  api/vendor/github.com/openshift/assisted-service/models/api_vip.go
  api/vendor/github.com/openshift/assisted-service/models/cluster.go
  api/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  api/vendor/github.com/openshift/assisted-service/models/ingress_vip.go
  api/vendor/github.com/openshift/assisted-service/models/ip.go
  api/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
  models/api_vip.go
  models/cluster.go
  models/cluster_create_params.go
  models/ingress_vip.go
  models/ip.go
  models/v2_cluster_update_params.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/api_vip.go
  vendor/github.com/openshift/assisted-service/models/cluster.go
  vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  vendor/github.com/openshift/assisted-service/models/ingress_vip.go
  vendor/github.com/openshift/assisted-service/models/ip.go
  vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
Labels: approved, size/M, api-review, lgtm

#4555 MGMT-12318: handle conditions in HASC
  api/v1beta1/agentserviceconfig_types.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go
Labels: approved, size/L, api-review, lgtm

#4420 MGMT-12083: Create enhancement document for discovery kernel parameters
  docs/enhancements/add-kernel-parameters.md
Labels: approved, size/L, lgtm

#4569 NO-ISSUE: add logs dashboard
  dashboards/grafana-dashboard-assisted-installer-logs.yaml
Labels: approved, size/L, lgtm

#4563 MGMT-12425: Removal of problematic validation.
  api/vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  internal/host/refresh_status_preprocessor.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/host/validator.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/host_validation_id.go
Labels: approved, size/L, api-review, lgtm

#4546 MGMT-12363: Changing the message which the service sends when the right amount of dedicated control plane nodes is achieved
  internal/cluster/transition_test.go
  internal/cluster/validator.go
  internal/operators/odf/validation_test.go
Labels: approved, size/L, lgtm

#4564 MGMT-12422: Fix bm platform update failure when cluster platform different than bm/none
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/provider/common.go
Labels: approved, size/L, lgtm

#4574 NO-ISSUE: Rename misleading network utility function
  internal/cluster/cluster.go
  internal/network/machine_network_cidr.go
  internal/network/machine_network_cidr_test.go
Labels: approved, size/M, lgtm

#4585 Remove redundant boto3 dependency
  dev-requirements.txt
Labels: approved, size/XS, lgtm

#4580 MGMT-12462: Fix assisted-service swagger file
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level.go
  api/vendor/github.com/openshift/assisted-service/models/host.go
  internal/featuresupport/support_levels_list.go
  models/feature_support_level.go
  models/host.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/feature_support_level.go
  vendor/github.com/openshift/assisted-service/models/host.go
Labels: approved, size/L, api-review, lgtm

#4587 MGMT-12398: Regression fix: Move host stage to "Done" only when not in KubeAPI mode.
  internal/host/host.go
Labels: approved, size/XS, lgtm

#4571 MGMT-12423: Add debug logs for counting unsynced agents
  internal/controller/controllers/clusterdeployments_controller.go
Labels: approved, size/XS, lgtm

#4562 MGMT-12354: Migrate single VIP values to the new data structure
  internal/common/db.go
  internal/migrations/20221031103047_multiple_vips.go
  internal/migrations/20221031103047_multiple_vips_test.go
  internal/migrations/migrations.go
Labels: approved, size/L, lgtm

#4565 MGMT-12389: Create flag for per-version support of dual-stack VIPs
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level.go
  internal/featuresupport/support_levels_list.go
  models/feature_support_level.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/feature_support_level.go
Labels: approved, size/M, api-review, lgtm

#4592 MGMT-12434: Allow nightly 4.12 builds to use the converged flow
  internal/controller/controllers/bmo_utils.go
  internal/controller/controllers/bmo_utils_test.go
Labels: approved, size/M, lgtm

#4593 Remove useless getReleaseImage function
  internal/controller/controllers/clusterdeployments_controller.go
Labels: approved, size/S, lgtm

#4597 MGMT-12522 Fix unit test DB connection failure
  internal/common/common_unitest_db.go
  internal/host/hostutil/host_utils_test.go
Labels: approved, size/M, lgtm

#4541 MGMT-12053: Add support for additional kernel arguments when serving iPXE script
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
Labels: approved, size/L, lgtm

#4599 MGMT-12098 Remove legacy auto reset host
  internal/host/config.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/mock_transition.go
  internal/host/statemachine.go
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, size/L, lgtm

#4603 [cloud_hotfix_releases] MGMT-12528 - Disable network scanning for very large IPv4 subnets
  internal/host/hostcommands/free_addresses_cmd.go
  internal/host/hostcommands/free_addresses_cmd_test.go
Labels: approved, size/M, lgtm

#4575 MGMT-9915: Create utility functions to get cluster's VIPs
  internal/network/utils.go
  internal/network/utils_test.go
Labels: approved, size/L, lgtm

#4595 MGMT-12507: Remove duplicated unit tests: RegisterHost and GetNextSteps
  internal/bminventory/inventory_test.go
Labels: approved, size/L, lgtm

#4572 NO-ISSUE: add warning and info panel to log dashboard
  dashboards/grafana-dashboard-assisted-installer-logs.yaml
Labels: approved, size/M, lgtm

#4601 MGMT-12528 - Disable network scanning for very large IPv4 subnets
  internal/host/hostcommands/free_addresses_cmd.go
  internal/host/hostcommands/free_addresses_cmd_test.go
Labels: approved, size/M, lgtm

#4588 MGMT-12500: Add AI support for a DPU worker
  api/go.sum
  api/vendor/github.com/openshift/assisted-service/models/versioned_host_requirements.go
  data/default_hw_requirements.json
  deploy/podman/configmap.yml
  deploy/podman/okd-configmap.yml
  go.mod
  go.sum
  internal/controller/controllers/default_controller_hw_requirements.json
  internal/hardware/validator.go
  internal/hardware/validator_test.go
  internal/hardware/versioned-requirements.go
  internal/hardware/versioned-requirements_test.go
  internal/host/transition_test.go
  internal/network/manifests_generator.go
  models/go.sum
  models/versioned_host_requirements.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/versioned_host_requirements.go
  vendor/modules.txt
Labels: approved, size/L, api-review, lgtm

#4604 MGMT-12478: AgentClusterInstall remains in installed state when using ignitionEndpoint
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook.go
Labels: approved, size/M, lgtm

#4537 MGMT-12299: Changing the message user sees when the cluster doesn't contain the correct composition of control plane nodes and workers
  internal/cluster/transition_test.go
  internal/cluster/validator.go
  internal/operators/odf/validation_test.go
Labels: approved, size/S, lgtm

#4586 MGMT-12492: update statusRebootTimeout info message to ask the user to look at the host console.
  internal/host/common.go
Labels: approved, size/XS, lgtm

#4605 MGMT-12545: Rename "discovery kernel arguments" to "kernel arguments" in infra-env context
  api/vendor/github.com/openshift/assisted-service/models/infra_env.go
  api/vendor/github.com/openshift/assisted-service/models/infra_env_create_params.go
  api/vendor/github.com/openshift/assisted-service/models/infra_env_update_params.go
  docs/enhancements/add-kernel-parameters.md
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/migrations/20221110174000_rename_kernel_arguments.go
  internal/migrations/20221110174000_rename_kernel_arguments_test.go
  internal/migrations/migrations.go
  models/infra_env.go
  models/infra_env_create_params.go
  models/infra_env_update_params.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/infra_env.go
  vendor/github.com/openshift/assisted-service/models/infra_env_create_params.go
  vendor/github.com/openshift/assisted-service/models/infra_env_update_params.go
Labels: approved, size/L, api-review, lgtm

#4612 MGMT-12557: remove duplicated unit tests: monitored operators
  internal/bminventory/inventory_test.go
Labels: approved, size/L, lgtm

#4611 MGMT-12489: We should validate that inventory is not nil while returning from GetOrUnmarshal in installer cache.
  internal/host/common.go
  internal/host/common_test.go
  internal/host/validator.go
Labels: approved, size/S, lgtm

#4610 MGMT-12552: Day-2 agent stuck with status_info rebooting although the node is already part of the cluster
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/host/host.go
  internal/host/host_test.go
Labels: approved, size/M, lgtm

#4619 [release-ocm-2.6] MGMT-11799: change all 'go get' commands
  Dockerfile.assisted-service-debug
  hack/setup_env.sh
Labels: approved, kind/dependency-change, size/S, lgtm, bugzilla/valid-bug

#4625 MGMT-12572: Remove duplicated tests: V2UpdateCluster
  internal/bminventory/inventory_test.go
Labels: approved, size/L, lgtm

#4566 MGMT-12068: kube api support for discovery kernel arguments
  api/v1beta1/infraenv_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/agent-install.openshift.io_infraenvs.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/infraenv_types.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/zz_generated.deepcopy.go
Labels: approved, size/L, api-review, lgtm

#4620 Describe openshift_version in os_image better
  api/vendor/github.com/openshift/assisted-service/models/os_image.go
  models/os_image.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/os_image.go
Labels: approved, size/XS, api-review, lgtm

#4626 Disable converged flow by default
  cmd/main.go
  docs/hive-integration/README.md
Labels: approved, size/XS, lgtm

#4613 MGMT-8357: Support kind hub-cluster for e2e tests
  skipper.yaml
  tools/deploy_assisted_installer_configmap.py
  tools/deploy_image_service.py
  tools/deploy_inventory_service.py
  tools/deploy_ui.py
  tools/deployment_options.py
  tools/utils.py
Labels: approved, size/L, lgtm

#4621 MGMT-11266: nutanix: remove worker MachineSet too
  internal/provider/nutanix/ignition.go
Labels: approved, size/XS, lgtm

#4623 MGMT-12318: added conditions for spoke kubeconfig secret
  api/v1beta1/agentserviceconfig_types.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go
Labels: approved, size/M, api-review, lgtm

#4629 MGMT-12588: fix attach-disk failure
  deploy/operator/libvirt_disks.sh
Labels: approved, size/M, lgtm

#4634 NO-ISSUE: Explicitly finish mock controller in ignition tests
  internal/ignition/ignition_test.go
Labels: approved, size/S, lgtm

#4616 MGMT-12332: Subsystem tests for discovery kernel arguments
  api/vendor/github.com/openshift/assisted-service/models/infra_env_create_params.go
  api/vendor/github.com/openshift/assisted-service/models/infra_env_update_params.go
  models/infra_env_create_params.go
  models/infra_env_update_params.go
  restapi/embedded_spec.go
  subsystem/infra_env_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/infra_env_create_params.go
  vendor/github.com/openshift/assisted-service/models/infra_env_update_params.go
Labels: approved, size/L, api-review, lgtm

#4638 NO-ISSUE: add stage logs to grafana
  dashboards/grafana-dashboard-assisted-installer-logs.yaml
Labels: approved, size/L, lgtm

#4624 MGMT-12555: Try avoid deadlocks when updating cluster or host
  internal/bminventory/inventory.go
Labels: approved, size/M, lgtm

#4637 MGMT-11799: Change 'go get' commands
  Dockerfile.assisted-service-debug
  Dockerfile.bundle
  hack/setup_env.sh
Labels: approved, kind/dependency-change, size/S, lgtm, bugzilla/valid-bug

#4434 MGMT-11087: Replaced HPP with ODF LVMO on CNV for a single-node …
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/hostutil/test_utils.go
  internal/host/monitor.go
  internal/ignition/ignition.go
  internal/operators/api/api.go
  internal/operators/api/mock_operator_api.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/cnv/cnv_operator_test.go
  internal/operators/cnv/manifest.go
  internal/operators/lso/ls_operator.go
  internal/operators/lvm/config.go
  internal/operators/lvm/lvm_operator.go
  internal/operators/manager.go
  internal/operators/manager_test.go
  internal/operators/mock_operators_api.go
  internal/operators/odf/odf_operator.go
  subsystem/day2_cluster_test.go
  subsystem/subsystem_suite_test.go
Labels: approved, size/L, api-review, lgtm, ok-to-test

#4641 MGMT-12318: improve condition message of missing secret
  internal/controller/controllers/hypershiftagentserviceconfig_controller.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go
Labels: approved, size/S, lgtm

#4618 NO-ISSUE: Explicitly finish mock controller in cluster tests
  internal/cluster/cluster_test.go
Labels: approved, size/L, lgtm

#4628 MGMT-12500: DPU cpu arch can be aarch64 and not arm64, adding aarch64 to allowed values
  internal/common/common.go
  internal/hardware/validator.go
  internal/hardware/validator_test.go
  subsystem/cluster_test.go
Labels: approved, size/S, lgtm

#4631 NO-ISSUE: Explicitly finish mock controller in host transition tests
  internal/host/hosts_suite_test.go
  internal/host/transition_test.go
Labels: approved, size/L, lgtm

#4633 NO-ISSUE: Explicitly finish mock controller in host command tests
  internal/host/hostcommands/download_boot_artifacts_cmd_test.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/M, lgtm

#4642 MGMT-8357: change 'local' deployment method to 'minikube'
  Makefile
  tools/deployment_options.py
Labels: approved, size/S, lgtm

#4577 MGMT-12460: added deploy_hypershift_cluster script
  deploy/operator/gather.sh
  deploy/operator/hypershift/deploy_hypershift_cluster.sh
  deploy/operator/hypershift/playbooks/bmh-playbook.yaml
  deploy/operator/hypershift/playbooks/hasc-playbook.yaml
  deploy/operator/hypershift/playbooks/spoke-crs-playbook.yaml
  deploy/operator/hypershift/playbooks/templates/baremetalHost.j2
  deploy/operator/hypershift/playbooks/templates/hasc.j2
  internal/controller/controllers/agentserviceconfig_controller.go
Labels: approved, size/L, lgtm

#4632 NO-ISSUE: Explicitly finish mock controller in host tests
  internal/host/host_test.go
Labels: approved, size/L, lgtm

#4644 MGMT-12605: Remove duplicated tests: Dual-stack UpdateCluster
  internal/bminventory/inventory_test.go
Labels: approved, size/S, lgtm

#4582 MGMT-11740: WebHook configuration in HASC
  api/v1beta1/agentserviceconfig_types.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go
Labels: approved, size/L, api-review, lgtm

#4497 NO-ISSUE: In 4.12 use 4.11 LSO and legacy security context
  deploy/operator/mirror_utils.sh
  deploy/operator/setup_lso.sh
Labels: approved, size/M, lgtm, bugzilla/valid-bug

#4652 MGMT-12552: Day-2 agent stuck with status_info rebooting although the node is already part of the cluster
  internal/host/host.go
Labels: approved, size/XS, lgtm

#4648 MGMT-12592: added webhooks tests to hypershift e2e
  deploy/operator/gather.sh
  deploy/operator/hypershift/deploy_hypershift_cluster.sh
Labels: approved, size/M, api-review, lgtm

#4358 MGMT-11506: Present a more useful validation message for packet loss
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, size/L, lgtm

#4657 MGMT-12552: Add UT for day-2 agent status updates
  internal/host/host_test.go
Labels: approved, size/L, lgtm

#4647 MGMT-12332: Kube API subsystem tests for kernel arguments
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, api-review, lgtm

#4650 OKD-90: Support automated extraction of OKD RPMs
  cmd/main.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/oc/mock_release.go
  internal/oc/release.go
Labels: approved, size/L, lgtm

#4658 NO-ISSUE: log build version
  Dockerfile.assisted-service
  Dockerfile.assisted-service.ocp
  Makefile
  cmd/main.go
  internal/versions/versions.go
Labels: approved, kind/dependency-change, size/M, lgtm

#4656 MGMT-12379: PlatformType is not validated when installing SNO cluster
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validations.go
Labels: approved, size/M, api-review, lgtm

#4552 MGMT-8789: Improve UX setting PUBLIC_CONTAINER_REGISTRIES
  api/v1beta1/agentserviceconfig_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
  config/crd/bases/agent-install.openshift.io_hypershiftagentserviceconfigs.yaml
  config/crd/resources.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agentserviceconfigs.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_hypershiftagentserviceconfigs.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/zz_generated.deepcopy.go
Labels: approved, size/L, api-review, lgtm

#4671 MGMT-12686: Allow installing on FC disks
  internal/hardware/validator.go
  internal/hardware/validator_test.go
Labels: approved, size/S, lgtm

#4663 MGMT-11813: how to install HASC doc
  docs/user-guide/hypershift-agent-service-config.md
Labels: approved, size/L, lgtm

#4676 NO-ISSUE: add unauthenticatedRegistries to HASC on deploy
  deploy/operator/hypershift/deploy_hypershift_cluster.sh
  deploy/operator/hypershift/playbooks/hasc-playbook.yaml
  deploy/operator/hypershift/playbooks/templates/hasc.j2
Labels: approved, size/S, lgtm

#4668 MGMT-12678: Deprecate API and Ingress VIP (Singular)
  api/vendor/github.com/openshift/assisted-service/models/cluster.go
  api/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  api/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
  models/cluster.go
  models/cluster_create_params.go
  models/v2_cluster_update_params.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster.go
  vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
Labels: approved, size/S, api-review, lgtm

#4150 MGMT-8818: clusterdeployments: set HTTPS Ignition URL when finalizing the cluster
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/constants/files.go
  internal/host/hostutil/host_utils.go
  internal/ignition/ignition.go
Labels: approved, size/L, lgtm

#4568 MGMT-12355: API and Ingress VIPs CRUD implementation
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validations.go
  internal/network/machine_network_cidr.go
  internal/network/utils.go
  subsystem/cluster_test.go
Labels: approved, lgtm, size/XXL

#4689 Small doc addition for OLM operator plugins
  docs/dev/olm-operator-plugins.md
Labels: approved, size/S, lgtm

#4670 MGMT-12684 add envoy as sidecar to produce access log
  openshift/template.yaml
Labels: approved, size/L, lgtm

#4596 MGMT-12389: Add feature usage for dual-stack VIPs
  internal/bminventory/inventory.go
  internal/usage/consts.go
  subsystem/cluster_test.go
Labels: approved, size/M, lgtm

#4643 MGMT-12627: Add Multiple VIPs support for state machine validators
  api/vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  internal/bminventory/inventory.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/refresh_status_preprocessor.go
  internal/cluster/statemachine.go
  internal/cluster/transition_test.go
  internal/cluster/validation_id.go
  internal/cluster/validator.go
  internal/common/test_configuration.go
  internal/network/utils.go
  internal/operators/odf/validation_test.go
  models/cluster_validation_id.go
  restapi/embedded_spec.go
  subsystem/agent_based_installer_client_test.go
  subsystem/cluster_test.go
  subsystem/ipv6_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
Labels: approved, api-review, lgtm, size/XXL

#4684 MGMT-12635: Add icsp-file support for all oc commands
  cmd/agentbasedinstaller/register.go
  cmd/main.go
  internal/installercache/installercache.go
  internal/oc/release.go
  internal/oc/release_test.go
Labels: approved, size/L, lgtm

#4679 MGMT-12723: Fix log formatting in inventory.go
  internal/bminventory/inventory.go
Labels: approved, size/S, lgtm

#4665 MGMT-12616: Reject register after install
  internal/bminventory/inventory.go
  internal/host/mock_transition.go
  internal/host/statemachine.go
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, size/M, lgtm

#4692 MGMT-12666: Document Unauthenticated Registries
  docs/operator.md
Labels: approved, size/S, lgtm

#4697 Revert "MGMT-11506: Present a more useful validation message for pack…
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, size/L, lgtm

#4695 Revert "MGMT-11506: Present a more useful validation message for pack…
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, size/L, lgtm, jira/severity-critical

#4630 Remove ValidateAccessToMultiarch function
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/versions/mock_versions.go
  internal/versions/versions.go
  internal/versions/versions_test.go
Labels: approved, size/M, lgtm

#4699 MGMT-12689: Day-2 agent stuck with status_info rebooting although the node is already part of the cluster
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, size/M, lgtm, bugzilla/valid-bug
