Repository openshift/assisted-service, pull requests merged in 2022-12, with the labels that each got.

#4701 NO-ISSUE: move grafana dashboards to other repository
  Makefile
  dashboards/grafana-dashboard-assisted-installer-agent-api.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-basic-cluster-operation.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-deployment-overview.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-logs.yaml
  dashboards/grafana-dashboard-assisted-installer-ocm-operations.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-resource-utilization.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-rnd-overview.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-validations.configmap.yaml
  dashboards/grafana-dashboard-assisted-rds-postgres.configmap.yaml
Labels: approved, lgtm, size/XXL

#4192 MGMT-11265: add platform integration enhancement
  docs/enhancements/platform-integration.md
Labels: approved, size/L, lgtm

#4709 MGMT-12795: Make agent to restart on upgrade (Temporary Patch)
  internal/host/hostcommands/instruction_manager.go
Labels: approved, size/XS, lgtm

#4694 MGMT-12388: Forbid dual-stack VIPs for OpenShift pre-4.12
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validations.go
  internal/cluster/validator.go
  subsystem/cluster_test.go
  subsystem/subsystem_suite_test.go
Labels: approved, size/L, lgtm

#4666 MGMT-11536: refresh cluster after host deletion
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/crd_utils.go
  internal/controller/controllers/crd_utils_test.go
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  internal/host/host.go
  internal/host/mock_host_api.go
  subsystem/cluster_test.go
  subsystem/cluster_v2_test.go
Labels: approved, size/L, lgtm

#4704 MGMT-12423: Additional debug logs when collecting Agents from ACI
  internal/controller/controllers/clusterdeployments_controller.go
Labels: approved, size/XS, lgtm

#4691 MGMT-11386: approve day2 CSRs for an agent without BMH
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, size/L, lgtm

#4579 MGMT-10376: Adding a feature usage flag for setting UserManagedNetworking flag in a non-SNO configuration
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/usage/consts.go
  models/feature_support_level.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/feature_support_level.go
Labels: approved, size/M, api-review, lgtm

#4718 MGMT-12806: Allow registration when pending for input
  internal/host/statemachine.go
  internal/host/transition_test.go
Labels: approved, size/XS, lgtm

#4719 MGMT-12806: Allow registration when pending for input
  internal/host/statemachine.go
  internal/host/transition_test.go
Labels: approved, size/XS, lgtm

#4696 MGMT-12749: BMH: add fallback location for spoke's root CA
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/M, lgtm

#4710 MGMT-12797: Missing dual-stack VIP values in SNO cluster
  internal/bminventory/inventory.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/common.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/cluster/validations/validations.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/network/utils.go
  subsystem/cluster_test.go
Labels: approved, size/L, lgtm

#4712 MGMT-12400: enable pprof when debug mode for memory profiling
  cmd/main.go
Labels: approved, size/S, lgtm

#4570 MGMT-12423: Use pointers when collecting Agents from ACI
  internal/controller/controllers/clusterdeployments_controller.go
Labels: approved, size/S, lgtm

#4700 MGMT-12635: Add icsp-file support for all oc commands (#4684)
  cmd/agentbasedinstaller/register.go
  cmd/main.go
  internal/installercache/installercache.go
  internal/oc/release.go
  internal/oc/release_test.go
Labels: approved, size/L, lgtm

#4245 MGMT-9915: Enhancement for dual-stack VIPs
  docs/enhancements/dual-stack-vips.md
Labels: approved, size/L, lgtm

#4733 MGMT-12840: set restricted list of approvers for 2.7
  OWNERS_ALIASES
Labels: approved, size/S, lgtm

#4730 NO-ISSUE: Verify that GORM embedded structure is always part of containing structure
  internal/common/common_test.go
Labels: approved, size/M, lgtm

#4717 MGMT-11506: Present a more useful validation message for packet loss
  internal/host/transition_test.go
  internal/host/validations_test.go
  internal/host/validator.go
Labels: approved, size/L, lgtm

#4728 Move version API handlers to a separate struct
  cmd/main.go
  internal/versions/api.go
  internal/versions/api_test.go
  internal/versions/mock_versions.go
  internal/versions/versions.go
  internal/versions/versions_test.go
Labels: approved, lgtm, size/XXL

#4732 MGMT-12648: Update operator bundle channel
  Makefile
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/metadata/annotations.yaml
Labels: approved, size/XS, lgtm

#4617 NO-ISSUE: Explicitly finish mock controllers in cluster transition tests
  internal/cluster/cluster_suite_test.go
  internal/cluster/transition_test.go
Labels: approved, size/L, lgtm

#4727 Use the cluster version when extracting the ironic agent image from a release
  cmd/main.go
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
  internal/ignition/ironic.go
  internal/ignition/ironic_test.go
Labels: approved, size/L, lgtm

#4736 NO-ISSUE: Fix wrong unit test for CIDR autoallocation
  internal/cluster/cluster_test.go
Labels: approved, size/XS, lgtm

#4723 OCPBUGS-4493: do not mutate ACI post installation start
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_mutating_hook.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_mutating_hook_test.go
Labels: approved, size/M, lgtm

#4739 OKD-90: execute should throw a warning
  internal/oc/release.go
Labels: approved, size/XS, lgtm

#4737 Split the os versions handling from the release image handling
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  internal/host/hostcommands/download_boot_artifacts_cmd.go
  internal/host/hostcommands/download_boot_artifacts_cmd_test.go
  internal/host/hostcommands/instruction_manager.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/versions/api.go
  internal/versions/api_test.go
  internal/versions/mock_osimages.go
  internal/versions/mock_versions.go
  internal/versions/osimages.go
  internal/versions/osimages_test.go
  internal/versions/versions.go
  internal/versions/versions_test.go
Labels: approved, lgtm, size/XXL

#4746 Use policy/v1 for pod disruption budget
  openshift/template.yaml
Labels: approved, size/XS, lgtm

#4745 MGMT-12863: Assisted Spoke install-config does not generate icsp with multiple mirror to entries
  internal/installcfg/builder/builder.go
  internal/installcfg/builder/builder_test.go
  internal/oc/release.go
  internal/oc/release_test.go
  pkg/mirrorregistries/generator.go
  pkg/mirrorregistries/generator_test.go
Labels: approved, size/M, lgtm

#4747 MGMT-12366: Allow to use UpdateMachineCidr for multiple networks
  internal/cluster/cluster.go
  internal/cluster/common.go
  internal/cluster/common_test.go
Labels: approved, size/L, lgtm

#4459 MGMT-11970: Add a validation to check for IP collissions.
  api/vendor/github.com/openshift/assisted-service/models/cluster.go
  api/vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/mock_cluster_api.go
  internal/common/common_test.go
  internal/host/refresh_status_preprocessor.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/host/validations_test.go
  internal/host/validator.go
  models/cluster.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  subsystem/kubeapi_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster.go
  vendor/github.com/openshift/assisted-service/models/host_validation_id.go
Labels: approved, size/XL, api-review, lgtm

#4754 MGMT-9915: Prepare sample CRs for dual-stack VIPs
  docs/hive-integration/crds/agentClusterInstall-dualstack-vips-SNO.yaml
  docs/hive-integration/crds/agentClusterInstall-dualstack-vips.yaml
Labels: approved, size/M, lgtm

#4698 MGMT-12759: Reinstate assisted NMState Go binding
  Dockerfile.assisted-service
  Dockerfile.assisted-service-build
  Dockerfile.assisted-service.ocp
  Makefile
  cmd/main.go
  go.mod
  go.sum
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  pkg/staticnetworkconfig/generator.go
  pkg/staticnetworkconfig/generator_test.go
  pkg/staticnetworkconfig/mock_generator.go
  vendor/github.com/nmstate/nmstate/rust/src/go/nmstate/LICENSE
  vendor/github.com/nmstate/nmstate/rust/src/go/nmstate/Makefile
  vendor/github.com/nmstate/nmstate/rust/src/go/nmstate/nmstate.go
  vendor/golang.org/x/sync/semaphore/semaphore.go
  vendor/modules.txt
Labels: approved, kind/dependency-change, size/L, lgtm

#4756 NO-ISSUE: edit HASC enhancement doc
  docs/enhancements/ai-on-hypershift.png
  docs/enhancements/ai-on-zero-worker-hypershift-components.jpg
  docs/enhancements/ai-on-zero-worker-hypershift.md
  docs/enhancements/webhook_in_hypershift.jpg
Labels: approved, size/M, lgtm

#4729 MGMT-12169: Changing the cluster's validation message when disks size is insufficient
  internal/operators/odf/odf_operator.go
  internal/operators/odf/odf_operator_test.go
  internal/operators/odf/validation_test.go
  internal/operators/odf/validations.go
Labels: approved, size/M, lgtm

#4738 MGMT-12635: Add icsp-file support for all oc commands
  cmd/agentbasedinstaller/register.go
  cmd/main.go
  internal/installercache/installercache.go
  internal/oc/release.go
  internal/oc/release_test.go
  pkg/mirrorregistries/generator.go
Labels: approved, size/L, lgtm

#4750 OCPBUGS-1683: Allow setting machine cidr in with UserManagedNetwork set to true
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, size/M, lgtm

#4213 TELCODOCS-831: Document capabilities exclusion
  docs/user-guide/install-customization.md
Labels: approved, size/M, lgtm

#4453 NO-ISSUE: Set the correct RAM size in BMH HardwareDetails
  internal/controller/controllers/bmh_agent_controller.go
  internal/host/monitor.go
  pkg/conversions/conversions.go
Labels: approved, size/XS, lgtm

#4720 NO-ISSUE: extract client from reconcile context
  cmd/operator/main.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_storage_validation_test.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go
Labels: approved, size/L, lgtm

#4734 NO-ISSUE: use two logger instance for generic and ocm logging
  cmd/main.go
  openshift/template.yaml
  pkg/ocm/client.go
Labels: approved, size/M, lgtm

#4757 Set infra-env kernel params on preprovisioning image
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
Labels: approved, size/M, lgtm

#4594 MGMT-12471: Don't wait for console if it is disabled
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/L, lgtm

#4762 NO-ISSUE: Added ZTP workflows to hive integration README.md
  docs/hive-integration/README.md
  docs/hive-integration/ZTP_converged_flow.png
  docs/hive-integration/ZTP_flow.png
Labels: approved, size/XS, lgtm

#4771 Document the ironic agent image behavior for converged flow
  docs/hive-integration/README.md
Labels: approved, size/S, lgtm

#4740 MGMT-12849: Set image references for the release branch so that they correctly point to :ocm-2.7 instead of :latest
  Makefile
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/metadata/annotations.yaml
  deploy/operator/setup_assisted_operator.sh
Labels: approved, size/M, lgtm

#4772 MGMT-12433: remove text minimum Size 0GB in lvm
  internal/operators/lvm/config.go
  internal/operators/lvm/lvm_operator.go
  internal/operators/lvm/lvm_operator_test.go
Labels: approved, size/XS, lgtm, needs-ok-to-test

#4775 NO-ISSUE: reduce build image size
  hack/setup_env.sh
Labels: approved, size/XS, lgtm

#4755 MGMT-12870: Add missing dual-stack VIP CRUD for KubeAPI
  internal/bminventory/inventory_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/common.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, lgtm

#4645 Refactor the versions handler into a proper cache
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/common.go
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
  internal/host/hostcommands/container_image_availability_cmd.go
  internal/host/hostcommands/container_image_availability_cmd_test.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/versions/api_test.go
  internal/versions/mock_versions.go
  internal/versions/versions.go
  internal/versions/versions_test.go
Labels: approved, size/XL, lgtm

#4767 OCPBUGS-2953: Fix regex to filter images by tag and by sha
  internal/ignition/ignition.go
Labels: approved, size/XS, lgtm

#4782 MGMT-12915: Day 2 workers cannot resolve api-int.* when attempting to pull ignition
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/constants/files.go
  internal/host/hostutil/host_utils.go
  internal/ignition/ignition.go
Labels: approved, size/L, lgtm

#4768 MGMT-12886: fetch CRDs by group in HASC ctrl
  cmd/operator/main.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go
Labels: approved, size/M, lgtm

#4786 MGMT-12237: Limit upgrade agent events
  internal/events/api/event.go
  internal/events/api/mock_event.go
  internal/events/event.go
  internal/events/event_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/metrics/metricsManager.go
  internal/metrics/metricsManager_test.go
Labels: approved, size/L, lgtm

#4760 [release-ocm-2.6] MGMT-12866: Assisted Spoke install-config does not generate icsp with multiple mirror to entries
  internal/installcfg/builder/builder.go
  internal/installcfg/builder/builder_test.go
  internal/oc/release.go
  internal/oc/release_test.go
  pkg/mirrorregistries/generator.go
  pkg/mirrorregistries/generator_test.go
Labels: approved, size/L, lgtm

#4742 MGMT-12591:setting lvmo on non-SNO cluster should return bad request
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/operators/manager.go
  internal/operators/manager_test.go
Labels: approved, size/M, lgtm, ok-to-test

#4761 MGMT-12366: Automatically calculate 2nd Machine Network from 2nd VIP
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
Labels: approved, size/M, lgtm

#4787 MGMT-12445: Update host install progress response
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/controllers/agent_controller.go
  internal/host/host.go
Labels: approved, size/M, api-review, lgtm

#4801 NO-ISSUE: Add danmanor to approvers
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#4795 NO-ISSUE: Add multiarch OCP 4.12 release images
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm

#4714 NO-ISSUE: Changing the way we handle an error from 'updateNetworkParams' from returning 'nil, err' to 'cluster, err'
  internal/controller/controllers/clusterdeployments_controller.go
Labels: approved, size/XS, lgtm

#4806 MGMT-12971: remove 4.12.0.0-0 as openshift hardcoded version in host monitor loop
  internal/host/monitor.go
  internal/operators/cnv/cnv_operator.go
Labels: approved, size/S, lgtm

#4791 MGMT-12950: Disable compatible agent validation while installing
  internal/host/common.go
  internal/host/refresh_status_preprocessor.go
  internal/host/validations_test.go
Labels: approved, size/M, lgtm

#4804 MGMT-12911: Update assisted service operator docs with new icsp behavior
  deploy/operator/setup_assisted_operator.sh
  docs/operator.md
  internal/controller/controllers/agentserviceconfig_controller_test.go
  pkg/mirrorregistries/generator_test.go
Labels: approved, size/S, lgtm

#4811 MGMT-12978: Append -multi suffix to multi-arch images in SupportedVersions
  internal/versions/api.go
  internal/versions/api_test.go
Labels: approved, size/M, lgtm

#4429 NO-ISSUE: Move SaaS networking documentation to Telco Docs
  docs/user-guide/network-configuration/README.md
  docs/user-guide/network-configuration/cluster-networking.md
  docs/user-guide/network-configuration/dhcp-vip-allocation.md
  docs/user-guide/network-configuration/dual-stack.md
  docs/user-guide/network-configuration/single-stack.md
  docs/user-guide/network-configuration/static-configuration.md
  docs/user-guide/network-configuration/user-managed-networking.md
Labels: approved, size/L, lgtm

#4779 Provide the inspector URL to the ironic ignition builder
  cmd/main.go
  config/rbac/role.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  internal/controller/controllers/bmo_utils.go
  internal/controller/controllers/bmo_utils_test.go
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/ignition/ironic.go
  internal/ignition/ironic_test.go
  vendor/github.com/openshift/image-customization-controller/pkg/ignition/builder.go
  vendor/github.com/openshift/image-customization-controller/pkg/ignition/service_config.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#4778 MGMT-12755: Disallow periods in cluster name
  internal/bminventory/inventory.go
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
Labels: approved, size/M, lgtm

#4821 MGMT-13036: add emptyDir mount for filesystem cache and ephemeral-storage policy
  openshift/template.yaml
Labels: approved, size/S, lgtm

#4822 MGMT-13038: Git fails to trust git repository because of mismatch with files
  ci-images/Dockerfile.base
Labels: approved, size/XS, lgtm

#4703 MGMT-12743: adds enhancement proposal for shorter image URLs
  docs/enhancements/short-url-enhancement.md
Labels: approved, size/L, lgtm

#4774 NO-ISSUE: Pass HA mode of the cluster to network validations
  internal/cluster/validations/validations.go
Labels: approved, lgtm

#4788 MGMT-13058: validating platform type for SNO
  go.mod
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/provider/base.go
  internal/provider/common.go
  internal/provider/none/base.go
  internal/provider/none/consts.go
  internal/provider/none/ignition.go
  internal/provider/none/installConfig.go
  internal/provider/none/inventory.go
  internal/provider/registry/registry.go
  internal/provider/registry/registry_test.go
  internal/provider/vsphere/installConfig.go
  subsystem/kubeapi_test.go
  vendor/github.com/bombsimon/logrusr/v3/.gitignore
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/zz_generated.deepcopy.go
Labels: approved, size/XL, lgtm

#4832 NO-ISSUE: disable invalid nmstate test
  subsystem/kubeapi_test.go
Labels: approved, size/XS, lgtm

#4816 MGMT-11979: verify install-config manifest in subsystem
  internal/ignition/dummy.go
  subsystem/cluster_test.go
Labels: approved, size/L, lgtm

#4831 MGMT-12794: allow to edit ACI post install
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook_test.go
Labels: approved, size/S, lgtm

#4835 MGMT-13080: UMN if machine cidr not set no need to validate bootstrap
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, size/M, lgtm

#4840 Revert "MGMT-12794: allow to edit ACI post install (#4836)"
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook_test.go
Labels: approved, size/S, lgtm

#4839 Revert "MGMT-12794: allow to edit ACI post install (#4831)"
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook_test.go
Labels: approved, size/S, lgtm

#4841 MGMT-12535: Swagger changes for vip verification
  api/vendor/github.com/openshift/assisted-service/models/api_vip.go
  api/vendor/github.com/openshift/assisted-service/models/ingress_vip.go
  api/vendor/github.com/openshift/assisted-service/models/step_type.go
  api/vendor/github.com/openshift/assisted-service/models/verified_vip.go
  api/vendor/github.com/openshift/assisted-service/models/verify_vip.go
  api/vendor/github.com/openshift/assisted-service/models/verify_vips_request.go
  api/vendor/github.com/openshift/assisted-service/models/verify_vips_response.go
  api/vendor/github.com/openshift/assisted-service/models/vip_type.go
  api/vendor/github.com/openshift/assisted-service/models/vip_verification.go
  models/api_vip.go
  models/ingress_vip.go
  models/step_type.go
  models/verified_vip.go
  models/verify_vip.go
  models/verify_vips_request.go
  models/verify_vips_response.go
  models/vip_type.go
  models/vip_verification.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/api_vip.go
  vendor/github.com/openshift/assisted-service/models/ingress_vip.go
  vendor/github.com/openshift/assisted-service/models/step_type.go
  vendor/github.com/openshift/assisted-service/models/verified_vip.go
  vendor/github.com/openshift/assisted-service/models/verify_vip.go
  vendor/github.com/openshift/assisted-service/models/verify_vips_request.go
  vendor/github.com/openshift/assisted-service/models/verify_vips_response.go
  vendor/github.com/openshift/assisted-service/models/vip_type.go
  vendor/github.com/openshift/assisted-service/models/vip_verification.go
Labels: approved, size/M, api-review, lgtm

#4770 MGMT-6536: select default cidr in SNO based on default route metrics
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/common.go
  internal/common/test_configuration.go
  internal/host/validator.go
  internal/network/machine_network_cidr.go
  internal/network/utils.go
Labels: approved, size/L, lgtm
