Repository openshift/assisted-service, pull requests merged in 2022-09, with the labels that each got.

#3870 MGMT-8568: Use NMState GenerateConfiguration Go binding
  Dockerfile.assisted-service
  Dockerfile.assisted-service-build
  Dockerfile.assisted-service.ocp
  Makefile
  cmd/main.go
  go.mod
  go.sum
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  pkg/staticnetworkconfig/generator.go
  pkg/staticnetworkconfig/generator_test.go
  pkg/staticnetworkconfig/mock_generator.go
  vendor/github.com/nmstate/nmstate/rust/src/go/nmstate/LICENSE
  vendor/github.com/nmstate/nmstate/rust/src/go/nmstate/nmstate.go
  vendor/golang.org/x/sync/semaphore/semaphore.go
  vendor/modules.txt
Labels: approved, kind/dependency-change, size/L, lgtm

#3923 Fix wrong var name in "Add additionalTrustbundle in install-config"
  docs/user-guide/install-customization.md
Labels: approved, size/XS, lgtm, ok-to-test

#4332 MGMTBUGSM-482: kube-api - improve error msg for missing OS image
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, size/S, lgtm

#4311 Update discovery.ign to fix incorrect file modes
  internal/ignition/templates/discovery.ign
Labels: approved, size/XS, lgtm, ok-to-test

#4337 AGENT-325: Support setting network type from AgentClusterInstall
  cmd/agentbasedinstaller/register.go
Labels: approved, size/XS, lgtm

#4354 MGMT-11596: improve invalid tags format message
  pkg/validations/validations.go
  pkg/validations/validations_test.go
Labels: approved, size/XS, lgtm

#4349 OCPBUGSM-47740: No networkconfig needed with DHCP agent config
  cmd/agentbasedinstaller/register.go
Labels: approved, size/S, lgtm

#4362 MGMT-11563: Fix default label for release image
  internal/versions/versions.go
  internal/versions/versions_test.go
Labels: approved, size/S, lgtm

#4365 MGMT-11585: Add release and OS images for OCP 4.12
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm

#4351 MGMT-11385: Add validation that host time is in valid window with service
  api/vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  go.sum
  internal/host/hostutil/test_utils.go
  internal/host/refresh_status_preprocessor.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/host/validator.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  subsystem/day2_cluster_test.go
  subsystem/metrics_test.go
  subsystem/utils_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/host_validation_id.go
Labels: approved, size/L, api-review, lgtm

#4374 MGMT-8890: Add subsystem test for overlapping multiarch releases
  subsystem/kubeapi_test.go
Labels: approved, size/S, lgtm

#4331 NO-ISSUE: Fix condition to get kubeconfig secret name from CR
  internal/controller/controllers/agent_controller.go
Labels: approved, size/XS, lgtm

#4375 MGMT-11973: Fix vSphere platform with enabled user-managed-networking results none platform
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/M, lgtm

#4373 MGMT-11563: Explicitly mark multiarch release payloads
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
  subsystem/cluster_v2_test.go
  subsystem/subsystem_suite_test.go
  tools/handle_ocp_versions.py
Labels: approved, size/M, lgtm

#4279 MGMT-11694: Add `NoSkipInstallationDisk` and `NoSkipMissingDisk` to `isSufficientForInstall`
  internal/host/mock_transition.go
  internal/host/statemachine.go
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, size/L, lgtm

#4352 MGMT-11035: Allow noProxy wildcard for infraEnv, regardless of OCP version
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
  subsystem/cluster_test.go
  subsystem/infra_env_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, lgtm, bugzilla/valid-bug

#4363 MGMT-11936: Use NMState Go binding with CentOS8 Stream
  Dockerfile.assisted-service
  Dockerfile.assisted-service-build
  go.mod
  go.sum
  vendor/github.com/nmstate/nmstate/rust/src/go/nmstate/Makefile
  vendor/modules.txt
Labels: approved, kind/dependency-change, size/S, lgtm

#4309 MGMT-11442: Add override ISO type parameter for v2DownloadInfraEnvFiles
  client/installer/v2_download_infra_env_files_parameters.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/ignition/mock_ignition.go
  restapi/embedded_spec.go
  restapi/operations/installer/v2_download_infra_env_files_parameters.go
  restapi/operations/installer/v2_download_infra_env_files_urlbuilder.go
  swagger.yaml
Labels: approved, kind/dependency-change, size/L, api-review, lgtm

#4384 MGMT-10817: Fix install-config on vsphere platform
  internal/bminventory/inventory_test.go
  internal/installcfg/builder/builder.go
  internal/installcfg/builder/builder_test.go
  internal/installcfg/installcfg.go
  internal/provider/baremetal/base.go
  internal/provider/none/base.go
  internal/provider/none/consts.go
  internal/provider/none/ignition.go
  internal/provider/none/installConfig.go
  internal/provider/none/inventory.go
  internal/provider/registry/registry.go
  internal/provider/vsphere/installConfig.go
Labels: approved, size/L, lgtm

#4340 NO-ISSUE: Specify Hive channel explicitly for RHACM 2.5
  deploy/operator/setup_hive.sh
Labels: approved, size/XS, lgtm, bugzilla/valid-bug

#4392 MGMT-11563: Add Z-stream to multi-arch release payload
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
  subsystem/subsystem_suite_test.go
Labels: approved, size/XS, lgtm

#4387 Remove reviewers listing from PR template
  docs/pull_request_template.md
Labels: approved, size/S, lgtm

#4391 MGMT-12024: Revert "Use NMState GenerateConfiguration Go binding (#3870)"
  Dockerfile.assisted-service
  Dockerfile.assisted-service-build
  Dockerfile.assisted-service.ocp
  Makefile
  cmd/main.go
  go.mod
  go.sum
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  pkg/staticnetworkconfig/generator.go
  pkg/staticnetworkconfig/generator_test.go
  pkg/staticnetworkconfig/mock_generator.go
  vendor/github.com/nmstate/nmstate/rust/src/go/nmstate/LICENSE
  vendor/github.com/nmstate/nmstate/rust/src/go/nmstate/Makefile
  vendor/github.com/nmstate/nmstate/rust/src/go/nmstate/nmstate.go
  vendor/golang.org/x/sync/semaphore/semaphore.go
  vendor/modules.txt
Labels: approved, kind/dependency-change, size/L, lgtm

#4357 MGMT-10174: Add node ip hint manifest for sno.
  go.sum
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/network/machine_network_cidr_test.go
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
  internal/network/mock_manifests_generator.go
Labels: approved, size/L, lgtm

#4393 Remove CGO_CFLAGS in build image
  Dockerfile.assisted-service-build
Labels: approved, kind/dependency-change, size/XS, lgtm

#3239 MGMT-8987: Allow for one worker to be added when masters are schedulable
  go.mod
  go.sum
  internal/cluster/cluster_test.go
  internal/cluster/common.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/cluster/validator.go
  internal/common/common.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  vendor/github.com/krishicks/yaml-patch/LICENSE
  vendor/github.com/krishicks/yaml-patch/Makefile
  vendor/github.com/krishicks/yaml-patch/README.md
  vendor/github.com/krishicks/yaml-patch/container.go
  vendor/github.com/krishicks/yaml-patch/node.go
  vendor/github.com/krishicks/yaml-patch/operation.go
  vendor/github.com/krishicks/yaml-patch/patch.go
  vendor/github.com/krishicks/yaml-patch/pathfinder.go
  vendor/github.com/krishicks/yaml-patch/placeholder_wrapper.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#4369 NO-ISSUE: Assign default storage classes on SNO
  internal/operators/cnv/manifest.go
Labels: approved, size/XS, lgtm, ok-to-test

#4398 MGMT-12062: Remove host reclaim feature flag
  cmd/main.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, size/M, lgtm

#4388 MGMT-12006: remove redundant upgrade code
  deploy/operator/upgrade/README.md
  deploy/operator/upgrade/after_upgrade.sh
  deploy/operator/upgrade/before_upgrade.sh
  deploy/operator/upgrade/upgrade.sh
Labels: approved, size/M, lgtm

#4404 NO-ISSUE: Fix trivial log formatting issues
  internal/ignition/ignition.go
  internal/oc/release.go
Labels: approved, size/XS, lgtm

#4345 MGMT-11590: Documentation Podman deployment with TLS
  deploy/podman/README.md
  deploy/podman/configmap_tls.yml
  deploy/podman/configmap_tls_certs.yml
  deploy/podman/pod_tls.yml
Labels: approved, size/L, lgtm

#4368 MGMT-11563: Allow org-based filtering for multiarch images
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/versions/mock_versions.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  pkg/ocm/utils.go
  subsystem/authz_test.go
  subsystem/cluster_v2_test.go
  subsystem/subsystem_suite_test.go
  subsystem/utils_test.go
  subsystem/versions_test.go
  subsystem/wiremock_stubs.go
Labels: approved, size/XL, lgtm

#4318 MGMTBUGSM-537: Create an utility GetIgnitionEndpoint function
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/hostcommands/api_vip_connectivity_check_cmd.go
  internal/host/hostutil/host_utils.go
  internal/host/hostutil/host_utils_test.go
Labels: approved, size/L, lgtm, bugzilla/valid-bug

#4399 MGMT-12063: Fix update cluster UMN when platform is different from baremetal/none
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/L, lgtm, priority/critical-urgent

#4403 MGMT-12066: Fix installation failed to start when UMN is enabled
  internal/bminventory/inventory_test.go
  internal/provider/base.go
  internal/provider/none/installConfig.go
  internal/provider/vsphere/installConfig.go
Labels: approved, size/M, lgtm, priority/critical-urgent

#4406 NO-ISSUE: Remove michaellevy101 from OWNERS
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#4405 MGMT-12078: increasing disconnection timeout for bootstrap and allowing running next step command after a minute on Installing state
  internal/host/hostcommands/instruction_manager.go
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, size/M, lgtm

#4407 MGMT-12087: Replace deprecated ioutils
  cmd/agentbasedinstaller/client/main.go
  cmd/agentbasedinstaller/host_config.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/cluster/cluster_test.go
  internal/common/test_configuration.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/ignition/dummy.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/isoeditor/rhcos_test.go
  internal/metrics/suite_test.go
  internal/oc/extract.go
  internal/provider/registry/registry_test.go
  internal/spec/spec_test.go
  internal/versions/versions_test.go
  pkg/app/middleware_test.go
  pkg/auth/auth_assisted_service_mock_test.go
  pkg/auth/jwk.go
  pkg/auth/rhsso_authz_handler_test.go
  pkg/executer/executer.go
  pkg/generator/generator.go
  pkg/s3wrapper/client_test.go
  pkg/s3wrapper/filesystem_test.go
  pkg/thread/example_test.go
  subsystem/authz_test.go
  subsystem/cluster_test.go
  subsystem/image_test.go
  subsystem/infra_env_test.go
  subsystem/kubeapi_test.go
  subsystem/metrics_test.go
  subsystem/spec_test.go
  subsystem/wiremock_stubs.go
Labels: approved, size/L, lgtm

#4410 bump to 4.12.0-ec.3 images
  data/default_release_images.json
  deploy/podman/configmap.yml
  go.mod
  openshift/template.yaml
Labels: approved, size/S, lgtm

#4408 Bug 2082979: Add node ip hint manifest for sno.
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/network/machine_network_cidr_test.go
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
  internal/network/mock_manifests_generator.go
Labels: approved, size/L, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#4416 NO-ISSUE: Remove `SetPlatformValuesInDBUpdates` from `ProviderRegistry` enhancement
  docs/enhancements/add-external-providers.md
Labels: approved, size/XS, lgtm

#4386 MGMT-11753: moving CI Dockerfiles to the repo
  ci-images/Dockerfile.base
  ci-images/Dockerfile.code-generation
  ci-images/Dockerfile.lint
  ci-images/Dockerfile.subsystem
  ci-images/Dockerfile.unit-tests
Labels: approved, size/M, lgtm

#4418 Update approvers and reviewers lists
  OWNERS
  OWNERS_ALIASES
Labels: approved, size/M, lgtm

#4414 OCPBUGS-1482: Don't override schedulableMasters unnecessarily
  internal/common/common.go
  internal/common/common_test.go
Labels: approved, size/S, lgtm

#4419 NO-ISSUE: add compression handler to http server
  cmd/main.go
Labels: approved, size/XS, lgtm

#4383 MGMT-12000: LVM installation failure resolved, added thinPoolConfigur…
  internal/operators/lvm/manifest.go
  internal/operators/lvm/manifests_test.go
Labels: approved, size/XS, lgtm, ok-to-test

#4409 NO-ISSUE: Reduce assisted-service-build image size
  Dockerfile.assisted-service-build
Labels: approved, kind/dependency-change, size/S, lgtm

#4397 MGMT-8987: Update master/worker count validation message
  docs/user-guide/samples/cluster.json
  internal/cluster/transition_test.go
  internal/cluster/validator.go
  internal/operators/odf/validation_test.go
Labels: approved, size/S, lgtm

#4380 MGMT-11056: Additional stages when adding workers with k8s API
  internal/bminventory/inventory.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/host/host.go
Labels: approved, size/L, lgtm

#4430 NO-ISSUE: fix network transfer widget in grafana dashboard
  dashboards/grafana-dashboard-assisted-installer-resource-utilization.configmap.yaml
Labels: approved, size/S, lgtm

#4422 MGMT-12117: fix flaky infra-env UT
  internal/infraenv/infraenv_test.go
Labels: approved, size/S, lgtm

#4435 NO-ISSUE: Increase compatibility of hacks for different OS
  hack/update_local_image.sh
Labels: approved, size/XS, lgtm

#4436 NO-ISSUE: Add shell debug for libvirt_disks.sh
  deploy/operator/libvirt_disks.sh
Labels: approved, size/XS, lgtm

#4440 MGMT-12130: Reduce hostname length to 64 characters
  internal/bminventory/inventory_test.go
  internal/host/hostutil/host_utils.go
  internal/host/hostutil/host_utils_test.go
Labels: approved, size/S, lgtm

#4438 NO-ISSUE: Abstract how to get spoke kubeconfig from ClusterReference and add tests
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, size/L, lgtm

#4412 NO-ISSUE: Remove unused `RegisterInstalledOCPHost` and its associated transition
  internal/host/host.go
  internal/host/mock_host_api.go
  internal/host/mock_transition.go
  internal/host/statemachine.go
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, size/M, lgtm

#4382 MGMT-11739: create spoke client using specified kubeconfig
  cmd/operator/main.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go
  internal/controller/controllers/mock_spoke_client_cache.go
  internal/controller/controllers/spoke_client_cache.go
  internal/controller/controllers/spoke_client_cache_test.go
Labels: approved, size/L, api-review, lgtm

#4165 MGMT-11271: Add Nutanix Platform type
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level.go
  api/vendor/github.com/openshift/assisted-service/models/platform_type.go
  internal/bminventory/inventory_test.go
  internal/featuresupport/support_levels_list.go
  internal/installcfg/installcfg.go
  internal/provider/nutanix/base.go
  internal/provider/nutanix/base_test.go
  internal/provider/nutanix/consts.go
  internal/provider/nutanix/ignition.go
  internal/provider/nutanix/installConfig.go
  internal/provider/nutanix/inventory.go
  internal/provider/nutanix/nutanix_suite_test.go
  internal/provider/registry/registry.go
  internal/provider/registry/registry_test.go
  internal/usage/consts.go
  models/feature_support_level.go
  models/platform_type.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/feature_support_level.go
  vendor/github.com/openshift/assisted-service/models/platform_type.go
Labels: approved, size/L, api-review, lgtm

#4432 MGMT-11443: Add API to retrieve Network Manager Config Files
  internal/bminventory/inventory.go
  pkg/staticnetworkconfig/generator.go
  pkg/staticnetworkconfig/generator_test.go
  restapi/embedded_spec.go
  restapi/operations/installer/v2_download_infra_env_files_parameters.go
  subsystem/infra_env_test.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm
