Repository openshift/assisted-service, pull requests merged in 2022-04, with the labels that each got.

#3550 MGMT-9673: Ownerhsip API to authz
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/db.go
  pkg/auth/authz.go
  pkg/auth/none_authz_handler.go
  pkg/auth/rhsso_authz_handler.go
  pkg/auth/rhsso_authz_handler_test.go
Labels: approved, size/L, lgtm

#3618 [release-ocm-2.4] NO-ISSUE: Bump crypto version
  go.mod
  go.sum
Labels: approved, size/S, lgtm, bugzilla/valid-bug

#3510 MGMT-9672: align manifest authz
  internal/cluster/common.go
  internal/manifests/manifests.go
  subsystem/manifests_test.go
Labels: approved, size/L, lgtm

#3595 Bug 2069101: fail SNO deployment with SDN
  internal/bminventory/inventory.go
  subsystem/kubeapi_test.go
Labels: approved, size/M, lgtm, bugzilla/severity-low, bugzilla/valid-bug

#3621 Bug 2061317: when using nmstateconfigs ISO is re-generated for each nmstateconfig
  pkg/staticnetworkconfig/generator.go
  pkg/staticnetworkconfig/generator_test.go
Labels: approved, size/M, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#3609 MGMT-9747: adding image validation regex to steps request objects
  internal/host/hostcommands/connectivity_check_convertor.go
  models/connectivity_check_nic.go
  models/container_image_availability_request.go
  models/domain_resolution_request.go
  models/install_cmd_request.go
  models/next_step_cmd_request.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#3358 MGMT-7340: add labels to the v2 update host api
  internal/bminventory/inventory.go
  internal/common/node_labels.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/mock_host_api.go
  models/host.go
  models/host_update_params.go
  models/node_label_params.go
  restapi/embedded_spec.go
  subsystem/host_v2_test.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#3554 MGMT-9451: Move cmd commands from service to agent
  go.mod
  go.sum
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/hostcommands/api_vip_connectivity_check_cmd.go
  internal/host/hostcommands/connectivity_check_cmd.go
  internal/host/hostcommands/container_image_availability_cmd.go
  internal/host/hostcommands/container_image_availability_cmd_test.go
  internal/host/hostcommands/dhcp_allocate_cmd.go
  internal/host/hostcommands/disk_performance_cmd.go
  internal/host/hostcommands/domain_name_resolution_cmd.go
  internal/host/hostcommands/free_addresses_cmd.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/host/hostcommands/inventory_cmd.go
  internal/host/hostcommands/inventory_cmd_test.go
  internal/host/hostcommands/logs_cmd.go
  internal/host/hostcommands/logs_cmd_test.go
  internal/host/hostcommands/next_step_runner_cmd.go
  internal/host/hostcommands/next_step_runner_cmd_test.go
  internal/host/hostcommands/ntp_synchronizer_cmd.go
  internal/host/hostcommands/stop_installation_cmd.go
  internal/host/hostcommands/stop_installation_cmd_test.go
  subsystem/host_test.go
Labels: approved, size/XL, api-review, lgtm

#3622 MGMT-9673: Add HasAccessTo API to authz
  pkg/auth/auth_utils.go
  pkg/auth/authz.go
  pkg/auth/none_authz_handler.go
  pkg/auth/rhsso_authz_handler.go
  pkg/auth/rhsso_authz_handler_test.go
  subsystem/authz_test.go
Labels: approved, size/L, lgtm

#3633 MGMT-8741: Accept full name OR tag for agent version
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/M, lgtm

#3623 MGMT-9912: Handle a nil cluster_id with events that have an optional cluster_id
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/common/conversions.go
  internal/events/eventstest/events_test_utils.go
Labels: approved, size/L, lgtm

#3598 Bug 2069976: Error with oc-mirror using an old outdated unsupported oc client in AI
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, size/XS, bugzilla/severity-urgent, lgtm, bugzilla/valid-bug

#3508 NO-ISSUE: tweak unit tests to allow running PostgreSQL on k8s instead of docker
  internal/common/common_unitest_db.go
Labels: approved, size/L, lgtm

#3632 MGMT-9810: check cluster update authz in RegisterInfraEnv
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/L, lgtm

#3635 [release-ocm-2.4] Bug 2072892: Backport `pin-latest.py` script
  deploy/olm-catalog/pin-latest.py
  deploy/olm-catalog/requirements.txt
Labels: approved, size/L, api-review, lgtm, bugzilla/severity-low, bugzilla/valid-bug

#3404 MGMT-9365: assisted kube-api SNO clusters should be converted to…
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/M, lgtm

#3629 NO-ISSUE: deploy: ensure that ServiceAccount is being created
  deploy/assisted-image-service.yaml
Labels: approved, size/XS, lgtm

#3630 MGMT-9732: add user authorization to BindHost
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/L, lgtm

#3631 MGMT-9758: replace AddUserFilter with HasAccessTo API
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  pkg/auth/auth_handler_test_utils.go
Labels: approved, size/L, lgtm

#3600 MGMT-9778: align authorization for events
  cmd/main.go
  internal/cluster/cluster_test.go
  internal/cluster/installer_test.go
  internal/cluster/transition_test.go
  internal/controller/controllers/controller_event_wrapper_test.go
  internal/events/event.go
  internal/events/event_test.go
  internal/events/events_api.go
  internal/host/host_test.go
  pkg/ocm/client.go
  subsystem/events_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/XL, lgtm

#3636 MGMT-9932: Remove unused events
  docs/events.yaml
  internal/common/events/events.go
Labels: approved, size/XL, api-review, lgtm

#3643 NO-ISSUE: move grafana dashboards to events scraper
  dashboards/grafana-dashboard-assisted-elasticsearch.configmap.yaml
  dashboards/grafana-dashboard-assisted-events-scrape.configmap.yaml
Labels: approved, lgtm, size/XXL

#3652 MGMT-9970: Upgrade gorm PG driver to fix segfault
  go.mod
  go.sum
Labels: approved, size/XS, lgtm

#3638 MGMT-9934: Use compatible iPXE script format
  docs/enhancements/ipxe-host-boot.md
  docs/user-guide/boot-discovery-image-on-aws-ec2.md
  docs/user-guide/deploy-on-bare-metal.md
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
Labels: approved, size/M, lgtm

#3642 Bug-2070838: Installation on baremetal SNO failed because 2 interfaces had overlapping subnets
  internal/host/hostutil/test_utils.go
  internal/host/refresh_status_preprocessor.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/host/validator.go
  internal/network/cidr_validations.go
  internal/network/utils.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#3651 Bug 2072929: agent is stuck on pending input condition when configuring the network for a multi node/compact ipv6 spoke
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, size/M, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#3657 MGMT-5442: assisted-service should use official oc client
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, size/XS, lgtm

#3627 AGENT-34: Allow preconfiguration of bootstrap host
  internal/host/host.go
  internal/host/host_test.go
Labels: approved, size/M, lgtm

#3658 Bug 2072728: ensure secret is labelled when it is being reconciled
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/common.go
  internal/controller/controllers/infraenv_controller.go
Labels: approved, size/S, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#3663 Bug 2073413: expose API/Ingress VIPs in ACI
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/M, bugzilla/severity-urgent, api-review, lgtm, bugzilla/valid-bug

#3610 NO-ISSUE: Add additional operator user guide doc
  docs/user-guide/additional-operator-notes.md
Labels: approved, size/XS, lgtm, ok-to-test

#3675 MGMT-9945: remove identity package
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/events/event.go
  internal/identity/identity.go
  internal/identity/identity_test.go
  pkg/auth/authz.go
  pkg/auth/none_authz_handler.go
  pkg/auth/rhsso_authz_handler.go
  pkg/auth/rhsso_authz_handler_test.go
Labels: approved, size/L, lgtm

#3674 NO-ISSUE: add a separate makefile for code generation
  Makefile
  docs/dev/olm-operator-plugins.md
  docs/hive-integration/README.md
  hack/Makefile
  hack/generate.sh
Labels: approved, size/L, lgtm

#3678 MGMT-8850: Don't copy http proxy to https proxy
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  subsystem/infra_env_test.go
Labels: approved, size/M, lgtm

#3679 NO-ISSUE: Bump github.com/aws/aws-sdk-go from 1.34.28 to 1.42.53
  go.mod
  go.sum
  pkg/s3wrapper/mock_s3iface.go
Labels: approved, size/L, lgtm

#3685 Bug 2076901: `pin-latest.py` script should exclude the postgres image
  deploy/olm-catalog/pin-latest.py
Labels: approved, bugzilla/severity-unspecified, size/S, lgtm, bugzilla/valid-bug

#3605 Bug 2070949: Add support for Ignition overrides for day2 worker
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/ignition/mock_ignition.go
Labels: approved, bugzilla/severity-unspecified, size/L, lgtm, bugzilla/valid-bug

#3687 NO-ISSUE: Add a retry when fetching oc with curl
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, size/XS, lgtm

#3681 MGMT-9460: Always use the image service in inventory unit tests
  internal/bminventory/inventory_test.go
Labels: approved, size/XL, lgtm

#3673 Fix small typo in podman readme
  deploy/podman/README.md
Labels: approved, size/XS, lgtm

#3692 MGMT-9495: Remove imgexpirer
  cmd/main.go
  internal/imgexpirer/imgexpirer.go
  internal/imgexpirer/imgexpirer_test.go
Labels: approved, size/L, lgtm

#3693 MGMT-10062: Remove default service version
  internal/versions/versions.go
  internal/versions/versions_test.go
Labels: approved, size/XS, lgtm

#3696 NO-ISSUE: create build directory for generate targets
  hack/Makefile
Labels: approved, size/XS, lgtm

#3683 MGMT-9495: Remove unreachable image handling code
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
Labels: approved, size/L, lgtm

#3700 Bug 2077162: Can not provision SNOs in a disconnected environment
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, size/XS, bugzilla/severity-urgent, lgtm, bugzilla/valid-bug

#3698 Bug 2077921: Operator deployment script doesn't wait after patching the Provisioning CR
  deploy/operator/setup_assisted_operator.sh
  deploy/operator/ztp/deploy_spoke_cluster.sh
Labels: approved, bugzilla/severity-unspecified, size/S, lgtm, bugzilla/valid-bug

#3666 MGMT-9561: MGMT-9562: vsphere host API changes
  models/disk.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/S, api-review, lgtm

#3697 MGMT-7274: Add Last-Modified to file middleware
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
  pkg/auth/auth_assisted_service_mock_test.go
  pkg/filemiddleware/middleware.go
  pkg/filemiddleware/middleware_test.go
Labels: approved, size/L, lgtm

#3714 MGMT-10029: remove generate-all target
  hack/Makefile
Labels: approved, size/XS, lgtm

#3721 MGMT-9272 Automatic agent classification labels
  api/v1beta1/agentclassification_types.go
  api/v1beta1/zz_generated.deepcopy.go
  cmd/main.go
  cmd/webadmission/main.go
  config/crd/bases/agent-install.openshift.io_agentclassifications.yaml
  config/crd/kustomization.yaml
  config/crd/resources.yaml
  config/rbac/role.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agentclassifications.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  docs/enhancements/automatic-agent-classification-labels.md
  docs/hive-integration/agent-labels.md
  docs/hive-integration/crds/agentClassification.yaml
  go.mod
  go.sum
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agentclassification_controller.go
  internal/controller/controllers/agentclassification_controller_test.go
  internal/controller/controllers/agentlabel_controller.go
  internal/controller/controllers/agentlabel_controller_test.go
  pkg/validating-webhooks/agentinstall/v1beta1/agent_classification_admission_hook.go
  pkg/validating-webhooks/agentinstall/v1beta1/agent_classification_admission_hook_test.go
  subsystem/cluster_test.go
  subsystem/kubeapi_test.go
Labels: approved, api-review, lgtm, size/XXL

#3688 MGMT-9495: Cleanup unused code in s3wrapper
  cmd/main.go
  pkg/s3wrapper/client.go
  pkg/s3wrapper/client_test.go
  pkg/s3wrapper/file_cache.go
  pkg/s3wrapper/file_cache_test.go
  pkg/s3wrapper/filesystem.go
  pkg/s3wrapper/filesystem_test.go
  pkg/s3wrapper/mock_s3wrapper.go
  pkg/s3wrapper/upload_iso.go
  pkg/s3wrapper/util.go
  pkg/s3wrapper/util_test.go
Labels: approved, lgtm, size/XXL

#3722 MGMT-10142: EditClusterRole can delete objects
  pkg/auth/rhsso_authz_handler.go
  pkg/auth/rhsso_authz_handler_test.go
Labels: approved, size/S, lgtm

#3724 MGMT-9060: Update arch doc with image service info
  docs/architecture.md
Labels: approved, size/S, lgtm

#3723 MGMT-10109: return status forbidden for manipulation ops
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  pkg/auth/rhsso_authz_handler.go
  subsystem/authz_test.go
  subsystem/wiremock_stubs.go
Labels: approved, size/L, lgtm

#3726 MGMT-10163: return StatusNotFound on non-existent infra-env
  pkg/auth/rhsso_authz_handler.go
  subsystem/authz_test.go
Labels: approved, size/S, lgtm

#3690 MGMT-9227: Create deploy_capi_cluster script for CAPI CI
  deploy/operator/capi/assisted-installer-crds-playbook.yaml
  deploy/operator/capi/baremetalHost.j2
  deploy/operator/capi/deploy_capi_cluster.sh
  deploy/operator/capi/infraEnv.j2
  deploy/operator/utils.sh
Labels: approved, size/L, lgtm
