Repository openshift/assisted-service, pull requests merged in 2022-05, with the labels that each got.

#3731 NO-ISSUE: Don't use deprecated APIs
  tools/debug/s3-list-cron.yaml
Labels: approved, size/XS, lgtm

#3716 MGMT-10164: fix generate target
  Makefile
Labels: approved, size/XS, lgtm, bugzilla/valid-bug

#3735 NO-ISSUE: Use official Hypershift image in E2E test
  deploy/operator/capi/deploy_capi_cluster.sh
Labels: approved, size/XS, lgtm

#3736 MGMT-10164: sync generated code
  deploy/olm-catalog/metadata/annotations.yaml
Labels: approved, size/XS, lgtm, bugzilla/valid-bug

#3730 MGMT-10174: Add node ip hint manifest for sno
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
  internal/network/mock_manifests_generator.go
Labels: approved, size/L, lgtm

#3734 MGMT-8738: Media disconnection status doesn't updated
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/S, lgtm

#3737 NO-ISSUE - Add the ability to override image-service image when deploying the assisted-image-service
  deploy/assisted-image-service.yaml
  tools/deploy_image_service.py
Labels: approved, size/S, lgtm

#3720 MGMT-10141: On validation 'non-overlapping-subnets', canonize subnets from same interfaces
  internal/host/hostutil/test_utils.go
  internal/host/transition_test.go
  internal/network/utils.go
Labels: approved, size/M, lgtm

#3754 Bug 2069976: oc client in AI failed to resolve MCO image when working with oc-mirror
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, size/XS, bugzilla/severity-urgent, lgtm, bugzilla/valid-bug

#3762 MGMT-10225: Update BUNDLE_CHANNELS to ocm-2.6 on master
  Makefile
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/metadata/annotations.yaml
Labels: approved, size/XS, lgtm

#3756 Bug 2081779: Implementing new service-agent protocol on server side - backport
  go.mod
  go.sum
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
  internal/dns/dns.go
  internal/host/hostcommands/api_vip_connectivity_check_cmd.go
  internal/host/hostcommands/connectivity_check_cmd.go
  internal/host/hostcommands/connectivity_check_convertor.go
  internal/host/hostcommands/container_image_availability_cmd.go
  internal/host/hostcommands/container_image_availability_cmd_test.go
  internal/host/hostcommands/dhcp_allocate_cmd.go
  internal/host/hostcommands/disk_performance_cmd.go
  internal/host/hostcommands/domain_name_resolution_cmd.go
  internal/host/hostcommands/free_addresses_cmd.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/instruction_manager.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/host/hostcommands/inventory_cmd.go
  internal/host/hostcommands/inventory_cmd_test.go
  internal/host/hostcommands/logs_cmd.go
  internal/host/hostcommands/logs_cmd_test.go
  internal/host/hostcommands/next_step_runner_cmd.go
  internal/host/hostcommands/next_step_runner_cmd_test.go
  internal/host/hostcommands/ntp_synchronizer_cmd.go
  internal/host/hostcommands/reset_installation_cmd.go
  internal/host/hostcommands/reset_installation_cmd_test.go
  internal/host/hostcommands/stop_installation_cmd.go
  internal/host/hostcommands/stop_installation_cmd_test.go
  internal/host/hostutil/host_utils.go
  internal/host/hostutil/host_utils_test.go
  models/connectivity_check_nic.go
  models/container_image_availability_request.go
  models/domain_resolution_request.go
  models/install_cmd_request.go
  models/logs_gather_cmd_request.go
  models/next_step_cmd_request.go
  models/step_type.go
  pkg/validations/validations.go
  pkg/validations/validations_test.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  subsystem/host_test.go
  swagger.yaml
Labels: approved, bugzilla/severity-unspecified, api-review, lgtm, size/XXL, bugzilla/valid-bug

#3677 MGMT-9787: Add the built-in ipxe script endpoint to baremetal deploy docs
  docs/user-guide/deploy-on-bare-metal.md
Labels: approved, size/M, lgtm

#3639 AGENT-56 Client to read ZTP manifests and register cluster and infraenv
  Dockerfile.assisted-service
  Dockerfile.assisted-service.ocp
  cmd/agentbasedinstaller/agent_based_installer.go
  cmd/agentbasedinstaller/client/main.go
  docs/agent-based-installer.md
  go.mod
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  subsystem/agent_based_installer_client_test.go
  vendor/modules.txt
Labels: approved, kind/dependency-change, size/XL, lgtm

#3770 AGENT-104: Removed redundant command
  Dockerfile.assisted-service.ocp
Labels: approved, kind/dependency-change, size/XS, lgtm

#3718 MGMT-9379: Service changes to allow day 2 workers on single node
  api/vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
  internal/bminventory/inventory.go
  internal/common/common.go
  models/install_cmd_request.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
Labels: approved, size/M, api-review, lgtm

#3704 MGMT-10094: Update must gather images for the OLM operators
  data/default_must_gather_versions.json
  openshift/template.yaml
Labels: approved, size/S, lgtm

#3776 removing OLM operator must-gather from docs
  docs/operator.md
Labels: approved, size/S, lgtm

#3732 MGMT-8796: clear msg about cidr range
  internal/network/cidr_validations.go
  internal/network/machine_network_cidr.go
  internal/network/machine_network_cidr_test.go
Labels: approved, size/M, lgtm

#3767 MGMT-9574: Improve error message when updating static IP
  pkg/staticnetworkconfig/generator.go
  subsystem/infra_env_test.go
Labels: approved, size/S, lgtm

#3733 NO-ISSUE: Remove unused subsystem client agentBMClient2
  subsystem/subsystem_suite_test.go
Labels: approved, size/XS, lgtm

#3781 MGMT-9180 - Fix bad SNO OVN/SDN doc example CR
  docs/user-guide/network-configuration.md
Labels: approved, size/XS, lgtm

#3729 MGMT-10160: remove cache for subscription access review
  pkg/auth/rhsso_authz_handler.go
  pkg/auth/rhsso_authz_handler_test.go
Labels: approved, size/M, lgtm

#3787 Bug 2083312: On validation 'non-overlapping-subnets', canonize subnets from same interfaces
  internal/host/hostutil/test_utils.go
  internal/host/transition_test.go
  internal/network/utils.go
Labels: approved, size/M, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#3779 MGMT-9452: Remove "command" from get next step api
  api/vendor/github.com/openshift/assisted-service/models/step.go
  internal/host/hostcommands/api_vip_connectivity_check_cmd.go
  internal/host/hostcommands/connectivity_check_cmd.go
  internal/host/hostcommands/container_image_availability_cmd.go
  internal/host/hostcommands/dhcp_allocate_cmd.go
  internal/host/hostcommands/disk_performance_cmd.go
  internal/host/hostcommands/domain_name_resolution_cmd.go
  internal/host/hostcommands/free_addresses_cmd.go
  internal/host/hostcommands/instruction_manager.go
  internal/host/hostcommands/inventory_cmd.go
  internal/host/hostcommands/logs_cmd.go
  internal/host/hostcommands/ntp_synchronizer_cmd.go
  internal/host/hostcommands/stop_installation_cmd.go
  models/step.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/step.go
Labels: approved, size/M, api-review, lgtm

#3778 MGMT-10237: Add events and cluster metadata to cluster logs
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/mock_cluster_api.go
  subsystem/cluster_test.go
Labels: approved, size/L, lgtm

#3794 [release-ocm-2.5] Bug 2082979: Revert "MGMT-10174: Add node ip hint manifest for sno. We want to be …
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
  internal/network/mock_manifests_generator.go
Labels: approved, size/L, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#3769 MGMT-9379: Do not pass "HA mode" parameter for worker nodes.
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/S, lgtm

#3745 MGMT-8738: media disconnected flip again by the state machine
  api/vendor/github.com/openshift/assisted-service/models/host.go
  api/vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  docs/events.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/events/events.go
  internal/host/common.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/mock_host_api.go
  internal/host/pool_host_statemachine.go
  internal/host/refresh_status_preprocessor.go
  internal/host/statemachine.go
  internal/host/transition.go
  internal/host/validation_id.go
  internal/host/validator.go
  models/host.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/host.go
  vendor/github.com/openshift/assisted-service/models/host_validation_id.go
Labels: approved, size/XL, api-review, lgtm

#3789 Bug 2083075: Allow cluster name to start with number
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
Labels: approved, size/S, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#3801 Bug 2084612: Add a retry in setup lso
  deploy/operator/setup_lso.sh
  deploy/operator/utils.sh
Labels: approved, size/M, lgtm, bugzilla/severity-low, bugzilla/valid-bug

#3786 MGMT-10261: For call GetClusterByKubeKey don't bring hosts
  internal/bminventory/inventory.go
  internal/bminventory/mock_installer_internal.go
  internal/cluster/cluster.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/mock_host_api.go
Labels: approved, size/XL, lgtm

#3808 NO-ISSUE: Log stack trace when failing to recover
  internal/bminventory/inventory.go
Labels: approved, size/S, lgtm

#3705 Bug 2078531: Expose ipxe boot artifacts via HTTP
  api/v1beta1/agentserviceconfig_types.go
  cmd/main.go
  config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
  config/crd/resources.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  config/rbac/ocp/role.yaml
  config/rbac/role.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agentserviceconfigs.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  internal/imageservice/url_test.go
  internal/imageservice/urls.go
  pkg/app/middleware.go
  pkg/app/middleware_test.go
  vendor/github.com/openshift/assisted-image-service/LICENSE
  vendor/github.com/openshift/assisted-image-service/pkg/servers/servers.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go
  vendor/modules.txt
Labels: approved, api-review, lgtm, size/XXL, bugzilla/valid-bug, bugzilla/severity-medium

#3803 NO-ISSUE: Add .spec.[]osImages.rootFSUrl to example and docs
  docs/hive-integration/kube-api-select-ocp-versions.md
Labels: approved, size/XS, lgtm, ok-to-test

#3802 MGMT-9682: fix default disk size requirement
  client/installer/v2_get_preflight_requirements_parameters.go
  data/default_hw_requirements.json
  deploy/podman/configmap.yml
  deploy/podman/okd-configmap.yml
  docs/dev/hardware-requirements.md
  internal/hardware/validator_test.go
  internal/hardware/versioned-requirements_test.go
  internal/host/transition_test.go
  restapi/embedded_spec.go
  restapi/operations/installer/v2_get_preflight_requirements_parameters.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#3795 Revert "MGMT-10174: Add node ip hint manifest for sno. (#3730)"
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
  internal/network/mock_manifests_generator.go
Labels: approved, size/L, lgtm

#3812 MGMT-9430: Remove v1Flag from V2ImportClusterInternal
  internal/bminventory/inventory.go
  internal/bminventory/inventory_v2_handlers.go
  internal/bminventory/mock_installer_internal.go
  internal/common/common.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, size/S, lgtm

#2861 MGMT-9259: Enhance the schedulable masters feature
  api/vendor/github.com/openshift/assisted-service/models/cluster.go
  api/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  api/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/progress_test.go
  internal/cluster/transition_test.go
  internal/common/common.go
  internal/operators/odf/validation_test.go
  internal/provider/baremetal/consts.go
  internal/provider/baremetal/inventory.go
  internal/provider/base.go
  internal/provider/mock_base_provider.go
  internal/provider/ovirt/inventory.go
  internal/provider/registry/mock_providerregistry.go
  internal/provider/registry/registry.go
  internal/provider/registry/registry_test.go
  internal/provider/vsphere/inventory.go
  models/cluster.go
  models/cluster_create_params.go
  models/v2_cluster_update_params.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster.go
  vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
Labels: approved, kind/dependency-change, api-review, lgtm, size/XXL, ok-to-test

#3813 MGMT-9315: Create inventory cache during refresh status preprocessing, to avoid unnecessary inventory unmarshalling
  internal/host/host.go
  internal/host/monitor.go
  internal/host/validator.go
Labels: approved, size/M, lgtm

#3796 MGMT-10263: Do not call refresh status from bm-inventory if called from Kube API
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/network/utils.go
  internal/network/utils_test.go
Labels: approved, size/XL, lgtm

#3821 MGMT-10347: Disallow capital letters from hostnames
  pkg/validations/validations.go
  pkg/validations/validations_test.go
Labels: approved, size/M, lgtm

#3825 MGMT-8376: Inline notification for SNO text fix
  internal/cluster/transition_test.go
  internal/cluster/validator.go
Labels: approved, size/S, lgtm

#3804 MGMT-10275: When getting release image, let a single thread query it, and other threads wait for it
  internal/common/common.go
  internal/common/expiring_cache.go
  internal/connectivity/validator.go
  internal/host/hostcommands/connectivity_check_cmd.go
  internal/host/hostcommands/connectivity_check_cmd_test.go
  internal/oc/release.go
  internal/oc/release_test.go
Labels: approved, size/L, lgtm

#3828 NO-ISSUE: increase memory requests and limits, and parametrize them
  openshift/template.yaml
Labels: approved, size/S, lgtm

#3744 MGMT-10196: feature enablement enhancement doc
  docs/enhancements/saas-per-organization-feature-access.md
Labels: approved, size/M, lgtm

#3797 MGMT-10264: In GetClusterInternal, do not bring hosts also from db unless requested explicitly
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/hardware/validator.go
  internal/host/host.go
  internal/host/hostcommands/dhcp_allocate_cmd.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/instruction_manager.go
  internal/host/hostcommands/instruction_manager_test.go
Labels: approved, size/M, lgtm

#3806 MGMT-9574: Improve error message when updating static network
  pkg/staticnetworkconfig/generator.go
Labels: approved, size/S, lgtm

#3831 MGMT-10179: transient day2 misleading validation message
  internal/host/validator.go
Labels: approved, size/XS, lgtm

#3826 Bug 2076333: Add clusterDeploymentRef as label to the Agent
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, size/M, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#3773 MGMT-10253: Use a modern ignition version for our machine config manifests
  internal/network/manifests_generator.go
Labels: approved, size/S, lgtm

#3829 NO-ISSUE: fix and tweak grafana dashboard about resource usage
  dashboards/grafana-dashboard-assisted-installer-resource-utilization.configmap.yaml
Labels: approved, size/XL, lgtm

#3847 Revert "MGMT-9259: Enhance the schedulable masters feature (#2861)"
  api/vendor/github.com/openshift/assisted-service/models/cluster.go
  api/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  api/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/progress_test.go
  internal/cluster/transition_test.go
  internal/common/common.go
  internal/operators/odf/validation_test.go
  internal/provider/baremetal/consts.go
  internal/provider/baremetal/inventory.go
  internal/provider/base.go
  internal/provider/mock_base_provider.go
  internal/provider/ovirt/inventory.go
  internal/provider/registry/mock_providerregistry.go
  internal/provider/registry/registry.go
  internal/provider/registry/registry_test.go
  internal/provider/vsphere/inventory.go
  models/cluster.go
  models/cluster_create_params.go
  models/v2_cluster_update_params.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster.go
  vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
Labels: approved, api-review, lgtm, size/XXL

#3832 MGMT-10494 Make sure that SNO is considered when auto approving CSRs
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/common.go
Labels: approved, size/L, lgtm

#3835 NO-ISSUE: add 'generate-bundle' to the 'generate' target
  hack/Makefile
Labels: approved, size/XS, lgtm

#3852 NO-ISSUE: improve readability for memory limits and requests
  openshift/template.yaml
Labels: approved, size/XS, lgtm

#3851 MGMT-10535: Set inventory+labels after inventory reported
  internal/controller/controllers/agent_controller.go
Labels: approved, size/S, lgtm

#3843 Bug 2089337: Fix the retry function to actually retry
  deploy/operator/utils.sh
Labels: approved, size/S, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#3853 MGMT-10493: fix gathering logs in ZTP flow
  deploy/operator/gather.sh
Labels: approved, size/S, lgtm

#3854 NO-ISSUE: skip vendor dirs generated files
  .gitattributes
Labels: approved, size/XS, api-review, lgtm

#3859 MGMT-10548: internal/network: fix NewConfig to avoid throwing errors
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
Labels: approved, size/M, lgtm

#3838 MGMT-10305: fix disconnect validation on bootstrap
  internal/host/common.go
  internal/host/host.go
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, size/M, lgtm

#3855 MGMT-10473: Add interface type to Interface API
  api/vendor/github.com/openshift/assisted-service/models/interface.go
  models/interface.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/interface.go
Labels: approved, size/XS, api-review, lgtm

#3841 Bug-2084410: Deploying OCP 4.8 on RHCOS with assisted-installer Failing validation blocks deployment with Insufficient error message
  internal/common/test_configuration.go
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, size/L, lgtm

#3842 MGMT-10003: save-partlabel and save-partindex coreos-installer args are not honored because the partition is formatted previously
  api/vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
  go.sum
  internal/host/conditions.go
  internal/host/host_test.go
  internal/host/hostcommands/disk_performance_cmd.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostutil/host_utils.go
  internal/host/transition_test.go
  models/install_cmd_request.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
Labels: approved, size/L, api-review, lgtm

#3858 Revert "MGMT-9259: Enhance the schedulable masters feature (#2861)"
  api/vendor/github.com/openshift/assisted-service/models/cluster.go
  api/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  api/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/progress_test.go
  internal/cluster/transition_test.go
  internal/common/common.go
  internal/operators/odf/validation_test.go
  internal/provider/baremetal/consts.go
  internal/provider/baremetal/inventory.go
  internal/provider/base.go
  internal/provider/mock_base_provider.go
  internal/provider/ovirt/inventory.go
  internal/provider/registry/mock_providerregistry.go
  internal/provider/registry/registry.go
  internal/provider/registry/registry_test.go
  internal/provider/vsphere/inventory.go
  models/cluster.go
  models/cluster_create_params.go
  models/v2_cluster_update_params.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster.go
  vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
Labels: approved, api-review, lgtm, size/XXL

#3861 MGMT-10004: Add UT for PreprovisioningImage controller
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
Labels: approved, size/L, lgtm

#3848 NO-ISSUE: Retry and redirect all curl actions
  hack/setup_env.sh
Labels: approved, size/XS, lgtm

#3839 AGENT-205: Fix OCP image build
  Dockerfile.assisted-service.ocp
Labels: approved, kind/dependency-change, size/XS, lgtm

#3727 MGMT-10197: Adds ENABLE_ORG_BASED_FEATURE_GATES
  Makefile
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/common.go
  openshift/template.yaml
  pkg/auth/auth_handler_test_utils.go
  pkg/auth/authenticator.go
  pkg/auth/authz.go
  pkg/auth/authz_utils.go
  pkg/auth/local_authenticator.go
  pkg/auth/none_authenticator.go
  pkg/auth/none_authz_handler.go
  pkg/auth/rhsso_authenticator.go
  pkg/auth/rhsso_authz_handler.go
  pkg/ocm/authorization.go
  pkg/ocm/utils.go
  skipper.env
  subsystem/authz_test.go
  subsystem/subsystem_suite_test.go
  subsystem/wiremock_stubs.go
  tools/deploy_assisted_installer_configmap.py
Labels: approved, size/XL, lgtm

#3774 deploy/podman: update OKD images
  data/default_okd_os_images.json
  data/default_okd_release_images.json
  deploy/podman/okd-configmap.yml
Labels: approved, size/S, lgtm

#3868 MGMT-10375: Get the ironic image from the release image for the arch
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
  internal/oc/mock_release.go
  internal/oc/release.go
Labels: approved, size/M, lgtm

#3872 MGMT-10587: Revise wording for the message of 'non-overlapping-subnets' validation
  internal/host/transition_test.go
  internal/host/validator.go
  internal/network/cidr_validations.go
  internal/network/utils.go
Labels: approved, size/M, lgtm

#3775 MGMT-8202: recalc suggested roles on host/operator changes
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/mock_cluster_api.go
  internal/host/host_test.go
  internal/host/monitor.go
  subsystem/cluster_test.go
Labels: approved, size/L, api-review, lgtm

#3873 MGMT-10281: Add documentation for the converged flow
  docs/hive-integration/README.md
  docs/hive-integration/baremetal-agent-controller.md
Labels: approved, size/M, lgtm

#3878 MGMT-10633: BMAC should disable the BMH AutomatedCleaningMode in the converged flow as well
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  internal/controller/controllers/preprovisioningimage_controller.go
Labels: approved, size/M, lgtm

#3876 MGMT-10631: remove Python dependencies auto bump
  .github/dependabot.yml
Labels: approved, size/S, lgtm
