Repository openshift/assisted-service, pull requests merged in 2022-02, with the labels that each got.

#3241 Bug 2048981: Add default value to default_release_images.json
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_release_images.json
  onprem-environment
  openshift/template.yaml
Labels: approved, bugzilla/severity-unspecified, size/S, lgtm, bugzilla/valid-bug

#3248 MGMT-9096: Add temporary solution to install baremetal arm on 4.10
  internal/bminventory/inventory.go
  internal/ignition/ignition.go
Labels: approved, size/S, lgtm

#3230 Bug 2049034: Simplify IPv6 Network Manager configuration
  internal/common/common.go
  internal/ignition/ignition.go
Labels: approved, size/M, bugzilla/severity-urgent, lgtm, bugzilla/valid-bug

#3276 MGMT-7709: optional openshift_version in infraenv
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/controller/controllers/infraenv_controller.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  models/infra_env_create_params.go
  restapi/embedded_spec.go
  subsystem/day2_cluster_test.go
  subsystem/host_v2_test.go
  subsystem/infra_env_test.go
  swagger.yaml
Labels: approved, size/M, api-review, lgtm

#3279 Bug 2049874: Proxy support in ACI
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  api/hiveextension/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#3262 MGMT-8823: Document REST-API V2 Day2 flows
  docs/user-guide/rest-api-day2.md
  docs/user-guide/rest-api-getting-started.md
Labels: approved, size/L, lgtm

#3263 MGMT-8524: support day2 cpu arm arc
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  subsystem/day2_cluster_test.go
Labels: approved, size/M, lgtm

#3281 MGMT-9077: refresh cluster after host unbound
  internal/bminventory/inventory.go
  subsystem/cluster_v2_test.go
Labels: approved, size/S, lgtm

#3289 MGMT-9069: Report unit tests code coverage
  .codecov.yml
  Makefile
  hack/publish-codecov.sh
Labels: approved, size/M, lgtm, ok-to-test

#3295 NO-ISSUE: fix ut inconsistency
  go.mod
  go.sum
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/logs_cmd_test.go
Labels: approved, size/M, lgtm

#3296 Update prometheus/client_golang package
  go.mod
  go.sum
Labels: approved, size/M, lgtm

#3278 BUG 1969933: Improve image_status_updated event message
  internal/host/host.go
  internal/host/host_test.go
Labels: approved, size/S, lgtm, bugzilla/severity-low, bugzilla/valid-bug

#3277 MGMT-9128: Remove V1 GetFreeAddresses (GET)
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  pkg/auth/authz_handler_test.go
  subsystem/host_test.go
Labels: approved, size/L, lgtm

#3298 MGMT-8744: Change image URL auth type log from warning to info
  internal/bminventory/inventory_v2_handlers.go
Labels: approved, size/XS, lgtm

#3180 MGMT-8046: BMAC should not create BMHs on the spoke cluster if it sees that platform==none
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/M, lgtm

#3293 MGMT-9114: Remove V1 operationId GetClusterInstallConfig, UpdateCluster
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/error_utils.go
Labels: approved, size/S, lgtm

#3294 MGMT-9113: Remove V1 GetCredentials, DownloadClusterKubeconfig
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  subsystem/authz_test.go
  subsystem/cluster_test.go
Labels: approved, size/L, lgtm

#3310 NO-ISSUE: Don't wait for CI to update coverage
  .codecov.yml
Labels: approved, size/XS, lgtm, ok-to-test

#3311 MGMT-8853: Prevents machine networks conflict errors
  internal/bminventory/inventory.go
  internal/cluster/common.go
Labels: approved, size/S, lgtm

#3316 OCPBUGSM-35526: Failed validation: Machine network CIDR : invalid CIDR address
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/network/cidr_validations.go
Labels: approved, size/M, lgtm

#3317 MGMT-9109: convert update role to v2 in subsystem
  subsystem/cluster_test.go
  subsystem/ipv6_test.go
Labels: approved, size/XL, lgtm

#3313 MGMT-9116: Remove V1 operationId CreateClusterManifest, DeleteClusterManifest
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
  internal/operators/manager.go
  internal/operators/manager_test.go
  subsystem/cluster_test.go
  subsystem/manifests_test.go
Labels: approved, size/M, lgtm

#3315 MGMT-9117: Remove V1 operationId DownloadClusterManifest, ListClusterManifests
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
  subsystem/cluster_test.go
  subsystem/manifests_test.go
Labels: approved, size/M, lgtm

#3305 MGMT-9129: Remove V1 operationId ListEvents
  internal/controller/controllers/controller_event_wrapper.go
  internal/events/api/event.go
  internal/events/api/mock_event.go
  internal/events/event.go
  internal/events/events_api.go
  subsystem/image_test.go
Labels: approved, size/M, lgtm

#3318 MGMTBUGSM-85: Change occurances of "API VIP connectivity" to "Ignition downloadable"
  internal/host/refresh_status_preprocessor.go
  internal/host/validator.go
  models/api_vip_connectivity_response.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/S, api-review, lgtm

#3319 MGMT-8447: Remove template image upload code
  cmd/main.go
  pkg/app/middleware.go
  pkg/app/middleware_test.go
Labels: approved, size/L, lgtm

#3297 NO-ISSUE: Add OKD support
  Makefile
  data/default_okd_os_images.json
  data/default_okd_release_images.json
  deploy/podman/README.md
  deploy/podman/okd-configmap.yml
  hack/generate.sh
  internal/ignition/ignition.go
Labels: approved, size/L, lgtm

#3322 MGMT-9233: disk validation fails for day2 hosts
  internal/bminventory/inventory.go
  internal/host/validations_test.go
  internal/host/validator.go
  subsystem/day2_cluster_test.go
Labels: approved, size/M, lgtm

#3328 MGMT-9109: separate clusterID and infraenvID in register host utils
  subsystem/ams_subscriptions_test.go
  subsystem/authz_test.go
  subsystem/cluster_test.go
  subsystem/manifests_test.go
  subsystem/metrics_test.go
  subsystem/operators_test.go
  subsystem/utils_test.go
Labels: approved, size/M, lgtm

#3341 Fix disk encryption role error in day2
  internal/bminventory/inventory.go
  internal/host/validations_test.go
  internal/host/validator.go
  subsystem/day2_cluster_test.go
Labels: approved, size/M, lgtm

#3290 MGMT-8380: Stop setting custom manifest feature flag for OLM operators
  internal/operators/manager.go
  internal/operators/manager_test.go
Labels: approved, size/M, lgtm

#3338 MGMT-9233: set MachineConfigPoolName for day2
  internal/bminventory/inventory.go
  subsystem/day2_cluster_test.go
Labels: approved, size/XS, lgtm, ok-to-test

#3335 MGMT-8582: Leader elector based on lease lock
  pkg/leader/leaderelector.go
  subsystem/leader_test.go
Labels: approved, size/L, lgtm, ok-to-test

#3312 NO-ISSUE: updates docs for running with podman
  deploy/podman/README.md
Labels: approved, size/S, lgtm

#3356 NO-ISSUE: OKD: expand /var if its less than 6GB
  internal/ignition/ignition.go
Labels: approved, size/XS, lgtm

#3331 MGMT-8447: Remove assisted-service-iso APIs and implementation
  client/assisted_install_client.go
  client/assisted_service_iso/assisted_service_iso_client.go
  client/assisted_service_iso/create_i_s_o_and_upload_to_s3_parameters.go
  client/assisted_service_iso/create_i_s_o_and_upload_to_s3_responses.go
  client/assisted_service_iso/download_i_s_o_parameters.go
  client/assisted_service_iso/download_i_s_o_responses.go
  client/assisted_service_iso/get_presigned_for_assisted_service_i_s_o_parameters.go
  client/assisted_service_iso/get_presigned_for_assisted_service_i_s_o_responses.go
  cmd/main.go
  docs/README.md
  docs/installer-live-iso.md
  internal/assistedserviceiso/assistedserviceiso_api.go
  internal/assistedserviceiso/assistedserviceiso_api_test.go
  models/assisted_service_iso_create_params.go
  pkg/auth/auth_assisted_service_mock_test.go
  pkg/auth/authz_handler_test.go
  pkg/auth/rhsso_authenticator_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/assisted_service_iso/create_i_s_o_and_upload_to_s3.go
  restapi/operations/assisted_service_iso/create_i_s_o_and_upload_to_s3_parameters.go
  restapi/operations/assisted_service_iso/create_i_s_o_and_upload_to_s3_responses.go
  restapi/operations/assisted_service_iso/create_i_s_o_and_upload_to_s3_urlbuilder.go
  restapi/operations/assisted_service_iso/download_i_s_o.go
  restapi/operations/assisted_service_iso/download_i_s_o_parameters.go
  restapi/operations/assisted_service_iso/download_i_s_o_responses.go
  restapi/operations/assisted_service_iso/download_i_s_o_urlbuilder.go
  restapi/operations/assisted_service_iso/get_presigned_for_assisted_service_i_s_o.go
  restapi/operations/assisted_service_iso/get_presigned_for_assisted_service_i_s_o_parameters.go
  restapi/operations/assisted_service_iso/get_presigned_for_assisted_service_i_s_o_responses.go
  restapi/operations/assisted_service_iso/get_presigned_for_assisted_service_i_s_o_urlbuilder.go
  subsystem/image_test.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL

#3349 NO-ISSUE: Guess compression tool used and improve scripts
  docs/user-guide/deploy-on-bare-metal.md
Labels: approved, size/S, lgtm

#3362 NO-ISSUE: Add @vrutkovs to OWNERS
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#3343 MGMT-9120: operationId Remove V1 InstallHosts, ResetCluster
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  subsystem/cluster_test.go
Labels: approved, size/L, lgtm

#3366 MGMT-9134: convert image_test to v2
  subsystem/image_test.go
Labels: approved, size/M, lgtm

#3364 MGMT-9131: Remove V1 GetClusterHostRequirements, GetPreflightRequirements, ListManagedDomains, ListComponentVersions, ListSupportedOpenshiftVersions
  docs/user-guide/rest-api-v1-v2-transition-guide.md
  internal/bminventory/inventory.go
  internal/domains/managed_domains.go
  internal/domains/managed_domains_test.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  pkg/auth/authz_handler_test.go
  subsystem/cluster_test.go
  subsystem/image_test.go
  subsystem/subsystem_suite_test.go
  subsystem/versions_test.go
Labels: approved, size/L, lgtm

#3365 MGMTBUGSM-98: Prevent nil pointer error when cluster ID is nil.
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, size/M, lgtm

#3367 MGMT-9134: convert update hostname to v2 in subsystem
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  subsystem/cluster_test.go
Labels: approved, size/M, lgtm

#3361 NO-ISSUE: validate api/api-int when ENABLE_SINGLE_NODE_DNSMASQ is not set
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/host/validator.go
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
  internal/network/mock_manifests_generator.go
Labels: approved, size/L, lgtm

#3371 MGMT-9122: Remove DisableHost from subsystem
  subsystem/cluster_test.go
  subsystem/host_test.go
  subsystem/metrics_test.go
Labels: approved, size/L, lgtm

#3373 NO-ISSUE: remove all Jenkins jobs
  Jenkinsfile
  Makefile
Labels: approved, size/L, lgtm

#3344 MGMT-9223: Automatic agent inventory labels
  docs/hive-integration/agent-labels.md
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, size/M, lgtm

#3381 MGMT-9225: Change the format if field StaticNetworkConfig in infra-env to JSON
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/migrations/20220221193600_change_static_config_format.go
  internal/migrations/20220221193600_change_static_config_format_test.go
  internal/migrations/migrations.go
  pkg/staticnetworkconfig/generator.go
  pkg/staticnetworkconfig/generator_test.go
  pkg/staticnetworkconfig/mock_generator.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, lgtm

#3380 NO-ISSUE: Set release and os images by a given version
  Makefile
  skipper.env
Labels: approved, size/S, lgtm

#3386 MGMT-9185: clean openshift-version object in swagger
  internal/common/test_configuration.go
  internal/host/hostcommands/container_image_availability_cmd_test.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  models/openshift_version.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#3382 MGMT-9125: Remove V1 operationIds UploadHostLogs and DownloadHostLogs
  docs/user-guide/rest-api-v1-v2-transition-guide.md
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  subsystem/cluster_test.go
Labels: approved, size/L, lgtm

#3385 MGMT-9356: Add go mod to models
  Dockerfile.assisted-service
  go.mod
  go.sum
  hack/generate.sh
  models/go.mod
  models/go.sum
Labels: approved, kind/dependency-change, size/L, lgtm

#3320 MGMT-8447: Remove GenerateClusterISO API
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  subsystem/cluster_test.go
  subsystem/image_test.go
Labels: approved, lgtm, size/XXL, ok-to-test

#3398 NO-ISSUE: Corrected indentation in example.
  docs/hive-integration/kube-api-getting-started.md
Labels: approved, size/XS, lgtm

#3325 MGMT-9132: Remove V1 operationId RegisterAddHostsCluster
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  subsystem/day2_cluster_test.go
  subsystem/metrics_test.go
Labels: approved, size/L, lgtm

#3391 MGMT-9118: Remove V1 UploadClusterIngressCert, CompleteInstallation
  docs/user-guide/rest-api-v1-v2-transition-guide.md
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  subsystem/authz_test.go
  subsystem/cluster_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, lgtm

#3399 MGMT-9393: Close file before passing it to nmstatectl
  pkg/staticnetworkconfig/generator.go
Labels: approved, size/XS, lgtm

#3370 MGMT-9111: Remove V1 operationId GetCluster, DeregisterCluster
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  subsystem/ams_subscriptions_test.go
  subsystem/authz_test.go
  subsystem/cluster_test.go
  subsystem/day2_cluster_test.go
  subsystem/ipv6_test.go
  subsystem/manifests_test.go
  subsystem/metrics_test.go
  subsystem/operators_test.go
  subsystem/utils_test.go
Labels: approved, size/L, lgtm

#3387 MGMT-9122: remove v1 EnableHost DisableHost
  docs/events.yaml
  internal/bminventory/inventory.go
  internal/cluster/cluster.go
  internal/cluster/common.go
  internal/cluster/common_test.go
  internal/cluster/conditions.go
  internal/cluster/transition_test.go
  internal/cluster/validator.go
  internal/common/common.go
  internal/common/common_test.go
  internal/common/db.go
  internal/common/events/events.go
  internal/controller/controllers/infraenv_controller.go
  internal/host/common.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostcommands/connectivity_check_convertor.go
  internal/host/hostcommands/install_cmd.go
  internal/host/mock_host_api.go
  internal/host/monitor_test.go
  internal/host/pool_host_statemachine.go
  internal/host/statemachine.go
  internal/host/transition.go
  internal/host/transition_test.go
  internal/host/validator.go
  internal/ignition/dummy.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/installcfg/builder/builder.go
  internal/installcfg/builder/builder_test.go
  internal/network/machine_network_cidr.go
  internal/network/machine_network_cidr_test.go
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
  internal/provider/baremetal/installConfig.go
  pkg/auth/authz_handler_test.go
  pkg/log/logcontext_test.go
  subsystem/cluster_test.go
  subsystem/kubeapi_test.go
Labels: approved, api-review, lgtm, size/XXL

#3390 MGMT-9121: Remove V1 operationId ListHosts, ResetHostValidation
  docs/user-guide/rest-api-v1-v2-transition-guide.md
  internal/bminventory/inventory.go
  subsystem/host_test.go
Labels: approved, size/M, lgtm

#3401 MGMT-9122: Remove v1 DergisterHost, GetHost
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  pkg/auth/auth_assisted_service_mock_test.go
  pkg/auth/authz_handler_test.go
Labels: approved, size/L, lgtm

#3403 MGMT-9416 - InfraEnv should not use any NMStateConfig if no selector is specified
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
Labels: approved, size/M, lgtm

#3407 MGMT-9110: v1 host related UpdateCluster to v2
  internal/bminventory/inventory_test.go
  internal/cluster/installer_test.go
  pkg/auth/authz_handler_test.go
Labels: approved, size/XL, lgtm

#3393 MGMT-9376: Remove V1 ListClusters, DownloadClusterFiles, GetClusterDefaultConfig, ResetHost
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  subsystem/authz_test.go
  subsystem/cluster_default_config_test.go
  subsystem/cluster_test.go
  subsystem/day2_cluster_test.go
  subsystem/utils_test.go
Labels: approved, size/L, lgtm

#3405 MGMT-9109: v1 RegisterCluster cleanup
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/bminventory/mock_installer_internal.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/mock_cluster_api.go
  internal/cluster/registrar.go
  internal/cluster/registrar_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, size/L, lgtm

#3412 MGMT-9126: Remove V1 GetHostIgnition, UpdateHostIgnition, DownloadHostIgnition
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/L, lgtm
