Repository openshift/assisted-service, pull requests merged in 2022-08, with the labels that each got.

#4211 deploy/podman: update okd to 4.11
  data/default_okd_os_images.json
  data/default_okd_release_images.json
  deploy/podman/okd-configmap.yml
Labels: approved, size/S, lgtm

#4212 Bug 2112817: Stop reconcile loop after changing CR inside BMAC
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, bugzilla/severity-unspecified, size/M, lgtm, bugzilla/valid-bug

#4175 MGMT-11035: Allow noProxy wildcard for infraEnv, regardless of OCP version
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
  subsystem/cluster_test.go
  subsystem/infra_env_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, lgtm

#4216 MGMT-11309: add prometheus expoter for postgresql
  openshift/template-monitoring-postgres.yaml
  openshift/template-monitoring.yaml
Labels: approved, size/L, lgtm

#4225 Bug 2099929: Print merged ignition for day2
  internal/ignition/ignition.go
Labels: approved, size/XS, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#4232 NO-ISSUE: https://red.ht/assisted doc should link to the actual hosted installer
  docs/user-guide/README.md
Labels: approved, size/XS, lgtm

#4230 MGMT-8890: Handle registries.conf without any mirrors correctly
  pkg/mirrorregistries/generator.go
  pkg/mirrorregistries/generator_test.go
Labels: approved, size/L, lgtm

#4203 Bug 2099929: Allow CI ZTP job with ignition override
  deploy/operator/ztp/add-remote-nodes-playbook.yaml
  deploy/operator/ztp/assisted-installer-crds-playbook.yaml
  deploy/operator/ztp/baremetalHost.j2
Labels: approved, size/S, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#4229 MGMT-11020: revert usage of 4.10 catalog for 4.11 ZTP jobs
  deploy/operator/setup_lso.sh
Labels: approved, size/S, lgtm

#4235 MGMT-11309: add suffix to servicemonitor name
  openshift/template-monitoring.yaml
Labels: approved, size/XS, lgtm

#4233 MGMT-11441: Allow Agent Upgrade while hosts are pending-for-input
  internal/host/hostcommands/instruction_manager.go
  internal/host/hostcommands/instruction_manager_test.go
Labels: approved, size/L, lgtm

#4209 [release-ocm-2.5] MGMT-11412: fix flaky installation of golangci-lint
  Dockerfile.assisted-service-build
  hack/setup_env.sh
Labels: approved, kind/dependency-change, size/XS, lgtm, bugzilla/valid-bug

#4234 Bug 2113954: Fix order when merging ignitions
  internal/controller/controllers/bmh_agent_controller.go
  internal/ignition/ignition_test.go
Labels: approved, bugzilla/severity-unspecified, size/L, lgtm, bugzilla/valid-bug

#4226 MGMT-11426: Assisted-service should publish event for failing validations
  docs/events.yaml
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/common/events/events.go
  internal/host/host.go
  internal/host/host_test.go
Labels: approved, size/M, api-review, lgtm

#4189 MGMT-8890: Integrate support for multiarch release images
  Dockerfile.assisted-service
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/common.go
  internal/oc/extract.go
  internal/oc/release.go
  internal/oc/release_test.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  subsystem/kubeapi_test.go
Labels: approved, kind/dependency-change, size/L, lgtm

#4231 MGMT-11444 - Wildcard DNS validation should be pending before we have DNS resolutions
  internal/common/test_configuration.go
  internal/host/validations_test.go
  internal/host/validator.go
Labels: approved, size/L, lgtm

#4237 MGMT-11447: Improve ignition downloadable (day2 API connectivity check) validation message
  api/vendor/github.com/openshift/assisted-service/models/api_vip_connectivity_response.go
  internal/host/validations_test.go
  internal/host/validator.go
  models/api_vip_connectivity_response.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/api_vip_connectivity_response.go
Labels: approved, size/M, api-review, lgtm

#4199 MGMT-10542: Allow users to skip writing over specific disks - SaaS
  api/vendor/github.com/openshift/assisted-service/models/disk_skip_formatting_params.go
  api/vendor/github.com/openshift/assisted-service/models/host.go
  api/vendor/github.com/openshift/assisted-service/models/host_update_params.go
  api/vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  docs/events.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/disk_formatting.go
  internal/common/disks_info.go
  internal/common/events/events.go
  internal/common/test_configuration.go
  internal/host/host.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostutil/host_utils.go
  internal/host/mock_host_api.go
  internal/host/refresh_status_preprocessor.go
  internal/host/transition.go
  internal/host/validation_id.go
  internal/host/validations_test.go
  internal/host/validator.go
  models/disk_skip_formatting_params.go
  models/host.go
  models/host_update_params.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  subsystem/host_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/disk_skip_formatting_params.go
  vendor/github.com/openshift/assisted-service/models/host.go
  vendor/github.com/openshift/assisted-service/models/host_update_params.go
  vendor/github.com/openshift/assisted-service/models/host_validation_id.go
Labels: approved, api-review, lgtm, size/XXL

#4208 [release-ocm-2.6] Bug 2112803: Fix image references for the release branch so that they correctly point to :ocm-2.6 instead of :latest
  Makefile
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/metadata/annotations.yaml
  deploy/operator/setup_assisted_operator.sh
Labels: approved, bugzilla/severity-unspecified, size/M, lgtm, bugzilla/valid-bug

#4243 MGMT-11521: Fix twine upload of assisted-service-client
  dev-requirements.txt
Labels: approved, size/XS, lgtm

#4219 MGMT-11416: support platform in kube-api
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  api/hiveextension/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  internal/controller/controllers/clusterdeployments_controller.go
  subsystem/cluster_test.go
  subsystem/kubeapi_test.go
  subsystem/utils_test.go
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/agentclusterinstall_types.go
Labels: approved, size/L, api-review, lgtm

#4250 NO-ISSUE: Remove duplicate PostStepReply tests
  internal/bminventory/inventory_test.go
Labels: approved, size/L, lgtm

#4249 NO-ISSUE: Vendor recent changes to api module in service
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/zz_generated.deepcopy.go
Labels: approved, size/XS, lgtm

#4135 MGMT-10789: Make sure that service can connect to KubeAPI during Day2 installation
  api/vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  cmd/main.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/mock_spoke_k8s_client_factory.go
  internal/controller/controllers/spoke_k8s_client.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostrole_test.go
  internal/host/monitor_test.go
  internal/host/refresh_status_preprocessor.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/host/validations_test.go
  internal/host/validator.go
  internal/spoke_k8s_client/mock_spoke_k8s_client.go
  internal/spoke_k8s_client/mock_spoke_k8s_client_factory.go
  internal/spoke_k8s_client/spoke_k8s_client.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/host_validation_id.go
Labels: approved, size/XL, api-review, lgtm

#4258 MGMT-10638: Document nmstate limits
  docs/hive-integration/README.md
  docs/user-guide/network-configuration/static-configuration.md
Labels: approved, size/XS, lgtm

#4117 MGMT-10739: Reclaim agents on unbind
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/agent_reclaimer.go
  internal/controller/controllers/agent_reclaimer_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/mock_host_api.go
  internal/host/transition_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm, size/XXL

#4248 MGMT-8890: Extend release image struct to store all archs
  api/vendor/github.com/openshift/assisted-service/models/release_image.go
  cmd/agentbasedinstaller/register.go
  data/default_okd_release_images.json
  data/default_release_images.json
  deploy/podman/configmap.yml
  deploy/podman/okd-configmap.yml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/common/test_configuration.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/oc/mock_release.go
  internal/oc/release.go
  internal/oc/release_test.go
  internal/oc/test_skopeo_multiarch_image_output
  internal/versions/mock_versions.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  models/release_image.go
  openshift/template.yaml
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/release_image.go
Labels: approved, size/XL, api-review, lgtm

#4130 MGMT-11156: Cluster validation, merge the print and validate methods
  Dockerfile.assisted-service-build
  internal/cluster/refresh_status_preprocessor.go
  internal/cluster/validator.go
  internal/cluster/validator_test.go
Labels: approved, kind/dependency-change, size/XL, lgtm

#4261 MGMT-11578: Update 4.11 release image to use GA version
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm

#4256 MGMT-10734: Add noop refresh transitions for reclaim states
  internal/host/statemachine.go
  internal/host/transition_test.go
Labels: approved, size/M, lgtm

#4262 NO-ISSUE: Fix incorrect network docs link in main README.md
  docs/user-guide/README.md
Labels: approved, size/XS, lgtm

#4266 MGMT-11509: Collect preprovisioningimages CR in operator gather job
  deploy/operator/gather.sh
Labels: approved, size/XS, api-review, lgtm

#4259 MGMT-11543: When there are many connectivity check packet losses, the host monitoring thread gets stuck
  internal/host/common.go
  internal/host/common_test.go
  internal/host/hostutil/test_utils.go
  internal/host/validator.go
Labels: approved, size/M, lgtm

#4268 MGMT-11618: remove OCP 4.7
  data/default_must_gather_versions.json
  data/default_os_images.json
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm

#4253 MGMT-11542: Fix connectivity check running forever on large cluster
  internal/network/connectivity_groups.go
Labels: approved, size/L, lgtm

#4247 NO-ISSUE: CI to be more graceful with ZTP log
  deploy/operator/gather.sh
Labels: approved, size/M, lgtm

#4265 Bug-2107617: Attempted 240 node cluster with MCE / Assisted-installer and ended up with 187 node cluster
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/progress_test.go
  internal/cluster/statemachine.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  subsystem/cluster_test.go
Labels: approved, size/L, lgtm

#4270 MGMT-11621: Allow subdomains in cluster name
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
Labels: approved, size/S, lgtm

#4273 MGMT-11507: remove COPY . . instruction from skipper Dockerfile
  Dockerfile.assisted-service-build
Labels: approved, kind/dependency-change, size/XS, lgtm

#4251 MGMT-11550: Remove unit test duplicates - Update Network
  internal/bminventory/inventory_test.go
Labels: approved, lgtm, size/XXL

#4276 NO-ISSUE: Static net config disclaimer
  docs/user-guide/network-configuration/static-configuration.md
Labels: approved, size/S, lgtm

#4281 NO-ISSUE: Clarify MAC interface mapping for static nmstate
  docs/user-guide/network-configuration/static-configuration.md
Labels: approved, size/XS, lgtm

#4283 MGMT-8890: Unit test to ensure compatibility of release images
  internal/common/common.go
  internal/versions/versions_test.go
Labels: approved, size/M, lgtm

#4278 Bug 2119308: save-partlabel and save-partindex coreos-installer args…
  internal/host/conditions.go
  internal/host/host_test.go
  internal/host/hostcommands/disk_performance_cmd.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostutil/host_utils.go
  internal/host/transition_test.go
  models/install_cmd_request.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, bugzilla/severity-unspecified, size/M, api-review, lgtm, bugzilla/valid-bug

#4287 NO-ISSUE: updated the converged flow docs
  docs/hive-integration/README.md
Labels: approved, size/XS, lgtm

#4286 MGMT-11708: install oc from quay.io
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, size/XS, lgtm

#4274 Bug-2118970: Create an utility GetIgnitionEndpoint function
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/hostcommands/api_vip_connectivity_check_cmd.go
  internal/host/hostutil/host_utils.go
  internal/host/hostutil/host_utils_test.go
Labels: approved, size/L, lgtm

#4114 MGMT-11121: Add enhancement document for day2 master
  docs/enhancements/day2-master.md
Labels: approved, size/M, lgtm

#4293 MGMT-8890: Use "multi" as a keyword for multi-arch OpenShift
  internal/common/common.go
  subsystem/kubeapi_test.go
Labels: approved, size/XS, lgtm

#4255 MGMT-11335: Handle agent reclaim step replies
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/mock_host_api.go
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, size/L, lgtm

#4197 MGMT-9914: Integration of the ODF LVM operator with assisted installer
  api/vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  api/vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  docs/dev/olm-operator-plugins.md
  internal/cluster/cluster_test.go
  internal/cluster/statemachine.go
  internal/cluster/validation_id.go
  internal/controller/controllers/gomock_reflect_2837856844/prog.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/statemachine.go
  internal/host/validation_id.go
  internal/host/validations_test.go
  internal/operators/builder.go
  internal/operators/lvm/config.go
  internal/operators/lvm/lvm_operator.go
  internal/operators/lvm/lvm_operator_test.go
  internal/operators/lvm/lvm_suite_test.go
  internal/operators/lvm/manifest.go
  internal/operators/lvm/manifests_test.go
  internal/operators/lvm/test_utils.go
  internal/operators/manager_test.go
  models/cluster_validation_id.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  subsystem/operators_test.go
  swagger.yaml
  vendor/github.com/golang/mock/mockgen/model/model.go
  vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  vendor/modules.txt
Labels: approved, size/XL, api-review, lgtm, ok-to-test

#4275 MGMT-8890: Provide a multiarch RELEASE_IMAGE
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
  tools/handle_ocp_versions.py
Labels: approved, size/S, lgtm

#3979 MGMT-10866: Update assisted container to CentOS 9
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, size/XS, lgtm

#4296 MGMT-11711: add dashboard for 5xx errors
  dashboards/grafana-dashboard-assisted-installer-resource-utilization.configmap.yaml
Labels: approved, size/L, lgtm

#4300 MGMT-11711: remove duplicate dashboard, which is breaking grafana
  dashboards/grafana-dashboard-assisted-resource-dashboard.yaml
Labels: approved, size/XL, lgtm

#4263 MGMT-11334: Add additional API models for service-to-agent host reclaim
  api/vendor/github.com/openshift/assisted-service/models/download_boot_artifacts_request.go
  api/vendor/github.com/openshift/assisted-service/models/reboot_for_reclaim_request.go
  models/download_boot_artifacts_request.go
  models/reboot_for_reclaim_request.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/download_boot_artifacts_request.go
  vendor/github.com/openshift/assisted-service/models/reboot_for_reclaim_request.go
Labels: approved, size/S, api-review, lgtm

#4298 MGMT-10850: Fix misleading message during KubeAPI reboot
  internal/host/host.go
  internal/host/host_test.go
Labels: approved, size/M, lgtm

#4285 MGMT-8890: InfraEnv to validate content of release image
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  subsystem/cluster_v2_test.go
  subsystem/infra_env_test.go
  subsystem/kubeapi_test.go
  subsystem/subsystem_suite_test.go
Labels: approved, size/L, lgtm

#4297 MGMT-8890: Update openshift-versions API call to return all archs
  internal/versions/versions.go
  internal/versions/versions_test.go
Labels: approved, size/L, lgtm

#4299 MGMT-11182: Allow base level domain
  pkg/validations/validations.go
  pkg/validations/validations_test.go
  subsystem/cluster_test.go
Labels: approved, size/M, lgtm

#4306 MGMT-11779: Add the kubelet IP for all architectures
  internal/ignition/ignition.go
Labels: approved, size/S, lgtm

#4308 MGMT-11711: align retries units with rest of measuramentes
  dashboards/grafana-dashboard-assisted-installer-resource-utilization.configmap.yaml
Labels: approved, size/XS, lgtm

#4158 MGMT-10816: Returning the actual resulting cluster platform
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/provider/baremetal/base.go
  internal/provider/registry/registry.go
  internal/provider/registry/registry_test.go
  subsystem/kubeapi_test.go
Labels: approved, lgtm, size/XXL

#4295 MGMT-11148:LVMO-feature-support
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level.go
  internal/featuresupport/support_levels_list.go
  internal/usage/consts.go
  models/feature_support_level.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/feature_support_level.go
Labels: approved, size/M, api-review, lgtm, ok-to-test

#4312 MGMT-8890: Add OS image validator to openshift-versions API call
  internal/versions/versions.go
  internal/versions/versions_test.go
Labels: approved, size/M, lgtm

#4314 MGMT-8890: Mark cluster as multi-arch automatically
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  subsystem/cluster_v2_test.go
Labels: approved, size/M, lgtm

#4316 NO-ISSUE: fix resource ratio for memory usage
  dashboards/grafana-dashboard-assisted-installer-resource-utilization.configmap.yaml
Labels: approved, size/S, lgtm

#4317 NO-ISSUE: fix ratio for memory limit in grafana dashboard
  dashboards/grafana-dashboard-assisted-installer-resource-utilization.configmap.yaml
Labels: approved, size/XS, lgtm

#4244 MGMT-11523: Add k8s API platform support to upstream docs
  docs/hive-integration/README.md
  docs/hive-integration/crds/agentClusterInstall.yaml
  docs/hive-integration/platform-selection.md
Labels: approved, size/S, lgtm

#4321 Bump mockgen to prevent dependencies removal
  hack/setup_env.sh
Labels: approved, size/XS, lgtm

#4324 MGMT-8890: Add 4.11 single-arch release image to defaults
  data/default_release_images.json
  deploy/podman/configmap.yml
  internal/versions/versions_test.go
  openshift/template.yaml
  subsystem/cluster_v2_test.go
Labels: approved, size/M, lgtm

#4271 MGMT-11549: Send reclaim steps to agent
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_reclaimer.go
  internal/controller/controllers/agent_reclaimer_test.go
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  internal/gencrypto/token.go
  internal/gencrypto/token_test.go
  internal/host/hostcommands/download_boot_artifacts_cmd.go
  internal/host/hostcommands/download_boot_artifacts_cmd_test.go
  internal/host/hostcommands/instruction_manager.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/host/hostcommands/reboot_for_reclaim_cmd.go
  internal/host/hostcommands/reboot_for_reclaim_cmd_test.go
  internal/imageservice/url_test.go
  internal/imageservice/urls.go
  internal/versions/mock_versions.go
  internal/versions/versions.go
  internal/versions/versions_test.go
Labels: approved, size/XL, lgtm

#4339 NO-ISSUE: Specify Hive channel explicitly
  deploy/operator/setup_hive.sh
Labels: approved, size/XS, lgtm
