Repository openshift/assisted-service, pull requests merged in 2022-01, with the labels that each got.

#3145 MGMT-7705: ignore empty OpenshiftVersions
  cmd/main.go
Labels: approved, size/XS, lgtm

#3147 [cloud_hotfix_releases] MGMT-8477: invoke cluster validations when updating a host (#3082)
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  subsystem/cluster_v2_test.go
Labels: approved, size/M, lgtm

#3151 MGMT-8498: fixing issue with not mounting pki due to old next_step_runner code.
  internal/bminventory/inventory.go
  internal/host/hostcommands/next_step_runner_cmd.go
  internal/host/hostcommands/next_step_runner_cmd_test.go
  internal/host/hostcommands/v2_next_step_runner_cmd.go
Labels: approved, size/M, lgtm

#3153 NO-ISSUE: Change default release image to 4.9
  Makefile
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_release_images.json
  onprem-environment
  openshift/template.yaml
Labels: approved, size/S, lgtm

#3156 NO-ISSUE: fix swagger UI link
  README.md
Labels: approved, size/XS, lgtm

#3158 MGMT-7307: Tweak media disconnected message
  internal/bminventory/inventory.go
Labels: approved, size/XS, lgtm

#3150 MGMT-8755: Make openshift_version optional for day2 cluster in REST API
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/instruction_manager_test.go
  models/import_cluster_params.go
  restapi/embedded_spec.go
  skipper.yaml
  subsystem/day2_cluster_test.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#3160 MGMT-8756: Make ImageSetRef optional in ACI for day2
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  api/hiveextension/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  pkg/validating-webhooks/hiveextension/v1beta1/agentclusterinstall_admission_hook.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, api-review, lgtm

#3152 MGMT-8748: detect overlapping networks in SNO
  internal/cluster/transition_test.go
  internal/cluster/validator.go
  internal/network/cidr_validations.go
  internal/network/utils.go
Labels: approved, size/L, lgtm

#3162 Replace docker usage with binary installation for conf generation
  hack/generate.sh
  hack/setup_env.sh
Labels: approved, size/S, lgtm

#3161 Backport podman installation mode changes
  Makefile
  docs/installer-stand-alone.md
  onprem-environment
Labels: approved, size/M, lgtm

#3164 MGMT-8755: remove mco image , must-gather and openshift version from day2 installation command.
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/S, lgtm

#3167 MGMT-8841: Container image availability check is not running in some cases
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, size/S, lgtm

#3143 MGMT-8765: Add integration tests to the MGMT-8280 code
  internal/common/common.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, lgtm

#3165 MGMT-7305: Fix ACI column
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
Labels: approved, size/XS, api-review, lgtm

#3131 MGMT-8197: Deploy HPP when CNV is requested on SNO (so persistent VMs are possible)
  internal/host/transition_test.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/cnv/cnv_operator_test.go
  internal/operators/cnv/config.go
  internal/operators/cnv/manifest.go
  internal/operators/cnv/manifests_test.go
  internal/operators/ocs/consts.go
  internal/operators/ocs/validations.go
  openshift/template.yaml
Labels: approved, size/L, lgtm, ok-to-test

#3172 Remove redundant files for bumping OCP versions
  dev-requirements.txt
  tools/ocp_version_update/Jenkinsfile.default_release_update
  tools/ocp_version_update/update_default_release_versions_to_latest.py
Labels: approved, size/L, lgtm

#3168 MGMT-8510: Duplicate hosts status messages on events
  internal/common/events/events.go
  internal/events/api/event.go
  internal/events/api/mock_event.go
  internal/events/eventstest/events_test_utils.go
  internal/host/hostutil/update_host.go
  internal/host/hostutil/update_host_test.go
  tools/generate_events.py
Labels: approved, size/L, lgtm, ok-to-test

#3174 MGMT-8851: Remove 99_ prefix from manifests
  internal/operators/cnv/manifest.go
  internal/operators/cnv/manifests_test.go
  internal/operators/lso/manifest.go
  internal/operators/lso/manifests_test.go
  internal/operators/ocs/manifest.go
  internal/operators/ocs/manifests_test.go
  internal/provider/ovirt/consts.go
Labels: approved, size/M, lgtm, ok-to-test

#3183 MGMT-5425: stop spamming logs from local authenticator
  pkg/auth/local_authenticator.go
Labels: approved, size/XS, lgtm

#3084 MGMT-8664: Add none ztp platform installation flow with load-balancer for libvirt
  deploy/operator/README.md
  deploy/operator/ztp/agentClusterInstall.j2
  deploy/operator/ztp/assisted-installer-crds-playbook.yaml
  deploy/operator/ztp/deploy_spoke_cluster.sh
  deploy/operator/ztp/none_platform_utils.sh
Labels: approved, size/L, lgtm

#3178 Bug 2038903: Add proxy env vars to image service
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
Labels: approved, size/M, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#3181 MGMT-8871: updates Ingress usage to v1
  deploy/assisted-installer-ingress-tls.yaml
  deploy/assisted-installer-ingress.yaml
Labels: approved, size/M, lgtm

#3186 MGMT-8887: Upgrade OCM SDK
  go.mod
  go.sum
Labels: approved, size/M, lgtm

#3055 Bug 2038250: Fix catalogsource name
  deploy/operator/common.sh
  deploy/operator/gather.sh
  deploy/operator/setup_assisted_operator.sh
Labels: approved, size/M, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#3194 [cloud_hotfix_releases] MGMT-8887: Upgrade OCM SDK
  go.mod
  go.sum
Labels: approved, size/M, lgtm

#3197 NO-ISSUE: Minor clean up to the PULL_REQUEST template
  docs/pull_request_template.md
Labels: approved, size/S, lgtm

#3166 NO-ISSUE: Add a middleware to optionally disable v1 API
  cmd/main.go
  openshift/template.yaml
  pkg/app/middleware.go
  pkg/app/middleware_test.go
Labels: approved, size/L, lgtm

#3196 NO-ISSUE: Add support for OCP 4.10.0-fc.0 version
  config/manager/manager.yaml
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  onprem-environment
  openshift/template.yaml
Labels: approved, size/M, lgtm

#3198 NO-ISSUE: Fix broken URLs in REST V1 to V2 doc
  docs/user-guide/rest-api-v1-v2-transition-guide.md
Labels: approved, size/XS, lgtm

#3188 NO-ISSUE: Fix assisted_service_build image can't find minikube
  Dockerfile.assisted-service-build
Labels: approved, kind/dependency-change, size/XS, lgtm

#3203 NO-ISSUE: Use the correct iso download url for 4.10 rhcos
  config/manager/manager.yaml
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  onprem-environment
  openshift/template.yaml
Labels: approved, size/S, lgtm

#3200 MGMT-8085: Change the cluster ssh_public_key field to text type
  internal/migrations/20220113152127_change_cluster_ssh_key_to_text.go
  internal/migrations/20220113152127_change_cluster_ssh_key_to_text_test.go
  internal/migrations/migrations.go
Labels: approved, size/M, lgtm

#3201 NO-ISSUE: add vlan and bond nmstate examples
  docs/user-guide/restful-api-guide.md
Labels: approved, size/M, lgtm

#3195 MGMT-8893: set arm64 support as dev-preview
  internal/featuresupport/support_levels_list.go
Labels: approved, size/S, lgtm

#3204 NO-ISSUE: Add syntax highlighting to restful API guide
  docs/user-guide/restful-api-guide.md
Labels: approved, size/S, lgtm

#3205 NO-ISSUE: update static networking guide to v2
  docs/user-guide/restful-api-guide.md
Labels: approved, size/S, lgtm

#3089 OCPBUGSM-38736: Fix 'supported-platforms' endpoint
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/S, lgtm, ok-to-test

#3170 MGMT-8428: cpu architecture support in kube-api
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  api/v1beta1/infraenv_types.go
  config/crd/bases/agent-install.openshift.io_infraenvs.yaml
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  internal/bminventory/inventory.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/infraenv_controller.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, api-review, lgtm

#3213 NO-ISSUE: remove unused etcd pkg from go.mod
  go.mod
  go.sum
Labels: approved, size/XS, lgtm

#3215 MGMT-8958: Proxy support in ACI
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  api/hiveextension/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, api-review, lgtm

#3217 MGMT-8664: Fix ACI template breaking dual-stack configuration
  deploy/operator/ztp/agentClusterInstall.j2
Labels: approved, size/XS, lgtm

#3199 MGMT-8894: Simplify IPv6 Network Manager configuration
  internal/common/common.go
  internal/ignition/ignition.go
Labels: approved, size/M, lgtm

#3221 NO-ISSUE: update approvers and reviewers lists
  OWNERS
  OWNERS_ALIASES
Labels: approved, size/S, lgtm

#3226 MGMT-8894: Catch FCs and nightlies when comparing OCP versions
  internal/common/common_test.go
  internal/ignition/ignition.go
Labels: approved, size/S, lgtm

#3184 MGMT-8716: uses Pod definition with podman
  Makefile
  README.md
  deploy/podman/README.md
  deploy/podman/configmap.yml
  deploy/podman/pod.yml
  deploy/ui/nginx.conf
  docs/installer-stand-alone.md
  docs/user-guide/assisted-service-on-local.md
  hack/generate.sh
  onprem-environment
Labels: size/L

#3232 NO-ISSUE: clarifies prerequisites in README
  README.md
Labels: approved, size/XS, lgtm

#3187 NO-ISSUE: Use agent's status role instead of spec
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/XS, lgtm

#3225 MGMT-8738: Set Disconnected status for media disconnection during dis…
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/hostutil/host_utils.go
Labels: approved, size/M, lgtm

#3234 MGMT-9035: Fix validation of CA bundle
  internal/common/common.go
  internal/common/common_test.go
Labels: approved, size/M, lgtm

#3238 MGMT-9027: fix flaky subsystem test
  subsystem/kubeapi_test.go
Labels: approved, size/S, lgtm

#3233 NO-ISSUE: extends doc with podman pod config detail
  deploy/podman/README.md
Labels: approved, size/XS, lgtm

#3182 MGMT-8582: Leader elector to use leases
  config/rbac/base/role.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  pkg/leader/leaderelector.go
  subsystem/leader_test.go
Labels: approved, size/L, lgtm

#3236 NO-ISSUE: corrects image reference in pod definition
  deploy/podman/pod.yml
Labels: approved, size/XS, lgtm

#3246 MGMT-8744: Add log indicating that with auth none image url will not change
  internal/bminventory/inventory.go
  internal/bminventory/inventory_v2_handlers.go
Labels: approved, size/XS, lgtm

#3222 MGMT-7896: Add host's log's URL to Agent CR's status.
  api/v1beta1/agent_types.go
  config/crd/bases/agent-install.openshift.io_agents.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, size/L, api-review, lgtm

#3219 MGMT-8783: support multiple patch versions of os/release images
  cmd/main.go
  docs/hive-integration/kube-api-select-ocp-versions.md
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/versions/mock_versions.go
  internal/versions/versions.go
  internal/versions/versions_test.go
Labels: approved, size/L, lgtm

#3250 MGMT-9068: Allow /31 machine cidr in SNO
  internal/network/cidr_validations.go
  internal/network/cidr_validations_test.go
Labels: approved, size/S, lgtm

#3220 MGMT-8844: Assisted-installer update SNO minimum RAM requirement to 16GB
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  data/default_hw_requirements.json
  deploy/operator/README.md
  deploy/podman/configmap.yml
  docs/dev/hardware-requirements.md
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/hardware/validator_test.go
  internal/host/transition_test.go
  site/dev/hardware-requirements/index.html
  site/search/search_index.json
Labels: approved, size/M, lgtm, ok-to-test

#3254 NO-ISSUE: use OpenshiftVersion as key in openshift-versions API
  internal/versions/versions.go
  internal/versions/versions_test.go
Labels: approved, size/XS, lgtm

#3237 Bug 2034686: Expose a way for users to disable TLS verification in image service through the agent service config
  docs/operator.md
  internal/controller/controllers/agentserviceconfig_controller.go
Labels: approved, size/S, api-review, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#3245 MGMT-9053: Replace register_host_to_infra_env_failed with host_registration_failed
  docs/events.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/events/events.go
  internal/controller/controllers/controller_event_wrapper_test.go
  subsystem/cluster_test.go
Labels: approved, size/L, api-review, lgtm

#3251 MGMT-9070: ZTP versions are not compared correctly for sorting and filtering
  deploy/operator/common.sh
Labels: approved, size/XS, lgtm

#3260 MGMT-8582: rbac permission for leases
  config/rbac/base/role.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
Labels: approved, size/M, lgtm

#3261 MGMT-9094: Wrong default timestamp for install_started_at and install…
  models/cluster.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/S, api-review, lgtm

#3252 MGMT-8580: Add documentation to boot discovery image through iPXE on AWS EC2
  docs/user-guide/boot-discovery-image-on-aws-ec2.md
Labels: approved, size/M, lgtm

#3253 MGMT-8943: Update documentation to V2 REST-API
  docs/set-discovery-password.md
  docs/set-minimal-iso.md
  docs/user-guide/deploy-on-bare-metal.md
  docs/user-guide/install-customization.md
  docs/user-guide/rest-api-v1-v2-transition-guide.md
  docs/user-guide/samples/cluster.json
Labels: approved, size/M, lgtm
