Repository openshift/assisted-service, pull requests merged in 2022-10, with the labels that each got.

#4413 MGMT-12074: Add unitests for bootstrap kubelet ip set
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
Labels: approved, size/M, lgtm

#4424 MGMT-11293: Added default network type setting during registration
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#4323 MGMT-11753: fix flaky kustomize installation
  Dockerfile.assisted-service-build
  Dockerfile.bundle
  ci-images/Dockerfile.code-generation
  ci-images/Dockerfile.subsystem
  deploy/operator/setup_hive.sh
  hack/Makefile
  hack/generate.sh
  hack/setup_env.sh
Labels: approved, kind/dependency-change, size/M, lgtm

#4454 Bug 2131023: Allow arm64 sno installation
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/M, lgtm, bugzilla/severity-low, bugzilla/valid-bug

#4458 MGMTBUGSM-529: fix error msg in update disk path scenario
  internal/host/host.go
Labels: approved, size/XS, lgtm

#4448 MGMT-11635: Bad request error when user chooses both LVM and CNV
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/operators/manager.go
  internal/operators/manager_test.go
  subsystem/cluster_test.go
  subsystem/operators_test.go
Labels: approved, size/L, lgtm

#4461 MGMT-12217: Update infraEnv initrd URL when image content is updated
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/M, lgtm

#4465 NO-ISSUE: Change `get_current_size_if_exist` to inspect PVC `.spec` and not `.status`
  tools/pvc_size_utils.py
Labels: approved, size/M, lgtm

#4470 MGMT-11878: Extend validator unit-tests to contain IPv6 URLs
  pkg/validations/validations_test.go
Labels: approved, size/XS, lgtm

#4469 MGMT-10557: Docs for per-customer feature enablement
  docs/dev/feature-per-customer.md
Labels: approved, size/M, lgtm

#4442 MGMT-8578: Describe process for day2 master for OCP 4.11
  docs/user-guide/day2-master/411-healthy.md
  docs/user-guide/day2-master/411-unhealthy.md
  docs/user-guide/day2-master/README.md
  docs/user-guide/day2-master/link-machine-and-node.sh
Labels: approved, size/XL, lgtm

#4467 NO-ISSUE: Update subsystem docs to use minikube with podman
  docs/dev/running-test.md
Labels: approved, size/XS, lgtm

#4401 MGMT-11751: ensure agent-install CRDs exist spoke cluster
  api/v1beta1/hypershiftagentserviceconfig_types.go
  cmd/operator/main.go
  config/rbac/role.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  internal/controller/controllers/common.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go
  internal/spoke_k8s_client/spoke_k8s_client.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/hypershiftagentserviceconfig_types.go
Labels: approved, size/L, api-review, lgtm

#4471 AGENT-374: agent-based-client: Apply installconfig overrides
  cmd/agentbasedinstaller/register.go
  docs/hive-integration/crds/agentClusterInstall-with-installconfig-overrides.yaml
  subsystem/agent_based_installer_client_test.go
Labels: approved, size/M, lgtm

#4476 NO-ISSUE: Use 4.11 index for LSO installation in 4.12
  deploy/operator/setup_lso.sh
Labels: approved, size/S, lgtm

#4385 MGMT-11736: refactor ASC reconciler
  cmd/operator/main.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
Labels: approved, size/XL, lgtm

#4478 NO-ISSUE: Use legacy security context for disconnected CI
  deploy/operator/mirror_utils.sh
  deploy/operator/setup_lso.sh
Labels: approved, size/S, lgtm

#4475 Bug 2106110: Don't set ip=<nic>:dhcp kernel params with static networking
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/S, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#4486 Revert buildkit usage in skipper dockerfile
  Dockerfile.assisted-service-build
  README.md
  hack/setup_env.sh
  skipper.env
Labels: approved, kind/dependency-change, size/M, lgtm

#4482 NO-ISSUE: DNS bad wildcard validation message should include IP addresses
  internal/host/validations_test.go
  internal/host/validator.go
Labels: approved, size/M, lgtm

#4372 document process for using assisted installer in a disconnected env
  deploy/podman/README-disconnected.md
  deploy/podman/configmap-disconnected.yml
  deploy/podman/pod-persistent-disconnected.yml
Labels: approved, size/L, lgtm, needs-ok-to-test

#4489 NO-ISSUE: In CI check status of Deployment and not Pod
  deploy/operator/gather.sh
  deploy/operator/setup_assisted_operator.sh
  deploy/operator/utils.sh
Labels: approved, size/S, lgtm

#4483 MGMT-11129: Only set bootstrap host when it's attached to a cluster
  internal/host/host.go
  internal/host/host_test.go
Labels: approved, size/M, lgtm

#4494 NO-ISSUE: In CI check status of Deployment and not Pod
  deploy/operator/gather.sh
  deploy/operator/setup_assisted_operator.sh
  deploy/operator/utils.sh
Labels: approved, size/S, lgtm, bugzilla/valid-bug

#4479 MGMT-8890: Create validator for RHCOS and OCP versions
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/versions/mock_versions.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  subsystem/cluster_v2_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, lgtm

#4490 MGMT-11642: Add Host Bind/Unbind Events
  docs/events.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/events/events.go
Labels: approved, size/L, api-review, lgtm

#4498 NO-ISSUE: Fix command syntax for getting postgres size
  tools/pvc_size_utils.py
Labels: approved, size/XS, lgtm

#4487 MGMT-12198: Validate Install Config Overrides
  internal/installcfg/builder/builder.go
  internal/installcfg/builder/builder_test.go
  subsystem/cluster_v2_test.go
Labels: approved, size/M, lgtm

#4501 Bug 2107715: Add validation for Agent's role
  internal/host/common.go
  internal/host/host_test.go
  internal/host/hostutil/host_utils.go
Labels: approved, size/M, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#4503 fixing small documentation error in Patch InfraEnv section
  docs/user-guide/rest-api-getting-started.md
Labels: approved, size/XS, lgtm, ok-to-test

#4463 MGMT-11700: Validate storage requirements
  deploy/operator/setup_assisted_operator.sh
  go.mod
  go.sum
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_storage_validation_test.go
  internal/controller/controllers/controllers_suite_test.go
  internal/testing/fake_cluster.go
  vendor/github.com/bombsimon/logrusr/v3/.gitignore
  vendor/github.com/bombsimon/logrusr/v3/LICENSE
  vendor/github.com/bombsimon/logrusr/v3/README.md
  vendor/github.com/bombsimon/logrusr/v3/logrusr.go
  vendor/github.com/go-logr/logr/README.md
  vendor/github.com/go-logr/logr/logr.go
  vendor/modules.txt
Labels: approved, size/XL, lgtm

#4502 MGMT-12167: Make possible to mirror an index referenced by digest
  deploy/operator/mirror_utils.sh
Labels: approved, size/XS, lgtm

#4488 Document using SaaS with internal registry
  docs/user-guide/README.md
  docs/user-guide/cloud-with-mirror.md
Labels: approved, size/L, lgtm, ok-to-test

#4509 NO-ISSUE: unlimit postgres CPU due to spiky nature of tests
  deploy/postgres/postgres-deployment.yaml
Labels: approved, size/XS, lgtm

#4510 Bug 2135714: Don't set bootstrap kubelet ip in case of UMN
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
Labels: approved, bugzilla/severity-unspecified, size/M, lgtm, bugzilla/valid-bug

#4495 NO-ISSUE: In CI check status of Deployment and not Pod
  deploy/operator/gather.sh
  deploy/operator/setup_assisted_operator.sh
  deploy/operator/utils.sh
Labels: approved, size/S, lgtm, bugzilla/valid-bug

#4517 NO-ISSUE: flaky test due to network type mismatch
  subsystem/cluster_test.go
Labels: approved, size/XS, lgtm

#4455 MGMT-12188: Fix panic when infraEnv image has not been created
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, lgtm

#4515 MGMT-11642: Add Host Bind/Unbind Events (#4490)
  docs/events.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/events/events.go
Labels: approved, size/L, api-review, lgtm, bugzilla/valid-bug

#4511 Bump 4.12 OCP image to ec.4
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm

#4506 MGMT-1107: Make host stage timeouts configurable
  cmd/main.go
  internal/host/config.go
  internal/host/config_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, size/L, lgtm

#4512 MGMT-11737: HASC RBAC Configuration
  api/v1beta1/agentserviceconfig_types.go
  cmd/operator/main.go
  go.mod
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go
  internal/controller/controllers/rbac/auth_proxy_client_clusterrole.yaml
  internal/controller/controllers/rbac/auth_proxy_role.yaml
  internal/controller/controllers/rbac/auth_proxy_role_binding.yaml
  internal/controller/controllers/rbac/auth_proxy_service.yaml
  internal/controller/controllers/rbac/base/kustomization.yaml
  internal/controller/controllers/rbac/base/role.yaml
  internal/controller/controllers/rbac/base/role_binding.yaml
  internal/controller/controllers/rbac/base/service_account.yaml
  internal/controller/controllers/rbac/kustomization.yaml
  internal/controller/controllers/rbac/leader_election_role.yaml
  internal/controller/controllers/rbac/leader_election_role_binding.yaml
  internal/controller/controllers/rbac/ocp/kustomization.yaml
  internal/controller/controllers/rbac/ocp/role.yaml
  internal/controller/controllers/rbac/ocp/role_binding.yaml
  internal/controller/controllers/rbac/role.yaml
  internal/controller/controllers/rbac/role_binding.yaml
  vendor/github.com/bombsimon/logrusr/v3/.gitignore
  vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/hypershiftagentserviceconfig_types.go
Labels: approved, api-review, lgtm, size/XXL

#4513 MGMT-12261: Respect `InstallConfigOverrides` when `getCAContents` is non-empty
  internal/installcfg/builder/builder.go
  internal/installcfg/builder/builder_test.go
Labels: approved, size/M, lgtm

#4523 NO-ISSUE: Update doc for per-customer feature enablement
  docs/dev/feature-per-customer.md
Labels: approved, size/XS, lgtm

#4524 MGMT-8890: Create intro doc into multiarch
  docs/user-guide/multiarch-and-heterogeneous-openshift.md
Labels: approved, size/M, lgtm

#4526 NO-ISSUE: Add Javi as reviewer
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#4320 MGMT-11782: Don't add installation disk to disks to format list when …
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/M, lgtm

#4507 NO-ISSUE: Ensure timeout is set in wait_for_deployment
  deploy/operator/setup_assisted_operator.sh
  deploy/operator/utils.sh
Labels: approved, size/XS, lgtm

#4472 MGMT-11878: Extend URL validator to check for trailing whitespaces
  pkg/validations/validations_test.go
Labels: approved, size/XS, lgtm

#4531 MGMT-12317: Add capabilities entries to install-config
  internal/installcfg/installcfg.go
Labels: approved, size/S, lgtm

#4530 MGMT-12314: Fix API IP detection for day2 ZTP CI
  deploy/operator/ztp/deploy_spoke_cluster.sh
Labels: approved, size/XS, lgtm

#4519 MGMT-11769: reconcile service components on HASC ctrl
  config/embed.go
  config/rbac/role.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go
  internal/controller/controllers/rbac/auth_proxy_client_clusterrole.yaml
  internal/controller/controllers/rbac/auth_proxy_role.yaml
  internal/controller/controllers/rbac/auth_proxy_role_binding.yaml
  internal/controller/controllers/rbac/auth_proxy_service.yaml
  internal/controller/controllers/rbac/base/kustomization.yaml
  internal/controller/controllers/rbac/base/role.yaml
  internal/controller/controllers/rbac/base/role_binding.yaml
  internal/controller/controllers/rbac/base/service_account.yaml
  internal/controller/controllers/rbac/kustomization.yaml
  internal/controller/controllers/rbac/leader_election_role.yaml
  internal/controller/controllers/rbac/leader_election_role_binding.yaml
  internal/controller/controllers/rbac/ocp/kustomization.yaml
  internal/controller/controllers/rbac/ocp/role.yaml
  internal/controller/controllers/rbac/ocp/role_binding.yaml
  internal/controller/controllers/rbac/role.yaml
  internal/controller/controllers/rbac/role_binding.yaml
Labels: approved, lgtm, size/XXL

#4527 MGMT-12300: Fix nil pointer exception with v2uploadLogs
  internal/bminventory/inventory_v2_handlers.go
  pkg/s3wrapper/client.go
  pkg/s3wrapper/client_test.go
Labels: approved, size/S, lgtm

#4425 MGMT-12067: Support discovery kernel arguments during infra-env registration and updates
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/L, lgtm

#4452 Bug 2131017: Fix MinSizeGigabytes root device hint
  internal/controller/controllers/bmh_agent_controller_test.go
  internal/host/hostutil/host_utils.go
Labels: approved, size/S, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#4539 NO-ISSUE: Add some time to the cluster delete test to avoid flakes
  internal/cluster/cluster_test.go
Labels: approved, size/XS, lgtm

#4493 NO-ISSUE: In CI check status of Deployment and not Pod
  deploy/operator/gather.sh
  deploy/operator/setup_assisted_operator.sh
  deploy/operator/utils.sh
Labels: approved, size/S, lgtm, bugzilla/valid-bug

#4538 MGMT-11799: change all 'go get' commands
  Dockerfile.assisted-service-debug
  hack/setup_env.sh
  skipper.yaml
Labels: approved, kind/dependency-change, size/S, lgtm

#4437 MGMT-8578: Framework for day2 master CI ZTP jobs
  deploy/operator/ztp/add-remote-nodes-playbook.yaml
  deploy/operator/ztp/add_day2_remote_nodes.sh
  deploy/operator/ztp/baremetalHost.j2
Labels: approved, size/XS, lgtm

#4544 MGMT-12318: fix conditions update on ASC
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller.go
Labels: approved, size/S, lgtm

#4545 NO-ISSUE: annotate lso namespace instead of project
  deploy/operator/setup_lso.sh
Labels: approved, size/XS, lgtm

#4439 MGMT-9984: Support iPXE in converged ZTP flow
  go.mod
  go.sum
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/baremetalhost_types.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/baremetalhost_validation.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/hardwaredata_types.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/preprovisioningimage_types.go
  vendor/github.com/metal3-io/baremetal-operator/apis/metal3.io/v1alpha1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, size/L, lgtm

#4481 MGMT-11997: Default to using converged flow for 4.12 hub versions
  cmd/main.go
  docs/hive-integration/README.md
  internal/controller/controllers/bmo_utils.go
  internal/controller/controllers/bmo_utils_test.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
Labels: approved, size/S, lgtm

#4551 MGMT-12361: Sync install-config structure with upstream
  internal/bminventory/inventory_test.go
  internal/installcfg/installcfg.go
  internal/provider/baremetal/installConfig.go
  internal/provider/nutanix/installConfig.go
  internal/provider/registry/registry_test.go
  internal/provider/vsphere/installConfig.go
Labels: approved, size/M, lgtm

#4534 MGMT-11750: ensure namespace exists on spoke cluster (HASC)
  api/v1beta1/agentserviceconfig_types.go
  config/rbac/role.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  internal/controller/controllers/hypershiftagentserviceconfig_controller.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go
Labels: approved, size/L, api-review, lgtm

#4540 MGMT-12214: extract reconciler logic for using HASC
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go
Labels: approved, size/L, api-review, lgtm

#4554 Bump to 4.12.0-ec.5
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm

#4528 NO-ISSUE: Document how to add OCM capabilities
  docs/ocm-integration.md
Labels: approved, size/L, lgtm

#4485 MGMT-12056: changing default network type kube api
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, size/L, api-review, lgtm

#4547 MGMT-12368: Verify that Kernel Arguments API does not change in the future
  api/vendor/github.com/openshift/assisted-service/models/kernel_argument.go
  api/vendor/github.com/openshift/assisted-service/models/kernel_arguments.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  models/kernel_argument.go
  models/kernel_arguments.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/kernel_argument.go
  vendor/github.com/openshift/assisted-service/models/kernel_arguments.go
Labels: approved, size/L, api-review, lgtm

#4553 MGMT-12380: Improve message of vip validation failure
  internal/cluster/transition_test.go
  internal/cluster/validator.go
Labels: approved, size/M, lgtm

#4557 NO-ISSUE: add initialDelaySeconds for readiness probe
  openshift/template.yaml
Labels: approved, size/XS, lgtm
