Repository openshift/assisted-service, pull requests merged in 2022-06, with the labels that each got.

#3879 MGMT-10643: V2ListSupportedOpenshiftVersions should not err for ValidateAccessToCPUArchitecture false
  internal/versions/versions.go
  internal/versions/versions_test.go
  pkg/auth/authz_utils.go
  subsystem/versions_test.go
Labels: approved, size/S, lgtm

#3884 Bug 2090415: internal/controller/controllers: label mirrorRegistryRef configmap for backup
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/common.go
Labels: approved, size/M, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#3885 MGMT-10662: Add timestamp to get-next-steps and let the service use it
  api/vendor/github.com/openshift/assisted-service/models/host.go
  client/installer/v2_get_next_steps_parameters.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster_test.go
  internal/cluster/transition_test.go
  internal/common/common.go
  internal/host/host_test.go
  internal/host/hostutil/test_utils.go
  models/host.go
  restapi/embedded_spec.go
  restapi/operations/installer/v2_get_next_steps_parameters.go
  restapi/operations/installer/v2_get_next_steps_urlbuilder.go
  subsystem/cluster_test.go
  subsystem/host_v2_test.go
  subsystem/ipv6_test.go
  subsystem/metrics_test.go
  subsystem/utils_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/host.go
Labels: approved, size/L, api-review, lgtm

#3880 MGMT-9175: Use an interface with a Mac address
  internal/provider/baremetal/installConfig.go
  internal/provider/registry/registry_test.go
  subsystem/cluster_test.go
  subsystem/ipv6_test.go
Labels: approved, size/M, lgtm

#3893 NO-ISSUE: fix dashboards metadata
  Makefile
  dashboards/grafana-dashboard-assisted-installer-agent-api.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-basic-cluster-operation.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-cluster-overview.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-deployment-overview.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-general-overview.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-resource-utilization.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-rnd-overview.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-weekly-overview.configmap.yaml
  dashboards/grafana-dashboard-assisted-resource-dashboard.yaml
Labels: approved, size/L, lgtm

#3862 MGMT-10616: add OCP 4.11 images
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm

#3897 Bug 2093503: Assisted service POD keeps crashing after a bare metal host is created
  cmd/main.go
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
Labels: approved, size/XS, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#3908 MGMT-10713: Soften IP-stack checks for host_network propagation
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/M, lgtm

#3836 AGENT-40: Supply TLS certs for kubeconfig to openshift-install
  cmd/main.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  pkg/generator/generator.go
Labels: approved, size/L, lgtm

#3903 MGMT-10705: Allow installation on FC multipath
  api/vendor/github.com/openshift/assisted-service/models/disk.go
  internal/hardware/mock_validator.go
  internal/hardware/validator.go
  internal/hardware/validator_test.go
  internal/host/host.go
  internal/host/host_test.go
  models/disk.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/disk.go
Labels: approved, size/L, api-review, lgtm

#3912 MGMT-10722: Hostname 'localhost.localdomain' should not be valid
  internal/host/transition_test.go
  internal/host/validator.go
Labels: approved, size/M, lgtm

#3913 MGMT-9388: Incorrect minimal CPU and RAM requirements for cnv operator shown in UI
  internal/operators/cnv/cnv_operator.go
  internal/operators/cnv/cnv_operator_test.go
Labels: approved, size/M, lgtm

#3914 MGMT-10569: Remove cluster ignition_config_overrides column
  api/vendor/github.com/openshift/assisted-service/models/cluster.go
  hack/Makefile
  internal/migrations/20201019194303_change_overrides_to_text_test.go
  internal/migrations/20210713123129_populate_infra_env.go
  internal/migrations/20210713123129_populate_infra_env_test.go
  internal/migrations/20220527210238_drop_cluster_ignition_overrides.go
  internal/migrations/20220527210238_drop_cluster_ignition_overrides_test.go
  internal/migrations/migrations.go
  models/cluster.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster.go
Labels: approved, size/L, api-review, lgtm

#3918 MGMT-8435: Fix V2UpdateCluster response to include hosts info
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  subsystem/cluster_test.go
Labels: approved, size/L, lgtm

#3920 MGMT-10748: Define disk types in swagger
  api/vendor/github.com/openshift/assisted-service/models/disk.go
  api/vendor/github.com/openshift/assisted-service/models/drive_type.go
  internal/cluster/cluster_test.go
  internal/common/test_configuration.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  internal/hardware/validator.go
  internal/hardware/validator_test.go
  internal/host/host_test.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostutil/test_utils.go
  internal/ignition/ignition.go
  internal/metrics/metricsManager.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/cnv/cnv_operator_test.go
  internal/operators/manager_test.go
  internal/operators/odf/consts.go
  internal/operators/odf/odf_operator_test.go
  internal/operators/odf/validation_test.go
  internal/operators/odf/validations.go
  models/disk.go
  models/drive_type.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/disk.go
  vendor/github.com/openshift/assisted-service/models/drive_type.go
Labels: approved, size/L, api-review, lgtm

#3917 MGMT-9553: Ensure that MaxHostDisconnectionTime is configurable.
  internal/hardware/validator.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/transition.go
  internal/host/transition_test.go
  internal/host/validator.go
  subsystem/metrics_test.go
Labels: approved, size/M, lgtm

#3904 MGMT-9561: VSphere platform lacking setting disk.EnableUUID guidance
  internal/hardware/mock_validator.go
  internal/hardware/validator.go
  internal/host/refresh_status_preprocessor.go
  internal/host/validation_id.go
  internal/host/validations_test.go
  internal/host/validator.go
Labels: approved, size/L, lgtm

#3877 MGMT-10618: enhancement doc - extract OS image
  docs/enhancements/extract-os-image-from-release.md
Labels: approved, size/L, lgtm

#3933 auth: AuthUserAuth errors should be wrapped in HTTP 401
  pkg/auth/rhsso_authenticator.go
  pkg/auth/rhsso_authenticator_test.go
Labels: approved, size/S, lgtm

#3840 Bug 2089195: [release-ocm-2.5] Expose ipxe boot artifacts via HTTP
  api/v1beta1/agentserviceconfig_types.go
  cmd/main.go
  config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
  config/crd/resources.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  config/rbac/ocp/role.yaml
  config/rbac/role.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agentserviceconfigs.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/bmh_agent_controller_test.go
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  internal/imageservice/url_test.go
  internal/imageservice/urls.go
  pkg/app/middleware.go
  pkg/app/middleware_test.go
  pkg/s3wrapper/client_test.go
Labels: approved, size/XL, api-review, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#3938 BZ-2096460: Spoke BMH stuck inspecting when deployed via the converged workflow
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/ignition/ironic.go
Labels: approved, size/XS, lgtm

#3586 MGMT-9710: Provide extended networking defaults in default-config API
  api/vendor/github.com/openshift/assisted-service/models/cluster_default_config.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_v2_handlers.go
  models/cluster_default_config.go
  restapi/embedded_spec.go
  subsystem/cluster_default_config_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster_default_config.go
Labels: approved, size/L, api-review, lgtm

#3886 MGMT-10666 - Single Node expansion feature support flag
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level.go
  internal/featuresupport/support_levels_list.go
  internal/usage/consts.go
  models/feature_support_level.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/feature_support_level.go
Labels: approved, size/S, api-review, lgtm

#3941 MGMT-9561: VSphere platform lacking setting disk.EnableUUID guidance.…
  internal/host/statemachine.go
Labels: approved, size/XS, lgtm

#3866 NO-ISSUE: update runc/ignition/bluemonday pkgs
  go.mod
  go.sum
Labels: approved, size/M, lgtm, bugzilla/valid-bug

#3922 MGMT-10755: Remove duplicates: 'IPv6 support disabled' unit tests
  internal/bminventory/inventory_test.go
Labels: approved, size/M, lgtm

#3945 MGMT-10801: Add necessary kargs for multipath
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/L, lgtm

#3951 MGMT-10656: Enable multipathd by default in live ISO
  internal/ignition/ignition.go
Labels: approved, size/S, lgtm

#3946 [cloud_hotfix_releases] MGMT-9710: Provide extended networking defaults in default-config API…
  api/vendor/github.com/openshift/assisted-service/models/cluster_default_config.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_v2_handlers.go
  models/cluster_default_config.go
  restapi/embedded_spec.go
  subsystem/cluster_default_config_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster_default_config.go
Labels: approved, size/XL, api-review, lgtm

#3955 NO-ISSUE: Remove code for deleting ISOs from S3
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/infraenv/infraenv.go
  internal/infraenv/infraenv_test.go
  pkg/s3wrapper/client.go
Labels: approved, size/M, lgtm

#3953 NO-ISSUE: Remove unused GarbageCollectors interface
  internal/garbagecollector/garbageCollector.go
Labels: approved, size/XS, lgtm

#3958 BUG 2097700: CI - Retry cluster-info readiness
  Makefile
  tools/wait_for_cluster_info.py
Labels: approved, size/M, lgtm, bugzilla/severity-low, bugzilla/valid-bug

#3948 MGMT-10780: Explicitly pass OCP version to Hypershift
  deploy/operator/capi/deploy_capi_cluster.sh
Labels: approved, size/XS, lgtm

#3960 NO-ISSUE: Generate /models/vendor directory correctly
  hack/Makefile
  models/vendor/github.com/PuerkitoBio/purell/purell.go
  models/vendor/github.com/asaskevich/govalidator/patterns.go
  models/vendor/github.com/asaskevich/govalidator/validator.go
  models/vendor/github.com/mailru/easyjson/jlexer/lexer.go
  models/vendor/golang.org/x/net/idna/idna10.0.0.go
  models/vendor/golang.org/x/net/idna/idna9.0.0.go
Labels: approved, size/XS, lgtm

#3905 MGMT-10411: Allow enabling virtual interfaces
  internal/common/test_configuration.go
  internal/host/host.go
  internal/host/host_test.go
  internal/provider/baremetal/base.go
  internal/provider/baremetal/installConfig.go
Labels: approved, size/L, lgtm

#3952 MGMT-10597 API address should be correct for SNO
  deploy/operator/ztp/deploy_spoke_cluster.sh
  deploy/operator/ztp/none_platform_utils.sh
Labels: approved, size/S, lgtm

#3967 [release-ocm-2.4] BUG 2097820: CI - Retry cluster-info readiness
  Makefile
  dev-requirements.txt
  tools/wait_for_cluster_info.py
Labels: approved, size/M, lgtm, bugzilla/severity-low, bugzilla/valid-bug

#3969 MGMT-10597: Open firewall ports after DNS setup.
  deploy/operator/ztp/deploy_spoke_cluster.sh
Labels: approved, size/XS, lgtm

#3973 MGMT-9682: fix default disk size requirement
  hack/generate.sh
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/default_controller_hw_requirements.json
Labels: approved, size/M, lgtm

#3947 MGMT-10311: set user_managed_networking to true with sno in ci
  deploy/operator/capi/deploy_capi_cluster.sh
  deploy/operator/ztp/deploy_spoke_cluster.sh
Labels: approved, size/S, lgtm

#3975 bz-2096106: Assisted service triggers the worker nodes re-provisioning on the hub cluster when the converged flow is enabled
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/M, lgtm

#3669 MGMT-8987: 4 nodes cluster deployment
  docs/enhancements/4-nodes-cluster-deployment.md
Labels: approved, size/L, lgtm

#3977 MGMT-10637: Add default ironic agent for ARM platform
  docs/hive-integration/README.md
  internal/ignition/ironic.go
  internal/ignition/ironic_test.go
Labels: approved, size/M, lgtm

#3982 MGMT-10855: Do not format bootable LVM logical volumes
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/S, lgtm

#3959 MGMT-10834: Remove ARM capability
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  pkg/auth/authz_utils.go
  pkg/ocm/utils.go
  subsystem/authz_test.go
  subsystem/image_test.go
  subsystem/versions_test.go
  subsystem/wiremock_stubs.go
Labels: approved, size/XL, lgtm

#3991 MGMT-10488: Add assisted-operator-ztp job for the converged flow
  cmd/main.go
  deploy/operator/setup_assisted_operator.sh
  docs/hive-integration/README.md
Labels: approved, size/S, lgtm

#3892 MGMT-9720: Rewrite network configuration guide
  docs/user-guide/README.md
  docs/user-guide/network-configuration.md
  docs/user-guide/network-configuration/README.md
  docs/user-guide/network-configuration/cluster-networking.md
  docs/user-guide/network-configuration/dhcp-vip-allocation.md
  docs/user-guide/network-configuration/dual-stack.md
  docs/user-guide/network-configuration/ovn-troubleshooting.md
  docs/user-guide/network-configuration/single-stack.md
  docs/user-guide/network-configuration/static-configuration.md
  docs/user-guide/network-configuration/user-managed-networking.md
Labels: approved, size/XL, lgtm

#3983 MGMT-10858: Get Ironic image from the release image only if the release version is 4.11 or above
  go.mod
  go.sum
  internal/controller/controllers/bmo_utils.go
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
Labels: approved, size/L, lgtm

#3671 NO-ISSUE: more indicative message when agents not coming up
  deploy/operator/ztp/deploy_spoke_cluster.sh
Labels: approved, size/XS, lgtm

#3988 AGENT-215: Set release mirror for agent-based-installer
  cmd/agentbasedinstaller/agent_based_installer.go
  cmd/agentbasedinstaller/client/main.go
  subsystem/agent_based_installer_client_test.go
Labels: approved, size/S, lgtm

#3989 MGMT-10864: Collect CAPI data in assisted-baremetal-operator-gather
  deploy/operator/gather.sh
Labels: approved, size/M, lgtm

#3993 MGMT-10330: do not change network manager config in case of SNO
  internal/ignition/ignition.go
Labels: approved, size/XS, lgtm

#4001 NO-ISSUE: update networking api-version to v1
  deploy/ui/ui_ingress.yaml
Labels: approved, size/XS, lgtm

#3995 MGMT-10889: consider usage of CMN with VMs as supported
  internal/featuresupport/support_levels_list.go
Labels: approved, size/S, lgtm

#4002 NO-ISSUE: skip flaky auto-assign subsystem test
  subsystem/cluster_test.go
Labels: approved, size/XS, lgtm

#3954 AGENT-75: Add assisted installer images into OCP playload for Agent Work
  Dockerfile.assisted-service.ocp
Labels: approved, kind/dependency-change, size/XS, lgtm

#3998 NO-ISSUE: fix MinimalVersionForConvergedFlow to include 4.11.0 nightly builds
  internal/controller/controllers/bmo_utils.go
  internal/controller/controllers/bmo_utils_test.go
Labels: approved, size/M, lgtm

#4000 MGMT-10493: Don't truncate CAPI/Hypershift logs in CI
  deploy/operator/gather.sh
Labels: approved, size/XS, lgtm

#3957 MGMT-10753: add base url to image-service deployment
  deploy/assisted-image-service-service.yaml
  deploy/assisted-image-service.yaml
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  tools/deploy_image_service.py
Labels: approved, size/L, lgtm

#4008 MGMT-10916: Change capi-provider-agent jobs to use the operator workflow
  deploy/operator/capi/deploy_capi_cluster.sh
Labels: approved, size/S, lgtm

#4003 NO-ISSUE: fix assisted-installer-ui ingress format
  deploy/ui/ui_ingress.yaml
Labels: approved, size/XS, lgtm

#4015 NO-ISSUE: turn on debug logging for golangci-lint
  hack/setup_env.sh
Labels: approved, size/XS, lgtm

#3966 AGENT-224: install packages for openshift-install
  Dockerfile.assisted-service.ocp
Labels: approved, kind/dependency-change, size/XS, lgtm

#4013 MGMT-10865: Machine network is not changing if list has same values
  internal/network/utils.go
  internal/network/utils_test.go
Labels: approved, size/S, lgtm

#3927 MGMT-10311: UserManagedNetworking type change
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  api/hiveextension/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  pkg/validating-webhooks/hiveextension/v1beta1/agentclusterinstall_admission_hook.go
  pkg/validating-webhooks/hiveextension/v1beta1/agentclusterinstall_admission_hook_test.go
  subsystem/kubeapi_test.go
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/agentclusterinstall_types.go
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/zz_generated.deepcopy.go
Labels: approved, size/L, api-review, lgtm

#4010 MGMT-10868: Add late binding to Day2 remote script.
  deploy/operator/ztp/add-remote-nodes-playbook.yaml
  deploy/operator/ztp/add_day2_remote_nodes.sh
  deploy/operator/ztp/infraEnv-latebinding.j2
  deploy/operator/ztp/infraEnv.j2
Labels: approved, size/M, lgtm

#4005 Use releaseImageMirror in GetReleaseArchitecture
  cmd/agentbasedinstaller/agent_based_installer.go
  internal/oc/mock_release.go
  internal/oc/release.go
  internal/oc/release_test.go
  internal/versions/versions.go
  internal/versions/versions_test.go
Labels: approved, size/M, lgtm

#4014 AGENT-227: Add host configuration support to ephemeral installer client
  Dockerfile.assisted-service
  Dockerfile.assisted-service.ocp
  cmd/agentbasedinstaller/client/main.go
  cmd/agentbasedinstaller/host_config.go
  cmd/agentbasedinstaller/register.go
  internal/controller/controllers/bmh_agent_controller.go
  internal/host/hostutil/host_utils.go
Labels: approved, kind/dependency-change, size/XL, lgtm

#4016 AGENT-144: Use pre-generated InfraEnv ID
  internal/bminventory/inventory.go
Labels: approved, size/S, lgtm

#4020 [release-ocm-2.5] more indicative message when agents not coming back (#3671)
  deploy/operator/ztp/deploy_spoke_cluster.sh
Labels: approved, size/XS, lgtm, bugzilla/valid-bug

#4023 MGMT-10956: Do not enable multipathd on OKD agent
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
Labels: approved, size/M, lgtm

#4032 NO-ISSUE: Gather service pods definitions in the operator CI
  deploy/operator/gather.sh
Labels: approved, size/S, lgtm

#4033 MGMT-10967: Set minimal ISO as default for SAAS deployment
  openshift/template.yaml
Labels: approved, size/XS, lgtm

#4031 Automatically label deploy/ directory with valid-bug
  OWNERS
Labels: approved, size/XS, lgtm, bugzilla/valid-bug

#3996 MGMT-10754: remove unused rootfs_url from OS images
  api/v1beta1/agentserviceconfig_types.go
  api/vendor/github.com/openshift/assisted-service/models/os_image.go
  config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
  config/crd/resources.yaml
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_okd_os_images.json
  data/default_os_images.json
  deploy/olm-catalog/manifests/agent-install.openshift.io_agentserviceconfigs.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/operator/setup_assisted_operator.sh
  deploy/podman/configmap.yml
  deploy/podman/okd-configmap.yml
  docs/hive-integration/kube-api-select-ocp-versions.md
  docs/operator.md
  hack/generate.sh
  internal/common/test_configuration.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  models/os_image.go
  openshift/template.yaml
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go
  vendor/github.com/openshift/assisted-service/models/os_image.go
Labels: approved, size/L, api-review, lgtm

#4030 AGENT-227: Don't exit when inventory not available
  cmd/agentbasedinstaller/host_config.go
Labels: approved, size/XS, lgtm

#4034 MGMT-10914: fix ASC deployment reason on success
  api/v1beta1/agentserviceconfig_types.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go
Labels: approved, size/XS, api-review, lgtm

#4011 MGMT-8089: schedulableMasters field in clusters api returns wrong default values
  api/vendor/github.com/openshift/assisted-service/models/cluster.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/mock_cluster_api.go
  internal/common/common.go
  internal/common/common_test.go
  models/cluster.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster.go
Labels: approved, size/L, api-review, lgtm

#4021 MGMT-10868 - Fix unbound `DAY2_LATE_BINDING` variable error
  deploy/operator/common.sh
  deploy/operator/ztp/add-remote-nodes-playbook.yaml
  deploy/operator/ztp/add_day2_remote_nodes.sh
  deploy/operator/ztp/deploy_spoke_cluster.sh
Labels: approved, size/S, lgtm

#4040 NO-ISSUE: Remove unused butane utility
  hack/setup_env.sh
Labels: approved, size/XS, lgtm

#3928 MGMT-10832: Add document for agent upgrade feature
  docs/enhancements/agent-upgrade.md
Labels: approved, size/L, lgtm

#4045 MGMT-10989: Missing condition status in case of unsupported image format
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
Labels: approved, size/S, lgtm

#4048 NO-ISSUE: Fix onprem job
  deploy/podman/configmap.yml
  deploy/podman/okd-configmap.yml
Labels: approved, size/XS, lgtm

#4050 Fix oc-ingress installation method
  Makefile
Labels: approved, size/XS, lgtm

#4053 MGMT-10868 - Fix missing `ASSISTED_PULLSECRET_NAME` in ZTP day-2 scripts
  deploy/operator/common.sh
  deploy/operator/ztp/deploy_spoke_cluster.sh
Labels: approved, size/XS, lgtm
