Repository openshift/assisted-service, pull requests merged in 2022-07, with the labels that each got.

#4051 AGENT-227: Add host configuration support to ephemeral installer client
  Dockerfile.assisted-service
  Dockerfile.assisted-service.ocp
  cmd/agentbasedinstaller/client/main.go
  cmd/agentbasedinstaller/host_config.go
  cmd/agentbasedinstaller/register.go
  internal/controller/controllers/bmh_agent_controller.go
  internal/host/hostutil/host_utils.go
Labels: approved, kind/dependency-change, size/XL, lgtm

#4058 MGMT-10868: Fix duplicate `-latebinding` suffix in ZTP latebinding scripts
  deploy/operator/ztp/add_day2_remote_nodes.sh
  deploy/operator/ztp/infraEnv-latebinding.j2
Labels: approved, size/XS, lgtm

#4059 Fix ui-ingress object to new API
  deploy/ui/ui_ingress.yaml
Labels: approved, size/XS, lgtm

#4047 MGMT-10767: Add subsystem for converged flow
  Makefile
  hack/converged_flow_crds/config.openshift.io_clusteroperators.yaml
  hack/converged_flow_crds/metal3.io_preprovisioningimage.yaml
  hack/converged_flow_crds/metal3.io_provisioning.yaml
  hack/converged_flow_crs/baremetal_operrator.yaml
  hack/converged_flow_crs/metal3.yaml
  hack/converged_flow_crs/provisioning.yaml
  subsystem/kubeapi_test.go
  tools/deploy_assisted_installer_configmap.py
  tools/deploy_converged_flow_requirements.py
  tools/deploy_crd.py
  tools/utils.py
Labels: approved, size/XL, lgtm

#4049 MGMT-10997: Use label filtering when listing Agents via K8s API
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/XS, lgtm

#4044 NO-ISSUE: Use `go:embed` for ignition templates
  cmd/main.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/ignition/templates.go
  internal/ignition/templates/agent.service
  internal/ignition/templates/discovery.ign
  internal/ignition/templates/node.ign
  internal/ignition/templates/okd-overlay.service
  internal/ignition/templates/pre-network-manager-config.service
  internal/ignition/templates/selinux.service
  internal/ignition/templates/systemd-journal-gatewayd.socket
Labels: approved, size/XL, lgtm

#4060 MGMT-11011: use 4.10 index for LSO installation in 4.11
  deploy/operator/setup_lso.sh
Labels: approved, size/S, lgtm

#4064 NO-ISSUE: Adding jhernand to approvers
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#4070 NO-ISSUE: Add @rccrdpccl as approver
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#3970 MGMT-10850: Message for Day2 reboot is misleading
  cmd/main.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostrole_test.go
  internal/host/monitor_test.go
  internal/host/transition_test.go
  internal/host/validations_test.go
Labels: approved, size/L, lgtm

#4056 MGMT-10991: Add forbidden hostnames to cluster_default_config
  api/vendor/github.com/openshift/assisted-service/models/cluster_default_config.go
  internal/bminventory/inventory_v2_handlers.go
  models/cluster_default_config.go
  restapi/embedded_spec.go
  subsystem/cluster_default_config_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster_default_config.go
Labels: approved, size/S, api-review, lgtm

#4075 Revert "MGMT-10850: Message for Day2 reboot is misleading (#3970)"
  cmd/main.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostrole_test.go
  internal/host/monitor_test.go
  internal/host/transition_test.go
  internal/host/validations_test.go
Labels: approved, size/L, lgtm

#4076 [cloud_hotfix_releases] MGMT-11000: Failed to update the cluster when select Integrate with vSphere
  internal/host/statemachine.go
  internal/host/transition_test.go
Labels: approved, size/L, lgtm

#4061 MGMT-11000: Failed to update the cluster when select Integrate with vsphere
  internal/host/statemachine.go
  internal/host/transition_test.go
Labels: approved, size/L, lgtm

#4069 NO-ISSUE: Remove host ID from the `serviceLogicClusterHostImagePullStatus` histogram metric
  internal/host/host.go
  internal/host/host_test.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_metrics_manager_api.go
Labels: approved, size/S, lgtm

#4022 MGMT-10311: aci mutation hook
  api/v1beta1/agentserviceconfig_types.go
  cmd/webadmission/main.go
  config/rbac/role.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  docs/dev/kube-api-webhook.md
  internal/controller/controllers/agentserviceconfig_controller.go
  pkg/webhooks/agentinstall/v1beta1/agent_admission_hook.go
  pkg/webhooks/agentinstall/v1beta1/agent_admission_hook_test.go
  pkg/webhooks/agentinstall/v1beta1/agent_classification_admission_hook.go
  pkg/webhooks/agentinstall/v1beta1/agent_classification_admission_hook_test.go
  pkg/webhooks/agentinstall/v1beta1/infraenv_admission_hook.go
  pkg/webhooks/agentinstall/v1beta1/infraenv_admission_hook_test.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_mutating_hook.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_mutating_hook_test.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook_test.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go
Labels: approved, size/L, api-review, lgtm

#4046 Bug 2076333: Add UnsyncedAgents error in ClusterDeployment and ACI
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  internal/controller/controllers/clusterdeployments_controller.go
  subsystem/kubeapi_test.go
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/agentclusterinstall_types.go
Labels: approved, size/L, api-review, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#4078 MGMT-11026: Use image tag for metrics
  internal/common/common.go
  internal/common/common_test.go
  internal/metrics/metricsManager.go
  internal/metrics/metricsManager_test.go
  internal/metrics/suite_test.go
Labels: approved, size/L, lgtm

#3964 MGMT-10848: Fix double agent unbind when deregistering a cluster
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, size/L, lgtm

#4081 NO-ISSUE: added some logging in setup_lso.sh
  deploy/operator/setup_lso.sh
Labels: approved, size/XS, lgtm

#3682 NO-ISSUE: Some cleanup of `add_day2_remote_nodes.sh`
  deploy/operator/ztp/add_day2_remote_nodes.sh
Labels: approved, size/M, lgtm

#4057 NO-ISSUE: Improve error reporting in ephemeral installer client
  cmd/agentbasedinstaller/client/main.go
  cmd/agentbasedinstaller/host_config.go
  cmd/agentbasedinstaller/register.go
Labels: approved, size/S, lgtm

#4068 MGMT-10921: Ensure that API DNS validation checks for resolution to a master.
  internal/common/test_configuration.go
  internal/host/hostutil/test_utils.go
  internal/host/transition_test.go
  internal/host/validator.go
  internal/network/utils.go
Labels: approved, size/L, lgtm

#3971 Bug 2100857: Fix master's manifest file pattern for oVirt provider
  go.mod
  internal/provider/ovirt/base.go
  internal/provider/ovirt/base_test.go
  internal/provider/ovirt/consts.go
  internal/provider/ovirt/ignition.go
  internal/provider/registry/registry.go
  internal/provider/registry/registry_test.go
Labels: approved, size/L, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#4041 MGMT-10734: Add host states and transitions for reclaim
  api/vendor/github.com/openshift/assisted-service/models/host.go
  internal/host/pool_host_statemachine.go
  internal/host/statemachine.go
  models/host.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/host.go
Labels: approved, size/S, api-review, lgtm

#4089 MGMT-10838: do not reset roles when operators are not updated
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/S, lgtm

#3608 MGMT-7741: New validation: TANG server connectivity check
  api/vendor/github.com/openshift/assisted-service/models/host.go
  api/vendor/github.com/openshift/assisted-service/models/step_type.go
  api/vendor/github.com/openshift/assisted-service/models/tang_connectivity_request.go
  api/vendor/github.com/openshift/assisted-service/models/tang_connectivity_response.go
  internal/bminventory/inventory.go
  internal/cluster/validations/validations.go
  internal/host/host.go
  internal/host/hostcommands/instruction_manager.go
  internal/host/hostcommands/tang_connectivity_check_cmd.go
  internal/host/hostcommands/tang_connectivity_check_cmd_test.go
  internal/host/hostutil/host_utils.go
  internal/host/hostutil/test_utils.go
  internal/host/mock_host_api.go
  internal/host/validations_test.go
  internal/host/validator.go
  internal/network/manifests_generator.go
  models/host.go
  models/step_type.go
  models/tang_connectivity_request.go
  models/tang_connectivity_response.go
  pkg/tang/tang_server.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  subsystem/utils_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/host.go
  vendor/github.com/openshift/assisted-service/models/step_type.go
  vendor/github.com/openshift/assisted-service/models/tang_connectivity_request.go
  vendor/github.com/openshift/assisted-service/models/tang_connectivity_response.go
Labels: approved, size/XL, api-review, lgtm

#3972 OCPRHV-637: Set 'replicas' to 0 in the machinset for the oVirt provider
  internal/provider/ovirt/consts.go
  internal/provider/ovirt/ignition.go
  internal/provider/ovirt/installConfig.go
  internal/provider/registry/registry_test.go
Labels: approved, kind/dependency-change, size/L, api-review, lgtm

#4094 NO-ISSUE: Skip failing static network subsystem test
  subsystem/infra_env_test.go
Labels: approved, size/XS, lgtm

#4083 AGENT-231: Agentbasedinstaller register extra manifests
  cmd/agentbasedinstaller/agentbasedinstaller_suite_test.go
  cmd/agentbasedinstaller/client/main.go
  cmd/agentbasedinstaller/host_config.go
  cmd/agentbasedinstaller/register.go
Labels: approved, size/L, lgtm

#4090 Bug 2104117: BMH stuck “available” after changing a BIOS attribute via the converged workflow
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/L, lgtm, bugzilla/severity-high, bugzilla/valid-bug

#3909 NO-ISSUE: add CPU vs response time panel, unify limits and resources
  dashboards/grafana-dashboard-assisted-installer-resource-utilization.configmap.yaml
Labels: approved, size/L, lgtm

#4100 NO-ISSUE: aws cli isn't available as a package in centos9
  hack/setup_env.sh
Labels: approved, size/S, lgtm

#4104 NO-ISSUE: remove butane usage
  Dockerfile.assisted-service
  config/onprem-iso-config.ign
  config/onprem-iso-fcc.yaml
  hack/generate.sh
  hack/setup_env.sh
Labels: approved, kind/dependency-change, size/L, lgtm, bugzilla/valid-bug

#4109 Update OKD version to latest stable
  data/default_okd_release_images.json
  deploy/podman/okd-configmap.yml
Labels: approved, size/XS, lgtm

#4111 Update postgres path - use PATH instead of absolute location
  hack/start_db.sh
Labels: approved, size/XS, lgtm

#4012 MGMT-9982: Alter ipxe-script endpoint to handle boot order
  client/installer/get_infra_env_presigned_file_url_parameters.go
  client/installer/v2_download_infra_env_files_parameters.go
  docs/user-guide/deploy-on-bare-metal.md
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  restapi/embedded_spec.go
  restapi/operations/installer/get_infra_env_presigned_file_url_parameters.go
  restapi/operations/installer/get_infra_env_presigned_file_url_urlbuilder.go
  restapi/operations/installer/v2_download_infra_env_files_parameters.go
  restapi/operations/installer/v2_download_infra_env_files_urlbuilder.go
  subsystem/infra_env_test.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#4119 MGMT-11098: Pass correct kernel args for multipath
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/S, lgtm

#4116 Minimize CI image - extract unit-tests requirements
  Makefile
  hack/setup_env.sh
Labels: approved, size/S, lgtm

#4123 MGMT-10985: add feature usage for static IP
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/usage/consts.go
Labels: approved, size/L, lgtm

#4125 MGMT-11120: Fix a misleading NMState error log
  pkg/staticnetworkconfig/generator.go
Labels: approved, size/XS, lgtm

#4134 MGMT-11161: fix rootfs access in PSI installations
  deploy/assisted-installer-ingress.yaml
Labels: approved, size/XS, lgtm

#4108 MGMT-10570: check that are master machine found before referencing them
  internal/controller/controllers/bmh_agent_controller.go
Labels: approved, size/S, lgtm

#4079 MGMT-10844: Add virtual interface metrics for SaaS
  internal/common/test_configuration.go
  internal/host/host.go
  internal/host/host_test.go
Labels: approved, size/L, lgtm

#4115 MGMT-10209: Pass in icsp file to be used for 'oc adm release extract'
  Dockerfile.assisted-service
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/installercache/installercache.go
  internal/oc/mock_release.go
  internal/oc/release.go
  internal/oc/release_test.go
  vendor/github.com/openshift/api/operator/v1alpha1/0000_10_config-operator_01_imagecontentsourcepolicy.crd.yaml
  vendor/github.com/openshift/api/operator/v1alpha1/doc.go
  vendor/github.com/openshift/api/operator/v1alpha1/register.go
  vendor/github.com/openshift/api/operator/v1alpha1/types.go
  vendor/github.com/openshift/api/operator/v1alpha1/types_image_content_source_policy.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, kind/dependency-change, size/L, lgtm

#4128 MGMT-11131: Track hosts' registration times
  api/vendor/github.com/openshift/assisted-service/models/host.go
  internal/bminventory/inventory.go
  internal/host/host.go
  internal/host/hostutil/test_utils.go
  models/host.go
  restapi/embedded_spec.go
  subsystem/host_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/host.go
Labels: approved, size/S, api-review, lgtm

#4142 Change importing of Ansible's nth-host function
  deploy/operator/utils.sh
Labels: approved, size/XS, lgtm

#4124 MGMT-8578: Use host's role when generating day2 ignition
  internal/bminventory/inventory.go
  internal/host/hostcommands/api_vip_connectivity_check_cmd.go
Labels: approved, size/XS, lgtm

#4143 MGMT-11161: Add "/boot-artifacts/" route to ingress-tls
  deploy/assisted-installer-ingress-tls.yaml
Labels: approved, size/XS, lgtm

#4136 Bug-2106496: Make sure that updateInventory function does not use the internal DB object.
  internal/host/host.go
Labels: approved, size/XS, lgtm

#3849 MGMT-10445: Add enhancement for automating returning an agent to the infra-env
  docs/enhancements/auto-return-agent-to-infra-env.md
Labels: approved, size/L, lgtm

#4072 MGMT-10973: Enable DNS validations if coredns or keepalived static pod manifests in day-2 connectivity-check ignition
  Makefile
  api/vendor/github.com/openshift/assisted-service/models/api_vip_connectivity_response.go
  api/vendor/github.com/openshift/assisted-service/models/cluster.go
  api/vendor/github.com/openshift/assisted-service/models/host.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_v2_handlers.go
  internal/bminventory/mock_installer_internal.go
  internal/common/common.go
  internal/common/test_configuration.go
  internal/constants/files.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/events/eventstest/events_test_utils.go
  internal/hardware/validator_test.go
  internal/host/host_test.go
  internal/host/hostcommands/dhcp_allocate_cmd_test.go
  internal/host/hostcommands/logs_cmd_test.go
  internal/host/hostrole_test.go
  internal/host/hostutil/test_utils.go
  internal/host/monitor_test.go
  internal/host/transition_test.go
  internal/host/validations_test.go
  internal/host/validator.go
  models/api_vip_connectivity_response.go
  models/cluster.go
  models/host.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  subsystem/day2_cluster_test.go
  subsystem/host_test.go
  subsystem/host_v2_test.go
  subsystem/subsystem_suite_test.go
  subsystem/utils_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/api_vip_connectivity_response.go
  vendor/github.com/openshift/assisted-service/models/cluster.go
  vendor/github.com/openshift/assisted-service/models/host.go
Labels: approved, api-review, lgtm, size/XXL

#4052 NO-ISSUE: Use template function go generate data URL
  internal/ignition/templates.go
  internal/ignition/templates/discovery.ign
  internal/ignition/templates/multipath.conf
Labels: approved, size/S, lgtm

#4126 NO-ISSUE: Return bytes from `executeTemplate` template function
  internal/ignition/templates.go
  internal/ignition/templates/discovery.ign
Labels: approved, size/M, lgtm

#4137 Bug-2106496: Do not perform refresh status on hosts after roles need to
  internal/bminventory/inventory.go
Labels: approved, size/S, lgtm

#4147 MGMT-9354: Define agent labels as variables
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  internal/controller/controllers/clusterdeployments_controller.go
Labels: approved, size/M, lgtm

#4138 MGMT-10866: Compile assisted-service with CentOS stream 9
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, size/S, lgtm

#4152 NO-ISSUE: Fix failing static network config subsystem test
  subsystem/infra_env_test.go
Labels: approved, size/XS, lgtm

#4151 MGMT-11174: Add IPXE boot control flag to infra env in kube API
  api/v1beta1/infraenv_types.go
  config/crd/bases/agent-install.openshift.io_infraenvs.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/infraenv_types.go
Labels: approved, size/L, api-review, lgtm

#4157 MGMT-11124: remove usage of IMAGE_SERVICE_SCHEME/HOST
  deploy/assisted-image-service.yaml
  deploy/podman/configmap.yml
  deploy/podman/okd-configmap.yml
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  tools/deploy_image_service.py
Labels: approved, size/M, lgtm

#4146 MGMT-10840: Change VIP DHCP allocation default to false
  internal/bminventory/inventory.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  subsystem/host_test.go
  subsystem/operators_test.go
  subsystem/utils_test.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm

#4163 MGMT-10007: Remove ovirt-platform object under platform. Change cluster.platform to PlatformType
  api/vendor/github.com/openshift/assisted-service/models/platform.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/provider/baremetal/inventory.go
  internal/provider/base.go
  internal/provider/mock_base_provider.go
  internal/provider/ovirt/consts.go
  internal/provider/ovirt/ignition.go
  internal/provider/ovirt/installConfig.go
  internal/provider/ovirt/inventory.go
  internal/provider/registry/mock_providerregistry.go
  internal/provider/registry/registry.go
  internal/provider/registry/registry_test.go
  internal/provider/vsphere/consts.go
  internal/provider/vsphere/inventory.go
  models/platform.go
  pkg/generator/generator.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/platform.go
Labels: approved, size/XL, api-review, lgtm

#4145 MGMT-10861: When removing/adding api* and apps records, it takes 5-15 minutes till host/cluster status is updated
  internal/host/host.go
  internal/host/host_test.go
Labels: approved, size/M, lgtm

#4131 MGMTBUGSM-412: validate pull secret in kube-api cluster deployment
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/cluster/validations/mock_validations.go
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/common.go
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  internal/controller/controllers/pullsecret_handler.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, lgtm

#4168 OCPBUGSM-46053: bootstrap flag is not cleaned after changing role
  internal/host/common.go
Labels: approved, size/XS, lgtm

#4170 MGMT-11131: Cache results of inventory unmarshalling in connectivity test
  internal/common/common.go
  internal/common/common_test.go
  internal/connectivity/validator.go
Labels: approved, size/M, lgtm

#4084 MGMT-10852: auto-assign races
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/mock_cluster_api.go
  internal/common/db.go
  internal/host/host.go
  internal/host/monitor.go
  subsystem/cluster_test.go
Labels: approved, size/L, lgtm

#4160 MGMT-11174: Add Boot Control Kube API documentation.
  api/v1beta1/infraenv_types.go
  client/installer/get_infra_env_presigned_file_url_parameters.go
  client/installer/v2_download_infra_env_files_parameters.go
  config/crd/bases/agent-install.openshift.io_infraenvs.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
  docs/user-guide/deploy-on-bare-metal.md
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  restapi/embedded_spec.go
  restapi/operations/installer/get_infra_env_presigned_file_url_parameters.go
  restapi/operations/installer/get_infra_env_presigned_file_url_urlbuilder.go
  restapi/operations/installer/v2_download_infra_env_files_parameters.go
  restapi/operations/installer/v2_download_infra_env_files_urlbuilder.go
  subsystem/infra_env_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/api/v1beta1/infraenv_types.go
Labels: approved, size/L, api-review, lgtm

#4121 MGMT-11027: Implement agent upgrade feature
  docs/events.yaml
  internal/bminventory/inventory.go
  internal/common/events/events.go
  internal/common/validations.go
  internal/feature/flags.go
  internal/hardware/validator.go
  internal/host/hostcommands/instruction_manager.go
  internal/host/hostcommands/upgrade_agent_cmd.go
  internal/host/hostcommands/upgrade_agent_cmd_test.go
  internal/host/hostutil/test_utils.go
  internal/host/refresh_status_preprocessor.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/host/validations_test.go
  internal/host/validator.go
  openshift/template.yaml
Labels: approved, size/XL, api-review, lgtm

#4172 MGMT-11027: Add ENABLE_UPGRADE_AGENT env variable
  deploy/podman/configmap.yml
  deploy/podman/okd-configmap.yml
  openshift/template.yaml
Labels: approved, size/XS, lgtm

#4177 MGMT-11316: Remove unused `ovirt-platform` from swagger.yaml
  api/vendor/github.com/openshift/assisted-service/models/ovirt_platform.go
  models/ovirt_platform.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/ovirt_platform.go
Labels: approved, size/M, api-review, lgtm

#3891 MGMT-9506: Remove timestamp from host inventory
  api/vendor/github.com/openshift/assisted-service/models/inventory.go
  internal/common/common.go
  models/inventory.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/inventory.go
Labels: approved, size/M, api-review, lgtm

#4018 MGMT-10790: Always use APIVipDNSName to obtain API address
  internal/bminventory/inventory.go
  internal/common/common.go
  internal/host/hostcommands/api_vip_connectivity_check_cmd.go
  internal/host/validator.go
Labels: approved, size/M, lgtm

#4171 MGMT-11262: Parse `/etc/kubernetes/kubeconfig` in day-2 ignition to disable DNS validations
  internal/host/test_hypershift_kubeconfig
  internal/host/test_regular_kubeconfig
  internal/host/validations_test.go
  internal/host/validator.go
Labels: approved, size/L, lgtm

#4176 NO-ISSUE: Fix set `platform_type` on cluster update.
  internal/bminventory/inventory.go
Labels: approved, size/XS, lgtm

#4173 MGMT-11309: clean up prom metrics to enable meaningful alerts
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/progress_test.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/metrics/metricsManager.go
  internal/metrics/metricsManager_test.go
  internal/metrics/mock_metrics_manager_api.go
Labels: approved, size/L, lgtm

#4162 NO-ISSUE: Remove leftover comment
  internal/host/validator.go
Labels: approved, size/XS, lgtm

#4186 MGMT-11309: clean up unnecessary grafana dashboards
  dashboards/grafana-dashboard-assisted-installer-cluster-overview.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-general-overview.configmap.yaml
  dashboards/grafana-dashboard-assisted-installer-weekly-overview.configmap.yaml
Labels: approved, lgtm, size/XXL

#4155 MGMT-10973 - kube-api imported clusters should be considered imported
  internal/bminventory/inventory.go
  internal/bminventory/inventory_v2_handlers.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, size/S, lgtm

#4097 MGMT-11092: Merge the format and the condition methods in host validation
  internal/host/refresh_status_preprocessor.go
  internal/host/transition_test.go
  internal/host/validations_test.go
  internal/host/validator.go
Labels: approved, lgtm, size/XXL

#4187 MGMT-11153: Add cluster tags support
  api/vendor/github.com/openshift/assisted-service/models/cluster.go
  api/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  api/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/usage/consts.go
  models/cluster.go
  models/cluster_create_params.go
  models/v2_cluster_update_params.go
  pkg/validations/validations.go
  pkg/validations/validations_test.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster.go
  vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
Labels: approved, size/L, api-review, lgtm

#4190 fix python syntax of string comparison
  tools/deploy_route53.py
Labels: approved, size/XS, lgtm

#4195 NO-ISSUE: cloud.md needs a little refresh
  docs/cloud.md
Labels: approved, size/M, lgtm

#4202 Bug 2099929: Detach BMH using dedicated function
  internal/controller/controllers/bmh_agent_controller.go
Labels: approved, size/XS, lgtm, bugzilla/valid-bug, bugzilla/severity-medium

#4139 MGMT-10734: Add more host reclaim states and transitions
  docs/enhancements/auto-return-agent-to-infra-env.md
  internal/host/common.go
  internal/host/host.go
  internal/host/monitor.go
  internal/host/monitor_test.go
  internal/host/statemachine.go
  internal/host/transition.go
  skipper.env
Labels: approved, size/L, lgtm

#4191 MGMT-11362: Set api vip and not dnsname for day2 cluster (transform) for bm platform
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/common/common.go
Labels: approved, size/L, lgtm

#4196 bug-2109637: Agent validations out of sync with the host validation
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/controller/controllers/controller_event_wrapper.go
  internal/events/api/event.go
  internal/events/api/mock_event.go
  internal/events/event.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/validations_test.go
Labels: approved, size/M, lgtm

#4204 NO-ISSUE: Don't log whole ignition for InfraEnv
  internal/bminventory/inventory.go
Labels: approved, size/XS, lgtm

#4205 NO-ISSUE: Fix conversion of disk size for device hints
  internal/host/hostutil/host_utils.go
Labels: approved, size/XS, lgtm

#4201 Bug 2112321: Stop reconcile loop after changing CR inside BMAC
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, bugzilla/severity-unspecified, size/M, lgtm, bugzilla/valid-bug

#4181 MGMT-10960: [Staging] changing machine network cidr while allocate IPs via DHCP checked , show error massage
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/M, lgtm

#4193 MGMT-11251: Update BUNDLE_CHANNELS to ocm-2.7 on master
  Makefile
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/metadata/annotations.yaml
Labels: approved, size/XS, lgtm

#4036 Upgrade base image to centos9 and support both docker on docker and p…
  Dockerfile.assisted-service-build
  Makefile
  README.md
  docs/dev/podman.md
  hack/setup_env.sh
  hack/update_local_image.sh
  hack/utils.sh
  skipper.yaml
  tools/utils.py
Labels: approved, kind/dependency-change, size/L, lgtm
