Repository openshift/assisted-service, pull requests merged in 2023-07, with the labels that each got.

#5278 MGMT-14704: Provide info on custom/vs non custom manifest in manifest endpoint.
  internal/bminventory/inventory.go
  internal/cluster/cluster.go
  internal/constants/manifests.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/manifests/api/interface.go
  internal/manifests/api/mock_manifests_api.go
  internal/manifests/api/mock_manifests_internal.go
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
  internal/manifests/manifests_v2.go
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
  internal/operators/manager.go
  internal/operators/manager_test.go
  subsystem/manifests_test.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#5335 MGMT-14374: update day2 master docs
  docs/user-guide/day2-master/411-healthy.md
Labels: approved, size/XS, lgtm, jira/valid-reference

#5319 MGMT-14852: Allow AutomatedCleaningMode to be set by user
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5336 MGMT-15064: Update is_external API description
  api/vendor/github.com/openshift/assisted-service/models/platform.go
  models/platform.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/platform.go
Labels: approved, size/XS, api-review, lgtm, jira/valid-reference

#5342 MGMT-14726: Ensure that manifest filename does not contain spaces.
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5343 MGMT-14851: Update docs for allowing automatedCleaningMode
  docs/hive-integration/baremetal-agent-controller.md
  docs/hive-integration/kube-api-getting-started.md
Labels: approved, size/S, lgtm, jira/valid-reference

#5334 MGMT-15150: Use same installer binary for all platform types
  internal/bminventory/inventory.go
  internal/ignition/dummy.go
  internal/ignition/ignition.go
  internal/ignition/mock_ignition.go
  internal/installercache/installercache.go
  internal/installercache/installercache_test.go
  internal/oc/mock_release.go
  internal/oc/release.go
  internal/oc/release_test.go
  pkg/generator/generator.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5348 MGMT-14634: Ensure that empty manifest may not be added.
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5349 MGMT-15070: Unable to change machine-network with dual stack
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5338 MGMT-15073:Cluster reset - only system generated manifests to be deleted
  cmd/main.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/mock_cluster_api.go
  internal/cluster/progress_test.go
  internal/cluster/transition_test.go
  internal/manifests/api/interface.go
  internal/manifests/api/mock_manifests_api.go
  internal/manifests/api/mock_manifests_internal.go
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
  internal/operators/odf/validation_test.go
  subsystem/cluster_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5341 [release-ocm-2.7] OCPBUGS-15152: Don't require key encipherment usage for approving CSRs
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/csr_utils.go
Labels: approved, size/L, lgtm, jira/severity-critical, jira/valid-reference

#5347 [release-4.12] MGMT-15150: Use same installer binary for all platform types
  internal/bminventory/inventory.go
  internal/oc/release.go
  internal/oc/release_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5353 No-ISSUE: Revert "MGMT-14634: Ensure that empty manifest may not be added. (#5348)"
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5355 MGMT-15243: Skip any zero size manifests when applying
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5359 OCPBUGS-13310 support setting CPUPartitioningMode with install config…
  internal/installcfg/builder/builder_test.go
  internal/installcfg/installcfg.go
Labels: approved, size/S, lgtm

#5346 [release-4.13] MGMT-15150: Use same installer binary for all platform types
  internal/bminventory/inventory.go
  internal/oc/release.go
  internal/oc/release_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5362 MGMT-14491: Invalid node label returns error 500 instead of 400
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5366 MGMT-15295: Fix bug in list manifests
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5357 MGMT-11456: kube-api should allow user to specify infraenv additional trust bundle
  api/v1beta1/infraenv_types.go
  cmd/agentbasedinstaller/client/main.go
  cmd/agentbasedinstaller/register.go
  config/crd/bases/agent-install.openshift.io_infraenvs.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
  internal/bminventory/inventory.go
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  subsystem/agent_based_installer_client_test.go
  subsystem/kubeapi_test.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/infraenv_types.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#5371 OCPBUGS-16077: Fix DNS validation
  pkg/validations/validations.go
  pkg/validations/validations_test.go
Labels: approved, size/S, lgtm, jira/severity-critical, jira/valid-reference

#5365 MGMT-14923: add OSImageVersion to InfraEnvSpec
  api/v1beta1/infraenv_types.go
  config/crd/bases/agent-install.openshift.io_infraenvs.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  pkg/webhooks/agentinstall/v1beta1/infraenv_admission_hook.go
  pkg/webhooks/agentinstall/v1beta1/infraenv_admission_hook_test.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/infraenv_types.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#5358 MGMT-15215: Allow setting of UI specific data for a cluster
  client/installer/installer_client.go
  client/installer/v2_get_cluster_ui_settings_parameters.go
  client/installer/v2_get_cluster_ui_settings_responses.go
  client/installer/v2_update_cluster_ui_settings_parameters.go
  client/installer/v2_update_cluster_ui_settings_responses.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/common/db.go
  mocks/mock_assisted_service.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_get_cluster_ui_settings.go
  restapi/operations/installer/v2_get_cluster_ui_settings_parameters.go
  restapi/operations/installer/v2_get_cluster_ui_settings_responses.go
  restapi/operations/installer/v2_get_cluster_ui_settings_urlbuilder.go
  restapi/operations/installer/v2_update_cluster_ui_settings.go
  restapi/operations/installer/v2_update_cluster_ui_settings_parameters.go
  restapi/operations/installer/v2_update_cluster_ui_settings_responses.go
  restapi/operations/installer/v2_update_cluster_ui_settings_urlbuilder.go
  subsystem/cluster_v2_test.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#5373 MGMT-14793: Assisted discovery core and root user shell should have proxy environment set
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/ignition/templates/discovery.ign
Labels: approved, size/M, lgtm, jira/valid-reference

#5364 MGMT-15264: Block installation if no custom manifests in OCI cluster
  api/vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  internal/cluster/refresh_status_preprocessor.go
  internal/cluster/validation_id.go
  internal/cluster/validator.go
  internal/cluster/validator_test.go
  models/cluster_validation_id.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
Labels: approved, size/M, api-review, lgtm, jira/valid-reference

#5386 OCPBUGS-13081: Support by-path root device hints
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  internal/host/hostutil/host_utils.go
  internal/ignition/ignition.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5390 NO-ISSUE: Add missing openssl package
  hack/setup_env.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#5392 MGMT-15343: dependabot remove docker
  .github/dependabot.yml
Labels: approved, size/S, lgtm, jira/valid-reference

#5381 MGMT-15047: use installer to deploy on external platform
  internal/installcfg/installcfg.go
  internal/provider/external/ignition.go
  internal/provider/external/ignition_test.go
  internal/provider/external/installConfig.go
  internal/provider/registry/registry_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5378 MGMT-15128: Nutanix: Remove control plane machine set on OCP greater or equal to 4.14
  internal/provider/nutanix/consts.go
  internal/provider/nutanix/ignition.go
  internal/provider/registry/registry_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5376 AGENT-557: Split register into registerCluster and registerInfraEnv
  cmd/agentbasedinstaller/client/main.go
  cmd/agentbasedinstaller/register.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5394 MGMT-15388: Remove unsupported platforms from the supported-platforms endpoint
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/provider/common.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5398 MGMT-11949: MGMT-12278: Update libksba and libxml2
  Dockerfile.assisted-service
  Dockerfile.assisted-service.ocp
Labels: approved, kind/dependency-change, size/XS, lgtm, jira/valid-reference

#5400 MGMT-15389: add feature flag to enable/disable OKD support
  deploy/podman/README.md
  deploy/podman/okd-configmap.yml
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference
