Repository openshift/assisted-service, pull requests merged in 2023-05, with the labels that each got.

#5169 NO-ISSUE: Fixes the UI deployment
  README.md
  deploy/podman/README.md
  docs/enhancements/platform-integration.md
  docs/user-guide/rest-api-getting-started.md
  tools/deploy_ui.py
Labels: approved, size/S, lgtm, ok-to-test, jira/valid-reference

#5145 MGMT-11424: added validations for ignition cert
  internal/bminventory/inventory.go
  pkg/validations/validations.go
  pkg/validations/validations_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#5175 MGMT-14391: Set image references for the release branch so that they correctly point to :ocm-2.8 instead of :latest
  Makefile
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/metadata/annotations.yaml
  deploy/operator/setup_assisted_operator.sh
Labels: approved, size/M, lgtm, jira/valid-reference

#5176 NO-ISSUE: Override the control plane operator image only if explicitly asked to
  deploy/operator/capi/deploy_capi_cluster.sh
Labels: approved, size/S, lgtm, jira/valid-reference

#5178 NO-ISSUE: Check whether is defined
  deploy/operator/capi/deploy_capi_cluster.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#5180 MGMT-14509 return 404 if cluster not found when host try to register
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/S, lgtm

#5179 MGMT-14507: Exposing event headers for scripts
  pkg/app/middleware.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5161 MGMT-14237: Remove all spoke resources when deleting the node
  api/v1beta1/agent_types.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/agent_types.go
Labels: approved, size/XL, api-review, lgtm, jira/valid-reference

#5153 MGMT-14226: Upgrade moby to 20.10.24
  go.mod
  go.sum
  vendor/github.com/moby/moby/pkg/ioutils/fswriters.go
  vendor/github.com/moby/moby/pkg/ioutils/temp_unix.go
  vendor/github.com/moby/moby/pkg/ioutils/temp_windows.go
  vendor/modules.txt
Labels: approved, size/XS, lgtm, jira/valid-reference

#5186 MGMT-14425: Changing event counts behavior
  client/events/v2_list_events_responses.go
  internal/common/common.go
  internal/events/event.go
  internal/events/event_test.go
  internal/events/events_api.go
  restapi/embedded_spec.go
  restapi/operations/events/v2_list_events_responses.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#5191 Podman README-disconnected requires 4.2 and not 3.3
  deploy/podman/README-disconnected.md
Labels: approved, size/XS, lgtm

#5190 MGMT-14370: add OCP 4.14.0-ec.0 images
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#5193 OCPBUGS-13250: Fix disk name in generated HardwareDetails
  internal/ignition/ignition.go
Labels: approved, size/XS, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-low, jira/valid-reference

#5194 MGMT-14530: Changing event message filtering to escape wildcards and not be case sensetive
  internal/events/event.go
  internal/events/event_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5196 MGMT-13977: Disallow single character base domain
  pkg/validations/validations.go
  pkg/validations/validations_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5197 OCPBUGS-13356: Fix 'vendor' root device hint evaluation
  internal/host/hostutil/host_utils.go
Labels: approved, size/XS, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/severity-low, jira/valid-reference

#5199 MGMT-13936: Make unbind work for converged flow BMHs
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5207 OCPBUGS-13310 support setting CPUPartitioningMode with install config…
  internal/installcfg/builder/builder_test.go
  internal/installcfg/installcfg.go
Labels: approved, size/S, lgtm

#5208 MGMT-14526: Allow trailing dot (.) to be appended to domain name
  api/vendor/github.com/openshift/assisted-service/models/domain_resolution_request.go
  models/domain_resolution_request.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/domain_resolution_request.go
Labels: approved, size/XS, api-review, lgtm, jira/valid-reference

#5185 OCPBUGS-13081: Support by-path root device hints
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  internal/host/hostutil/host_utils.go
  internal/ignition/ignition.go
Labels: approved, size/M, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#5213 [release-4.13] OCPBUGS-13083: Support by-path root device hints
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  internal/host/hostutil/host_utils.go
  internal/ignition/ignition.go
Labels: approved, size/M, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#5215 MGMT-14610: Wait for the hostedcontrolplane CR ready status instead of watching the ready status of all pods in the namespace
  deploy/operator/capi/deploy_capi_cluster.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#5214 [release-4.12] OCPBUGS-13529: Support by-path root device hints
  internal/controller/controllers/bmh_agent_controller_test.go
  internal/host/hostutil/host_utils.go
Labels: approved, size/S, lgtm, bugzilla/valid-bug, jira/valid-bug, jira/valid-reference

#5217 NO-ISSUE: Fix install customization doc
  docs/user-guide/install-customization.md
Labels: approved, size/XS, lgtm, jira/valid-reference

#5218 NO-ISSUE: Wait for hostedcontrolplane to be created
  deploy/operator/capi/deploy_capi_cluster.sh
  deploy/operator/utils.sh
Labels: approved, size/S, lgtm, jira/valid-reference

#5223 MGMT-14648: Make "sufficient-masters-count - failed" subsystem test tolerate extra event.
  subsystem/metrics_test.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5198 MGMT-14526: Possible issue with validateNoWildcardDNS resolution validation
  internal/common/test_configuration.go
  internal/host/hostcommands/domain_name_resolution_cmd.go
  internal/host/hostcommands/domain_name_resolution_cmd_test.go
  internal/host/validations_test.go
  internal/host/validator.go
  subsystem/utils_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5209 MGMT-14416: VipDhcpAllocation from update params should take precedence
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validations.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5227 Fix cpu partitioning struct tag/field
  internal/installcfg/builder/builder_test.go
  internal/installcfg/installcfg.go
Labels: approved, size/XS, lgtm

#5230 MGMT-14356: Set 4.13 release image as default
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#5226 MGMT-13643: added MaxLength to additional_trust_bundle
  api/vendor/github.com/openshift/assisted-service/models/infra_env_create_params.go
  api/vendor/github.com/openshift/assisted-service/models/infra_env_update_params.go
  internal/bminventory/inventory_test.go
  models/infra_env_create_params.go
  models/infra_env_update_params.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/infra_env_create_params.go
  vendor/github.com/openshift/assisted-service/models/infra_env_update_params.go
Labels: approved, size/S, api-review, lgtm, jira/valid-reference

#5228 MGMT-14498: Remove the detached annotation when BMH is being deleted
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5240 MGMT-8097: masters schedulable kube-api
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  internal/controller/controllers/clusterdeployments_controller.go
  subsystem/kubeapi_test.go
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/agentclusterinstall_types.go
Labels: approved, size/M, api-review, lgtm, jira/valid-reference

#5246 Docs fix: ensure kubeconfig secret is created with a kubeconfig key.
  docs/hive-integration/import-installed-cluster.md
Labels: approved, size/XS, lgtm

#5252 MGMT-14728: Escape the escape char (\)
  internal/events/event.go
  internal/events/event_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5253 MGMT-14734: Fix failed to update Nutanix provider cluster when on multi architecture
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5254 MGMT-14723: Remove duplicate operator cpu architecture validation
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  internal/featuresupport/common.go
  internal/featuresupport/feature_support_level.go
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features.go
  internal/operators/api/api.go
  internal/operators/api/mock_operator_api.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/lso/ls_operator.go
  internal/operators/lvm/lvm_operator.go
  internal/operators/manager.go
  internal/operators/odf/odf_operator.go
  models/feature_support_level_id.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#5255 [cloud_hotfix_releases] MGMT-14734: Fix failed to update Nutanix provider cluster when on multi architecture
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5239 Delete the spoke BMH before removing the finalizer
  internal/controller/controllers/agent_controller.go
Labels: approved, size/S, lgtm

#5247 MGMT-14306: Update host role validation to accept AutoAssign in Day2
  internal/host/hostutil/host_utils.go
  internal/host/hostutil/host_utils_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5257 NO-ISSUE: fixed misleading error message, the order of the host status was reverse
  internal/host/host.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5244 MGMT-14649: Add feature support for OCI platform
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  internal/bminventory/inventory_test.go
  internal/featuresupport/common.go
  internal/featuresupport/feature_support_level.go
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features.go
  models/feature_support_level_id.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#5259 MGMT-14723: Fix randomly failing subsystem test
  subsystem/feature_support_levels_test.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5256 MGMT-13685: Make sure ingress and api vip are not broadcast address.
  go.mod
  go.sum
  internal/cluster/validator_test.go
  internal/network/machine_network_cidr.go
  vendor/github.com/IBM/netaddr/.travis.yml
  vendor/github.com/IBM/netaddr/LICENSE
  vendor/github.com/IBM/netaddr/README.md
  vendor/github.com/IBM/netaddr/iprange.go
  vendor/github.com/IBM/netaddr/ipset.go
  vendor/github.com/IBM/netaddr/iptree.go
  vendor/github.com/IBM/netaddr/net_utils.go
  vendor/modules.txt
Labels: approved, size/M, lgtm, jira/valid-reference

#5233 MGMT-13997: Issues when using multiple bonds with CIM Assisted Installer
  internal/constants/scripts.go
  internal/constants/scripts_test.go
  internal/constants/test_root/etc/assisted/network/host0/eth0.101.nmconnection
  internal/constants/test_root/etc/assisted/network/host0/eth0.nmconnection
  internal/constants/test_root/etc/assisted/network/host0/mac_interface.ini
  internal/constants/test_root/etc/assisted/network/host1/eth0.nmconnection
  internal/constants/test_root/etc/assisted/network/host1/mac_interface.ini
  internal/constants/test_root/etc/assisted/network/host2/bond0.nmconnection
  internal/constants/test_root/etc/assisted/network/host2/eth0.nmconnection
  internal/constants/test_root/etc/assisted/network/host2/eth1.nmconnection
  internal/constants/test_root/etc/assisted/network/host2/mac_interface.ini
  internal/constants/test_root/etc/assisted/network/host3/bond0.nmconnection
  internal/constants/test_root/etc/assisted/network/host3/eth0.nmconnection
  internal/constants/test_root/etc/assisted/network/host3/mac_interface.ini
  internal/constants/test_root/sys/class/net/enp0s31f6/address
  internal/constants/test_root/sys/class/net/ens1/address
  internal/constants/test_root/sys/class/net/ens2/address
  internal/constants/test_root/sys/class/net/wlp0s20f3/address
Labels: approved, size/XL, lgtm, jira/valid-reference

#5249 MGMT-14582: Set OCI platform behind a capability
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/cluster/validations/validations.go
  pkg/auth/rhsso_authz_handler.go
  pkg/ocm/utils.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5262 MGMT-14781: Make LSO operator to support all CPU architectures
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features.go
Labels: approved, size/S, lgtm, jira/valid-reference
