Repository openshift/assisted-service, pull requests merged in 2023-01, with the labels that each got.

#4830 MGMT-12875: fail gracefully when konnectivity is missing
  internal/controller/controllers/hypershiftagentserviceconfig_controller.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go
Labels: approved, size/S, lgtm

#4843 MGMT-12794: allow to edit ProvisionRequirement post install
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook_test.go
Labels: approved, size/M, lgtm

#4846 NO-ISSUE: improve UpdateMachineCidr
  internal/cluster/cluster.go
  internal/cluster/common.go
  internal/cluster/common_test.go
Labels: approved, size/M, lgtm

#4842 MGMT-13098: add missing networks on V2GetClusterInstallConfig
  internal/bminventory/inventory_v2_handlers.go
  subsystem/cluster_test.go
Labels: approved, size/M, lgtm

#4849 MGMT-13040: Check cluster state before delete
  internal/bminventory/inventory_v2_handlers.go
Labels: approved, size/S, lgtm

#4852 NO-ISSUE: Small numbering issue in doc, amendment
  docs/hive-integration/import-installed-cluster.md
Labels: approved, size/XS, lgtm

#4847 MGMT-13080: [Nutanix] - UMN and machine_network = [] - bootstrap is in insufficient
  internal/bminventory/inventory_test.go
  internal/provider/common.go
Labels: approved, size/M, lgtm

#4817 MGMT-12978: Handle multiple images with the same OCP version
  internal/versions/api_test.go
  internal/versions/versions.go
  internal/versions/versions_test.go
Labels: approved, size/M, lgtm

#4858 MGMT-13132: Respond with 409 when rejecting registration
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  subsystem/cluster_test.go
Labels: approved, size/XS, lgtm

#4860 MGMT-12794: allow to edit ProvisionRequirement post install
  pkg/validating-webhooks/hiveextension/v1beta1/agentclusterinstall_admission_hook.go
  pkg/validating-webhooks/hiveextension/v1beta1/agentclusterinstall_admission_hook_test.go
Labels: approved, size/M, lgtm

#4861 MGMT-13170: Fix nil pointer dereference in validation if host inventory is nil
  internal/host/validations_test.go
  internal/host/validator.go
Labels: approved, size/S, lgtm

#4863 MGMT-13170: Fix nil pointer dereference in validation if host inventory is nil
  internal/host/validations_test.go
  internal/host/validator.go
Labels: approved, size/S, lgtm

#4857 MGMT-12951: change log message from lvmo to lvms
  internal/operators/lvm/lvm_operator.go
  internal/operators/lvm/lvm_operator_test.go
Labels: approved, size/XS, lgtm, ok-to-test

#4798 MGMT-12894: Use the hub release image when determining the ironic agent image
  config/rbac/role.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  docs/hive-integration/README.md
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
Labels: approved, size/L, lgtm

#4845 MGMT-13081: CI to use CentOS8
  ci-images/Dockerfile.base
  ci-images/Dockerfile.lint
  ci-images/Dockerfile.subsystem
  internal/cluster/cluster_test.go
  internal/cluster/transition_test.go
  internal/events/eventstest/events_test_utils.go
  internal/host/host_test.go
  internal/migrations/20211115162400_modify_events_id_test.go
  internal/migrations/20211125182200_change_hosts_pkey_test.go
Labels: approved, size/L, lgtm

#4859 MGMT-12273: Updated logging in PreNetworkConfig script.
  internal/constants/scripts.go
Labels: approved, size/M, lgtm

#4866 MGMT-13081: Re-enable and fix a negative NNState subsystem test
  subsystem/kubeapi_test.go
Labels: approved, size/XS, lgtm

#4796 Add ppc64le & s390x RHCOS ISOs to configmap - rebase
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  internal/versions/api_test.go
  openshift/template.yaml
  subsystem/cluster_v2_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, lgtm, ok-to-test

#4869 MGMT-13192: dualstack SNO cluster fails to complete - getting error
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/S, lgtm

#4567 MGMT-12294: Run subsystem with deterministic openshift version
  subsystem/subsystem_suite_test.go
Labels: approved, size/S, lgtm

#4444 MGMT-11090: Enhancement Doc: Assisted boot-reporter service
  docs/enhancements/boot-status-reporter.md
Labels: approved, size/L, lgtm

#4867 MGMT-10869: Forbid multiple machine networks in single-stack clusters
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validations.go
Labels: approved, size/M, lgtm

#4856 MGMT-12655: Set Agent's installation disk ID only if hints exist
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/M, lgtm

#4879 MGMT-13058: backport vsphere validation in sno to 2.6
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validations.go
Labels: approved, size/M, lgtm

#4865 MGMT-12655: Add installation disk ID to Agent's status
  api/v1beta1/agent_types.go
  config/crd/bases/agent-install.openshift.io_agents.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  subsystem/kubeapi_test.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/agent_types.go
Labels: approved, size/M, api-review, lgtm

#4878 MGMT-13906: inventory: limit allowed Nutanix versions in API
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/M, lgtm

#4873 MGMT-7878: storage config doc using MachineConfig manifest
  docs/user-guide/install-customization.md
Labels: approved, size/M, lgtm

#4793 MGMT-12423: Watch for Agent changes in ClusterDeployment
  internal/controller/controllers/clusterdeployments_controller.go
Labels: approved, size/M, lgtm

#4882 NO-ISSUE: When comparing VIPs, compare only IPs
  internal/controller/controllers/clusterdeployments_controller.go
  internal/network/utils.go
  internal/network/utils_test.go
Labels: approved, size/L, lgtm

#4529 MGMT-12312: Adds node-boot log type
  api/vendor/github.com/openshift/assisted-service/models/logs_type.go
  docs/events.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/common/events/events.go
  models/logs_type.go
  restapi/embedded_spec.go
  restapi/operations/installer/v2_download_cluster_logs_parameters.go
  restapi/operations/installer/v2_upload_logs_parameters.go
  subsystem/cluster_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/logs_type.go
Labels: approved, size/L, api-review, lgtm

#4887 MGMT-11799: change all 'go get' commands
  Dockerfile.assisted-service-debug
  Dockerfile.bundle
  hack/setup_env.sh
Labels: approved, kind/dependency-change, size/S, lgtm

#4890 MGMT-13271: Bump 4.12 release images to use the latest rc version
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm

#4892 MGMT-13240: Create ip hint file in sno installation even if there is only one ip on the host.
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
Labels: approved, size/M, lgtm

#4883 MGMT-12749: BMH: add another fallback location for spoke's root CA
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/M, lgtm

#4864 MGMT-10785: report failing cluster operators
  api/vendor/github.com/openshift/assisted-service/models/completion_params.go
  docs/events.yaml
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/common/events/events.go
  models/completion_params.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/completion_params.go
Labels: approved, size/L, api-review, lgtm

#4897 Setting minikube registry addon to use images from quay.io
  docs/dev/running-test.md
Labels: approved, size/XS, lgtm

#4900 MGMT-12405: Enclose API endpoint with brackets if IPv6 address
  internal/host/hostutil/host_utils.go
  internal/host/hostutil/host_utils_test.go
Labels: approved, size/S, lgtm

#4895 MGMT-13138: Improve messaging over host connectivity.
  internal/host/common.go
  internal/host/mock_transition.go
  internal/host/statemachine.go
  internal/host/transition.go
  internal/host/transition_test.go
  internal/host/validator.go
  subsystem/host_test.go
Labels: approved, size/L, lgtm

#4902 MGMT-13333: Fix iPXE ZTP host connectivity during initramfs
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
Labels: approved, size/XS, lgtm

#4753 bump version for hacking LSO catalog
  deploy/operator/setup_lso.sh
Labels: approved, size/S, lgtm

#4891 MGMT-12970: don't reset auto-assign for irrelevant hosts
  internal/host/monitor.go
  internal/host/monitor_test.go
Labels: approved, size/M, lgtm

#4908 MGMT-13342: Git fails to trust git repository because of mismatch with files
  Dockerfile.assisted-service-build
Labels: approved, kind/dependency-change, size/XS, lgtm

#4912 MGMT-12975: Update 4.12 release image to use GA version
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm

#4916 MGMT-12697: Add `ENABLE_REJECT_UNKNOWN_FIELDS` to SaaS template
  openshift/template.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#4905 MGMT-12405: Enclose API endpoint with brackets if IPv6 address
  internal/host/hostutil/host_utils.go
  internal/host/hostutil/host_utils_test.go
Labels: approved, size/S, lgtm

#4781 MGMT-12915: Day 2 workers cannot resolve api-int.* when attempting to pull ignition
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/constants/files.go
  internal/host/hostutil/host_utils.go
  internal/ignition/ignition.go
Labels: approved, size/L, lgtm

#4903 MGMT-13229: Allow setting Joined to sno installation stages
  internal/host/common.go
  subsystem/kubeapi_test.go
Labels: approved, size/XS, lgtm

#4918 Disable installation on FC disks
  internal/hardware/validator.go
  internal/hardware/validator_test.go
Labels: approved, size/S, lgtm

#4899 MGMT-13305: update the min version for lvm
  internal/bminventory/inventory_test.go
  internal/operators/lvm/config.go
  internal/operators/lvm/lvm_operator.go
  internal/operators/lvm/lvm_operator_test.go
  internal/operators/lvm/manifest.go
  internal/operators/manager.go
Labels: approved, size/S, lgtm, ok-to-test, jira/valid-reference

#4898 MGMT-13327: MGMT-13300: Add support with 4.13 dev preview images
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#4920 remove testing log message
  internal/operators/manager.go
Labels: approved, size/XS, lgtm, ok-to-test

#4924 MGMT-13432: fire and forget kafka messages for event notification
  pkg/stream/event_stream.go
Labels: approved, size/S, lgtm, jira/valid-reference

#4926 NO-ISSUE: explicitly declare timeout
  openshift/template.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#4917 [cloud_hotfix_releases] MGMT-12697: Add ENABLE_REJECT_UNKNOWN_FIELDS to SaaS template
  openshift/template.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#4928 NO-ISSUE: rename event that was erroneusly named as InfraEnv
  internal/events/event.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#4457 MGMT-12193: Add enhancement doc for collecting on-prem data
  docs/enhancements/on-prem-data-collection.md
Labels: approved, size/L, lgtm

#4933 NO-ISSUE: Update 4.13 release images to ec.2
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#4893 MGMT-12996: enhancement for dynamic OCP fetching
  docs/enhancements/README.md
  docs/enhancements/dynamic-fetching-of-openshift-versions.md
Labels: approved, size/L, lgtm

#4931 MGMT-13317: missing transition on refresh when media is disconnected
  internal/host/statemachine.go
  internal/host/transition_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#4934 MGMT-13008: ignition size validation on register infraenv
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#4938 Fix support_level value for 4.12 to fully supported
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/XS, lgtm

#4937 MGMT-12714: Define RAID drive type
  api/vendor/github.com/openshift/assisted-service/models/drive_type.go
  models/drive_type.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/drive_type.go
Labels: approved, size/XS, api-review, lgtm, jira/valid-reference

#4944 NO-ISSUE: add method to access log
  openshift/template.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#4935 Enable converged flow by default
  cmd/main.go
  docs/hive-integration/README.md
Labels: approved, size/XS, lgtm

#4947 MGMT-13493: stream model data instead of DB data
  cmd/main.go
  internal/bminventory/inventory.go
  internal/cluster/common.go
  internal/cluster/common_test.go
  internal/events/event.go
  internal/host/host.go
  internal/host/host_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#4953 NO-ISSUE: skipper error when podman is missing
  skipper.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#4941 Verify detached annotation
  deploy/operator/capi/deploy_capi_cluster.sh
Labels: approved, size/S, lgtm

#4922 OKD: update to OKD 4.12
  data/default_okd_os_images.json
  data/default_okd_release_images.json
  deploy/podman/okd-configmap.yml
Labels: approved, size/S, lgtm

#4543 MGMT-12329: Implements assisted boot reporter and add to ignition
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/cluster/auth.go
  internal/cluster/cluster.go
  internal/ignition/boot-reporter/assisted-boot-reporter.sh
  internal/ignition/dummy.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/ignition/mock_ignition.go
  pkg/generator/generator.go
Labels: approved, kind/dependency-change, size/L, api-review, lgtm

#4952 MGMT-13305: Fix invalid lvms version installed on 4.11
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/hostutil/test_utils.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/cnv/cnv_operator_test.go
  internal/operators/lvm/config.go
  internal/operators/lvm/lvm_operator.go
  internal/operators/lvm/lvm_operator_test.go
  internal/operators/lvm/manifest.go
  internal/operators/manager.go
  internal/operators/manager_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#4945 Add automatic `ShellCheck` linting for `assisted-boot-reporter.sh`
  Dockerfile.assisted-service-build
  Makefile
  ci-images/Dockerfile.lint
Labels: approved, kind/dependency-change, size/XS, lgtm

#4958 MGMT-13462: Fix disk encryption validation pending
  internal/host/validations_test.go
  internal/host/validator.go
Labels: approved, size/S, lgtm, jira/valid-reference

#4959 NO-ISSUE: Add logs to getOLMOperators LVM flow
  internal/bminventory/inventory.go
Labels: approved, size/XS, lgtm, jira/valid-reference
