Repository openshift/assisted-service, pull requests merged in 2023-09, with the labels that each got.

#5372 MGMT-11456: Bugfix - remove redundant code
  internal/bminventory/inventory.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5454 Bump OCP versions: 4.13, 4.11, 4.12
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/L, lgtm

#5463 Bump OCP versions: 4.10
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm

#5460 NO-ISSUE: Add subsystem tests to platform support level
  subsystem/feature_support_levels_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5389 MGMT-15340: Ensure vlan interface names will be <= 15 characters
  internal/constants/scripts.go
  internal/constants/scripts_test.go
  internal/constants/test_root/etc/assisted/network/host4/eth0.2507.nmconnection
  internal/constants/test_root/etc/assisted/network/host4/eth0.nmconnection
  internal/constants/test_root/etc/assisted/network/host4/mac_interface.ini
  internal/constants/test_root/sys/class/net/enp94s0f0np0/address
Labels: approved, size/L, lgtm, jira/valid-reference

#5459 MGMT-15704 Assisted service should create Day2 import CR for hub cluster.
  cmd/main.go
  config/rbac/role.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  go.mod
  internal/controller/controllers/clusterdeployments_controller.go
  pkg/localclusterimport/import_local_cluster.go
  pkg/localclusterimport/import_local_cluster_test.go
  pkg/localclusterimport/local_cluster_import_operations.go
  pkg/localclusterimport/local_cluster_import_operations_mocks.go
Labels: approved, lgtm, size/XXL

#5467 Bump OCP versions: 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm

#5468 OCPBUGS-17992 day2 skip install config overrides
  internal/controller/controllers/clusterdeployments_controller.go
Labels: approved, size/XS, lgtm

#5462 MGMT-15306: Fix UpdateCluster for requests that include VIPS and UMA
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validations.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5472 Bump OCP versions: 4.14
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm

#5474 MGMT-15503: Update operator bundle channel
  Makefile
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/metadata/annotations.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#5482 MGMT-15653: Fix DNS regex validation
  pkg/validations/validations.go
  pkg/validations/validations_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5483 Bump OCP versions: 4.12, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm

#5486 NO-ISSUE: Opening PR for ACM 2.9 Images
  README.md
Labels: approved, size/XS, lgtm, jira/valid-reference

#5490 [release-ocm-2.8] MGMT-15034: MGMT-15047: use installer to deploy on external platform
  internal/installcfg/installcfg.go
  internal/provider/external/external_suite_test.go
  internal/provider/external/ignition.go
  internal/provider/external/installConfig.go
  internal/provider/registry/registry_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5488 NO-ISSUE: update RHTAP deprecated image check
  .tekton/assisted-service-q2vh-pull-request.yaml
  .tekton/assisted-service-q2vh-push.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#5484 MGMT-15704 - Bugfix for local cluster import
  config/rbac/role.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/clusterdeployments_controller.go
  pkg/localclusterimport/import_local_cluster.go
  pkg/localclusterimport/import_local_cluster_test.go
  pkg/localclusterimport/local_cluster_import_operations.go
  pkg/localclusterimport/local_cluster_import_operations_mocks.go
Labels: approved, size/L, lgtm

#5469 MGMT-15732: Add extra flag var for hypershift install
  deploy/operator/capi/deploy_capi_cluster.sh
  deploy/operator/hypershift/deploy_hypershift_cluster.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#5480 MGMT-15715: Allow handling multi-document YAML custom manifests
  docs/user-guide/install-customization.md
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5493 MGMT-15732: Fix unbound variable
  deploy/operator/capi/deploy_capi_cluster.sh
  deploy/operator/hypershift/deploy_hypershift_cluster.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#5445 MGMT-15559: Change detached annotation condition in non-converged flow
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5497 MGMT-15808: change base image to stream9
  Dockerfile.assisted-service
  Dockerfile.assisted-service-build
  ci-images/Dockerfile.base
Labels: approved, kind/dependency-change, size/S, lgtm, jira/valid-reference

#5506 Bump OCP versions: 4.12, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm

#5511 NO-ISSUE: Fix email domain for event uploader
  internal/uploader/auth_utils.go
  internal/uploader/events_uploader.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5512 Bump OCP versions: 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm

#5475 [release-ocm-2.9] MGMT-15501: ClusterServiceVersion for release 2.9 branch references `latest` tag
  Makefile
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/metadata/annotations.yaml
  deploy/operator/setup_assisted_operator.sh
Labels: approved, size/M, lgtm, jira/valid-reference

#5507 [release-ocm-2.7] MGMT-15559: Change detached annotation condition in non-converged flow
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5515 Bump OCP versions: 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm

#5498 MGMT-15598: Add a parameter to manifest list to disable filter
  client/manifests/v2_list_cluster_manifests_parameters.go
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
  restapi/embedded_spec.go
  restapi/operations/manifests/v2_list_cluster_manifests_parameters.go
  restapi/operations/manifests/v2_list_cluster_manifests_urlbuilder.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/client/manifests/v2_list_cluster_manifests_parameters.go
Labels: approved, size/M, api-review, lgtm, jira/valid-reference

#5453 MGMT-15699: Service changes for avoiding MCO reboot
  api/vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
  client/vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
  internal/feature/flags.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/instruction_manager.go
  models/install_cmd_request.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
Labels: approved, size/M, api-review, lgtm, jira/valid-reference

#5514 NO-ISSUE: Add versions file to onprem event upload
  cmd/main.go
  internal/uploader/events_uploader.go
  internal/uploader/events_uploader_test.go
  internal/uploader/uploader.go
Labels: approved, size/M, lgtm, jira/valid-reference
