Repository openshift/assisted-service, pull requests merged in 2023-02, with the labels that each got.

#4925 MGMT-12535: Service implementation for verify-vips
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/mock_cluster_api.go
  internal/cluster/transition_test.go
  internal/cluster/validations/validations.go
  internal/cluster/validator.go
  internal/cluster/validator_test.go
  internal/common/common.go
  internal/common/conversions.go
  internal/common/db.go
  internal/common/test_configuration.go
  internal/host/hostcommands/free_addresses_cmd.go
  internal/host/hostcommands/free_addresses_cmd_test.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/instruction_manager.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/host/hostcommands/verify_vips_cmd.go
  internal/host/hostcommands/verify_vips_cmd_test.go
  internal/network/machine_network_cidr.go
  internal/network/machine_network_cidr_test.go
  subsystem/host_test.go
  subsystem/ipv6_test.go
  subsystem/kubeapi_test.go
  subsystem/utils_test.go
Labels: approved, lgtm, size/XXL, jira/valid-reference

#4930 MGMT-13302: MGMT-13358: Fix multiple OLM - CPU architecture related bugs
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/operators/api/api.go
  internal/operators/api/mock_operator_api.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/cnv/cnv_operator_test.go
  internal/operators/lso/ls_operator.go
  internal/operators/lvm/lvm_operator.go
  internal/operators/lvm/lvm_operator_test.go
  internal/operators/manager.go
  internal/operators/manager_test.go
  internal/operators/mock_operators_api.go
  internal/operators/odf/odf_operator.go
Labels: approved, size/L, lgtm, jira/valid-reference

#4960 Hypershift test delete
  deploy/operator/capi/deploy_capi_cluster.sh
Labels: approved, size/XS, lgtm

#4962 MGMT-13548: add feature-support-level list for 4.13
  internal/featuresupport/support_levels_list.go
Labels: approved, size/M, lgtm, jira/valid-reference

#4967 MGMT-13505: allow to edit ignition url in kube-api
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#4441 ARMOCP-417: enable arm64 for agent installer
  api/vendor/github.com/openshift/assisted-service/models/cluster.go
  api/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  api/vendor/github.com/openshift/assisted-service/models/infra_env.go
  api/vendor/github.com/openshift/assisted-service/models/infra_env_create_params.go
  api/vendor/github.com/openshift/assisted-service/models/os_image.go
  api/vendor/github.com/openshift/assisted-service/models/release_image.go
  internal/bminventory/inventory.go
  internal/common/common.go
  internal/oc/release.go
  internal/versions/osimages.go
  internal/versions/versions.go
  models/cluster.go
  models/cluster_create_params.go
  models/infra_env.go
  models/infra_env_create_params.go
  models/os_image.go
  models/release_image.go
  restapi/embedded_spec.go
  subsystem/cluster_v2_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster.go
  vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  vendor/github.com/openshift/assisted-service/models/infra_env.go
  vendor/github.com/openshift/assisted-service/models/infra_env_create_params.go
  vendor/github.com/openshift/assisted-service/models/os_image.go
  vendor/github.com/openshift/assisted-service/models/release_image.go
Labels: approved, size/M, api-review, lgtm, jira/valid-reference

#4927 MGMT-13203: Create REST points for validation ignore feature.
  api/vendor/github.com/openshift/assisted-service/models/ignored_validations.go
  client/installer/installer_client.go
  client/installer/v2_get_ignored_validations_parameters.go
  client/installer/v2_get_ignored_validations_responses.go
  client/installer/v2_set_ignored_validations_parameters.go
  client/installer/v2_set_ignored_validations_responses.go
  internal/bminventory/inventory_v2_handlers.go
  internal/common/db.go
  internal/common/validations.go
  mocks/mock_assisted_service.go
  models/ignored_validations.go
  pkg/auth/auth_assisted_service_mock_test.go
  pkg/ocm/utils.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_get_ignored_validations.go
  restapi/operations/installer/v2_get_ignored_validations_parameters.go
  restapi/operations/installer/v2_get_ignored_validations_responses.go
  restapi/operations/installer/v2_get_ignored_validations_urlbuilder.go
  restapi/operations/installer/v2_set_ignored_validations.go
  restapi/operations/installer/v2_set_ignored_validations_parameters.go
  restapi/operations/installer/v2_set_ignored_validations_responses.go
  restapi/operations/installer/v2_set_ignored_validations_urlbuilder.go
  subsystem/authz_test.go
  subsystem/wiremock_stubs.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/ignored_validations.go
Labels: approved, size/L, api-review, lgtm, do-not-merge/hold, jira/valid-reference

#4957 MGMT-13526: Fix wrong subscription name on pre-release versions
  internal/bminventory/inventory.go
  internal/common/common_test.go
  internal/common/version.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/lvm/manifest.go
  internal/operators/lvm/manifests_test.go
  internal/operators/manager.go
Labels: approved, size/L, lgtm, jira/severity-critical, jira/valid-reference

#4966 MGMT-13447: Fix LVM subscription name is empty on SNO CNV
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/common_test.go
  internal/common/version.go
  internal/operators/api/api.go
  internal/operators/api/mock_operator_api.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/cnv/cnv_operator_test.go
  internal/operators/lso/ls_operator.go
  internal/operators/lvm/lvm_operator.go
  internal/operators/lvm/lvm_operator_test.go
  internal/operators/lvm/manifest.go
  internal/operators/lvm/manifests_test.go
  internal/operators/manager.go
  internal/operators/manager_test.go
  internal/operators/mock_operators_api.go
  internal/operators/odf/odf_operator.go
  subsystem/operators_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#4970 MGMT-11805: Dedicated `.sh` file for the `docs/change-iso-password.sh` script
  docs/change-iso-password.sh
  docs/set-discovery-password.md
Labels: approved, size/L, lgtm, jira/valid-reference

#4964 NO-ISSUE: Add scenarios to consider to enhancement template
  docs/enhancements/template.md
Labels: approved, size/S, lgtm, jira/valid-reference

#4904 MGMT-12405: Enclose API endpoint with brackets if IPv6 address
  internal/host/hostutil/host_utils.go
  internal/host/hostutil/host_utils_test.go
Labels: approved, size/S, lgtm

#4971 MGMT-11805: `docs/change-iso-password.sh` lint
  Makefile
  docs/change-iso-password.sh
Labels: approved, size/M, lgtm, jira/valid-reference

#4974 NO-ISSUE: added ENABLE_ORG_TENANCY to deploy-test target
  Makefile
Labels: approved, size/XS, lgtm, jira/valid-reference

#4973 MGMT-13487: handle day2 cluster authz
  internal/bminventory/inventory_test.go
  pkg/auth/rhsso_authz_handler.go
  pkg/auth/rhsso_authz_handler_test.go
  subsystem/authz_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#4939 MGMT-13471: SNO installation with OCP 4.13 lacks proper dnsmasq configuration
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#4961 MGMT-13292: Add the installed version on the monitored operator response
  api/vendor/github.com/openshift/assisted-service/models/monitored_operator.go
  api/vendor/github.com/openshift/assisted-service/models/operator_monitor_report.go
  internal/operators/handler/handler.go
  internal/operators/handler/handler_test.go
  models/monitored_operator.go
  models/operator_monitor_report.go
  restapi/embedded_spec.go
  skipper.env
  subsystem/cluster_test.go
  subsystem/operators_test.go
  subsystem/utils_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/monitored_operator.go
  vendor/github.com/openshift/assisted-service/models/operator_monitor_report.go
Labels: approved, size/M, api-review, lgtm, jira/valid-reference

#4983 MGMT-13682: Gather host logs on failure in day2 flow
  internal/host/hostcommands/instruction_manager.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#4826 MGMT-13045: Enhancement document for node labeling
  docs/enhancements/support-node-labeling.md
Labels: approved, size/L, lgtm

#4982 NO-ISSUE: Add logs to supported-platforms
  internal/bminventory/inventory.go
Labels: approved, size/S, lgtm, jira/valid-reference

#4980 MGMT-13657: Don't wait for console if it is disabled - ACM 2.6
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#4972 MGMT-13549: Day1 implementation for K8S node labels
  api/v1beta1/agent_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/agent-install.openshift.io_agents.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  subsystem/kubeapi_test.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/agent_types.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#4976 MGMT-13620: Make worker to use custom MCP if it was set as part of the host DB record
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#4988 MGMT-13711: it takes the assisted-service few minutes to notice that the cluster installation is completed
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/cluster/cluster.go
  internal/cluster/progress_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#4975 MGMT-13454: Group Host and boot logs to a single tarball
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/mock_cluster_api.go
  restapi/embedded_spec.go
  restapi/operations/installer/v2_download_cluster_logs_parameters.go
  subsystem/cluster_test.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#4981 MGMT-13664: Don't wait for console if it is disabled - ACM 2.7
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#4985 MGMT-13708: allow overriding image service image in subscription
  deploy/operator/setup_assisted_operator.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#4907 MGMT-13204: Implement skipping of host and cluster validations
  api/vendor/github.com/openshift/assisted-service/models/cluster.go
  docs/events.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/refresh_status_preprocessor.go
  internal/cluster/refresh_status_preprocessor_test.go
  internal/common/common.go
  internal/common/events/events.go
  internal/common/validations.go
  internal/host/refresh_status_preprocessor.go
  internal/host/refresh_status_preprocessor_test.go
  internal/usage/consts.go
  models/cluster.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster.go
Labels: approved, size/XL, api-review, lgtm

#4993 MGMT-13521: Clearer messaging when non-overlapping-subnets validation is pending.
  internal/host/validations_test.go
  internal/host/validator.go
Labels: approved, size/M, lgtm, jira/valid-reference

#4994 MGMT-13274: Update time-synced-between-host-and-service message to remove bad advice
  internal/host/validator.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#4995 Add registry config for ironic agent image
  deploy/operator/setup_assisted_operator.sh
Labels: approved, size/XS, lgtm

#4998 Use the correct env var for the hub release image mirror
  deploy/operator/setup_assisted_operator.sh
Labels: approved, size/XS, lgtm

#5001 MGMT-13210: Revert "Increase timeout waiting for image-service"
  tools/wait_for_assisted_service.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#5002 MGMT-13646: bump to 4.12.3 live-iso images
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#4996 MGMT-13374: support Nutanix in kube-api
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  docs/hive-integration/platform-selection.md
  internal/controller/controllers/clusterdeployments_controller.go
  subsystem/kubeapi_test.go
  subsystem/utils_test.go
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/agentclusterinstall_types.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/zz_generated.deepcopy.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#5007 Make get_image_without_tag work when registry has a port
  deploy/operator/utils.sh
Labels: approved, size/XS, lgtm

#5005 add 4.13 multi ec.3 dev preview images
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, ok-to-test

#5008 MGMT-12956: Add feature IDs for ppc64le and s390x
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level.go
  internal/bminventory/inventory.go
  internal/common/common.go
  internal/featuresupport/support_levels_list.go
  internal/usage/consts.go
  models/feature_support_level.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/feature_support_level.go
Labels: approved, size/M, api-review, lgtm, ok-to-test, jira/valid-reference
