Repository openshift/assisted-service, pull requests merged in 2023-11, with the labels that each got.

#5589 MGMT-15680: Adds InfraEnv ctrl watch for pull secret changes
  internal/controller/controllers/infraenv_controller.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5649 MGMT-15271: Add the boot command line to the host inventory
  api/vendor/github.com/openshift/assisted-service/models/boot.go
  client/vendor/github.com/openshift/assisted-service/models/boot.go
  models/boot.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/boot.go
Labels: approved, size/XS, api-review, lgtm, ok-to-test, jira/valid-reference

#5565 OCPBUGS-19823: Ignore hostPrefix validation for plugins other than OVN/SDN
  internal/cluster/validator.go
  internal/cluster/validator_test.go
Labels: approved, size/M, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#5638 MGMT-15405: Add a URL to infraenv to show download link from static network config
  api/v1beta1/infraenv_types.go
  config/crd/bases/agent-install.openshift.io_infraenvs.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/infraenv_types.go
Labels: approved, size/M, api-review, lgtm, jira/valid-reference

#5661 NO-ISSUE: Bump OCP versions: 4.14, 4.12
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#5659 MGMT-16052: Fix cluster HighAvailabilityMode nil pointer in update flow
  internal/provider/common.go
  subsystem/kubeapi_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5651 MGMT-16114: Update 4.14 release image to use GA version
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#5667 MGMT-16151: change default envoy sidecar timeout value
  openshift/template.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#5524 MGMT-15814: Ensure that preparation timeout gives some clues
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  api/vendor/github.com/openshift/assisted-service/models/cluster.go
  api/vendor/github.com/openshift/assisted-service/models/last_installation_preparation.go
  client/vendor/github.com/openshift/assisted-service/models/cluster.go
  client/vendor/github.com/openshift/assisted-service/models/last_installation_preparation.go
  docs/events.yaml
  docs/hive-integration/kube-api-conditions.md
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/conditions.go
  internal/cluster/progress_test.go
  internal/cluster/refresh_status_preprocessor_test.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/common/db.go
  internal/common/events/events.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/events/eventstest/events_test_utils.go
  internal/host/refresh_status_preprocessor_test.go
  models/cluster.go
  models/last_installation_preparation.go
  restapi/embedded_spec.go
  subsystem/ams_subscriptions_test.go
  subsystem/cluster_test.go
  subsystem/manifests_test.go
  subsystem/utils_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/agentclusterinstall_types.go
  vendor/github.com/openshift/assisted-service/models/cluster.go
  vendor/github.com/openshift/assisted-service/models/last_installation_preparation.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#5521 MGMT-15878: Ensure that hosts emit event showing why preparation failed.
  cmd/graphstatemachine/main.go
  cmd/main.go
  internal/cluster/statemachine.go
  internal/host/common.go
  internal/host/config.go
  internal/host/mock_transition.go
  internal/host/monitor.go
  internal/host/statemachine.go
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#5669 MGMT-16164: Install 4.14 redhat-operators catalog for LSO
  deploy/operator/setup_lso.sh
Labels: approved, size/S, lgtm, jira/valid-reference

#5668 NO-JIRA: Allow the command in wait_for_cmd_amount to receive arguments to pass to the inner function
  deploy/operator/utils.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#5648 MGMT-15902: Trigger reboots for node event when day2 node moves to done
  cmd/main.go
  go.mod
  internal/controller/controllers/agent_controller.go
  internal/oc/debug.go
  internal/oc/debug_test.go
  internal/spoke_k8s_client/factory.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5670 NO-ISSUE: Fix for error in wait_for_cmd_amount function
  deploy/operator/utils.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#5592 AGENT-723: Use json.Marshal to correctly process vSphere credentials
  internal/bminventory/inventory_test.go
  internal/installcfg/builder/builder.go
  internal/installcfg/builder/builder_test.go
  internal/installcfg/installcfg.go
  internal/provider/external/installConfig.go
  internal/provider/none/installConfig.go
  internal/provider/registry/registry_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5673 MGMT-16077: Add OCP 4.15.0-ec.1 images
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#5658 MGMT-16061: changing dnsmasq configuration for sno in order to meet single ip installation flow for ibu
  internal/network/manifests_generator.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5671 MGMT-16151: allow CORS HEAD for s3 presigned url
  pkg/app/middleware.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5681 NO-ISSUE: Bump OCP versions: 4.11, 4.12, 4.13
  data/default_os_images.json
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#5680 NO-JIRA: Enable skip mco reboot functionality only if openshift version is 4.15 and higher
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  client/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  internal/featuresupport/feature_support_level.go
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features_misc.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  models/feature_support_level_id.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
Labels: approved, size/M, api-review, lgtm, jira/valid-reference

#5575 MGMT-15971: Create ManagedCluster CR so that the hub will show up as "Ready" in MCE
  cmd/main.go
  pkg/localclusterimport/import_local_cluster.go
  pkg/localclusterimport/import_local_cluster_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5672 Add missing scheme to `ServiceMonitor`
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
Labels: approved, size/XS, lgtm, jira/valid-bug, jira/valid-reference

#5665 MGMT-15271: Append kargs to installer for s390x
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/L, lgtm, ok-to-test, jira/valid-reference

#5690 NO-ISSUE: InfraEnv controller code cleanup
  internal/controller/controllers/infraenv_controller.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5693 NO-ISSUE: BMH and Agent controllers code cleanup
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/bmh_agent_controller.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5696 NO-ISSUE: Remove unused functions
  internal/cluster/validations/validations.go
  internal/common/image_status.go
  internal/common/test_configuration.go
  internal/host/hostutil/host_utils.go
  internal/host/matchers.go
  internal/ignition/ignition.go
  internal/network/machine_network_cidr.go
  pkg/log/context.go
  pkg/requestid/requestid.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5697 NO-ISSUE: dependabot optimize
  .github/dependabot.yml
Labels: approved, size/L, lgtm, ok-to-test, jira/valid-reference

#5695 NO-ISSUE: Inventory code cleanups
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5536 HOSTEDCP-999: Setup CI for disconnected ipv6 CAPI
  deploy/operator/capi/deploy_capi_cluster.sh
Labels: approved, size/M, lgtm, jira/valid-reference

#5711 NO-ISSUE: Upgrade debug image to latest delve
  Dockerfile.assisted-service-debug
Labels: approved, kind/dependency-change, size/XS, lgtm, jira/valid-reference

#5714 NO-ISSUE: Bump OCP versions: 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#5715 NO-ISSUE: Cluster code cleanups
  internal/cluster/cluster.go
  internal/cluster/registrar.go
  internal/cluster/statemachine.go
  internal/cluster/validator.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5675 AGENT-740: Include baremetal host BMC fields in install-config override
  internal/installcfg/builder/builder_test.go
  internal/installcfg/installcfg.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5713 HOSTEDCP-999: Minor fixes for disconnected CAPI CI
  deploy/operator/capi/deploy_capi_cluster.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#5699 MGMT-16001: Sanitize reclaim agent daemonset name
  internal/controller/controllers/agent_reclaimer.go
  internal/controller/controllers/agent_reclaimer_test.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5722 NO-ISSUE: Bump OCP versions: 4.14, 4.13, 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#5721 HOSTEDCP-999: Missed service-cidr for capi ipv6 CI test
  deploy/operator/capi/deploy_capi_cluster.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#5501 MGMT-14810: Remove API and Ingress VIP
  cmd/agentbasedinstaller/register.go
  deploy/operator/ztp/agentClusterInstall.j2
  docs/hive-integration/crds/agentClusterInstall-with-installconfig-overrides.yaml
  docs/hive-integration/crds/agentClusterInstall.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/common.go
  internal/cluster/progress_test.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/cluster/validations/validations.go
  internal/common/common.go
  internal/common/common_test.go
  internal/common/test_configuration.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/common.go
  internal/dns/dns.go
  internal/dns/dns_test.go
  internal/installcfg/builder/builder_test.go
  internal/migrations/20221031103047_multiple_vips.go
  internal/migrations/20221031103047_multiple_vips_test.go
  internal/network/dhcp_param_file.go
  internal/network/dhcp_param_file_test.go
  internal/network/machine_network_cidr_test.go
  internal/network/utils.go
  internal/network/utils_test.go
  internal/operators/odf/validation_test.go
  internal/provider/baremetal/installConfig.go
  internal/provider/nutanix/installConfig.go
  internal/provider/registry/registry_test.go
  internal/provider/vsphere/installConfig.go
  subsystem/agent_based_installer_client_test.go
  subsystem/cluster_test.go
  subsystem/ipv6_test.go
  subsystem/kubeapi_test.go
  subsystem/utils_test.go
Labels: approved, api-review, lgtm, size/XXL, jira/valid-reference

#5728 MGMT-16273: Allow installing on iSCSI disks on OCI
  cmd/main.go
  internal/hardware/mock_validator.go
  internal/hardware/validator.go
  internal/hardware/validator_test.go
  internal/host/host_test.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/transition_test.go
  internal/host/validations_test.go
  internal/host/validator.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5741 HOSTEDCP-999: Fix incorrect check for CAPI image in ci
  deploy/operator/capi/deploy_capi_cluster.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#5734 MGMT-15972: Remove Swagger definition for api_vip and ingress_vip
  api/vendor/github.com/openshift/assisted-service/models/cluster.go
  api/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  api/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
  client/vendor/github.com/openshift/assisted-service/models/cluster.go
  client/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  client/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
  internal/migrations/20231010101010_drop_cluster_api_vip_and_ingress_vip.go
  internal/migrations/20231010101010_drop_cluster_api_vip_and_ingress_vip_test.go
  internal/migrations/migrations.go
  models/cluster.go
  models/cluster_create_params.go
  models/v2_cluster_update_params.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/assisted-service/models/cluster.go
  vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#5736 MGMT-16235: Ensure that agent controller will watch for changes to ignition endpoint token.
  internal/controller/controllers/agent_controller.go
  subsystem/kubeapi_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5738 MGMT-15690: Add support for external platform
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  api/vendor/github.com/openshift/assisted-service/models/platform.go
  api/vendor/github.com/openshift/assisted-service/models/platform_external.go
  api/vendor/github.com/openshift/assisted-service/models/platform_type.go
  client/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  client/vendor/github.com/openshift/assisted-service/models/platform.go
  client/vendor/github.com/openshift/assisted-service/models/platform_external.go
  client/vendor/github.com/openshift/assisted-service/models/platform_type.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validations.go
  internal/common/common.go
  internal/common/conversions.go
  internal/featuresupport/feature_support_level.go
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features_networking.go
  internal/featuresupport/features_platforms.go
  internal/provider/external/base.go
  internal/provider/external/external.go
  internal/provider/external/inventory.go
  internal/provider/external/oci.go
  internal/provider/platform.go
  internal/provider/platform_validations.go
  internal/provider/registry/registry.go
  internal/provider/registry/registry_test.go
  models/feature_support_level_id.go
  models/platform.go
  models/platform_external.go
  models/platform_type.go
  pkg/ocm/utils.go
  restapi/embedded_spec.go
  restapi/operations/installer/get_supported_features_parameters.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  vendor/github.com/openshift/assisted-service/models/platform.go
  vendor/github.com/openshift/assisted-service/models/platform_external.go
  vendor/github.com/openshift/assisted-service/models/platform_type.go
Labels: approved, api-review, lgtm, size/XXL, jira/valid-reference

#5747 HOSTEDCP-999: Fix incorrect ICSP for CAPI CI
  deploy/operator/capi/deploy_capi_cluster.sh
Labels: approved, size/S, lgtm, jira/valid-reference
