Repository openshift/assisted-service, pull requests merged in 2023-03, with the labels that each got.

#5010 NO-ISSUE: customize the image path for disk creation
  deploy/operator/README.md
  deploy/operator/libvirt_disks.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#5012 Revert "MGMT-13471: SNO installation with OCP 4.13 lacks proper dnsmasq configuration
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#4906 MGMT-13313: bminventory: throw Bad Request error on arm64 Nutanix clusters
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validations.go
Labels: approved, size/M, lgtm

#5011 NO-ISSUE: remove mocks from coverage
  Makefile
  hack/display_cover_profile.sh
Labels: approved, size/S, lgtm, jira/valid-reference

#5009 MGMT-13398 omit BMH secret from day2 spoke worker
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/M, lgtm

#5000 MGMT-13780: Write a feature-support-level enhancement doc
  docs/enhancements/add-feature-support-by-generic-attributes.md
Labels: approved, size/L, lgtm, jira/valid-reference

#5021 Fix invalid character in feature-support enhancement
  docs/enhancements/add-feature-support-by-generic-attributes.md
Labels: approved, size/XS, lgtm

#4989 MGMT-13659: Design a feature support mechanism that supports different feature-support criteria
  api/vendor/github.com/openshift/assisted-service/models/architecture_support_level_id.go
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level.go
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  api/vendor/github.com/openshift/assisted-service/models/feature_support_levels.go
  api/vendor/github.com/openshift/assisted-service/models/support_level.go
  api/vendor/github.com/openshift/assisted-service/models/support_levels.go
  client/installer/get_supported_architectures_parameters.go
  client/installer/get_supported_architectures_responses.go
  client/installer/get_supported_features_parameters.go
  client/installer/get_supported_features_responses.go
  client/installer/installer_client.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/cluster/validations/validations.go
  internal/common/common_test.go
  internal/common/version.go
  internal/featuresupport/architectures.go
  internal/featuresupport/feature_support_level.go
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features.go
  internal/featuresupport/support_levels_list.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/lvm/lvm_operator.go
  internal/operators/lvm/manifest.go
  internal/operators/manager.go
  internal/provider/baremetal/installConfig.go
  internal/provider/common.go
  internal/provider/nutanix/installConfig.go
  internal/provider/vsphere/installConfig.go
  mocks/mock_assisted_service.go
  models/architecture_support_level_id.go
  models/feature_support_level.go
  models/feature_support_level_id.go
  models/feature_support_levels.go
  models/support_level.go
  models/support_levels.go
  pkg/auth/auth_assisted_service_mock_test.go
  pkg/auth/rhsso_authz_handler_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/get_supported_architectures.go
  restapi/operations/installer/get_supported_architectures_parameters.go
  restapi/operations/installer/get_supported_architectures_responses.go
  restapi/operations/installer/get_supported_architectures_urlbuilder.go
  restapi/operations/installer/get_supported_features.go
  restapi/operations/installer/get_supported_features_parameters.go
  restapi/operations/installer/get_supported_features_responses.go
  restapi/operations/installer/get_supported_features_urlbuilder.go
  restapi/operations/installer/v2_import_cluster.go
  restapi/operations/installer/v2_list_feature_support_levels.go
  subsystem/feature_support_levels_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/architecture_support_level_id.go
  vendor/github.com/openshift/assisted-service/models/feature_support_level.go
  vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  vendor/github.com/openshift/assisted-service/models/feature_support_levels.go
  vendor/github.com/openshift/assisted-service/models/support_level.go
  vendor/github.com/openshift/assisted-service/models/support_levels.go
Labels: approved, api-review, lgtm, size/XXL, jira/valid-reference

#4948 Allow removing the agent when BMH is deleted
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/L, lgtm

#5013 MGMT-13859: notify when creating cluster and resources
  Makefile
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/common.go
  internal/cluster/common_test.go
  internal/cluster/progress_test.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/common/db.go
  internal/common/testing/dummies.go
  internal/controller/controllers/controller_event_wrapper_test.go
  internal/events/event.go
  internal/events/event_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/transition.go
  internal/host/transition_test.go
  internal/operators/odf/validation_test.go
  internal/stream/mock_notification_stream.go
  internal/stream/mock_writer.go
  internal/stream/notification_stream.go
  internal/stream/notification_stream_test.go
  internal/stream/writer_factory.go
  internal/uploader/events_uploader_test.go
  pkg/kafka/json_writer.go
  pkg/kafka/json_writer_test.go
  pkg/kafka/mock_json_writer.go
  pkg/stream/event_stream_test.go
  pkg/stream/mock_event_stream.go
Labels: approved, lgtm, size/XXL, jira/valid-reference

#5029 MGMT-13913: Fix empty features list when calling GET v2/support-levels/features
  internal/featuresupport/feature_support_level.go
  internal/featuresupport/feature_support_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5030 MGMT-13904: MGMT-13914: Add missing feature IDs.
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  internal/featuresupport/feature_support_level.go
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features.go
  models/feature_support_level_id.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#5024 MGMT-13903: Select IP inside machine CIDR for BMH
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5031 MGMT-13925: Handle missing inspection URL
  internal/controller/controllers/bmo_utils.go
  internal/controller/controllers/bmo_utils_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5036 MGMT-13947: Revert assisted boot reporter service
  Makefile
  api/vendor/github.com/openshift/assisted-service/models/logs_type.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_v2_handlers.go
  internal/ignition/boot-reporter/assisted-boot-reporter.sh
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  models/logs_type.go
  restapi/embedded_spec.go
  restapi/operations/installer/v2_upload_logs_parameters.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/logs_type.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#5037 MGMT-13957: deny requests with query parameters matching node-boot.
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#5027 ACM-4127: Cache release images even if there is no matching OS image
  cmd/main.go
  go.mod
  go.sum
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/versions/api_test.go
  internal/versions/versions.go
  internal/versions/versions_test.go
  vendor/golang.org/x/sync/semaphore/semaphore.go
  vendor/golang.org/x/sync/singleflight/singleflight.go
  vendor/modules.txt
Labels: approved, size/L, lgtm, jira/valid-reference

#5022 MGMT-13941: Don't wait for console if disabled
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/mock_cluster_api.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5040 MGMT-13963: Don't wait for console if disabled
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/mock_cluster_api.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5032 NO-ISSUE: remove the full ignition from log
  internal/ignition/ignition.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5015 MGMT-13596: Add PATCH to the Manifests API
  api/vendor/github.com/openshift/assisted-service/models/update_manifest_params.go
  client/manifests/manifests_client.go
  client/manifests/v2_update_cluster_manifest_parameters.go
  client/manifests/v2_update_cluster_manifest_responses.go
  internal/manifests/api/mock_manifests_api.go
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
  internal/manifests/manifests_v2.go
  mocks/mock_manifests.go
  models/update_manifest_params.go
  pkg/s3wrapper/client.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/manifests/v2_update_cluster_manifest.go
  restapi/operations/manifests/v2_update_cluster_manifest_parameters.go
  restapi/operations/manifests/v2_update_cluster_manifest_responses.go
  restapi/operations/manifests/v2_update_cluster_manifest_urlbuilder.go
  subsystem/manifests_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/update_manifest_params.go
Labels: approved, size/XL, api-review, lgtm, jira/valid-reference

#5033 Sparing the redirect for official k8s registery
  Dockerfile.assisted-service-build
  ci-images/Dockerfile.code-generation
  ci-images/Dockerfile.subsystem
Labels: approved, kind/dependency-change, size/XS, lgtm

#5035 MGMT-13947: Revert assisted boot reporter service
  Makefile
  api/vendor/github.com/openshift/assisted-service/models/logs_type.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_v2_handlers.go
  internal/ignition/boot-reporter/assisted-boot-reporter.sh
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  models/logs_type.go
  restapi/embedded_spec.go
  restapi/operations/installer/v2_upload_logs_parameters.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/logs_type.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#5039 MGMT-13958: MGMT-13862: Return bed request on wrong feature-feature or feature-architecture combination
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/featuresupport/architecture_support_level.go
  internal/featuresupport/feature_support_level.go
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features.go
  models/feature_support_level_id.go
  restapi/embedded_spec.go
  subsystem/feature_support_levels_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
Labels: approved, api-review, lgtm, size/XXL, jira/valid-reference

#5023 MGMT-13520: filter out unnecessary validations for unbound host
  internal/host/pool_host_statemachine.go
  internal/host/transition_test.go
  internal/host/validations_test.go
  internal/host/validator.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5048 MGMT-12486: Add ENABLE_DATA_COLLECTION environment variable to template.yaml
  openshift/template.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#5050 manifests: Add a shebang to NM dispatcher script
  internal/network/manifests_generator.go
Labels: approved, size/XS, lgtm

#5056 MGMT-14042: Disable data collection for SaaS by default
  openshift/template.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#5020 OKD: bump to latest stable release
  data/default_okd_release_images.json
  deploy/podman/okd-configmap.yml
Labels: approved, size/XS, lgtm

#5055 Cleanup BMAC logging
  internal/controller/controllers/bmh_agent_controller.go
Labels: approved, size/L, lgtm

#5053 MGMT-14000: Document support-level new API
  docs/user-guide/support-level.md
Labels: approved, size/M, lgtm, jira/valid-reference

#5061 MGMT-14075: Fix register cluster won't fail when creating cluster with P or Z architectures on 4.12
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/featuresupport/feature_support_level.go
  internal/featuresupport/feature_support_test.go
  subsystem/feature_support_levels_test.go
Labels: approved, size/L, lgtm, jira/severity-critical, jira/valid-reference

#5063 actually use the ENABLE_DATA_COLLECTION parameter
  openshift/template.yaml
Labels: approved, size/XS, lgtm

#5054 MGMT-14040: Add log that shows event upload is running
  internal/cluster/cluster.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5069 Remove README section about the assisted-service live iso
  README.md
Labels: approved, size/XS, lgtm

#5070 MGMT-14073: Fix logging for event uploader
  internal/uploader/events_uploader.go
  internal/uploader/events_uploader_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#4987 MGMT-13308: Adding events pagination
  client/events/v2_list_events_parameters.go
  client/events/v2_list_events_responses.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/transition_test.go
  internal/common/common.go
  internal/controller/controllers/controller_event_wrapper.go
  internal/controller/controllers/controller_event_wrapper_test.go
  internal/events/api/event.go
  internal/events/api/mock_event.go
  internal/events/event.go
  internal/events/event_test.go
  internal/events/events_api.go
  internal/host/host_test.go
  internal/uploader/events_uploader.go
  internal/uploader/events_uploader_test.go
  pkg/app/middleware.go
  pkg/auth/rhsso_authz_handler_test.go
  restapi/embedded_spec.go
  restapi/operations/events/v2_list_events_parameters.go
  restapi/operations/events/v2_list_events_responses.go
  restapi/operations/events/v2_list_events_urlbuilder.go
  subsystem/events_test.go
  subsystem/kubeapi_test.go
  swagger.yaml
Labels: approved, api-review, lgtm, size/XXL, jira/valid-reference

#5072 MGMT-14110: MGMT-14109: Set P and Z architectures support label as tech-preview on 4.12
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/featuresupport/architectures.go
  internal/featuresupport/feature_support_test.go
  internal/provider/common.go
  subsystem/feature_support_levels_test.go
Labels: approved, size/L, lgtm, jira/severity-critical, jira/valid-reference

#5067 MGMT-14096: Don't wait for console if disabled - ACM 2.6
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/mock_cluster_api.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5078 ACM-4530: Update cluster-baremetal-operator to 4.13 branch
  go.mod
  go.sum
  vendor/github.com/openshift/cluster-baremetal-operator/api/v1alpha1/provisioning_types.go
  vendor/github.com/openshift/cluster-baremetal-operator/provisioning/baremetal_config.go
  vendor/github.com/openshift/cluster-baremetal-operator/provisioning/baremetal_pod.go
  vendor/github.com/openshift/cluster-baremetal-operator/provisioning/image_cache.go
  vendor/github.com/openshift/cluster-baremetal-operator/provisioning/utils.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/headermap.go
  vendor/golang.org/x/net/http2/hpack/encode.go
  vendor/golang.org/x/net/http2/hpack/static_table.go
  vendor/golang.org/x/net/http2/hpack/tables.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/term/terminal.go
  vendor/golang.org/x/text/unicode/bidi/trieval.go
  vendor/k8s.io/apimachinery/pkg/apis/meta/v1/micro_time_proto.go
  vendor/k8s.io/client-go/plugin/pkg/client/auth/exec/exec.go
  vendor/k8s.io/client-go/rest/request.go
  vendor/k8s.io/client-go/tools/clientcmd/auth_loaders.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/k8s.io/client-go/transport/config.go
  vendor/k8s.io/client-go/transport/transport.go
  vendor/modules.txt
Labels: approved, size/M, lgtm, jira/valid-reference

#5066 MGMT-14074: Reload NM config after creation
  internal/constants/scripts.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5087 MGMT-14074: Don't run `nmcli` if not available
  internal/constants/scripts.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5084 MGMT-14136: Reload NM config after creation - ACM 2.7
  internal/constants/scripts.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5088 MGMT-14133: Fix P/Z support level allows cluster with OLM operators.
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/featuresupport/feature_support_level.go
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features.go
  subsystem/feature_support_levels_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5090 MGMT-14150: Update install-config to support multi vSphere data-centers
  internal/installcfg/installcfg.go
  internal/provider/registry/registry_test.go
  internal/provider/vsphere/consts.go
  internal/provider/vsphere/installConfig.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5044 MGMT-13793: Do not remove host default configuration unless network configuration is provided for it
  internal/constants/scripts.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5099 Add a function for setting annotations
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/common.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller.go
  internal/controller/controllers/preprovisioningimage_controller.go
Labels: approved, size/M, lgtm
