Repository openshift/assisted-service, pull requests merged in 2023-04, with the labels that each got.

#5095 MGMT-13916: Update enhancement doc for ignoring validations feature
  docs/enhancements/api-for-ignoring-validations.md
Labels: approved, size/S, lgtm, jira/valid-reference

#4943 NO-ISSUE: Wrap VIP update in the DB with transaction
  internal/network/utils.go
Labels: approved, size/M, lgtm, jira/valid-reference

#4946 NO-ISSUE: Make DB transaction terminate function only when error
  internal/cluster/common.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5077 MGMT-13918: Modify ignored validation should not be possible post-install
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5074 MGMT-14026: Add validation to ensure ignored validation ID exists
  internal/bminventory/inventory_v2_handlers.go
  internal/common/common.go
  subsystem/authz_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5101 MGMT-14190: Allow installing Power architecture with CMN and MinimalISO
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/featuresupport/architecture_support_level.go
  internal/featuresupport/architectures.go
  internal/featuresupport/common.go
  internal/featuresupport/feature_support_level.go
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features.go
  internal/provider/common.go
  models/feature_support_level_id.go
  restapi/embedded_spec.go
  subsystem/feature_support_levels_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
Labels: approved, size/XL, api-review, lgtm, jira/valid-reference

#5071 MGMT-13846: Reject UserManagedNetworking true when cluster VIPs are set
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validations.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5098 MGMT-14161: removing "multi" cpu architecture for infra envs
  api/vendor/github.com/openshift/assisted-service/models/infra_env.go
  api/vendor/github.com/openshift/assisted-service/models/infra_env_create_params.go
  models/infra_env.go
  models/infra_env_create_params.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/infra_env.go
  vendor/github.com/openshift/assisted-service/models/infra_env_create_params.go
Labels: approved, size/XS, api-review, lgtm, jira/severity-critical, jira/valid-reference

#5104 MGMT-14195: Use clusterIdMatcher instead of gomock.Any() in inventory_test
  internal/bminventory/inventory_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5106 MGMT-13178: Adding order parameter and changing the count of events by severity to apply only after the filtering
  client/events/v2_list_events_parameters.go
  internal/common/common.go
  internal/events/event.go
  internal/events/event_test.go
  internal/events/events_api.go
  restapi/embedded_spec.go
  restapi/operations/events/v2_list_events_parameters.go
  restapi/operations/events/v2_list_events_urlbuilder.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#5103 MGMT-12301: refactor the progress bar to use state machine
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostutil/update_host.go
  internal/host/hostutil/update_host_test.go
  internal/host/mock_transition.go
  internal/host/statemachine.go
  internal/host/transition.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5117 MGMT-14283: Ignored validations - validation id "all" does not work
  internal/bminventory/inventory_v2_handlers.go
  subsystem/authz_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5109 Add private SELinux label for volume mount content
  docs/change-iso-password.sh
Labels: approved, size/XS, lgtm, ok-to-test

#5119 MGMT-14242: MGMT-14017: MGMT-14239: MGMT-14300: Fix multiple bugs (feature support and feature usage)
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/featuresupport/common.go
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5102 MGMT-10977: Validate DNS server connection
  api/vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  cmd/main.go
  internal/common/test_configuration.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostcommands/domain_name_resolution_cmd.go
  internal/host/hostcommands/domain_name_resolution_cmd_test.go
  internal/host/hostcommands/instruction_manager.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/host/hostrole_test.go
  internal/host/monitor_test.go
  internal/host/refresh_status_preprocessor.go
  internal/host/refresh_status_preprocessor_test.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/host/validations_test.go
  internal/host/validator.go
  internal/versions/versions.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  subsystem/utils_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/host_validation_id.go
Labels: approved, size/XL, api-review, lgtm

#5122 MGMT-14266: Fix unclear message when creating a P/Z cluster with OCP version 4.10
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5127 MGMT-14239: Enable UMN as default for Power architecture (ppc64le)
  internal/provider/common.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5123 MGMT-14317: Fix events filtering
  internal/events/event.go
  internal/events/event_test.go
Labels: approved, size/XL, lgtm, jira/valid-reference

#5120 MGMT-13083: limit the size of release binaries
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/installercache/installercache.go
  internal/installercache/installercache_test.go
  internal/installercache/priorityqueue.go
  internal/oc/mock_release.go
  internal/oc/release.go
  openshift/template.yaml
  pkg/generator/generator.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5130 Use contexts in spoke client
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go
  internal/spoke_k8s_client/mock_spoke_k8s_client.go
  internal/spoke_k8s_client/spoke_k8s_client.go
Labels: approved, size/L, lgtm

#5132 MGMT-14338: add missing stream notifications
  cmd/main.go
  internal/bminventory/inventory.go
  internal/usage/manager.go
  internal/usage/manager_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5137 Improve inaccurate ODF validation message
  internal/operators/odf/odf_operator.go
  internal/operators/odf/odf_operator_test.go
Labels: approved, size/XS, lgtm

#5136 MGMT-14298: Set full ISO as default for Z architecture
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  subsystem/cluster_v2_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5140 MGMT-14246: Cache must-gather images by architecture
  data/default_must_gather_versions.json
  internal/versions/versions.go
  internal/versions/versions_test.go
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#5139 MGMT-14395: Day-2 domain name resolution step shouldn't include release image domain
  internal/host/hostcommands/domain_name_resolution_cmd.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5146 NO-ISSUE: Fix grammar mistakes
  docs/dev/testing.md
Labels: approved, size/XS, lgtm, jira/valid-reference

#5141 MGMT-14396: Get correct path for binary from mirror
  internal/installercache/installercache.go
  internal/installercache/installercache_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5086 MGMT-14137: Create test flow for ZTP for node labeling and avoiding reboot for custom role
  deploy/operator/README.md
  deploy/operator/ztp/add-remote-nodes-playbook.yaml
  deploy/operator/ztp/agentClusterInstall.j2
  deploy/operator/ztp/assisted-installer-crds-playbook.yaml
  deploy/operator/ztp/baremetalHost.j2
  deploy/operator/ztp/deploy_spoke_cluster.sh
Labels: approved, size/M, lgtm, jira/valid-reference

#5150 MGMT-14108: add readiness probe initialDelaySeconds for service and image-service
  deploy/assisted-image-service.yaml
  deploy/assisted-service.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#5155 NO ISSUE: use literal for cpu limits, to enable nulliable value
  openshift/template.yaml
Labels: approved, size/XS, lgtm

#5147 MGMT-14315: Allow to install P and Z architectures with Single Node Openshift on 4.13
  internal/bminventory/inventory_test.go
  internal/featuresupport/feature_support_level.go
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features.go
  subsystem/feature_support_levels_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5158 MGMT-13955: Add known issue regarding ignoring disk size validations
  docs/enhancements/api-for-ignoring-validations.md
Labels: approved, size/XS, lgtm, jira/valid-reference

#5160 MGMT-14449: change creation time for hosts to one minute ago instead of now
  internal/host/hostutil/test_utils.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5166 NO-ISSUE Remove Sarah from approvers
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm

#5167 MGMT-14462: Allow to deploy assisted-service with all available images
  Makefile
Labels: approved, size/XS, lgtm, jira/valid-reference
