Repository openshift/assisted-service, pull requests merged in 2023-08, with the labels that each got.

#5404 MGMT-15389: add feature flag to enable/disable OKD support (#5400)
  deploy/podman/README.md
  deploy/podman/okd-configmap.yml
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#5403 Bump OCP versions: 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  internal/controller/controllers/common.go
  openshift/template.yaml
Labels: approved, size/S, lgtm

#5399 MGMT-15335: Fix missing transition when trying to update to not supported platform
  internal/host/statemachine.go
  internal/host/transition_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5407 Bump OCP versions: 4.11
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm

#5408 [release-ocm-2.8] MGMT-15413: Use same installer binary for all platform types (#5334)
  internal/bminventory/inventory.go
  internal/ignition/dummy.go
  internal/ignition/ignition.go
  internal/ignition/mock_ignition.go
  internal/installercache/installercache.go
  internal/installercache/installercache_test.go
  internal/oc/mock_release.go
  internal/oc/release.go
  internal/oc/release_test.go
  pkg/generator/generator.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5409 Bump OCP versions: 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm

#5411 MGMT-15424: parametrize envoy configmap name
  openshift/template.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#5333 RHTAPBUGS-318: Fetch tag in RHTAP build
  .tekton/assisted-service-q2vh-pull-request.yaml
  .tekton/assisted-service-q2vh-push.yaml
Labels: approved, size/XS, lgtm, ok-to-test, jira/valid-reference

#5414 MGMT-15489: Don't set detached for BMHs without infraenv label
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5412 MGMT-15423: Change the user message when host is not compatible with platform type
  internal/host/validator.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5406 MGMT-15382: Ensure inspection is disabled on day-2 spoke node BMHs
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5421 Bump OCP versions: 4.13, 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm

#5425 NO-ISSUE: Extend waiting time to test DB container to be ready
  internal/common/common_unitest_db.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5416 MGMT-15491: Validate vSphere disk.EnableUUID ignoring cluster platform
  internal/host/host_test.go
  internal/host/hostrole_test.go
  internal/host/monitor_test.go
  internal/host/transition_test.go
  internal/host/validations_test.go
  internal/host/validator.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5382 MGMT-15356: Ensure filenames are distinct between openshift and manifest directories.
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5422 MGMT-15525: Use go 1.18 when setting up environment
  hack/setup_env.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#5431 Bump OCP versions: 4.11, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm

#5432 Bump OCP versions: 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm

#5430 MGMT-14881 - return a valid error when no disks has been found
  internal/host/validations_test.go
  internal/host/validator.go
Labels: approved, size/L, api-review, lgtm

#5439 OCPBUGS-17992 day2 skip install config overrides
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, size/L, lgtm

#5444 Add BMH annotation keys to docs
  docs/hive-integration/README.md
Labels: approved, size/XS, lgtm

#5442 Fix setup_env.sh failure handling
  hack/setup_env.sh
Labels: approved, size/M, lgtm

#5447 Revert "Fix DNS validation (#5371)"
  pkg/validations/validations.go
  pkg/validations/validations_test.go
Labels: approved, size/S, lgtm

#5450 MGMT-15100: Remove unused feature-support-levels API endpoint
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level.go
  api/vendor/github.com/openshift/assisted-service/models/feature_support_levels.go
  client/installer/installer_client.go
  client/installer/v2_list_feature_support_levels_parameters.go
  client/installer/v2_list_feature_support_levels_responses.go
  client/vendor/github.com/openshift/assisted-service/models/feature_support_level.go
  client/vendor/github.com/openshift/assisted-service/models/feature_support_levels.go
  internal/bminventory/inventory_v2_handlers.go
  internal/featuresupport/support_levels_list.go
  mocks/mock_assisted_service.go
  models/feature_support_level.go
  models/feature_support_levels.go
  pkg/auth/auth_assisted_service_mock_test.go
  pkg/auth/rhsso_authz_handler_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_list_feature_support_levels.go
  restapi/operations/installer/v2_list_feature_support_levels_parameters.go
  restapi/operations/installer/v2_list_feature_support_levels_responses.go
  restapi/operations/installer/v2_list_feature_support_levels_urlbuilder.go
  subsystem/feature_support_levels_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/client/installer/installer_client.go
  vendor/github.com/openshift/assisted-service/client/installer/v2_list_feature_support_levels_parameters.go
  vendor/github.com/openshift/assisted-service/client/installer/v2_list_feature_support_levels_responses.go
  vendor/github.com/openshift/assisted-service/models/feature_support_level.go
  vendor/github.com/openshift/assisted-service/models/feature_support_levels.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#5438 AGENT-694: Support external platform type for agent installer
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  api/hiveextension/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  docs/hive-integration/platform-selection.md
  internal/controller/controllers/clusterdeployments_controller.go
  subsystem/kubeapi_test.go
  subsystem/utils_test.go
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/agentclusterinstall_types.go
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/zz_generated.deepcopy.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#5452 Bump OCP versions: 4.11, 4.12, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm
