Repository openshift/assisted-service, pull requests merged in 2023-12, with the labels that each got.

#5751 MGMT-16312 fix update host ignition for unbound host
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5344 MGMT-14605: Gather more data for hypershift tests
  deploy/operator/gather.sh
Labels: approved, size/S, lgtm, jira/valid-reference

#5762 MGMT-16250: Propagate OS_IMAGES var in operator deploy
  deploy/operator/common.sh
  deploy/operator/setup_assisted_operator.sh
Labels: approved, size/S, lgtm, jira/valid-reference

#5765 MGMT-16303: Disable skip MCO reboot for architecture s390x
  internal/featuresupport/features_misc.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5773 NO-ISSUE: update OS_IMAGES filter to 4.11
  deploy/operator/common.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#5768 NO-ISSUE: add build tags option
  Makefile
Labels: approved, size/XS, lgtm, jira/valid-reference

#5757 OCPBUGS-24319: fix: allow LVMS to be installed for MultiNode / HA Configurations in OpenShift >=4.15.0
  internal/operators/lvm/config.go
  internal/operators/lvm/lvm_operator.go
  internal/operators/lvm/lvm_operator_test.go
Labels: approved, size/M, lgtm, jira/valid-bug, jira/valid-reference

#5740 MGMT-16289: Add configuration variable and cluster attribute defining if soft timeouts feature is enabled
  cmd/main.go
Labels: approved, size/XS, api-review, lgtm, jira/valid-reference

#5790 NO-ISSUE: fix golangci-lint failing to be pulled
  Dockerfile.assisted-service-build
  ci-images/Dockerfile.lint
Labels: approved, kind/dependency-change, size/XS, lgtm, jira/valid-reference

#5796 NO-ISSUE: Bump OCP versions: 4.15
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#5789 [release-ocm-2.9] MGMT-16312: changing dnsmasq configuration for sno in order to meet single ip installation flow for ibu
  internal/network/manifests_generator.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5795 MGMT-16157 Remove recover usage from DB transactions
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/cluster/registrar.go
  internal/cluster/transition.go
  internal/operators/handler/handler.go
Labels: approved, lgtm, size/XXL, jira/valid-reference

#5802 [release-ocm-2.8] MGMT-16370: fix golangci-lint failing to be pulled
  Dockerfile.assisted-service-build
  ci-images/Dockerfile.lint
Labels: approved, kind/dependency-change, size/XS, lgtm, jira/valid-reference

#5806 MGMT-16157 move db transactions to new format
  internal/bminventory/inventory.go
  internal/cluster/registrar.go
  internal/events/event.go
  internal/host/host_test.go
  internal/host/transition_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5799 MGMT-14159: Use imageDigestSources in install-config instead of ICSP
  internal/installcfg/builder/builder.go
  internal/installcfg/builder/builder_test.go
  internal/installcfg/installcfg.go
  internal/provider/registry/registry_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5808 NO-ISSUE: Bump OCP versions: 4.13, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#5813 NO-ISSUE: Bump OCP versions: 4.11
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#5780 MGMT-16355: API changes for soft timeouts
  api/vendor/github.com/openshift/assisted-service/models/cluster_finalizing_progress.go
  api/vendor/github.com/openshift/assisted-service/models/cluster_progress_info.go
  api/vendor/github.com/openshift/assisted-service/models/finalizing_stage.go
  client/installer/installer_client.go
  client/installer/v2_update_cluster_finalizing_progress_parameters.go
  client/installer/v2_update_cluster_finalizing_progress_responses.go
  client/vendor/github.com/openshift/assisted-service/models/cluster_finalizing_progress.go
  client/vendor/github.com/openshift/assisted-service/models/cluster_progress_info.go
  client/vendor/github.com/openshift/assisted-service/models/finalizing_stage.go
  internal/bminventory/inventory_v2_handlers.go
  mocks/mock_assisted_service.go
  models/cluster_finalizing_progress.go
  models/cluster_progress_info.go
  models/finalizing_stage.go
  pkg/auth/auth_assisted_service_mock_test.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/installer/v2_update_cluster_finalizing_progress.go
  restapi/operations/installer/v2_update_cluster_finalizing_progress_parameters.go
  restapi/operations/installer/v2_update_cluster_finalizing_progress_responses.go
  restapi/operations/installer/v2_update_cluster_finalizing_progress_urlbuilder.go
  swagger.yaml
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/assisted-service/client/installer/installer_client.go
  vendor/github.com/openshift/assisted-service/client/installer/v2_update_cluster_finalizing_progress_parameters.go
  vendor/github.com/openshift/assisted-service/client/installer/v2_update_cluster_finalizing_progress_responses.go
  vendor/github.com/openshift/assisted-service/models/cluster_finalizing_progress.go
  vendor/github.com/openshift/assisted-service/models/cluster_progress_info.go
  vendor/github.com/openshift/assisted-service/models/finalizing_stage.go
Labels: approved, size/M, api-review, lgtm, jira/valid-reference

#5777 MGMT-14633: Include manifest information in the log download
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  subsystem/cluster_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5801 MGMT-15886: Fix domain validation
  pkg/validations/validations.go
  pkg/validations/validations_test.go
  subsystem/cluster_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5816 MGMT-16047: Compare normalized infraenv and preprov image architectures
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5824 NO-ISSUE: Bump OCP versions: 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#5805 MGMT-16420: enable latest lso for 4.15 ztp
  deploy/operator/setup_lso.sh
Labels: approved, size/S, lgtm, jira/valid-reference

#5829 MGMT-16428: create migration from oci to external platform type
  internal/migrations/20231219105000_update_oci_to_external_platform_type.go
  internal/migrations/20231219105000_update_oci_to_external_platform_type_test.go
  internal/migrations/migrations.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5825 MGMT-16373: KubeAPI - Ensure that ISO type is full-iso when cpuarchitecture is S390x
  internal/controller/controllers/infraenv_controller.go
  subsystem/kubeapi_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5822 MGMT-16414: When trying to create cluster with s390x architecture, an error occurs that stops cluster creation
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features_misc.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5837 MGMT-16332: fix issue validating pre-release versions
  internal/operators/lvm/lvm_operator.go
  internal/operators/lvm/lvm_operator_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5832 HOSTEDCP-999: Fix images used for disconnected CAPI test
  deploy/operator/capi/deploy_capi_cluster.sh
Labels: approved, size/S, lgtm, jira/valid-reference

#5836 MGMT-16216: Bump requests package, change to a pure python builder
  Dockerfile.assisted-service
  dev-requirements.txt
Labels: approved, kind/dependency-change, size/XS, lgtm, jira/valid-reference

#5817 MGMT-16404: Add soft timeouts capability to host stage timeouts
  api/vendor/github.com/openshift/assisted-service/models/host_progress_info.go
  client/vendor/github.com/openshift/assisted-service/models/host_progress_info.go
  cmd/main.go
  docs/events.yaml
  internal/common/events/events.go
  internal/host/common.go
  internal/host/conditions.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostrole_test.go
  internal/host/hostutil/update_host.go
  internal/host/mock_transition.go
  internal/host/monitor_test.go
  internal/host/refresh_status_preprocessor.go
  internal/host/refresh_status_preprocessor_test.go
  internal/host/statemachine.go
  internal/host/transition.go
  internal/host/transition_test.go
  internal/host/validations_test.go
  internal/host/validator.go
  models/host_progress_info.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/host_progress_info.go
Labels: approved, size/XL, api-review, lgtm, jira/valid-reference

#5844 OCPBUGS-25434: handle NMStateConfig deletion
  internal/controller/controllers/infraenv_controller.go
  subsystem/kubeapi_test.go
Labels: approved, size/M, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#5843 MGMT-16452: Change MCE subscription to use the default channel
  Makefile
  data/default_ocp_mce_version_map.json
  deploy/assisted-service-configmap.yaml
  deploy/podman/configmap.yml
  internal/operators/builder.go
  internal/operators/manager_test.go
  internal/operators/mce/config.go
  internal/operators/mce/manifest.go
  internal/operators/mce/manifest_test.go
  internal/operators/mce/mce_operator.go
  internal/operators/mce/mce_operator_test.go
  openshift/template.yaml
  tools/deploy_assisted_installer_configmap.py
Labels: approved, size/L, lgtm, jira/valid-reference
