Repository openshift/assisted-service, pull requests merged in 2023-10, with the labels that each got.

#5499 NO-ISSUE: fix docker-ce-cli package missing
  Dockerfile.assisted-service-build
Labels: approved, kind/dependency-change, size/XS, lgtm, jira/valid-reference

#5525 Bump OCP versions: 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm

#5522 NO-ISSUE: fail upload if response is not 2XX
  internal/uploader/events_uploader.go
  internal/uploader/events_uploader_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5528 Bump OCP versions: 4.12, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm

#5529 MGMT-15762 - fix odf validation failing where is one small disk
  .gitignore
  internal/operators/odf/odf_operator.go
  internal/operators/odf/odf_operator_test.go
  internal/operators/odf/validation_test.go
  internal/operators/odf/validations.go
Labels: approved, size/L, lgtm

#5523 MGMT-14409: generate short image URL
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/gencrypto/token.go
  internal/imageservice/url_test.go
  internal/imageservice/urls.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5537 Bump OCP versions: 4.13, 4.11
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm

#5477 MGMT-15738: Support for E2E test, make sure we have an infraenv for adding a node to the local cluster.
  deploy/operator/utils.sh
  deploy/operator/ztp/add-worker-nodes-to-local-cluster-playbook.yaml
  deploy/operator/ztp/add_day2_local_cluster_nodes.sh
  deploy/operator/ztp/add_day2_remote_nodes.sh
  deploy/operator/ztp/assisted-installer-crds-playbook.yaml
  deploy/operator/ztp/infraEnv.j2
Labels: approved, size/L, lgtm, jira/valid-reference

#5479 MGMT-15507: Set restricted list of approvers for protected release-ocm-2.9 branch
  OWNERS_ALIASES
Labels: approved, size/S, lgtm, jira/valid-reference

#5542 MGMT-15507: Add adriengentil as approver in ocm-2.9
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#5543 MGMT-15947: Add assisted images service short URL routes
  deploy/assisted-installer-ingress-tls.yaml
  deploy/assisted-installer-ingress.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#5544 MGMT-15950: Fix DNS wilcard domain validation
  pkg/validations/validations.go
  pkg/validations/validations_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5546 Bump OCP versions: 4.12, 4.14, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm

#5560 NO-ISSUE: Set default ENABLE_SKIP_MCO_REBOOT: false
  internal/feature/flags.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5559 Bump OCP versions: 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm

#5550 NO-ISSUE: add console output for ztp CI jobs
  deploy/operator/ztp/baremetalHost.j2
  deploy/operator/ztp/infraEnv-latebinding.j2
  deploy/operator/ztp/infraEnv.j2
Labels: approved, size/XS, lgtm, jira/valid-reference

#5554 [release-ocm-2.8] MGMT-15306: Fix UpdateCluster for requests that include VIPS and UMA
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validations.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5562 NO-ISSUE: Fix console output in ZTP jobs
  deploy/operator/ztp/baremetalHost.j2
  deploy/operator/ztp/infraEnv-latebinding.j2
  deploy/operator/ztp/infraEnv.j2
Labels: approved, size/XS, lgtm, jira/valid-reference

#5549 MGMT-15572 Hold installation when reconcile-pause annotation is set on cluster deployment
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/agentclusterinstall_types.go
Labels: approved, size/L, lgtm

#5566 Revert "NO-ISSUE: Set default ENABLE_SKIP_MCO_REBOOT: false (#5560)"
  internal/feature/flags.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5552 MGMT-15949: fix missing ImageSetRef validation
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5572 MGMT-15997: use kubectl 1.28.2
  hack/setup_env.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#5569 MGMT-15980: added missing Create op to infraenvs Webhook
  internal/controller/controllers/agentserviceconfig_controller.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5587 NO-ISSUE: Disable local cluster import in ACM 2.9
  cmd/main.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5586 Bump OCP versions: 4.11, 4.12, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm

#5579 MGMT-16001: Sanitize reclaim daemonset name
  internal/controller/controllers/agent_reclaimer.go
  internal/controller/controllers/agent_reclaimer_test.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5593 Bump OCP versions: 4.13, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm

#5595 NO-ISSUE: fixing dependabot issues
  .github/dependabot.yml
Labels: approved, size/M, lgtm, jira/valid-reference

#5558 Add skopeo to OCP build
  Dockerfile.assisted-service.ocp
Labels: approved, kind/dependency-change, size/XS, lgtm

#5591 MGMT-15902: Add event that shows the number of reboots for a node before completing installation
  docs/events.yaml
  internal/common/events/events.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#5614 MGMT-16045: mitigate CVE-2023-44487
  api/go.mod
  api/go.sum
  api/vendor/golang.org/x/net/http2/Dockerfile
  api/vendor/golang.org/x/net/http2/Makefile
  api/vendor/golang.org/x/net/http2/server.go
  api/vendor/golang.org/x/net/http2/transport.go
  api/vendor/golang.org/x/text/unicode/norm/trie.go
  api/vendor/modules.txt
Labels: approved, size/S, api-review, lgtm, jira/valid-reference

#5615 Bump OCP versions: 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm

#5618 Revert "MGMT-15997: use kubectl 1.28.2"
  hack/setup_env.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#5628 MGMT-16037: fix messaging errors on big clusters
  internal/bminventory/inventory.go
  internal/cluster/common.go
  internal/stream/utils.go
  internal/stream/utils_test.go
  internal/usage/manager.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5633 Bump OCP versions: 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm

#5634 MGMT-15684: Return appropriate HTTP error code for invalid manifest file path
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5635 MGMT-15683: Ensure that manifest filename has valid name part
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5613 MGMT-16061: changing dnsmasq configuration for sno in order to meet single ip installation flow for ibu
  internal/network/manifests_generator.go
Labels: approved, size/S, lgtm, jira/valid-reference
