Repository openshift/assisted-service, pull requests merged in 2023-06, with the labels that each got.

#5203 MGMT-12186: Add MCE operator plugin
  api/vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  api/vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  internal/cluster/cluster_test.go
  internal/cluster/statemachine.go
  internal/cluster/validation_id.go
  internal/featuresupport/feature_support_level.go
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/operators/builder.go
  internal/operators/manager_test.go
  internal/operators/mce/config.go
  internal/operators/mce/manifest.go
  internal/operators/mce/manifest_test.go
  internal/operators/mce/mce_operator.go
  internal/operators/mce/mce_operator_test.go
  internal/operators/mce/mce_suite_test.go
  internal/operators/mce/test_utils.go
  models/cluster_validation_id.go
  models/feature_support_level_id.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  subsystem/feature_support_levels_test.go
  subsystem/operators_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  vendor/github.com/openshift/assisted-service/models/host_validation_id.go
Labels: approved, size/XL, api-review, lgtm, jira/valid-reference

#5269 MGMT-14750: Allow FC, ECKD, FBA drive types on s390x
  api/vendor/github.com/openshift/assisted-service/models/drive_type.go
  internal/common/test_configuration.go
  internal/hardware/mock_validator.go
  internal/hardware/validator.go
  internal/hardware/validator_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostutil/test_utils.go
  internal/host/transition_test.go
  internal/host/validations_test.go
  internal/host/validator.go
  models/drive_type.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/drive_type.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#5271 MGMT-14600: Prevent installing dual-stack vSphere on OCP version less than 4.13
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  internal/featuresupport/common.go
  internal/featuresupport/feature_support_level.go
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features.go
  internal/network/dual_stack_validations.go
  models/feature_support_level_id.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#5266 MGMT-14384: Set restricted list of approvers for the new branch
  OWNERS_ALIASES
Labels: approved, size/S, lgtm, jira/valid-reference

#5268 MGMT-13431: ODF storage class not recognizing all available disks in the cluster
  internal/operators/odf/odf_operator.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5279 MGMT-14830: Enable TechPreviewNoUpgrade when platform is external
  internal/installcfg/installcfg.go
  internal/provider/external/installConfig.go
  internal/provider/registry/registry_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5273 MGMT-13746: validate discovery ignition size
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5267 OCPBUGS-14405: Avoid panic if pull secret contains non-string
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
Labels: approved, size/S, lgtm, jira/valid-bug, jira/valid-reference

#5250 OCPBUGS-7076: Copy Day2 BMH if Agent is installing
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/M, lgtm, jira/valid-bug, jira/valid-reference

#5282 MGMT-14756: Add tls config for the service monitor
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5221 MGMT-14631: Remove support for openshift 4.8
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  docs/hive-integration/crds/agentClusterInstall-SNO.yaml
  docs/hive-integration/crds/agentClusterInstall-dualstack-SNO.yaml
  docs/hive-integration/crds/agentClusterInstall-dualstack-vips.yaml
  docs/hive-integration/crds/agentClusterInstall-dualstack.yaml
  docs/hive-integration/crds/agentClusterInstall-with-ignitionEndpoint.yaml
  docs/hive-integration/crds/agentClusterInstall-with-installconfig-overrides.yaml
  docs/hive-integration/crds/agentClusterInstall.yaml
  docs/hive-integration/crds/clusterImageSet.yaml
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/support_levels_list.go
  internal/versions/api_test.go
  openshift/template.yaml
  subsystem/cluster_test.go
  subsystem/kubeapi_test.go
  subsystem/subsystem_suite_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5291 MGMT-14904: fix error code for ignition size validation
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5290 MGMT-14883: Fix feature-support validation fail to validate openshift version
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/featuresupport/common.go
  internal/featuresupport/feature_support_level.go
  internal/featuresupport/features.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5281 MGMT-14730: Validate that manifest file size does not exceed 1MB
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5275 MGMT-14165: `AgentClusterInstall` Webhooks improvements and fixes
  internal/common/conversions.go
  internal/provider/common.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_mutating_hook.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_mutating_hook_test.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook_test.go
Labels: approved, size/XL, lgtm, jira/valid-reference

#5276 MGMT-14769: Enable upgrade agent by default
  deploy/podman/configmap-disconnected.yml
  deploy/podman/configmap.yml
  deploy/podman/configmap_tls.yml
  internal/feature/flags.go
  openshift/template.yaml
  subsystem/utils_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5297 MGMT-14975: Update MCE operator installation to use stable-2.3 channel
  internal/operators/mce/config.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5298 MGMT-14973: Fix misleading logs showing wrong platform and user_managed_networking combination
  internal/bminventory/inventory.go
  internal/common/conversions.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5301 MGMT-14631: Removing leftover of support for openshift 4.8
  internal/featuresupport/features.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5302 MGMT-14992: Fix Minimal ISO set as default in s390x
  internal/bminventory/inventory.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5303 [cloud_hotfix_releases] MGMT-14992: Fix Minimal ISO set as default in s390x
  internal/bminventory/inventory.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5304 [release-ocm-2.8] MGMT-14992: Fix Minimal ISO set as default in s390x
  internal/bminventory/inventory.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5295 OCPBUGS-13738 enforce additional ntp sources added into chrony
  cmd/main.go
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
Labels: approved, size/L, lgtm

#5305 [release-ocm-2.8] MGMT-15013: AgentClusterInstall Webhooks improvements and fixes
  api/vendor/github.com/openshift/assisted-service/models/platform.go
  api/vendor/github.com/openshift/assisted-service/models/platform_type.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validations.go
  internal/common/conversions.go
  internal/provider/common.go
  internal/provider/external/base.go
  internal/provider/external/consts.go
  internal/provider/external/ignition.go
  internal/provider/external/installConfig.go
  internal/provider/external/inventory.go
  internal/provider/registry/registry.go
  internal/provider/registry/registry_test.go
  models/platform.go
  models/platform_type.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_mutating_hook.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_mutating_hook_test.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook_test.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/platform.go
  vendor/github.com/openshift/assisted-service/models/platform_type.go
Labels: approved, api-review, lgtm, size/XXL, jira/valid-reference

#5306 MGMT-15015 Provider IsHostSupported panic if platform is not found
  internal/provider/registry/registry.go
  internal/provider/registry/registry_test.go
Labels: approved, size/S, lgtm

#5309 MGMT-15025: Forbid register Z architecture cluster with OCI platform
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5312 MGMT-15034: Fix patch of infrastructure CR with external platform
  internal/provider/external/external_suite_test.go
  internal/provider/external/ignition.go
  internal/provider/external/ignition_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5313 NO-ISSUE: parametrize template to enable switching secrets
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#5317 MGMT-14937: Deprecate `user_managed_networking` attribute
  api/vendor/github.com/openshift/assisted-service/models/cluster.go
  api/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  api/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
  models/cluster.go
  models/cluster_create_params.go
  models/v2_cluster_update_params.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster.go
  vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
Labels: approved, size/S, api-review, lgtm, jira/valid-reference

#5284 MGMT-13284: Check for BMH CRD before creating controller
  cmd/main.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5322 OCPBUGS-15152: Don't require key encipherment usage for approving CSRs
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/csr_utils.go
Labels: approved, size/L, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#5216 OCPBUGS-13621: Fix singular Ingress and API cluster VIPs removal
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validations.go
  internal/network/utils.go
  subsystem/operators_test.go
Labels: approved, size/L, lgtm, bugzilla/valid-bug, jira/severity-important, jira/valid-bug, jira/valid-reference

#5310 MGMT-10534: Create an override annotation for the ironic agent image
  docs/hive-integration/README.md
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5325 NO-ISSUE: Add diffutils to lint Dockerfile
  ci-images/Dockerfile.lint
Labels: approved, size/XS, lgtm, jira/valid-reference

#5326 [release-ocm-2.7] MGMT-14871: Copy Day2 BMH if Agent is installing
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5323 MGMT-15107: Bump version for hacking LSO catalog
  deploy/operator/setup_lso.sh
Labels: approved, size/S, lgtm, jira/valid-reference

#5327 MGMT-15126: Add missing incompatible features in some of the feature-support feature
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5330 MGMT-15114: remove event for cluster registration failed
  docs/events.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/common/events/events.go
  internal/migrations/20230629113604_delete_events_with_unbound_cluster.go
  internal/migrations/20230629113604_delete_events_with_unbound_cluster_test.go
  internal/migrations/migrations.go
Labels: approved, size/XL, api-review, lgtm, jira/valid-reference
