Repository openshift/assisted-service, pull requests merged in 2024-03, with the labels that each got.

#6041 MGMT-17095: Disable local cluster import
  cmd/main.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#6043 NO-ISSUE: Bump OCP versions: 4.15
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6050 NO-ISSUE: Bump OCP versions: 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6052 MGMT-16775: bump OCP images
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6048 MGMT-16814: Use all cluster networks to determine IP family for ironic
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#6056 NO-ISSUE: Bump OCP versions: 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6063 NO-ISSUE: Bump OCP versions: 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6069 NO-ISSUE: Bump OCP versions: 4.14
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6000 OCPBUGS-27787: Use multi payload with ABI
  cmd/agentbasedinstaller/register.go
Labels: approved, size/XS, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#6051 MGMT-16759: Copy cluster proxy settings to imported local-cluster AgentCluster Install
  config/rbac/role.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  internal/controller/controllers/agentserviceconfig_controller.go
  pkg/localclusterimport/import_local_cluster.go
  pkg/localclusterimport/import_local_cluster_test.go
  pkg/localclusterimport/local_cluster_import_operations.go
  pkg/localclusterimport/local_cluster_import_operations_mocks.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6060 NO-ISSUE: Docs - clarifying consequences of capabilities override
  docs/user-guide/install-customization.md
Labels: approved, size/XS, lgtm, jira/valid-reference

#6078 NO-ISSUE: Protect must gather versions cache with mutex
  internal/versions/versions.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6076 MGMT-16766: Use `client_id` instead of `clientId`
  pkg/auth/auth_handler_test_utils.go
  pkg/auth/rhsso_authenticator.go
Labels: approved, size/S, lgtm, jira/valid-reference

#6083 NO-ISSUE: Add environment variable ENABLE_SOFT_TIMEOUTS to openshift/template.yaml
  openshift/template.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#6066 MGMT-16813: Prioritize finding release image with exact CPU architecture
  internal/versions/versions.go
  internal/versions/versions_test.go
  subsystem/operators_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6085 NO-ISSUE: Bump OCP versions: 4.13, 4.15, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6062 AGENT-860: Update configure command to handle multiple HostConfigs
  cmd/agentbasedinstaller/client/main.go
  cmd/agentbasedinstaller/host_config.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6087 MGMT-17196: Fix none existens of static MAC adr. in case of specific network devices on s390x.
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/M, lgtm, ok-to-test, jira/valid-reference

#6090 MGMT-16587: Bump runc to 1.1.12 to mitigate CVE-2024-21626
  go.mod
  go.sum
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/modules.txt
Labels: approved, size/M, lgtm, jira/valid-reference

#6091 MGMT-17266: Add OCP 4.16 images
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#6061 MGMT-16706: Allow in-progress clusters to be deleted in more cases
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6098 NO-ISSUE: Bump OCP versions: 4.16, 4.15, 4.14, 4.12
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6099 MGMT-17308: Offboard osherdp from maintainers list
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#6037 MGMT-17080: enable infrastructure operator
  docs/user-guide/additional-operator-notes.md
  go.mod
  go.sum
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/mock_cluster_api.go
  internal/operators/api/api.go
  internal/operators/common/common.go
  internal/operators/common/common_test.go
  internal/operators/lvm/config.go
  internal/operators/lvm/lvm_operator.go
  internal/operators/lvm/lvm_operator_test.go
  internal/operators/lvm/manifest.go
  internal/operators/manager.go
  internal/operators/manager_test.go
  internal/operators/mce/manifest.go
  internal/operators/mce/mce_operator.go
  internal/operators/mce/mce_operator_test.go
  internal/operators/odf/odf_operator.go
  internal/operators/odf/validations.go
  subsystem/operators_test.go
  vendor/github.com/samber/lo/.gitignore
  vendor/github.com/samber/lo/.travis.yml
  vendor/github.com/samber/lo/CHANGELOG.md
  vendor/github.com/samber/lo/Dockerfile
  vendor/github.com/samber/lo/LICENSE
  vendor/github.com/samber/lo/Makefile
  vendor/github.com/samber/lo/README.md
  vendor/github.com/samber/lo/channel.go
  vendor/github.com/samber/lo/concurrency.go
  vendor/github.com/samber/lo/condition.go
  vendor/github.com/samber/lo/constraints.go
  vendor/github.com/samber/lo/errors.go
  vendor/github.com/samber/lo/find.go
  vendor/github.com/samber/lo/func.go
  vendor/github.com/samber/lo/intersect.go
  vendor/github.com/samber/lo/map.go
  vendor/github.com/samber/lo/math.go
  vendor/github.com/samber/lo/retry.go
  vendor/github.com/samber/lo/slice.go
  vendor/github.com/samber/lo/string.go
  vendor/github.com/samber/lo/tuples.go
  vendor/github.com/samber/lo/type_manipulation.go
  vendor/github.com/samber/lo/types.go
  vendor/modules.txt
Labels: approved, size/XL, lgtm, jira/valid-reference

#6070 MGMT-16002: Accept *yml.patch* and *yaml.patch* extensions
  api/vendor/github.com/openshift/assisted-service/models/create_manifest_params.go
  api/vendor/github.com/openshift/assisted-service/models/update_manifest_params.go
  client/vendor/github.com/openshift/assisted-service/models/create_manifest_params.go
  client/vendor/github.com/openshift/assisted-service/models/update_manifest_params.go
  docs/user-guide/install-customization.md
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
  models/create_manifest_params.go
  models/update_manifest_params.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/create_manifest_params.go
  vendor/github.com/openshift/assisted-service/models/update_manifest_params.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#6092 MGMT-17241: [soft-timeout] Installation not timeout /aborted after 24 Hours
  internal/cluster/common.go
  internal/cluster/mock_transition.go
  internal/cluster/statemachine.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6025 MGMT-16263: Enable usage of custom OCP release images when we create cluster
  Makefile
  client/versions/v2_list_supported_openshift_versions_parameters.go
  cmd/main.go
  data/default_release_sources.json
  deploy/assisted-service-configmap.yaml
  deploy/wiremock/wiremock-deployment.yaml
  docs/hive-integration/crds/clusterImageSet.yaml
  hack/add_wiremock_stubs.go
  hack/wait_for_wiremock.sh
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/common/version.go
  internal/common/version_test.go
  internal/releasesources/clients.go
  internal/releasesources/clients_test.go
  internal/releasesources/mock_clients.go
  internal/releasesources/release_sources.go
  internal/releasesources/release_sources_test.go
  internal/versions/api.go
  internal/versions/api_test.go
  internal/versions/common.go
  internal/versions/common_test.go
  internal/versions/kube_api_versions.go
  internal/versions/kube_api_versions_test.go
  internal/versions/mock_versions.go
  internal/versions/osimages.go
  internal/versions/rest_api_versions.go
  internal/versions/rest_api_versions_test.go
  openshift/template.yaml
  restapi/embedded_spec.go
  restapi/operations/versions/v2_list_supported_openshift_versions_parameters.go
  restapi/operations/versions/v2_list_supported_openshift_versions_urlbuilder.go
  subsystem/agent_based_installer_client_test.go
  subsystem/authz_test.go
  subsystem/cluster_test.go
  subsystem/image_test.go
  subsystem/operators_test.go
  subsystem/subsystem_suite_test.go
  subsystem/wiremock_stubs.go
  swagger.yaml
  tools/deploy_assisted_installer_configmap.py
  tools/deploy_wiremock.py
  vendor/github.com/openshift/assisted-service/client/versions/v2_list_supported_openshift_versions_parameters.go
Labels: approved, kind/dependency-change, api-review, lgtm, size/XXL, jira/valid-reference

#6110 NO-ISSUE: disable dynamic release images collection until UI will merge its changes adjusting itself to larger amount of versions
  openshift/template.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#6054 OCPBUGS-30232: Handle skipping hostPrefix validation for IPv6
  internal/cluster/validator.go
Labels: approved, size/M, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#6104 MGMT-17328: OCI should be tech preview for OCP 4.14
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features_platforms.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#6114 NO-ISSUE: Bump OCP versions: 4.13, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6116 NO-ISSUE: rename docker image for postgres 12 as latest tag disappeared
  Makefile
  config/manager/manager.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/pod-persistent-disconnected.yml
  deploy/podman/pod-persistent.yml
  deploy/podman/pod.yml
  deploy/podman/pod_tls.yml
  deploy/postgres/postgres-deployment-ephemeral.yaml
  deploy/postgres/postgres-deployment.yaml
  docs/dev/testing.md
  internal/common/common_unitest_db.go
  internal/common/testcontainers_db_context.go
  internal/controller/controllers/images.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6113 MGMT-17354: Update CBO to support dual stack SNO hub deploying an IPv6 spoke
  go.mod
  go.sum
  internal/controller/controllers/bmo_utils.go
  vendor/github.com/openshift/cluster-baremetal-operator/provisioning/baremetal_pod.go
  vendor/github.com/openshift/cluster-baremetal-operator/provisioning/image_cache.go
  vendor/github.com/openshift/cluster-baremetal-operator/provisioning/image_customization.go
  vendor/github.com/openshift/cluster-baremetal-operator/provisioning/ironic_proxy.go
  vendor/github.com/openshift/cluster-baremetal-operator/provisioning/machine_os_images.go
  vendor/github.com/openshift/cluster-baremetal-operator/provisioning/utils.go
  vendor/modules.txt
Labels: approved, size/XS, lgtm, jira/valid-reference

#6126 [release-ocm-2.10] NO-ISSUE: replace postgres images as current image disappeared from quay.io
  Makefile
  config/manager/manager.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/pod-persistent-disconnected.yml
  deploy/podman/pod-persistent.yml
  deploy/podman/pod.yml
  deploy/podman/pod_tls.yml
  deploy/postgres/postgres-deployment-ephemeral.yaml
  deploy/postgres/postgres-deployment.yaml
  docs/dev/testing.md
  internal/common/common_unitest_db.go
  internal/controller/controllers/images.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6132 NO-ISSUE: replace postgres images as current one disappeared from quay
  Makefile
  config/manager/manager.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/pod-persistent-disconnected.yml
  deploy/podman/pod-persistent.yml
  deploy/podman/pod.yml
  deploy/podman/pod_tls.yml
  deploy/postgres/postgres-deployment-ephemeral.yaml
  deploy/postgres/postgres-deployment.yaml
  docs/dev/testing.md
  internal/common/common_unitest_db.go
Labels: approved, size/S, lgtm, jira/valid-reference

#6134 NO-ISSUE: replace postgres images as current one disappeared from quay
  Makefile
  config/manager/manager.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/pod-persistent-disconnected.yml
  deploy/podman/pod-persistent.yml
  deploy/podman/pod.yml
  deploy/podman/pod_tls.yml
  deploy/postgres/postgres-deployment-ephemeral.yaml
  deploy/postgres/postgres-deployment.yaml
  docs/dev/testing.md
  internal/common/common_unitest_db.go
  internal/controller/controllers/images.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6133 NO-ISSUE: replace postgres images as current one disappeared from quay
  Makefile
  config/manager/manager.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/pod-persistent-disconnected.yml
  deploy/podman/pod-persistent.yml
  deploy/podman/pod.yml
  deploy/podman/pod_tls.yml
  deploy/postgres/postgres-deployment-ephemeral.yaml
  deploy/postgres/postgres-deployment.yaml
  docs/dev/testing.md
  internal/common/common_unitest_db.go
  internal/controller/controllers/images.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6135 NO-ISSUE: replace postgres images as current one disappeared from quay
  Makefile
  config/manager/manager.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/pod-persistent-disconnected.yml
  deploy/podman/pod-persistent.yml
  deploy/podman/pod.yml
  deploy/podman/pod_tls.yml
  deploy/postgres/postgres-deployment-ephemeral.yaml
  deploy/postgres/postgres-deployment.yaml
  docs/dev/testing.md
  internal/common/common_unitest_db.go
  internal/controller/controllers/images.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6125 MGMT-17367: Use ICSP in install-config for older OCP releases
  internal/installcfg/builder/builder.go
  internal/installcfg/builder/builder_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6115 MGMT-17361: Changing the addition of configuration release images to run when the instance becomes leader instead of skipping if it not
  cmd/main.go
  internal/releasesources/release_sources.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6119 MGMT-17369: Add multi-arch release images to as well when setting "only_latest=true" in ".../openshift-versions"
  internal/versions/api.go
  internal/versions/api_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6139 Revert "MGMT-16980: Change the default value of ENABLE_SKIP_MCO_REBOOT to false (#6011)"
  internal/feature/flags.go
Labels: approved, size/XS, lgtm, jira/valid-reference
