Repository openshift/assisted-service, pull requests merged in 2024-08, with the labels that each got.

#6639 MGMT-18505: Fix installation from a 4.17 hub with converged flow
  go.mod
  go.sum
  internal/controller/controllers/bmo_utils.go
  internal/controller/controllers/bmo_utils_test.go
  vendor/github.com/openshift/image-customization-controller/pkg/ignition/builder.go
  vendor/modules.txt
Labels: approved, size/M, lgtm, jira/valid-reference

#6612 MGMT-18231: Block iSCSI as an installation disk when its holder is multipath
  internal/hardware/validator.go
  internal/hardware/validator_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6643 [release-ocm-2.11] MGMT-18508: Allow converged from 4.17 hub
  go.mod
  go.sum
  internal/controller/controllers/bmo_utils.go
  internal/controller/controllers/bmo_utils_test.go
  internal/controller/controllers/mock_bmo_utils.go
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
  internal/oc/mock_release.go
  internal/oc/release.go
  vendor/github.com/openshift/image-customization-controller/pkg/ignition/builder.go
  vendor/modules.txt
Labels: approved, size/L, lgtm, jira/valid-reference

#6644 NO-ISSUE: [master] Bump OCP versions: 4.14, 4.16, 4.13
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6637 MGMT-18313: Replace golang base image as it is based on Centos Linux 7
  .golangci.yml
  Dockerfile.assisted-service
  Dockerfile.assisted-service-build
  Dockerfile.assisted-service-debug
  ci-images/Dockerfile.base
  ci-images/Dockerfile.code-generation
  hack/container_build_scripts/install_build_deps.sh
  hack/container_build_scripts/replace_dnf_repositories_ref_if_needed.sh
Labels: approved, kind/dependency-change, size/L, api-review, lgtm, jira/valid-reference

#6650 NO-ISSUE: [release-ocm-2.11] Bump OCP versions: 4.16, 4.14, 4.13, 4.15
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#6652 NO-ISSUE: [release-ocm-2.9] Bump OCP versions: 4.13, 4.14, 4.15
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#6651 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.15, 4.14, 4.13
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#6653 NO-ISSUE: [release-ocm-2.8] Bump OCP versions: 4.13, 4.14
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6434 MGMT-17560: validation to support iSCSI boot volume
  api/vendor/github.com/openshift/assisted-service/models/disk.go
  api/vendor/github.com/openshift/assisted-service/models/iscsi.go
  client/vendor/github.com/openshift/assisted-service/models/disk.go
  client/vendor/github.com/openshift/assisted-service/models/iscsi.go
  internal/common/common.go
  internal/common/test_configuration.go
  internal/hardware/mock_validator.go
  internal/hardware/validator.go
  internal/hardware/validator_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/transition_test.go
  internal/network/connectivity_groups.go
  internal/network/utils.go
  models/disk.go
  models/iscsi.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/disk.go
  vendor/github.com/openshift/assisted-service/models/iscsi.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#6654 NO-ISSUE: Print subsystem environment variables before test
  Makefile
Labels: approved, size/XS, lgtm, jira/valid-reference

#6655 NO-ISSUE: Add missing kube api flag on kube api subsystem test
  Makefile
Labels: approved, size/XS, lgtm, jira/valid-reference

#6658 NO-ISSUE: [master] Bump OCP versions: 4.16
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6656 [release-ocm-2.9] MGMT-18313: Replace golang base image as it is based on Centos Linux 7
  .golangci.yml
  Dockerfile.assisted-service
  Dockerfile.assisted-service-build
  Dockerfile.assisted-service-debug
  ci-images/Dockerfile.base
  ci-images/Dockerfile.code-generation
  subsystem/kubeapi_test.go
Labels: approved, kind/dependency-change, size/L, lgtm, jira/valid-reference

#6647 [release-ocm-2.11] MGMT-18313: Replace golang base image as it is based on Centos Linux 7
  .golangci.yml
  Dockerfile.assisted-service
  Dockerfile.assisted-service-build
  Dockerfile.assisted-service-debug
  ci-images/Dockerfile.base
  ci-images/Dockerfile.code-generation
  hack/container_build_scripts/install_build_deps.sh
  hack/container_build_scripts/replace_dnf_repositories_ref_if_needed.sh
Labels: approved, kind/dependency-change, size/L, lgtm, jira/valid-reference

#6648 [release-ocm-2.10] MGMT-18313: Replace golang base image as it is based on Centos Linux 7
  .golangci.yml
  Dockerfile.assisted-service
  Dockerfile.assisted-service-build
  Dockerfile.assisted-service-debug
  ci-images/Dockerfile.base
  ci-images/Dockerfile.code-generation
Labels: approved, kind/dependency-change, size/M, lgtm, jira/valid-reference

#6657 [release-ocm-2.8] MGMT-18313: Replace golang base image as it is based on Centos Linux 7
  .golangci.yml
  Dockerfile.assisted-service
  Dockerfile.assisted-service-build
  Dockerfile.assisted-service-debug
  ci-images/Dockerfile.base
  ci-images/Dockerfile.code-generation
  subsystem/kubeapi_test.go
Labels: approved, kind/dependency-change, size/L, lgtm, jira/valid-reference

#6659 NO-ISSUE: Fix debug image by adding required packages
  Dockerfile.assisted-service-debug
Labels: approved, size/XS, lgtm, jira/valid-reference

#6663 NO-ISSUE: [master] Bump OCP versions: 4.14, 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6662 MGMT-18560: Fix AutomatedCleaningMode behavior
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6649 OCPBUGS-27238: Use both the OCP cluster trusted certs and user certs
  docs/operator.md
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/common.go
Labels: approved, size/L, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#6661 MGMT-18514: Calculate machine networks in external platform
  internal/provider/base.go
  internal/provider/external/base.go
  internal/provider/external/external.go
  internal/provider/external/oci.go
  internal/provider/none/installConfig.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6670 [release-ocm-2.9] MGMT-18585: Fix AutomatedCleaningMode behavior
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6673 NO-ISSUE: [release-ocm-2.9] Bump OCP versions: 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6671 NO-ISSUE: [release-ocm-2.11] Bump OCP versions: 4.15, 4.14, 4.16
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6603 MGMT-17560: Workaround missing DNS on iSCSI
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
  internal/network/mock_manifests_generator.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6674 NO-ISSUE: Change debug Dockerfile so it will not require prior actions
  Dockerfile.assisted-service-debug
  Makefile
Labels: approved, kind/dependency-change, size/S, lgtm, jira/valid-reference

#6665 MGMT-18121: Configure networking when using ISCSI over OCI
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/ignition/templates/discovery.ign
  internal/ignition/templates/iscsi-oci-configure-secondary-nic.service
  internal/ignition/templates/iscsi-oci-configure-secondary-nic.sh
Labels: approved, size/L, lgtm, jira/valid-reference

#6676 NO-ISSUE: [master] Bump OCP versions: 4.16, 4.17
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6678 [release-ocm-2.10] NO-ISSUE: Change debug Dockerfile so it will not require prior actions
  Dockerfile.assisted-service-debug
  Makefile
Labels: approved, kind/dependency-change, size/S, lgtm, jira/valid-reference

#6677 [release-ocm-2.11] NO-ISSUE: Change debug Dockerfile so it will not require prior actions
  Dockerfile.assisted-service-debug
  Makefile
Labels: approved, kind/dependency-change, size/S, lgtm, jira/valid-reference

#6679 [release-ocm-2.9] NO-ISSUE: Change debug Dockerfile so it will not require prior actions
  Dockerfile.assisted-service-debug
  Makefile
Labels: approved, kind/dependency-change, size/S, lgtm, jira/valid-reference

#6680 [release-ocm-2.8] NO-ISSUE: Change debug Dockerfile so it will not require prior actions
  Dockerfile.assisted-service-debug
  Makefile
Labels: approved, kind/dependency-change, size/S, lgtm, jira/valid-reference

#6666 MGMT-10006: Wait for host to deprovision in BMAC
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/XL, lgtm, jira/valid-reference

#6685 MGMT-18418: Reapply "Add certs to ingress when deploying in non-OCP clusters (#6564)"
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/kube_compat.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6645 MGMT-18378: allow CNV on ARM Dev preview
  internal/featuresupport/features_olm_operators.go
  internal/featuresupport/features_olm_operators_test.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/cnv/cnv_operator_test.go
  internal/operators/manager_test.go
  subsystem/cluster_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6660 MGMT-16212: Allow Assisted-Installer to tolerate a slightly lower memory than required
  internal/host/validator.go
Labels: approved, size/XS, lgtm, ok-to-test, jira/valid-reference

#6667 MGMT-18384: bump golang 1.21
  Dockerfile.assisted-service
  Dockerfile.assisted-service-build
  Dockerfile.assisted-service-debug
  api/go.mod
  api/go.sum
  api/vendor/modules.txt
  ci-images/Dockerfile.base
  ci-images/Dockerfile.lint
  client/go.mod
  client/go.sum
  client/vendor/modules.txt
  go.mod
  go.sum
  internal/host/refresh_status_preprocessor_test.go
  models/go.mod
  models/go.sum
  vendor/modules.txt
Labels: approved, kind/dependency-change, size/M, api-review, lgtm, jira/valid-reference

#6688 [release-ocm-2.10] NO-ISSUE: Add OCP 4.16 OS images to ocm-2.10
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6689 NO-ISSUE: add MCE to OLM operators dev docs
  docs/dev/olm-operator-plugins.md
Labels: approved, size/XS, lgtm, jira/valid-reference

#6664 NO-ISSUE: Support both minikube and kind for deploying on k8s cluster
  Makefile
  README.md
  deploy/wiremock/wiremock-deployment.yaml
  docs/dev/debug.md
  docs/dev/running-test.md
  docs/user-guide/assisted-service-on-k8s.md
  docs/user-guide/assisted-service-on-local.md
  docs/user-guide/deploy-assisted-monitoring.md
  docs/user-guide/deploy-on-local.md
  hack/hub_cluster.sh
  hack/kind/kind-config.yaml
  hack/kind/kind.sh
  hack/minikube/minikube.sh
  skipper.env
  tools/deploy_assisted_installer.py
  tools/deploy_assisted_installer_configmap.py
  tools/deploy_ui.py
Labels: approved, size/XL, lgtm, jira/valid-reference

#6694 NO-ISSUE: Soft install timeout enhancement
  docs/enhancements/soft-install-timeout.md
  docs/enhancements/soft-install-timeout/ui-example.png
Labels: approved, size/L, lgtm, jira/valid-reference

#6690 NO-ISSUE: [release-ocm-2.11] Bump OCP versions: 4.16, 4.12, 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6702 NO-ISSUE: change ci operator to 4.17
  .ci-operator.yaml
  Dockerfile.assisted-service.ocp
Labels: approved, kind/dependency-change, size/XS, lgtm, jira/valid-reference

#6706 NO-ISSUE: [master] Bump OCP versions: 4.16, 4.13, 4.14, 4.15, 4.12, 4.17
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6683 MGMT-18589: Enhancement doc for backup/restore support
  docs/enhancements/backup-restore-support.md
Labels: approved, size/L, lgtm, jira/valid-reference

#6710 NO-ISSUE: Add mlorenzofr to OWNERS_ALIASES file
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#6682 MGMT-17805: Fix MCO reboot error for s390x
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features_misc.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/S, lgtm, ok-to-test, jira/valid-reference

#6704 NO-ISSUE: Prepare base documents and targets for devel environments using kind
  Makefile
  deploy/kind/agent-svc-config.yaml
  deploy/kind/assisted-service-portmap.yaml
  docs/dev/kind/README.md
  hack/hub_cluster.sh
  hack/kind/dev-env-infra.sh
  hack/kind/dev-env-sylva.sh
  hack/kind/kind-config.yaml
  hack/kind/kind.sh
Labels: approved, size/L, lgtm, jira/valid-reference

#6696 MGMT-18659: Local cluster name should be picked up from ACM ManagedCluster label
  cmd/operator/main.go
  internal/controller/controllers/local_cluster_import_controller.go
  internal/controller/controllers/local_cluster_import_controller_test.go
Labels: approved, size/L, lgtm, jira/valid-reference
