Repository openshift/assisted-service, pull requests merged in 2024-01, with the labels that each got.

#5859 NO-ISSUE: Fix for subsystem test that fails locally.
  internal/cluster/cluster.go
  subsystem/cluster_test.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5811 MGMT-16241: Ensure that LastInstallationPreparationStatus is reset on cluster install.
  api/vendor/github.com/openshift/assisted-service/models/last_installation_preparation.go
  client/vendor/github.com/openshift/assisted-service/models/last_installation_preparation.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/transition_test.go
  models/last_installation_preparation.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/last_installation_preparation.go
Labels: approved, size/M, api-review, lgtm, jira/valid-reference

#5863 NO-ISSUE: Bump OCP versions: 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#5867 NO-ISSUE: Bump OCP versions: 4.15, 4.12, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#5872 MGMT-16505: Huge amount of "Cluster was updated with api-vip <IP ADDRESS>, ingress-vip <IP ADDRESS>" in cluster events
  internal/bminventory/inventory.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5877 OCPBUGS-26764: set CloudControllerManager to External for OCI
  internal/installcfg/installcfg.go
  internal/provider/external/installConfig.go
Labels: approved, size/S, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#5861 MGMT-16494: Move ip hint file creation to ignition in order to change it in IBI process
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
  internal/network/mock_manifests_generator.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5830 NO-ISSUE: Removes unused assistedservice CRD
  config/crd/bases/assistedservice.openshift.io.openshift.io_assistedservices.yaml
  config/crd/patches/cainjection_in_assistedservices.yaml
  config/crd/patches/webhook_in_assistedservices.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#5818 MGMT-16371: Fix additionial kargs in case of DHCP
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/M, lgtm, ok-to-test, jira/valid-reference

#5883 [release-ocm-2.8] MGMT-16494: Move ip hint file creation to ignition in order to change it in IBI process
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
  internal/network/mock_manifests_generator.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5850 NO-ISSUE: testing go1.20 in all packages
  api/go.mod
  api/vendor/modules.txt
  client/go.mod
  client/vendor/modules.txt
  deploy/operator/deploy.sh
  hack/setup_env.sh
  models/go.mod
  vendor/modules.txt
Labels: approved, size/S, api-review, lgtm, jira/valid-reference

#5875 NO-ISSUE: Bump OCP versions: 4.14, 4.13, 4.11
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#5871 MGMT-16332: allow lvms on multi node
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features_networking.go
  internal/featuresupport/features_olm_operators.go
  internal/featuresupport/features_olm_operators_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5887 NO-ISSUE: Bump OCP versions: 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#5888 NO-ISSUE remove filanov from approves
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#5886 NO-ISSUE: Fix Hypershift must-gather
  deploy/operator/gather.sh
Labels: approved, size/S, lgtm, jira/valid-reference

#5870 MGMT-16501: Add request headers to api_vip_connectivity check request
  api/vendor/github.com/openshift/assisted-service/models/api_vip_connectivity_additional_request_header.go
  api/vendor/github.com/openshift/assisted-service/models/api_vip_connectivity_request.go
  client/vendor/github.com/openshift/assisted-service/models/api_vip_connectivity_additional_request_header.go
  client/vendor/github.com/openshift/assisted-service/models/api_vip_connectivity_request.go
  internal/host/hostcommands/api_vip_connectivity_check_cmd.go
  internal/host/hostcommands/api_vip_connectivity_check_cmd_test.go
  models/api_vip_connectivity_additional_request_header.go
  models/api_vip_connectivity_request.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/api_vip_connectivity_additional_request_header.go
  vendor/github.com/openshift/assisted-service/models/api_vip_connectivity_request.go
Labels: approved, size/M, api-review, lgtm, jira/valid-reference

#5896 NO-ISSUE: migrate pipeline task init from 0.1 to 0.2
  .tekton/assisted-service-q2vh-pull-request.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#5868 OCPBUGS-24428: Redact passwords logged in installConfigOverrides
  cmd/agentbasedinstaller/register.go
Labels: approved, size/XS, lgtm, jira/valid-bug, jira/valid-reference

#5897 NO-ISSUE: Bump OCP versions: 4.15, 4.13, 4.14, 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#5907 NO-ISSUE: Bump OCP versions: 4.15
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#5880 MGMT-16208: Add controller stages to assisted service
  api/vendor/github.com/openshift/assisted-service/models/cluster_progress_info.go
  api/vendor/github.com/openshift/assisted-service/models/finalizing_stage.go
  client/vendor/github.com/openshift/assisted-service/models/cluster_progress_info.go
  client/vendor/github.com/openshift/assisted-service/models/finalizing_stage.go
  cmd/main.go
  docs/events.yaml
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/common.go
  internal/cluster/finalizing_stages.go
  internal/cluster/finalizing_stages_test.go
  internal/cluster/mock_cluster_api.go
  internal/cluster/mock_transition.go
  internal/cluster/progress_test.go
  internal/cluster/statemachine.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/cluster/validator_test.go
  internal/common/events/events.go
  internal/host/common.go
  internal/operators/odf/validation_test.go
  models/cluster_progress_info.go
  models/finalizing_stage.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster_progress_info.go
  vendor/github.com/openshift/assisted-service/models/finalizing_stage.go
Labels: approved, size/XL, api-review, lgtm, jira/valid-reference

#5908 NO-ISSUE: migrate rhtap init step to v0.2
  .tekton/assisted-service-q2vh-pull-request.yaml
  .tekton/assisted-service-q2vh-push.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#5915 NO-ISSUE: Bump OCP versions: 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#5914 OCPBUGS-27376: Allow domain names starting with a number
  pkg/validations/validations.go
  pkg/validations/validations_test.go
  subsystem/cluster_test.go
Labels: approved, size/M, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#5920 MGMT-16660: OCI is tech-preview from OCP 4.15
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features_platforms.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5919 NO-ISSUE: Bump OCP versions: 4.13, 4.11
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#5913 ACM-9504: Remove unecessary dependency on go-git
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/L, lgtm, jira/valid-reference

#5929 NO-ISSUE: Bump OCP versions: 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#5884 MGMT-16508: Add API to AgentServiceConfig CRD to allow pass of CA certificates for image pull.
  api/v1beta1/agentserviceconfig_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
  config/crd/bases/agent-install.openshift.io_hypershiftagentserviceconfigs.yaml
  config/crd/resources.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agentserviceconfigs.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_hypershiftagentserviceconfigs.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/zz_generated.deepcopy.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#5874 MGMT-16517: Add Env Var for On-Prem Data Deployment Type
  deploy/assisted-service.yaml
  deploy/podman/configmap-disconnected.yml
  deploy/podman/configmap.yml
  deploy/podman/configmap_tls.yml
  internal/uploader/events_uploader.go
  internal/uploader/events_uploader_test.go
  internal/uploader/uploader.go
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#5906 MGMT-16521: Identify Operator-based Deployment Data
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5930 MGMT-16612: notify when host updates status
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/host/hostutil/update_host.go
  internal/host/hostutil/update_host_test.go
  internal/host/monitor_test.go
  internal/host/transition.go
  internal/host/transition_test.go
  internal/host/validations_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5893 MGMT-16603: Allow setting agent cluster reference via BHM
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5936 [release-ocm-2.9] MGMT-16717: Allow domain names starting with a number (#5914)
  pkg/validations/validations.go
  pkg/validations/validations_test.go
  subsystem/cluster_test.go
Labels: approved, size/L, lgtm, jira/valid-reference
