Repository openshift/assisted-service, pull requests merged in 2024-09, with the labels that each got.

#6698 NO-ISSUE: [release-ocm-2.11] Bump OCP versions: 4.13, 4.16, 4.15, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6713 NO-ISSUE: [master] Bump OCP versions: 4.12, 4.16, 4.17, 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6716 NO-ISSUE: [release-ocm-2.11] Bump OCP versions: 4.16, 4.12, 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6720 [release-ocm-2.10] MGMT-18698: Use release image version as key instead of openshift version in unit-test
  data/default_release_images.json
  deploy/podman/configmap.yml
  internal/versions/api_test.go
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6721 MGMT-18702: Fix error due to missing local cluster name
  internal/controller/controllers/local_cluster_import_controller.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#6723 [release-ocm-2.8] MGMT-18698: Use release image version as key instead of openshift version
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#6722 [release-ocm-2.9] MGMT-18698: Use release image version as key instead of openshift ver…
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#6724 NO-ISSUE: [master] Bump OCP versions: 4.16
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6733 NO-ISSUE: workaround for LSO on 4.17
  deploy/operator/setup_lso.sh
Labels: approved, size/S, lgtm, jira/valid-reference

#6705 MGMT-10006: Cleanup spoke after unbind
  api/v1beta1/agent_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/agent-install.openshift.io_agents.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
  docs/hive-integration/late-binding.md
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/agent_types.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/zz_generated.deepcopy.go
Labels: approved, size/XL, api-review, lgtm, jira/valid-reference

#6734 MGMT-18645: Ensure CA bundle exists before assisted-service
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_storage_validation_test.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6741 NO-ISSUE: fixed destroy target in running-test doc
  docs/dev/running-test.md
Labels: approved, size/XS, lgtm, jira/valid-reference

#6738 NO-ISSUE: [release-ocm-2.9] Bump OCP versions: 4.13, 4.14, 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6739 NO-ISSUE: [release-ocm-2.8] Bump OCP versions: 4.13, 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6737 NO-ISSUE: [master] Bump OCP versions: 4.17, 4.13, 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6731 MGMT-14634: Ensure that nil values and empty values for filenames are handled correctly.
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6715 MGMT-18694, MGMT-18575, OCPBUGS-34849: Don't require mapping for names matching physical interfaces
  pkg/staticnetworkconfig/generator.go
  pkg/staticnetworkconfig/generator_test.go
Labels: approved, size/L, lgtm, jira/valid-bug, jira/valid-reference

#6686 MGMT-18510: Add an annotation to override ironic IP family to provide in dual-stack hubs
  docs/hive-integration/README.md
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6746 NO-ISSUE: [master] Bump OCP versions: 4.15, 4.16, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6703 MGMT-18636: Handle status annotation in provisioned BMHs
  cmd/main.go
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6751 MGMT-18466: moving to security updates only
  .github/dependabot.yml
Labels: approved, size/M, lgtm, jira/valid-reference

#6697 CORS-3664: Authentication tech debt for agent based installer
  pkg/auth/agent_local_authenticator.go
  pkg/auth/agent_local_authenticator_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6760 NO-ISSUE: [release-ocm-2.11] Bump OCP versions: 4.14, 4.16, 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6761 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.14, 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6695 MGMT-18579: Inject nmpolicy captures into the provided YAML and place it with INI file under the host-specific path
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/constants/common_network_script.go
  internal/constants/nmstatectl_script.go
  internal/constants/nmstatectl_script_test.go
  internal/constants/scripts.go
  internal/constants/scripts_files_test.go
  internal/constants/scripts_test.go
  internal/constants/test_root_with_nmstate/etc/assisted/network/host0/mac_interface.ini
  internal/constants/test_root_with_nmstate/etc/assisted/network/host0/ymlFile0.yml
  internal/constants/test_root_with_nmstate/sys/class/net/enp100/address
  internal/ignition/discovery.go
  internal/ignition/discovery_test.go
  internal/ignition/templates/discovery.ign
  internal/ignition/templates/pre-network-manager-config-with-nmstatectl.service
  internal/isoeditor/rhcos.go
  internal/isoeditor/rhcos_test.go
  pkg/staticnetworkconfig/backward_compatibility.go
  pkg/staticnetworkconfig/generator.go
  pkg/staticnetworkconfig/generator_test.go
  pkg/staticnetworkconfig/mock_generator.go
  subsystem/infra_env_test.go
Labels: approved, lgtm, size/XXL, jira/valid-reference

#6753 OCPBUGS-42071: Switch to github.com/docker/distribution/reference to Mitigate CVE-2024-3727
  go.mod
  go.sum
  internal/cluster/validations/validations.go
  internal/common/common.go
  vendor/github.com/containers/image/v5/docker/reference/README.md
  vendor/github.com/containers/image/v5/docker/reference/regexp-additions.go
  vendor/github.com/docker/distribution/LICENSE
  vendor/github.com/docker/distribution/digestset/set.go
  vendor/github.com/docker/distribution/reference/helpers.go
  vendor/github.com/docker/distribution/reference/normalize.go
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/docker/distribution/reference/regexp.go
  vendor/modules.txt
Labels: approved, cherry-pick-approved, size/XL, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#6750 OCPBUGS-42075: Switch to github.com/docker/distribution/reference to Mitigate CVE-2024-3727
  go.mod
  go.sum
  internal/cluster/validations/validations.go
  internal/common/common.go
  vendor/github.com/containers/image/v5/docker/reference/README.md
  vendor/github.com/containers/image/v5/docker/reference/regexp-additions.go
  vendor/github.com/docker/distribution/LICENSE
  vendor/github.com/docker/distribution/digestset/set.go
  vendor/github.com/docker/distribution/reference/helpers.go
  vendor/github.com/docker/distribution/reference/normalize.go
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/docker/distribution/reference/regexp.go
  vendor/modules.txt
Labels: approved, cherry-pick-approved, size/XL, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#6752 OCPBUGS-42073: Switch to github.com/docker/distribution/reference to Mitigate CVE-2024-3727
  go.mod
  go.sum
  internal/cluster/validations/validations.go
  internal/common/common.go
  vendor/github.com/containers/image/v5/docker/reference/README.md
  vendor/github.com/containers/image/v5/docker/reference/regexp-additions.go
  vendor/github.com/docker/distribution/LICENSE
  vendor/github.com/docker/distribution/digestset/set.go
  vendor/github.com/docker/distribution/reference/helpers.go
  vendor/github.com/docker/distribution/reference/normalize.go
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/docker/distribution/reference/regexp.go
  vendor/modules.txt
Labels: approved, cherry-pick-approved, size/XL, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#6769 MGMT-18455: Don't destroy cluster on detach - OCM 2.10 backport
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6749 MGMT-18905: Fix failing dependencies
  go.mod
  go.sum
  hack/setup_env.sh
  vendor/k8s.io/api/admissionregistration/v1alpha1/types.go
  vendor/k8s.io/api/admissionregistration/v1beta1/types.go
  vendor/k8s.io/api/batch/v1/types.go
  vendor/modules.txt
Labels: approved, size/M, lgtm, jira/valid-reference

#6742 OCPBUGS-33824: Libraries bump to mitigate CVE-2024-27289
  go.mod
  go.sum
  vendor/github.com/jackc/pgconn/CHANGELOG.md
  vendor/github.com/jackc/pgconn/auth_scram.go
  vendor/github.com/jackc/pgconn/krb5.go
  vendor/github.com/jackc/pgconn/pgconn.go
  vendor/github.com/jackc/pgproto3/v2/authentication_cleartext_password.go
  vendor/github.com/jackc/pgproto3/v2/authentication_gss.go
  vendor/github.com/jackc/pgproto3/v2/authentication_gss_continue.go
  vendor/github.com/jackc/pgproto3/v2/authentication_md5_password.go
  vendor/github.com/jackc/pgproto3/v2/authentication_ok.go
  vendor/github.com/jackc/pgproto3/v2/authentication_sasl.go
  vendor/github.com/jackc/pgproto3/v2/authentication_sasl_continue.go
  vendor/github.com/jackc/pgproto3/v2/authentication_sasl_final.go
  vendor/github.com/jackc/pgproto3/v2/backend.go
  vendor/github.com/jackc/pgproto3/v2/backend_key_data.go
  vendor/github.com/jackc/pgproto3/v2/bind.go
  vendor/github.com/jackc/pgproto3/v2/bind_complete.go
  vendor/github.com/jackc/pgproto3/v2/cancel_request.go
  vendor/github.com/jackc/pgproto3/v2/close.go
  vendor/github.com/jackc/pgproto3/v2/close_complete.go
  vendor/github.com/jackc/pgproto3/v2/command_complete.go
  vendor/github.com/jackc/pgproto3/v2/copy_both_response.go
  vendor/github.com/jackc/pgproto3/v2/copy_data.go
  vendor/github.com/jackc/pgproto3/v2/copy_done.go
  vendor/github.com/jackc/pgproto3/v2/copy_fail.go
  vendor/github.com/jackc/pgproto3/v2/copy_in_response.go
  vendor/github.com/jackc/pgproto3/v2/copy_out_response.go
  vendor/github.com/jackc/pgproto3/v2/data_row.go
  vendor/github.com/jackc/pgproto3/v2/describe.go
  vendor/github.com/jackc/pgproto3/v2/empty_query_response.go
  vendor/github.com/jackc/pgproto3/v2/error_response.go
  vendor/github.com/jackc/pgproto3/v2/execute.go
  vendor/github.com/jackc/pgproto3/v2/flush.go
  vendor/github.com/jackc/pgproto3/v2/frontend.go
  vendor/github.com/jackc/pgproto3/v2/function_call.go
  vendor/github.com/jackc/pgproto3/v2/function_call_response.go
  vendor/github.com/jackc/pgproto3/v2/gss_enc_request.go
  vendor/github.com/jackc/pgproto3/v2/gss_response.go
  vendor/github.com/jackc/pgproto3/v2/no_data.go
  vendor/github.com/jackc/pgproto3/v2/notice_response.go
  vendor/github.com/jackc/pgproto3/v2/notification_response.go
  vendor/github.com/jackc/pgproto3/v2/parameter_description.go
  vendor/github.com/jackc/pgproto3/v2/parameter_status.go
  vendor/github.com/jackc/pgproto3/v2/parse.go
  vendor/github.com/jackc/pgproto3/v2/parse_complete.go
  vendor/github.com/jackc/pgproto3/v2/password_message.go
  vendor/github.com/jackc/pgproto3/v2/pgproto3.go
  vendor/github.com/jackc/pgproto3/v2/portal_suspended.go
  vendor/github.com/jackc/pgproto3/v2/query.go
  vendor/github.com/jackc/pgproto3/v2/ready_for_query.go
  vendor/github.com/jackc/pgproto3/v2/row_description.go
  vendor/github.com/jackc/pgproto3/v2/sasl_initial_response.go
  vendor/github.com/jackc/pgproto3/v2/sasl_response.go
  vendor/github.com/jackc/pgproto3/v2/ssl_request.go
  vendor/github.com/jackc/pgproto3/v2/startup_message.go
  vendor/github.com/jackc/pgproto3/v2/sync.go
  vendor/github.com/jackc/pgproto3/v2/terminate.go
  vendor/modules.txt
Labels: approved, size/S, lgtm, jira/valid-bug, jira/valid-reference

#6775 MGMT-18466: grouping all other updates
  .github/dependabot.yml
Labels: approved, size/XS, lgtm, jira/valid-reference

#6772 MGMT-18579: Remove generateConfiguration call and its associated error check
  pkg/staticnetworkconfig/generator.go
  pkg/staticnetworkconfig/generator_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#6774 NO-ISSUE: Fix typo in pgx reference
  go.mod
  go.sum
  vendor/github.com/jackc/pgx/v4/CHANGELOG.md
  vendor/github.com/jackc/pgx/v4/README.md
  vendor/github.com/jackc/pgx/v4/conn.go
  vendor/github.com/jackc/pgx/v4/copy_from.go
  vendor/github.com/jackc/pgx/v4/internal/sanitize/sanitize.go
  vendor/github.com/jackc/pgx/v4/large_objects.go
  vendor/github.com/jackc/pgx/v4/logger.go
  vendor/github.com/jackc/pgx/v4/rows.go
  vendor/github.com/jackc/pgx/v4/stdlib/sql.go
  vendor/github.com/jackc/pgx/v4/tx.go
  vendor/modules.txt
Labels: approved, size/M, lgtm, jira/valid-reference

#6730 MGMT-18635: Restore missing Host by Agent CR
  internal/bminventory/inventory.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/XL, lgtm, jira/valid-reference

#6776 MGMT-16437: drop platform_is_external column
  internal/migrations/20240918161800_drop_cluster_platform_is_external.go
  internal/migrations/20240918161800_drop_cluster_platform_is_external_test.go
  internal/migrations/migrations.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6779 MGMT-18618: Fix local rhsso deployment
  Makefile
  tools/deploy_assisted_installer_configmap.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#6781 NO-ISSUE: Add Dedent function
  internal/common/dedent.go
  internal/common/dedent_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6788 OCPBUGS-42312: Switch to github.com/docker/distribution/reference to mitigate CVE-2024-3727
  go.mod
  go.sum
  internal/cluster/validations/validations.go
  internal/common/common.go
  vendor/github.com/containers/image/v5/docker/reference/README.md
  vendor/github.com/containers/image/v5/docker/reference/regexp-additions.go
  vendor/github.com/docker/distribution/LICENSE
  vendor/github.com/docker/distribution/digestset/set.go
  vendor/github.com/docker/distribution/reference/helpers.go
  vendor/github.com/docker/distribution/reference/normalize.go
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/docker/distribution/reference/regexp.go
  vendor/modules.txt
Labels: approved, size/XL, lgtm, jira/valid-bug, jira/valid-reference

#6786 MGMT-18955: Add 4.18 RHCOS / OCP images
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  data/default_release_sources.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#6783 MGMT-17230: Update scripts and docs to use IDMS instead of ICSP
  deploy/operator/mirror_utils.sh
  deploy/operator/setup_assisted_operator.sh
  deploy/podman/README-disconnected.md
  docs/operator.md
  docs/user-guide/cloud-with-mirror.md
Labels: approved, size/M, lgtm, jira/valid-reference

#6794 NO-ISSUE: [release-ocm-2.9] Bump OCP versions: 4.14, 4.13, 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6797 NO-ISSUE: Explicitly set DEBUG_SERVICE with true value to avoid unexplicit setting
  Makefile
Labels: approved, size/XS, lgtm, jira/valid-reference

#6799 NO-ISSUE: [master] Bump OCP versions: 4.15, 4.14, 4.16, 4.12, 4.17, 4.13
  data/default_os_images.json
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6764 MGMT-17230: Use IDMS when possible
  internal/oc/release.go
  internal/oc/release_test.go
Labels: approved, size/XL, lgtm, jira/valid-reference

#6803 NO-ISSUE: Add linoyaslan to approvers list
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#6800 MGMT-19006, MGMT-19004, MGMT-19007: rremove default LVM for CNV deployments
  internal/operators/cnv/cnv_operator.go
  internal/operators/cnv/cnv_operator_test.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#6798 MGMT-19001, MGMT-19005: Add dhcp and autoconf fields if missing in nmstate YAML + fix the nmstate flow bug on archs other than x86
  internal/bminventory/inventory.go
  internal/ignition/discovery.go
  internal/ignition/discovery_test.go
  internal/ignition/templates/pre-network-manager-config-with-nmstatectl.service
  internal/ignition/templates/pre-network-manager-config.service
  pkg/staticnetworkconfig/generator.go
  pkg/staticnetworkconfig/generator_test.go
  subsystem/infra_env_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6782 MGMT-17229: Use IDMS if possible in CAPI deploy script
  deploy/operator/capi/deploy_capi_cluster.sh
Labels: approved, size/M, lgtm, jira/valid-reference

#6792 NO-ISSUE: [release-ocm-2.11] Bump OCP versions: 4.12, 4.15, 4.14, 4.13, 4.16
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6795 NO-ISSUE: [release-ocm-2.8] Bump OCP versions: 4.13, 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6810 MGMT-17230: Revert use IDMS when possible
  internal/oc/release.go
  internal/oc/release_test.go
Labels: approved, size/XL, lgtm, jira/valid-reference

#6809 NO-ISSUE: [master] Bump OCP versions: 4.15, 4.17
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6838 MGMT-10006: fix agent delete kube-api tests
  subsystem/kubeapi_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#6839 NO-ISSUE: Remove failing NMState kube api test until it is fixed
  subsystem/kubeapi_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#6841 NO-ISSUE: Fix debugging image and docs
  Dockerfile.assisted-service-debug
  docs/dev/debug.md
Labels: approved, kind/dependency-change, size/XS, lgtm, jira/valid-reference

#6773 MGMT-18696: OCI: Download network configuration script from user data
  internal/ignition/templates/discovery.ign
  internal/ignition/templates/iscsi-oci-configure-secondary-nic.sh
  internal/ignition/templates/oci-eval-user-data.service
  internal/ignition/templates/oci-eval-user-data.sh
Labels: approved, size/L, lgtm, jira/valid-reference

#6844 NO-ISSUE: [master] Bump OCP versions: 4.17
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6845 MGMT-19029: Fix issue where validation failed on CNV with ARM host
  internal/hardware/virt/virt.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#6808 ACM-14502: Allow updates to InfraEnv version
  api/vendor/github.com/openshift/assisted-service/models/infra_env_update_params.go
  client/vendor/github.com/openshift/assisted-service/models/infra_env_update_params.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/controller/controllers/infraenv_controller.go
  models/infra_env_update_params.go
  restapi/embedded_spec.go
  subsystem/infra_env_test.go
  subsystem/kubeapi_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/infra_env_update_params.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference
