Repository openshift/assisted-service, pull requests merged in 2024-06, with the labels that each got.

#6388 [release-ocm-2.10] MGMT-18015: Use the static installer for 4.16 nightlies
  internal/oc/release.go
  internal/oc/release_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#6391 NO-ISSUE: [release-ocm-2.9] Bump OCP versions: 4.12, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6390 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.12, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6394 NO-ISSUE: [release-ocm-2.8] Bump OCP versions: 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6398 NO-ISSUE: [backport-release-ocm-2.9] Use archived dnf repositories for centos8 as the current ones are no longer valid
  Dockerfile.assisted-service
  Dockerfile.assisted-service-build
  ci-images/Dockerfile.base
Labels: approved, kind/dependency-change, size/S, lgtm, jira/valid-reference

#6399 NO-ISSUE: [backport-release-ocm-2.8] Use archived dnf repositories for centos8 as the current ones are no longer valid
  Dockerfile.assisted-service
  Dockerfile.assisted-service-build
  ci-images/Dockerfile.base
Labels: approved, kind/dependency-change, size/S, lgtm, jira/valid-reference

#6400 NO-ISSUE: [backport-release-ocm-2.7] Use archived dnf repositories for centos8 as the current ones are no longer valid
  Dockerfile.assisted-service
  Dockerfile.assisted-service-build
Labels: approved, kind/dependency-change, size/XS, lgtm, jira/valid-reference

#6396 MGMT-17523: [backport-release-ocm-2.10] Fail when OS images CPU architecture is missing instead of giving it default value
  internal/versions/osimages.go
  internal/versions/osimages_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6397 NO-ISSUE: Use archived dnf repositories for centos8 as the current ones are no longer valid
  Dockerfile.assisted-service
  hack/container_build_scripts/install_build_deps.sh
  hack/container_build_scripts/replace_dnf_repositories_ref_if_needed.sh
  hack/container_build_scripts/utils.sh
Labels: approved, kind/dependency-change, size/S, lgtm, jira/valid-reference

#6406 [cloud_hotfix_releases] MGMT-18059: Mark OCI as supported integration
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features_platforms.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#6401 MGMT-18046: Create an infraenv for the local cluster during import
  internal/controller/controllers/local_cluster_import_controller.go
  internal/controller/controllers/local_cluster_import_controller_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6382 MGMT-17984: [soft timeout] operators timeout after 10 hours without events
  internal/cluster/finalizing_stages.go
  internal/cluster/finalizing_stages_test.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6174 AGENT-869: Implement a new auth type for ABI
  cmd/agentbasedinstaller/client/main.go
  internal/bminventory/inventory_v2_handlers.go
  internal/cluster/auth.go
  pkg/auth/agent_local_authenticator.go
  pkg/auth/agent_local_authenticator_test.go
  pkg/auth/authenticator.go
  pkg/auth/authenticator_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6407 NO-ISSUE: Adding verification if file exist before sourcing it in forcedns script
  internal/network/manifests_generator.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#6410 MGMT-17794: Make sure that uploaded manifest files have valid filename before extensions
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#6411 MGMT-17802: Ensure that manifest patches may be placed in either `manifests` or `openshift`
  internal/ignition/installmanifests.go
  internal/ignition/installmanifests_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6381 [release-4.15] OCPBUGS-34641: Invalid Pull-Secret when using password which contains a colon character
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
Labels: approved, size/M, lgtm, jira/valid-bug, jira/valid-reference

#6409 NO-ISSUE: [master] Bump OCP versions: 4.15, 4.14, 4.12, 4.16, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6403 MGMT-18059: Mark OCI as supported integration
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features_platforms.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#6418 MGMT-18086: Clean subsystem tests resources correctly
  subsystem/kubeapi_test.go
  subsystem/leader_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6383 MGMT-17300: adding has partition field for disks
  api/vendor/github.com/openshift/assisted-service/models/disk.go
  client/vendor/github.com/openshift/assisted-service/models/disk.go
  models/disk.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/disk.go
Labels: approved, size/XS, api-review, lgtm, jira/valid-reference

#6421 NO-ISSUE: [master] Bump OCP versions: 4.16
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6423 NO-ISSUE: Remove double 'required: false' in openshift template
  openshift/template.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#6415 MGMT-18041: Expose helper to parse uploaded events (on-prem)
  internal/uploader/events_uploader.go
  internal/uploader/events_uploader_test.go
  internal/uploader/extract.go
  internal/uploader/extract_test.go
  pkg/uploader/events.go
  pkg/uploader/models/metadata.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6430 NO-ISSUE: Add Linoy Hadad to OWNER_ALIASES file
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#6429 MGMT-17708: Adjust the logs to show values when registering the cluster
  internal/bminventory/inventory.go
Labels: approved, size/S, lgtm, ok-to-test, jira/valid-reference

#6437 NO-ISSUE: Differentiate between monitoring failures and component issues
  api/v1beta1/agentserviceconfig_types.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go
Labels: approved, size/M, api-review, lgtm, jira/valid-reference

#6428 NO-ISSUE: [master] Bump OCP versions: 4.12, 4.14, 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6438 NO-ISSUE: [Snyk] Fix for 3 vulnerabilities
  dev-requirements.txt
Labels: approved, size/XS, lgtm, jira/valid-reference

#6427 MGMT-18130: Allow infra-operator to start in non OCP kubernetes clusters
  cmd/operator/main.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller.go
  internal/controller/controllers/kube_compat.go
  internal/controller/controllers/kube_compat_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6420 MGMT-18092: infraenv cannot be created while deploying vlan spokes with previous configuration
  pkg/staticnetworkconfig/generator.go
  pkg/staticnetworkconfig/generator_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#6439 NO-ISSUE: Push cluster_installation_failed event each time the state …
  internal/cluster/mock_transition.go
  internal/cluster/statemachine.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6435 NO-ISSUE: Refactor uploader pkg
  internal/uploader/auth_utils.go
  internal/uploader/auth_utils_test.go
  internal/uploader/events_uploader.go
  internal/uploader/events_uploader_test.go
  internal/uploader/extract_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6442 NO-ISSUE: [master] Bump OCP versions: 4.16
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6432 NO-ISSUE: Add omer-vishlitzky to OWNERS_ALIASES file
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#6440 MGMT-18067: Update operator bundle channel to 2.12
  Makefile
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/metadata/annotations.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#6443 [release-ocm-2.11] MGMT-18069: ClusterServiceVersion for release 2.11 branch references "latest" tag
  Makefile
  OWNERS_ALIASES
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/metadata/annotations.yaml
  deploy/operator/setup_assisted_operator.sh
Labels: approved, size/M, lgtm, jira/valid-reference

#6385 MGMT-8356: Deploy assisted-service and its components to kind cluster instead of minikube for local subsystem testing
  Makefile
  deploy/assisted-image-service-service.yaml
  deploy/assisted-service-service.yaml
  deploy/postgres/postgres-deployment.yaml
  deploy/wiremock/wiremock-deployment.yaml
  docs/dev/running-test.md
  hack/kind/kind-config.yaml
  hack/kind/kind.sh
  hack/wait_for_wiremock.sh
  subsystem/leader_test.go
  tools/deploy_assisted_installer_configmap.py
  tools/deploy_image_service.py
  tools/deploy_inventory_service.py
  tools/deploy_postgres.py
  tools/deploy_ui.py
  tools/deploy_wiremock.py
  tools/utils.py
Labels: approved, size/XL, lgtm, jira/valid-reference

#6431 MGMT-18163: Enhancement - Transactional Custom Manifests
  docs/enhancements/transactional-custom-manifests.md
Labels: approved, size/L, lgtm, jira/valid-reference

#6448 NO-ISSUE: Create 'build' directory if missing
  Makefile
Labels: approved, size/XS, lgtm, jira/valid-reference

#6449 NO-ISSUE: [master] Bump OCP versions: 4.14, 4.16, 4.15, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6445 NO-ISSUE: [Snyk] Security upgrade urllib3 from 2.0.7 to 2.2.2
  dev-requirements.txt
Labels: approved, size/XS, lgtm, jira/valid-reference

#6458 NO-ISSUE: Trigger MCE 2.6 snapshot build
  docs/user-guide/README.md
Labels: approved, size/XS, lgtm, jira/valid-reference

#6460 NO-ISSUE: Add pastequo as approver
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#6463 NO-ISSUE: Konflux/fix saas hotfix init
  .tekton/assisted-service-q2vh-pull-request.yaml
  .tekton/assisted-service-q2vh-push.yaml
  .tekton/assisted-service-saas-hotfix-pull-request.yaml
  .tekton/assisted-service-saas-hotfix-push.yaml
Labels: approved, size/XL, lgtm, jira/valid-reference

#6454 NO-ISSUE: Fix konflux git clone params
  .tekton/assisted-service-q2vh-pull-request.yaml
  .tekton/assisted-service-q2vh-push.yaml
  .tekton/assisted-service-saas-main-pull-request.yaml
  .tekton/assisted-service-saas-main-push.yaml
Labels: approved, size/XL, lgtm, jira/valid-reference

#6466 NO-ISSUE: Add missing 'make' command
  docs/dev/running-test.md
Labels: approved, size/XS, lgtm, jira/valid-reference

#6472 NO-ISSUE: Fix Konflux git clone params
  .tekton/assisted-service-saas-main-pull-request.yaml
  .tekton/assisted-service-saas-main-push.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#6467 MGMT-18127: User name and password in a proxy url should be url encoded
  pkg/validations/validations.go
  pkg/validations/validations_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#6495 NO-ISSUE: Increase Konflux git clone depth
  .tekton/assisted-service-saas-main-pull-request.yaml
  .tekton/assisted-service-saas-main-push.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#6496 NO-ISSUE: Increase Konflux git clone depth
  .tekton/assisted-service-saas-hotfix-pull-request.yaml
  .tekton/assisted-service-saas-hotfix-push.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#6501 MGMT-18073: update OCP 4.16 GA version, add 4.17 beta versions
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6502 NO-ISSUE: [master] Bump OCP versions: 4.16, 4.14, 4.12, 4.15
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6494 NO-ISSUE: Retrieve 'subsystem-clean' target as it is used by the QE
  Makefile
Labels: approved, size/XS, lgtm, jira/valid-reference

#6465 OCPBUGS-35932: Allow auth in docker credentials to be empty
  internal/cluster/validations/pull_secret_validation.go
  internal/uploader/auth_utils.go
  internal/uploader/auth_utils_test.go
Labels: approved, size/L, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#6503 NO-ISSUE: Add 4.17 OS/OCP images
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_sources.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#6504 MGMT-8356: Fix postgres deployment script in 'kind' target to set static nodePort correctly, Remove static nodePorts for deployment targets other then 'kind'
  deploy/assisted-image-service-service.yaml
  deploy/assisted-service-service.yaml
  deploy/postgres/postgres-deployment.yaml
  deploy/wiremock/wiremock-deployment.yaml
  tools/deploy_postgres.py
Labels: approved, size/S, lgtm, jira/valid-reference
