Repository openshift/assisted-service, pull requests merged in 2024-11, with the labels that each got.

#6964 NO-ISSUE: [master] Bump OCP versions: 4.16, 4.18, 4.15, 4.14, 4.17, 4.13
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#6957 MGMT-19194: Save Agent inventory and status in annotation
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6961 [cloud_hotfix_releases] MGMT-19177: Update tekton pipelines' tasks to latest versions
  .tekton/assisted-service-saas-hotfix-pull-request.yaml
  .tekton/assisted-service-saas-hotfix-push.yaml
  hack/setup_env.sh
Labels: approved, size/L, lgtm, jira/valid-reference

#6966 NO-ISSUE: allow kind to run with non root user
  docs/dev/operator-on-kind.md
  docs/dev/running_kind_rootless.md
  hack/hub_cluster.sh
Labels: approved, size/M, lgtm, jira/valid-reference

#6970 MGMT-18417: Update openshift/origin-oauth-proxy image
  deploy/monitoring/grafana/assisted-installer-ocp-grafana.yaml
  deploy/monitoring/prometheus/assisted-installer-ocp-prometheus-subscription-instance.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#6969 [cloud_hotfix_releases] cherry-pick MGMT-19129: Migrate assisted-service to Konflux (#6911)
  build_deploy.sh
  build_images.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#6963 MGMT-19218: Remove getting OKD for late-binding InfraEnv
  internal/ignition/discovery.go
  internal/ignition/discovery_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#6971 MGMT-19215: add paused annotation only when BMH is detached
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#6846 MGMT-18863: Fix bug in host event list endpoint
  internal/events/event.go
  internal/events/event_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6973 [release-ocm-2.11] MGMT-19194: Restore hosts using Agent CRs
  internal/bminventory/inventory.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  subsystem/kubeapi_test.go
Labels: approved, size/XL, lgtm, jira/valid-reference

#6976 NO-ISSUE: [master] Bump OCP versions: 4.16, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6981 NO-ISSUE: [master] Bump OCP versions: 4.14, 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6962 MGMT-19158: Always try to cache the ClusterImageSet
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6918 OCPBUGS-42705: Use icsp/idms for oc commands instead of releaseMirror
  internal/installercache/installercache.go
  internal/installercache/installercache_test.go
  internal/oc/release.go
  internal/oc/release_test.go
Labels: approved, size/L, lgtm, jira/valid-bug, jira/valid-reference

#6986 NO-ISSUE: pin compatible gocov version
  hack/setup_env.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#6988 NO-ISSUE: PR to rerun ACM 2.11 publish CI Job
  internal/controller/controllers/agent_reclaimer_test.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#6994 [release-ocm-2.10] MGMT-19218: Remove getting OKD for late-binding InfraEnv
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#6784 AGENT-949 AGENT-951: Add new authz handler and swagger security defn.
  cmd/agentbasedinstaller/client/main.go
  cmd/main.go
  pkg/auth/agent_local_authenticator.go
  pkg/auth/agent_local_authenticator_test.go
  pkg/auth/agent_local_authz_handler.go
  pkg/auth/authenticator.go
  pkg/auth/authz.go
  pkg/auth/local_authenticator.go
  pkg/auth/local_authenticator_test.go
  pkg/auth/none_authenticator.go
  pkg/auth/rhsso_authenticator.go
  pkg/ocm/utils.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  swagger.yaml
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#6995 NO-ISSUE: [master] Bump OCP versions: 4.17, 4.16, 4.15, 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#5996 MGMT-16691: Document OSImageAdditionalParamsRef functionality for infrastructure operator
  docs/operator.md
Labels: approved, size/M, lgtm, jira/valid-reference

#6917 MGMT-19080, MGMT-18590: Enable installation of 3-5 control plane cluster in day1
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  api/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  api/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
  client/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  client/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/common.go
  internal/cluster/mock_cluster_api.go
  internal/cluster/progress_test.go
  internal/cluster/refresh_status_preprocessor.go
  internal/cluster/statemachine.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/cluster/validator.go
  internal/cluster/validator_test.go
  internal/common/common.go
  internal/common/common_test.go
  internal/common/db.go
  internal/common/db_test.go
  internal/common/validations.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostrole_test.go
  internal/host/mock_host_api.go
  internal/host/monitor.go
  internal/host/transition_test.go
  internal/host/validations_test.go
  internal/ignition/installmanifests.go
  internal/ignition/installmanifests_test.go
  internal/operators/common/common.go
  internal/operators/lvm/lvm_operator.go
  internal/operators/odf/odf_operator.go
  internal/operators/odf/odf_operator_test.go
  internal/operators/odf/validation_test.go
  internal/operators/odf/validations.go
  internal/testing/common.go
  models/cluster_create_params.go
  models/v2_cluster_update_params.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  subsystem/kubeapi_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/agentclusterinstall_types.go
  vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
Labels: approved, api-review, lgtm, size/XXL, jira/valid-reference

#6983 MGMT-19230: Handle installation preparation status in statemachine
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/progress_test.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/constants/installation_preparation_status_reasons.go
  internal/host/refresh_status_preprocessor_test.go
  subsystem/cluster_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7003 MGMT-19277: allow mtv to run on SNO clusters
  internal/featuresupport/features_olm_operators.go
  internal/featuresupport/features_olm_operators_test.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#7000 MGMT-19290: iSCSI validation blocks UMN cluster installation
  internal/host/validations_test.go
  internal/host/validator.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6999 MGMT-19280: iSCSI volume should be eligible on day2
  internal/hardware/validator.go
  internal/hardware/validator_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#7004 MGMT-19150: add support for RAID drivers for openshift 4.14 an above
  internal/hardware/validator.go
  internal/hardware/validator_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7006 MGMT-19283: fix output for preflight requirements
  internal/operators/lvm/lvm_operator.go
  subsystem/cluster_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#6965 MGMT-18561: MGMT-18562: Add kube api support for adding per cluster mirror registry in AgentClusterInstall
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  api/hiveextension/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/infraenv_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/agent-install.openshift.io_infraenvs.yaml
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/bminventory/mock_installer_internal.go
  internal/common/common.go
  internal/common/db.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  internal/controller/controllers/mirrorregistry/mirror_registry_parser.go
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
  internal/ignition/discovery.go
  internal/ignition/discovery_test.go
  internal/installcfg/builder/builder.go
  internal/installcfg/builder/builder_test.go
  internal/oc/release.go
  internal/oc/release_test.go
  pkg/mirrorregistries/generator.go
  pkg/mirrorregistries/generator_test.go
  pkg/mirrorregistries/mirror_registry_test.go
  pkg/mirrorregistries/mock_generator.go
  pkg/mirrorregistries/parser.go
  subsystem/kubeapi_test.go
  vendor/github.com/openshift/assisted-service/api/common/common_types.go
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/agentclusterinstall_types.go
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/infraenv_types.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/zz_generated.deepcopy.go
Labels: approved, api-review, lgtm, size/XXL, jira/valid-reference

#7017 NO-ISSUE: [master] Bump OCP versions: 4.16, 4.17, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7001 MGMT-19237: Update validation hook to support external platform
  internal/common/conversions.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_mutating_hook.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_mutating_hook_test.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7016 MGMT-19331: Add `secure_boot_state` to inventory
  api/vendor/github.com/openshift/assisted-service/models/boot.go
  api/vendor/github.com/openshift/assisted-service/models/secure_boot_state.go
  client/vendor/github.com/openshift/assisted-service/models/boot.go
  client/vendor/github.com/openshift/assisted-service/models/secure_boot_state.go
  models/boot.go
  models/secure_boot_state.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/boot.go
  vendor/github.com/openshift/assisted-service/models/secure_boot_state.go
Labels: approved, size/S, api-review, lgtm, jira/valid-reference

#7024 NO-ISSUE: Remove unused Konflux references
  .tekton/assisted-service-q2vh-pull-request.yaml
  .tekton/assisted-service-q2vh-push.yaml
Labels: approved, size/XL, lgtm, jira/valid-reference

#7023 MGMT-19338, MGMT-19080, MGMT-18590, NO-ISSUE: Patches for non-standard HA OCP Control Plane PR
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  client/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster_test.go
  internal/cluster/transition_test.go
  internal/cluster/validator.go
  internal/cluster/validator_test.go
  internal/common/common.go
  internal/common/db.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/featuresupport/feature_support_level.go
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features_misc.go
  internal/featuresupport/features_olm_operators.go
  internal/featuresupport/features_platforms.go
  internal/host/monitor.go
  internal/migrations/20241122160000_update_new_column_control_plane_count_value_for_existing_cluster_records.go
  internal/migrations/20241122160000_update_new_column_control_plane_count_value_for_existing_cluster_records_test.go
  internal/migrations/migrations.go
  internal/operators/odf/odf_operator.go
  internal/operators/odf/validation_test.go
  internal/operators/odf/validations.go
  internal/testing/common.go
  models/feature_support_level_id.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/api/common/common_types.go
  vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
Labels: approved, size/XL, api-review, lgtm, jira/valid-reference

#7018 NO-ISSUE: Allow configuring suported GPUs
  internal/operators/openshiftai/openshift_ai_config.go
  internal/operators/openshiftai/openshift_ai_operator.go
  internal/operators/openshiftai/openshift_ai_operator_test.go
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#7032 MGMT-19369: Restrict non-standard HA OCP control plane feature to x86_64 architecture
  internal/bminventory/inventory_test.go
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features_misc.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7002 MGMT-18288: Don't copy BMH and Machine to Baremetal Spoke Cluster without MAPI
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/capabilities.go
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  internal/controller/controllers/common.go
  internal/installcfg/installcfg.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7026 MGMT-19192: Add current stage when restoring host by Agent
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7035 NO-ISSUE: Add giladravid16 to approvers list
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#7033 MGMT-19371: Add downstream dockerfiles for mce
  Dockerfile.assisted-service-rhel8-mce
  Dockerfile.assisted-service-rhel9-mce
Labels: approved, kind/dependency-change, size/L, lgtm, jira/valid-reference

#7030 MGMT-19360: do not monitor hosts with status installed
  internal/host/monitor.go
  internal/host/monitor_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7039 MGMT-19388: Add NTP sources to generated install-config.yaml - ACM 2.12
  internal/installcfg/builder/builder.go
  internal/installcfg/installcfg.go
  internal/provider/baremetal/installConfig.go
  internal/provider/baremetal/installConfig_test.go
  internal/provider/baremetal/suite_test.go
  internal/provider/base.go
  internal/provider/external/base.go
  internal/provider/mock_base_provider.go
  internal/provider/none/installConfig.go
  internal/provider/nutanix/installConfig.go
  internal/provider/registry/mock_providerregistry.go
  internal/provider/registry/registry.go
  internal/provider/registry/registry_test.go
  internal/provider/vsphere/installConfig.go
Labels: approved, size/L, lgtm, jira/valid-reference
