Repository openshift/assisted-service, pull requests merged in 2024-04, with the labels that each got.

#6127 [release-ocm-2.9] NO-ISSUE: replace postgres images as current one disappeared from quay
  Makefile
  config/manager/manager.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/pod-persistent-disconnected.yml
  deploy/podman/pod-persistent.yml
  deploy/podman/pod.yml
  deploy/podman/pod_tls.yml
  deploy/postgres/postgres-deployment-ephemeral.yaml
  deploy/postgres/postgres-deployment.yaml
  docs/dev/testing.md
  internal/common/common_unitest_db.go
  internal/controller/controllers/images.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6146 NO-ISSUE: Add doc for iPXE HTTP
  docs/operator.md
Labels: approved, size/M, lgtm, jira/valid-reference

#6149 OCPBUGS-31631: Deploy dual stack with IPv6 on top of bond/vlan fails
  internal/network/connectivity_groups.go
  internal/network/connectivity_groups_test.go
Labels: approved, size/M, lgtm, jira/valid-bug, jira/valid-reference

#6151 NO-ISSUE: replace minio quay.io image repository
  deploy/s3/deployment.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#6157 NO-ISSUE: Bump OCP versions: 4.15, 4.14, 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6161 NO-ISSUE: Add my account as an approver
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#6145 MGMT-17412: Change fallbck behavior when error occuring in OpenShift Release Syncer
  cmd/main.go
  internal/releasesources/release_sources.go
  internal/releasesources/release_sources_test.go
  internal/versions/common.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6167 NO-ISSUE: Add more accounts as approvers
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#6168 NO-ISSUE: Add missing accounts for PR approvals
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#6129 [release-ocm-2.7] NO-ISSUE: replace postgres images as current one disappeared from quay
  Makefile
  config/manager/manager.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/pod-persistent-disconnected.yml
  deploy/podman/pod-persistent.yml
  deploy/podman/pod.yml
  deploy/podman/pod_tls.yml
  deploy/postgres/postgres-deployment-ephemeral.yaml
  deploy/postgres/postgres-deployment.yaml
  docs/dev/testing.md
  internal/common/common_unitest_db.go
Labels: approved, size/S, lgtm, jira/valid-reference

#6169 [release-ocm-2.9] NO-ISSUE: Add missing accounts for PR approvals
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#6191 MGMT-17541: Replace broken golangci reference
  Dockerfile.assisted-service-build
Labels: approved, kind/dependency-change, size/XS, lgtm, jira/valid-reference

#6195 MGMT-17541: Replace broken golangci reference
  Dockerfile.assisted-service-build
Labels: approved, kind/dependency-change, size/XS, lgtm, jira/valid-reference

#6196 MGMT-17541: Replace broken golangci reference
  Dockerfile.assisted-service-build
Labels: approved, kind/dependency-change, size/XS, lgtm, jira/valid-reference

#6197 MGMT-17541: Replace broken golangci reference
  Dockerfile.assisted-service-build
Labels: approved, kind/dependency-change, size/XS, lgtm, jira/valid-reference

#6163 MGMT-17489: Fix disconnected CAPI tests
  deploy/operator/capi/deploy_capi_cluster.sh
Labels: approved, size/S, lgtm, jira/valid-reference

#6162 NO-ISSUE: Prevent false positive host connectivity
  internal/network/connectivity_groups.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#6171 MGMT-16587: Bump runc to v1.1.12 to mitigate CVE-2024-21626
  go.mod
  go.sum
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/modules.txt
Labels: approved, size/M, lgtm, jira/valid-reference

#6079 MGMT-17180: Add a LocalClusterImportController
  api/v1beta1/agentserviceconfig_types.go
  cmd/main.go
  cmd/operator/main.go
  config/rbac/role.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  go.mod
  go.sum
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/local_cluster_import_controller.go
  internal/controller/controllers/local_cluster_import_controller_test.go
  pkg/localclusterimport/import_local_cluster.go
  pkg/localclusterimport/import_local_cluster_test.go
  pkg/localclusterimport/local_cluster_import_operations.go
  pkg/localclusterimport/local_cluster_import_operations_mocks.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go
  vendor/modules.txt
  vendor/open-cluster-management.io/api/LICENSE
  vendor/open-cluster-management.io/api/cluster/v1/0000_00_clusters.open-cluster-management.io_managedclusters.crd.yaml
  vendor/open-cluster-management.io/api/cluster/v1/doc.go
  vendor/open-cluster-management.io/api/cluster/v1/register.go
  vendor/open-cluster-management.io/api/cluster/v1/types.go
  vendor/open-cluster-management.io/api/cluster/v1/zz_generated.deepcopy.go
  vendor/open-cluster-management.io/api/cluster/v1/zz_generated.swagger_doc_generated.go
Labels: approved, kind/dependency-change, api-review, lgtm, size/XXL, jira/valid-reference

#6165 MGMT-17414: Changing requirements for LVM on 4.16
  internal/operators/lvm/config.go
  internal/operators/lvm/lvm_operator.go
  internal/operators/lvm/lvm_operator_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#6199 NO-ISSUE: Bump OCP versions: 4.16, 4.15, 4.12, 4.14, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6180 MGMT-16587: Bump runc to v1.1.12 to mitigate CVE-2024-21626
  go.mod
  go.sum
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/modules.txt
Labels: approved, size/S, lgtm, jira/valid-reference

#6203 MGMT-17549: Bump runc to v1.1.12 to mitigate CVE-2024-21626
  go.mod
  go.sum
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/modules.txt
Labels: approved, size/M, lgtm, jira/valid-reference

#6190 MGMT-17468: Use x86_64 over amd64 and arm64 over aarch64 for CPU architecture of both release and OS images to comply with ABI current behavior
  internal/versions/common.go
  internal/versions/common_test.go
  internal/versions/kube_api_versions.go
  internal/versions/kube_api_versions_test.go
  internal/versions/osimages.go
  internal/versions/osimages_test.go
  internal/versions/rest_api_versions.go
  internal/versions/rest_api_versions_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6170 MGMT-16587: Bump runc version to 1.1.12 to Mitigate CVE-2024-21626
  go.mod
  go.sum
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/modules.txt
Labels: approved, size/M, api-review, lgtm, jira/valid-reference

#6201 MGMT-17528: Add 4.15 OS images for ACM 2.9
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6185 MGMT-17513: Change the latest release image retrieved in GetReleaseImage using major.minor OpenShift version to latest non-beta release image if exists, or latest beta release image otherwise
  internal/versions/rest_api_versions.go
  internal/versions/rest_api_versions_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6142 MGMT-17313: Create day 2 BMH and Machine for control plane nodes
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6124 MGMT-17365: Add support for setting agent labels in BMH as annotations
  docs/hive-integration/README.md
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  internal/controller/controllers/crd_utils.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6184 MGMT-17503: Fix the cpu architectures retrieved in ../openshift-versions endpoint
  internal/common/version.go
  internal/common/version_test.go
  internal/versions/api.go
  internal/versions/api_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6208 Revert "MGMT-17549: Bump runc version to 1.1.12 to Mitigate CVE-2024-21626
  go.mod
  go.sum
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, size/M, lgtm, jira/valid-reference

#6186 MGMT-17515: Fix the CPU architecture query for in GetReleaseImage to having the necessary CPU architecture in the list and the list must be of size one to exclude multi architecture release images
  internal/versions/rest_api_versions.go
  internal/versions/rest_api_versions_test.go
  subsystem/cluster_v2_test.go
  subsystem/feature_support_levels_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6211 MGMT-17549: Bump runc version to 1.1.12 to Mitigate CVE-2024-21626
  go.mod
  go.sum
  vendor/github.com/opencontainers/runc/libcontainer/user/user.go
  vendor/github.com/openshift/api/build/v1/generated.proto
  vendor/github.com/openshift/api/build/v1/types.go
  vendor/github.com/openshift/api/build/v1/zz_generated.swagger_doc_generated.go
  vendor/modules.txt
Labels: approved, size/M, lgtm, jira/valid-reference

#6218 MGMT-17558: Allow installation on iSCSI volume
  internal/hardware/mock_validator.go
  internal/hardware/validator.go
  internal/hardware/validator_test.go
  internal/host/host_test.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/transition_test.go
  internal/host/validations_test.go
  internal/host/validator.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6209 NO-ISSUE: Change only-latest api response to compare versions according to pre-release suffix as well instead of just base version
  internal/common/version.go
  internal/common/version_test.go
  internal/versions/api.go
  internal/versions/api_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6212 MGMT-17518: Bump x/net to 0.24.0 to mitigate CVE-2023-45288 (api go.mod)
  api/go.mod
  api/go.sum
  api/vendor/golang.org/x/net/http2/databuffer.go
  api/vendor/golang.org/x/net/http2/frame.go
  api/vendor/golang.org/x/net/http2/go111.go
  api/vendor/golang.org/x/net/http2/go115.go
  api/vendor/golang.org/x/net/http2/go118.go
  api/vendor/golang.org/x/net/http2/not_go111.go
  api/vendor/golang.org/x/net/http2/not_go115.go
  api/vendor/golang.org/x/net/http2/not_go118.go
  api/vendor/golang.org/x/net/http2/pipe.go
  api/vendor/golang.org/x/net/http2/server.go
  api/vendor/golang.org/x/net/http2/testsync.go
  api/vendor/golang.org/x/net/http2/transport.go
  api/vendor/golang.org/x/net/idna/go118.go
  api/vendor/golang.org/x/net/idna/idna10.0.0.go
  api/vendor/golang.org/x/net/idna/idna9.0.0.go
  api/vendor/golang.org/x/net/idna/pre_go118.go
  api/vendor/golang.org/x/net/idna/tables10.0.0.go
  api/vendor/golang.org/x/net/idna/tables11.0.0.go
  api/vendor/golang.org/x/net/idna/tables12.0.0.go
  api/vendor/golang.org/x/net/idna/tables13.0.0.go
  api/vendor/golang.org/x/net/idna/tables15.0.0.go
  api/vendor/golang.org/x/net/idna/tables9.0.0.go
  api/vendor/golang.org/x/net/idna/trie12.0.0.go
  api/vendor/golang.org/x/net/idna/trie13.0.0.go
  api/vendor/golang.org/x/text/secure/bidirule/bidirule10.0.0.go
  api/vendor/golang.org/x/text/secure/bidirule/bidirule9.0.0.go
  api/vendor/golang.org/x/text/unicode/bidi/tables10.0.0.go
  api/vendor/golang.org/x/text/unicode/bidi/tables11.0.0.go
  api/vendor/golang.org/x/text/unicode/bidi/tables12.0.0.go
  api/vendor/golang.org/x/text/unicode/bidi/tables13.0.0.go
  api/vendor/golang.org/x/text/unicode/bidi/tables15.0.0.go
  api/vendor/golang.org/x/text/unicode/bidi/tables9.0.0.go
  api/vendor/golang.org/x/text/unicode/norm/tables10.0.0.go
  api/vendor/golang.org/x/text/unicode/norm/tables11.0.0.go
  api/vendor/golang.org/x/text/unicode/norm/tables12.0.0.go
  api/vendor/golang.org/x/text/unicode/norm/tables13.0.0.go
  api/vendor/golang.org/x/text/unicode/norm/tables15.0.0.go
  api/vendor/golang.org/x/text/unicode/norm/tables9.0.0.go
  api/vendor/modules.txt
Labels: approved, size/M, api-review, lgtm, jira/valid-reference

#6227 MGMT-17620: Change the way multi-arch release images are handled in RestAPI flow
  internal/versions/rest_api_versions.go
  internal/versions/rest_api_versions_test.go
  subsystem/cluster_v2_test.go
  subsystem/feature_support_levels_test.go
  subsystem/operators_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6231 NO-ISSUE: Update OKD images to 4.16
  data/default_okd_os_images.json
  data/default_okd_release_images.json
  deploy/podman/okd-configmap.yml
Labels: approved, size/S, lgtm, jira/valid-reference

#6241 NO-ISSUE: Change bare metal host CRD name to a non-uuid format
  subsystem/kubeapi_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6242 NO-ISSUE: Change bare metal host CRD name to a non-uuid format
  subsystem/kubeapi_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6158 MGMT-17413: Change pull secret validation on register/update cluster/infraenv to run only against the required images
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/cluster/validations/mock_pull_secret_validation.go
  internal/cluster/validations/pull_secret_validation.go
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/infraenv_controller_test.go
  internal/controller/controllers/pullsecret_handler.go
Labels: approved, size/XL, lgtm, jira/valid-reference
