Repository openshift/assisted-service, pull requests merged in 2024-02, with the labels that each got.

#5939 NO-ISSUE: Bump OCP versions: 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#5938 [release-ocm-2.7] MGMT-16719: Allow domain names starting with a number (#5914)
  pkg/validations/validations.go
  pkg/validations/validations_test.go
  subsystem/cluster_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5937 [release-ocm-2.8] MGMT-16718: Allow domain names starting with a number (#5914)
  pkg/validations/validations.go
  pkg/validations/validations_test.go
  subsystem/cluster_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5941 MGMT-16739: CNV and MCE should be disabled when select platform Nutanix
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features_olm_operators.go
  internal/featuresupport/features_olm_operators_test.go
  internal/featuresupport/features_platforms.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5944 NO-ISSUE: Bump OCP versions: 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#5932 NO-ISSUE: Fix CI gather script for baremetal operator
  deploy/operator/gather.sh
Labels: approved, size/S, lgtm, jira/valid-reference

#5945 MGMT-16757: CNV should be disabled when select platform vSphere
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features_olm_operators.go
  internal/featuresupport/features_platforms.go
Labels: approved, size/S, lgtm, jira/valid-reference

#5947 NO-ISSUE: Bump OCP versions: 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#5931 MGMT-16649: Add Ignition Endpoint Headers to Host and Agent APIs
  api/v1beta1/agent_types.go
  api/v1beta1/zz_generated.deepcopy.go
  api/vendor/github.com/openshift/assisted-service/models/host_update_params.go
  api/vendor/github.com/openshift/assisted-service/models/ignition_endpoint_http_headers_params.go
  client/vendor/github.com/openshift/assisted-service/models/host_update_params.go
  client/vendor/github.com/openshift/assisted-service/models/ignition_endpoint_http_headers_params.go
  config/crd/bases/agent-install.openshift.io_agents.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
  internal/common/db.go
  models/host_update_params.go
  models/ignition_endpoint_http_headers_params.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/api/v1beta1/agent_types.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/assisted-service/models/host_update_params.go
  vendor/github.com/openshift/assisted-service/models/ignition_endpoint_http_headers_params.go
Labels: approved, size/M, api-review, lgtm, jira/valid-reference

#5940 MGMT-16721: handle hosts with no luks
  internal/host/hostcommands/tang_connectivity_check_cmd.go
  internal/host/hostcommands/tang_connectivity_check_cmd_test.go
  internal/host/validator.go
Labels: approved, size/L, lgtm, jira/valid-reference

#5951 MGMT-14226: Upgrade docker to 20.10.24 for CVE-2023-28842
  go.mod
  go.sum
  vendor/github.com/docker/docker/api/types/container/hostconfig_unix.go
  vendor/github.com/docker/docker/api/types/filters/parse.go
  vendor/github.com/docker/docker/api/types/registry/registry.go
  vendor/modules.txt
Labels: approved, size/XS, lgtm, jira/valid-reference

#5963 NO-ISSUE: Bump OCP versions: 4.13, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#5962 [release-ocm-2.9] MGMT-14226: Upgrade docker to 20.10.24 for CVE-2023-28842 (#5951)
  go.mod
  go.sum
  vendor/github.com/docker/docker/api/types/container/hostconfig_unix.go
  vendor/github.com/docker/docker/api/types/filters/parse.go
  vendor/github.com/docker/docker/api/types/registry/registry.go
  vendor/modules.txt
Labels: approved, size/XS, lgtm, jira/valid-reference

#5959 MGMT-16791: disable VipAutoAllocation for 4.15 and above
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features_networking.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5928 MGMT-16684: Make OLM finalizing stages behave as soft timeouts even if soft timeouts are not enabled
  api/vendor/github.com/openshift/assisted-service/models/finalizing_stage.go
  client/vendor/github.com/openshift/assisted-service/models/finalizing_stage.go
  docs/events.yaml
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/finalizing_stages.go
  internal/cluster/statemachine.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/common/events/events.go
  models/finalizing_stage.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/finalizing_stage.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#5935 MGMT-16704: Add organization capability to control soft timeouts
  api/vendor/github.com/openshift/assisted-service/models/cluster.go
  client/vendor/github.com/openshift/assisted-service/models/cluster.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/host/conditions.go
  internal/host/transition_test.go
  models/cluster.go
  pkg/ocm/utils.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster.go
Labels: approved, size/M, api-review, lgtm, jira/valid-reference

#5970 [release-ocm-2.9] ACM-9506: Remove unecessary dependency on go-git (#5913)
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/L, lgtm, jira/valid-reference

#5972 NO-ISSUE: Change bare metal host CRD name to a non-uuid format
  subsystem/kubeapi_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5967 MGMT-16523: Set ABI deployment type for on-prem data collection
  cmd/main.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5971 NO-ISSUE: Bump OCP versions: 4.12, 4.11
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#5934 MGMT-16649: Use new ignition endpoint HTTP headers when requesting Ignition
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/controller/controllers/agent_controller.go
  internal/host/host.go
  internal/host/hostcommands/api_vip_connectivity_check_cmd.go
  internal/host/mock_host_api.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/ignition/mock_ignition.go
  internal/ignition/templates/node.ign
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#5911 MGMT-16625: Make host connection timeout soft
  api/vendor/github.com/openshift/assisted-service/models/host.go
  client/vendor/github.com/openshift/assisted-service/models/host.go
  internal/host/common.go
  internal/host/conditions.go
  internal/host/host_test.go
  internal/host/mock_transition.go
  internal/host/refresh_status_preprocessor.go
  internal/host/statemachine.go
  internal/host/transition.go
  internal/host/transition_test.go
  models/host.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/host.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#5946 MGMT-16588: Adding host with incompatible platform to day2 cluster should fail
  internal/host/validations_test.go
  internal/host/validator.go
  subsystem/day2_cluster_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#5900 MGMT-16627: add OCP 4.13 images
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#5898 MGMT-16332: fix validation for LVM multinode
  internal/bminventory/inventory.go
  internal/host/hostutil/test_utils.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/cnv/cnv_operator_test.go
  internal/operators/lvm/config.go
  internal/operators/lvm/lvm_operator.go
  internal/operators/lvm/lvm_operator_test.go
  internal/operators/lvm/manifest.go
  internal/operators/lvm/manifests_test.go
  internal/operators/manager.go
Labels: approved, size/XL, lgtm, jira/valid-reference

#5988 NO-ISSUE: Fix subsystem test for invalid nmstate config error message
  subsystem/kubeapi_test.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#5990 NO-ISSUE: Bump OCP versions: 4.14, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#5987 [release-4.14] MGMT-16517: Add Env Var Deployment Type & Set ABI
  cmd/main.go
  deploy/assisted-service.yaml
  deploy/podman/configmap-disconnected.yml
  deploy/podman/configmap.yml
  deploy/podman/configmap_tls.yml
  internal/uploader/events_uploader.go
  internal/uploader/events_uploader_test.go
  internal/uploader/uploader.go
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#5995 NO-ISSUE: Bump OCP versions: 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#5981 MGMT-4458: Remove status change from old CompleteInstallation API
  api/vendor/github.com/openshift/assisted-service/models/finalizing_stage.go
  client/vendor/github.com/openshift/assisted-service/models/finalizing_stage.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/finalizing_stages.go
  internal/cluster/mock_cluster_api.go
  internal/cluster/statemachine.go
  internal/cluster/transition.go
  models/finalizing_stage.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/finalizing_stage.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#5998 MGMT-16926: fix validation bug + allow CNV and LVM multi node
  internal/operators/lvm/config.go
  internal/operators/lvm/lvm_operator.go
  internal/operators/lvm/lvm_operator_test.go
  internal/operators/manager.go
  internal/operators/manager_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6006 NO-ISSUE: Bump OCP versions: 4.13, 4.12, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6004 AGENT-860: Add command to import cluster for agent-based-installer
  cmd/agentbasedinstaller/client/main.go
  cmd/agentbasedinstaller/import.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6013 NO-ISSUE: Add environment variable ENABLE_SKIP_MCO_REBOOT to openshift/template.yaml
  openshift/template.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#6011 OCPBUGS-29818: Spoke will not boot after agent install with error "Failed to mount /sysroot
  internal/feature/flags.go
Labels: approved, size/XS, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#6009 MGMT-16995 fixing lvm requirement message
  internal/operators/lvm/lvm_operator.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#6016 [release-4.15] MGMT-16517: Add Env Var Deployment Type & Set ABI
  cmd/main.go
  deploy/assisted-service.yaml
  deploy/podman/configmap-disconnected.yml
  deploy/podman/configmap.yml
  deploy/podman/configmap_tls.yml
  internal/uploader/events_uploader.go
  internal/uploader/events_uploader_test.go
  internal/uploader/uploader.go
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6010 OCPBUGS-29772: All nodes fail to become managed when installConfigOverrides defined
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/S, lgtm, jira/valid-bug, jira/valid-reference

#6019 NO-ISSUE: Bump OCP versions: 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6023 MGMT-16882: Update operator bundle channel to 2.11
  Makefile
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/metadata/annotations.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#6028 [release-ocm-2.10] MGMT-16878: Set restricted list of approvers
  OWNERS_ALIASES
Labels: approved, size/S, lgtm, jira/valid-reference

#6029 [release-ocm-2.10] MGMT-16884: ClusterServiceVersion for release 2.10 branch references "latest" tag
  Makefile
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/metadata/annotations.yaml
  deploy/operator/setup_assisted_operator.sh
Labels: approved, size/M, lgtm, jira/valid-reference

#6032 NO-ISSUE: Bump OCP versions: 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6021 MGMT-17008: fix lvm host requirement
  internal/operators/lvm/lvm_operator.go
  internal/operators/lvm/lvm_operator_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#6038 NO-ISSUE: Bump OCP versions: 4.15, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6035 MGMT-16620: Update OCP 4.15 GA in release images
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
  subsystem/cluster_test.go
  subsystem/host_test.go
  subsystem/infra_env_test.go
  subsystem/operators_test.go
  subsystem/subsystem_suite_test.go
  subsystem/utils_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6040 MGMT-17095: Disable local cluster import
  cmd/main.go
Labels: approved, size/XS, lgtm, jira/valid-reference
