Repository openshift/assisted-service, pull requests merged in 2024-07, with the labels that each got.

#6499 MGMT-18269: Reset finalizing stage in DB while resetting cluster
  internal/cluster/transition.go
  internal/cluster/transition_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6508 NO-ISSUE: [release-ocm-2.9] Bump OCP versions: 4.12, 4.14, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6507 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.12, 4.14, 4.15, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6509 NO-ISSUE: [release-ocm-2.8] Bump OCP versions: 4.12, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6505 MGMT-18286: Internal Documentation for using and testing multipath
  docs/dev/multipath.md
  docs/dev/multipath.png
Labels: approved, size/L, lgtm, jira/valid-reference

#6511 NO-ISSUE: [master] Bump OCP versions: 4.15
  data/default_os_images.json
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6446 MGMT-18131: Make application work on non-OCP kubernetes
  api/v1beta1/agentserviceconfig_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
  config/crd/bases/agent-install.openshift.io_hypershiftagentserviceconfigs.yaml
  config/crd/resources.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  config/rbac/role.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agentserviceconfigs.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_hypershiftagentserviceconfigs.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  docs/dev/operator-on-kind.md
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_storage_validation_test.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/zz_generated.deepcopy.go
Labels: approved, size/XL, api-review, lgtm, jira/valid-reference

#6544 NO-ISSUE: Mount emptyDir for data in image service
  deploy/assisted-image-service.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#6547 NO-ISSUE: [master] Bump OCP versions: 4.17, 4.16
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6549 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6536 NO-ISSUE: Add renovate config to limit number of PR
  renovate.json
Labels: approved, size/S, lgtm, jira/valid-reference

#6532 MGMT-17893: Don't destroy cluster on detach
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6558 NO-ISSUE: [master] Bump OCP versions: 4.17, 4.16, 4.15
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6561 NO-ISSUE: Fix kind deploy
  docs/dev/operator-on-kind.md
  hack/crds/metal3.io_preprovisioningimages.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#6533 MGMT-17478: Use ICC config secret for converged flow info when available
  internal/controller/controllers/bmo_utils.go
  internal/controller/controllers/bmo_utils_test.go
  internal/controller/controllers/mock_bmo_utils.go
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
  internal/oc/mock_release.go
  internal/oc/release.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6560 NO-ISSUE: Fix skipper configuration
  skipper.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#6551 NO-ISSUE: [Snyk] Security upgrade zipp from 3.15.0 to 3.19.1
  dev-requirements.txt
Labels: approved, size/XS, lgtm, jira/valid-reference

#6538 [cloud_hotfix_releases] NO-ISSUE: Add renovate config
  renovate.json
Labels: approved, size/S, lgtm, jira/valid-reference

#6457 MGMT-18165: Make manifest metadata storage more transactional in nature
  api/vendor/github.com/openshift/assisted-service/models/manifest.go
  client/vendor/github.com/openshift/assisted-service/models/manifest.go
  cmd/main.go
  go.mod
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/constants/manifests.go
  internal/ignition/installmanifests.go
  internal/ignition/installmanifests_test.go
  internal/manifests/api/interface.go
  internal/manifests/api/mock_manifests_api.go
  internal/manifests/api/mock_manifests_internal.go
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
  models/manifest.go
  pkg/generator/generator.go
  pkg/s3wrapper/client.go
  pkg/s3wrapper/filesystem.go
  pkg/s3wrapper/filesystem_test.go
  pkg/s3wrapper/mock_s3wrapper.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  subsystem/manifests_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/manifest.go
Labels: approved, api-review, lgtm, size/XXL, jira/valid-reference

#6568 NO-ISSUE: [master] Bump OCP versions: 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6569 NO-ISSUE: Fix subsystem tests in the CI - Wiremock stubs script is failing to reach Wiremock pod occasionally
  tools/deploy_wiremock.py
Labels: approved, size/S, lgtm, jira/valid-reference

#6553 MGMT-18105: Update registry.svc.ci.openshift.org to registry.ci.openshift.org (bugzilla #6552)
  api/v1beta1/agentserviceconfig_types.go
  config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
  config/crd/bases/agent-install.openshift.io_hypershiftagentserviceconfigs.yaml
  config/crd/resources.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agentserviceconfigs.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_hypershiftagentserviceconfigs.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go
Labels: approved, size/M, api-review, lgtm, do-not-merge/hold, ok-to-test, jira/valid-reference

#6572 NO-ISSUE: Exclude vendor directory from snyk code analysis
  .snyk
Labels: approved, size/XS, lgtm, jira/valid-reference

#6575 NO-ISSUE: [release-ocm-2.9] Bump OCP versions: 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6574 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.14, 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6577 [release-ocm-2.11] NO-ISSUE: Fix subsystem tests in the CI - WireMock stubs script is failing to reach WireMock from time to time
  Makefile
  tools/deploy_wiremock.py
Labels: approved, size/M, lgtm, jira/valid-reference

#6579 MGMT-18333: Remove the python client from the image
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, size/S, lgtm, jira/valid-reference

#6524 [release-ocm-2.10] OCPBUGS-36504: Allow auth in docker credentials to be empty
  internal/cluster/validations/validations.go
  internal/uploader/auth_utils.go
Labels: approved, size/M, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#6573 NO-ISSUE: [release-ocm-2.11] Bump OCP versions: 4.14, 4.15, 4.16
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6564 MGMT-18305: Add certs to ingress when deploying in non-OCP clusters
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/kube_compat.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6583 [release-ocm-2.10] MGMT-18333: Remove the python client from the image
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, size/S, lgtm, jira/valid-reference

#6581 [release-ocm-2.9] MGMT-18333: Remove the python client from the image
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, size/S, lgtm, jira/valid-reference

#6582 [release-ocm-2.8] MGMT-18333: Remove the python client from the image
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, size/S, lgtm, jira/valid-reference

#6578 MGMT-18380: Update package naming in generator_test.go for black-box testing methodology
  pkg/staticnetworkconfig/generator_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6484 KONFLUX-1611: Add labels, licenses & user to Dockerfile
  .tekton/assisted-service-saas-main-pull-request.yaml
  .tekton/assisted-service-saas-main-push.yaml
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, size/M, lgtm, jira/valid-reference

#6586 NO-ISSUE: Remove unused extracter struct
  cmd/main.go
  internal/cluster/transition_test.go
  internal/host/hostrole_test.go
  internal/host/transition_test.go
  internal/oc/extract.go
  internal/oc/extract_test.go
  internal/oc/mock_extract.go
  internal/operators/builder.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/cnv/cnv_operator_test.go
  internal/operators/cnv/manifests_test.go
  internal/operators/lvm/lvm_operator.go
  internal/operators/lvm/lvm_operator_test.go
  internal/operators/lvm/manifests_test.go
  internal/operators/manager_test.go
  internal/operators/odf/manifests_test.go
  internal/operators/odf/odf_operator.go
  internal/operators/odf/odf_operator_test.go
  internal/operators/odf/validation_test.go
  subsystem/operators_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6570 MGMT-18155: handle state of day2 node in Done stage
  internal/host/statemachine.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#6576 NO-ISSUE: [Snyk] Security upgrade setuptools from 59.2.0 to 70.0.0
  dev-requirements.txt
Labels: approved, size/XS, lgtm, jira/valid-reference

#6593 NO-ISSUE: Fix python client generation
  hack/generate.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#6591 MGMT-18411: Add NTP sources to discovery environment
  internal/ignition/discovery.go
  internal/ignition/discovery_test.go
  internal/ignition/templates/add-ntp-sources.service
  internal/ignition/templates/add-ntp-sources.sh
  internal/ignition/templates/discovery.ign
Labels: approved, size/L, lgtm, jira/valid-reference

#6588 NO-ISSUE: Fix OKD podman deploy
  data/default_public_container_registries.txt
  deploy/podman/README.md
  deploy/podman/configmap.yml
  deploy/podman/okd-configmap.yml
Labels: approved, size/S, lgtm, jira/valid-reference

#6590 MGMT-18418: Revert "Add certs to ingress when deploying in non-OCP clusters (#6564)"
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/kube_compat.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6587 NO-ISSUE: Adjust permissions on /data directory
  Dockerfile.assisted-service
Labels: approved, size/S, lgtm, jira/valid-reference

#6594 NO-ISSUE: Add -L option to curl command to follow redirects
  deploy/operator/mirror_utils.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#6598 NO-ISSUE: [master] Bump OCP versions: 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6607 NO-ISSUE: [release-ocm-2.11] Bump OCP versions: 4.15, 4.14, 4.16, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6608 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.15, 4.14, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6610 NO-ISSUE: [release-ocm-2.8] Bump OCP versions: 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6609 NO-ISSUE: [release-ocm-2.9] Bump OCP versions: 4.14, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6600 MGMT-17773: Enforce go modules tidy
  docs/user-guide/support-level.md
  hack/Makefile
Labels: approved, size/S, lgtm, jira/valid-reference

#6606 MGMT-18448: Allow local cluster import to be disabled.
  api/v1beta1/agentserviceconfig_types.go
  internal/controller/controllers/local_cluster_import_controller.go
  internal/controller/controllers/local_cluster_import_controller_test.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go
Labels: approved, size/M, api-review, lgtm, jira/valid-reference

#6611 NO-ISSUE: [master] Bump OCP versions: 4.17
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6599 NO-ISSUE: Tidy golang dependencies before vendoring in base image
  ci-images/Dockerfile.base
Labels: approved, size/XS, lgtm, jira/valid-reference

#6619 MGMT-18456: Revert "MGMT-18127: User name and password in a proxy url should be url encoded"
  pkg/validations/validations.go
  pkg/validations/validations_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#6613 MGMT-18451: Enable debugging assisted-service on kind
  Makefile
  docs/dev/debug.md
  docs/dev/running-test.md
  hack/kind/kind-config.yaml
  tools/deploy_inventory_service.py
Labels: approved, size/L, lgtm, jira/valid-reference

#6622 NO-ISSUE: Konflux migration
  .tekton/assisted-service-saas-hotfix-pull-request.yaml
  .tekton/assisted-service-saas-hotfix-push.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#6621 NO-ISSUE: [master] Bump OCP versions: 4.16
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6623 NO-ISSUE: Deprecated image check migration
  .tekton/assisted-service-saas-hotfix-pull-request.yaml
  .tekton/assisted-service-saas-hotfix-push.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#6262 MGMT-16242: Suggest OCP images based on availability for architecture
  internal/versions/common.go
  internal/versions/common_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6629 NO-ISSUE: Use skipepr to build images as debug image requires nmstate packages
  Makefile
Labels: approved, size/XS, lgtm, jira/valid-reference

#6634 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.12, 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6633 NO-ISSUE: [release-ocm-2.11] Bump OCP versions: 4.16, 4.12, 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6605 AGENT-930: Verify token expiration
  pkg/auth/agent_local_authenticator.go
  pkg/auth/agent_local_authenticator_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6635 NO-ISSUE: [release-ocm-2.9] Bump OCP versions: 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6636 NO-ISSUE: [release-ocm-2.8] Bump OCP versions: 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference
