Repository openshift/assisted-service, pull requests merged in 2024-10, with the labels that each got.

#6848 MGMT-19032: Use old static network flow if OCP version is empty
  pkg/staticnetworkconfig/backward_compatibility.go
Labels: approved, size/S, lgtm, jira/valid-reference

#6847 MGMT-19027: Fix failing kubeapi subsystem test invalid NMstate YAML
  pkg/staticnetworkconfig/generator.go
  subsystem/kubeapi_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6852 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.13, 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6850 NO-ISSUE: fix 'object has been modified' error in kubeapi subsystem
  subsystem/kubeapi_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#6854 NO-ISSUE: [release-ocm-2.8] Bump OCP versions: 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6853 NO-ISSUE: [release-ocm-2.9] Bump OCP versions: 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6851 NO-ISSUE: [release-ocm-2.11] Bump OCP versions: 4.16, 4.13, 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6842 MGMT-18579, MGMT-19018: Add feature flag for minimal OCP version for nmstate service flow
  cmd/main.go
  internal/bminventory/inventory.go
  internal/common/test_configuration.go
  internal/ignition/discovery.go
  internal/ignition/discovery_test.go
  internal/isoeditor/rhcos_test.go
  openshift/template.yaml
  pkg/staticnetworkconfig/backward_compatibility.go
  pkg/staticnetworkconfig/generator.go
  pkg/staticnetworkconfig/generator_test.go
  pkg/staticnetworkconfig/mock_generator.go
  subsystem/infra_env_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6812 MGMT-17230: Use IDMS when possible, take two
  internal/oc/release.go
  internal/oc/release_test.go
Labels: approved, size/XL, lgtm, jira/valid-reference

#6857 MGMT-18938: Update operator bundle channel to ocm-2.13
  Makefile
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/metadata/annotations.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#6843 MGMT-18980: BMH finalizer - remove paused annotation
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6814 MGMT-18996: Set pod security context to ensure group is root.
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#6864 NO-ISSUE: Don't use `subPath` in `pod-persistent-disconnected.yml`
  deploy/podman/pod-persistent-disconnected.yml
Labels: approved, size/XS, lgtm, jira/valid-reference

#6790 ACM-14590: Switch to github.com/docker/distribution/reference to Mitigate CVE-2024-3727
  go.mod
  go.sum
  internal/cluster/validations/validations.go
  internal/common/common.go
  vendor/github.com/containers/image/v5/docker/reference/README.md
  vendor/github.com/containers/image/v5/docker/reference/regexp-additions.go
  vendor/github.com/docker/distribution/LICENSE
  vendor/github.com/docker/distribution/digestset/set.go
  vendor/github.com/docker/distribution/reference/helpers.go
  vendor/github.com/docker/distribution/reference/normalize.go
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/docker/distribution/reference/regexp.go
  vendor/modules.txt
Labels: approved, size/XL, lgtm, jira/valid-reference

#6862 [release-ocm-2.12] MGMT-18936: ClusterServiceVersion for release 2.12 branch references "latest" tag
  Makefile
  OWNERS_ALIASES
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/metadata/annotations.yaml
  deploy/operator/setup_assisted_operator.sh
Labels: approved, size/M, lgtm, jira/valid-reference

#6877 NO-ISSUE: [release-ocm-2.9] Bump OCP versions: 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6875 NO-ISSUE: [release-ocm-2.11] Bump OCP versions: 4.16, 4.14, 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6874 NO-ISSUE: [master] Bump OCP versions: 4.17, 4.14, 4.16, 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6873 NO-ISSUE: [release-ocm-2.12] Bump OCP versions: 4.17, 4.16, 4.14, 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6878 MGMT-19067: fix static network for fulliso old flow
  internal/ignition/discovery.go
  internal/ignition/templates/discovery.ign
Labels: approved, size/S, lgtm, jira/valid-reference

#6879 MGMT-19054: remove LSO as default for CNV on ARM
  internal/operators/cnv/cnv_operator.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#6888 [cloud_hotfix_releases] MGMT-19099: modify default value of MIN_VERSION_FOR_NMSTATE_SERVICE flag to 4.19
  internal/common/test_configuration.go
  internal/ignition/discovery_test.go
  openshift/template.yaml
  pkg/staticnetworkconfig/backward_compatibility.go
  pkg/staticnetworkconfig/generator_test.go
  subsystem/infra_env_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6887 MGMT-19099: Modify default value of MIN_VERSION_FOR_NMSTATE_SERVICE flag to 4.19
  internal/common/test_configuration.go
  internal/ignition/discovery_test.go
  openshift/template.yaml
  pkg/staticnetworkconfig/backward_compatibility.go
  pkg/staticnetworkconfig/generator_test.go
  subsystem/infra_env_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6881 OCPBUGS-32857: Fix of go-jose version from 4.x.x to 2.x.x
  go.mod
  go.sum
  pkg/auth/auth_handler_test_utils.go
  vendor/github.com/go-jose/go-jose/.gitcookies.sh.enc
  vendor/github.com/go-jose/go-jose/.gitignore
  vendor/github.com/go-jose/go-jose/.travis.yml
  vendor/github.com/go-jose/go-jose/CHANGELOG.md
  vendor/github.com/go-jose/go-jose/CONTRIBUTING.md
  vendor/github.com/go-jose/go-jose/LICENSE
  vendor/github.com/go-jose/go-jose/README.md
  vendor/github.com/go-jose/go-jose/asymmetric.go
  vendor/github.com/go-jose/go-jose/crypter.go
  vendor/github.com/go-jose/go-jose/doc.go
  vendor/github.com/go-jose/go-jose/encoding.go
  vendor/github.com/go-jose/go-jose/json/LICENSE
  vendor/github.com/go-jose/go-jose/json/README.md
  vendor/github.com/go-jose/go-jose/json/decode.go
  vendor/github.com/go-jose/go-jose/json/encode.go
  vendor/github.com/go-jose/go-jose/json/indent.go
  vendor/github.com/go-jose/go-jose/json/scanner.go
  vendor/github.com/go-jose/go-jose/json/stream.go
  vendor/github.com/go-jose/go-jose/json/tags.go
  vendor/github.com/go-jose/go-jose/jwe.go
  vendor/github.com/go-jose/go-jose/jwk.go
  vendor/github.com/go-jose/go-jose/jws.go
  vendor/github.com/go-jose/go-jose/opaque.go
  vendor/github.com/go-jose/go-jose/shared.go
  vendor/github.com/go-jose/go-jose/signing.go
  vendor/github.com/go-jose/go-jose/symmetric.go
  vendor/github.com/go-jose/go-jose/v4/.golangci.yml
  vendor/github.com/go-jose/go-jose/v4/.travis.yml
  vendor/github.com/go-jose/go-jose/v4/README.md
  vendor/github.com/go-jose/go-jose/v4/SECURITY.md
  vendor/golang.org/x/crypto/ed25519/ed25519.go
  vendor/gopkg.in/go-jose/go-jose.v2/LICENSE
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/cbc_hmac.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/concat_kdf.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/ecdh_es.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/key_wrap.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/LICENSE
  vendor/gopkg.in/go-jose/go-jose.v2/json/README.md
  vendor/gopkg.in/go-jose/go-jose.v2/json/decode.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/encode.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/indent.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/scanner.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/stream.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/tags.go
  vendor/modules.txt
Labels: approved, size/S, lgtm, jira/valid-bug, jira/valid-reference

#6891 NO-ISSUE: [master] Bump OCP versions: 4.16, 4.15, 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6896 ACM-14807: Update go-jose to v2.6.3 to mitigate CVE-2024-28180
  go.mod
  go.sum
  pkg/auth/auth_handler_test_utils.go
  vendor/github.com/go-jose/go-jose/.gitcookies.sh.enc
  vendor/github.com/go-jose/go-jose/.gitignore
  vendor/github.com/go-jose/go-jose/.travis.yml
  vendor/github.com/go-jose/go-jose/CHANGELOG.md
  vendor/github.com/go-jose/go-jose/CONTRIBUTING.md
  vendor/github.com/go-jose/go-jose/LICENSE
  vendor/github.com/go-jose/go-jose/README.md
  vendor/github.com/go-jose/go-jose/asymmetric.go
  vendor/github.com/go-jose/go-jose/crypter.go
  vendor/github.com/go-jose/go-jose/doc.go
  vendor/github.com/go-jose/go-jose/encoding.go
  vendor/github.com/go-jose/go-jose/json/LICENSE
  vendor/github.com/go-jose/go-jose/json/README.md
  vendor/github.com/go-jose/go-jose/json/decode.go
  vendor/github.com/go-jose/go-jose/json/encode.go
  vendor/github.com/go-jose/go-jose/json/indent.go
  vendor/github.com/go-jose/go-jose/json/scanner.go
  vendor/github.com/go-jose/go-jose/json/stream.go
  vendor/github.com/go-jose/go-jose/json/tags.go
  vendor/github.com/go-jose/go-jose/jwe.go
  vendor/github.com/go-jose/go-jose/jwk.go
  vendor/github.com/go-jose/go-jose/jws.go
  vendor/github.com/go-jose/go-jose/opaque.go
  vendor/github.com/go-jose/go-jose/shared.go
  vendor/github.com/go-jose/go-jose/signing.go
  vendor/github.com/go-jose/go-jose/symmetric.go
  vendor/gopkg.in/go-jose/go-jose.v2/LICENSE
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/cbc_hmac.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/concat_kdf.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/ecdh_es.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/key_wrap.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/LICENSE
  vendor/gopkg.in/go-jose/go-jose.v2/json/README.md
  vendor/gopkg.in/go-jose/go-jose.v2/json/decode.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/encode.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/indent.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/scanner.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/stream.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/tags.go
  vendor/gopkg.in/square/go-jose.v2/BUG-BOUNTY.md
  vendor/gopkg.in/square/go-jose.v2/README.md
  vendor/modules.txt
Labels: approved, size/S, lgtm, jira/valid-reference

#6889 OCPBUGS-42525: Disable pprof for agent-based installer
  cmd/main.go
Labels: approved, size/XS, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#6892 OCPBUGS-43020: Update go-jose to v2.6.3 to mitigate CVE-2024-28180
  go.mod
  go.sum
  pkg/auth/auth_handler_test_utils.go
  vendor/github.com/go-jose/go-jose/.gitcookies.sh.enc
  vendor/github.com/go-jose/go-jose/.gitignore
  vendor/github.com/go-jose/go-jose/.travis.yml
  vendor/github.com/go-jose/go-jose/CHANGELOG.md
  vendor/github.com/go-jose/go-jose/CONTRIBUTING.md
  vendor/github.com/go-jose/go-jose/LICENSE
  vendor/github.com/go-jose/go-jose/README.md
  vendor/github.com/go-jose/go-jose/asymmetric.go
  vendor/github.com/go-jose/go-jose/crypter.go
  vendor/github.com/go-jose/go-jose/doc.go
  vendor/github.com/go-jose/go-jose/encoding.go
  vendor/github.com/go-jose/go-jose/json/LICENSE
  vendor/github.com/go-jose/go-jose/json/README.md
  vendor/github.com/go-jose/go-jose/json/decode.go
  vendor/github.com/go-jose/go-jose/json/encode.go
  vendor/github.com/go-jose/go-jose/json/indent.go
  vendor/github.com/go-jose/go-jose/json/scanner.go
  vendor/github.com/go-jose/go-jose/json/stream.go
  vendor/github.com/go-jose/go-jose/json/tags.go
  vendor/github.com/go-jose/go-jose/jwe.go
  vendor/github.com/go-jose/go-jose/jwk.go
  vendor/github.com/go-jose/go-jose/jws.go
  vendor/github.com/go-jose/go-jose/opaque.go
  vendor/github.com/go-jose/go-jose/shared.go
  vendor/github.com/go-jose/go-jose/signing.go
  vendor/github.com/go-jose/go-jose/symmetric.go
  vendor/gopkg.in/go-jose/go-jose.v2/LICENSE
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/cbc_hmac.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/concat_kdf.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/ecdh_es.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/key_wrap.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/LICENSE
  vendor/gopkg.in/go-jose/go-jose.v2/json/README.md
  vendor/gopkg.in/go-jose/go-jose.v2/json/decode.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/encode.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/indent.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/scanner.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/stream.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/tags.go
  vendor/gopkg.in/square/go-jose.v2/BUG-BOUNTY.md
  vendor/gopkg.in/square/go-jose.v2/README.md
  vendor/modules.txt
Labels: approved, size/S, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#6893 OCPBUGS-43021: Update go-jose to v2.6.3 to mitigate CVE-2024-28180
  go.mod
  go.sum
  pkg/auth/auth_handler_test_utils.go
  vendor/github.com/go-jose/go-jose/.gitcookies.sh.enc
  vendor/github.com/go-jose/go-jose/.gitignore
  vendor/github.com/go-jose/go-jose/.travis.yml
  vendor/github.com/go-jose/go-jose/CHANGELOG.md
  vendor/github.com/go-jose/go-jose/CONTRIBUTING.md
  vendor/github.com/go-jose/go-jose/LICENSE
  vendor/github.com/go-jose/go-jose/README.md
  vendor/github.com/go-jose/go-jose/asymmetric.go
  vendor/github.com/go-jose/go-jose/crypter.go
  vendor/github.com/go-jose/go-jose/doc.go
  vendor/github.com/go-jose/go-jose/encoding.go
  vendor/github.com/go-jose/go-jose/json/LICENSE
  vendor/github.com/go-jose/go-jose/json/README.md
  vendor/github.com/go-jose/go-jose/json/decode.go
  vendor/github.com/go-jose/go-jose/json/encode.go
  vendor/github.com/go-jose/go-jose/json/indent.go
  vendor/github.com/go-jose/go-jose/json/scanner.go
  vendor/github.com/go-jose/go-jose/json/stream.go
  vendor/github.com/go-jose/go-jose/json/tags.go
  vendor/github.com/go-jose/go-jose/jwe.go
  vendor/github.com/go-jose/go-jose/jwk.go
  vendor/github.com/go-jose/go-jose/jws.go
  vendor/github.com/go-jose/go-jose/opaque.go
  vendor/github.com/go-jose/go-jose/shared.go
  vendor/github.com/go-jose/go-jose/signing.go
  vendor/github.com/go-jose/go-jose/symmetric.go
  vendor/gopkg.in/go-jose/go-jose.v2/LICENSE
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/cbc_hmac.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/concat_kdf.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/ecdh_es.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/key_wrap.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/LICENSE
  vendor/gopkg.in/go-jose/go-jose.v2/json/README.md
  vendor/gopkg.in/go-jose/go-jose.v2/json/decode.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/encode.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/indent.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/scanner.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/stream.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/tags.go
  vendor/gopkg.in/square/go-jose.v2/BUG-BOUNTY.md
  vendor/gopkg.in/square/go-jose.v2/README.md
  vendor/modules.txt
Labels: approved, size/S, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#6894 OCPBUGS-43022: Update go-jose to v2.6.3 to mitigate CVE-2024-28180
  go.mod
  go.sum
  pkg/auth/auth_handler_test_utils.go
  vendor/github.com/go-jose/go-jose/.gitcookies.sh.enc
  vendor/github.com/go-jose/go-jose/.gitignore
  vendor/github.com/go-jose/go-jose/.travis.yml
  vendor/github.com/go-jose/go-jose/CHANGELOG.md
  vendor/github.com/go-jose/go-jose/CONTRIBUTING.md
  vendor/github.com/go-jose/go-jose/LICENSE
  vendor/github.com/go-jose/go-jose/README.md
  vendor/github.com/go-jose/go-jose/asymmetric.go
  vendor/github.com/go-jose/go-jose/crypter.go
  vendor/github.com/go-jose/go-jose/doc.go
  vendor/github.com/go-jose/go-jose/encoding.go
  vendor/github.com/go-jose/go-jose/json/LICENSE
  vendor/github.com/go-jose/go-jose/json/README.md
  vendor/github.com/go-jose/go-jose/json/decode.go
  vendor/github.com/go-jose/go-jose/json/encode.go
  vendor/github.com/go-jose/go-jose/json/indent.go
  vendor/github.com/go-jose/go-jose/json/scanner.go
  vendor/github.com/go-jose/go-jose/json/stream.go
  vendor/github.com/go-jose/go-jose/json/tags.go
  vendor/github.com/go-jose/go-jose/jwe.go
  vendor/github.com/go-jose/go-jose/jwk.go
  vendor/github.com/go-jose/go-jose/jws.go
  vendor/github.com/go-jose/go-jose/opaque.go
  vendor/github.com/go-jose/go-jose/shared.go
  vendor/github.com/go-jose/go-jose/signing.go
  vendor/github.com/go-jose/go-jose/symmetric.go
  vendor/gopkg.in/go-jose/go-jose.v2/LICENSE
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/cbc_hmac.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/concat_kdf.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/ecdh_es.go
  vendor/gopkg.in/go-jose/go-jose.v2/cipher/key_wrap.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/LICENSE
  vendor/gopkg.in/go-jose/go-jose.v2/json/README.md
  vendor/gopkg.in/go-jose/go-jose.v2/json/decode.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/encode.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/indent.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/scanner.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/stream.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/tags.go
  vendor/gopkg.in/square/go-jose.v2/BUG-BOUNTY.md
  vendor/gopkg.in/square/go-jose.v2/README.md
  vendor/modules.txt
Labels: approved, size/S, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#6902 NO-ISSUE: Pin gocov version
  hack/setup_env.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#6880 MGMT-19085: fix 'object has been modified' error in kubeapi subsystem
  subsystem/kubeapi_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#6911 MGMT-19129: Migrate assisted-service to Konflux
  build_deploy.sh
  build_images.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#6910 NO-ISSUE: [master] Bump OCP versions: 4.18
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6913 NO-ISSUE: [release-ocm-2.12] Bump OCP versions: 4.12, 4.18, 4.16, 4.15
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#6915 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.12, 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6916 NO-ISSUE: [release-ocm-2.9] Bump OCP versions: 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#6914 NO-ISSUE: [release-ocm-2.11] Bump OCP versions: 4.12, 4.16, 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6920 MGMT-19141: Ensure no finalizer is set for BMHs without the infraenv label
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6925 NO-ISSUE: add carbonin to the owner list
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#6924 NO-ISSUE: add carbonin to the owner list
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#6926 NO-ISSUE: add carbonin to the owner list
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#6927 NO-ISSUE: add carbonin to the owner list
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#6933 MGMT-19148: Add OLM operator setup jobs finalizing stage
  api/vendor/github.com/openshift/assisted-service/models/finalizing_stage.go
  client/vendor/github.com/openshift/assisted-service/models/finalizing_stage.go
  internal/cluster/finalizing_stages.go
  internal/cluster/finalizing_stages_test.go
  models/finalizing_stage.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/finalizing_stage.go
Labels: approved, size/S, api-review, lgtm, jira/valid-reference

#6934 NO-ISSUE: Update CI gather script and fix failing to scale nodepool
  deploy/operator/capi/deploy_capi_cluster.sh
  deploy/operator/gather.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#6930 NO-ISSUE: add carbonin to the owner list
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#6937 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6935 NO-ISSUE: [release-ocm-2.12] Bump OCP versions: 4.16, 4.13, 4.17
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6936 NO-ISSUE: [release-ocm-2.11] Bump OCP versions: 4.16, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6954 NO-ISSUE: [release-ocm-2.9] Bump OCP versions: 4.14, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6951 NO-ISSUE: [release-ocm-2.12] Bump OCP versions: 4.14, 4.17, 4.16
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6955 MGMT-19190: Bump LSO version override to 4.18
  deploy/operator/setup_lso.sh
Labels: approved, size/S, lgtm, jira/valid-reference

#6952 NO-ISSUE: [release-ocm-2.11] Bump OCP versions: 4.14, 4.16
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6956 MGMT-19176: Reduce the version of operator-sdk binary
  ci-images/Dockerfile.code-generation
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  deploy/olm-catalog/metadata/annotations.yaml
  hack/setup_env.sh
Labels: approved, size/M, lgtm, jira/valid-reference

#6711 ECOPROJECT-2080: Add MTV operator as an option to cluster post installation
  api/vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  api/vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  client/vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  client/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  client/vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  internal/cluster/cluster_test.go
  internal/cluster/statemachine.go
  internal/cluster/validation_id.go
  internal/featuresupport/feature_support_level.go
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features_olm_operators.go
  internal/featuresupport/features_olm_operators_test.go
  internal/featuresupport/features_platforms.go
  internal/host/host_test.go
  internal/host/monitor_test.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/operators/builder.go
  internal/operators/manager_test.go
  internal/operators/mtv/config.go
  internal/operators/mtv/manifest.go
  internal/operators/mtv/manifest_test.go
  internal/operators/mtv/mtv_suite_test.go
  internal/operators/mtv/operator.go
  internal/operators/mtv/operator_test.go
  models/cluster_validation_id.go
  models/feature_support_level_id.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  subsystem/operators_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  vendor/github.com/openshift/assisted-service/models/host_validation_id.go
Labels: approved, size/XL, api-review, lgtm, ok-to-test, jira/valid-reference

#6947 MGMT-19174: Add rpms-signature-scan task to tekton pipelines
  .tekton/assisted-service-saas-main-pull-request.yaml
  .tekton/assisted-service-saas-main-push.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6948 MGMT-19171: Fix nmpolicy injection into nmstate YAML
  pkg/staticnetworkconfig/generator.go
  pkg/staticnetworkconfig/generator_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6943 OCPBUGS-43513: allow configuring cluster UserManagedNetworking field when importing a cluster
  cmd/agentbasedinstaller/agentbasedinstaller_suite_test.go
  cmd/agentbasedinstaller/client/main.go
  cmd/agentbasedinstaller/import.go
Labels: approved, size/L, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference
