Repository openshift/assisted-service, pull requests merged in 2024-12, with the labels that each got.

#7046 MGMT-19390: Update mce's tekton pipelines to be multi-arch
  .tekton/assisted-service-rhel8-mce-downstream-main-pull-request.yaml
  .tekton/assisted-service-rhel8-mce-downstream-main-push.yaml
  .tekton/assisted-service-rhel9-mce-downstream-main-pull-request.yaml
  .tekton/assisted-service-rhel9-mce-downstream-main-push.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7042 MGMT-19348: Mark cluster-create-param high_availability_mode as deprecated
  api/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  client/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  models/cluster_create_params.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
Labels: approved, size/XS, api-review, lgtm, jira/valid-reference

#7040 [cloud_hotfix_releases] MGMT-19360: do not monitor hosts with status installed (#7030)
  internal/host/monitor.go
  internal/host/monitor_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6991 MGMT-18628: fix better waiting for deployment
  deploy/operator/capi/deploy_capi_cluster.sh
  deploy/operator/hypershift/deploy_hypershift_cluster.sh
  deploy/operator/setup_assisted_operator.sh
  deploy/operator/setup_hive.sh
  deploy/operator/utils.sh
  deploy/operator/ztp/deploy_spoke_cluster.sh
Labels: approved, size/L, lgtm, jira/valid-reference

#7050 [cloud_hotfix_releases] NO-ISSUE: Update konflux pipeline ref
  .tekton/assisted-service-saas-hotfix-pull-request.yaml
  .tekton/assisted-service-saas-hotfix-push.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7019 MGMT-19331: Secure boot must be disabled for NVIDIA GPUs
  internal/operators/nvidiagpu/nvidia_gpu_operator.go
  internal/operators/nvidiagpu/nvidia_gpu_operator_test.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#7058 [cloud_hotfix_releases] MGMT-19360: Improve monitor host query performance
  internal/host/monitor.go
Labels: approved, size/S, lgtm, jira/valid-reference

#7054 MGMT-19408: Create tekton pipelines for acm 2.13
  .tekton/assisted-service-rhel8-mce-downstream-2-13-pull-request.yaml
  .tekton/assisted-service-rhel8-mce-downstream-2-13-push.yaml
  .tekton/assisted-service-rhel9-mce-downstream-2-13-pull-request.yaml
  .tekton/assisted-service-rhel9-mce-downstream-2-13-push.yaml
Labels: approved, lgtm, size/XXL, jira/valid-reference

#6744 MGMT-18227: Add quickstart document for new developers
  docs/dev/README.md
Labels: approved, size/L, lgtm, jira/valid-reference

#7029 OCPBUGS-44849: Provide fallback Xattr method where not supported in kernel.
  cmd/main.go
  pkg/s3wrapper/composite_xattr_client.go
  pkg/s3wrapper/composite_xattr_client_test.go
  pkg/s3wrapper/filesystem.go
  pkg/s3wrapper/filesystem_test.go
  pkg/s3wrapper/filesystem_xattr_client.go
  pkg/s3wrapper/mock_xattr_client.go
  pkg/s3wrapper/os_xattr_client.go
  pkg/s3wrapper/os_xattr_client_test.go
  pkg/s3wrapper/xattr_client.go
Labels: approved, lgtm, size/XXL, jira/valid-bug, jira/valid-reference

#7051 NO-ISSUE: renovate to add labels for auto-merge
  renovate.json
Labels: approved, size/XS, lgtm, jira/valid-reference

#7057 MGMT-19360: Improve monitor host query performance
  internal/host/monitor.go
Labels: approved, size/S, lgtm, jira/valid-reference

#6998 MGMT-18986: Allow ISO type configuration from kube API
  api/v1beta1/infraenv_types.go
  config/crd/bases/agent-install.openshift.io_infraenvs.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
  internal/bminventory/inventory.go
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  internal/infraenv/iso_image_type.go
  subsystem/kubeapi_test.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/infraenv_types.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#7059 MGMT-19370: Enable none platfrom with non-standard HA control plane
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features_misc.go
  internal/featuresupport/features_platforms.go
Labels: approved, size/S, lgtm, jira/valid-reference

#7065 NO-ISSUE: [master] Bump OCP versions: 4.16, 4.18, 4.17, 4.15, 4.12, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7060 MGMT-19410: Export control_plane_count cluster property
  api/vendor/github.com/openshift/assisted-service/models/cluster.go
  api/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  api/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
  client/vendor/github.com/openshift/assisted-service/models/cluster.go
  client/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  client/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster_test.go
  internal/cluster/transition_test.go
  internal/cluster/validator_test.go
  internal/common/db.go
  internal/migrations/20241122160000_update_new_column_control_plane_count_value_for_existing_cluster_records_test.go
  internal/operators/odf/validation_test.go
  models/cluster.go
  models/cluster_create_params.go
  models/v2_cluster_update_params.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster.go
  vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#7064 MGMT-19413: Add validations info to the Agents annotations
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7069 MGMT-19051: Add documentation for the new non-standard highly available control plane configurations for day1
  docs/user-guide/configuring_the_number_of_nodes_for_highly_available_control_planes.md
  docs/user-guide/img/control_plane_count_dropdown.png
Labels: approved, size/S, lgtm, jira/valid-reference

#7061 NO-ISSUE: Enable static network using the nmstate flow across all architectures
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/ignition/discovery.go
  internal/ignition/discovery_test.go
  pkg/staticnetworkconfig/backward_compatibility.go
  pkg/staticnetworkconfig/generator.go
  pkg/staticnetworkconfig/generator_test.go
  pkg/staticnetworkconfig/mock_generator.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7062 ACM-6053: Add NTP to machineconfig even if no sync
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7015 MGMT-19299: Add _Authorino_ operator
  api/vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  api/vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  client/vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  client/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  client/vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  internal/cluster/cluster_test.go
  internal/cluster/statemachine.go
  internal/cluster/validation_id.go
  internal/featuresupport/feature_support_level.go
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features_olm_operators.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/operators/authorino/authorino_manifests.go
  internal/operators/authorino/authorino_manifests_test.go
  internal/operators/authorino/authorino_operator.go
  internal/operators/authorino/authorino_suite_test.go
  internal/operators/authorino/authorino_templates.go
  internal/operators/authorino/templates/openshift/50_authorino_subscription.yaml
  internal/operators/authorino/test_utils.go
  internal/operators/builder.go
  internal/operators/manager_test.go
  internal/operators/openshiftai/openshift_ai_operator.go
  models/cluster_validation_id.go
  models/feature_support_level_id.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  subsystem/operators_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  vendor/github.com/openshift/assisted-service/models/host_validation_id.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#7070 NO-ISSUE: fixing late binding
  deploy/operator/setup_assisted_operator.sh
Labels: approved, size/S, lgtm, ok-to-test, jira/valid-reference

#7052 MGMT-19362: Explicitly add OpenShift AI incompatibilities
  internal/featuresupport/features_misc.go
  internal/featuresupport/features_olm_operators.go
  internal/featuresupport/features_olm_operators_test.go
Labels: approved, size/S, lgtm, ok-to-test, jira/valid-reference

#7080 MGMT-19507: Stop using multi-arch builds in konflux
  .tekton/assisted-service-rhel8-mce-downstream-2-13-pull-request.yaml
  .tekton/assisted-service-rhel8-mce-downstream-2-13-push.yaml
  .tekton/assisted-service-rhel8-mce-downstream-main-pull-request.yaml
  .tekton/assisted-service-rhel8-mce-downstream-main-push.yaml
  .tekton/assisted-service-rhel9-mce-downstream-2-13-pull-request.yaml
  .tekton/assisted-service-rhel9-mce-downstream-2-13-push.yaml
  .tekton/assisted-service-rhel9-mce-downstream-main-pull-request.yaml
  .tekton/assisted-service-rhel9-mce-downstream-main-push.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7078 NO-ISSUE: Remove unused method from spoke client factory
  internal/spoke_k8s_client/factory.go
  internal/spoke_k8s_client/mock_spoke_k8s_client_factory.go
Labels: approved, size/S, lgtm, jira/valid-reference

#7063 MGMT-19414: Add default requeue time when Hosts are created from Agents
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#7012 MGMT-19166: Implement MTU validations for CMN and UMN
  api/vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  client/vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  internal/host/refresh_status_preprocessor.go
  internal/host/validation_id.go
  internal/host/validations_test.go
  internal/host/validator.go
  internal/network/utils.go
  internal/network/utils_test.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/host_validation_id.go
Labels: approved, size/L, api-review, lgtm, ok-to-test, jira/valid-reference

#7067 ACM-16164: Add NTP to machineconfig even if no sync - ACM 2.11
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7068 ACM-16166: Add NTP to machineconfig even if no sync - ACM 1.10
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7095 NO-ISSUE: [master] Bump OCP versions: 4.17, 4.16, 4.18, 4.15, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7092 [release-ocm-2.11] MGMT-19158: Always try to cache the ClusterImageSet (#6962)
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7091 [release-ocm-2.12] MGMT-19158: Always try to cache the ClusterImageSet
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7103 NO-ISSUE: Remove unused Konflux references
  .tekton/assisted-service-q2vh-pull-request.yaml
  .tekton/assisted-service-q2vh-push.yaml
Labels: approved, size/XL, lgtm, jira/valid-reference

#6990 MGMT-19239: Add an option to install OSC operator
  api/vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  api/vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  client/vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  client/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  client/vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  internal/cluster/cluster_test.go
  internal/cluster/statemachine.go
  internal/cluster/validation_id.go
  internal/featuresupport/feature_support_level.go
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features_olm_operators.go
  internal/featuresupport/features_olm_operators_test.go
  internal/featuresupport/features_platforms.go
  internal/host/host_test.go
  internal/host/monitor_test.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/operators/builder.go
  internal/operators/manager_test.go
  internal/operators/osc/config.go
  internal/operators/osc/manifest.go
  internal/operators/osc/manifest_test.go
  internal/operators/osc/operator.go
  internal/operators/osc/operator_test.go
  internal/operators/osc/osc_suite_test.go
  models/cluster_validation_id.go
  models/feature_support_level_id.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  subsystem/operators_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  vendor/github.com/openshift/assisted-service/models/host_validation_id.go
Labels: approved, size/XL, api-review, lgtm, jira/valid-reference

#7081 NO-ISSUE: Simplify spoke client factory
  internal/controller/controllers/spoke_client_cache.go
  internal/controller/controllers/spoke_client_cache_test.go
  internal/spoke_k8s_client/factory.go
  internal/spoke_k8s_client/factory_test.go
  internal/spoke_k8s_client/mock_spoke_k8s_client_factory.go
  internal/spoke_k8s_client/suite_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7113 NO-ISSUE: [master] Bump OCP versions: 4.18
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7076 MGMT-18288: Approve CSRs for agents with baremetal platform without MAPI
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/common.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7100 NO-ISSUE: Allow use of 'envtest'
  go.sum
  hack/setup_env.sh
  internal/testing/envtest.go
  internal/testing/envtest_test.go
  internal/testing/suite_test.go
  vendor/modules.txt
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/crd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/helper.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/server.go
  vendor/sigs.k8s.io/controller-runtime/pkg/envtest/webhook.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/flock/doc.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/flock/errors.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/flock/flock_other.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/flock/flock_unix.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/addr/manager.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/certs/tinyca.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/apiserver.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/auth.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/etcd.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/kubectl.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/controlplane/plane.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/process/arguments.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/process/bin_path_finder.go
  vendor/sigs.k8s.io/controller-runtime/pkg/internal/testing/process/process.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7115 NO-ISSUE: [master] Bump OCP versions: 4.16, 4.17, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7116 MGMT-19537: Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http/httpguts/httplex.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/net/websocket/hybi.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/modules.txt
Labels: approved, size/S, lgtm, jira/valid-reference

#7121 MGMT-19537: Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, size/M, lgtm, jira/valid-reference

#7122 [release-ocm-2.9] MGMT-19537: Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http/httpguts/httplex.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/net/websocket/hybi.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/modules.txt
Labels: approved, size/M, lgtm, jira/valid-reference

#7124 [release-ocm-2.11] MGMT-19537: Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http/httpguts/httplex.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/net/websocket/hybi.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/modules.txt
Labels: approved, size/M, lgtm, jira/valid-reference

#7123 [release-ocm-2.10] MGMT-19537: Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http/httpguts/httplex.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/net/websocket/hybi.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/modules.txt
Labels: approved, size/M, lgtm, jira/valid-reference

#7125 [release-ocm-2.12] MGMT-19537: Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http/httpguts/httplex.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/net/websocket/hybi.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/modules.txt
Labels: approved, size/M, lgtm, jira/valid-reference

#7131 NO-ISSUE: Add 4.19 release and os images
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  data/default_release_sources.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#7114 [release-ocm-2.12] NO-ISSUE: Bump controller-gen version
  api/common/zz_generated.deepcopy.go
  api/hiveextension/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.deepcopy.go
  ci-images/Dockerfile.code-generation
  config/crd/bases/agent-install.openshift.io_agentclassifications.yaml
  config/crd/bases/agent-install.openshift.io_agents.yaml
  config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
  config/crd/bases/agent-install.openshift.io_hypershiftagentserviceconfigs.yaml
  config/crd/bases/agent-install.openshift.io_infraenvs.yaml
  config/crd/bases/agent-install.openshift.io_nmstateconfigs.yaml
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  config/rbac/role.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agentclassifications.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agentserviceconfigs.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_hypershiftagentserviceconfigs.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_nmstateconfigs.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  hack/generate.sh
  hack/setup_env.sh
Labels: approved, api-review, lgtm, size/XXL, jira/valid-reference

#7105 MGMT-18501: Configure sast-snyk-check in konflux pipelines
  .tekton/assisted-service-rhel8-mce-downstream-2-13-pull-request.yaml
  .tekton/assisted-service-rhel8-mce-downstream-2-13-push.yaml
  .tekton/assisted-service-rhel8-mce-downstream-main-pull-request.yaml
  .tekton/assisted-service-rhel8-mce-downstream-main-push.yaml
  .tekton/assisted-service-rhel9-mce-downstream-2-13-pull-request.yaml
  .tekton/assisted-service-rhel9-mce-downstream-2-13-push.yaml
  .tekton/assisted-service-rhel9-mce-downstream-main-pull-request.yaml
  .tekton/assisted-service-rhel9-mce-downstream-main-push.yaml
  .tekton/assisted-service-saas-main-pull-request.yaml
  .tekton/assisted-service-saas-main-push.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7135 [release-ocm-2.11] NO-ISSUE: Bump controller-gen
  api/common/zz_generated.deepcopy.go
  api/hiveextension/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.deepcopy.go
  ci-images/Dockerfile.code-generation
  config/crd/bases/agent-install.openshift.io_agentclassifications.yaml
  config/crd/bases/agent-install.openshift.io_agents.yaml
  config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
  config/crd/bases/agent-install.openshift.io_hypershiftagentserviceconfigs.yaml
  config/crd/bases/agent-install.openshift.io_infraenvs.yaml
  config/crd/bases/agent-install.openshift.io_nmstateconfigs.yaml
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  config/rbac/role.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agentclassifications.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agentserviceconfigs.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_hypershiftagentserviceconfigs.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_nmstateconfigs.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  hack/generate.sh
  hack/setup_env.sh
  vendor/github.com/openshift/assisted-service/api/common/zz_generated.deepcopy.go
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/zz_generated.deepcopy.go
Labels: approved, api-review, lgtm, size/XXL, jira/valid-reference

#7136 [release-ocm-2.10] NO-ISSUE: Bump controller-gen
  api/common/zz_generated.deepcopy.go
  api/hiveextension/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.deepcopy.go
  ci-images/Dockerfile.code-generation
  config/crd/bases/agent-install.openshift.io_agentclassifications.yaml
  config/crd/bases/agent-install.openshift.io_agents.yaml
  config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
  config/crd/bases/agent-install.openshift.io_hypershiftagentserviceconfigs.yaml
  config/crd/bases/agent-install.openshift.io_infraenvs.yaml
  config/crd/bases/agent-install.openshift.io_nmstateconfigs.yaml
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  config/rbac/role.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agentclassifications.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agentserviceconfigs.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_hypershiftagentserviceconfigs.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_nmstateconfigs.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  hack/generate.sh
  hack/setup_env.sh
Labels: approved, api-review, lgtm, size/XXL, jira/valid-reference

#7137 [release-ocm-2.9] NO-ISSUE: Bump controller-gen
  api/common/zz_generated.deepcopy.go
  api/hiveextension/v1beta1/zz_generated.deepcopy.go
  api/v1beta1/zz_generated.deepcopy.go
  ci-images/Dockerfile.code-generation
  config/crd/bases/agent-install.openshift.io_agentclassifications.yaml
  config/crd/bases/agent-install.openshift.io_agents.yaml
  config/crd/bases/agent-install.openshift.io_agentserviceconfigs.yaml
  config/crd/bases/agent-install.openshift.io_hypershiftagentserviceconfigs.yaml
  config/crd/bases/agent-install.openshift.io_infraenvs.yaml
  config/crd/bases/agent-install.openshift.io_nmstateconfigs.yaml
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  config/rbac/role.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agentclassifications.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agentserviceconfigs.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_hypershiftagentserviceconfigs.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_nmstateconfigs.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  hack/generate.sh
  hack/setup_env.sh
Labels: approved, api-review, lgtm, size/XXL, jira/valid-reference

#7139 NO-ISSUE: [release-ocm-2.12] Bump OCP versions: 4.16, 4.12, 4.14, 4.17, 4.15, 4.13, 4.18
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#7140 NO-ISSUE: [release-ocm-2.11] Bump OCP versions: 4.16, 4.12, 4.14, 4.15, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7145 [release-ocm-2.10] NO-ISSUE: Remove default release images testing for OCM branches
  internal/versions/api_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7146 [release-ocm-2.9] NO-ISSUE: Remove default release images testing for OCM branches
  internal/versions/api_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7143 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.14, 4.13, 4.15, 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7144 NO-ISSUE: [release-ocm-2.9] Bump OCP versions: 4.14, 4.13, 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7148 MGMT-18891: Use old static network flow when MAC identifier exists
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/ignition/discovery.go
  internal/ignition/discovery_test.go
  pkg/staticnetworkconfig/backward_compatibility.go
  pkg/staticnetworkconfig/backward_compatibility_test.go
  pkg/staticnetworkconfig/generator.go
  pkg/staticnetworkconfig/generator_test.go
  pkg/staticnetworkconfig/mock_generator.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7151 MGMT-19523: Fix validation looping in ODF
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostrole_test.go
  internal/host/hostutil/test_utils.go
  internal/host/mock_host_api.go
  internal/host/monitor.go
  internal/host/validations_test.go
  internal/operators/manager_test.go
  internal/operators/odf/common.go
  internal/operators/odf/odf_operator.go
  internal/operators/odf/odf_operator_test.go
  internal/operators/odf/validation_test.go
  internal/operators/odf/validations.go
Labels: approved, size/L, lgtm, jira/valid-reference
