Repository openshift/assisted-service, pull requests merged in 2024-05, with the labels that each got.

#5792 CORS-2750: Move to rhel9, decouple from cli image
  .ci-operator.yaml
  Dockerfile.assisted-service.ocp
Labels: approved, kind/dependency-change, size/S, lgtm, jira/valid-reference

#6246 NO-ISSUE: Fix hypershift destroy in CI test script
  deploy/operator/capi/deploy_capi_cluster.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#6250 NO-ISSUE: Bump OCP versions: 4.13, 4.12, 4.14, 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6252 MGMT-17697: Change L3 connectivity to use connected addresses instead of majority groups
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/host/transition_test.go
  internal/host/validator.go
  internal/network/connectivity_groups.go
  internal/network/connectivity_groups_test.go
Labels: approved, size/XL, lgtm, jira/valid-reference

#6239 OCPBUGS-31733: Remove CPMS manifest for vSphere platform
  internal/provider/vsphere/ignition.go
Labels: approved, size/XS, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#6256 MGMT-17523: Fail when OS images CPU architecture is missing instead of giving it default value
  internal/versions/osimages.go
  internal/versions/osimages_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6260 MGMT-17194: Ensure releaseImage is not tag based when mirror registry enabled.
  cmd/main.go
  go.mod
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  vendor/github.com/openshift/library-go/pkg/image/internal/digest/digest.go
  vendor/github.com/openshift/library-go/pkg/image/internal/digest/digester.go
  vendor/github.com/openshift/library-go/pkg/image/internal/digest/doc.go
  vendor/github.com/openshift/library-go/pkg/image/internal/reference/doc.go
  vendor/github.com/openshift/library-go/pkg/image/internal/reference/reference.go
  vendor/github.com/openshift/library-go/pkg/image/internal/reference/regexp.go
  vendor/github.com/openshift/library-go/pkg/image/reference/reference.go
  vendor/modules.txt
Labels: approved, size/L, lgtm, jira/valid-reference

#6267 [release-ocm-2.8] MGMT-17544: Prioritize finding release image with exact CPU architecture
  internal/versions/versions.go
  internal/versions/versions_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6268 Revert "MGMT-17194: Ensure releaseImage is not tag based when mirror registry enabled. (#6260)
  cmd/main.go
  go.mod
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  vendor/github.com/openshift/library-go/pkg/image/internal/digest/digest.go
  vendor/github.com/openshift/library-go/pkg/image/internal/digest/digester.go
  vendor/github.com/openshift/library-go/pkg/image/internal/digest/doc.go
  vendor/github.com/openshift/library-go/pkg/image/internal/reference/doc.go
  vendor/github.com/openshift/library-go/pkg/image/internal/reference/reference.go
  vendor/github.com/openshift/library-go/pkg/image/internal/reference/regexp.go
  vendor/github.com/openshift/library-go/pkg/image/reference/reference.go
  vendor/modules.txt
Labels: approved, size/L, lgtm, jira/valid-reference

#6255 NO-ISSUE: Add openshift-edge-bot as an OWNER
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#6276 MGMT-17764: Update the latest image search functionality in the RestAPI flow to correctly compare pre-release versions
  internal/versions/rest_api_versions.go
  internal/versions/rest_api_versions_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6266 MGMT-17194: Ensure that we improve error messages for mirror registry tagged images
  cmd/main.go
  go.mod
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  vendor/github.com/openshift/library-go/pkg/image/internal/digest/digest.go
  vendor/github.com/openshift/library-go/pkg/image/internal/digest/digester.go
  vendor/github.com/openshift/library-go/pkg/image/internal/digest/doc.go
  vendor/github.com/openshift/library-go/pkg/image/internal/reference/doc.go
  vendor/github.com/openshift/library-go/pkg/image/internal/reference/reference.go
  vendor/github.com/openshift/library-go/pkg/image/internal/reference/regexp.go
  vendor/github.com/openshift/library-go/pkg/image/reference/reference.go
  vendor/modules.txt
Labels: approved, size/L, lgtm, jira/valid-reference

#6289 MGMT-17775: Ensure that patch manifest filenames are consistent and correct.
  api/vendor/github.com/openshift/assisted-service/models/create_manifest_params.go
  api/vendor/github.com/openshift/assisted-service/models/update_manifest_params.go
  client/vendor/github.com/openshift/assisted-service/models/create_manifest_params.go
  client/vendor/github.com/openshift/assisted-service/models/update_manifest_params.go
  docs/user-guide/install-customization.md
  internal/manifests/manifests.go
  internal/manifests/manifests_test.go
  models/create_manifest_params.go
  models/update_manifest_params.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/create_manifest_params.go
  vendor/github.com/openshift/assisted-service/models/update_manifest_params.go
Labels: approved, size/M, api-review, lgtm, jira/valid-reference

#6288 NO-ISSUE: [release-ocm-2.8] Add 4.14 RHCOS images
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6301 NO-ISSUE: [release-ocm-2.9] Bump OCP versions: 4.11, 4.13, 4.12, 4.14
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#6300 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.13, 4.15, 4.12, 4.14, 4.11
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#6311 NO-ISSUE: [release-ocm-2.8] Bump OCP versions: 4.11, 4.13, 4.12, 4.10
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  internal/controller/controllers/common.go
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#6309 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.15, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6310 NO-ISSUE: [release-ocm-2.9] Bump OCP versions: 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6341 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.12, 4.14, 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6342 NO-ISSUE: [release-ocm-2.9] Bump OCP versions: 4.12, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6343 NO-ISSUE: [release-ocm-2.8] Bump OCP versions: 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6352 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6339 MGMT-17866: Assisted service change for F5 DNS load balancer
  api/vendor/github.com/openshift/assisted-service/models/domain_resolution_response.go
  client/vendor/github.com/openshift/assisted-service/models/domain_resolution_response.go
  internal/common/test_configuration.go
  internal/host/validations_test.go
  internal/host/validator.go
  models/domain_resolution_response.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/domain_resolution_response.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#6355 OCPBUGS-34181: Don't use the statically linked installer if FIPS is enabled
  cmd/agentbasedinstaller/register.go
  cmd/main.go
  internal/ignition/ignition.go
  internal/oc/release.go
  internal/oc/release_test.go
  internal/system/mock_system.go
  internal/system/system.go
  internal/system/system_test.go
Labels: approved, size/L, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#6314 MGMT-17811: Do not create local cluster namespace
  internal/controller/controllers/local_cluster_import_controller.go
  internal/controller/controllers/local_cluster_import_controller_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6358 NO-ISSUE: [master] Bump OCP versions: 4.16, 4.14, 4.12, 4.15
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6283 MGMT-17770: Split ignition handling file
  cmd/main.go
  internal/ignition/discovery.go
  internal/ignition/discovery_test.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/ignition/installmanifests.go
  internal/ignition/installmanifests_test.go
  internal/ignition/mock_ignition_builder.go
  pkg/generator/generator.go
Labels: approved, lgtm, size/XXL, jira/valid-reference

#6305 MGMT-17618: NMStateConfig interfaces presence should be validated
  pkg/staticnetworkconfig/generator.go
  pkg/staticnetworkconfig/generator_test.go
  subsystem/image_test.go
  subsystem/infra_env_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6348 NO-ISSUE: [Snyk] Security upgrade requests from 2.31.0 to 2.32.0
  dev-requirements.txt
Labels: approved, size/XS, lgtm, jira/valid-reference

#6258 OCPBUGS-31727: Invalid Pull-Secret when using password which contains a colon character
  internal/cluster/validations/pull_secret_validation.go
  internal/cluster/validations/validation_test.go
Labels: approved, size/S, lgtm, jira/valid-bug, jira/valid-reference

#6346 NO-ISSUE: [Snyk] Security upgrade requests from 2.31.0 to 2.32.0
  deploy/olm-catalog/requirements.txt
Labels: approved, size/XS, lgtm, jira/valid-reference

#6347 MGMT-17896: Add separate Dockerfile for assisted-service with an el8 base
  Dockerfile.assisted-service
  hack/container_build_scripts/install_build_deps.sh
Labels: approved, kind/dependency-change, size/S, lgtm, jira/valid-reference

#6361 MGMT-17823: Cleanup the install manifest generator
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/instruction_manager.go
  internal/ignition/discovery.go
  internal/ignition/dummy.go
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/ignition/installmanifests.go
  internal/ignition/installmanifests_test.go
  internal/ignition/templates/discovery.ign
  pkg/generator/generator.go
  pkg/generator/mock_install_config.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6368 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.14, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6369 NO-ISSUE: [release-ocm-2.9] Bump OCP versions: 4.14, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6257 MGMT-17700: Assign none platform node-ips based on connected addresses and etcd restrictions
  internal/common/common.go
  internal/ignition/installmanifests.go
  internal/ignition/installmanifests_test.go
  internal/network/none_platform_node_ips_allocation.go
  internal/network/none_platform_node_ips_allocation_test.go
  internal/provider/none/installConfig.go
Labels: approved, size/XL, lgtm, jira/valid-reference

#6356 MGMT-17849: escape '%' in agent.service proxy urls
  internal/ignition/discovery.go
  internal/ignition/discovery_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6374 NO-ISSUE: wait for LSO to be installed
  deploy/operator/setup_lso.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#6307 NO-ISSUE: Deprecate and disable support for OCM offline token
  pkg/ocm/client.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6360 MGMT-17848: Assisted service should not format multipath devices
  internal/common/disk_formatting.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6371 MGMT-17901: Ignore mirror registries during pull secret validation
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  pkg/mirrorregistries/generator.go
  pkg/mirrorregistries/generator_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6359 MGMT-17763: Setting Machine network CIDR is forbidden" error is only present on cluster updates
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#6349 MGMT-17898: Use the EL8 assisted-service image when requested by annotation
  config/manager/manager.yaml
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  docs/operator.md
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/images.go
Labels: approved, size/M, lgtm, jira/valid-reference

#6378 NO-ISSUE: [master] Bump OCP versions: 4.14, 4.15, 4.13, 4.16
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#6379 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#6332 MGMT-17353: Debug pod left in ImagePullBackOff after install in disconnected environment
  api/vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
  client/vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/instruction_manager.go
  models/install_cmd_request.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
Labels: approved, size/M, api-review, lgtm, jira/valid-reference

#6377 MGMT-17901: Add the external registry to the list of ignored registries for pull secret validation instead of the mirror one
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#6333 MGMT-17353: Debug pod left in ImagePullBackOff after install in disconnected environment
  cmd/main.go
  go.mod
  internal/controller/controllers/agent_controller.go
  internal/oc/debug.go
  internal/oc/debug_test.go
  internal/spoke_k8s_client/factory.go
Labels: approved, size/L, lgtm, jira/valid-reference

#6386 MGMT-18010: Use the static installer for 4.16 nightlies when not FIPS-enabled
  internal/oc/release.go
  internal/oc/release_test.go
Labels: approved, size/S, lgtm, jira/valid-reference
