Repository openshift/assisted-service, pull requests merged in 2025-07, with the labels that each got.

#7813 NO-ISSUE: Set OCP 4.20 images
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7815 MGMT-20988: Add arbiter to cluster's hyperthreading and disk encryption in kube-api
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  api/hiveextension/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  internal/controller/controllers/clusterdeployments_controller.go
  subsystem/kubeapi/kubeapi_test.go
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/agentclusterinstall_types.go
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/zz_generated.deepcopy.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#7820 NO-ISSUE: Add slack notification when merge pipeline failed
  .tekton/assisted-service-rhel8-acm-ds-2-14-push.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-14-push.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7777 MGMT-20549: Add cluster validation for openshift-ai if cluster has no gpu
  api/vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  client/vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  internal/cluster/validation_id.go
  internal/operators/openshiftai/openshift_ai_operator.go
  internal/operators/openshiftai/openshift_ai_operator_test.go
  models/cluster_validation_id.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
Labels: approved, kind/dependency-change, size/L, api-review, lgtm, jira/valid-reference

#7847 NO-JIRA: Remove refs to shellcheck
  Dockerfile.assisted-service-build
  ci-images/Dockerfile.lint
Labels: approved, kind/dependency-change, size/XS, lgtm, jira/valid-reference

#7855 OCPBUGS-59300: Bump glog to v1.2.5
  go.mod
  go.sum
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/github.com/golang/glog/glog_file_nonwindows.go
  vendor/github.com/golang/glog/glog_file_windows.go
  vendor/github.com/golang/glog/internal/logsink/logsink.go
  vendor/modules.txt
Labels: approved, size/XS, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#7860 [release-ocm-2.14] NO-ISSUE: Remove redundant shellcheck image
  Dockerfile.assisted-service-build
  ci-images/Dockerfile.lint
Labels: approved, kind/dependency-change, size/XS, lgtm, jira/valid-reference

#7861 [release-ocm-2.10] NO-ISSUE: Remove redundant shellcheck image
  Dockerfile.assisted-service-build
  ci-images/Dockerfile.lint
Labels: approved, kind/dependency-change, size/XS, lgtm, jira/valid-reference

#7863 NO-ISSUE: Fix hermetic build for acm (rhel8)
  rpm-prefetching/assisted-service-rhel8/rpms.lock.yaml
  rpm-prefetching/assisted-service-rhel9/rpms.lock.yaml
Labels: approved, kind/dependency-change, lgtm, size/XXL, jira/valid-reference

#7866 NO-ISSUE: [master] Bump OCP versions: 4.13, 4.18, 4.16
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7869 NO-ISSUE: Add NHO and FAR back to the virtualization bundle
  internal/operators/fenceagentsremediation/fence_agents_remediation_operator.go
  internal/operators/nodehealthcheck/node_healthcheck_operator.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#7872 NO-ISSUE: Fix tekton pipeline
  .tekton/assisted-service-rhel8-acm-ds-2-15-pull-request.yaml
  .tekton/assisted-service-rhel8-acm-ds-2-15-push.yaml
  .tekton/assisted-service-rhel8-acm-ds-main-pull-request.yaml
  .tekton/assisted-service-rhel8-acm-ds-main-push.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-15-pull-request.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-15-push.yaml
  .tekton/assisted-service-rhel9-acm-ds-main-pull-request.yaml
  .tekton/assisted-service-rhel9-acm-ds-main-push.yaml
  .tekton/assisted-service-saas-main-pull-request.yaml
  .tekton/assisted-service-saas-main-push.yaml
  .tekton/assisted-service-saas-v2-43-pull-request.yaml
  .tekton/assisted-service-saas-v2-43-push.yaml
Labels: approved, lgtm, size/XXL, jira/valid-reference

#7878 [v2.43] NO-ISSUE: Add NHO and FAR back to the virtualization bundle (#7869)
  internal/operators/fenceagentsremediation/fence_agents_remediation_operator.go
  internal/operators/nodehealthcheck/node_healthcheck_operator.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#7884 [v2.43] MGMT-21252: MGMT-21253: Performance fixes for cluster monitoring
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/mock_cluster_api.go
  internal/network/connectivity_groups.go
  internal/network/connectivity_groups_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7879 MGMT-21252: Make l3_connected_addresses output deterministic
  internal/network/connectivity_groups.go
  internal/network/connectivity_groups_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7881 NO-ISSUE: [master] Bump OCP versions: 4.15, 4.17
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7877 OCPBUGS-58640,OCPBUGS-58635: Bump glog to v1.2.5 in release-4.18
  go.mod
  go.sum
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/github.com/golang/glog/glog_file_nonwindows.go
  vendor/github.com/golang/glog/glog_file_windows.go
  vendor/github.com/golang/glog/internal/logsink/logsink.go
  vendor/modules.txt
Labels: approved, size/XS, lgtm, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#7889 MGMT-21287: Remove NHO dependency in SNR
  internal/operators/nodehealthcheck/node_healthcheck_operator.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#7891 MGMT-21312: Index hosts by cluster id
  internal/migrations/20250728120000_add_host_by_cluster_id_index.go
  internal/migrations/migrations.go
Labels: approved, size/S, lgtm, jira/valid-reference

#7887 NO-ISSUE: Remove unused variables from cluster monitor loop
  internal/cluster/cluster.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#7899 [release-ocm-2.11] MGMT-21328: Increase the timeout for host stage - 'waiting for control plane' for operator deployments
  internal/controller/controllers/agentserviceconfig_controller.go
Labels: approved, size/S, jira/valid-reference

#7895 OCPBUGS-58634,OCPBUGS-58639: Bump glog to v1.2.5 in release-4.17
  go.mod
  go.sum
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/github.com/golang/glog/glog_file_nonwindows.go
  vendor/github.com/golang/glog/glog_file_windows.go
  vendor/github.com/golang/glog/internal/logsink/logsink.go
  vendor/modules.txt
Labels: approved, size/XS, lgtm, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference
