Repository openshift/assisted-service, pull requests merged in 2025-01, with the labels that each got.

#7152 MGMT-19601: Add tests for static networking in inventory_test
  internal/bminventory/inventory_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7155 MGMT-19582: Enable static networking with nmstate service flow in 4.18
  internal/common/test_configuration.go
  internal/ignition/discovery_test.go
  openshift/template.yaml
  pkg/staticnetworkconfig/backward_compatibility.go
  subsystem/infra_env_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#7128 [release-4.18] OCPBUGS-47491: MGMT-19537: Bump golang.org/x/net to 0.33.0
  go.mod
  go.sum
  vendor/github.com/openshift/assisted-service/api/common/common_types.go
  vendor/golang.org/x/net/LICENSE
  vendor/golang.org/x/net/html/doc.go
  vendor/golang.org/x/net/html/doctype.go
  vendor/golang.org/x/net/html/foreign.go
  vendor/golang.org/x/net/html/iter.go
  vendor/golang.org/x/net/html/node.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/http/httpguts/httplex.go
  vendor/golang.org/x/net/http2/client_conn_pool.go
  vendor/golang.org/x/net/http2/config.go
  vendor/golang.org/x/net/http2/config_go124.go
  vendor/golang.org/x/net/http2/config_pre_go124.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/http2.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/testsync.go
  vendor/golang.org/x/net/http2/timer.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/http2/unencrypted.go
  vendor/golang.org/x/net/http2/write.go
  vendor/golang.org/x/net/http2/writesched_priority.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/net/websocket/hybi.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/modules.txt
Labels: approved, size/M, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#7160 MGMT-19626: Skip MTU validation for Day 2
  internal/host/validations_test.go
  internal/host/validator.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7164 NO-ISSUE: [release-ocm-2.12] Bump OCP versions: 4.15, 4.17, 4.16
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7167 [cloud_hotfix_releases] NO-ISSUE: Merge ODF and day2 MTU validation fixes for releasing a hotfix v2.37.1
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/host.go
  internal/host/host_test.go
  internal/host/hostrole_test.go
  internal/host/hostutil/test_utils.go
  internal/host/mock_host_api.go
  internal/host/monitor.go
  internal/host/validations_test.go
  internal/host/validator.go
  internal/operators/manager_test.go
  internal/operators/odf/common.go
  internal/operators/odf/odf_operator.go
  internal/operators/odf/odf_operator_test.go
  internal/operators/odf/validation_test.go
  internal/operators/odf/validations.go
Labels: approved, size/XL, lgtm, jira/valid-reference

#7163 MGMT-19631: Enable FC on x86_64
  internal/hardware/validator.go
  internal/hardware/validator_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7166 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7147 MGMT-19381: Change downstream base image to rhel9.4 instead of ubi9
  Dockerfile.assisted-service-rhel9-mce
Labels: approved, kind/dependency-change, size/XS, lgtm, jira/valid-reference

#7171 NO-ISSUE: [master] Bump OCP versions: 4.12, 4.17
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7174 MGMT-19672: Add NTP sources to discovery environment - ACM 2.10
  internal/ignition/ignition.go
  internal/ignition/ignition_test.go
  internal/ignition/templates/add-ntp-sources.service
  internal/ignition/templates/add-ntp-sources.sh
  internal/ignition/templates/discovery.ign
Labels: approved, size/L, lgtm, jira/valid-reference

#7156 MGMT-19573: Track release stats in installercache
  cmd/main.go
  internal/ignition/installmanifests.go
  internal/ignition/installmanifests_test.go
  internal/installercache/installercache.go
  internal/installercache/installercache_test.go
  pkg/generator/generator.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7173 MGMT-19673: Add NTP sources to discovery environment - ACM 2.11
  .tekton/assisted-service-q2vh-pull-request.yaml
  .tekton/assisted-service-q2vh-push.yaml
  internal/ignition/discovery.go
  internal/ignition/discovery_test.go
  internal/ignition/templates/add-ntp-sources.service
  internal/ignition/templates/add-ntp-sources.sh
  internal/ignition/templates/discovery.ign
Labels: approved, size/XL, lgtm, jira/valid-reference

#7183 NO-ISSUE: [release-ocm-2.12] Bump OCP versions: 4.18, 4.16, 4.17, 4.12, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7184 NO-ISSUE: [release-ocm-2.11] Bump OCP versions: 4.16, 4.15, 4.12, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7181 OCPBUGS-43578: Log disk info if rootDeviceHint not found
  cmd/agentbasedinstaller/host_config.go
Labels: approved, size/S, lgtm, jira/valid-bug, jira/valid-reference

#7187 MGMT-19590: Enable user managed load balancer with hosts in the same subnet but load balancer outside this subnet on baremetal
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/validations/validations.go
  internal/cluster/validator.go
  internal/cluster/validator_test.go
  internal/featuresupport/features_networking.go
  internal/host/validations_test.go
  internal/host/validator.go
  internal/network/cidr_validations.go
  internal/network/cidr_validations_test.go
  internal/network/machine_network_cidr.go
  internal/network/machine_network_cidr_test.go
  internal/network/utils.go
Labels: approved, lgtm, size/XXL, jira/valid-reference

#7185 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.12, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7186 NO-ISSUE: [release-ocm-2.9] Bump OCP versions: 4.12, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7195 NO-ISSUE: Fix typos
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#7194 NO-ISSUE: [master] Bump OCP versions: 4.17, 4.15, 4.16
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#7090 MGMT-19120: Use service net to connect to hosted API server
  cmd/main.go
  cmd/operator/main.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller_test.go
  internal/controller/controllers/mock_spoke_client_cache.go
  internal/controller/controllers/spoke_client_cache.go
  internal/controller/controllers/spoke_client_cache_test.go
  internal/spoke_k8s_client/factory.go
  internal/spoke_k8s_client/factory_test.go
  internal/spoke_k8s_client/mock_spoke_k8s_client_factory.go
  internal/spoke_k8s_client/spoke_k8s_client.go
  internal/spoke_k8s_client/suite_test.go
Labels: approved, size/XL, lgtm, jira/valid-reference

#7202 MGMT-19748: Configure snyk ignore
  .tekton/assisted-service-rhel8-mce-downstream-2-13-pull-request.yaml
  .tekton/assisted-service-rhel8-mce-downstream-2-13-push.yaml
  .tekton/assisted-service-rhel8-mce-downstream-main-pull-request.yaml
  .tekton/assisted-service-rhel8-mce-downstream-main-push.yaml
  .tekton/assisted-service-rhel9-mce-downstream-2-13-pull-request.yaml
  .tekton/assisted-service-rhel9-mce-downstream-2-13-push.yaml
  .tekton/assisted-service-rhel9-mce-downstream-main-pull-request.yaml
  .tekton/assisted-service-rhel9-mce-downstream-main-push.yaml
  .tekton/assisted-service-saas-main-pull-request.yaml
  .tekton/assisted-service-saas-main-push.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7178 MGMT-19529: Send metrics about disk usage
  cmd/main.go
  internal/metrics/directory_usage_collector.go
  internal/metrics/directory_usage_collector_test.go
  internal/metrics/disk_stats_helper.go
  internal/metrics/metricsManager.go
  internal/metrics/metricsManager_test.go
  internal/metrics/mock_disk_stats_helper.go
  internal/metrics/os_disk_stats_helper_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7170 MGMT-19599: Extend the operator API to indicate to which bundle the operator belongs
  api/vendor/github.com/openshift/assisted-service/models/bundle.go
  api/vendor/github.com/openshift/assisted-service/models/monitored_operator.go
  client/operators/operators_client.go
  client/operators/v2_get_bundle_parameters.go
  client/operators/v2_get_bundle_responses.go
  client/operators/v2_list_bundles_parameters.go
  client/operators/v2_list_bundles_responses.go
  client/vendor/github.com/openshift/assisted-service/models/bundle.go
  client/vendor/github.com/openshift/assisted-service/models/monitored_operator.go
  docs/enhancements/operator-marketplace.md
  internal/operators/api/api.go
  internal/operators/api/mock_operator_api.go
  internal/operators/authorino/authorino_operator.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/common/common.go
  internal/operators/handler/handler_v2.go
  internal/operators/lso/ls_operator.go
  internal/operators/lvm/lvm_operator.go
  internal/operators/manager.go
  internal/operators/manager_test.go
  internal/operators/mce/mce_operator.go
  internal/operators/mock_operators_api.go
  internal/operators/mtv/operator.go
  internal/operators/nodefeaturediscovery/node_feature_discovery_operator.go
  internal/operators/nvidiagpu/nvidia_gpu_operator.go
  internal/operators/odf/odf_operator.go
  internal/operators/openshiftai/openshift_ai_operator.go
  internal/operators/osc/operator.go
  internal/operators/pipelines/pipelines_operator.go
  internal/operators/serverless/serverless_operator.go
  internal/operators/servicemesh/servicemesh_operator.go
  internal/spoke_k8s_client/gomock_reflect_3544310690/prog.go
  models/bundle.go
  models/monitored_operator.go
  restapi/configure_assisted_install.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/operators/v2_get_bundle.go
  restapi/operations/operators/v2_get_bundle_parameters.go
  restapi/operations/operators/v2_get_bundle_responses.go
  restapi/operations/operators/v2_get_bundle_urlbuilder.go
  restapi/operations/operators/v2_list_bundles.go
  restapi/operations/operators/v2_list_bundles_parameters.go
  restapi/operations/operators/v2_list_bundles_responses.go
  restapi/operations/operators/v2_list_bundles_urlbuilder.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/client/operators/operators_client.go
  vendor/github.com/openshift/assisted-service/client/operators/v2_get_bundle_parameters.go
  vendor/github.com/openshift/assisted-service/client/operators/v2_get_bundle_responses.go
  vendor/github.com/openshift/assisted-service/client/operators/v2_list_bundles_parameters.go
  vendor/github.com/openshift/assisted-service/client/operators/v2_list_bundles_responses.go
  vendor/github.com/openshift/assisted-service/models/bundle.go
  vendor/github.com/openshift/assisted-service/models/monitored_operator.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#7204 MGMT-19733: Enable user-managed load balancer with hosts on different subnets
  internal/featuresupport/features_misc.go
  internal/featuresupport/features_networking.go
  internal/host/validations_test.go
  internal/host/validator.go
  internal/ignition/installmanifests.go
  internal/ignition/installmanifests_test.go
  internal/installcfg/builder/builder.go
  internal/installcfg/builder/builder_test.go
  internal/network/machine_network_cidr.go
  internal/network/machine_network_cidr_test.go
  internal/provider/baremetal/installConfig.go
  internal/provider/baremetal/installConfig_test.go
  internal/provider/registry/registry_test.go
Labels: approved, lgtm, size/XXL, jira/valid-reference

#7208 NO-ISSUE: [master] Bump OCP versions: 4.18
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7212 NO-ISSUE: Update buildah image to fix a bug with SBOM
  .tekton/assisted-service-rhel8-mce-downstream-2-13-pull-request.yaml
  .tekton/assisted-service-rhel8-mce-downstream-2-13-push.yaml
  .tekton/assisted-service-rhel8-mce-downstream-main-pull-request.yaml
  .tekton/assisted-service-rhel8-mce-downstream-main-push.yaml
  .tekton/assisted-service-rhel9-mce-downstream-2-13-pull-request.yaml
  .tekton/assisted-service-rhel9-mce-downstream-2-13-push.yaml
  .tekton/assisted-service-rhel9-mce-downstream-main-pull-request.yaml
  .tekton/assisted-service-rhel9-mce-downstream-main-push.yaml
  .tekton/assisted-service-saas-main-pull-request.yaml
  .tekton/assisted-service-saas-main-push.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7197 MGMT-19100: Allow install to the existing root filesystem
  api/vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
  client/vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
  internal/host/conditions.go
  internal/host/conditions_test.go
  internal/host/config.go
  internal/host/host.go
  internal/host/hostcommands/disk_performance_cmd.go
  internal/host/hostcommands/disk_performance_cmd_test.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/instruction_manager.go
  internal/host/refresh_status_preprocessor.go
  internal/host/refresh_status_preprocessor_test.go
  internal/host/validator.go
  internal/oc/mock_release.go
  internal/oc/release.go
  models/install_cmd_request.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#7214 NO-ISSUE: [master] Bump OCP versions: 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7217 NO-ISSUE: Ensure that hard links are accounted for when measuring disk usage
  internal/metrics/disk_stats_helper.go
  internal/metrics/os_disk_stats_helper_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7188 OCPBUGS-48390: Bump moby from v26.0.0 to v27.2.1
  go.mod
  go.sum
  vendor/github.com/moby/moby/AUTHORS
  vendor/github.com/moby/moby/pkg/ioutils/fswriters.go
  vendor/modules.txt
Labels: approved, size/XS, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7193 MGMT-19708: Ignore mirrored registries when validating pull secrets
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/mock_installer_internal.go
  internal/cluster/validations/mock_pull_secret_validation.go
  internal/cluster/validations/pull_secret_validation.go
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/controller/controllers/infraenv_controller_test.go
  internal/controller/controllers/pullsecret_handler.go
Labels: approved, size/XL, lgtm, jira/valid-reference

#7226 NO-ISSUE: [master] Bump OCP versions: 4.19, 4.18
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7221 MGMT-19102: Add boot device type
  api/v1beta1/agent_types.go
  api/vendor/github.com/openshift/assisted-service/models/boot.go
  client/vendor/github.com/openshift/assisted-service/models/boot.go
  config/crd/bases/agent-install.openshift.io_agents.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
  internal/controller/controllers/agent_controller.go
  models/boot.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/api/v1beta1/agent_types.go
  vendor/github.com/openshift/assisted-service/models/boot.go
Labels: approved, size/S, api-review, lgtm, jira/valid-reference

#7207 MGMT-19358: Switch mirror registry references for disconnected CAPI script
  deploy/operator/capi/deploy_capi_cluster.sh
Labels: approved, size/M, lgtm, jira/valid-reference

#7232 NO-ISSUE: [release-ocm-2.12] Bump OCP versions: 4.14, 4.18
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7235 NO-ISSUE: [release-ocm-2.9] Bump OCP versions: 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7233 NO-ISSUE: [release-ocm-2.11] Bump OCP versions: 4.15, 4.14, 4.16
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7236 NO-ISSUE: Set CPU Limit for envoy
  openshift/template.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#7234 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.15, 4.14, 4.16
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7229 [release-ocm-2.12] MGMT-19708: Add assisted mirror registries to public registries list
  cmd/main.go
  internal/cluster/validations/pull_secret_validation.go
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7237 MGMT-19102: Use inventory to determine if install is on the existing root
  internal/host/conditions.go
  internal/host/conditions_test.go
  internal/host/config.go
  internal/host/host.go
  internal/host/hostcommands/disk_performance_cmd.go
  internal/host/hostcommands/disk_performance_cmd_test.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/instruction_manager.go
  internal/host/refresh_status_preprocessor.go
  internal/host/refresh_status_preprocessor_test.go
  internal/host/validator.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7231 [release-ocm-2.10] MGMT-19708: Add assisted mirror registries to public registries list
  cmd/main.go
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7238 NO-ISSUE: [master] Bump OCP versions: 4.17, 4.16
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7242 MGMT-19815: Update tekton pipelines to point to new components
  .tekton/assisted-service-rhel8-acm-ds-2-13-pull-request.yaml
  .tekton/assisted-service-rhel8-acm-ds-2-13-push.yaml
  .tekton/assisted-service-rhel8-acm-ds-main-pull-request.yaml
  .tekton/assisted-service-rhel8-acm-ds-main-push.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-13-pull-request.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-13-push.yaml
  .tekton/assisted-service-rhel9-acm-ds-main-pull-request.yaml
  .tekton/assisted-service-rhel9-acm-ds-main-push.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7230 [release-ocm-2.11] MGMT-19834: Add assisted mirror registries to public registries list
  cmd/main.go
  internal/cluster/validations/pull_secret_validation.go
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7241 MGMT-19819: Add the commit reference from which the image is built to the image
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, size/XS, lgtm, jira/valid-reference

#7245 NO-ISSUE: Modify the multipath + iSCSI setup doc
  docs/dev/multipath-iscsi.md
  docs/dev/multipath-iscsi.png
  docs/dev/multipath.md
Labels: approved, size/XL, lgtm, jira/valid-reference

#7215 MGMT-19657: Adding nmstate operator to assisted installer
  api/vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  api/vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  client/vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  client/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  client/vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  docs/dev/olm-operator-plugins.md
  internal/cluster/cluster_test.go
  internal/cluster/statemachine.go
  internal/cluster/validation_id.go
  internal/featuresupport/feature_support_level.go
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features_olm_operators.go
  internal/featuresupport/features_olm_operators_test.go
  internal/featuresupport/features_platforms.go
  internal/host/statemachine.go
  internal/host/transition_test.go
  internal/host/validation_id.go
  internal/operators/builder.go
  internal/operators/manager_test.go
  internal/operators/nmstate/config.go
  internal/operators/nmstate/manifest.go
  internal/operators/nmstate/manifest_test.go
  internal/operators/nmstate/nmstate_suite_test.go
  internal/operators/nmstate/operator.go
  internal/operators/nmstate/operator_test.go
  models/cluster_validation_id.go
  models/feature_support_level_id.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  subsystem/operators_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  vendor/github.com/openshift/assisted-service/models/host_validation_id.go
Labels: approved, size/XL, api-review, lgtm, ok-to-test, jira/valid-reference

#7244 NO-ISSUE: [master] Bump OCP versions: 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7243 MGMT-19792: Add discovery ignition URL to the infraenv status
  api/v1beta1/infraenv_types.go
  config/crd/bases/agent-install.openshift.io_infraenvs.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_infraenvs.yaml
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/infraenv_types.go
Labels: approved, size/M, api-review, lgtm, jira/valid-reference

#7254 MGMT-19844: Validate the internal ignition override
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/ignition/ignition.go
Labels: approved, size/S, lgtm, jira/valid-reference
