Repository openshift/assisted-service, pull requests merged in 2025-08, with the labels that each got.

#7913 [release-ocm-2.12] ACM-22788: Approve CSRs for a host before marking as Done
  api/v1beta1/agent_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/agent-install.openshift.io_agents.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/agent-install.openshift.io_agents.yaml
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/agent_types.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/zz_generated.deepcopy.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#7917 NO-ISSUE: [master] Bump OCP versions: 4.20, 4.14
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7888 MGMT-21063: Use mac address to configure dhcp on kargs
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7918 OCPBUGS-59112,OCPBUGS-59113: Bump glog to v1.2.5 in release-4.13
  go.mod
  go.sum
  vendor/github.com/golang/glog/glog.go
  vendor/github.com/golang/glog/glog_file.go
  vendor/github.com/golang/glog/glog_file_linux.go
  vendor/github.com/golang/glog/glog_file_nonwindows.go
  vendor/github.com/golang/glog/glog_file_other.go
  vendor/github.com/golang/glog/glog_file_posix.go
  vendor/github.com/golang/glog/glog_file_windows.go
  vendor/github.com/golang/glog/glog_flags.go
  vendor/github.com/golang/glog/internal/logsink/logsink.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/equate.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/ignore.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/sort.go
  vendor/github.com/google/go-cmp/cmp/cmpopts/xform.go
  vendor/github.com/google/go-cmp/cmp/compare.go
  vendor/github.com/google/go-cmp/cmp/export.go
  vendor/github.com/google/go-cmp/cmp/export_panic.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer.go
  vendor/github.com/google/go-cmp/cmp/internal/value/pointer_purego.go
  vendor/github.com/google/go-cmp/cmp/options.go
  vendor/github.com/google/go-cmp/cmp/path.go
  vendor/github.com/google/go-cmp/cmp/report_reflect.go
  vendor/modules.txt
Labels: approved, size/S, lgtm, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#7921 NO-ISSUE: [master] Bump OCP versions: 4.19
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7924 NO-ISSUE: [master] Bump OCP versions: 4.15, 4.17
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7922 NO-ISSUE: support setting TNA_CLUSTERS_SUPPORT when deploying with assisted-test-infra
  Makefile
  deploy/assisted-service-configmap.yaml
  tools/deploy_assisted_installer_configmap.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#7923 OCPBUGS-59393: Fix IsMachineCidrEqualsToCalculatedCidr validation to handle unnormalized IPv6 addresses
  internal/cluster/validator.go
  internal/cluster/validator_test.go
  internal/common/test_configuration.go
  internal/network/utils.go
  internal/network/utils_test.go
Labels: approved, size/L, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#7927 NO-ISSUE: [master] Bump OCP versions: 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#7933 MGMT-21274: Report duration of monitored hosts
  cmd/main.go
  internal/host/monitor.go
  internal/host/monitor_test.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_metrics_manager_api.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7949 MGMT-21395: Add monitoring label and Prometheus RBAC for supported OLM operators
  docs/dev/olm-operator-plugins.md
  internal/operators/amdgpu/amd_gpu_manifests_test.go
  internal/operators/amdgpu/templates/openshift/50_amd_gpu_namespace.yaml
  internal/operators/amdgpu/templates/openshift/50_amd_gpu_prometheus-role.yaml
  internal/operators/amdgpu/templates/openshift/50_amd_gpu_prometheus-rolebinding.yaml
  internal/operators/clusterobservability/templates/openshift/50_cluster_observability_namespace.yaml
  internal/operators/kubedescheduler/templates/openshift/50_kube_descheduler_namespace.yaml
  internal/operators/lso/manifest.go
  internal/operators/lso/manifests_test.go
  internal/operators/manager_test.go
  internal/operators/nodefeaturediscovery/templates/openshift/50_nodefeaturediscovery_namespace.yaml
  internal/operators/numaresources/numaresources_manifests_test.go
  internal/operators/numaresources/templates/openshift/50_numaresources_namespace.yaml
  internal/operators/numaresources/templates/openshift/50_numaresources_prometheus-role.yaml
  internal/operators/numaresources/templates/openshift/50_numaresources_prometheus-rolebinding.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#7935 ACM-21902: Merge system ca-bundle into spoke client
  cmd/main.go
  cmd/operator/main.go
  internal/spoke_k8s_client/factory.go
  internal/spoke_k8s_client/factory_test.go
  internal/system/mock_system.go
  internal/system/system.go
Labels: approved, size/L, lgtm, jira/valid-reference
