Repository openshift/assisted-service, pull requests merged in 2025-06, with the labels that each got.

#7705 MGMT-20700: Revert "MGMT-20272: Cluster attribute finalizing_stage_started_at show wrong value (#7594)"
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7702 MGMT-20664: ironic inspection fails when hub and spoke architectures are different
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7695 MGMT-20604: Modify Global DNS workaround to also check for dhcp: true
  pkg/staticnetworkconfig/backward_compatibility.go
  pkg/staticnetworkconfig/backward_compatibility_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7720 [cloud_hotfix_releases] NO-ISSUE: Prepare release v2.41.1 (with Konflux files)
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
Labels: approved, size/M, jira/valid-reference

#7642 MGMT-20605: Add logic to handle cancelling a day-2 host installation
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/host/common.go
  internal/host/host_test.go
  internal/host/statemachine.go
  internal/host/transition_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7712 [release-ocm-2.11] MGMT-20740: Don't require mapping for names matching physical interfaces (PR #6715)
  pkg/staticnetworkconfig/generator.go
  pkg/staticnetworkconfig/generator_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7721 NO-ISSUE: Update operator bundle channel to ocm-2.15
  Makefile
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/metadata/annotations.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#7729 [cloud_hotfix_releases] NO-ISSUE: Prepare release v2.41.2
  internal/operators/nodefeaturediscovery/templates/custom/nodefeaturediscovery.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#7726 NO-ISSUE: [master] Bump OCP versions: 4.17, 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7703 OCPBUGS-56596: Include AdditionalTrustBundlePolicy in installConfig
  internal/installcfg/builder/builder_test.go
  internal/installcfg/installcfg.go
Labels: approved, size/S, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7734 [release-ocm-2.14] NO-ISSUE: Remove old OS images from release-ocm-2.14
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  docs/hive-integration/crds/agentClusterInstall-with-installconfig-overrides.yaml
  docs/hive-integration/crds/agentClusterInstall.yaml
  docs/hive-integration/crds/clusterImageSet.yaml
  openshift/template.yaml
  subsystem/agent_based_installer_client_test.go
  subsystem/cluster_test.go
  subsystem/cluster_v2_test.go
  subsystem/feature_support_levels_test.go
  subsystem/host_test.go
  subsystem/infra_env_test.go
  subsystem/kubeapi/kubeapi_suite_test.go
  subsystem/metrics_test.go
  subsystem/operators_test.go
  subsystem/subsystem_suite_test.go
  subsystem/utils_test/subsystem_test_context.go
Labels: approved, lgtm, size/XXL, jira/valid-reference

#7714 [release-ocm-2.13] MGMT-20601: Update pull secret validation
  go.mod
  go.sum
  internal/cluster/validations/pull_secret_validation.go
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
  internal/common/common.go
  vendor/github.com/distribution/reference/README.md
  vendor/github.com/distribution/reference/normalize.go
  vendor/github.com/distribution/reference/reference.go
  vendor/github.com/docker/distribution/LICENSE
  vendor/github.com/docker/distribution/digestset/set.go
  vendor/github.com/docker/distribution/reference/helpers.go
  vendor/github.com/docker/distribution/reference/normalize.go
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/docker/distribution/reference/regexp.go
  vendor/modules.txt
Labels: approved, size/L, lgtm, jira/valid-reference

#7752 NO-ISSUE: [master] Bump OCP versions: 4.18
  data/default_os_images.json
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7755 ACM-21380: Make ACM builds multi-arch
  .tekton/assisted-service-rhel8-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-service-rhel8-acm-ds-2-14-push.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-14-push.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7744 MGMT-19999: allow automatic detection of ironic agent image in case of multi arch installation
  docs/hive-integration/README.md
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7756 NO-ISSUE: [master] Bump OCP versions: 4.17
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7749 ACM-21001: Allow Host Management if explicitly set
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7762 NO-ISSUE: [master] Bump OCP versions: 4.16
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7767 MGMT-20858: apply tags migration
  .tekton/assisted-service-rhel8-acm-ds-2-13-pull-request.yaml
  .tekton/assisted-service-rhel8-acm-ds-2-13-push.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-13-pull-request.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-13-push.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7768 MGMT-20858: apply tags migration
  .tekton/assisted-service-rhel8-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-service-rhel8-acm-ds-2-14-push.yaml
  .tekton/assisted-service-rhel8-acm-ds-main-pull-request.yaml
  .tekton/assisted-service-rhel8-acm-ds-main-push.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-14-push.yaml
  .tekton/assisted-service-rhel9-acm-ds-main-pull-request.yaml
  .tekton/assisted-service-rhel9-acm-ds-main-push.yaml
  .tekton/assisted-service-saas-main-pull-request.yaml
  .tekton/assisted-service-saas-main-push.yaml
Labels: approved, lgtm, size/XXL, jira/valid-reference

#7769 MGMT-20858: apply tags migration
  .tekton/assisted-service-rhel8-acm-ds-2-15-pull-request.yaml
  .tekton/assisted-service-rhel8-acm-ds-2-15-push.yaml
  .tekton/assisted-service-rhel8-acm-ds-main-pull-request.yaml
  .tekton/assisted-service-rhel8-acm-ds-main-push.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-15-pull-request.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-15-push.yaml
  .tekton/assisted-service-rhel9-acm-ds-main-pull-request.yaml
  .tekton/assisted-service-rhel9-acm-ds-main-push.yaml
  .tekton/assisted-service-saas-main-pull-request.yaml
  .tekton/assisted-service-saas-main-push.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#7709 MGMT-20674: Operator may return several ValidationResult
  internal/operators/amdgpu/amd_gpu_operator.go
  internal/operators/api/api.go
  internal/operators/api/mock_operator_api.go
  internal/operators/authorino/authorino_operator.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/cnv/cnv_operator_test.go
  internal/operators/fenceagentsremediation/fence_agents_remediation_consts.go
  internal/operators/fenceagentsremediation/fence_agents_remediation_operator.go
  internal/operators/fenceagentsremediation/fence_agents_remediation_validations.go
  internal/operators/kmm/kmm_operator.go
  internal/operators/kubedescheduler/kube_descheduler_consts.go
  internal/operators/kubedescheduler/kube_descheduler_operator.go
  internal/operators/kubedescheduler/kube_descheduler_validations.go
  internal/operators/lso/ls_operator.go
  internal/operators/lvm/lvm_operator.go
  internal/operators/lvm/lvm_operator_test.go
  internal/operators/manager.go
  internal/operators/manager_test.go
  internal/operators/mce/mce_operator.go
  internal/operators/mce/mce_operator_test.go
  internal/operators/mtv/config.go
  internal/operators/mtv/operator.go
  internal/operators/mtv/operator_test.go
  internal/operators/nmstate/operator.go
  internal/operators/nmstate/operator_test.go
  internal/operators/nodefeaturediscovery/node_feature_discovery_operator.go
  internal/operators/nodehealthcheck/node_healthcheck_consts.go
  internal/operators/nodehealthcheck/node_healthcheck_operator.go
  internal/operators/nodehealthcheck/node_healthcheck_validations.go
  internal/operators/nodemaintenance/node_maintenance_consts.go
  internal/operators/nodemaintenance/node_maintenance_operator.go
  internal/operators/nodemaintenance/node_maintenance_validations.go
  internal/operators/nvidiagpu/nvidia_gpu_operator.go
  internal/operators/odf/consts.go
  internal/operators/odf/odf_operator.go
  internal/operators/odf/odf_operator_test.go
  internal/operators/openshiftai/openshift_ai_operator.go
  internal/operators/osc/operator.go
  internal/operators/osc/operator_test.go
  internal/operators/pipelines/pipelines_operator.go
  internal/operators/selfnoderemediation/self_node_remediation_consts.go
  internal/operators/selfnoderemediation/self_node_remediation_operator.go
  internal/operators/selfnoderemediation/self_node_remediation_validations.go
  internal/operators/serverless/serverless_operator.go
  internal/operators/servicemesh/servicemesh_operator.go
Labels: approved, size/XL, lgtm, jira/valid-reference

#7776 OCPEDGE-1933: feat: update featureSet for arbiter
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features_misc.go
  internal/installcfg/builder/builder.go
  internal/installcfg/builder/builder_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7784 MGMT-20914: Prepare image versions for OCP 4.19 GA
  data/default_release_sources.json
Labels: approved, size/M, lgtm, jira/valid-reference

#7785 MGMT-20918: Override OCP 4.20 index image for LSO installation
  deploy/operator/setup_lso.sh
Labels: approved, size/S, lgtm, jira/valid-reference

#7772 OCPBUGS-57361: Use hostname to match hosts to BMH ignition
  internal/ignition/installmanifests.go
  internal/ignition/installmanifests_test.go
Labels: approved, size/M, lgtm, jira/valid-bug, jira/valid-reference

#7792 NO-ISSUE: [release-ocm-2.14] Bump OCP versions: 4.19
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#7764 MGMT-20651: Assisted Service panics if both installation_disk_id and installation-disk_path are empty
  internal/host/hostutil/host_utils.go
  internal/host/hostutil/host_utils_test.go
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7765 OCPEDGE-1931: add arbiter agents counts
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  config/crd/bases/extensions.hive.openshift.io_agentclusterinstalls.yaml
  config/crd/resources.yaml
  deploy/olm-catalog/manifests/extensions.hive.openshift.io_agentclusterinstalls.yaml
  internal/common/db_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/agentclusterinstall_types.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#7795 MGMT-20893: Remove Remediation operators from virtualization bundle
  internal/operators/fenceagentsremediation/fence_agents_remediation_operator.go
  internal/operators/nodehealthcheck/node_healthcheck_operator.go
  internal/operators/selfnoderemediation/self_node_remediation_operator.go
Labels: approved, size/S, lgtm, jira/valid-reference

#7805 NO-ISSUE: [master] Bump OCP versions: 4.18, 4.15, 4.17
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference
