Repository openshift/assisted-service, pull requests merged in 2025-03, with the labels that each got.

#7356 [release-ocm-2.13] MGMT-20066: Remove 4.19 pre-release os images
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7365 MGMT-20080: Add unitests to check mirroring priority
  internal/ignition/discovery_test.go
  internal/installcfg/builder/builder_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7364 MGMT-20005: Prepare OCP 4.18 / 4.19 images for OCP 4.18 GA
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  data/default_release_sources.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7325 MGMT-19939: Allow using the rootfs install method to add nodes
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7368 NO-ISSUE: [release-ocm-2.12] Bump OCP versions: 4.16, 4.17, 4.15
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#7281 MGMT-19840: Gather operational metrics from installercache
  cmd/main.go
  internal/ignition/installmanifests_test.go
  internal/installercache/installercache.go
  internal/installercache/installercache_test.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_metrics_manager_api.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7375 NO-ISSUE: Update konflux pipeline
  .tekton/assisted-service-saas-hotfix-pull-request.yaml
  .tekton/assisted-service-saas-hotfix-push.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7189 OCPBUGS-45244: Bump moby from v26.0.0 to v27.2.1
  go.mod
  go.sum
  vendor/github.com/moby/moby/AUTHORS
  vendor/github.com/moby/moby/pkg/ioutils/fswriters.go
  vendor/modules.txt
Labels: approved, size/XS, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7380 NO-ISSUE: [master] Bump OCP versions: 4.16, 4.18, 4.17
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7367 NO-ISSUE: [release-ocm-2.13] Bump OCP versions: 4.14, 4.16, 4.17, 4.18, 4.15
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#7370 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.16, 4.15
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7348 MGMT-20022: Handle missing ManagedCluster in non MCE environments
  cmd/operator/main.go
  deploy/operator/hypershift/deploy_hypershift_cluster.sh
  deploy/operator/setup_assisted_operator.sh
  hack/crds/hive/hive.openshift.io_clusterdeployments.yaml
  hack/crds/hive/hive.openshift.io_clusterimagesets.yaml
  hack/crds/mce/managedclusters.cluster.open-cluster-management.io.yaml
  hack/crds/metal3/metal3.io_baremetalhosts.yaml
  hack/crds/metal3/metal3.io_preprovisioningimages.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#7369 NO-ISSUE: [release-ocm-2.11] Bump OCP versions: 4.16, 4.15
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7378 MGMT-20099: add nmstate to /v2/supported-operators
  restapi/embedded_spec.go
  swagger.yaml
Labels: approved, size/XS, api-review, lgtm, jira/valid-reference

#7372 MGMT-19832: Fix time out during cluster last finalizing stage
  docs/user-guide/finalization_stages_timeouts.md
  internal/cluster/finalizing_stages.go
Labels: approved, size/S, lgtm, jira/valid-reference

#7386 NO-ISSUE: Fix bug in MTU validation for CMN - validation should pass if all reports are checked
  internal/host/validator.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#7383 MGMT-19596: Fixing broken KubeAPI tests
  subsystem/kubeapi/kubeapi_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7272 MGMT-19830: Enable installation of OCP clusters in vSphere environments with user-managed LB
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features_networking.go
  internal/featuresupport/features_platforms.go
  internal/provider/baremetal/installConfig.go
  internal/provider/vsphere/installConfig.go
  internal/provider/vsphere/installConfig_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7393 NO-ISSUE: [release-ocm-2.12] Bump OCP versions: 4.17, 4.18, 4.16
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7397 NO-ISSUE: [master] Bump OCP versions: 4.18, 4.19
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7398 NO-ISSUE: Fix Konflux configuration for ocm-2.14
  .tekton/assisted-service-rhel8-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-service-rhel8-acm-ds-2-14-push.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-14-push.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7400 NO-ISSUE: [master] Bump OCP versions: 4.17
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7390 NO-ISSUE: Modify condition to get release image when installing hosts
  internal/host/hostcommands/install_cmd.go
Labels: approved, size/S, lgtm, jira/valid-reference

#7408 NO-ISSUE: [master] Bump OCP versions: 4.15, 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7415 NO-ISSUE: Fix setuptools issue
  ci-images/Dockerfile.base
  ci-images/Dockerfile.subsystem
  hack/setup_env.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#7431 [release-ocm-2.12] ACM-18653: CVE-2025-22869 - change golang.org/x/crypto to openshift/golang-crypto to fix a cve
  go.mod
  go.sum
  vendor/github.com/openshift/assisted-service/api/common/zz_generated.deepcopy.go
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/zz_generated.deepcopy.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_x86.go
  vendor/golang.org/x/sys/unix/auxv.go
  vendor/golang.org/x/sys/unix/auxv_unsupported.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/modules.txt
Labels: approved, size/M, lgtm, jira/valid-reference

#7434 [release-ocm-2.9] ACM-18651: CVE-2025-22869 - change golang.org/x/crypto to openshift/golang-crypto to fix a cve
  go.mod
  go.sum
  vendor/github.com/openshift/assisted-service/api/common/zz_generated.deepcopy.go
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/zz_generated.deepcopy.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_x86.go
  vendor/golang.org/x/sys/unix/auxv.go
  vendor/golang.org/x/sys/unix/auxv_unsupported.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/modules.txt
Labels: approved, size/M, lgtm, jira/valid-reference

#7373 MGMT-19423: Remove HighAvailabilityMode from assisted-service
  api/vendor/github.com/openshift/assisted-service/models/cluster.go
  api/vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
  client/vendor/github.com/openshift/assisted-service/models/cluster.go
  client/vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
  docs/user-guide/rest-api-getting-started.md
  docs/user-guide/samples/cluster.json
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/progress_test.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/cluster/validations/validations.go
  internal/cluster/validator.go
  internal/cluster/validator_test.go
  internal/common/common.go
  internal/common/common_test.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  internal/dns/dns.go
  internal/dns/dns_test.go
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features_misc.go
  internal/hardware/validator_test.go
  internal/host/host_test.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/transition_test.go
  internal/host/validations_test.go
  internal/ignition/installmanifests.go
  internal/ignition/installmanifests_test.go
  internal/installcfg/builder/builder_test.go
  internal/operators/cnv/cnv_operator_test.go
  internal/operators/cnv/manifests_test.go
  internal/operators/lvm/lvm_operator.go
  internal/operators/lvm/lvm_operator_test.go
  internal/operators/lvm/manifests_test.go
  internal/operators/manager_test.go
  internal/operators/mce/mce_operator_test.go
  internal/operators/mtv/operator_test.go
  internal/operators/nmstate/operator_test.go
  internal/operators/osc/operator_test.go
  internal/provider/platform.go
  internal/usage/consts.go
  models/cluster.go
  models/install_cmd_request.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_mutating_hook.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_mutating_hook_test.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook.go
  pkg/webhooks/hiveextension/v1beta1/agentclusterinstall_validation_hook_test.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  subsystem/feature_support_levels_test.go
  subsystem/operators_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster.go
  vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
Labels: approved, api-review, lgtm, size/XXL, jira/valid-reference

#7433 [release-ocm-2.10] ACM-18549: CVE-2025-22869 - change golang.org/x/crypto to openshift/golang-crypto to fix a cve
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_x86.go
  vendor/golang.org/x/sys/unix/auxv.go
  vendor/golang.org/x/sys/unix/auxv_unsupported.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/modules.txt
Labels: approved, size/M, lgtm, jira/valid-reference

#7428 [release-ocm-2.11] ACM-18732: CVE-2025-27144 Bump github.com/go-jose/go-jose to v3.0.4
  go.mod
  go.sum
  pkg/auth/auth_handler_test_utils.go
  vendor/github.com/go-jose/go-jose/.gitcookies.sh.enc
  vendor/github.com/go-jose/go-jose/.travis.yml
  vendor/github.com/go-jose/go-jose/README.md
  vendor/github.com/go-jose/go-jose/v3/.gitignore
  vendor/github.com/go-jose/go-jose/v3/.golangci.yml
  vendor/github.com/go-jose/go-jose/v3/.travis.yml
  vendor/github.com/go-jose/go-jose/v3/CHANGELOG.md
  vendor/github.com/go-jose/go-jose/v3/CONTRIBUTING.md
  vendor/github.com/go-jose/go-jose/v3/LICENSE
  vendor/github.com/go-jose/go-jose/v3/README.md
  vendor/github.com/go-jose/go-jose/v3/SECURITY.md
  vendor/github.com/go-jose/go-jose/v3/asymmetric.go
  vendor/github.com/go-jose/go-jose/v3/cipher/cbc_hmac.go
  vendor/github.com/go-jose/go-jose/v3/cipher/concat_kdf.go
  vendor/github.com/go-jose/go-jose/v3/cipher/ecdh_es.go
  vendor/github.com/go-jose/go-jose/v3/cipher/key_wrap.go
  vendor/github.com/go-jose/go-jose/v3/crypter.go
  vendor/github.com/go-jose/go-jose/v3/doc.go
  vendor/github.com/go-jose/go-jose/v3/encoding.go
  vendor/github.com/go-jose/go-jose/v3/json/LICENSE
  vendor/github.com/go-jose/go-jose/v3/json/README.md
  vendor/github.com/go-jose/go-jose/v3/json/decode.go
  vendor/github.com/go-jose/go-jose/v3/json/encode.go
  vendor/github.com/go-jose/go-jose/v3/json/indent.go
  vendor/github.com/go-jose/go-jose/v3/json/scanner.go
  vendor/github.com/go-jose/go-jose/v3/json/stream.go
  vendor/github.com/go-jose/go-jose/v3/json/tags.go
  vendor/github.com/go-jose/go-jose/v3/jwe.go
  vendor/github.com/go-jose/go-jose/v3/jwk.go
  vendor/github.com/go-jose/go-jose/v3/jws.go
  vendor/github.com/go-jose/go-jose/v3/opaque.go
  vendor/github.com/go-jose/go-jose/v3/shared.go
  vendor/github.com/go-jose/go-jose/v3/signing.go
  vendor/github.com/go-jose/go-jose/v3/symmetric.go
  vendor/golang.org/x/crypto/ed25519/ed25519.go
  vendor/gopkg.in/go-jose/go-jose.v2/LICENSE
  vendor/gopkg.in/go-jose/go-jose.v2/json/LICENSE
  vendor/gopkg.in/go-jose/go-jose.v2/json/README.md
  vendor/gopkg.in/go-jose/go-jose.v2/json/decode.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/encode.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/indent.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/scanner.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/stream.go
  vendor/gopkg.in/go-jose/go-jose.v2/json/tags.go
  vendor/modules.txt
Labels: approved, size/S, lgtm, jira/valid-reference

#7427 [release-ocm-2.12] ACM-18075: CVE-2025-27144 Bump github.com/go-jose/go-jose to v4.0.5
  go.mod
  go.sum
  vendor/github.com/go-jose/go-jose/v4/CONTRIBUTING.md
  vendor/github.com/go-jose/go-jose/v4/README.md
  vendor/github.com/go-jose/go-jose/v4/jwe.go
  vendor/github.com/go-jose/go-jose/v4/jwk.go
  vendor/github.com/go-jose/go-jose/v4/jws.go
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_custom.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_default.go
  vendor/github.com/stretchr/testify/assert/yaml/yaml_fail.go
  vendor/github.com/stretchr/testify/mock/mock.go
  vendor/modules.txt
Labels: approved, size/S, lgtm, jira/valid-reference

#7432 [release-ocm-2.11] ACM-18552: CVE-2025-22869 - change golang.org/x/crypto to openshift/golang-crypto to fix a cve
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_x86.go
  vendor/golang.org/x/sys/unix/auxv.go
  vendor/golang.org/x/sys/unix/auxv_unsupported.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/modules.txt
Labels: approved, size/M, lgtm, jira/valid-reference

#7341 MGMT-19903: Disable ODF and OpenShift AI Operators for Oracle (OCI)
  internal/featuresupport/features_olm_operators.go
  internal/featuresupport/features_platforms.go
Labels: approved, size/S, lgtm, jira/valid-reference

#7410 OCPBUGS-53031: Bump oauth2 with v0.26.openshift.1
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/LICENSE
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/internal/client_appengine.go
  vendor/golang.org/x/oauth2/internal/transport.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/token.go
  vendor/google.golang.org/appengine/LICENSE
  vendor/google.golang.org/appengine/internal/api.go
  vendor/google.golang.org/appengine/internal/api_classic.go
  vendor/google.golang.org/appengine/internal/api_common.go
  vendor/google.golang.org/appengine/internal/app_id.go
  vendor/google.golang.org/appengine/internal/base/api_base.pb.go
  vendor/google.golang.org/appengine/internal/base/api_base.proto
  vendor/google.golang.org/appengine/internal/datastore/datastore_v3.pb.go
  vendor/google.golang.org/appengine/internal/datastore/datastore_v3.proto
  vendor/google.golang.org/appengine/internal/identity.go
  vendor/google.golang.org/appengine/internal/identity_classic.go
  vendor/google.golang.org/appengine/internal/identity_flex.go
  vendor/google.golang.org/appengine/internal/identity_vm.go
  vendor/google.golang.org/appengine/internal/internal.go
  vendor/google.golang.org/appengine/internal/log/log_service.pb.go
  vendor/google.golang.org/appengine/internal/log/log_service.proto
  vendor/google.golang.org/appengine/internal/main.go
  vendor/google.golang.org/appengine/internal/main_common.go
  vendor/google.golang.org/appengine/internal/main_vm.go
  vendor/google.golang.org/appengine/internal/metadata.go
  vendor/google.golang.org/appengine/internal/net.go
  vendor/google.golang.org/appengine/internal/regen.sh
  vendor/google.golang.org/appengine/internal/remote_api/remote_api.pb.go
  vendor/google.golang.org/appengine/internal/remote_api/remote_api.proto
  vendor/google.golang.org/appengine/internal/transaction.go
  vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.pb.go
  vendor/google.golang.org/appengine/internal/urlfetch/urlfetch_service.proto
  vendor/google.golang.org/appengine/urlfetch/urlfetch.go
  vendor/modules.txt
Labels: approved, size/S, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#7443 NO-ISSUE: [master] Bump OCP versions: 4.17, 4.13, 4.18, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7440 [release-ocm-2.13] MGMT-20149: Add required sast tasks for Konflux
  .tekton/assisted-service-rhel8-acm-ds-2-13-pull-request.yaml
  .tekton/assisted-service-rhel8-acm-ds-2-13-push.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-13-pull-request.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-13-push.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#7447 [release-ocm-2.13] NO-ISSUE: Remove eran ifrach account from OWNERS
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#7441 MGMT-20149: Add required sast tasks for Konflux
  .tekton/assisted-service-rhel8-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-service-rhel8-acm-ds-2-14-push.yaml
  .tekton/assisted-service-rhel8-acm-ds-main-pull-request.yaml
  .tekton/assisted-service-rhel8-acm-ds-main-push.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-14-push.yaml
  .tekton/assisted-service-rhel9-acm-ds-main-pull-request.yaml
  .tekton/assisted-service-rhel9-acm-ds-main-push.yaml
  .tekton/assisted-service-saas-main-pull-request.yaml
  .tekton/assisted-service-saas-main-push.yaml
Labels: approved, lgtm, size/XXL, jira/valid-reference

#7453 [release-ocm-2.9] NO-ISSUE: Update OWNERS
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#7452 [release-ocm-2.11] NO-ISSUE: Update OWNERS
  OWNERS_ALIASES
Labels: approved, size/XS, lgtm, jira/valid-reference

#7391 AGENT-538: Add ability for ABI UI to generate kubeconfig
  internal/bminventory/inventory.go
  internal/cluster/cluster.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7442 MGMT-20149: Add required sast tasks for Konflux
  .tekton/assisted-service-saas-hotfix-pull-request.yaml
  .tekton/assisted-service-saas-hotfix-push.yaml
  ci-images/Dockerfile.base
  ci-images/Dockerfile.subsystem
Labels: approved, size/L, lgtm, jira/valid-reference

#7460 NO-ISSUE: Update adding OLM operators doc
  docs/dev/olm-operator-plugins.md
Labels: approved, size/M, lgtm, jira/valid-reference

#7409 MGMT-20032: handle duplicates in CA bundle
  internal/common/common.go
  internal/common/common_test.go
  internal/controller/controllers/agentserviceconfig_controller.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7462 MGMT-20191: Enable installation of Kube Descheduler Operator
  api/vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  api/vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  client/vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  client/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  client/vendor/github.com/openshift/assisted-service/models/host_validation_id.go
  internal/cluster/validation_id.go
  internal/featuresupport/feature_support_level.go
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features_misc.go
  internal/featuresupport/features_olm_operators.go
  internal/host/validation_id.go
  internal/operators/builder.go
  internal/operators/kubedescheduler/kube_descheduler_consts.go
  internal/operators/kubedescheduler/kube_descheduler_manifests.go
  internal/operators/kubedescheduler/kube_descheduler_manifests_test.go
  internal/operators/kubedescheduler/kube_descheduler_operator.go
  internal/operators/kubedescheduler/kube_descheduler_requirements.go
  internal/operators/kubedescheduler/kube_descheduler_suite_test.go
  internal/operators/kubedescheduler/kube_descheduler_templates.go
  internal/operators/kubedescheduler/kube_descheduler_validations.go
  internal/operators/kubedescheduler/templates/custom/kube_descheduler.yaml
  internal/operators/kubedescheduler/templates/node_healthcheck_suite_test.go
  internal/operators/kubedescheduler/templates/openshift/50_kube_descheduler_namespace.yaml
  internal/operators/kubedescheduler/templates/openshift/50_kube_descheduler_operatorgroup.yaml
  internal/operators/kubedescheduler/templates/openshift/50_kube_descheduler_subscription.yaml
  internal/operators/manager_test.go
  models/cluster_validation_id.go
  models/feature_support_level_id.go
  models/host_validation_id.go
  restapi/embedded_spec.go
  subsystem/cluster_test.go
  subsystem/operators_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster_validation_id.go
  vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  vendor/github.com/openshift/assisted-service/models/host_validation_id.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#7458 NO-JIRA: OKD: Use /tmp as socket directory when calling pg_ctl and postgres
  hack/agent_installer/start_db.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#7455 MGMT-20216: Remove memory and CPU requirements
  internal/operators/nmstate/config.go
  internal/operators/nmstate/operator.go
  internal/operators/nmstate/operator_test.go
  subsystem/cluster_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7438 MGMT-18437: Consumer label on AgentClusterInstall to identify clusters used by CAPI providers
  api/hiveextension/v1beta1/agentclusterinstall_types.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  vendor/github.com/openshift/assisted-service/api/hiveextension/v1beta1/agentclusterinstall_types.go
Labels: approved, size/S, api-review, lgtm, jira/valid-reference

#7429 MGMT-20134: Disable OLM Catalog for CAPI CI tests
  deploy/operator/capi/deploy_capi_cluster.sh
Labels: approved, size/XS, lgtm, jira/valid-reference

#7477 [master] OCPBUGS-54378: Bump go-jwt to 4.5.2 to fix CVE-30204
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, size/XS, lgtm, jira/severity-important, jira/valid-bug, jira/valid-reference

#7479 [release-ocm-2.12] ACM-19195: Bump go-jwt to 4.5.2 to fix CVE-30204
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, size/XS, lgtm, jira/valid-reference

#7481 [release-ocm-2.10] ACM-19191: Bump go-jwt to 4.5.2 to fix CVE-30204
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, size/XS, lgtm, jira/valid-reference

#7482 [release-ocm-2.9] ACM-19192: Bump go-jwt to 4.5.2 to fix CVE-30204
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, size/XS, lgtm, jira/valid-reference

#7480 [release-ocm-2.11] ACM-19194: Bump go-jwt to 4.5.2 to fix CVE-30204
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, size/XS, lgtm, jira/valid-reference

#7478 [release-ocm-2.13] ACM-19193: CVE-30204 Bump go-jwt to 4.5.2 to fix CVE-30204
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, size/XS, lgtm, jira/valid-reference

#7451 MGMT-19970: Improve iSCSI host IP validation error handling
  internal/hardware/validator.go
  internal/hardware/validator_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#7484 [release-4.17] OCPBUGS-54402: Bump go-jwt to 4.5.2 to fix CVE-30204
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: approved, size/XS, cherry-pick-approved, lgtm, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#7471 NO-ISSUE: Update eviction/deletetion logging on failure
  internal/controller/controllers/bmh_agent_controller.go
Labels: approved, size/XS, lgtm, jira/valid-reference
