Repository openshift/assisted-service, pull requests merged in 2025-09, with the labels that each got.

#7972 NO-ISSUE: Add tekton pipeline for 2.45
  .tekton/assisted-service-saas-v2-45-pull-request.yaml
  .tekton/assisted-service-saas-v2-45-push.yaml
Labels: approved, lgtm, size/XXL, jira/valid-reference

#7966 MGMT-19854: Fix Agent deletion across namespaces and prevent duplicate host IDs
  internal/bminventory/inventory.go
  internal/bminventory/mock_installer_internal.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7978 MGMT-20830:Support for serving an OVE image (ISO) with an embedded custom ignition - enhancement doc
  docs/enhancements/disconnected-iso-ignition-generation.md
Labels: approved, size/L, lgtm, jira/valid-reference

#7992 MGMT-21701: Fix the nmstate example
  docs/hive-integration/crds/nmstate.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#7993 NO-ISSUE: [master] Bump OCP versions: 4.19, 4.20
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7999 [release-ocm-2.13] MGMT-21688: Order pre-nm-config after NM-wait-online to fix race on full ISO
  docs/hive-integration/crds/nmstate.yaml
  internal/ignition/templates/pre-network-manager-config-with-nmstatectl.service
Labels: approved, size/XS, lgtm, jira/valid-reference

#7989 NO-ISSUE: [release-ocm-2.14] Bump OCP versions: 4.19
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, jira/valid-reference

#8017 NO-ISSUE: pin gotestsum to v1.12.3
  Dockerfile.assisted-service-build
  ci-images/Dockerfile.base
Labels: approved, kind/dependency-change, size/XS, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#8018 NO-ISSUE: pin gotestsum to v1.12.3
  Dockerfile.assisted-service-build
  ci-images/Dockerfile.base
Labels: approved, kind/dependency-change, size/XS, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#8020 NO-ISSUE: pin gotestsum to v1.12.3
  Dockerfile.assisted-service-build
  ci-images/Dockerfile.base
Labels: approved, kind/dependency-change, size/XS, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#8019 NO-ISSUE: pin gotestsum to v1.12.3
  Dockerfile.assisted-service-build
  ci-images/Dockerfile.base
Labels: approved, kind/dependency-change, size/XS, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference, verified

#8023 NO-ISSUE: pin gotestsum to v1.12.3
  Dockerfile.assisted-service-build
  ci-images/Dockerfile.base
Labels: approved, kind/dependency-change, size/XS, lgtm, backport-risk-assessed, jira/valid-bug, jira/valid-reference

#8024 NO-ISSUE: pin gotestsum to v1.12.3
  Dockerfile.assisted-service-build
  ci-images/Dockerfile.base
Labels: approved, kind/dependency-change, size/XS, lgtm, jira/valid-reference

#8028 NO-ISSUE: [master] Bump OCP versions: 4.12, 4.20, 4.17
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7942 MGMT-21419: fix assisted ZTP day 2 workers jobs
  internal/host/hostutil/host_utils.go
  internal/host/hostutil/host_utils_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7995 MGMT-21704: add index on host infra env
  internal/migrations/20250115120000_add_hosts_by_infra_env_id_index.go
  internal/migrations/migrations.go
Labels: approved, size/S, lgtm, jira/valid-reference

#8039 KONFLUX-6210: fix and set name and cpe label for assisted-service-rhel8-acm-ds-2-14
  Dockerfile.assisted-service-rhel8-mce
Labels: approved, kind/dependency-change, size/XS, lgtm, jira/valid-reference

#8034 NO-ISSUE: Configure konflux pipelines for ACM 2.11
  .tekton/assisted-service-rhel8-acm-ds-2-11-pull-request.yaml
  .tekton/assisted-service-rhel8-acm-ds-2-11-push.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-11-pull-request.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-11-push.yaml
  Dockerfile.assisted-service-rhel8-mce
  Dockerfile.assisted-service-rhel9-mce
  rpm-prefetching/README.md
  rpm-prefetching/assisted-service-rhel8/rpms.in.yaml
  rpm-prefetching/assisted-service-rhel8/rpms.lock.yaml
  rpm-prefetching/assisted-service-rhel9/rpms.in.yaml
  rpm-prefetching/assisted-service-rhel9/rpms.lock.yaml
Labels: approved, kind/dependency-change, lgtm, size/XXL, jira/valid-reference

#8045 [release-ocm-2.13] MGMT-20651: Assisted Service panics if both installation_disk_id and installation-disk_path are empty
  internal/host/hostutil/host_utils.go
  internal/host/hostutil/host_utils_test.go
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#8047 NO-ISSUE: [master] Bump OCP versions: 4.16, 4.18
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#8048 NO-ISSUE: Update kustomize to v5.7.1
  Dockerfile.assisted-service-build
  ci-images/Dockerfile.code-generation
  ci-images/Dockerfile.subsystem
Labels: approved, kind/dependency-change, size/XS, lgtm, jira/valid-reference

#7954 MGMT-21268: cancel long cluster monitoring cycles
  README.md
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/host/config.go
  internal/host/monitor.go
  internal/host/refresh_status_preprocessor.go
  internal/host/validator.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_metrics_manager_api.go
  internal/operators/manager.go
  skipper.env
Labels: approved, size/XL, lgtm, jira/valid-reference

#8044 MGMT-21450: Allow OpenshiftAI installation on SNO cluster
  internal/featuresupport/features_misc.go
  internal/featuresupport/features_olm_operators.go
  internal/featuresupport/features_olm_operators_test.go
  internal/operators/openshiftai/openshift_ai_manifests.go
  internal/operators/openshiftai/openshift_ai_manifests_test.go
  internal/operators/openshiftai/openshift_ai_operator.go
  internal/operators/openshiftai/templates/files/setup.sh
Labels: approved, size/M, lgtm, jira/valid-reference

#7955 MGMT-20192: add possibility to disable image service
  api/v1beta1/agentserviceconfig_types.go
  api/v1beta1/infraenv_types.go
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/hypershiftagentserviceconfig_controller.go
  internal/controller/controllers/infraenv_controller.go
  internal/controller/controllers/infraenv_controller_test.go
  internal/host/hostcommands/download_boot_artifacts_cmd.go
  internal/host/hostcommands/instruction_manager_test.go
  internal/versions/api_test.go
  internal/versions/kube_api_versions_test.go
  internal/versions/osimages.go
  internal/versions/osimages_test.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/agentserviceconfig_types.go
  vendor/github.com/openshift/assisted-service/api/v1beta1/infraenv_types.go
Labels: approved, api-review, lgtm, size/XXL, jira/valid-reference

#8084 NO-ISSUE: [master] Bump OCP versions: 4.17, 4.19, 4.20, 4.15, 4.14
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference
