Repository openshift/assisted-service, pull requests merged in 2025-05, with the labels that each got.

#7621 MGMT-20527: Ensure no_proxy contains no duplicates in the install command
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#7619 OCPBUGS-54319: mirror changes to openshift-installer with oci-eval-user-data
  internal/ignition/templates/oci-eval-user-data.sh
Labels: approved, size/XS, lgtm, ok-to-test, jira/valid-bug, jira/valid-reference

#7629 NO-ISSUE: Update konflux references and apply migration
  .tekton/assisted-service-saas-hotfix-pull-request.yaml
  .tekton/assisted-service-saas-hotfix-push.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7631 MGMT-20468: Add arbiter to cluster's hyperthreading and disk encryption enums
  api/vendor/github.com/openshift/assisted-service/models/cluster.go
  api/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  api/vendor/github.com/openshift/assisted-service/models/disk_encryption.go
  api/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
  client/vendor/github.com/openshift/assisted-service/models/cluster.go
  client/vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  client/vendor/github.com/openshift/assisted-service/models/disk_encryption.go
  client/vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
  internal/hardware/validator.go
  internal/host/hostutil/host_utils.go
  internal/host/hostutil/host_utils_test.go
  internal/installcfg/builder/builder.go
  internal/installcfg/builder/builder_test.go
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
  models/cluster.go
  models/cluster_create_params.go
  models/disk_encryption.go
  models/v2_cluster_update_params.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/cluster.go
  vendor/github.com/openshift/assisted-service/models/cluster_create_params.go
  vendor/github.com/openshift/assisted-service/models/disk_encryption.go
  vendor/github.com/openshift/assisted-service/models/v2_cluster_update_params.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#7492 MGMT-20228: Enhancement to allow cancelling day-2 host's installation
  docs/enhancements/cancel-day-2-host-installation.md
Labels: approved, size/L, lgtm, jira/valid-reference

#7630 MGMT-20567: Enable skip MCO reboot for day2 hosts
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#7613 MGMT-14821: Remove multi-arch capability
  git
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/versions/api.go
  internal/versions/api_test.go
  pkg/ocm/utils.go
  subsystem/authz_test.go
  subsystem/utils_test/wiremock_stubs.go
  subsystem/versions_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7648 NO-ISSUE: [master] Bump OCP versions: 4.12, 4.17, 4.15, 4.18, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7614 MGMT-20473: Revert "MGMT-20384: Feature flag for AMD GPU supported OCP versions (#7572)"
  internal/featuresupport/feature_support_config.go
  internal/featuresupport/features_olm_operators.go
  internal/featuresupport/features_olm_operators_test.go
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#7633 MGMT-20366: fix ironic inspection bug when ironic image override annotation is provided in disconnected environments
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7445 MGMT-19297: Error when querying /events endpoint with ?host_ids=uuid1…
  internal/events/event.go
  internal/events/event_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#7657 NO-ISSUE: [master] Bump OCP versions: 4.18
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7628 MGMT-20506: Reset preprovisioningimage status after cooldown period
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7651 MGMT-20378: Disable skip MCO reboot for s390x
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features_misc.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#7627 MGMT-20465: Limit TNA Clusters to baremetal platform.
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  client/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/featuresupport/feature_support_level.go
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features_misc.go
  internal/featuresupport/features_platforms.go
  models/feature_support_level_id.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
Labels: approved, size/L, api-review, lgtm, ok-to-test, jira/valid-reference

#7656 MGMT-20601: Update pull secret validation
  go.mod
  go.sum
  internal/cluster/validations/pull_secret_validation.go
  internal/cluster/validations/validation_test.go
  internal/cluster/validations/validations.go
  internal/common/common.go
  vendor/github.com/distribution/reference/README.md
  vendor/github.com/distribution/reference/normalize.go
  vendor/github.com/distribution/reference/reference.go
  vendor/github.com/docker/distribution/LICENSE
  vendor/github.com/docker/distribution/digestset/set.go
  vendor/github.com/docker/distribution/reference/helpers.go
  vendor/github.com/docker/distribution/reference/normalize.go
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/docker/distribution/reference/regexp.go
  vendor/modules.txt
Labels: approved, size/L, lgtm, jira/valid-reference

#7663 NO-ISSUE: [master] Bump OCP versions: 4.19, 4.16, 4.17
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7667 NO-ISSUE: Allow setting TNA_CLUSTERS_SUPPORT in the template
  openshift/template.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#7672 NO-ISSUE: [master] Bump OCP versions: 4.13, 4.19
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7665 MGMT-20610: Generate manifests for arbiter hosts for chrony and nic reapply
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7676 MGMT-20366: ironic inspection fails with Networking Connection error
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7677 MGMT-20366: ironic inspection fails with Networking Connection error
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7664 MGMT-20378: Change skip MCO Reboot usage condition
  api/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  client/vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
  internal/common/common.go
  internal/featuresupport/feature_support_level.go
  internal/featuresupport/feature_support_test.go
  internal/featuresupport/features_misc.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostcommands/instruction_manager_test.go
  models/feature_support_level_id.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/feature_support_level_id.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#7662 MGMT-20331: Don't use the detached annotation with the converged flow
  internal/controller/controllers/bmh_agent_controller.go
  internal/controller/controllers/bmh_agent_controller_test.go
  internal/controller/controllers/preprovisioningimage_controller.go
  internal/controller/controllers/preprovisioningimage_controller_test.go
Labels: approved, size/L, lgtm, ok-to-test, jira/valid-reference

#7680 NO-ISSUE: [master] Bump OCP versions: 4.18
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7682 NO-ISSUE: [master] Bump OCP versions: 4.15, 4.14, 4.17, 4.19
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7668 NO-ISSUE: Change NHO, SNR, FAR, Kube Descheduler and Node Maintenance operators support level to 'tech-preview'
  internal/featuresupport/features_olm_operators.go
Labels: approved, size/S, lgtm, jira/valid-reference

#7693 NO-ISSUE: [master] Bump OCP versions: 4.17, 4.16
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7659 MGMT-20466: Add hardware requirements for arbiter hosts
  api/vendor/github.com/openshift/assisted-service/models/versioned_host_requirements.go
  client/vendor/github.com/openshift/assisted-service/models/versioned_host_requirements.go
  data/default_hw_requirements.json
  deploy/podman/configmap.yml
  deploy/podman/okd-configmap.yml
  internal/controller/controllers/default_controller_hw_requirements.json
  internal/hardware/validator.go
  internal/hardware/validator_test.go
  internal/hardware/versioned-requirements.go
  internal/hardware/versioned-requirements_test.go
  internal/host/transition_test.go
  internal/operators/amdgpu/amd_gpu_operator.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/lvm/lvm_operator.go
  internal/operators/mce/mce_operator.go
  internal/operators/mtv/operator.go
  internal/operators/nvidiagpu/nvidia_gpu_operator.go
  internal/operators/odf/common.go
  internal/operators/odf/odf_operator_test.go
  internal/operators/odf/validation_test.go
  internal/operators/osc/operator.go
  models/versioned_host_requirements.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/versioned_host_requirements.go
Labels: approved, size/XL, api-review, lgtm, jira/valid-reference
