Repository openshift/assisted-service, pull requests merged in 2025-04, with the labels that each got.

#7412 NO-ISSUE: [release-ocm-2.12] Bump OCP versions: 4.15, 4.12, 4.17, 4.18
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7413 NO-ISSUE: [release-ocm-2.11] Bump OCP versions: 4.15, 4.16, 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7414 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.15, 4.12
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7493 NO-ISSUE: [master] Bump OCP versions: 4.19
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7491 NO-ISSUE: Change node-maintenance operator namespace to avoid conflict with node-healthcheck operator
  internal/operators/nodemaintenance/node_maintenance_consts.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#7490 MGMT-20153: Improve ostree cleanup service
  internal/ignition/installmanifests.go
  internal/ignition/installmanifests_test.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#7467 [release-ocm-2.11] ACM-19143: align default osImages for 2.11 with supported-ocp-versions
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  docs/hive-integration/crds/agentClusterInstall-with-installconfig-overrides.yaml
  docs/hive-integration/crds/agentClusterInstall.yaml
  openshift/template.yaml
  subsystem/cluster_test.go
  subsystem/cluster_v2_test.go
  subsystem/feature_support_levels_test.go
  subsystem/kubeapi_test.go
  subsystem/operators_test.go
  subsystem/subsystem_suite_test.go
Labels: approved, size/XL, lgtm, jira/valid-reference

#7494 [cloud_hotfix_releases] NO-ISSUE: Prepare v2.39.1 hotfix
  .tekton/assisted-service-rhel8-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-service-rhel8-acm-ds-2-14-push.yaml
  .tekton/assisted-service-rhel8-acm-ds-main-pull-request.yaml
  .tekton/assisted-service-rhel8-acm-ds-main-push.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-14-push.yaml
  .tekton/assisted-service-rhel9-acm-ds-main-pull-request.yaml
  .tekton/assisted-service-saas-hotfix-pull-request.yaml
  .tekton/assisted-service-saas-hotfix-push.yaml
  .tekton/assisted-service-saas-main-push.yaml
  internal/operators/nodemaintenance/node_maintenance_consts.go
Labels: approved, lgtm, size/XXL, jira/valid-reference

#7466 ACM-19143: align default osImages for 2.10 with supported-ocp-versions
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  docs/hive-integration/crds/agentClusterInstall-with-installconfig-overrides.yaml
  docs/hive-integration/crds/agentClusterInstall.yaml
  docs/hive-integration/crds/clusterImageSet.yaml
  internal/versions/api_test.go
  openshift/template.yaml
  subsystem/cluster_test.go
  subsystem/cluster_v2_test.go
  subsystem/feature_support_levels_test.go
  subsystem/kubeapi_test.go
  subsystem/operators_test.go
  subsystem/subsystem_suite_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7464 MGMT-20181: cleanup platform_oci and platform_external capabilities
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/validations/validations.go
  pkg/ocm/utils.go
Labels: approved, size/M, lgtm, ok-to-test, jira/valid-reference

#7499 OCPBUGS-53691: Bump jwt to 4.5.2 in release-4.14
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/github.com/golang-jwt/jwt/v4/token.go
  vendor/modules.txt
Labels: approved, size/XS, cherry-pick-approved, lgtm, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#7506 MGMT-20009: Change OCP 4.19 to the default version
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7472 AGENT-538: For ABI, also allow early retrieval of kubeadmin-password
  internal/bminventory/inventory.go
  internal/cluster/cluster.go
  internal/common/error_utils.go
  internal/constants/files.go
  pkg/generator/generator.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7448 MGMT-20207: avoid adding system CA bundle to AdditionalTrustBundle
  internal/common/common.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/common.go
  pkg/mirrorregistries/generator.go
  pkg/mirrorregistries/mirror_registry_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7507 MGMT-20302: Remove root=/dev/disk/by-label/dm-mpath-root from kargs added when installation disk is multipath iSCSI
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/S, lgtm, ok-to-test, jira/valid-reference

#7508 MGMT-20245: Add kernel args for raid (Intel VROC)
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/M, lgtm, ok-to-test, jira/valid-reference

#7519 [cloud-hotfix-releases] MGMT-20302: Prepare v2.39.2
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#7520 [release-ocm-2.12] MGMT-20207: avoid adding system CA bundle to AdditionalTrustBundle
  internal/common/common.go
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
  internal/controller/controllers/common.go
  pkg/mirrorregistries/generator.go
  pkg/mirrorregistries/generator_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7396 [release-ocm-2.13] NO-ISSUE: No-op to push to ACM
  README.md
Labels: approved, size/XS, lgtm, jira/valid-reference

#7512 [release-4.13] OCPBUGS-53693: Bump go-jwt to 4.5.2 to fixCVE-30204
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/github.com/golang-jwt/jwt/v4/token.go
  vendor/modules.txt
Labels: approved, size/XS, cherry-pick-approved, lgtm, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#7529 NO-ISSUE: [master] Bump OCP versions: 4.17, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7527 MGMT-20324: Fix day2 add hosts with P/Z CPU architectures
  internal/featuresupport/common.go
  internal/featuresupport/feature_support_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7533 NO-ISSUE: Update tekton pipeline
  .tekton/assisted-service-saas-hotfix-pull-request.yaml
  .tekton/assisted-service-saas-hotfix-push.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#7531 [cloud_hotfix_releases] NO-ISSUE: Prepare version v2.38.3
  internal/featuresupport/common.go
  internal/featuresupport/feature_support_test.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7461 MGMT-18518: Renovate configuration tu update golang and golangci-lint
  renovate.json
Labels: approved, size/M, lgtm, jira/valid-reference

#7543 MGMT-20339: Disable skip mco reboot for day2 hosts
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7569 NO-ISSUE: Rollback renovate config
  renovate.json
Labels: approved, size/M, lgtm, jira/valid-reference

#7573 NO-ISSUE: ci: Use virtualenv to avoid conflict with setuptools
  ci-images/Dockerfile.base
  ci-images/Dockerfile.subsystem
Labels: approved, size/XS, lgtm, jira/valid-reference

#7535 NO-ISSUE: Truncate statusInfo if it's too long
  internal/host/hostutil/host_utils.go
  internal/host/hostutil/update_host.go
  internal/host/transition.go
Labels: approved, size/S, lgtm, jira/valid-reference

#7570 NO-ISSUE: Revert "NO-ISSUE: Update quay.io/openshift/origin-cli Docke…
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, size/XS, lgtm, jira/valid-reference

#7522 NO-ISSUE: Remove root=/dev/disk/by-label/dm-mpath-root from kargs added when installation disk is multipath
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
Labels: approved, size/S, lgtm, ok-to-test, jira/valid-reference

#7572 MGMT-20384: Feature flag for AMD GPU supported OCP versions
  internal/featuresupport/feature_support_config.go
  internal/featuresupport/features_olm_operators.go
  internal/featuresupport/features_olm_operators_test.go
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#7498 MGMT-19968: Fix duplicate error messages in disk eligibility validation
  internal/hardware/validator.go
  internal/hardware/validator_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7546 MGMT-20375: Skip installconfig generation only for agent-based installer
  pkg/generator/generator.go
Labels: approved, size/XS, lgtm, ok-to-test, jira/valid-reference

#7589 NO-ISSUE: [master] Bump OCP versions: 4.13, 4.18, 4.17, 4.12, 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7590 [cloud_hotfix_releases] Prepare v2.39.3
  internal/featuresupport/feature_support_config.go
  internal/featuresupport/features_olm_operators.go
  internal/featuresupport/features_olm_operators_test.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  openshift/template.yaml
Labels: approved, size/L, lgtm

#7593 MGMT-20322: Add AI operators environment requirements for testing
  Makefile
  deploy/assisted-service-configmap.yaml
  tools/deploy_assisted_installer_configmap.py
Labels: approved, size/XS, lgtm, jira/valid-reference

#7591 MGMT-20413: support missing ca-bundle.crt in mirror registry ConfigMap
  internal/controller/controllers/agentserviceconfig_controller.go
  internal/controller/controllers/agentserviceconfig_controller_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7468 ACM-19143: align default osImages for 2.12 with supported-ocp-versions
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
  subsystem/cluster_test.go
  subsystem/cluster_v2_test.go
  subsystem/feature_support_levels_test.go
  subsystem/host_test.go
  subsystem/infra_env_test.go
  subsystem/metrics_test.go
  subsystem/operators_test.go
  subsystem/subsystem_suite_test.go
  subsystem/utils_test.go
Labels: approved, size/XL, lgtm, ok-to-test, jira/valid-reference

#7402 MGMT-19980: TNA clusters
  docs/enhancements/arbiter-clusters.md
Labels: approved, size/L, lgtm, jira/valid-reference

#7601 NO-ISSUE: [master] Bump OCP versions: 4.18
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7495 NO-ISSUE: Small fix updating agent annotation
  internal/controller/controllers/agent_controller.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#7596 MGMT-20455: Add NFD as dependency of NVIDIA GPU
  internal/operators/nvidiagpu/nvidia_gpu_operator.go
  internal/operators/nvidiagpu/nvidia_gpu_operator_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#7505 OCPBUGS-52285: ABI vSphere Installation Fails Due to disk.EnableUUID
  internal/host/validations_test.go
  internal/host/validator.go
Labels: approved, size/S, lgtm, jira/valid-bug, jira/severity-critical, jira/valid-reference

#7513 [release-4.12] OCPBUGS-53692: Bump go-jwt to 4.5.2 to fix-CVE-30204
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/README.md
  vendor/github.com/golang-jwt/jwt/v4/claims.go
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/github.com/golang-jwt/jwt/v4/token.go
  vendor/modules.txt
Labels: approved, size/XS, cherry-pick-approved, lgtm, backport-risk-assessed, jira/severity-important, jira/valid-bug, jira/valid-reference

#7605 OCPBUGS-51230:Revert go-jose from v4.0.5 to v0.3.04
  go.mod
  go.sum
  pkg/auth/auth_handler_test_utils.go
  vendor/github.com/go-jose/go-jose/v3/.gitignore
  vendor/github.com/go-jose/go-jose/v3/.golangci.yml
  vendor/github.com/go-jose/go-jose/v3/.travis.yml
  vendor/github.com/go-jose/go-jose/v3/CHANGELOG.md
  vendor/github.com/go-jose/go-jose/v3/CONTRIBUTING.md
  vendor/github.com/go-jose/go-jose/v3/LICENSE
  vendor/github.com/go-jose/go-jose/v3/README.md
  vendor/github.com/go-jose/go-jose/v3/SECURITY.md
  vendor/github.com/go-jose/go-jose/v3/asymmetric.go
  vendor/github.com/go-jose/go-jose/v3/cipher/cbc_hmac.go
  vendor/github.com/go-jose/go-jose/v3/cipher/concat_kdf.go
  vendor/github.com/go-jose/go-jose/v3/cipher/ecdh_es.go
  vendor/github.com/go-jose/go-jose/v3/cipher/key_wrap.go
  vendor/github.com/go-jose/go-jose/v3/crypter.go
  vendor/github.com/go-jose/go-jose/v3/doc.go
  vendor/github.com/go-jose/go-jose/v3/encoding.go
  vendor/github.com/go-jose/go-jose/v3/json/LICENSE
  vendor/github.com/go-jose/go-jose/v3/json/README.md
  vendor/github.com/go-jose/go-jose/v3/json/decode.go
  vendor/github.com/go-jose/go-jose/v3/json/encode.go
  vendor/github.com/go-jose/go-jose/v3/json/indent.go
  vendor/github.com/go-jose/go-jose/v3/json/scanner.go
  vendor/github.com/go-jose/go-jose/v3/json/stream.go
  vendor/github.com/go-jose/go-jose/v3/json/tags.go
  vendor/github.com/go-jose/go-jose/v3/jwe.go
  vendor/github.com/go-jose/go-jose/v3/jwk.go
  vendor/github.com/go-jose/go-jose/v3/jws.go
  vendor/github.com/go-jose/go-jose/v3/opaque.go
  vendor/github.com/go-jose/go-jose/v3/shared.go
  vendor/github.com/go-jose/go-jose/v3/signing.go
  vendor/github.com/go-jose/go-jose/v3/symmetric.go
  vendor/modules.txt
Labels: approved, size/S, cherry-pick-approved, lgtm, backport-risk-assessed, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7592 MGMT-18930: Consolidate static network configuration log messages
  pkg/staticnetworkconfig/generator.go
  pkg/staticnetworkconfig/generator_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7525 MGMT-20124: Introduce DependencyOnly property on Operator
  api/vendor/github.com/openshift/assisted-service/models/monitored_operator.go
  client/vendor/github.com/openshift/assisted-service/models/monitored_operator.go
  models/monitored_operator.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/monitored_operator.go
Labels: approved, size/XS, api-review, lgtm, jira/valid-reference

#7524 MGMT-20233: Recompute operator dependencies after discovering the hosts
  cmd/main.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/cluster/progress_test.go
  internal/cluster/refresh_status_preprocessor.go
  internal/cluster/refresh_status_preprocessor_test.go
  internal/cluster/transition_test.go
  internal/operators/common/common.go
  internal/operators/manager.go
  internal/operators/odf/validation_test.go
  vendor/github.com/dustin/go-humanize/english/words.go
  vendor/modules.txt
Labels: approved, size/XL, lgtm, jira/valid-reference

#7604 MGMT-20296: Fix returned error code in PostRegisterAfterInstallation
  internal/bminventory/inventory.go
  internal/host/transition.go
  internal/host/transition_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#7612 NO-ISSUE: [master] Bump OCP versions: 4.17, 4.19, 4.16
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7534 MGMT-20369: retrieve stream-coreos image instead of rhel-coreos when installing OKD
  internal/oc/release.go
  internal/oc/release_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7606 OCPBUGS-55300: For agent-installer remove bypass of manifest generation
  pkg/generator/generator.go
Labels: approved, size/XS, lgtm, jira/valid-bug, jira/valid-reference

#7469 ACM-19143: align default osImages for 2.13 with supported-ocp-versions
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  docs/hive-integration/crds/agentClusterInstall-with-installconfig-overrides.yaml
  docs/hive-integration/crds/agentClusterInstall.yaml
  docs/hive-integration/crds/clusterImageSet.yaml
  openshift/template.yaml
  subsystem/agent_based_installer_client_test.go
  subsystem/cluster_test.go
  subsystem/cluster_v2_test.go
  subsystem/feature_support_levels_test.go
  subsystem/host_test.go
  subsystem/infra_env_test.go
  subsystem/kubeapi/kubeapi_suite_test.go
  subsystem/metrics_test.go
  subsystem/operators_test.go
  subsystem/subsystem_suite_test.go
  subsystem/utils_test/subsystem_test_context.go
Labels: approved, size/XL, lgtm, jira/valid-reference

#7523 MGMT-20119: Create feature gate to allow installing TNA using the API
  api/vendor/github.com/openshift/assisted-service/models/host_role.go
  api/vendor/github.com/openshift/assisted-service/models/host_role_update_params.go
  api/vendor/github.com/openshift/assisted-service/models/host_update_params.go
  client/vendor/github.com/openshift/assisted-service/models/host_role.go
  client/vendor/github.com/openshift/assisted-service/models/host_role_update_params.go
  client/vendor/github.com/openshift/assisted-service/models/host_update_params.go
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/cluster/cluster.go
  internal/cluster/common.go
  internal/cluster/transition.go
  internal/cluster/transition_test.go
  internal/cluster/validator.go
  internal/cluster/validator_test.go
  internal/common/common.go
  internal/common/common_test.go
  internal/host/common.go
  internal/host/conditions.go
  internal/host/hostutil/host_utils.go
  internal/host/transition.go
  internal/host/validator.go
  internal/ignition/installmanifests.go
  internal/ignition/installmanifests_test.go
  internal/installcfg/builder/builder.go
  internal/installcfg/builder/builder_test.go
  internal/installcfg/installcfg.go
  internal/operators/odf/common.go
  internal/provider/baremetal/installConfig.go
  internal/provider/platform.go
  models/host_role.go
  models/host_role_update_params.go
  models/host_update_params.go
  pkg/k8sclient/k8s_utils.go
  restapi/embedded_spec.go
  restapi/operations/installer/list_cluster_hosts_parameters.go
  restapi/operations/installer/v2_download_cluster_files_parameters.go
  subsystem/cluster_test.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/host_role.go
  vendor/github.com/openshift/assisted-service/models/host_role_update_params.go
  vendor/github.com/openshift/assisted-service/models/host_update_params.go
Labels: approved, api-review, lgtm, size/XXL, jira/valid-reference

#7598 NO-ISSUE: Apply konflux migration
  .tekton/assisted-service-saas-hotfix-pull-request.yaml
  .tekton/assisted-service-saas-hotfix-push.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7600 NO-ISSUE: Apply konflux migration
  .tekton/assisted-service-rhel8-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-service-rhel8-acm-ds-2-14-push.yaml
  .tekton/assisted-service-rhel8-acm-ds-main-pull-request.yaml
  .tekton/assisted-service-rhel8-acm-ds-main-push.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-14-push.yaml
  .tekton/assisted-service-rhel9-acm-ds-main-pull-request.yaml
  .tekton/assisted-service-rhel9-acm-ds-main-push.yaml
  .tekton/assisted-service-saas-main-pull-request.yaml
  .tekton/assisted-service-saas-main-push.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7599 NO-ISSUE: Apply konflux migration
  .tekton/assisted-service-rhel8-acm-ds-2-13-pull-request.yaml
  .tekton/assisted-service-rhel8-acm-ds-2-13-push.yaml
  .tekton/assisted-service-rhel8-acm-ds-main-pull-request.yaml
  .tekton/assisted-service-rhel8-acm-ds-main-push.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-13-pull-request.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-13-push.yaml
  .tekton/assisted-service-rhel9-acm-ds-main-pull-request.yaml
  .tekton/assisted-service-rhel9-acm-ds-main-push.yaml
  .tekton/assisted-service-saas-main-pull-request.yaml
  .tekton/assisted-service-saas-main-push.yaml
Labels: approved, lgtm, size/XXL, jira/valid-reference
