Repository openshift/assisted-service, pull requests merged in 2025-02, with the labels that each got.

#7247 OCPBUGS-47627: dnsmasq service on OCP SNO fails to read /etc/resolv.conf file during system startup
  internal/network/manifests_generator.go
Labels: approved, size/XS, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7213 MGMT-19599: Update get bundles endpoint to return a list of bundles instead of list of bundles names
  client/operators/v2_list_bundles_responses.go
  docs/enhancements/operator-marketplace.md
  internal/operators/manager.go
  internal/operators/manager_test.go
  internal/operators/mock_operators_api.go
  restapi/embedded_spec.go
  restapi/operations/operators/v2_list_bundles_responses.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/client/operators/v2_list_bundles_responses.go
Labels: approved, size/M, api-review, lgtm, jira/valid-reference

#7258 MGMT-19193: Add current stage when restoring host by Agent (#7026)
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7192 MGMT-19670, MGMT-19484: Enable multipath + iSCSI as installation disk
  internal/hardware/validator.go
  internal/hardware/validator_test.go
  internal/host/hostcommands/install_cmd.go
  internal/host/hostcommands/install_cmd_test.go
  internal/host/hostutil/host_utils.go
  internal/host/hostutil/host_utils_test.go
  internal/host/validations_test.go
  internal/host/validator.go
  internal/network/manifests_generator.go
  internal/network/manifests_generator_test.go
Labels: approved, size/XL, lgtm, jira/valid-reference

#7246 MGMT-19490: Day 2 clusters /install-config endpoint is broken
  internal/bminventory/inventory_test.go
  internal/bminventory/inventory_v2_handlers.go
Labels: approved, size/S, lgtm, jira/valid-reference

#7264 [ACM 2.12] MGMT-19855: validate internal ignition
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/ignition/ignition.go
Labels: approved, size/S, lgtm, jira/valid-reference

#7265 [ACM 2.11] MGMT-19856: MGMT-19844: Validate the internal ignition override (#7254)
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/ignition/ignition.go
Labels: approved, size/S, lgtm, jira/valid-reference

#7253 MGMT-14495: Stop removing the finalizers from BMH
  internal/controller/controllers/agent_controller.go
Labels: approved, size/XS, lgtm, jira/valid-reference

#7250 ACM-17553: Save version of imported clusters - ACM 2.12
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/day2_cluster_test.go
Labels: approved, size/S, lgtm, jira/valid-reference

#7248 AGENT-1074: Add support for ABI to install OLM operators
  cmd/agentbasedinstaller/client/main.go
  cmd/agentbasedinstaller/register.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/agent_based_installer_client_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7269 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7268 NO-ISSUE: [release-ocm-2.11] Bump OCP versions: 4.16, 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7249 OCPBUGS-42059: Save version of imported clusters
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/day2_cluster_test.go
Labels: approved, size/S, lgtm, jira/valid-bug, jira/valid-reference

#7259 MGMT-19847: Add Documentation for Mirror Registry Feature
  docs/user-guide/mirror_registry_guide.md
Labels: approved, size/L, lgtm, jira/valid-reference

#7267 NO-ISSUE: [release-ocm-2.12] Bump OCP versions: 4.16, 4.17, 4.15
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7260 MGMT-19420: Adding the control-plane-count reference to install-cmd
  api/vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
  client/vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
  models/install_cmd_request.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/install_cmd_request.go
Labels: approved, size/XS, api-review, lgtm, jira/valid-reference

#7252 ACM-17555: Save version of imported clusters - ACM 2.10
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/controller/controllers/clusterdeployments_controller.go
  internal/controller/controllers/clusterdeployments_controller_test.go
  subsystem/day2_cluster_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7277 [release-ocm-2.11] MGMT-19193: Add current stage when restoring host by Agent
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7273 MGMT-19860: Add descriptions to operator bundles
  api/vendor/github.com/openshift/assisted-service/models/bundle.go
  client/vendor/github.com/openshift/assisted-service/models/bundle.go
  internal/operators/authorino/authorino_operator.go
  internal/operators/common/common.go
  internal/operators/manager.go
  internal/operators/manager_test.go
  internal/operators/nvidiagpu/nvidia_gpu_operator.go
  internal/operators/odf/odf_operator.go
  internal/operators/openshiftai/openshift_ai_operator.go
  internal/operators/pipelines/pipelines_operator.go
  internal/operators/serverless/serverless_operator.go
  internal/operators/servicemesh/servicemesh_operator.go
  models/bundle.go
  restapi/embedded_spec.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/models/bundle.go
Labels: approved, size/M, api-review, lgtm, jira/valid-reference

#7266 [ACM 2.10] MGMT-19857: Validate the internal ignition override (#7254)
  internal/bminventory/inventory.go
  internal/bminventory/inventory_test.go
  internal/ignition/ignition.go
Labels: approved, size/S, lgtm, jira/valid-reference

#7274 MGMT-19860: Remove dependencies from OpenShift AI operator
  internal/operators/openshiftai/openshift_ai_config.go
  internal/operators/openshiftai/openshift_ai_operator.go
  internal/operators/openshiftai/openshift_ai_operator_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7282 MGMT-19847: Move version matching comment to Mirror OpenShift Release Images section
  docs/user-guide/mirror_registry_guide.md
Labels: approved, size/XS, lgtm, jira/valid-reference

#7278 MGMT-19860: Add ID and title to operator bundles
  api/vendor/github.com/openshift/assisted-service/models/bundle.go
  api/vendor/github.com/openshift/assisted-service/models/monitored_operator.go
  client/operators/operators_client.go
  client/operators/v2_get_bundle_parameters.go
  client/operators/v2_get_bundle_responses.go
  client/vendor/github.com/openshift/assisted-service/models/bundle.go
  client/vendor/github.com/openshift/assisted-service/models/monitored_operator.go
  internal/operators/authorino/authorino_operator.go
  internal/operators/cnv/cnv_operator.go
  internal/operators/common/bundles.go
  internal/operators/common/common.go
  internal/operators/handler/handler_v2.go
  internal/operators/manager.go
  internal/operators/manager_test.go
  internal/operators/mtv/operator.go
  internal/operators/nmstate/operator.go
  internal/operators/nvidiagpu/nvidia_gpu_operator.go
  internal/operators/odf/odf_operator.go
  internal/operators/openshiftai/openshift_ai_operator.go
  internal/operators/pipelines/pipelines_operator.go
  internal/operators/serverless/serverless_operator.go
  internal/operators/servicemesh/servicemesh_operator.go
  models/bundle.go
  models/monitored_operator.go
  restapi/embedded_spec.go
  restapi/operations/assisted_install_api.go
  restapi/operations/operators/v2_get_bundle.go
  restapi/operations/operators/v2_get_bundle_parameters.go
  restapi/operations/operators/v2_get_bundle_urlbuilder.go
  swagger.yaml
  vendor/github.com/openshift/assisted-service/client/operators/operators_client.go
  vendor/github.com/openshift/assisted-service/client/operators/v2_get_bundle_parameters.go
  vendor/github.com/openshift/assisted-service/client/operators/v2_get_bundle_responses.go
  vendor/github.com/openshift/assisted-service/models/bundle.go
  vendor/github.com/openshift/assisted-service/models/monitored_operator.go
Labels: approved, size/L, api-review, lgtm, jira/valid-reference

#7276 [release-ocm-2.12] MGMT-19413: Add validations info to the Agents annotations
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7296 NO-ISSUE: [master] Bump OCP versions: 4.18, 4.14, 4.12, 4.17
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7297 NO-ISSUE: [release-ocm-2.12] Bump OCP versions: 4.18, 4.16, 4.12, 4.17, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7298 NO-ISSUE: [master] Bump OCP versions: 4.16
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7300 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.12, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7301 NO-ISSUE: [release-ocm-2.9] Bump OCP versions: 4.12, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7299 NO-ISSUE: [release-ocm-2.11] Bump OCP versions: 4.12, 4.14, 4.16
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7303 ACM-17767: Don't remove spoke resources when cluster is being deleted
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7283 MGMT-19106: Remove discovery stateroot when installing to existing root
  internal/ignition/installmanifests.go
  internal/ignition/installmanifests_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7306 NO-ISSUE: [master] Bump OCP versions: 4.12, 4.18, 4.17, 4.15, 4.16
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7305 MGMT-19844: Validate that no_proxy does not contain duplicate entries
  pkg/validations/validations.go
  pkg/validations/validations_test.go
Labels: approved, size/M, lgtm, jira/valid-reference

#7309 [ACM 2.12] ACM-17877: Don't remove spoke resources when cluster is being deleted
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7317 [release-ocm-2.13] MGMT-19947: Update Manifests In ocm-2.13
  Makefile
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/manifests/bases/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/olm-catalog/metadata/annotations.yaml
  deploy/operator/setup_assisted_operator.sh
Labels: approved, size/M, lgtm, jira/valid-reference

#7318 MGMT-19950: Modify Konflux YAMLs to ocm-2.14
  .tekton/assisted-service-rhel8-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-service-rhel8-acm-ds-2-14-push.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-14-pull-request.yaml
  .tekton/assisted-service-rhel9-acm-ds-2-14-push.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7316 MGMT-19952: Update operator bundle channel to ocm-2.14
  Makefile
  deploy/olm-catalog/bundle.Dockerfile
  deploy/olm-catalog/metadata/annotations.yaml
Labels: approved, size/XS, lgtm, jira/valid-reference

#7320 [release-ocm-2.13] MGMT-19953: Reduce the OWNERS list for release-ocm-2.13 as it is feature complete
  OWNERS_ALIASES
Labels: approved, size/S, lgtm, jira/valid-reference

#7324 [release-ocm-2.11] ACM-17953: Don't remove spoke resources when cluster is being deleted
  internal/controller/controllers/agent_controller.go
  internal/controller/controllers/agent_controller_test.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7328 NO-ISSUE: [release-ocm-2.12] Bump OCP versions: 4.18, 4.17, 4.12, 4.13, 4.15, 4.16
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7327 NO-ISSUE: [release-ocm-2.13] Bump OCP versions: 4.18, 4.17, 4.12, 4.13, 4.19, 4.15, 4.16
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7329 NO-ISSUE: [release-ocm-2.11] Bump OCP versions: 4.15, 4.12, 4.16, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7310 MGMT-19928: Add dev doc for disk image install
  docs/dev/disk-image-install.md
Labels: approved, size/S, lgtm, jira/valid-reference

#7308 MGMT-19583: Remove references to kube-rbac-proxy that was deprecated
  config/default/kustomization.yaml
  config/default/manager_auth_proxy_patch.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7326 NO-ISSUE: [master] Bump OCP versions: 4.18, 4.19
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7331 NO-ISSUE: [master] Bump OCP versions: 4.17
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7332 [release-ocm-2.12] MGMT-19819: Add the commit reference from which the image is built to the image
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, size/XS, lgtm, jira/valid-reference

#7335 [release-ocm-2.9] MGMT-19819: Add the commit reference from which the image is built to the image
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, size/XS, lgtm, jira/valid-reference

#7334 [release-ocm-2.10] MGMT-19819: Add the commit reference from which the image is built to the image
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, size/XS, lgtm, jira/valid-reference

#7333 [release-ocm-2.11] MGMT-19819: Add the commit reference from which the image is built to the image
  Dockerfile.assisted-service
Labels: approved, kind/dependency-change, size/XS, lgtm, jira/valid-reference

#7330 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.15, 4.12, 4.13
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7336 NO-ISSUE: [master] Bump OCP versions: 4.16, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7307 MGMT-19887: Add Histogram Metric for Host Monitoring Time
  internal/cluster/cluster.go
  internal/cluster/cluster_test.go
  internal/host/monitor.go
  internal/host/monitor_test.go
  internal/metrics/metricsManager.go
  internal/metrics/mock_metrics_manager_api.go
Labels: approved, size/L, lgtm, jira/valid-reference

#7294 [release-ocm-2.11] ACM-16099: Bump moby/moby version to close CVE-2024-36620
  api/go.mod
  api/go.sum
  api/vendor/golang.org/x/net/LICENSE
  api/vendor/golang.org/x/net/http/httpguts/httplex.go
  api/vendor/golang.org/x/net/http2/client_conn_pool.go
  api/vendor/golang.org/x/net/http2/config.go
  api/vendor/golang.org/x/net/http2/config_go124.go
  api/vendor/golang.org/x/net/http2/config_pre_go124.go
  api/vendor/golang.org/x/net/http2/frame.go
  api/vendor/golang.org/x/net/http2/http2.go
  api/vendor/golang.org/x/net/http2/server.go
  api/vendor/golang.org/x/net/http2/testsync.go
  api/vendor/golang.org/x/net/http2/timer.go
  api/vendor/golang.org/x/net/http2/transport.go
  api/vendor/golang.org/x/net/http2/unencrypted.go
  api/vendor/golang.org/x/net/http2/write.go
  api/vendor/golang.org/x/net/http2/writesched_priority.go
  api/vendor/golang.org/x/text/LICENSE
  api/vendor/modules.txt
  go.mod
  go.sum
  vendor/github.com/docker/distribution/reference/reference.go
  vendor/github.com/docker/docker/api/swagger.yaml
  vendor/github.com/docker/docker/api/types/types.go
  vendor/github.com/docker/docker/client/client.go
  vendor/github.com/docker/docker/client/container_create.go
  vendor/github.com/docker/docker/client/container_exec.go
  vendor/github.com/docker/docker/client/container_restart.go
  vendor/github.com/docker/docker/client/container_stop.go
  vendor/github.com/docker/docker/client/container_wait.go
  vendor/github.com/docker/docker/client/errors.go
  vendor/github.com/docker/docker/client/image_list.go
  vendor/github.com/docker/docker/client/network_create.go
  vendor/github.com/docker/docker/client/ping.go
  vendor/github.com/docker/docker/client/request.go
  vendor/github.com/docker/docker/client/service_create.go
  vendor/github.com/docker/docker/client/service_update.go
  vendor/github.com/docker/docker/client/volume_remove.go
  vendor/github.com/moby/moby/AUTHORS
  vendor/github.com/moby/moby/pkg/ioutils/fswriters.go
  vendor/modules.txt
Labels: approved, size/M, api-review, lgtm, jira/valid-reference

#7346 NO-ISSUE: [release-ocm-2.11] Bump OCP versions: 4.16, 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7345 NO-ISSUE: [release-ocm-2.12] Bump OCP versions: 4.18, 4.16, 4.14, 4.17
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/L, lgtm, jira/valid-reference

#7351 NO-ISSUE: change default 4.19 image according to the new path
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7347 NO-ISSUE: [release-ocm-2.10] Bump OCP versions: 4.14
  data/default_release_images.json
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/S, lgtm, jira/valid-reference

#7354 NO-ISSUE: [master] Bump OCP versions: 4.17, 4.16, 4.18
  config/manager/manager.yaml
  config/samples/agent-install.openshift.io_v1beta1_agentserviceconfig.yaml
  data/default_os_images.json
  data/default_release_images.json
  deploy/olm-catalog/manifests/assisted-service-operator.clusterserviceversion.yaml
  deploy/podman/configmap.yml
  openshift/template.yaml
Labels: approved, size/M, lgtm, jira/valid-reference

#7315 MGMT-19622: Proxy setting with special characters are ignored when minimal ISO is used
  internal/isoeditor/rhcos.go
  internal/isoeditor/rhcos_test.go
Labels: approved, size/M, lgtm, jira/valid-reference
